### ISSUE TITLE
After updating to 3.x.x getting TS2536 

### ISSUE THREAD

**Issue by pikax** [Microsoft/TypeScript#28647]
**TypeScript Version:**  typescript@3.3.0-dev.20181122

**Search Terms:**
TS2536 Record Map vuex

**Code**

```ts
interface ITest {
  expectedStr: string;
  expectedN: number;
}

interface MapAccessor<Getters> {
  <T = Getters, Map extends Record<string, keyof T> = Record<string, keyof T>>(
    map: Map
  ): { [K in keyof Map]: (() => T[Map[K]]) };
}

interface TestAccess {
  str: "expectedStr";
}

const t: MapAccessor<ITest> = {} as any;

const str = t({
  str: "expectedStr"
}).str;

```

**Expected behavior:**
No compile issue, is working using typescript@3.0.1, checked the breaking changes and found nothing in regards to this.

Intellisense still works as expected giving error if you change `expectedStr` to an invalid value.

**Actual behavior:**
Not giving error: index.ts:9:33 - error TS2536: Type 'Map[K]' cannot be used to index type 'T'.

**Playground Link:**  
[playground](http://www.typescriptlang.org/play/index.html#src=interface%20ITest%20%7B%0D%0A%20%20expectedStr%3A%20string%3B%0D%0A%20%20expectedN%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20MapAccessor%3CGetters%3E%20%7B%0D%0A%20%20%3CT%20%3D%20Getters%2C%20Map%20extends%20Record%3Cstring%2C%20keyof%20T%3E%20%3D%20Record%3Cstring%2C%20keyof%20T%3E%3E(%0D%0A%20%20%20%20map%3A%20Map%0D%0A%20%20)%3A%20%7B%20%5BK%20in%20keyof%20Map%5D%3A%20(()%20%3D%3E%20T%5BMap%5BK%5D%5D)%20%7D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20TestAccess%20%7B%0D%0A%20%20str%3A%20%22expectedStr%22%3B%0D%0A%7D%0D%0A%0D%0Aconst%20t%3A%20MapAccessor%3CITest%3E%20%3D%20%7B%7D%20as%20any%3B%0D%0A%0D%0Aconst%20str%20%3D%20t(%7B%0D%0A%20%20str%3A%20%22expectedStr%22%0D%0A%7D).str%3B%0D%0A)

**Comment by jack-williams** [comment]
This might be affected by this: #27490 (and thus working as intended).

`Map[K]` is no longer pulling in the constraint `keyof T` because both `Map` and `K` are generic.

I'd wait on a final say from someone on the team though,

**Comment by pikax** [comment]
What I find odd is the intellisense/editor picking up the correct value.

Is there a way to have the same behavior without the error?

**Comment by jack-williams** [comment]
Is your editor using an older version of tsserver?

**Comment by pikax** [comment]
I'm using VSCode and even the typescript playground it works (even with the error it resolves the correct type).

![image](https://user-images.githubusercontent.com/4620458/48937695-d825d380-ef06-11e8-8809-003d6e21093e.png)

[playground](http://www.typescriptlang.org/play/index.html#src=interface%20ITest%20%7B%0D%0A%20%20expectedStr%3A%20string%3B%0D%0A%20%20expectedN%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20MapAccessor%3CGetters%3E%20%7B%0D%0A%20%20%3CT%20%3D%20Getters%2C%20Map%20extends%20Record%3Cstring%2C%20keyof%20T%3E%20%3D%20Record%3Cstring%2C%20keyof%20T%3E%3E(%0D%0A%20%20%20%20map%3A%20Map%0D%0A%20%20)%3A%20%7B%20%5BK%20in%20keyof%20Map%5D%3A%20(()%20%3D%3E%20T%5BMap%5BK%5D%5D)%20%7D%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20TestAccess%20%7B%0D%0A%20%20str%3A%20%22expectedStr%22%3B%0D%0A%7D%0D%0A%0D%0Aconst%20t%3A%20MapAccessor%3CITest%3E%20%3D%20%7B%7D%20as%20any%3B%0D%0A%0D%0Aconst%20str%20%3D%20t(%7B%0D%0A%20%20str%3A%20%22expectedStr%22%0D%0A%7D).str%3B%0D%0A)

**Comment by ahejlsberg** [comment]
This is working as intended. A simplified example:

```ts
function f1<T, U extends Record<string, keyof T>, K extends keyof U>(obj: T, map: U, key: K) {
    return obj[map[key]];  // Error
}
```

Here, `U` is constrained to an object type where properties with `string` names are constrained to `keyof T`. However, it is possible for an instantiation to supply a type argument for `U` that has properties with symbol names which aren't constrained in any way. Therefore `U[K]` isn't known to be constrained to `keyof T`.

Changing the constraint of `U` to an object type where _all_ properties are constrained to `keyof T` does indeed work:

```ts
function f2<T, U extends Record<keyof U, keyof T>, K extends keyof U>(obj: T, map: U, key: K) {
    return obj[map[key]];  // Ok
}
```

**Comment by jack-williams** [comment]
Yep, so it seems like I was _completely_ wrong on this one. The mistake I made was that the PR I linked to only concerned the case when relating _to_ an indexed access type; this example is about relating _from_ an indexed access type. Subtle, but wrong. Sorry!

**Comment by weswigham** [comment]
cc @DanielRosenwasser to double-check that we're documenting this break in the 3.2 (? I think that's the first) release.

**Comment by pikax** [comment]
Sorry to comment on a closed issue, is this suppose to happen:

```typescript

interface MyGetter {
    vstring : string,
    vnumber: number,

    vhidden: boolean;
}
declare interface TestGeneric<Getters> {
    <Map extends Record<string, keyof Getters>>(map: Map) : { [K in keyof Map]: Getters[Map[K]]}; 
}

declare interface TestSpecific {
    <Map extends Record<string, keyof MyGetter>>(map: Map): { [K in keyof Map]: MyGetter[Map[K]]}
}

declare const genericInterface: TestGeneric<MyGetter>;
declare const speficInterface: TestSpecific;

declare const generic = genericInterface({
    testString: 'vstring',
    testNumber: 'vnumber'
});
declare const specific = speficInterface({
    testString: 'vstring',
    testNumber: 'vnumber'
}); 


generic.testNumber; //number
specific.testNumber; // number

generic.testString; // string
specific.testString; //string
```

`TestGeneric` is getting a compile error but `TestSpecific` doesn't, shouldn't the type be correct?
