### PR TITLE
Defer generic awaited type

### LINKED ISSUE #22469: Suggestion: Allow array of > 10 values in argument of Promise.all() and Promise.race()
Currently, Promise.all() and Promise.race() both have signatures like this:
```typescript
all<T1>(values: [T1 | PromiseLike<T1>]): Promise<[T1]>;
// ...
all<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>, T4 | PromiseLike <T4>, T5 | PromiseLike<T5>, T6 | PromiseLike<T6>, T7 | PromiseLike<T7>, T8 | PromiseLike<T8>, T9 | PromiseLike<T9>, T10 | PromiseLike<T10>]): Promise<[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]>;
```
While this is suitable in most cases, occasionally there is a need (or preference) to wait on the retrieval of several (10+) dependencies and then access them all within a single block.

Workarounds for Promise.all() certainly exist (i.e. splitting into multiple Promise.all() calls) - but code can become unnecessarily complex. Workarounds for Promise.race() are not as easy.

Since actual implementations of Promise.all() and Promise.race() are boundless, it would be helpful if  lib.es2015.promise.d.ts reflected a wider range of plausible use cases.

**Proposed solution:**
Add overloads to lib.es2015.promise.d.ts - using the pattern it already uses today - to support ~20 items instead of ~10.

### LINKED ISSUE #28427: when has optional elements in tuple types, Promise.all has error
**TypeScript Version:**  3.1.3

**Search Terms:**
Promise.all, optional elements in tuple types

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const arr: [Promise<number>, Promise<string>?] = [
  Promise.resolve(1)
];

arr[1] = Promise.resolve('1');

Promise.all(arr);    // Error

// or

const arr2: Array<Promise<number> | Promise<string>> = [Promise.resolve(1)];
arr2.push(Promise.resolve('1'));

Promise.all(arr2);   // Error
```

**Expected behavior:**

`Promise.all(arr)` should be correct 

**Actual behavior:**

### LINKED ISSUE #30390: 3.4 regression for type argument inference
Found trying to compile VS Code at https://github.com/Microsoft/vscode/blob/1ce2b64abb08ed7998a5a6697ba0248a51934605/src/vs/workbench/services/textfile/common/textFileService.ts#L294-L338

Isolated repro:

```ts
function blah(): Promise<{ success: boolean }> {
    return Promise.resolve(100).then(() => {
        if (Math.random()) {
            return {
                success: true
            }
        }
        return Promise.resolve({ success: false })
    })
}
```

### LINKED ISSUE #31722: [3.5.1] Iterable is missing in lib.es2015.promise.d.ts
**TypeScript Version:**  
* 3.5.1
* 3.6.0-dev.20190601

**Search Terms:** async, await, polyfill, csproj, TypeScriptLib 

**Code**

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "none",
    "lib": ["dom", "es5", "es2015.promise"],
    "strict": true,
  }
}
```

a.ts
```
// empty
```

**Expected behavior:**
```
> npx typescript@3.4.5
// ok
```

**Actual behavior:**
```
> npx typescript@3.5.1
../path/typescript/lib/lib.es2015.promise.d.ts:129:21 - error TS2304: Cannot find name 'Iterable'.

129     race<T>(values: Iterable<T>): Promise<T extends PromiseLike<infer U> ? U : T>;
                        ~~~~~~~~


Found 1 error.
```

**Playground Link:** None

**Related Issues:** Not found.

**Workaround:**
Add "es2015.iterable" to lib

### LINKED ISSUE #33559: new readonly modifiers on Promise.all break lyricist in DT
Broken by #33057 

1. clone dt
2. cd ~/dt/types/lyricist
3. tsl
4. error on `const songsByArtist: SongByArtist[] = results[5];

```ts
Promise
    .all([
        lyricist.album(1, { fetchTracklist: true, textFormat: LyricistTextFormat.PLAIN }),
        lyricist.artist(1, { textFormat: LyricistTextFormat.PLAIN }),
        lyricist.artistByName('any_artist', { textFormat: LyricistTextFormat.PLAIN }),
        lyricist.search('any_song'),
        lyricist.song(1, { fetchLyrics: true, textFormat: LyricistTextFormat.PLAIN }),
        lyricist.songsByArtist(1, { page: 1, perPage: 10, sort: 'asc' }),
    ])
    .then((results) => {
        const album: Album = results[0];
        const artist: Artist = results[1];
        const artistByName: Artist = results[2];
        const searchResult: SearchResult[] = results[3];
        const song: Song = results[4];
        const songsByArtist: SongByArtist[] = results[5];

        console.log('album', album.name);
        console.log('artist', artist.name);
        console.log('artistByName', artistByName.name);
        console.log('searchResult length', searchResult.length);
        console.log('song', song.title);
        console.log('songsByArtist length', songsByArtist.length);
    });
```

**Expected behavior:**
No error, and `results[5]: SongByArtist[]`

**Actual behavior:**
Error, and `results[5]: SearchResult[]`

The two types are VERY similar, although I'm not sure that's relevant. My guess is that it's a very subtle inference problem.

### LINKED ISSUE #33562: tsc 3.6.3: `Promise.all` breaks with some union type
**TypeScript Version:**  3.6.3

**Search Terms:** promise all

**Code**

```ts
type MaybePromise<T> = T | Promise<T> | PromiseLike<T>

function MaybePromise<T>(value: T): MaybePromise<T> {
    return Promise.resolve(value)
}

async function main() {
    let aaa: number
    let bbb: string
    [
        aaa,
        bbb,
    ] = await Promise.all([
        MaybePromise(1),
        MaybePromise('2'),
        MaybePromise(true),
    ])
}
```

tsconfig:

```json
{
  "compilerOptions": {
    "strict": true,
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "es6"
    ]
  }

```

**Expected behavior:**

Code should compile without errors.

**Actual behavior:**

Error:

```
test.ts:11:9 - error TS2322: Type 'number | Promise<1>' is not assignable to type 'number'.
  Type 'Promise<1>' is not assignable to type 'number'.
test.ts:12:9 - error TS2322: Type 'string | Promise<"2">' is not assignable to type 'string'.
  Type 'Promise<"2">' is not assignable to type 'string'.
```

Code compiles well with 3.5.3, but not 3.6.3 nor 3.7.0-dev.20190922.

**Playground Link:** 

Weirdly enough, on the playground the return value of `Promise.all` is not a tuple but a list.

https://www.typescriptlang.org/play/#code/C4TwDgpgBAsghiARhACgJwPYFsCWBnCAHgBUA+KAXimKgB8p1t8iy6HNcCAZHAaxdIAoQQDMArgDsAxsBwYJsBMkacBACgBucADZiIALmoBKQ-CSoOzEuQDegqA6hoIwMWgUrmAOmd4M2jQhNHT0jQQBfYTg8EGkocWlZeSgsOBwJNSMoO0cobRcoOCLDCTEsZDR7R3zgKER6wzxgNHSAcyqHAG0O3MKigBoe3PrEQdyAXUpCgHc02s8CLx1tNW7exzNlSwI1AEYjMfXFcwWggHIAJjODoY2lCyYd5tDDh3GwyKA

**Related Issues:** 

- ~~Maybe related? https://github.com/microsoft/TypeScript/issues/33559~~

### LINKED ISSUE #33752: 3.7-beta regression: Promise.all wrongly adds `undefined` type
**TypeScript Version:**  3.7.0-beta

**Search Terms:**

promise all

**Code**

```ts
interface A {
  a: string
}
interface B {
  b: string
}
async function main(): Promise<A> {
  const [a, b] = await Promise.all([
    Promise.resolve({a: "a"} as A),
    Promise.resolve({b: "b"} as B | undefined), // <- the `| undefined` here is the problem
  ]);
  return a; // <- a has type `A | undefined`, but should be `A`
}
```

**Expected behavior:**

This is a regression from 3.6.3, where the return tuple of `Promise.all` is correctly inferred.

**Actual behavior:**

A `| undefined` bound of a different tuple member also adds a `| undefined` bound on a different unrelated return value of `Promise.all`.

**Playground Link:** 

https://www.typescriptlang.org/play/?ts=3.7-Beta#code/JYOwLgpgTgZghgYwgAgILIN4ChnLgLmQGcwpQBzLAXy1ElkRQCFMdkAjQkskSmuIgE8QCZDACuIsMAD2IZAFs4oABQBKQgAUoMhcCIQAPKgB8rXAjklkAbTgAaDgF1kAXjwB3ZWGTbd+iAA6OAAbEJUbNlw-PQNAqAgiGRCANwgVDAJkACI4bKo8IjQ1eyjfHVighKTU9IxOHPZ8wuQWAB9kSQATCBhQCC6S5AB6YeRDAFpkMAALFAADDu7e-q755DmE5H1pueQABx12EIgFNic1AG42BLBxKHk4S5GxybwNgWnBfYX0JZAen0QAN5o52OIfEQZjJxCEuhxfvNqEA

**Related Issues:** 

Maybe https://github.com/microsoft/TypeScript/pull/33707 ?

### LINKED ISSUE #34924: A second argument in Promise.all([...]) that returns a Record breaks the return signature
**TypeScript Version:** 

3.7.2

**Search Terms:**

Promise.all, Record

**Code**

```typescript
interface MoviesResponse {
    movies: [];
}

type CharactersResponse = Record<number, any>;

const getMovies = async (): Promise<MoviesResponse> => ({
    movies: [],
})

const getCharacters = async (): Promise<CharactersResponse> => ({
});

(async () => {
    const [{ movies }, characters] = await Promise.all([getMovies(), getCharacters()]);
    console.log(movies, characters);
})();
```

**Expected behavior:**

The first variable in the deconstructed array should be correctly typed as `MoviesResponse`, rather than `CharactersResponse`. This worked in 3.6.4.

**Actual behavior:**

Both variables in the deconstructed array are inferred to be `CharactersResponse`. So when I try to deconstruct the first argument doing `{ movies }`, it's an invalid destructuring.

Interestingly, if we update `CharactersResponse` to not be a map type, the problem goes away, e.g:

```
interface CharactersResponse {
    characters: any[];
}
const getCharacters = async (): Promise<CharactersResponse> => ({
    characters: [],
});
```

**Playground Link:**

http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=6#code/JYOwLgpgTgZghgYwgAgLIHsBuwIGcBKeADuiLigN4BQytyAtljrgFzIDaAugNxUC+VKmACeRFAGEAFnCiJIUAsVLlkAXmSEE6KABMAPCACu9AEbQANMjghhAPl5UtZMMgDmEMBmx41V3MJAEZAAKAEo2AAUodHpgcj0vZkJcEjIIWzUM4Oo6BiY8Ni5zflDBJ1wXdzApGTloXF84f0CQ8OQomLiIPRrZBHlFFOV0zJDqPlCHYKaAoLDRnLpyl3YKPO8GvksEaT6BzkaAdzhgFw7Y8gA6OAAbG+D2KsS8MMsq3rqFMM5JmiXldA3CCXG7oVzBRgbba7T64X4TMLcIA

**Related Issues:**

None found.

### LINKED ISSUE #34937: 3.7.2 Promise.all does infers base type of interfaces rather than actual interface
**TypeScript 3.7.2**
[Playground link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgIoFcD2kBiwA2kUyA3gFDKXID6wAJgFzIDOYUoA5gNxkC+ZZUEXhI0WXASIBBOgDc4IJHWQQAHpBB1mY7BDyFopClRBwAthCat2IbnwEx0isMEwhkHCGAy79RZgAUAJRMAApQmGbAzBAAPD4SBlAA2gC6AHxGVMhQXuhQ7iAQAO7I4ZHRcQl6ktBp6QHG2ZQBucyY+LIQADQ5EABWEAhgQcgAvJnkzdN97Z0QAclNM80kNPRMAOQAKhCsm8j8K9mpQTwrvGf2ZI7Oru6e3uI1Scwy8ooQdMFhEVEx8Wefmg7wUSnqWSouTA+UKJTKf0qgN8tSgoM+dHqjRWrT2HS6vVyg2GowmkOOs3xCyWFNW60YyB2ezAm16pgsW12+0OyxWp3OM0uPH4ZDgzAAnopguNJssEG5WMhkjBUcxenA5GCvqlxsg4MU4MAwAiKjEAHRwfD4Ra8qiParAqCBILdW2Ue1A1XopTBZb8vhAA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
interface QuoteFilter {
    _id: string;
}

interface QuoteFilterAdvanced extends QuoteFilter {
    name: string;
}

function getQuoteFilters(): Promise<QuoteFilter[]> {
    return new Promise<QuoteFilter[]>(
        (resolve, reject) => {
            resolve([
               { _id: 'Test' }
            ]);
        });
}

function getQuoteFiltersAdvanced(): Promise<QuoteFilterAdvanced[]> {
    return new Promise<QuoteFilterAdvanced[]>(
        (resolve, reject) => {
            resolve([
               { _id: 'Test', name: 'Test' }
            ]);
        });
}

async() => {
    const [filters, advanced] = await Promise.all([
        getQuoteFilters(),
        getQuoteFiltersAdvanced()
    ]);
}
```

**Output:**
```javascript
"use strict";
function getQuoteFilters() {
    return new Promise((resolve, reject) => {
        resolve([
            { _id: 'Test' }
        ]);
    });
}
function getQuoteFiltersAdvanced() {
    return new Promise((resolve, reject) => {
        resolve([
            { _id: 'Test', name: 'Test' }
        ]);
    });
}
async () => {
    const [filters, advanced] = await Promise.all([
        getQuoteFilters(),
        getQuoteFiltersAdvanced()
    ]);
};

```

**Expected behavior:**
I am expecting the advanced variable to be an array of QuoteFilterAdvanced rather than QuoteFilter.

This was correctly inferred in Typescript 3.6.3

### PR DESCRIPTION
**Pull request by jablko**
Roll up ~#33062~, #33074, ~#33103~, ~#33105~, #33707 and #35284

Fixes ~#27711~
Fixes #22469
Fixes #28427
Fixes ~#30390~
Fixes #31722
Fixes #33559
Fixes #33562
Fixes #33752
Fixes ~#34924~
Fixes #34937
Fixes ~#35136~
Fixes ~#35258~

@typescript-bot test this
@typescript-bot run dt
@typescript-bot user test this

### CODE REVIEW

**Comment by orta** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by orta** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by orta** [comment]
Looks like most of that diff is just file number changing

There is [a few errors](https://github.com/jablko/TypeScript/pull/6/files#diff-d695a847eac7045aa1b78c59764cdd21R8) though [at this location](https://github.com/xtermjs/xterm.js/blob/master/test/api/TestUtils.ts#L16) - which I think could be correct. Does that feel right?

**Comment by orta** [comment]
Relates to https://github.com/microsoft/TypeScript/pull/35998

File: src/lib/es5.d.ts [hunk 1]
```diff
@@ -1378,7 +1378,12 @@ declare type PropertyDecorator = (target: Object, propertyKey: string | symbol)
 declare type MethodDecorator = <T>(target: Object, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<T>) => TypedPropertyDescriptor<T> | void;
 declare type ParameterDecorator = (target: Object, propertyKey: string | symbol, parameterIndex: number) => void;
 
-declare type PromiseConstructorLike = new <T>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void) => PromiseLike<T>;
+// The undefined case is for strictNullChecks false, in which case
+// undefined extends PromiseLike<infer U> is true, which would otherwise
+// make Awaited<undefined> -> unknown.
+type Awaited<T> = T extends undefined ? T : T extends PromiseLike<infer U> ? U : T extends { then(...args: any[]): any } ? unknown : T;
```
Comment (ExE-Boss) [inline src/lib/es5.d.ts]:
```suggestion
type Awaited<T> = T extends undefined ? T : T extends PromiseLike<infer U> ? U : T extends { then: Function } ? unknown : T;
```

Comment (jablko) [reply src/lib/es5.d.ts]: :+1: Works, thanks for your help! Done. :heavy_check_mark:

**Comment by jablko** [comment]
@orta Fixed. Thanks! Would you mind re-triggering @typescript-bot, please?

**Comment by orta** [comment]
👍 
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by orta** [comment]
These baselines look alright to me - https://github.com/jablko/TypeScript/pull/7

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -29379,98 +29383,22 @@ namespace ts {
...
-                    return undefined;
-                }
-
-                return typeAsAwaitable.awaitedTypeOfType = getUnionType(types);
+            const symbol = getGlobalAwaitedSymbol(/*reportErrors*/ false);
+            if (!symbol) {
+                return typeAsAwaitable.awaitedTypeOfType = type;
             }
 
-            const promisedType = getPromisedTypeOfPromise(type);
```
Comment (rbuckton) [inline src/compiler/checker.ts]: I don't agree with this change. This completely removes support for recursively unwrapping a non-native promise, which is a core capability of `await` and our type-system support for it which has existed since the feature was added.

Comment (jablko) [reply src/compiler/checker.ts]: Can a non-native promise resolve to another promise? If not, then `await` isn't recursive and I think this change is safe?

If it can, then I concede that implies a [recursive awaited solution](https://github.com/microsoft/TypeScript/pull/35998).

Comment (ExE-Boss) [reply src/compiler/checker.ts]: Well, non‑native&nbsp;promises can&nbsp;resolve to&nbsp;an&nbsp;object with&nbsp;a&nbsp;`.then` function&nbsp;property, which&nbsp;`await` will&nbsp;resolve&nbsp;recursively.

Comment (jablko) [reply src/compiler/checker.ts]: Wouldn't that violate [Promises/A+](https://promisesaplus.com)?

Comment (rbuckton) [reply src/compiler/checker.ts]: @jablko: non-native promise-like implementations aren't all guaranteed to be Promise/A+. In the past, JQuery's `defer` created something promise-like (i.e. it has a callable `then` that accepted fulfill/reject callbacks), but it did *not* recursively unwrap. This is why native `await` and native `Promise` both recursively unwrap (to defend against non-Promise/A+-compliant promise-likes)

Comment (rbuckton) [reply src/compiler/checker.ts]: `await` *is* recursive for non-native promises. In https://tc39.es/ecma262/#await, the value is passed to [`PromiseResolve`](https://tc39.es/ecma262/#sec-promise-resolve) which adopts the foreign promise and performs recursive unwrapping.

Comment (jablko) [reply src/compiler/checker.ts]: Thanks! I concede that `await` is recursive for non-compliant promises, however there's only ever been incomplete support for non-compliant promises in TypeScript. TypeScript's native promise type hasn't recursively unwrapped non-compliant promises until [now](https://github.com/microsoft/TypeScript/pull/35998).

In practice, do non-compliant promises justify introducing a new kind of type? For native and A+-compliant promises, `await` isn't recursive because they can't be nested.

Is it more likely that an instance of a non-compliant promise is actually an error? Supporting non-compliant promises can be [error prone](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41960), by masking what would otherwise be errors.

**Comment by sandersn** [comment]
This PR hasn't seen any activity for quite a while, so I'm going to close it to keep the number of open PRs manageable. Feel free to open a fresh PR or continue the discussion here.
