### PR TITLE
Fix contextually typed parameter issues

### LINKED ISSUE #28816: literal function with structure spread can't be rightly inferred in function's generic type slot
**TypeScript Version:**  3.2.1

**Search Terms:**

strucutre spread + generic

**Code**

```ts
function id<T>(input: T): T { return input }

function getFoo ({ foo = 42 }) {
  return foo
}

const newGetFoo = id(getFoo)
const newGetFoo2 = id(function getFoo ({ foo = 42 }) {
  return foo
})
```

**Expected behavior:**

newGetFoo and newGetFoo2 should have the same signature

**Actual behavior:**

`newGetFoo` is:
```ts
({ foo }: {
    foo?: number | undefined;
}) => number
```

but `newGetFoo2` is
```ts
 ({ foo }: any) => number
```

**Playground Link:** 
http://www.typescriptlang.org/play/index.html#src=function%20id%3CT%3E(input%3A%20T)%3A%20T%20%7B%20return%20input%20%7D%0A%0Afunction%20getFoo%20(%7B%20foo%20%3D%2042%20%7D)%20%7B%0A%20%20return%20foo%0A%7D%0A%0Aconst%20newGetFoo%20%3D%20id(getFoo)%0Aconst%20newGetFoo2%20%3D%20id(function%20getFoo%20(%7B%20foo%20%3D%2042%20%7D)%20%7B%0A%20%20return%20foo%0A%7D)%0A

**Related Issues:**

### LINKED ISSUE #30840: Case that infering type for parameters works for 3.3.0 but error in 3.4.0
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:**

3.4.0 regression
parameter type infer

**Code**

```ts
// with compilerOptions.noImplicitAny=true in tsconfig.json
export function test<S>(options: { partial: Partial<S> | undefined }) {
  const fn: any = function (state = options.partial, action_: any) {
    return state
  }
  return fn
}
```
The related tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": ["src"]
}
```

**Expected behavior:**
No error. It's worth noting that it works in 3.3.4.

**Actual behavior:**

With the `tsc` command line, it outputs the following errors:

```
error TS7006: Parameter 'state' implicitly has an 'any' type.

25   const fn: any = function(state = options.partial, action_: any) {
```

**Playground Link:** 

**Related Issues:** 

<hr />

The code works in 3.3.4 with no errors, but after upgrading to 3.4.0, the tsc complains that the parameter has 'any' type when the __LHS__ `fn` is of any type. If I replace `fn: any = ` with `fn =`, it works for 3.4.0.

### LINKED ISSUE #36052: Incorrect type inferrence for default-initialized parameters and noImplicitAny
Having a default initialized parameter in a function declaration passed to a function incorrectly asserts that the parameter is an `any` type

**TypeScript Version:**  
3.7.4 (also reproduced on Nightly)
I recently upgraded from Typescript 3.5.2 to 3.7.3. The code below was fine with ts 3.5.2

**Search Terms:**
default parameter noImplicitAny
**Code**

```ts
function execute(script: string | Function): Promise<string> {
  return new Promise((resolve, reject) => {
    if (typeof script === 'string') {
      reject('rejecting promise');
    }
    resolve('resolving promise');
  });
}

export function executeSomething() {
  return execute((root: HTMLElement, debug = true) => {
    if (debug) {
      root.innerHTML = '';
    }
  });
}
```

**Expected behavior:**
No Errors

**Actual behavior:**
I get an error for the `debug = true` statement. "TS7006: Parameter 'debug' implicitly has an 'any' type."

**Playground Link:** 
[Playground link](http://www.typescriptlang.org/play/?ts=3.8.0-dev.20200104#code/GYVwdgxgLglg9mABAUwB7IiKyAUBnCAJxgAcoAuRPKYsAc0QB9EAxcaeMASkoAVC4AWxh5kAHmq06APkQBvAFCJEhZFBCEkYZAHdE-ISNw5VeOABsAbsgA0K5ACsMULogC8sxcuUxgiHFAAniTIcH4ExGTubm6IAOSSMPRxrl7eyqpO0Dhxmc5JDCQCwqIpANxK3gC+lRnIZla4ufUWlgWIRYalXBXKVT0KNQpoJHCEUIigkLAIKOiY2ADKQmoAFgU4qZWq6ppzGFjGAnAUiAASACoAsgAyAKLmyILIYFB2ACbIAEYgDLE0IGQrg88lqiF8-k+PzoW3SGTgJwAdEltIRLrd3PE4r1qpV+hUqkA)

**Related Issues:** 
None

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes multiple issues related to contextually typed parameters:

* Previously we'd consider a parameter of a function expression, arrow function, or object literal method to be contextually typed if *any* contextual type could be found for the function. We now consider a parameter to be contextually typed only if the contextual type of the function provides a call signature and that call signature has a parameter in the corresponding position.
* Previously,  in `checkFunctionExpressionOrObjectLiteralMethod`, we'd only assign types to contextually sensitive parameters if a contextual type was found. We now *always* assign types to contextually sensitive parameters, thus also recording the fact that there was no contextual type. This matters because different phases of overload resolution may change the contextual type, causing inconsistent results depending on when the type of a parameter is resolved. For example, we might see different types in quick info vs. batch compilation.

Some examples:

```ts
const f1 = (x = 1) => 0;  // x: number
const f2: any = (x = 1) => 0;  // x: number (previously implicit any error)
const f3: unknown = (x = 1) => 0;  // x: number (previously implicit any error)
const f4: Function = (x = 1) => 0;  // x: number (previously implicit any error)
const f5: (...args: any[]) => any = (x = 1) => 0;  // x: any
const f6: () => any = (x = 1) => 0;  // x: number (previously any)
const f7: () => any = (x?) => 0;  // Implicit any error (previously any and no error)
const f8: () => any = (...x) => 0;  // x: []

declare function memoize<F extends Function>(func: F): F;

// Type (x: number, y?: number) => number
const add = (x: number, y = 0): number => x + y;

// Type (x: number, y?: number) => number
const memoizedAdd1 = memoize(add);

// Type (x: number, y?: number) => number (previously implicit any error on y)
const memoizedAdd2 = memoize((x: number, y = 0): number => x + y);
```

Related to this PR, I discovered an issue caused by #25937 and #31574:

```ts
declare function foo<T>(obj: T, settings: (row: T) => { value: string, func?: Function }): void;

foo(new Error(),
    o => ({
        value: o.name,
        func: x => 'foo'
    })
);
```

Above, hovering over the call to `foo` correctly shows `T` was inferred as `Error`, but hovering over `o` shows type `any` because of a circularity error (which isn't displayed by quick info). The issue is caused by code in #31574 that I have now removed. Furthermore, I have restricted the functionality introduced by #25937 to only kick in for parameterless arrow functions (because the functionality is safe only so long as there are no parameters that can be referenced in the return type).

Fixes #28816.
Fixes #30840.
Fixes #36052.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
RWC tests look good (two implicit any errors disappeared in favor of actual types). DT tests are clean. Community tests show a new error in `webpack` which is correct (type annotations appear to be wrong).

**Comment by weswigham** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -26430,14 +26420,14 @@ namespace ts {
...
-        function checkFunctionExpressionOrObjectLiteralMethod(node: FunctionExpression | MethodDeclaration, checkMode?: CheckMode): Type {
+        function checkFunctionExpressionOrObjectLiteralMethod(node: FunctionExpression | ArrowFunction | MethodDeclaration, checkMode?: CheckMode): Type {
             Debug.assert(node.kind !== SyntaxKind.MethodDeclaration || isObjectLiteralMethod(node));
             checkNodeDeferred(node);
 
             // The identityMapper object is used to indicate that function expressions are wildcards
             if (checkMode && checkMode & CheckMode.SkipContextSensitive && isContextSensitive(node)) {
                 // Skip parameters, return signature with return type that retains noncontextual parts so inferences can still be drawn in an early stage
-                if (!getEffectiveReturnTypeNode(node) && hasContextSensitiveReturnExpression(node)) {
+                if (!getEffectiveReturnTypeNode(node) && node.kind === SyntaxKind.ArrowFunction && node.parameters.length === 0) {
```
Comment (weswigham) [inline src/compiler/checker.ts]: This seems wrong; it does not admit annotated parameters; I see no reason why a list of annotated parameters would be treated differently than an empty parameter list when it comes to contextual-ness. Moreover, this inverts the check; rather than seeing if the return is context sensitive, this is checking if the parameters _aren't_ (almost). We have no reason to do the return type special-casing below if the return _isn't_ context sensitive (it's extra work we shouldn't do since it'll be repeated in later inference phases), so we should still be checking that the return expression is context sensitive, even if we pile on additional constraints.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -26461,14 +26451,9 @@ namespace ts {
...
 
-            const type = getTypeOfSymbol(getMergedSymbol(node.symbol));
-            if (isTypeAny(type)) {
-                return type;
-            }
-
             contextuallyCheckFunctionExpressionOrObjectLiteralMethod(node, checkMode);
 
-            return type;
+            return getTypeOfSymbol(getSymbolOfNode(node));
```
Comment (weswigham) [inline src/compiler/checker.ts]: 👍  on using `getSymbolOfNode`, but why'd we eschew the `isTypeAny` bail?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -26481,13 +26466,12 @@ namespace ts {
...
                 if (!(links.flags & NodeCheckFlags.ContextChecked)) {
                     links.flags |= NodeCheckFlags.ContextChecked;
-                    if (contextualSignature) {
-                        const type = getTypeOfSymbol(getMergedSymbol(node.symbol));
-                        if (isTypeAny(type)) {
-                            return;
-                        }
-                        const signature = getSignaturesOfType(type, SignatureKind.Call)[0];
-                        if (isContextSensitive(node)) {
+                    const signature = firstOrUndefined(getSignaturesOfType(getTypeOfSymbol(getSymbolOfNode(node)), SignatureKind.Call));
```
Comment (weswigham) [inline src/compiler/checker.ts]: The internal singleton `anyFunctionType` exists, is function-y, and lacks call signatures, no? Our checker internal `isFunctionType` helper also fails to account for this; but it definitely seems correct to do so. Maybe amending `isFunctionType` and using that here would be a good idea, rather than duplicating the check in a slightly different manner?

**Comment by weswigham** [comment]
Oh, also add a normal test and fourslash test for this:
```ts
declare function foo<T>(settings: (row: T) => { value: string, func?: Function }, obj: T): void;

foo(o => ({
        value: o.name,
        func: x => 'foo'
    }),
    new Error(),
);
```
which is to say, your example, but with inverted argument order. This PR actually fixes it; without this PR is errors on `o.name` with an `Object is of type unknown` error. We should make sure the unreported quickinfo/ordering issues have regression tests.

**Comment by weswigham** [comment]
Oof, I'd also wanna see some fourslash/type tests for
```ts
declare function foo<T extends { name: string }, U extends keyof T>(settings: (row: T) => { value: T[U], func?: Function }, obj: T, key: U): U;

function q<T extends { name: string }>(x: T): T["name"] {
    return foo(o => ({
        value: o.name,
        func: x => 'foo'
    }),
        x,
        "name"
    );
}

foo(o => ({
    value: o.name,
    func: x => 'foo'
}),
    new Error(),
    "name"
);
```
while the error behaviors are the same both with and without this PR, the signature quickinfo on both `foo` calls has very different types in each, so recording the behavior in a test seems good.

File: src/compiler/checker.ts (hunk 1 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yeah, we should permit functions with no contextually sensitive parameters.

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Because there's nothing gained from that extra code. The following code paths already ignore functions whose type turn out to be any.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [reply src/compiler/checker.ts]: The `anyFunctionType` will never be captured as the type of a symbol, so we'll never see it here.

Comment (weswigham) [reply src/compiler/checker.ts]: `checkObjectLiteralMethod` can return `anyFunctionType` when `CheckMode.SkipGenericFunctions` is set, which is called by `checkObjectLiteral` and then cached on the transient member symbol we produce directly as the type.

So yea, we can totally see it as the type of a symbol.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I'm not sure what we're debating here. I think the code to extract the signature is fine as is, I'm not getting what change you want and why?

Comment (weswigham) [reply src/compiler/checker.ts]: From our discussion in person: Because the symbol is a binder symbol (or merge/late bound symbol) of a method, it'll never have a type affixed directly to it by `checkObjectLiteral` (it'll clone the symbol first); so the only way it could happen would be if the `anyFunctionType` leaked out of an inference phase via another cache, which we'd consider a bug regardless, so it _probably_ doesn't need to be accounted for here, assuming the invariants around symbols which we expect to be upheld are.
