### PR TITLE
Exclude special index signature rule from strict subtype relation

### LINKED ISSUE #53379: Assertion function & Type guards for Record types broken on 5.0
### 🔎 Search Terms
* asserts
* assertion function
* type guard
* record

### 🕗 Version & Regression Information

Worked on 4.9, broken since 5.0 

Probably introduced by #52984

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXywGcB5AIwCtwMAKHALnjQGtUcB3VASgZwMPgBK4HDGAAeQhhhZUAcwA08KKgCeAPgBQG0JFgIU6bHiWFCIGBjKVMtBs1YduJsxf68ig4aIlSZCpapq8PBaECAY8ABuUBDIIAwA3gC+8AC88KjIEBAAhADcGliI1ERWVNTRsSCcnPAJGsHBlXEAdMoqGAAWfvAA9L3w5jAi8IQyYAgArC0ADC0ATBpJWlCm5pYU5c3VWtttql09-YMwwzCj41OzC0A)

### 💻 Code

```ts
declare function isObject(o: unknown): o is Record<string, any>

declare function assertObject(o: unknown): asserts o is Record<string, any>  

let value: {} = null!;
if(isObject(value)) {
    value.anything // error since 5.0.2
}

assertObject(value)

value.anything // error since 5.0.2
```

### 🙁 Actual behavior

`Property 'anything' does not exist on type '{}'.(2339)`

### 🙂 Expected behavior

No error, narrowing / assertion should work fine.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #53379.

### CODE REVIEW

**Comment by ahejlsberg** [comment]
Tests and performance are unchanged, except for a new error in `typeorm`. In that code, `FindOptionsWhere<any>` is resolved to `{ [x: string]: any }`. The error is caused by the fact that `any[]` is no longer a strict subtype of `{ [x: string]: any }`, so the type in the false branch becomes `any[] | FindOptionsWhere<any>`, correctly revealing that `where` might be a zero length array in the false branch. So, new error seems entirely reasonable.

**Comment by DanielRosenwasser** [comment]
@typescript-bot pack this

**Comment by DanielRosenwasser** [comment]
@ahejlsberg sounds like what you're saying is that TypeORM is supposed to still handle the 0-length case, and can do so by

Would you be able to add an equivalentish test case to document this?

```ts
function foo(obj: Record<string, any> | Record<string, any>[]) {
    if (Array.isArray(obj) && obj.length) {
        for (let key in obj) {
            if (obj[key] !== undefined) {
                console.log(obj[key])
            }
        }
    }
    else {
        for (let key in obj) {
            if (obj[key] !== undefined) {
                console.log(obj[key])
            }
        }
    }
}

function bar(obj: Record<string, any> | Record<string, any>[]) {
    if (Array.isArray(obj)) {
        for (let key in obj) {
            if (obj[key] !== undefined) {
                console.log(obj[key])
            }
        }
    }
    else {
        for (let key in obj) {
            if (obj[key] !== undefined) {
                console.log(obj[key])
            }
        }
    }
}
```

**Comment by DanielRosenwasser** [comment]
Confirmed in the test playground that `foo` has errors, but `bar` is fine.

**Comment by DanielRosenwasser** [comment]
I've made the tests, I'm running a task to update the baselines.

**Comment by DanielRosenwasser** [comment]
the heck?

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-5.0

**Review by DanielRosenwasser — APPROVED** [review]
