### ISSUE TITLE
Typescript 4.5.5 parsing error on [I don't know what to call this issue]

### ISSUE THREAD

**Issue by bigopon** [microsoft/TypeScript#48130]
# Bug Report

For the following repro

https://www.typescriptlang.org/play?ts=4.4.4#code/FAFwngDgpgBAYgVwHYGMAKAnA9hAcgQwFsoBnAHgBUA+GAXhgG9gYYBtAaRgEskYBrKGCwAzGBQC6ALhicoADxBQkAExIwA5CixISIDAhQgsGdTAD8MJFABuUDDGkUO4mPMUq1ACk8A6P-gwAcxJpfCQwAEo6GjDI8xkHSxs7AG5gAF9WASFRCTT5CGMQGHBoGAAZLmEoFDAUABsoAAksLD5KADUuKAB3AFksZSh6gBoxdkFXBSVVeGR0bDwiUk7u-sHhqipmOhgyWWmPMS7egaH61goJsHEqT2tCRxP187G-HwDg6TQA5cUMcjsKhRWg0ABKUBACAwSAokCg+yoKSAA

code:
```ts
type FuncPropNames<T> = {
  [K in keyof T]: K extends 'constructor' ? never : T[K] extends ((...args: any) => any) ? K : never;
}[keyof T];
export type LifecycleHook<TViewModel, TKey extends FuncPropNames<TViewModel>>
  = <K extends TViewModel[TKey]>(vm: TViewModel, ...args: Parameters<K>) => ReturnType<K>;
```

It works fine in typescript 4.4, but throws in 4.5, 4.6

### 🔎 Search Terms

N/A since I'm not sure how to describe it.

### 🕗 Version & Regression Information

4.5.5

It's not fixed in nightly.

- This is a crash
- This changed between versions 4.4.4 and 4.5.5
- 
### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=4.4.4#code/FAFwngDgpgBAYgVwHYGMAKAnA9hAcgQwFsoBnAHgBUA+GAXhgG9gYYBtAaRgEskYBrKGCwAzGBQC6ALhicoADxBQkAExIwA5CixISIDAhQgsGdTAD8MJFABuUDDGkUO4mPMUq1ACk8A6P-gwAcxJpfCQwAEo6GjDI8xkHSxs7AG5gAF9WASFRCTT5CGMQGHBoGAAZLmEoFDAUABsoAAksLD5KADUuKAB3AFksZSh6gBoxdkFXBSVVeGR0bDwiUk7u-sHhqipmOhgyWWmPMS7egaH61goJsHEqT2tCRxP187G-HwDg6TQA5cUMcjsKhRWg0ABKUBACAwSAokCg+yoKSAA

### 💻 Code

```ts
type FuncPropNames<T> = {
  [K in keyof T]: K extends 'constructor' ? never : T[K] extends ((...args: any) => any) ? K : never;
}[keyof T];
export type LifecycleHook<TViewModel, TKey extends FuncPropNames<TViewModel>>
  = <K extends TViewModel[TKey]>(vm: TViewModel, ...args: Parameters<K>) => ReturnType<K>;
```

### 🙁 Actual behavior

in the `Parameters<K>`, `TKey` is turned into `string` type instead of `FuncPropNames<TViewModel>` 

### 🙂 Expected behavior

Not sure, but it used to "work".

**Comment by Sayan751** [comment]
This can also be reproduced in the following rudimentary example:

```typescript
export type MethodNames<TObject> = { [Method in keyof TObject]: TObject[Method] extends Function ? Method : never }[keyof TObject];
export type PickOnlyMethods<TObject> = { [Method in MethodNames<TObject>]: TObject[Method] };
export type MethodParameters<TObject, TMethod extends MethodNames<TObject>> = Parameters<PickOnlyMethods<TObject>[TMethod]>;
```
Although it works in TS 4.4.4, TS 4.5.5 onwards following compilation error is generated

```shell
Type 'TObject[TMethod]' does not satisfy the constraint '(...args: any) => any'.
  Type 'TObject[MethodNames<TObject>]' is not assignable to type '(...args: any) => any'.
    Type 'TObject[TObject[keyof TObject] extends Function ? keyof TObject : never]' is not assignable to type '(...args: any) => any'.
      Type 'TObject[keyof TObject]' is not assignable to type '(...args: any) => any'.
        Type 'TObject[string] | TObject[number] | TObject[symbol]' is not assignable to type '(...args: any) => any'.
          Type 'TObject[string]' is not assignable to type '(...args: any) => any'.
```

Here is the link to the playground: https://www.typescriptlang.org/play?ts=4.5.5&ssl=3&ssc=125&pln=1&pc=1#code/KYDwDg9gTgLgBDAnmYcCywYAsIBMByAhgLbADOAPACoDyARgFbADGMAfHALxwDecA2hmx44ASwB2cANbBEEAGZxajFjAC6ALiX0mrQZhy41cUDGDjcZOADEAruNaiIkgPzoDIreOAA3YFDgAX34ZOUVlXXUAbgAoUEhYBGRUAAVRZikacQAbRCFDSgjVDm4+fWFcMUl8vCJSQp1izW0VPRqjINj46HgkFHcKlMIoEkx-BtaYABoldpMQMwsrdrryakbWNhK4IZHSMyhKNIys3PaJyLZ+Kna1NiigA

**Comment by Sayan751** [comment]
Funnily enough, it can be noted that the `MethodParameters` as shown in my last comment do work even after TS error.

```typescript
class Foo {
    p1: number = 1;
    m1(_a1: string) { }
    m2(_a1: number, _a2: string) { }
}

let a: MethodParameters<Foo, 'm1'> = ['1'];     // works
let a2: MethodParameters<Foo, 'm1'> = ['1', 1]; // shows expected error
let a3: MethodParameters<Foo, 'm2'> = [1, '1']; // works
```

Playgorund: https://www.typescriptlang.org/play?ts=4.5.5&ssl=23&ssc=48&pln=20&pc=1#code/KYDwDg9gTgLgBDAnmYcCywYAsIBMByAhgLbADOAPACoDyARgFbADGMAfHALxwDecA2hmx44ASwB2cANbBEEAGZxajFjAC6ALiX0mrQZhy41cUDGDjcZOADEAruNaiIkgPzoDIreOAA3YFDgAX34ZOUVlXXUAbgAoUEhYBGRUAAVRZikacQAbRCFDSgjVDm4+fWFcMUl8vCJSQp1izW0VPRqjINj46HgkFHcKlMIoEkx-BtaYABoldpMQMwsrdrryakbWNhK4IZHSMyhKNIys3PaJyLZ+Kna1NliY5mzCMitrCAheGLgfuDAARi8tmIdH8XDg-1ivzgxH+AAoAPqEQFwMgwKASADmAEpeEFvr9iAAmRHIoEg-wzJFErRojHiHF4wIxZkxbKYOAgLQrUaUd4QbYAclhgti7PgiC0x0yOTyHksFH52x4BJ+sNJKLpWNxfECU1VMJJSJR4mBoKgVMINNR6O1TJZMTZHIAXlLhqMDkd0jKzvK+R8rsKiYK7uD+P8ZoL-iGxRzYVog4LwYnY-BnSjdh7xhRpac5RV-QL+H1gAoYf9Q9xw5Ho2oHuK4IRufLM-ts-zIyLtvwozGnfArc3Bu624dFR9O9Hu72ZhXU42AMxDwytsZjjtwRPdiOb2tRIA
