### PR TITLE
fix: correct name length criterion for spelling fixes

### LINKED ISSUE #49557: Codefix "Correct spelling" stops working when 3 spaces are missing, or suggests bad replacement
# Bug Report

### 🔎 Search Terms

codefix spelling spaces

### 🕗 Version & Regression Information

- This is the behavior in every version I tried
- 
### ⏯ Playground Link

[Playground Link](https://www.typescriptlang.org/play?ts=4.7.2#code/KYOwrgtgBAcghhYBnA6gSwC4AsDKAHOAY2SgG8AoASACIYB7fI4agGiuoHkRgpHjX2ACThIoAFQDudXgWJIBNMVjSjhopQCdgPPsgXUAgiAAm45apFQAYnTAaZTeW3YAhADZ1CAayhdmbGndPH3EpfSDvKCjNbQEAX3JyQjoQJAwoDGQMAAYoAF5YBGR0bF0kADp6XQBuJJS0jKyARnzCxFRMXFlkcr8aqAB6AagAYTpjYAAzNAAPKDgANzg0NzgAIzdgOtT0zLSAJlb4dpKux3K1SQZupGrB4bGJ6bnF5dWNreSdxrSAZiOih1SjdykoVJcsFpgGU7kNYBwoMknrN5ksVutNtsGnsMAAWAEnTplcpGYxgpBqGx2GH3eGI8ZTFGvdEfRJfBobYItArHYpEkERLx+WEPBnPVFvDGferpTneQ48wGnYmCq4i0Ziplo96Y9myjzef6KwnA86qyHadUwBFIxkvbVSoA)

### 💻 Code

```ts
enum NamesWithSpaces {
	"NoSpace",
	"One Space",
	"Has Two Spaces",
	"This Has Three Spaces",
	"And This Has Four Spaces",

	"Block One",
	"Block  Two",
	"Block   Three",
}

const test0 = NamesWithSpaces.NoSpace;
const test1 = NamesWithSpaces.OneSpace; // Codefix available
const test2 = NamesWithSpaces.HasTwoSpaces; // Codefix available
const test3 = NamesWithSpaces.ThisHasThreeSpaces; // NO codefix available
const test4 = NamesWithSpaces.AndThisHasFourSpaces; // NO codefix available

const block1 = NamesWithSpaces.BlockOne; // Codefix available
const block2 = NamesWithSpaces.BlockTwo; // Codefix available
const block3 = NamesWithSpaces.BlockThree; // NO codefix available
```

### 🙁 Actual behavior

Only the enum members with less than 3 spaces in the correct name have a suggestion to correct spelling (TS2551). The ones with 3 or more spaces don't (TS2339).

It seems to depend on the metric used to compare the strings. If we add a bunch of characters, the suggestions become even weirder:
```ts
enum NamesWithSpaces {
	"This Has Three Spaces_________________________________________________________",
	"And This Has Four Spaces_________________________________________________________",
}

const test3 = NamesWithSpaces.ThisHasThreeSpaces_________________________________________________________;
// ^ NO codefix available
const test4 = NamesWithSpaces.AndThisHasFourSpaces_________________________________________________________;
// Suggests "This Has Three Spaces_________________________________________________________"
```

The absolute (not normalized to string length) Damerau–Levenshtein distance between the correct replacements are 3 or 4 respectively (adding 3 or 4 spaces). The distance to the incorrect (but suggested) replacement is 10.

### 🙂 Expected behavior

Every one of those enum members should have a codefix available to correct spelling (by adding the spaces).

### PR DESCRIPTION
**Pull request by AlCalzone**
Using `Math.min` effectively invalidated the name length criterion and prevented some otherwise good candidates from being suggested.

Fixes #49557

### CODE REVIEW

**Review by DanielRosenwasser — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Can you accept the rest of the baselines?

File: tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt [hunk 1]
```diff
@@ -86,13 +87,13 @@ tests/cases/compiler/doYouNeedToChangeYourTargetLibraryES2016Plus.ts(44,33): err
...
                                       ~~~~~~~~~~~~~~~~~~~~~~
-!!! error TS2583: Cannot find name 'AsyncGeneratorFunction'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2018' or later.
+!!! error TS2552: Cannot find name 'AsyncGeneratorFunction'. Did you mean 'GeneratorFunction'?
     const testAsyncIterable: AsyncIterable<any> = null as any;
                              ~~~~~~~~~~~~~
 !!! error TS2583: Cannot find name 'AsyncIterable'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2018' or later.
     const testAsyncIterableIterator: AsyncIterableIterator<any> = null as any;
                                      ~~~~~~~~~~~~~~~~~~~~~
-!!! error TS2583: Cannot find name 'AsyncIterableIterator'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2018' or later.
+!!! error TS2552: Cannot find name 'AsyncIterableIterator'. Did you mean 'IterableIterator'?
```
Comment (AlCalzone) [inline tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt:96]: This worries me a bit.

**Comment by AlCalzone** [comment]
@DanielRosenwasser Done. Most of the changes are good IMO, except the one I highlighted. I mean the suggested name is similar, but the previous error message was better. Maybe the criteria need some tuning now?

File: tests/baselines/reference/propertyOrdering.errors.txt [hunk 2]
```diff
@@ -1,17 +1,20 @@
...
     class Foo {
         constructor(store: string) { }
           public foo() {
                 return this._store.length;   // shouldn't be an error
           }
           public _store = store; // no repro if this is first line in class body
                           ~~~~~
+!!! error TS2301: Initializer of instance member variable '_store' cannot reference identifier 'store' declared in the constructor.
+                          ~~~~~
 !!! error TS2304: Cannot find name 'store'.
```
Comment (DanielRosenwasser) [inline tests/baselines/reference/propertyOrdering.errors.txt:18]: Weird that you get both errors now.

File: tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt (hunk 1 above)
Comment (DanielRosenwasser) [reply tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt:96]: Is there an easy way to do the built-in declarations check before the "did you mean...?" check?

File: tests/baselines/reference/propertyOrdering.errors.txt (hunk 2 above)
Comment (AlCalzone) [reply tests/baselines/reference/propertyOrdering.errors.txt:18]: I'm suspecting that the new error is the expected one and the "cannot find name" isn't? At least that's how I understand this comment:
https://github.com/AlCalzone/TypeScript/blob/1213c35d57d91cc773f05c3e5dc36770c602ba94/src/compiler/checker.ts#L1956-L1973

Comment (DanielRosenwasser) [reply tests/baselines/reference/propertyOrdering.errors.txt:18]: Well...yeah I suppose if we report the new one, the old one should disappear - OR this should be an elaboration on the `Cannot find name` one.

But why does this change even make this error appear?

Comment (AlCalzone) [reply tests/baselines/reference/propertyOrdering.errors.txt:18]: Any hint how to find that out? I'm not familiar with the TS codebase.

Comment (jakebailey) [reply tests/baselines/reference/propertyOrdering.errors.txt:18]: The way I'd do it would be to breakpoint on the line that adds that diagnostic, and see who's calling it. Maybe this spelling stuff is being used more than it should?

Comment (AlCalzone) [reply tests/baselines/reference/propertyOrdering.errors.txt:18]: I think the issue is that this case comes into effect and does not set the `result` variable:
grafik

This means that this section of the code is called, reporting the "cannot find store" error in the currently paused line:
grafik

For reference, this is the top of the call stack:
```
<anonymous> (i:\TypeScript\src\compiler\checker.ts:2205)
addLazyDiagnostic (i:\TypeScript\src\compiler\checker.ts:41845)
resolveNameHelper (i:\TypeScript\src\compiler\checker.ts:2166)
resolveName (i:\TypeScript\src\compiler\checker.ts:1817)
getResolvedSymbol (i:\TypeScript\src\compiler\checker.ts:23216)
checkIdentifier (i:\TypeScript\src\compiler\checker.ts:25708)
checkExpressionWorker (i:\TypeScript\src\compiler\checker.ts:34904)
checkExpression (i:\TypeScript\src\compiler\checker.ts:34847)
checkExpressionCached (i:\TypeScript\src\compiler\checker.ts:34484)
checkDeclarationInitializer (i:\TypeScript\src\compiler\checker.ts:34507)
getTypeForVariableLikeDeclaration (i:\TypeScript\src\compiler\checker.ts:8985)
getWidenedTypeForVariableLikeDeclaration (i:\TypeScript\src\compiler\checker.ts:9484)
getTypeOfVariableOrParameterOrPropertyWorker (i:\TypeScript\src\compiler\checker.ts:9651)
getTypeOfVariableOrParameterOrProperty (i:\TypeScript\src\compiler\checker.ts:9539)
getTypeOfSymbol (i:\TypeScript\src\compiler\checker.ts:9932)
checkPropertyAccessExpressionOrQualifiedName (i:\TypeScript\src\compiler\checker.ts:29171)
checkPropertyAccessExpression (i:\TypeScript\src\compiler\checker.ts:28913)
checkExpressionWorker (i:\TypeScript\src\compiler\checker.ts:34938)
checkExpression (i:\TypeScript\src\compiler\checker.ts:34847)
checkNonNullExpression (i:\TypeScript\src\compiler\checker.ts:28854)
checkPropertyAccessExpression (i:\TypeScript\src\compiler\checker.ts:28913)
checkExpressionWorker (i:\TypeScript\src\compiler\checker.ts:34938)
checkExpression (i:\TypeScript\src\compiler\checker.ts:34847)
checkExpressionCached (i:\TypeScript\src\compiler\checker.ts:34484)
```

Comment (AlCalzone) [reply tests/baselines/reference/propertyOrdering.errors.txt:18]: To be honest I have no clue what the best mitigation is here.

Comment (AlCalzone) [reply tests/baselines/reference/propertyOrdering.errors.txt]: I tried simply reordering the two checks which gets rid of the double error here but adds some bad changes elsewhere. See https://github.com/microsoft/TypeScript/pull/49575/commits/6b521325fb3aec4cc3ac8c7bf3dd685b8b9c85f2 for reference.

File: tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt [hunk 3]
```diff
@@ -1,36 +1,36 @@
...
 ==== tests/cases/compiler/constructorParametersInVariableDeclarations.ts (6 errors) ====
     class A {
         private a = x;
                     ~
-!!! error TS2304: Cannot find name 'x'.
+!!! error TS2301: Initializer of instance member variable 'a' cannot reference identifier 'x' declared in the constructor.
         private b = { p: x };
                          ~
-!!! error TS2304: Cannot find name 'x'.
+!!! error TS2301: Initializer of instance member variable 'b' cannot reference identifier 'x' declared in the constructor.
```
Comment (AlCalzone) [inline tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt:16]: I think these are good

File: tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt [hunk 4]
```diff
@@ -1,36 +1,36 @@
...
         private c = () => x;
                           ~
-!!! error TS2304: Cannot find name 'x'.
+!!! error TS2301: Initializer of instance member variable 'c' cannot reference identifier 'x' declared in the constructor.
```
Comment (AlCalzone) [inline tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt:19]: but not this. Maybe the check for TS2301 should not happen in arrow function assignments?

File: tests/baselines/reference/checkIndexConstraintOfJavascriptClassExpression.errors.txt [hunk 5]
```diff
@@ -1,12 +1,13 @@
-tests/cases/compiler/weird.js(1,1): error TS2304: Cannot find name 'someFunction'.
+tests/cases/compiler/weird.js(1,1): error TS2552: Cannot find name 'someFunction'. Did you mean 'Function'?
```
[the remark this answers is not in the document]
Comment (AlCalzone) [reply tests/baselines/reference/checkIndexConstraintOfJavascriptClassExpression.errors.txt:1]: This happens for prefixes with length 1-4, so `aFunction`, `myFunction`, ..., `someFunction` but not longer prefixes - and for things like `aPhunction`.

File: tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt (hunk 1 above)
Comment (AlCalzone) [reply tests/baselines/reference/doYouNeedToChangeYourTargetLibraryES2016Plus.errors.txt]: These are restored with the latest commit. Even added some more lib recommendations related to BigInt64Array.

File: tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt (hunk 4 above)
Comment (jakebailey) [reply tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt:19]: I don't think `x` should be in scope for this arrow function; `x` in this example is just a constructor parameter.

I'm a little confused as to why all of these say that it's "declared in the constructor"; my brain is telling me that it's something that's assigned to `this` in the constructor, when it's just some variable that happens to be in scope for the constructor function, so it's a little weird. I would think that "cannot find name x" is technically the more accurate message, because there's nothing you can do to `x` in the constructor signature (not even `private x: number`) that would make it accessible. (But, there is that comment that says "it's legal in this one situation", which is complicating.)

I guess I'd have to go back to when this diagnostic was added to see what the intent was.

File: tests/baselines/reference/classMemberInitializerWithLamdaScoping4.errors.txt [hunk 6]
```diff
@@ -14,6 +14,6 @@ tests/cases/compiler/classMemberInitializerWithLamdaScoping3_1.ts(8,21): error T
         messageHandler = () => {
             console.log(field1); // Should be error that couldnt find symbol field1
                         ~~~~~~
-!!! error TS2663: Cannot find name 'field1'. Did you mean the instance member 'this.field1'?
+!!! error TS2301: Initializer of instance member variable 'messageHandler' cannot reference identifier 'field1' declared in the constructor.
```
Comment (jakebailey) [inline tests/baselines/reference/classMemberInitializerWithLamdaScoping4.errors.txt:17]: This seems like a less-good error message here; similar to the `x` example, this name wouldn't be in scope, but differs in that it can be fixed by writing `this.field`, which is what the old error said.

**Review by jakebailey — COMMENTED** [review]
Looks a lot better now, but I am a little concerned about the initializer messages.

File: tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt (hunk 4 above)
Comment (sandersn) [reply tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt:19]: The reason for the error is that pre-ES2021 (2022?), TS defaults to emitting class properties as assignments in the constructor (controllable separately from `target` with `useDefinedForClassFields`), so `private a = x` would emit:

```js
class A {
  constructor(x) {
    this.a = x
  }
}
```

Then there are two problems:

1. The thing you wrote *should* not find name 'x' -- so you'd expect the old error.
2. But it *will* at runtime, because the emitted code in the constructor -- so you'd expect the new error.

The new error message is correct when `useDefineForClassFields: false`, which it is for this file, ***and also*** extremely obscure.

Note that you can get the new error without the old one if you add `var x = 1` at the beginning of the test. The new error is possibly even more confusing in this case.

So: the new error is correct and also horrible. I don't know if we should fix it (separately) though: the top hit for the error is a pretty good explanation from 2015. And over time fewer people will target non-compliant emit.

Minutes later: The error still shows up when useDefineForClassFields: true, which it shouldn't. I'll file a bug for that.

Comment (sandersn) [reply tests/baselines/reference/constructorParametersInVariableDeclarations.errors.txt:19]: Filed #49719

File: tests/baselines/reference/classMemberInitializerWithLamdaScoping4.errors.txt (hunk 6 above)
Comment (AlCalzone) [reply tests/baselines/reference/classMemberInitializerWithLamdaScoping4.errors.txt]: Fixed in the latest commit

**Review by AlCalzone — COMMENTED** [review]
Most of the concerns are addressed with the latest commit. I'm not sure if this https://github.com/microsoft/TypeScript/pull/49575/files/7effd54c0224207b142997ad98e9456eeb5be776#r908149168 is desired or not, but I'm also not sure how to fix it.

I won't be available for the next 2 weeks, so if anyone from the team wants to pick up and finish this, feel free to.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -2161,19 +2161,46 @@ namespace ts {
                     }
                 }
             }
+
+            // The invalid initializer error is needed in two situation:
+            // 1. When result is undefined, after checking for a missing "this."
+            // 2. When result is defined
+            const checkAndReportErrorForInvalidInitializer = ()=>{
```
Comment (jakebailey) [inline src/compiler/checker.ts:2168]:
```suggestion
            function checkAndReportErrorForInvalidInitializer() {
```

Is more the style we have in this codebase.

**Comment by jakebailey** [comment]
> I won't be available for the next 2 weeks, so if anyone from the team wants to pick up and finish this, feel free to.

I just updated your branch to be up to date with `main` and with baselines accepted. I'll quick look into the message you're noting; everything else seems okay to me at this point.

File: tests/baselines/reference/initializerReferencingConstructorParameters.errors.txt [hunk 8]
```diff
@@ -11,20 +11,20 @@ tests/cases/conformance/classes/propertyMemberDeclarations/initializerReferencin
...
     
     class D {
         a = x; // error
             ~
-!!! error TS2663: Cannot find name 'x'. Did you mean the instance member 'this.x'?
+!!! error TS2301: Initializer of instance member variable 'a' cannot reference identifier 'x' declared in the constructor.
         b: typeof x; // error
                   ~
-!!! error TS2304: Cannot find name 'x'.
+!!! error TS2301: Initializer of instance member variable 'b' cannot reference identifier 'x' declared in the constructor.
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply tests/baselines/reference/initializerReferencingConstructorParameters.errors.txt:27]: It's just the message that was wrong; I guess this message didn't come up a lot so nobody realized the wording didn't make sense if the error location was inside a type node. It's an easy fix; just make another message that says "Type" instead. I'm pushing that now.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -2204,19 +2205,48 @@ m2: ${(this.mapper2 as unknown as DebugTypeMapper).__debugToString().split("\n")
...
+            // The invalid initializer error is needed in two situation:
+            // 1. When result is undefined, after checking for a missing "this."
+            // 2. When result is defined
+            function checkAndReportErrorForInvalidInitializer() {
+                if (propertyWithInvalidInitializer && !(getEmitScriptTarget(compilerOptions) === ScriptTarget.ESNext && useDefineForClassFields)) {
+                    // We have a match, but the reference occurred within a property initializer and the identifier also binds
+                    // to a local variable in the constructor where the code will be emitted. Note that this is actually allowed
+                    // with ESNext+useDefineForClassFields because the scope semantics are different.
+                    error(errorLocation,
+                        errorLocation && propertyWithInvalidInitializer.type && textRangeContainsPositionInclusive(propertyWithInvalidInitializer.type, errorLocation.pos)
```
Comment (jakebailey) [inline src/compiler/checker.ts:2218]: I don't really like what I've done here; I just want to know "is errorLocation in the type of the property declaration". I was going to use `findAncestor`, but it needs to stop once the property declaration node is reached, so that makes it a little more than a one liner, and just checking that the node contains the other node by position is fast. This is done in one other place, so it seemed okay.

File: tests/baselines/reference/initializerReferencingConstructorParameters.errors.txt (hunk 8 above)
[the remark this answers is not in the document]
Comment (jakebailey) [reply tests/baselines/reference/initializerReferencingConstructorParameters.errors.txt]: Or, we could just say "instance member variable 'b' cannot reference identifier 'x' declared in the constructor."

That would be agnostic and remove a bit of logic I had to add to distinguish the cases.
