### ISSUE TITLE
Regression in type inference with functional intersection type

### ISSUE THREAD

**Issue by rsimp** [microsoft/TypeScript#19732]
**TypeScript Version:**  2.6.1 and 2.7.1

**Code**

```
declare var R: R.Static;
declare namespace R {
    interface Dictionary<T> {
        [index: string]: T;
    }

    interface FilterDict<T> {
      (obj: Dictionary<T>): Dictionary<T>;
    }

    interface FilterList<T> {
      (list: T[]): T[];
    }

    type Filter<T> = FilterList<T> & FilterDict<T>;

    interface Static {
        filter<T>(fn: (value: T) => boolean): Filter<T>;
        compose<V0, T1, T2, T3>(fn2: (x: T2) => T3, fn1: (x: T1) => T2, fn0: (x: V0) => T1): (x: V0) => T3;
        map<T, U>(fn: (x: T) => U): (list: T[]) => U[];
        prop<T>(p: string): (obj: any) => T;
    }
}

export const nonNullMapValues = R.compose(
  R.filter<string>(Boolean),
  R.map<any, string>(R.prop("1")), //error: Type 'string[]' is not assignable to type 'Dictionary<T>', Index signature is missing
  Array.from
);
```

**Expected behavior:**
Given the `string` type parameter specified on `R.filter<string>(Boolean)`, the resulting functional type: `Filter<string>` must then satisfy the `fn2` parameter typing in the `R.compose` signature. Because `Filter<string>` is an intersection type this means the `T2` type parameter of `R.compose` must either be `Dictionary<string>` **OR** `string[]`. Given the `string` generic type parameter specified on `R.map<any, string>(R.prop("1"))` then the `T2` type parameter can only be `string[]`. Because `string[]` matches with `string[]` **OR** `Dictionary<T>`, `string[]` is a valid input type for the functional `Filter<string>` intersection type. I fail to see why this should be a compilation error, and it wasn't one in typescript 2.5.3, so I believe this is a regression.

**Actual behavior:**
The typescript compiler tries to verify that `string[]` is a valid input for both function types on the `Filter<string>` intersection type. Fails because `string[]` is not compatible with `Dictionary<string>`, even though this check is unnecessary.

**Comment by mhegazy** [comment]
note to self. need to bisect to find which commit caused the change in behavior.

**Comment by rsimp** [comment]
@mhegazy one thing to point out is that this scenario never worked with functional interfaces: 
```
interface Filter<T> {
  (obj: Dictionary<T>): Dictionary<T>;
  (list: T[]): T[];
}
```
which should function identical to the intersection type:
```
interface FilterDict<T> {
  (obj: Dictionary<T>): Dictionary<T>;
}
interface FilterList<T> {
  (list: T[]): T[];
}
type Filter<T> = FilterList<T> & FilterDict<T>;
```
The intersection type worked with typescript 2.5.3 but then regressed in 2.6. It would be great if we could get it working with both functional intersection types and with functional interfaces.

**Comment by rsimp** [comment]
I think the issue is that the typescript compiler is deciding that the functional intersection requires an input of `Dictionary<T> & T[]` where it should instead be `Dictionary<T> | T[]`. Same with the functional interface with more than one signature specified. The inputs themselves shouldn't be intersections, they are separate, and therefore should be unions. The function that satisfies the functional intersection can take in either of the input types, not an intersection of the two.

**Comment by rsimp** [comment]
@mhegazy had anytime to look this over? Also could we get the issue labeled as a bug if appropriate?

**Comment by RyanCavanaugh** [comment]
Given the fairly involved repro and the length of time this has been open without change, this looks likely to be working as intended. If you can demonstrate this more clearly in a short repro please open a new issue, but we're not able to investigate lengthy repros. Thanks!
