### ISSUE TITLE
Weird heap overflow when compiling a single line of code with recursive type definition.

### ISSUE THREAD

**Issue by Veetaha** [microsoft/TypeScript#30831]
**TypeScript Version:**  `typescript@3.4.2`, `typescript@3.5.0-dev.20190409`

**Search Terms:**

* Heap overflow

**Code**

```ts
type Foo<T> = Extract<{[i in keyof T]: Foo<T[i]>; }[0], 0>;
```

**Expected behavior:**
Should print an error for indexing object literal with `0` or using circular references.
Or at least the same behavior as in `v3.3.4000`:

<details>
<summary>Output when compiled with `typescript@3.3.4000`</summary>

![image](https://user-images.githubusercontent.com/36276403/55800661-eacb2e80-5adc-11e9-979b-9d51567347d4.png)

</details>

**Actual behavior:**

NodeJS standard heap crash report: `Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/36276403/55800223-d9cded80-5adb-11e9-82eb-b49799f39674.png)
</details>

Playground from `typescriptlang.com` produces in-browser heap memory allocation failure:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/36276403/55800895-71800b80-5add-11e9-92bf-39e7febf7825.png)

</details>

**Playground Link:** 

[Klick me if you are not afraid of crashing your browser's heap](https://www.typescriptlang.org/play/index.html#src=type%20Foo%3CT%3E%20%3D%20Extract%3C%7B%5Bi%20in%20keyof%20T%5D%3A%20Foo%3CT%5Bi%5D%3E%3B%20%7D%5B0%5D%2C%200%3E%3B)

**Related Issues:** 

* `typesafe-joi` heap overflow #30794
* extremely slow compilation #30781
* performance degradation since `typescript@3.4.1` #30663
* weird stack overflow issue #30804
* [stackoverflow question about heap overflow](https://stackoverflow.com/questions/55524565/typescript-compile-time-heap-overflow-or-how-to-resolve-circular-infinitely-dee)

**Comment by hjkcai** [comment]
Great! I think this will be the minimal reproduction of this issue. Thanks a lot!

**Comment by ahejlsberg** [comment]
The example above produces the expected errors with #30769.

```ts
t.ts:1:6 - error TS2456: Type alias 'Foo' circularly references itself.

1 type Foo<T> = Extract<{[i in keyof T]: Foo<T[i]>; }[0], 0>;
       ~~~

t.ts:1:23 - error TS2536: Type '0' cannot be used to index type '{ [i in keyof T]: any; }'.

1 type Foo<T> = Extract<{[i in keyof T]: Foo<T[i]>; }[0], 0>;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

t.ts:1:40 - error TS2315: Type 'Foo' is not generic.

1 type Foo<T> = Extract<{[i in keyof T]: Foo<T[i]>; }[0], 0>;
                                         ~~~~~~~~~


Found 3 errors.
```

**Comment by andrewbranch** [comment]
Confirmed that this doesn't crash in 3.5.0-rc, although the only error I get is

main.ts:1:23 - error TS2536: Type '0' cannot be used to index type '{ [i in keyof T]: Extract<{ [i in keyof T[i]]: Extract<{ [i in keyof T[i][i]]: Extract<{ [i in keyof T[i][i][i]]: Extract<{ [i in keyof T[i][i][i][i]]: Extract<{ [i in keyof T[i][i][i][i][i]]: Extract<{ [i in keyof T[i][i][i][i][i][i]]: Extract<{ [i in keyof T[i][i][i][i][i][i][i]]: Extract<{ [i in keyof T[i][i][i][i][i][i][i][i]]: Extract<{ [i in keyof T[i][i][i][i][i][i][i][i][i]]: Extract<{ [i in keyof T[i][i][i][i][i][i][i][i][i][i]]: Extract<any[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }[0], 0>; }'.

1 type Foo<T> = Extract<{[i in keyof T]: Foo<T[i]>; }[0], 0>;

🤔

**Comment by andrewbranch** [comment]
Talked to @weswigham and this is probably caused by #31354. I think the new output here is not super desirable, but it's not related to this issue per se. If there are new real-world issues with this code or other conditional types in the RC, a new issue is welcomed.
