### ISSUE TITLE
Non-null assertion operator does not remove `void` since 2.8

### ISSUE THREAD

**Issue by bradleyayers** [Microsoft/TypeScript#23847]
**TypeScript Version:**

- typescript@2.9.0-dev.20180502
- typescript@2.8.3

(Works in 2.7.2)

**Search Terms:**

- non-null assertion operator void
- ! operator void
- nonnull operator void

**Code**

```ts
const someVar = "text" as void | string;
someVar!.length
```

**Expected behavior:**

No warnings

**Actual behavior:**

```
Property 'length' does not exist on type 'string | void'.
  Property 'length' does not exist on type 'void'.
```

**Playground Link:**  

https://www.typescriptlang.org/play/#src=const%20someVar%20%3D%20%22foo%22%20as%20void%20%7C%20string%3B%0AsomeVar!.length%3B

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
Nor should it; if you somehow find yourself with a value of type `void` you cannot be sure it has the value `undefined`, because a reference to a function returning `void` may in fact be an alias for a function returning something else.
