### ISSUE TITLE
Excessive Stack Depth from DeepPartial/RecursivePartial in 2.7.x

### ISSUE THREAD

**Issue by kevinbeal** [microsoft/TypeScript#21592]
**Search Terms:** 
"excessive depth"
"generic partial"

**Code**

```ts
const fn = <T>(arg: T) => {
    ((arg2: RecursivePartial<T>) => {
        // ...
    })(arg); // <-- here
};

type RecursivePartial<T> = {
    [P in keyof T]?: RecursivePartial<T[P]>;
};
```

**Expected behavior:**
Comparing a generic with a partial of that generic working without errors.

**Actual behavior:**
Getting "Excessive stack depth comparing types 'T' and 'RecursivePartial<T>'." since upgrading to 2.7.x. (Also errors in 2.8.x). Working in 2.6.1.

**Playground Link:** 
https://www.typescriptlang.org/play/index.html#src=class%20Greeter%20%7B%0D%0A%20%20%20%20greeting%3A%20RecursivePartial%3Cstring%3E%3B%0D%0A%20%20%20%20constructor(message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.greeting%20%3D%20message%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20greet()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%22Hello%2C%20%22%20%2B%20this.greeting%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20greeter%20%3D%20new%20Greeter(%22world%22)%3B%0D%0A%0D%0Alet%20button%20%3D%20document.createElement('button')%3B%0D%0Abutton.textContent%20%3D%20%22Say%20Hello%22%3B%0D%0Abutton.onclick%20%3D%20function()%20%7B%0D%0A%20%20%20%20alert(greeter.greet())%3B%0D%0A%7D%0D%0A%0D%0Adocument.body.appendChild(button)%3B%0D%0A%0D%0Aconst%20fn%20%3D%20%3CT%3E(arg%3A%20T)%20%3D%3E%20%7B%0D%0A%20%20%20%20((arg2%3A%20RecursivePartial%3CT%3E)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2F%0D%0A%20%20%20%20%7D)(arg)%3B%0D%0A%7D%3B%0D%0A%0D%0Atype%20RecursivePartial%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3F%3A%20RecursivePartial%3CT%5BP%5D%3E%3B%0D%0A%7D%3B

**Related Issues:**
None?

**Comment by Conaclos** [comment]
I got the same code with the next [code](https://www.typescriptlang.org/play/#src=type%20SafeAny%20%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bk%20in%20keyof%20T%5D%3F%3A%20SafeAny%3CT%5Bk%5D%3E%0D%0A%7D%20%7C%20boolean%20%7C%20number%20%7C%20string%20%7C%20symbol%20%7C%20null%20%7C%20undefined%0D%0A%0D%0Atype%20DataValidator%20%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bk%20in%20keyof%20T%5D%3F%3A%20(v%3A%20SafeAny%3CT%5Bk%5D%3E)%20%3D%3E%20v%20is%20T%5Bk%5D%0D%0A%7D%0D%0A):

```ts
type SafeAny <T> = {
    [k in keyof T]?: SafeAny<T[k]>
} | boolean | number | string | symbol | null | undefined

type DataValidator <T> = {
    [k in keyof T]?: (v: SafeAny<T[k]>) => v is T[k] // 
}
```

The following error is reported:

```
error TS2321: Excessive stack depth comparing types 'T[k]' and 'SafeAny<T[k]>'.
```

**Comment by kevinbeal** [comment]
@Conaclos In what sense exactly is the link wrong? I did hit "share". It wouldn't be a really long URL with url encoded typescript in the URL if I hadn't. Are you not seeing the issue when you click the link?

**Comment by Conaclos** [comment]
@kevinbeal
Sorry, I expected the same code than the one posted here...

**Comment by sandersn** [comment]
From bisecting, the bad commit is part of #19564.

**Comment by chirdeeptomar** [comment]
I am using TypeScript 2.9.1 and still the same issue.

**Comment by rafaelbatistamarcilio** [comment]
@chirdeeptomar this issue was assigned to the 3.0 milestone

**Comment by stefanosaittamrf** [comment]
they move this in the 3.1 milestone. 😢

**Comment by nerder** [comment]
This was actually shifted from 3.0 to 3.1 milestone. 😢

**Comment by murbanowicz** [comment]
Any updates on this? I came across this issue today with 3.1..

**Comment by chukwunomso** [comment]
Typescript V3.1.4 fixed it for me

**Comment by chukwunomso** [comment]
> Any updates on this? I came across this issue today with 3.1..

Typescript V3.1.4 fixed it for me today

**Comment by dverlik** [comment]
Ran into this on 3.2.1.

**Comment by mtford90** [comment]
This only seems to happen when i'm using yarn for some reason.

**Comment by shaunxu** [comment]
I have the same problem when updated to 3.2.2. I have to use `require("lodash")` to bypass the type validation. BTW I'm using npm 6.5

**Comment by ryuuji3** [comment]
I had to disable type checking altogether by casting T to any.

**Comment by chukwunomso** [comment]
Any joy with this issue. It still happens on v 3.2.2

**Comment by vitaliusvs** [comment]
typescript@3.2.2

C:\spool\cpt-develop\webapp\server\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS2321: Excessive stack depth comparing types 'any' and 'ListIterateeCustom<T, boolean>'.
error TS2321: Excessive stack depth comparing types 'any' and 'ObjectIterateeCustom<T[], boolean>'.

    at createTSError (C:\spool\cpt-develop\webapp\server\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\spool\cpt-develop\webapp\server\node_modules\ts-node\src\index.ts:367:40)
    at Object.compile (C:\spool\cpt-develop\webapp\server\node_modules\ts-node\src\index.ts:558:11)
    at Module.m._compile (C:\spool\cpt-develop\webapp\server\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\spool\cpt-develop\webapp\server\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by keawade** [comment]
I'm currently seeing this on 3.2.2:
`error TS2321: Excessive stack depth comparing types 'T' and 'DeepPartial<T>'`

Also, it seems I can't cast to `any` to avoid the issue:
`error TS2321: Excessive stack depth comparing types 'any' and 'DeepPartial<T>'.`

```
export declare type DeepPartial<T> = {
    [P in keyof T]?: DeepPartial<T[P]>;
};
```

**Comment by vitaliusvs** [comment]
Retested with typescript@3.2.4

C:\dev\server\node_modules\ts-node\src\index.ts:261
return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
error TS2321: Excessive stack depth comparing types 'any' and 'ListIterateeCustom<T, boolean>'.
error TS2321: Excessive stack depth comparing types 'any' and 'ObjectIterateeCustom<T[], boolean>'.

**Comment by johannesschobel** [comment]
i can confirm, that this issue still exists in `typescript 3.2.4 (latest)`

**Comment by alessandrojcm** [comment]
I'm also having this issue with Typescript 3.2.4

**Comment by bryanrideshark** [comment]
This problem exists in Typescript 3.2.

**Comment by andreymaznyak** [comment]
I have the same problem in Typescript 3.3

**Comment by wyqydsyq** [comment]
Also suffering this issue on TS 3.3, It happens on any Models I define using [sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript#readme) that have associations to other models e.g.

```ts
@Table
export class User extends Model<User> {
  @Column({
    type: DataType.UUID,
    primaryKey: true,
  })
  id: string;

  @Column(DataType.STRING(255))
  identity: string;

  @Column(DataType.TEXT) metadata: string;

  @HasMany(() => Project)
  projects: Project[];
}
```
Gives me the error:
```ts
Excessive stack depth comparing types '() => typeof Project' and 'ModelClassGetter'.ts(2321)
```

Changing the `@HasMany(() => Project)` line to `@HasMany(() => Project as any)` avoids the error

**Comment by Yaojian** [comment]
I bet a $ that we will see a message: `sandersn (or whoever) mofied the milestones: TypeScript 3.5.0, TypeScript 3.6.0` some day.  😿

**Comment by mtford90** [comment]
Indeed... quite infuriating. I'm currently using a postinstall script that blasts away any lodash typings in my dependencies. Gnarly.

**Comment by sandersn** [comment]
I'm trying to get this bug up to date since it's been open a long time. Sorry for the random pings everybody is going to get.

Here's the current status, pre-cleanup: I [created a PR more than a year ago](https://github.com/microsoft/TypeScript/pull/22612) with a not-very-good fix for this bug, but we didn't give it high priority because self-recursive mapped types are not a good idea. At the time, we thought they weren't used much, but they do show up in a few high-profile packages, lodash in particular.

1. Given Typescript's structural semantics, there's no easy way to specify where the recursion should terminate; primitives like `string` have methods that come from their apparent types (eg `String`) so a recursive mapped type recurs right down through these methods, even though that's never the intended meaning. With conditional types (which didn't exist when this bug was created), it's now possible to specify termination conditions for the recursion, which leads to problem 2...
2. When checking higher-order types -- types that have type parameters inside them -- Typescript doesn't have a smart solver or anything that can simplify interesting patterns. It's just good old recursion through a series of rules that may simplify *locally* but have no global knowledge. Self-recursive mapped types that get assigned "one level off", like `T ==> Rec<T>`, can only try to expand the mapped type over and over again because `T` is a type parameter. 

    What you need is a global way to prove that `Rec<T> ==> Rec<Rec<T>>` implies that `T ==> Rec<T>`. But `Rec<T> ==> Rec<Rec<T>>` is hard to recognise in the current compiler. My PR introduced an ad-hoc check for it, but I'm still not convinced that it correctly proves that `T ==> Rec<T>`.

So I'm going to re-discuss the fix with other members of the team and in the meantime find popular packages that use self-recursive mapped types to see if they can be rewritten to not use them.

**Comment by sandersn** [comment]
@kevinbeal @Conaclos @keawade  Can you provide a bit more context on `RecursivePartial`/`DeepPartial` and `SafeAny`? What is some real code that would have used these types? What did you do instead? What were you using before?

@Yaojian it sounds like `tsc` is your globally installed typescript, whereas `yarn compile` gives a local typescript. Do you still see this difference? Can you check typescript versions of `tsc` versus `yarn compile` if so?

@mtford90 @shaunxu @vitaliusvs Do you still have problems with lodash if you upgrade to `@types/lodash@4.14.125` or newer? That change improved memory usage quite a bit, although it does not get rid of the DeepPartial type. If you still have problems with lodash, could you give an example snippet that fails?

@alessandrojcm @wyqydsyq Thanks for the repros. I'll take a look and let you know if I can't make it fail on my machine.

Everyone else:
@chirdeeptomar @mdekrey @rafaelbatistamarcilio @nerder @murbanowicz @ryuuji3 @chukwunomso @bryanrideshark @andreymaznyak 
Can you give me an example of the code that you saw the failure with, and what package it happened with?

**Comment by sandersn** [comment]
Update: after some discussion, we're not any closer to solving the underlying problem.

@alessandrojcm Your error comes from typeorm; they found a workaround: adding a conditional type in the self-referential mapped type. Here's a standalone example with a nonsensical conditional type:

```ts
export type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends never ? DeepPartial<T[P]> : DeepPartial<T[P]>
};
declare class Repo<U> {
    save(entity: DeepPartial<U>): void;
}
function save<T>(entityRepository: Repo<T>, entity: T) {
    entityRepository.save(entity);
}
```

This is unlikely to work forever since someday the compiler will probably understand conditional types better, but is a decent workaround for now. (typeorm's conditional type is less obviously a workaround than the example above.) 

However, I think most users of typeorm would be fine with just `Partial`.

**Comment by sandersn** [comment]
@wyqydsyq Your example doesn't include `Project` so I couldn't get your error to repro. Also I'm not sure what version of sequelize-typescript you are using.

**Comment by shaunxu** [comment]
@sandersn I had my @types/lodash updated to 4.14.129 and the error was still there

**Comment by pietschy** [comment]
@sandersn I was using `_.sortBy(..)` in lodash@4.17.4 and that was triggering the failure. The method signature was:
```
 sortBy<T>(
     collection: List<T> | null | undefined,
    ...iteratees: Array<Many<ListIteratee<T>>>
): T[];
```
I was passing an any as the second parameter and got the errors:
Error:(108, 2) TS2321: Excessive stack depth comparing types 'any' and 'Many<ListIteratee<T>>'.
Error:(108, 2) TS2321: Excessive stack depth comparing types 'any' and 'Many<ObjectIteratee<T[]>>'.

**Comment by vitaliusvs** [comment]
@sandersn Retested with typescript@3.4.5 and @types/lodash@4.14.132:

C:\...\server\node_modules\ts-node\src\index.ts:228
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS2321: Excessive stack depth comparing types 'any' and 'ListIterateeCustom<T, boolean>'.
error TS2321: Excessive stack depth comparing types 'any' and 'ObjectIterateeCustom<T[], boolean>'.

**Comment by kevinbeal** [comment]
I was using RecursivePartial to annotate mocks of services. I didn't want to build out something with the whole shape at every level. So something like this:

`{ a1: { b1: { c1: {} }, b2: { d1: {} } } }`

...when the only thing I'm actually testing with is that `d1` property--I didn't want to also add `b1`, `c1`, etc. Something this trivially small is okay, but larger objects would be a pain, especially considering the following.

Neither did I want to add an annotation for every level. Something like this: 

`{ prop: { something: 1 } as Partial<T['prop']> } as Partial<T>`

i.e. I didn't want to have to add `Partial<T['prop']>`.

The workaround you (@sandersn) showed would work in my case. Thank you :)

**Comment by sandersn** [comment]
@pietschy Here's what I tried with 4.14.132:

```ts
function f(a: any) {
    return _.sortBy([1,2,3], a)
}
```

But it seems fine. Can you try your code with `@types/lodash@4.14.132`?

@shaunxu @vitaliusvs Can you give short examples of the failing code? Was it similar to the above call to `sortBy` ?

**Comment by vitaliusvs** [comment]
Retested with typescript@3.5.1 and @types/lodash@4.14.132:

function test<T>(match?) {
    const items: T[] = undefined;
    return _.filter(items, match);
}

C:\...\server\node_modules\ts-node\src\index.ts:228
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS2321: Excessive stack depth comparing types 'any' and 'ListIterateeCustom<T, boolean>'.
error TS2321: Excessive stack depth comparing types 'any' and 'ObjectIterateeCustom<T[], boolean>'.

**Comment by pietschy** [comment]
Also retested with typescript@3.5.1 and @types/lodash@4.14.132 and still failing.

error TS2321: Excessive stack depth comparing types 'any' and 'Many<ListIteratee<T>>'.
error TS2321: Excessive stack depth comparing types 'any' and 'Many<ObjectIteratee<T[]>>'.

If you'd like access to the source let on bitbucket me know.

**Comment by sandersn** [comment]
Thanks, @vitaliusvs. Turns out the missing ingredient was that the first argument needs to be generic.

I'm sceptical that anybody actually relies on DeepPartial in lodash so I'm going to propose removing it and see what the maintainers of the types think.

**Comment by vitaliusvs** [comment]
Thanks, @types/lodash@4.14.133 has fixed this issue with lodash.

**Comment by shaunxu** [comment]
This error goes away after updated to `@types/lodash@4.14.133` thanks @vitaliusvs

**Comment by hswhite33** [comment]
Running into the same issue with `typescript@3.5.1` and `redux@4.0.1`. Redux also provides a `DeepPartial` type.

Example:

```
function foo<S>(reducer: Redux.Reducer<S>, initialState: S) {
	const middleware: Redux.Middleware<{}, S>[] = [];
	const compose = window['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'] || Redux.compose;
	return Redux.createStore(reducer, initialState, compose(Redux.applyMiddleware(...middleware)));
}
```

This actually results in excessive stack depth on both the second and third params of `createStore`:
* The second fails trying to compare `S` with `DeepPartial<S>`, and can be resolved by passing `initialState as unknown as Redux.DeepPartial<S>`
* The third fails trying to compare `any` with `DeepPartial<S>` and can be resolved by casting `compose` as `typeof Redux.compose`

This has gotten worse in one of the more recent TypeScript versions; with `typescript@3.1.6` I only needed to add `as any` to workaround the second parameter, and no workaround was necessary for the third.

Seems like this is a difficult problem on TypeScript's end so hopefully this workaround is useful to someone else in the meantime... Is this something I should be raising with the Redux maintainers?

**Comment by sandersn** [comment]
@hswhite33 Yes, the Redux maintainers should first consider whether they need the additional type safety or inference information that comes from DeepPartial. Redux users probably don't rely on it that much, actually.

If they want to keep it, they can use the workaround above, although it might break in future Typescript versions.

**Comment by Yaojian** [comment]
> I bet a $ that we will see a message: `sandersn (or whoever) modified the milestones: TypeScript 3.5.0, TypeScript 3.6.0` some day. 😿

I won but disappointed. 😭 

Now my questions is: Will it be moved to 3.7.0 😿 ? Should I bet 10$ ?

**Comment by alfaproject** [comment]
Just got hit by this in TS 3.6.2 which Renovate bot just attempted to update to and our pipeline failed. ):

It's not even our own code. It comes from one of the libraries that we use:
```
error TS2321: Excessive stack depth comparing types 'ElemMatch<?>' and 'ElemMatch<?>'.
error TS2321: Excessive stack depth comparing types 'InternalQuery<?>' and 'InternalQuery<?>'.
error TS2321: Excessive stack depth comparing types 'SiftQuery<?>' and 'SiftQuery<?>'.
```
https://github.com/crcn/sift.js/blob/ef8c5ca2e4b4277cf79085dd4168dbbe58ea4869/index.d.ts

**Comment by lukejagodzinski** [comment]
Is it a bug in TypeScript compiler or just libraries' code is faulty? Maybe TS team should come up with some guidance how to write code to avoid this bug if it's not an issue with tsc itself. It's really frustrating that it didn't get fixed yet

**Comment by sandersn** [comment]
@alfaproject you have a different issue. Notice that the two types are the same in your case. This is a known bug (#33132) with a fix at https://github.com/microsoft/TypeScript/pull/33144. We'll ship it in 3.6.3 in the next week or so.

**Comment by tomas-wrobel** [comment]
I hate this bug. The only thing is work agains it is `// @ts-ignore`

**Comment by sandersn** [comment]
Fixed in 3.7
