### ISSUE TITLE
TypeError: Cannot read property 'failedTypeParameterIndex' of undefined

### ISSUE THREAD

**Issue by panuhorsmalahti** [Microsoft/TypeScript#3464]
I'm getting this exception with TypeScript 1.5.0-beta when I'm creating a class which doesn't satisfy the constraits of the generic type.

```
C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14007
                    ts.Debug.assert(resultOfFailedInference.failedTypeParamete
                                                           ^
TypeError: Cannot read property 'failedTypeParameterIndex' of undefined
    at resolveCall (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14007:60)
    at resolveCallExpression (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14088:28)
    at getResolvedSignature (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14170:47)
    at checkCallExpression (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14186:29)
    at checkExpressionWorker (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14875:28)
    at checkExpressionOrQualifiedName (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14826:42)
    at checkExpression (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:14818:20)
    at checkExpressionStatement (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:15785:13)
    at checkSourceElement (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:16946:28)
    at Object.forEach (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:37:30)
    at checkBlock (C:\Projects\my_project\node_modules\typescript\bin\tsc.js:15551:16)
```

Unfortunately, I'm not able to create a small reproducable test case. It should be similar to this:
```
interface A {
    foo: any;
    bar: any;
}

interface C {
    prop: any;
}

interface B extends C {
    foo: any;
}

module Test {
    export class Foo<T extends A> {
    }
}

class Bar extends Test.Foo<B> {
}
```

but that reports the error correctly.

If I comment out lines 14007...14011 in my application's build, the error is reported correctly:
```
C:/Projects/my_project/lib/data_storage.ts(282,45): error TS2344: Type 'FooConfig' does not satisfy the constraint 'BarConfig'.
  Types of property 'foo' are incompatible.
    Type '{ service: { id: string; fooUri: string; barUri: string; }; otherProperty: { barUri: s...' is not assignable to type '{ service: { name: string; type: string; id: string; fooUri: string; barUri: string; ...'.
      Types of property 'service' are incompatible.
        Type '{ id: string; fooUri: string; barUri: string; }' is not assignable to type '{ name: string; type: string; id: string; fooUri: string; barUri: string; }'.
          Property 'name' is missing in type '{ id: string; fooUri: string; barUri: string; }'.
```

**Comment by danquirk** [comment]
I assume you're unable to share the full project with us in some form (privately if not posted publicly)? Do you still get the crash with the latest bits from ```master```?

**Comment by randombk** [comment]
I've also found this bug. This code triggers it:

```Typescript
class Foo {
    fooMethod() {} //There must be a method in Foo _not_ present in FooExtended
}

class FooExtended { }

class Bar<T extends Foo> { }

class BarExtended extends Bar<FooExtended> {
    constructor() {
        //This call to super() must be present in order to trigger the bug
        super();
    }
}
```

I've bisected it to 93dbcf006f3855c20f02e587970add1744cf32d1

**Comment by randombk** [comment]
I fixed the bug and created PR #3473

**Comment by panuhorsmalahti** [comment]
@danquirk That's correct, unfortunately I cannot share the code.

**Comment by mhegazy** [comment]
@panuhorsmalahti can you give the fix from @randombk a try and see if the problem still persists.

**Comment by davetayls** [comment]
I'm getting this, how can I track down the file causing the issue?

**Comment by mhegazy** [comment]
@davetayls what version of the compiler are you using? `tsc --version`?

**Comment by davetayls** [comment]
hey @mhegazy I am on 1.5.3

**Comment by mhegazy** [comment]
@davetayls can you share a repo?

**Comment by davetayls** [comment]
It's private unfortunately, I managed to track down the culprit by commenting out code till it worked! took a while :smile: 

It was strange because the underlying problem was that the class being passed to the generic had an import it was extending from where the path was broken. The generic constraint failed before the import path failed.

Don't know if that makes sense

**Comment by mhegazy** [comment]
@davetayls not really.. can you reproduce that with a minimal example?

**Comment by davetayls** [comment]
I'll sort out an example

**Comment by mhegazy** [comment]
thanks @davetayls! appreciate the help.

**Comment by davetayls** [comment]
Here you go https://github.com/davetayls/typescript-issue-3464

**Comment by mhegazy** [comment]
@davetayls i can not see any issues either with 1.5.3 or with latest from master. both give me an error for 
> MediaModel.ts(2,28): error TS2307: Cannot find module './BaseModelx'.
removing the `x` in the module import seems to work fine.

**Comment by davetayls** [comment]
I did a fresh `npm i -g typescript` before running `tsc`. I'll check the version. 

Are you definitely trying to compile the MediaStore.ts not the MediaModel.ts

You can see the output from my shell in the read me

**Comment by davetayls** [comment]
```
$ tsc --version
message TS6029: Version 1.5.3
$ ls
BaseModel.ts  MediaModel.ts MediaStore.ts ModelStore.ts
$ tsc --module commonjs --target es5 MediaStore.ts
/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:14169
                    ts.Debug.assert(resultOfFailedInference.failedTypeParamete
                                                           ^
TypeError: Cannot read property 'failedTypeParameterIndex' of undefined
    at resolveCall (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:14169:60)
    at resolveCallExpression (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:14250:28)
    at getResolvedSignature (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:14332:47)
    at checkCallExpression (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:14348:29)
    at checkExpressionWorker (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:15039:28)
    at checkExpressionOrQualifiedName (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:14990:42)
    at checkExpression (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:14982:20)
    at checkExpressionStatement (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:15952:13)
    at checkSourceElement (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:17118:28)
    at Object.forEach (/Users/davetayls/.nvm/versions/node/v0.12.6/lib/node_modules/typescript/bin/tsc.js:67:30)

```

**Comment by mhegazy** [comment]
aah.. i was trying on latest. sorry about the confusion. the issue has been fixed in master. can you give `typescript@next` a try.

**Comment by davetayls** [comment]
@mhegazy yep, i can confirm this is working on version 1.6.0-dev.20150815

**Comment by mhegazy** [comment]
thanks @davetayls!
