### ISSUE TITLE
Breaking change: Does not accept `"lib": ["ES5"],`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#16710]
**TypeScript Version:**  nightly (2.5.0-dev.20170616) (works in 2.5.0-dev.20170615)

**Code**

```ts
{
  "compilerOptions": {
    "lib": ["ES5"]
  }
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
tsconfig.json(3,13): error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'esnext', 'dom', 'dom.iterable', 'webworker', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'esnext.asynciterable'.
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
```

Probably related to #12336? @sheetalkamat

**Comment by mhegazy** [comment]
Looks like this is handled by https://github.com/Microsoft/TypeScript/pull/17755
