### ISSUE TITLE
Promise.all sometimes infers incorrect types

### ISSUE THREAD

**Issue by JavaScriptBach** [microsoft/TypeScript#52601]
# Bug Report

### 🔎 Search Terms

Promise.all, Awaited

### 🕗 Version & Regression Information

4.9.4

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

Simplified repro:
```ts
async function test() {
    const requests = ["a", "b", "c"].map(async doc =>
        fetch(doc)
    );
    const responses: Response[] = await Promise.all(requests);
}
```

### 🙁 Actual behavior

This code sometimes fails to build, with an error like this:
```
error TS2322: Type 'Promise<Response>[]' is not assignable to type 'Response[]'.
  Type 'Promise<Response>' is missing the following properties from type 'Response': headers, ok, redirected, status, and 11 more.
```

For some reason, the return type of `Promise.all(requests)` somehow gets evaluated to `Promise<Promise<Response>[]>` instead of `Response[]`.

It's difficult for me to reproduce this bug. A variant of this code compiles on CI under certain circumstances, but I had trouble getting it to consistently repro locally or to agree with VSCode's intellisense.

In such cases, I've had to workaround the problem by typing the `Promise.all()` call myself:

```ts
const response = await Promise.all<Response>(requests);
```

Downgrading to 4.8.4 makes this problem go away. I suspect this was caused by #50472 which changed the return type of `Promise.all` in `lib.es2015.iterable.d.ts` to `Promise<Awaited<T>[]>` from `Promise<T[]>`.

My guess is that this function has so many ambiguous overloads and generics that letting TypeScript infer the type no longer always does the right thing anymore.

### 🙂 Expected behavior

Code typechecks.

**Comment by JavaScriptBach** [comment]
Possibly also related to #51993

**Comment by RyanCavanaugh** [comment]
We'd need some way to reproduce this

**Comment by ritschwumm** [comment]
no idea whether this is helpful or even related:

in the past (probably 4.7.x or even 4.6.x) i had a vaguely similar problem _without_ Promise.all involved at all, just some large-ish function call expression being awaited, and tsc complaining it could not assign to the variable because the types were mismatched.

the interesting part was, that while
```
const xxx:SomeType = await something();
```
failed to compile,
```
const xxx = await something();
const yyy:SomeType = xxx;
```
worked perfectly fine, and at least in vscode the popup on xxx did show the expected type SomeType.
additionally,
```
const xxx:Promise<SomeType> = something();
```
worked fine, too.

to me the whole thing felt like the machanism behind `await` did something strange after looking into the expected type derived from the variable's type annotation, but as i have no idea how the actual implementation works, my assumption is probably completely wrong :)

**Comment by JavaScriptBach** [comment]
I think I found the issue. The problem is there are two overloads of `Promise.all()`, defined in separate files:

https://github.com/microsoft/TypeScript/blob/main/lib/lib.es2015.iterable.d.ts#L227
https://github.com/microsoft/TypeScript/blob/main/lib/lib.es2015.promise.d.ts#L41

The former is intended for arrays and the latter for tuples, but arrays are sometimes getting matched with the tuple overload.  Moving the definitions into the same file and declaring the array one first solved my issue.

(Per [Typescript docs](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering), TypeScript chooses the first matching overload, but I'm not sure what this behavior is if the overloads are specified in separate files. Probably it's undefined?)

**Comment by JavaScriptBach** [comment]
@RyanCavanaugh I've attached a repro to the issue. Hope you or someone else on the team could take a look. Thanks!

**Comment by wjaspers** [comment]
This is still prevalent in TS5.9.3.

[Playground Example](https://www.typescriptlang.org/play/?#code/AoJw9gtglgzgpgOhHGYA2A3OAKA5AFxX1wEoACAegrICkBXGfMgQzMZCgDsBzAKDIFkE+ABZxO2bOQC8APjKhIsRMzRpsAbX6Cdi6PCQp0WPM1IAabToF7lh1JhwbcAI1wBdElbKevO4WISmswASih0aPjmZC5hMBH4nmRyZADe3jqx4ZEIAA4MItih2fgkANyU1AAqAJ65cAAmZADGYCDIzfhoNd4AvuW8vLYGyA4mzoSMHuRUbPgcPBru3gHikjLywypqmhmCW-bGOLhmJJbW++D6iKNHmq7T3r4romvBcQnRWfGRSSnpFwE3wSeQKRQ+kXKlTItXqTS4rXacE63T6AyGVzst0c90mxCSs3YXG4SxegXWyU2mIMqnUWkBCmpNyMOJOFj2NiZhxxzjcnieJFWQQAHhsyKKZtR6IwyMh8HQQJwyK8yFx8vgyW8NMUflEYhDEmKAYDgTl8jBCjqElDZrDGi02h0uj0gA)

Related (to tuples):

https://github.com/microsoft/TypeScript/issues/51993

**Comment by RyanCavanaugh** [comment]
I wouldn't consider that example a bug, since it can be solved with `as const`.

```ts
Promise.resolve(['test']) // string[]
    .then(() => Promise.all([
        Promise.resolve('a'),
        Promise.resolve(['b'])
    ] as const))
    .then(([aResult, bResult]) => {
        bResult.push(aResult); // Typed incorrectly -> correctly
    });
```

**Comment by wjaspers** [comment]
Its just an oversimplification to minimize noise in the reproduction.

The real code I encountered is several async calls working together. One returns a singular string, the rest return string[]. 

What is weird to me is that this works if the Promise.all is immediately followed up by an identity function. 

When would someone naturally think to use `Promise.all([...]) as const` in their day to day work?

**Comment by fidian** [comment]
> This is still prevalent in TS5.9.3.
> 
> [Playground Example](https://www.typescriptlang.org/play/?#code/AoJw9gtglgzgpgOhHGYA2A3OAKA5AFxX1wEoACAegrICkBXGfMgQzMZCgDsBzAKDIFkE+ABZxO2bOQC8APjKhIsRMzRpsAbX6Cdi6PCQp0WPM1IAabToF7lh1JhwbcAI1wBdElbKevO4WISmswASih0aPjmZC5hMBH4nmRyZADe3jqx4ZEIAA4MItih2fgkANyU1AAqAJ65cAAmZADGYCDIzfhoNd4AvuW8vLYGyA4mzoSMHuRUbPgcPBru3gHikjLywypqmhmCW-bGOLhmJJbW++D6iKNHmq7T3r4romvBcQnRWfGRSSnpFwE3wSeQKRQ+kXKlTItXqTS4rXacE63T6AyGVzst0c90mxCSs3YXG4SxegXWyU2mIMqnUWkBCmpNyMOJOFj2NiZhxxzjcnieJFWQQAHhsyKKZtR6IwyMh8HQQJwyK8yFx8vgyW8NMUflEYhDEmKAYDgTl8jBCjqElDZrDGi02h0uj0gA)
> 
> Related (to tuples):
> 
> [#51993](https://github.com/microsoft/TypeScript/issues/51993)

There's nearly identical code in these three examples. It seems strange that only one of the examples is typed incorrectly. Please forgive me, but I would love to understand why this is not considered a bug with this unusual behavior.

1. When starting from `Promise<string>` it works. With `Promise<string[]>` , the type is lost after `Promise.all()` (see the difference between line 7 and line 10). Could you explain how this works?
2. With the third example, why would `.then(x => x)` fix the types when `x` is unchanged?
3. Why would `as const` be necessary? The example is dealing with an inline literal array, how can that be assigned to something else?
4. If the call to `Promise.all()` is pulled out to a `var` and returned, the type problems go away as well. This is the exact same value as returning the result from `Promise.all()`, so why would the types differ?

This behavior is inconsistent. A developer would have to employ a trick only when using `Promise.all()` in a promise chain when the prior resolved value is an array.

**Comment by wjaspers** [comment]
@RyanCavanaugh Could you please elaborate on @fidian 's questions? 

Type widening in the example above suggests it is hard to trust the order of Promise.all's arguments to `.then()`. This seems misleading.
