### ISSUE TITLE
JSDoc property description containing "@" character seems to make everything below this as undefined

### ISSUE THREAD

**Issue by pocesar** [microsoft/TypeScript#39976]
This is an issue with TS typings declarations generated from JSDoc and code analysis

**TypeScript Version:**  3.8.3

**Search Terms:** jsdoc property at @ description link markdown

**Code**

```js
/**
 * @typedef SomeTypeDef
 * @property {string} property1
 *   I'm a comment with an [@s](link)
 * @property {boolean} propertyCantBeAccessed
 */

/**
 * @param {SomeTypeDef} s
 */
const f = (s) => {
    s.propertyCantBeAccessed
}

f({
    property1: 'only exists here',
    propertyCantBeAccessed: false
})
```

**Expected behavior:**
The property exists and can be accessed

**Actual behavior:**
Code fails with `Property 'propertyCantBeAccessed' does not exist on type 'SomeTypeDef'`

**Comment by orta** [comment]
This is somewhat linked to https://github.com/microsoft/TypeScript/issues/37346 ( the `@description is basically treated as plain chars in that example )

**Comment by jakebailey** [comment]
Just looking at old issues; the original code no longer fails since #42364, but it's not actually fixed; add a space before the `@` and it becomes a jsdoc tag again.

[Playground Link](https://www.typescriptlang.org/play?ts=5.1.6&filetype=js#code/N4WAUABFEPQFR3NKcIAEAuBPADgUwBM8AzCAZQHsBbPAFVzwBESllU0cAnC-T7CYAGcMnAJYA7AOYBfCFx54+WAIytoqKAEkA5FQgBDCAGNqNcRggB3URgAWB8RADaaQQF0AFABsJAawCUaijo8rz8wABGFBReePrisqGK2ADC8RgAQngAgkZGeIKChEEQcDDgQfCIkGwh+pz6esCUNPT4zMSygiVlQSbiwhCkALwQHoL+EMMAfAIl0IIAdElKaeZZufmFxTVQ0hW7Qx6gh8gr2MoAXBDaFOJeWBB4AB6iwoIQtop42gA081Bzlg1pkcnkCkUCNdiPovEUgtJAmB9mBwCdkFUeuhsPgiKQWnQGB0sRxuGFHkIRBIZHIyckVFitLoDMZTHhzFYbPZ4s50O5vH4kchSiE6UoBFEYnEErSFKt0htwdsCD1yqjDpjTuwcPVGgICW0mCQuqq+ndBiMxhMprN0cKoEsgSDFVtIQiDshiMcAbLyVcbncHk9Xu9Pt8-j6nQqwa7CNDYfDDojwNIgA)
