### PR TITLE
Mark conditional extends as Unmeasurable and use a conditional-opaque wildcard for type erasure

### LINKED ISSUE #23352: `cb: (x: T) => void` not assignable to `cb: (x: T) => void` when it has an overload: "'any' is not assignable to 'never'"
**TypeScript Version:**  2.9.0-dev.20180411

**Code**

```ts
declare function provide<T>(cb: (x: T) => void): void;
declare function provide<T>(cb: (x: T[keyof T]) => void): void;

declare function provider<T>(provide: (cb: (x: T) => void) => void): void;
provider(provide);
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(4,10): error TS2345: Argument of type '{ <T>(cb: (x: T) => void): void; <T>(cb: (x: T[keyof T]) => void): void; }' is not assignable to parameter of type '(cb: (x: never) => void) => void'.
  Types of parameters 'cb' and 'cb' are incompatible.
    Types of parameters 'x' and 'x' are incompatible.
      Type 'any' is not assignable to type 'never'.
```

Worked in `typescript@2.9.0-dev.20180327`, broken in `typescript@2.9.0-dev.20180328`.

### LINKED ISSUE #31251: Comparison targets are reversed (regression)
The similar problem #30118 had been fixed, but appeared again.

**TypeScript Version:**  3.4.0-dev.20190504

**Search Terms:**

**Code**

https://github.com/falsandtru/spica/blob/v0.0.249/src/supervisor.legacy.ts#L56

**Expected behavior:**

pass

**Actual behavior:**

```
Argument of type 'this' is not assignable to parameter of type 'Supervisor<string, unknown, unknown, unknown>'.
  Type 'Supervisor<N, P, R, S>' is not assignable to type 'Supervisor<string, unknown, unknown, unknown>'.
    Type 'string' is not assignable to type 'N'.
      'string' is assignable to the constraint of type 'N', but 'N' could be instantiated with a different subtype of constraint 'string'.ts(2345)
```

**Playground Link:** 

**Related Issues:**

### LINKED ISSUE #43867: redux-orm broken by #43624
The nightly dtslint run for 4/28 fails on redux-orm, with new errors on examples like:

```ts
export default class Model<MClass extends typeof AnyModel = typeof AnyModel, Fields extends ModelFieldMap = any> {
    // ...
    readonly ref: Ref<this>;
    // ...
}
export class AnyModel extends Model {}
export type Ref<M extends AnyModel> = {
    [K in keyof RefFields<M>]: ModelFields<M>[K] extends AnyModel ? IdType<ModelFields<M>[K]> : RefFields<M>[K];
};
```

```
ERROR: 118:23  expect  TypeScript@4.3 compile error: 
Type 'this' does not satisfy the constraint 'AnyModel'.
  Type 'Model<MClass, Fields>' is not assignable to type 'Model<typeof AnyModel, any>'.
    Type 'typeof AnyModel' is not assignable to type 'MClass'.
      'typeof AnyModel' is assignable to the constraint of type 'MClass', but 'MClass' could be instantiated with a different subtype of constraint 'typeof AnyModel'.
```

Almost certainly a result of https://github.com/microsoft/TypeScript/pull/43624, but it could be #42449 or #43835, since they went in on the same day.

If this is an intended result of that PR, can you fix up redux-orm? A naive change to `Ref<M extends Model>` doesn't work.

### LINKED ISSUE #44945: Conditional types behavior is different when referencing same type with different name
# Bug Report

### 🔎 Search Terms
conditional types different name 

### 🕗 Version & Regression Information
v4.4.0-beta

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about *conditional types*

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-beta#code/C4TwDgpgBAMhBmwA8AtAfFAvFJAVNAFAJRYYG5QQAewEAdgCYDOUKUA-FAIxQBcUAJiIBuAFChIUAEoBLAOYALZOiw58xUlHKUa9Zqw7c+gkaPHhoAUQCOAVwCGAGy5IAGgBooATQzY4iNwxqWkYWWUVkH0NgACdbaH54JyYIMQkrOycBN08ovwRkVyDdUNgCpCjOWPjjJMcUsVEAeiaoOpTzSVcebBsHZyQAb3teJliZOjkAX09BmIh7BgB7OkcQKBGoMZiJ6bRm1uqITuhXAVU+rKGR7d2ZqDmF5dX1zdvJqbQgA)

### 💻 Code

```ts
type Left<Z> = <T>() => (T extends Z ? 1 : 2);
type Right<Z> = <T>() => (T extends Z ? 1 : 2);

type Equal1<X, Y> = Left<X> extends Right<Y> ? true : false;
type Equal2<X, Y> = Left<X> extends Left<Y> ? true : false;

// false
type X1 = Equal1<{a:string}, {readonly a: string}>
// true
type X2 = Equal2<{a:string}, {readonly a: string}>
```

### 🙁 Actual behavior
 
`X1` and `X2` is different.

### 🙂 Expected behavior

`X1` and `X2` is the same.

Actually, `Left` and `Right` are the same, `Equal1` and `Equal2` are the same.
But the result of `Equal1` and `Equal2` with the same parameters are different.

### PR DESCRIPTION
**Pull request by weswigham**
This PR is essentially #41067 + #31277, with a change added on top so it also fixes #43867.

Fixes #43867 (we always now reliably issue the correct error (which is a new thing), rather than just for variance comparisons, as in `master`)
Fixes  #23352 (we now use a wildcard marker for type erasure that is assignable to `never`, which allows overload resolution to process the overloads as we'd like)
Fixes #31251 (we now force a structural comparison when comparing type parameters which flow into conditional `extends` clauses (which require identical types))
Fixes #44945

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot pack this
@typescript-bot perf test this
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13788,7 +13791,10 @@ namespace ts {
             const includes = addTypesToUnion(typeSet, 0, types);
             if (unionReduction !== UnionReduction.None) {
                 if (includes & TypeFlags.AnyOrUnknown) {
-                    return includes & TypeFlags.Any ? includes & TypeFlags.IncludesWildcard ? wildcardType : anyType : unknownType;
+                    // A wildcard has the _lowest_ type id, as it's first types created, and it's made in priority order
+                    // - a normal `wildcardType` should take priority over an `opaqueWildcardType` if both somehoe end up
```
Comment (jack-williams) [inline src/compiler/checker.ts:13795]: somehow* end up

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -13629,7 +13632,7 @@ namespace ts {
             if (!(flags & TypeFlags.Never)) {
                 includes |= flags & TypeFlags.IncludesMask;
                 if (flags & TypeFlags.StructuredOrInstantiable) includes |= TypeFlags.IncludesStructuredOrInstantiable;
-                if (type === wildcardType) includes |= TypeFlags.IncludesWildcard;
+                if (type === wildcardType || type === opaqueWildcardType) includes |= TypeFlags.IncludesWildcard;
```
Comment (jack-williams) [inline src/compiler/checker.ts:13635]: Should this also set the `IncludesOpaqueWildcard` like the statements abit below?

Comment (weswigham) [reply src/compiler/checker.ts:13635]: It probably can. I was originally trying to avoid adding an extra includes flag, which, for unions, was possible by exploiting the sort order of the result set; however intersections are unsorted, so I had to add a flag to handle it there.

**Comment by sandersn** [comment]
Unfortunately, we never finished reviewing this PR. It is pretty old now, so I'm going to close it to reduce the number of open PRs.
