### ISSUE TITLE
`--forceConsistentCasingInFileNames` complains when given absolute paths with wrong casing

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#9934]
To reproduce (Windows only):

    cd C:\
    mkdir repro; cd repro
    echo "export default 0" > a.ts
    echo "import a from './a'" > b.ts
    tsc c:\repro\a.ts c:\repro\b.ts --forceConsistentCasingInFileNames

The error is:

    b.ts(1,15): error TS1149: File name 'C:/repro/a.ts' differs from already included file name 'c:/repro/a.ts' only in casing

**Comment by mhegazy** [comment]
I have not seen this happen since upgrading to node 6.7. can you reproduce it locally?

**Comment by andy-ms** [comment]
Testing with `typescript@next`, looks like it was broken in node `6.3.0` but works in `6.4.0`.
