### ISSUE TITLE
4.4 regression: `in` operator does not narrow types in generic constraints when destructuring

### ISSUE THREAD

**Issue by adalinesimonian** [microsoft/TypeScript#45762]
# Bug Report

### 🔎 Search Terms

in operator, narrowing, generics, constraints, destructuring

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAGlC8UDeUCGAuKBnYAnAlgHYDmUAvlAD7JQBGmOBJ5AUCwGYCuhAxsPgHtCULrwCMAHgAqUCAA9gEQgBMssAHwAKAG6oANpwiYpASmQsoUfOyiaA5KjtXhugxDNILlqDyE40CFCuhgB0qF6WvoRYAnoQIXoCxPaOADRoJl4UEHpY0J7ePn7AdIHB8bQRRdGx8YnJdrR26bSZlmQsHRzcfILCojwATNKyCkqqGjr6hsYeXta2Dk5EQdPu5oVR-iio5GVrVVu1CUkpzRlZsrn5h8U0tHuI5bc1cScNTS1trB1AA)

### 💻 Code

```ts
type X = { a: string } | { b: string }

// Works in 4.3.5 and 4.4.2
function func1<T extends X>(value: T) {
  if ('a' in value) {
    const a = value.a
    console.log('a', a)
  } else {
    const b = value.b
    console.log('b', b)
  }
}

// Works in 4.3.5, not in 4.4.2
function func2<T extends X>(value: T) {
  if ('a' in value) {
    const { a } = value // Property 'a' does not exist on type 'X'.(2339)
    console.log('a', a)
  } else {
    const { b } = value // Property 'b' does not exist on type 'X'.(2339)
    console.log('b', b)
  }
}

```

### 🙁 Actual behavior

Types are not narrowed when using destructuring assignment and the compiler throws error 2339.

### 🙂 Expected behavior

Types are narrowed when using destructuring assignment.

**Comment by andrewbranch** [comment]
I’d start by making sure `getNarrowableTypeForReference` is returning `X` rather than `T` for the reference `value`, since that’s what 4.3 added that makes this possible in the first place.

**Comment by a-tarasyuk** [comment]
> I’d start by making sure getNarrowableTypeForReference is returning X rather than T
 
@andrewbranch It seems this commit  https://github.com/microsoft/TypeScript/commit/0cc5c7bae9dfc0bee5693285c58e3962d7591784 changed `getNarrowableTypeForReference` behavior to returning `T` rather than `X` for binding patterns.

**Comment by andrewbranch** [comment]
I subsequently killed more contextual typing by binding patterns in #45719, not sure at a glance whether that will play a role here or not
