### ISSUE TITLE
error TS2531: Object is possibly 'null' when using | operator (strictNullChecks are off)

### ISSUE THREAD

**Issue by sweko** [Microsoft/TypeScript#14380]
I'm getting errors compiling after an update to 2.2.1.
The tsconfig.json file does not specify strictNullChecks, and the problem persists even when strictNullChecks are explicitly set to false.

**TypeScript Version:**  2.2.1

**Code**

```ts
console.log( 3 | null);
```

**Expected behavior:**
Successful compilation 
**Actual behavior:**
error TS2531: Object is possibly 'null'

**Comment by mhegazy** [comment]
did you mean `3 || null` ?

**Comment by sweko** [comment]
3 || null works as expected, but 3 | null does not.

In the specific case where I've encountered the issue, it was indeed an error where I've meant to do || but did | instead.
Nonetheless, I've gotten a build error on upgrading typescript, and this is not mentioned anywhere as a breaking change.

**Comment by gcnew** [comment]
It's caused by https://github.com/Microsoft/TypeScript/pull/13483 and is mentioned in What's new  in TypeScript - [Better checking for null/undefined in operands of expressions](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#better-checking-for-nullundefined-in-operands-of-expressions). Sure, it can be seen as a breaking change although the better interpretations seems to be an error that wasn't previously caught.
