### ISSUE TITLE
Retained binding patterns in declaration emit can require naming types that aren't exported (TS4023)

### ISSUE THREAD

**Issue by thempatel** [microsoft/TypeScript#63923]
### 🔎 Search Terms

- TS4023
- TS7056
- 4775,
- "destructuring declaration emit"
- "binding pattern declaration emit"
- "createSlice declaration"
- destructuring
- WritableDraft
- "cannot be named"
- "declaration emit"
- recreateBindingPattern
- "binding pattern"
- "TS4023 nightly"
- "export const destructuring d.ts regression"

### 🕗 Version & Regression Information

- This changed in commit or PR: https://github.com/microsoft/typescript-go/pull/4775
- Works correctly on 5.9.3, 7.0.2, and nightlies through 7.1.0-dev.20260728.1.

### 💻 Code

```ts
// src/lib.ts
type Hidden = { x: number; next: Hidden };

export type Names<T> = { [K in keyof T]: string };

export declare function make<T>(shape: T): Names<T>;

export declare const hidden: Hidden;
```

```ts
// src/main.ts
import { make, hidden } from "./lib";

export const { a, b } = make({ a: hidden, b: hidden });
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "declaration": true,
    "emitDeclarationOnly": true,
    "rootDir": "./src",
    "outDir": "./dist",
    "strict": true
  },
  "include": ["src"]
}
```

run `tsc -p .`

## Behavior with `tsgo`

```
src/main.ts(3,14): error TS4023: Exported variable '{ a, b }' has or is using name 'Hidden' from external module ".../src/lib" but cannot be named.
```

## Behavior with `typescript@6.0`

```ts
// dist/main.d.ts
export declare const a: string, b: string;
```

Same output on 5.9.3, 7.0.2, and nightlies through 7.1.0-dev.20260728.1.

### Additional information about the issue

> Disclosure: everything below was produced by an AI agent (Claude Code) — the reduction, the version matrix, the bisect, the root-cause analysis, and the patch at the end along with the testing behind it. The bug surfaced in a real upgrade of our monorepo; the investigation of it was not hand-written.

Bisected to 7.1.0-dev.20260730.1. The preceding nightly, 20260728.1, is fine. The change in that window is microsoft/typescript-go#4775 (d9773e3eb, merged 2026-07-29), which stops routing uninitialized binding patterns through `recreateBindingPattern`:

```go
-	if ast.IsBindingPattern(input.Name()) {
+	if ast.IsBindingPattern(input.Name()) && hasAnyBindingInitializers(input.Name().AsBindingPattern()) {
 		return tx.recreateBindingPattern(input.Name().AsBindingPattern())
 	}
```

The retained form serializes one type for the whole declaration, which here is the initializer's type `Names<{ a: Hidden; b: Hidden }>`. Printing that requires naming `Hidden`, and `lib.ts` doesn't export it. The old per-element form only ever needed each bound name's own type, which is `string`.

Note that this isn't about a bound name having an unnameable type. Each name is perfectly emittable on its own; only the combined type isn't.

That change came over with the repo merge unmodified; the predicate is byte-identical on this repo's `main` today, now at `tsc/internal/transformers/declarations/transform.go`.

`tsc/CHANGES.md` doesn't list this under intentional departures from 6.0, and its declaration emit section scopes the expected divergence to `.js`/JSDoc input. This repro is plain TypeScript.

## Where this came up

Upgrading a monorepo from 7.0.2 to the nightly. The real case is `export const { a, b } = slice.actions` with Redux Toolkit, where the retained type is `CaseReducerActions<{ /* reducer signatures */ }, "name">`. That type argument carries the reducers' `draft` parameters, so it reaches `WritableNonArrayDraft`, which immer declares but does not export. There's no change available to the user, short of hand-annotating every slice. On larger slices the same expansion also exceeds the serializer budget and reports TS7056.

Where the retained form does succeed, it's still a regression in output quality for this pattern: 7.0.2 emitted `ActionCreatorWithPayload<Payload, "name">` per action, and the nightly emits the reducer implementation signatures instead.

## A fix, tested on main

Serialize the retained form speculatively and fall back to `recreateBindingPattern` if it reported a declaration-emit diagnostic. Both failure modes here (`handleSymbolAccessibilityError` for TS4023, `ReportTruncationError` for TS7056) go through `state.addDiagnostic`, so one check covers both.

```diff
--- a/tsc/internal/transformers/declarations/transform.go
+++ b/tsc/internal/transformers/declarations/transform.go
@@ -837,9 +837,32 @@ func (tx *DeclarationTransformer) transformVariableDeclaration(input *ast.Variab
 	if tx.state.currentSourceFile.CommonJSModuleIndicator != nil && ast.IsVariableDeclarationInitializedToRequire(input.AsNode()) {
 		return tx.transformCjsRequireVariableDeclaration(input)
 	}
-	if ast.IsBindingPattern(input.Name()) && hasAnyBindingInitializers(input.Name().AsBindingPattern()) {
-		return tx.recreateBindingPattern(input.Name().AsBindingPattern())
-	}
+	if ast.IsBindingPattern(input.Name()) {
+		pattern := input.Name().AsBindingPattern()
+		if hasAnyBindingInitializers(pattern) {
+			return tx.recreateBindingPattern(pattern)
+		}
+		// Retaining the pattern means serializing one type for the whole declaration. That type can
+		// be unnameable here, or too large to serialize, even when every bound name has a perfectly
+		// nameable type of its own - e.g. `export const { a } = f()` where the return type of `f`
+		// mentions a type its own module doesn't export. Speculate, and fall back to a declaration
+		// per bound name when the whole-pattern type couldn't be written.
+		diagnosticMark := len(tx.state.diagnostics)
+		oldSuppressNewDiagnosticContexts := tx.suppressNewDiagnosticContexts
+		retained := tx.retainVariableDeclaration(input)
+		if len(tx.state.diagnostics) == diagnosticMark {
+			return retained
+		}
+		// Discard the diagnostics the failed attempt reported. Anything it marked visible stays
+		// marked: visibility is monotonic, and the fallback re-serializes the same underlying types.
+		tx.state.diagnostics = tx.state.diagnostics[:diagnosticMark]
+		tx.suppressNewDiagnosticContexts = oldSuppressNewDiagnosticContexts
+		return tx.recreateBindingPattern(pattern)
+	}
+	return tx.retainVariableDeclaration(input)
+}
+
+func (tx *DeclarationTransformer) retainVariableDeclaration(input *ast.VariableDeclaration) *ast.Node {
 	// Variable declaration types also suppress new diagnostic contexts, provided the contexts wouldn't be made for binding pattern types
 	tx.suppressNewDiagnosticContexts = true
 	return tx.Factory().UpdateVariableDeclaration(
```

This was developed and tested in `microsoft/typescript-go` before that repo closed, against `1bcfa18d7` with submodule `5848bc5157`. There it is `gofmt` clean, turns the repro above back into `export declare const a: string, b: string;`, and `TestLocal` and `TestSubmodule` both pass with zero local baselines written — no emitted baseline changes anywhere, including the cases #4775 added to `submoduleAccepted.txt`. Those all serialize their retained pattern successfully, so the fallback never fires for them and the accepted divergences from 6.0 stay as they are.

The diff above is that patch repathed for this repo's layout. It applies cleanly to `tsc/internal/transformers/declarations/transform.go` on `main` as of 2026-08-20, since the surrounding function is unchanged, but I have not re-run the test suite here — worth treating the baseline result above as evidence from the pre-merge tree rather than a green run on this one.

Two caveats on it. Rolling back `state.lateMarkedStatements` alongside the diagnostics seems natural but is wrong: `IsSymbolAccessible(..., shouldComputeAliasToMarkVisible: true)` is memoized in the checker, so the fallback pass sees "already accessible", never re-adds the aliases, and the emitted file loses its imports entirely. Leaving that state marked is the lesser problem, but it means an abandoned attempt can leave behind an unused type import in the output.

Restoring `suppressNewDiagnosticContexts` is load-bearing rather than tidiness. `retainVariableDeclaration` sets it and never restores it, which is pre-existing behavior since it's reset per source file, but left set the fallback's per-element `ensureType` calls would skip installing `createGetSymbolAccessibilityDiagnosticForNode` and inherit whatever context is current.

This is offered as a starting point rather than as a PR. Happy to discuss and push things forward if desired!

**Comment by jakebailey** [comment]
@weswigham

**Comment by weswigham** [comment]
This is working entirely as intended - the inferred type of that call to `Make` is `Names<{ a: Hidden; b: Hidden }>`, which we can't name. So you have to annotate it yourself - we no longer break down the declaration type (intentionally - we changed this to make isolated declarations work better) and emit inner types for the individual destructured names, intentionally.

Just add an explicit type annotation to the declaration.

> tsc/CHANGES.md doesn't list this under intentional departures from 6.0

Because it's a 7.1 bound change AFAIK. See the milestone on the PR.

**Comment by thempatel** [comment]
Thanks @weswigham
