### ISSUE TITLE
Error: node_modules/typescript/lib/lib.dom.d.ts:4179:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.

### ISSUE THREAD

**Issue by tco7878** [microsoft/TypeScript#47100]
# Bug Report

After upgrading from typescript 4.3.5 to 4.5.3 as well as Angular 12 to 13 we are now getting the following error when running ng build:

```
Error: node_modules/typescript/lib/lib.dom.d.ts:4179:11 - error TS2430: Interface 'Document' incorrectly extends interface 'FontFaceSource'.
  Types of property 'fonts' are incompatible.
    Type '{ ready: Promise<void>; } | undefined' is not assignable to type 'FontFaceSet'.
      Type 'undefined' is not assignable to type 'FontFaceSet'.
```

Opening lib.dom.d.ts in my IDE the error "Interface 'Document' incorrectly extends interface 'FontFaceSource'" is also displayed in line 4179. The issue occurs on every device even after running npm ci

**Comment by RyanCavanaugh** [comment]
This seems to be caused by `ng build` or something else in your toolchain
