### ISSUE TITLE
ts+yarn workspaces - relative import preferred over node_module imort

### ISSUE THREAD

**Issue by akomm** [microsoft/TypeScript#44007]
VSC: 1.55.2
For yarn, I'v also set `nodeLinker: node-modules`

When working with ts and yarn workspaces, example (`@project` is placeholder):

- packages/app -> linked to `node_modules/@project/app`
- packages/lib -> linked to `node_modules/@project/lib`

From inside `@project/app` i **can** manually import items from `@project/lib` and the typing works:
```ts
// this works manually, I can use item and it has typings (tsconfig strict, so no implicit any)
import {item} from '@project/lib'
```

However: I don't receive any fix proposal or auto-import for the it, instead I get proposed relative imports `../../lib/*` and the `@project/lib` import does not show up in the list of options

The lib package has also explicit `types` pointing to the d.ts that provides the items.

**Comment by akomm** [comment]
Oh. I'm a bit surprised. This is an issue in typescript?

**Comment by andrewbranch** [comment]
@akomm what version of yarn is embedded here?

**Comment by akomm** [comment]
I have yarn 2.4.1. and typescript@4.3.0-dev.20210505

**Comment by andrewbranch** [comment]
I just had two colleagues try the repro on Ubuntu and it’s working for them as well. I’m on macOS. To avoid executing the included copy of yarn (as a routine security precaution), these are the steps we took. You could try them to ensure there’s not something weird here:

* clone the repo
* delete `yarnPath` from `.yarnrc.yml`
* `rm -r .yarn`
* `npx yarn@berry set version berry`
* `yarn --version` - 2.4.1
* `yarn`

After that, can you share your TS Server logs with `index.ts` open? https://github.com/microsoft/TypeScript/wiki/Getting-logs-from-TS-Server-in-VS-Code

**Comment by akomm** [comment]
Problem persists. This is basically restart ts server and trigger the quick-fix and opening the logs (nothing privicy-critical inside and its not long, so I post it here):

```
Info 0    [13:49:23.516] Starting TS Server
Info 1    [13:49:23.516] Version: 4.3.0-dev.20210505
Info 2    [13:49:23.516] Arguments: /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/code-insiders /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/42b4dd7c213a1e87164d/tscancellation-11e13de89dc464e65d75.tmp* --logVerbosity verbose --logFile /home/andre/.config/Code - Insiders/logs/20210514T134321/exthost1/vscode.typescript-language-features/tsserver-log-mjHkIX/tsserver.log --globalPlugins typescript-vscode-sh-plugin --pluginProbeLocations /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/typescript-language-features --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation
Info 3    [13:49:23.516] Platform: linux NodeVersion: 14 CaseSensitive: true
Info 4    [13:49:23.516] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [13:49:23.522] Binding...
Info 6    [13:49:23.526] request:
    {"seq":0,"type":"request","command":"configure","arguments":{"hostInfo":"vscode","preferences":{"providePrefixAndSuffixTextForRename":true,"allowRenameOfImportPath":true,"includePackageJsonAutoImports":"auto"},"watchOptions":{}}}
Info 7    [13:49:23.527] Host information vscode
Info 8    [13:49:23.527] Host watch options changed to undefined, it will be take effect for next watches.
Info 9    [13:49:23.527] response:
    {"seq":0,"type":"response","command":"configure","request_seq":0,"success":true}
Perf 10   [13:49:23.527] 0::configure: async elapsed time (in milliseconds) 0.9492
Info 11   [13:49:23.527] request:
    {"seq":1,"type":"request","command":"compilerOptionsForInferredProjects","arguments":{"options":{"module":"commonjs","target":"es2020","jsx":"preserve","strictFunctionTypes":true,"sourceMap":true,"allowJs":true,"allowSyntheticDefaultImports":true,"allowNonTsExtensions":true,"resolveJsonModule":true}}}
Perf 12   [13:49:23.528] 1::compilerOptionsForInferredProjects: elapsed time (in milliseconds) 0.2481
Info 13   [13:49:23.528] response:
    {"seq":0,"type":"response","command":"compilerOptionsForInferredProjects","request_seq":1,"success":true,"body":true}
Info 14   [13:49:23.528] request:
    {"seq":2,"type":"request","command":"updateOpen","arguments":{"changedFiles":[],"closedFiles":[],"openFiles":[{"file":"/home/andre/code-insider-test/packages/app/index.ts","fileContent":"// it works, if you uncomment the import. \n// However there are no quick-fixes/auto-imports for it\n//import {Item} from \"@code-insider-test/lib\"\n\nconst i: Item = {}","projectRootPath":"/home/andre/code-insider-test","scriptKindName":"TS"}]}}
Info 15   [13:49:23.528] Search path: /home/andre/code-insider-test/packages/app
Info 16   [13:49:23.529] For info: /home/andre/code-insider-test/packages/app/index.ts :: Config file name: /home/andre/code-insider-test/packages/app/tsconfig.json
Info 17   [13:49:23.529] Creating configuration project /home/andre/code-insider-test/packages/app/tsconfig.json
Info 18   [13:49:23.530] FileWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/packages/app/tsconfig.json 2000 undefined Project: /home/andre/code-insider-test/packages/app/tsconfig.json WatchType: Config file
Info 19   [13:49:23.531] event:
    {"seq":0,"type":"event","event":"projectLoadingStart","body":{"projectName":"/home/andre/code-insider-test/packages/app/tsconfig.json","reason":"Creating possible configured project for /home/andre/code-insider-test/packages/app/index.ts to open"}}
Info 20   [13:49:23.538] Config: /home/andre/code-insider-test/packages/app/tsconfig.json : {
 "rootNames": [
  "/home/andre/code-insider-test/packages/app/index.ts"
 ],
 "options": {
  "strict": true,
  "configFilePath": "/home/andre/code-insider-test/packages/app/tsconfig.json"
 }
}
Info 21   [13:49:23.539] Loading global plugin typescript-vscode-sh-plugin
Info 22   [13:49:23.539] Enabling plugin typescript-vscode-sh-plugin from candidate paths: /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/typescript-language-features,/home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..
Info 23   [13:49:23.539] Loading typescript-vscode-sh-plugin from /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/typescript-language-features (resolved to /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/typescript-language-features/node_modules)
Info 24   [13:49:23.542] typescript-vscode-sh-plugin active for version < 4.2 and JS/JSX files. Current version : 4.3.0-dev.20210505
Info 25   [13:49:23.542] Intercepting getEncodedSemanticClassifications and getEncodedSyntacticClassifications.
Info 26   [13:49:23.542] Plugin validation succeeded
Info 27   [13:49:23.544] Starting updateGraphWorker: Project: /home/andre/code-insider-test/packages/app/tsconfig.json
Info 28   [13:49:23.549] DirectoryWatcher:: Added:: WatchInfo: /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules 1 undefined WatchType: node_modules for closed script infos in them
Info 29   [13:49:23.553] Elapsed:: 4.23204299993813ms DirectoryWatcher:: Added:: WatchInfo: /home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules 1 undefined WatchType: node_modules for closed script infos in them
Info 30   [13:49:24.102] DirectoryWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/packages/app/node_modules/@types 1 undefined Project: /home/andre/code-insider-test/packages/app/tsconfig.json WatchType: Type roots
Info 31   [13:49:24.102] Elapsed:: 0.4969499986618757ms DirectoryWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/packages/app/node_modules/@types 1 undefined Project: /home/andre/code-insider-test/packages/app/tsconfig.json WatchType: Type roots
Info 32   [13:49:24.102] DirectoryWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/packages/node_modules/@types 1 undefined Project: /home/andre/code-insider-test/packages/app/tsconfig.json WatchType: Type roots
Info 33   [13:49:24.102] Elapsed:: 0.08555999957025051ms DirectoryWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/packages/node_modules/@types 1 undefined Project: /home/andre/code-insider-test/packages/app/tsconfig.json WatchType: Type roots
Info 34   [13:49:24.103] Finishing updateGraphWorker: Project: /home/andre/code-insider-test/packages/app/tsconfig.json Version: 1 structureChanged: true Elapsed: 558.7879809997976ms
Info 35   [13:49:24.103] Project '/home/andre/code-insider-test/packages/app/tsconfig.json' (Configured)
Info 36   [13:49:24.104] 	Files (6)
	/home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.d.ts
	/home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts
	/home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts
	/home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	/home/andre/programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.scripthost.d.ts
	/home/andre/code-insider-test/packages/app/index.ts


	../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.d.ts
	  Default library
	../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.es5.d.ts
	  Library referenced via 'es5' from file '../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.d.ts'
	../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.dom.d.ts
	  Library referenced via 'dom' from file '../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.d.ts'
	../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.webworker.importscripts.d.ts
	  Library referenced via 'webworker.importscripts' from file '../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.d.ts'
	../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.scripthost.d.ts
	  Library referenced via 'scripthost' from file '../../../programme/code-insider-x64-1620279117/VSCode-linux-x64/resources/app/extensions/node_modules/typescript/lib/lib.d.ts'
	index.ts
	  Matched by include pattern 'index.ts' in 'tsconfig.json'

Info 37   [13:49:24.104] -----------------------------------------------
Info 38   [13:49:24.105] FileWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/packages/app/package.json 250 undefined WatchType: package.json file for import suggestions
Info 39   [13:49:24.106] FileWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/package.json 250 undefined WatchType: package.json file for import suggestions
Info 40   [13:49:24.108] FileWatcher:: Added:: WatchInfo: /home/andre/code-insider-test/packages/lib/index.d.ts 500 undefined WatchType: Closed Script info
Info 41   [13:49:24.108] Starting updateGraphWorker: Project: /dev/null/autoImportProviderProject1*
Info 42   [13:49:24.110] Finishing updateGraphWorker: Project: /dev/null/autoImportProviderProject1* Version: 1 structureChanged: true Elapsed: 1.8659719992429018ms
Info 43   [13:49:24.110] Project '/dev/null/autoImportProviderProject1*' (AutoImportProvider)
Info 44   [13:49:24.110] 	Files (1)
	/home/andre/code-insider-test/packages/lib/index.d.ts


	../lib/index.d.ts
	  Root file specified for compilation

Info 45   [13:49:24.110] -----------------------------------------------
Info 46   [13:49:24.110] event:
    {"seq":0,"type":"event","event":"projectLoadingFinish","body":{"projectName":"/home/andre/code-insider-test/packages/app/tsconfig.json"}}
Info 47   [13:49:24.111] event:
    {"seq":0,"type":"event","event":"telemetry","body":{"telemetryEventName":"projectInfo","payload":{"projectId":"5226ea00578033df3d2e2d6b009ba8d443a47aad140924eec71be125780e5d42","fileStats":{"js":0,"jsSize":0,"jsx":0,"jsxSize":0,"ts":1,"tsSize":164,"tsx":0,"tsxSize":0,"dts":5,"dtsSize":1049309,"deferred":0,"deferredSize":0},"compilerOptions":{"strict":true},"typeAcquisition":{"enable":false,"include":false,"exclude":false},"extends":false,"files":false,"include":true,"exclude":false,"compileOnSave":false,"configFileName":"tsconfig.json","projectType":"configured","languageServiceEnabled":true,"version":"4.3.0-dev.20210505"}}}
Info 48   [13:49:24.112] event:
    {"seq":0,"type":"event","event":"configFileDiag","body":{"triggerFile":"/home/andre/code-insider-test/packages/app/index.ts","configFile":"/home/andre/code-insider-test/packages/app/tsconfig.json","diagnostics":[]}}
Info 49   [13:49:24.112] Project '/home/andre/code-insider-test/packages/app/tsconfig.json' (Configured)
Info 49   [13:49:24.112] 	Files (6)

Info 49   [13:49:24.112] -----------------------------------------------
Info 49   [13:49:24.112] Project '/dev/null/autoImportProviderProject1*' (AutoImportProvider)
Info 49   [13:49:24.112] 	Files (1)

Info 49   [13:49:24.112] -----------------------------------------------
Info 49   [13:49:24.112] Open files: 
Info 49   [13:49:24.112] 	FileName: /home/andre/code-insider-test/packages/app/index.ts ProjectRootPath: /home/andre/code-insider-test
Info 49   [13:49:24.112] 		Projects: /home/andre/code-insider-test/packages/app/tsconfig.json
Perf 49   [13:49:24.112] 2::updateOpen: elapsed time (in milliseconds) 584.7808
Info 50   [13:49:24.113] response:
    {"seq":0,"type":"response","command":"updateOpen","request_seq":2,"success":true,"performanceData":{"updateGraphDurationMs":560.6539529990405,"createAutoImportProviderProgramDurationMs":5.230364998802543},"body":true}
Info 51   [13:49:24.113] event:
    {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":12175}}
Info 52   [13:49:24.122] request:
    {"seq":3,"type":"request","command":"projectInfo","arguments":{"file":"/home/andre/code-insider-test/packages/app/index.ts","needFileNameList":false}}
Perf 53   [13:49:24.122] 3::projectInfo: elapsed time (in milliseconds) 0.3009
Info 54   [13:49:24.122] response:
    {"seq":0,"type":"response","command":"projectInfo","request_seq":3,"success":true,"body":{"configFileName":"/home/andre/code-insider-test/packages/app/tsconfig.json","languageServiceDisabled":false}}
Info 55   [13:49:24.123] request:
    {"seq":4,"type":"request","command":"geterr","arguments":{"delay":0,"files":["/home/andre/code-insider-test/packages/app/index.ts"]}}
Perf 56   [13:49:24.123] 4::geterr: async elapsed time (in milliseconds) 0.4701
Info 57   [13:49:24.125] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/home/andre/code-insider-test/packages/app/index.ts","diagnostics":[]}}
Info 58   [13:49:24.132] event:
    {"seq":0,"type":"event","event":"semanticDiag","body":{"file":"/home/andre/code-insider-test/packages/app/index.ts","diagnostics":[{"start":{"line":5,"offset":10},"end":{"line":5,"offset":14},"text":"Cannot find name 'Item'.","code":2304,"category":"error"}]}}
Info 59   [13:49:24.133] event:
    {"seq":0,"type":"event","event":"suggestionDiag","body":{"file":"/home/andre/code-insider-test/packages/app/index.ts","diagnostics":[]}}
Info 60   [13:49:24.133] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":4}}

```

**Comment by andrewbranch** [comment]
@akomm I tried this again with the nightly version of TypeScript referenced in your TS Server log (4.3.0-dev.20210505), and it does reproduce for me now. However, it doesn’t reproduce with the 4.3.2 stable release. I think you just happened to get a nightly where things were temporarily broken. Let me know if you still get the issue with the latest TS version.

**Comment by akomm** [comment]
@andrewbranch thanks. The problem was not directly nightly, because I only installed it after I was asked to install vsc preview. It did not work in 4.2.* in general. 

I think it was just fixed at some point and my nightly version was a step to short of the nightly version you'v got in which it worked...

But now I have installed v. 4.3.2 and it works! Problem solved, thans.
