### ISSUE TITLE
Functions with optional arguments in union types not working

### ISSUE THREAD

**Issue by ivogabe** [Microsoft/TypeScript#4122]
I noticed the following gives an error when using typescript@next:
```typescript
var a: boolean | number;
a.toString(); // number#toString has an optional argument

var b: { foo(arg?: string): string } | { foo(): string };
b.foo();

var c: { foo(...args): string } | { foo(): string };
c.foo();

var d: ((arg?: string) => string) | (() => string);
d();
```
This used to work with 1.5.3, but with 1.6.0-dev.20150802 this gives the following errors:
```
test.ts(2,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
test.ts(5,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
test.ts(8,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
test.ts(11,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
```
Is this a bug?

**Comment by ahejlsberg** [comment]
This is a known effect of the changes in #3823. Some more details here:

https://github.com/Microsoft/TypeScript/pull/3823#issuecomment-122125926

We could trivially fix it for your `boolean | number` example just by adding a parameterless `toString()` method to the global `Number` interface. Are your other examples real world code, or just examples to illustrate the issue? We'd have to do more work to fix those, but it is not 100% clear what the right solution is for the general problem, particularly when the function types have overloads. We used to do subtype reduction on union types (i.e. remove types that are subtypes of other types) which so happens to help in your examples, but because it is a lossy transformation it produces issues in other scenarios.

**Comment by ivogabe** [comment]
The other examples were just to find out what was going on. I've only tested it on a small project, and I think that the other constructs might be used in some other projects. Anyway, I think at least the error message should be changed, as it's not helpful at the moment, but I'd prefer that this would be fixed. Could one of these two suggestions fix it?

1 - Expand optional arguments to overloads. For example, `(arg?: string): string` would be expanded to `((): string) & ((arg: string): string)`. The union will reduce that as expected: `((() => string) & ((arg: string) => string)) | (() => string)` collapses to `() => string`. Rest arguments can be a problem, as they need to be infinitely expanded.

2 - Make unions callable if all parts are callable with the specified signature. This is in line with assignability: `d` from the example is assignable to `() => string` because every part of the union is assignable. `d` would be callable with no arguments because every part is callable without arguments.

I think the second would be the easiest to implement. I can try to create a PR if you agree.

**Comment by ahejlsberg** [comment]
> Make unions callable if all parts are callable with the specified *signature*. This is in line with assignability: `d` from the example is assignable to `() => string` because every part of the union is assignable. `d` would be callable with no arguments because every part is callable without arguments.

Did you mean *parameter list* instead of *signature* above? In other words, require that the call can be resolved as written for each constituent type in the union type, and union together the results. Intuitively this seems like a good approach, but we may run into issues. For example, we have a core assumption that function expressions are contextually typed only once and then keep their assigned parameter types in all further analysis. That may become a problem in cases such as this:

```typescript
interface A { a: string }
interface B { b: string }
var func: { foo(cb: (x: A) => A): A } | { foo(cb: (x: B) => B): B };
obj.foo(x => x);
```

Above, we'd give type `A` to `x` when processing the first type in the union, but then that type would stick and we'd fail to resolve the call for the second type. Still, that may be ok. Certainly we'd succeed in a lot more cases than we do now.

@JsonFreeman may have an opinion.

**Comment by ivogabe** [comment]
I meant that indeed. That's an interesting question. When we're processing the union parts one by one, we could intersect all the resolved types. In your example, `cb` will be resolved to `(x: A) => A` and `(x: B) => B`, resulting into `((x: A) => A) & ((x: B) => B)` which would type `x` as `A | B`. Maybe this is to complicated and I think that supporting this case not wouldn't be a very big problem, as you pointed out (but it would be great if this would be possible).

**Comment by ahejlsberg** [comment]
I'm not actually suggesting we intersect the types. Once we have unions of types with multiple overloaded signatures or signatures with multiple parameters, intersecting isn't really an option.

What I'm proposing is actually rather simple. Say `obj` has type `X | Y | Z`. To resolve the call `obj.foo(...)` we would resolve the call three times, first giving `obj` type `X`, then type `Y`, then type `Z`, and if each of those calls resolve successfully, we'd union together the result types.

**Comment by ivogabe** [comment]
Sorry, I was referring to the inferring of `x` and `x => x` in your example. I agree with you about using unions for the return type.

About the inferring, the callback `x => x` would first be inferred to `(x: A) => A` and then `(x: B) => B`, and my suggestion would be to intersect these types to `((x: A) => A) & ((x: B) => B)`. That way we can infer `x` to `A | B`, but I'm not sure whether that would be too complex.

**Comment by JsonFreeman** [comment]
I like this idea, at least in theory. It aligns better with intuition than any of the union signature schemes we've had so far. And even with our current algorithm, "union signature annihilation" is still a problem.

However, I am worried about the contextual typing issue that @ahejlsberg mentioned. The problem is that the way function expressions get contextually typed works fine when **only one** of the signatures has to match the call (that is the policy for overload resolution). In other words, the fact that a function parameter gets contextually typed **only once** relies on the looseness of the requirement that **only one** signature has to match. But for our idea, multiple signatures may have to match, and so that's where the problem lies.

@ivogabe The intersection you mentioned for the callback `((x: A) => A) & ((x: B) => B)` does not actually make the parameter have type `A | B`, it makes the parameter have type `any`. This is because intersecting signatures forms an overload set, and a function expression can only be contextually typed by a type with a single signature. Would `any` be preferable to `A`? At least it would pass.

Maybe this problem is not so bad though. After all, a user passing a function expression can specify types for the parameters in complex cases like this. I don't think that is necessarily unreasonable.

**Comment by ahejlsberg** [comment]
Looking at the effects of this change I'm becoming less enamored with it. In addition to the issue with contextual typing, we'd also run into issues with statement completion (i.e. what list of signature would we show?). Plus there are quite a few places where we assume we can get a single list of call signatures from a type, all of which would need to be modified to handle union types.

I'm thinking it may be better to look at the partial signature matching we discussed [here](https://github.com/Microsoft/TypeScript/pull/3823#issuecomment-122132936). It would solve the original issue without a lot of downstream effects.

**Comment by JsonFreeman** [comment]
I agree that signature help could become very confusing with this proposal.

**Comment by JsonFreeman** [comment]
For the partial matches idea, the challenge would be that if we are trying to match some signature in the first constituent, then whether a match is found in another constituent could depend on a third constituent. For example:
```ts
var foo: ((x?: number) => void) | ((x?: string) => void) | (() => void)
foo();
```
In this case, the first and second constituent do have a match in a sense, even though the type of the parameter is not the same. But that is only true because the third constituent eliminates this parameter. So we somehow have to track the parameter index of the match as we traverse the constituents looking for matches. @ahejlsberg Do you think this would work?

**Comment by ahejlsberg** [comment]
@JsonFreeman I implemented this by looking for matches for *every* signature in *every* constituent type (instead of just looking for matches for signatures in the first constituent). A signature is matched by other signatures with extra optional parameters and/or different return type, and we don't process signatures with parameter lists that are already in the result set (i.e. the result set is deduplicated).

So, in your example above, only the third signature is considered to have matches in the other constituents, so it gets added to the result set with a union of `void | void | void` which collapses to just `void`.

**Comment by Tragetaschen** [comment]
Just to make sure I got this right:

As an example in D3, there are two types [Transition](https://github.com/borisyankov/DefinitelyTyped/blob/00c2478e989faab63b7f862ce385ec1989895d3e/d3/d3.d.ts#L807) and [Selection](https://github.com/borisyankov/DefinitelyTyped/blob/00c2478e989faab63b7f862ce385ec1989895d3e/d3/d3.d.ts#L437) which both share some function overload signatures in the `style` method. With this change, I can now build a union type and call a common style overload without getting TS2349?

If yes: Yay!

**Comment by ahejlsberg** [comment]
@Tragetaschen That is indeed the case. So: Yay! :smile:

**Comment by ivogabe** [comment]
Thanks!
