### PR TITLE
Migrate strict mode check

### PR DESCRIPTION
**Pull request by yuit**
Move strict mode check into type checker so we can give better error messages. This will be useful particularly when class declaration and ES6 module become strict mode code. One thing worth pointing out is that strict mode is a grammar check which means that if there is any parsing error, strict mode error will not get reported.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8337,10 +8340,23 @@ module ts {
         }
 
         function checkTypeReferenceNode(node: TypeReferenceNode) {
+            // Check if the type reference is using strict mode keyword
+            // Example:
+            //      class C {
+            //          foo(x: public){}  // Error.
+            //      }
+            if (node.typeName.kind === SyntaxKind.Identifier && (<Identifier>node.typeName).strictModeKind) {
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: this reads oddly.  Perhaps if this was .isKeywordInStrictMode instead?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -8337,10 +8340,23 @@ module ts {
...
         function checkTypeReferenceNode(node: TypeReferenceNode) {
+            // Check if the type reference is using strict mode keyword
+            // Example:
+            //      class C {
+            //          foo(x: public){}  // Error.
+            //      }
+            if (node.typeName.kind === SyntaxKind.Identifier && (<Identifier>node.typeName).strictModeKind) {
+                let typeName = <Identifier>node.typeName;
+                let nameText = declarationNameToString(typeName);
+                reportStrictModeGrammarErrorInClassDeclaration(typeName, Diagnostics.Type_expected_0_is_a_reserved_word_Class_definitions_are_automatically_in_strict_mode, nameText) ||
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: This needs to be "Type expected. '{0}' is a reserved word *in strict mode*. Class blah blah blah"

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -11915,6 +11934,94 @@ module ts {
...
+                        }
+                        return reportError;
+                    }
+                }
+            }
+            return false;
+        }
+
+        function checkGrammarDeclarationNameInStrictMode(node: Declaration): boolean {
+            let name = node.name;
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: This won't work for modules.  For example, if you have:

```ts
"use strict";
module public.whatever {
}
```

(make sure to add a test for this).

Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: This also won't work for a variable with a binding pattern.  For example:

```ts
"use strict";
var { public, private };
```

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -11915,6 +11934,94 @@ module ts {
...
+                switch (node.kind) {
+                    case SyntaxKind.Parameter:
+                    case SyntaxKind.VariableDeclaration:
+                    case SyntaxKind.FunctionDeclaration:
+                    case SyntaxKind.TypeParameter:
+                    case SyntaxKind.BindingElement:
+                    case SyntaxKind.InterfaceDeclaration:
+                    case SyntaxKind.TypeAliasDeclaration:
+                    case SyntaxKind.EnumDeclaration:
+                        let reportError = reportStrictModeGrammarErrorInClassDeclaration(<Identifier>name, Diagnostics.Identifier_expected_0_is_a_reserved_word_Class_definitions_are_automatically_in_strict_mode, nameText) ||
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: "is a reserved word *in strict mode*."

File: src/compiler/types.ts [hunk 5]
```diff
@@ -387,6 +387,7 @@ module ts {
 
     export interface Identifier extends PrimaryExpression {
         text: string;                 // Text of identifier (with escapes converted to characters)
+        strictModeKind?: SyntaxKind;  // TODO(yuisu): comment
```
Comment (CyrusNajmabadi) [inline src/compiler/types.ts]: Comment :)

File: src/compiler/parser.ts [hunk 6]
```diff
@@ -1485,6 +1486,11 @@ module ts {
             identifierCount++;
             if (isIdentifier) {
                 let node = <Identifier>createNode(SyntaxKind.Identifier);
+
+                // Set strictModeKind property so that we can report appropriate error later in type checker
+                if (inStrictModeContext() && (token > SyntaxKind.Identifier && token <= SyntaxKind.LastFutureReservedWord)) {
```
Comment (CyrusNajmabadi) [inline src/compiler/parser.ts]: I'm not sure i get this condition.  Can you explain why this is correct?

File: tests/baselines/reference/decoratorOnClassMethod3.errors.txt [hunk 7]
```diff
@@ -1,11 +1,29 @@
...
     declare function dec<T>(target: any, propertyKey: string, descriptor: TypedPropertyDescriptor<T>): TypedPropertyDescriptor<T>;
     
     class C {
         public @dec method() {}
         ~~~~~~
 !!! error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
-    }
\ No newline at end of file
+        ~~~~~~
+!!! error TS2304: Cannot find name 'public'.
```
Comment (CyrusNajmabadi) [inline tests/baselines/reference/decoratorOnClassMethod3.errors.txt]: this seems to have gotten worse...

File: src/compiler/parser.ts (hunk 6 above)
Comment (yuit) [inline src/compiler/parser.ts]: The check is that if we are in strict mode check if the token is a reserved words or strict mode reserved words. Reserved words and strict-mode reserved words are greater than identifier in SyntaxKind. However if we just check if the token is greater than Identifier, it will include contextual keyword as well.That is why we have to check that token is less than LastFutureReservedWord.

Comment (DanielRosenwasser) [inline src/compiler/parser.ts]: To make it clearer, I'd at least compare it to `FirstReservedWord`? Also, make your conditions as close to a 3-way inequality as possible (i.e. `blah < foo && foo <= bleep`).

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -8069,6 +8070,8 @@ module ts {
         // DECLARATION AND STATEMENT TYPE CHECKING
 
         function checkTypeParameter(node: TypeParameterDeclaration) {
+            checkGrammarDeclarationNameInStrictMode(node);
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: Good catch remembering to check this.  Is there a test for this as well?

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -8337,10 +8340,25 @@ module ts {
         }
 
         function checkTypeReferenceNode(node: TypeReferenceNode) {
+            // Check if the type reference is using strict mode keyword
+            // Example:
+            //      class C {
+            //          foo(x: public){}  // Error.
+            //      }
+            if (node.typeName.kind === SyntaxKind.Identifier) {
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: What about if you have:   ```foo(x: public.bar)``` ?

File: src/compiler/checker.ts [hunk 10]
```diff
@@ -10567,7 +10588,7 @@ module ts {
                     // export { x, y } from "foo"
                     forEach(node.exportClause.elements, checkExportSpecifier);
 
-                    let inAmbientExternalModule = node.parent.kind === SyntaxKind.ModuleBlock && (<ModuleDeclaration>node.parent.parent).name.kind === SyntaxKind.StringLiteral;
+                let inAmbientExternalModule = node.parent.kind === SyntaxKind.ModuleBlock && (<ModuleDeclaration>node.parent.parent).name.kind === SyntaxKind.StringLiteral;
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: fix.

File: src/compiler/checker.ts (hunk 8 above)
Comment (yuit) [inline src/compiler/checker.ts]: Yep

File: src/compiler/checker.ts (hunk 9 above)
Comment (yuit) [inline src/compiler/checker.ts]: That is a good one. Going to add into the test

File: src/compiler/checker.ts (hunk 10 above)
Comment (yuit) [inline src/compiler/checker.ts]: github decides to omit code so the indent looks wrong. I check the source code; it is fine

File: src/compiler/checker.ts [hunk 11]
```diff
@@ -11913,8 +11922,157 @@ module ts {
             anyArrayType = createArrayType(anyType);
         }
 
-
         // GRAMMAR CHECKING
+        function isReservedwordInStrictMode(node: Identifier): boolean {
+            // Check that originalStrictModeSyntaxKind is less than LastFurtureReservedWord to see if an Identifier is a strict-mode reserved word
+            if ((node.parserContextFlags & ParserContextFlags.StrictMode) && node.originalStrictModeSyntaxKind <= SyntaxKind.LastFutureReservedWord) {
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: can you simplify this to "return (node.parseContextFlags & ParserContextFlags.StrictMode) !== 0 && ..."

File: src/compiler/checker.ts [hunk 12]
```diff
@@ -11913,8 +11922,157 @@ module ts {
...
+                            return grammarErrorOnNode(name, Diagnostics.Identifier_expected_0_is_a_reserved_word_in_strict_mode, nameText);
+                        }
+                    }
+                    else if (nameBindings.kind === SyntaxKind.NamedImports) {
+                        let reportError = false;
+                        for (let element of (<NamedImports>nameBindings).elements) {
+                            let name = element.name;
+                            if (name.originalStrictModeSyntaxKind) {
+                                let nameText = declarationNameToString(name);
+                                reportError = grammarErrorOnNode(name, Diagnostics.Identifier_expected_0_is_a_reserved_word_in_strict_mode, nameText);
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: this should probably be |=

File: src/compiler/checker.ts [hunk 13]
```diff
@@ -11913,8 +11922,157 @@ module ts {
...
+            //          foo(x: public){}  // Error.
+            //      }
+            if (typeName.kind === SyntaxKind.Identifier) {
+                checkGrammarTypeNameInStrictMode(<Identifier>typeName);
+            }
+            // Report an error for each identifier in QualifiedName
+            // Example:
+            //      foo (x: public.private.bar)      // no Error
+            //      foo (x: public.private.package)  // error at package
+            else if (typeName.kind === SyntaxKind.QualifiedName) {
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: Youwant the opposite.   You want to error on *public*, and not on 'private' or 'package'.

File: src/compiler/checker.ts [hunk 14]
```diff
@@ -11913,8 +11922,157 @@ module ts {
...
+                // Report strict mode at the property of memberExpression
+                // Example:
+                //      x1: public.private.package // error at package as memberExpression can be IdentifierName
+                checkGrammarTypeNameInStrictMode((<QualifiedName>typeName).right);
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: Instead, call: checkGrammarTypeReferenceInStrictMode((<QualifiedName>typeName).left)

File: src/compiler/checker.ts [hunk 15]
```diff
@@ -11913,8 +11922,157 @@ module ts {
...
+            if (expression && expression.kind === SyntaxKind.Identifier) {
+                return checkGrammarIdentifierInStrictMode(expression);
+            }
+            else if (expression && expression.kind === SyntaxKind.PropertyAccessExpression) {
+                let propertyAccessExp = <PropertyAccessExpression>expression;
+
+                // Report strict mode at the property of memberExpression
+                // Example:
+                //      public.private.package  // error at package as memberExpression can be IdentifierName
+                checkGrammarIdentifierInStrictMode((<PropertyAccessExpression>expression).name);
```
Comment (CyrusNajmabadi) [inline src/compiler/checker.ts]: again, the reverse.  You want to walk down the *left* side.

File: src/compiler/parser.ts [hunk 16]
```diff
@@ -1485,6 +1486,11 @@ module ts {
             identifierCount++;
             if (isIdentifier) {
                 let node = <Identifier>createNode(SyntaxKind.Identifier);
+
+                // Store original token kind if it is not just an Identifier so we can report appropriate error later in type checker
+                if (token !== SyntaxKind.Identifier) {
+                    node.originalStrictModeSyntaxKind = token;
```
Comment (CyrusNajmabadi) [inline src/compiler/parser.ts]: This is probably better named as originalKeywordKind or originalKeywordSyntaxKind.

File: src/compiler/checker.ts (hunk 14 above)
Comment (yuit) [inline src/compiler/checker.ts]: For TypeReference, according to TypeScript, we want to check each identifier in QualifiedName

**Comment by Arnavion** [comment]
@CyrusNajmabadi @yuit

With this change, `import * as set from "set";` no longer compiles - `error TS1212: Identifier expected. 'set' is a reserved word in strict mode` (because name.originalKeywordKind is set to SetKeyword). Is this intentional? Or should the checks for originalKeywordKind check that it's between First and LastKeyword/ReservedWord/FutureReservedWord before generating the diagnostic?

Such code compiles with 1.5 alpha with no issue.
