### ISSUE TITLE
3.9 regression: bogus property-will-be-overwritten-by-spread errors

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#36779]
```ts
export class Terror extends Error {
    public get telemetry() {
        return { command: "bye", ok: "next" }
    }
}
function g(u: unknown, b: boolean, t: Terror) {
    return { command: "hi", ...(b ? t.telemetry : {}) }
}
```

**Expected behavior:**

No error; `command` is not necessarily overwritten, for example when `b=false`.

**Actual behavior:**

Error: 'command' is specified more than once, so this usage will be overwritten.

User tests vscode and office-fabric-ui have failures because of this.

**Comment by DanielRosenwasser** [comment]
To clarify, this isn't a 3.8 RC issue, right?

**Comment by sandersn** [comment]
Yep, that's why I put '3.9' in the title.

**Comment by JakeGinnivan** [comment]
Our code base got hit by this as well when trying out the latest @next build. Mainly in options objects and css in JS when you provide a default and spread an object which can optionally specify a key.

**Comment by mvestergaard** [comment]
I think this might still be an issue in JSX?
I've tried upgrading our code base to both `@beta` and `@next` and they both give me these kinds of errors in any JSX that specifies a prop which could be overwritten by a spread:
```
src/features/search/components/SearchResult/SearchResult.tsx:89:92 - error TS2783: 'alignItems' is specified more than once, so this usage will be overwritten.

89   <Box flex="0 0 auto" display="flex" flexDirection="column" justifyContent="space-evenly" alignItems="flex-end" {...rest}>
                                                                                              ~~~~~~~~~~~~~~~~~~~~~
```

**Comment by janicduplessis** [comment]
I'm also getting a few of those since updating to 3.9-beta. Seems related to `any` type usage.

```ts
type Props = {
  someProp?: any;
};
function Component(props: Props) {
  return <View {...props} someProp={{}} />
}
```

Using another type instead of `any`, for example `object` does not trigger the error.

**Comment by bradleyayers** [comment]
@janicduplessis I'm not sure if this will be on their radar, given this issue is closed. Perhaps open a new issue?

**Comment by sandersn** [comment]
@janicduplessis please do; I tried a simple repro like yours but couldn't get it to work since I don't have `View` declared.

I just merged a fix from a community member that might help, but it didn't make the beta. Can you try `typescript@next` before filing the bug?

**Comment by mvestergaard** [comment]
@sandersn Here's a small reproduction repo

**Comment by janicduplessis** [comment]
@sandersn Thanks for checking into it, could have made a better repro. See #37740

**Comment by JoeSchr** [comment]
I also have this, but I don't see store getting overwritten...
```TS
    const store = provideClearingStore(ctx, nuxtInject);
    const apolloClient = provideVueApolloComposable(ctx);
    (ctx as any).store = store; // delete vuex
    provideGlobalsForCypress({ store, apolloClient, ...ctx });
    return { store, apolloClient };
```

Error:
```TS
 13:32 'store' is specified more than once, so this usage will be overwritten.
     11 |     const apolloClient = provideVueApolloComposable(ctx);
     12 |     (ctx as any).store = store; // del files.ete vuex
   > 13 |     provideGlobalsForCypress({ store,apolloClient, ...ctx });
        |                                ^
     14 |     return { store, apolloClient };   provide-globals-once.ts(13,32):
     15 |   };                                  his usage will be overwritten.
     16 | };   

```

**Comment by JoeSchr** [comment]
AH, I get it, it's also in my `ctx` which also get spread in and since I casted it to any before, TS doesn't get it. Sorry for the noise
