### ISSUE TITLE
TypeScript 5.5 Iteration Plan

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#57475]
This document outlines our focused tasks for TypeScript 5.4. It minimally indicates intent to investigate tasks or contribute to an implementation. Nothing is set in stone, but we will strive to complete these tasks in a reasonable timeframe.

Date           | Event
---------------|-------------------------
2024-03-05     | TypeScript 5.4 Release
2024-04-12     | Create 5.5 Beta (5.5.0) Build for Testing
2024-04-16     | **TypeScript 5.5 Beta Release**
2024-05-31     | Create 5.5 RC (5.5.1) Build for Testing
2024-06-04     | **TypeScript 5.5 RC Release**
2024-06-14     | Create 5.5 Final (5.5.2) Build for Testing
2024-06-18     | **TypeScript 5.5 Final Release** 🚀

```mermaid
gantt
    dateFormat  YYYY-MM-DD
    TypeScript 5.4 Stabilization Period : 2024-02-16, 2024-03-05
    TypeScript 5.5 Beta Development : 2024-02-16, 2024-04-12
    TypeScript 5.5 RC Development : 2024-04-13, 2024-05-31
    TypeScript 5.5 Stabilization Period : 2024-06-01, 2024-06-18
todayMarker stroke-width:5px,stroke:#0f0,opacity:0.5
```

# Compiler and Language

* [The `--isolatedDeclarations` Flag](https://github.com/microsoft/TypeScript/pull/53463)
* [Type-Only Imports in JSDoc](https://github.com/microsoft/TypeScript/pull/57207)
* [Non-Null Assertions in JSDoc](https://github.com/microsoft/TypeScript/pull/57207)
* [Regex Syntax Validation](https://github.com/microsoft/TypeScript/pull/55600)
* [Checks for Never-Initialized Variables](https://github.com/microsoft/TypeScript/pull/55887)
* [Allow Implementing Functions That Return Conditional Types](https://github.com/microsoft/TypeScript/issues/33014)
* [Improvements in Extending `tsconfig.json` Files](https://github.com/microsoft/TypeScript/issues/56436)
* [Investigate Recursive Object Type References](https://github.com/microsoft/TypeScript/issues/57034)
* [Investigate Speculation Infrastructure for Overload Resolution](https://github.com/microsoft/TypeScript/pull/57421)
* [Provide Better `default` Import Interop Configurability](https://github.com/microsoft/TypeScript/issues/54102)
* [Improve `default` Import Detection from ECMAScript Modules](https://github.com/microsoft/TypeScript/issues/54752)
* [ECMAScript `Set` Methods](https://github.com/microsoft/TypeScript/pull/57230)
* [`lib.d.ts` Updates](https://github.com/microsoft/TypeScript/issues/57474)
* [Removal of 5.0-Deprecated Functionality in 5.5](https://github.com/microsoft/TypeScript/issues/51909)

# Editor and Language Service

* [Auto-Import on Paste](https://github.com/microsoft/TypeScript/issues/50187)
* [Region-Prioritized Error Checking](https://github.com/microsoft/TypeScript/issues/57393)
* [Investigate AI-powered Refactorings](https://github.com/microsoft/vscode/issues/182779)
* [Provide Code Action Ranges](https://github.com/microsoft/TypeScript/issues/57264)
* [TSServer File-Watching Events](https://github.com/microsoft/vscode/pull/193848)
* [Improve Organize Import Ordering](https://github.com/microsoft/TypeScript/issues/57030)
* [Investigate Simpler Quick Fix API](https://github.com/microsoft/TypeScript/issues/46249)
* [Define Initial Sketch of LSP Support](https://github.com/microsoft/TypeScript/issues/39459)

# Performance

* [More Caching in `--incremental` Mode](https://github.com/microsoft/TypeScript/pull/55968)
* Improved Performance for Git Branch Switching Scenarios
* [Investigate Running With V8 Snapshots](https://github.com/microsoft/TypeScript/pull/55830)

# Website and Docs

* [Simplify and Refactor Website for Faster Builds](https://github.com/microsoft/TypeScript-Website/issues/2730)

# Infrastructure

* Adopt `--isolatedDeclarations` and Parallelize TypeScript's Build

**Comment by DanielRosenwasser** [comment]
[The last iteration plan is available here](https://github.com/microsoft/TypeScript/issues/56948).

**Comment by kevinbarabash** [comment]
How much of an impact will `--isolatedDeclarations` have on type checking performance in large projects?

**Comment by jakebailey** [comment]
None directly, in the same way that `isolatedModules` doesn't speed things up in and of itself.

But, if you have code which passes `isolatedModules`, it can be safely transpiled by an external tool (like Babel, esbuild, swc). And similarly, code passing `isolatedDeclarations` can be transpiled into a declaration file by an external tool too (once one exists).

**Comment by jakebailey** [comment]
(This isn't to say that there can't be some speedups possible in TypeScript in the future enabled by this option, just that the flag itself is intended to just be checks.)

**Comment by JVKdouk** [comment]
Hey everyone, any chance of getting #26242 in this release? It was proposed back in 2018 and there has not been much work on the issue up to this point. I believe it would substantially improve the power of TS in the long run!

**Comment by ClearedFram3** [comment]
Just a heads up, I'm working on remaking the website using Sveltekit. Styles will be the same, but the overall structure will be simpler and much quicker to iterate on.

**Comment by DanielRosenwasser** [comment]
@ClearedFram3 while I don't want to encourage experimentation, I don't think we would accept such a large PR without discussing changes ahead of time.

**Comment by ClearedFram3** [comment]
@DanielRosenwasser I should've said the codebase structure will be different—the website style/content structure will be the same. After the current codebase is replaced, there will ample room for discussion about changing design and content or even to a different framework haha.

**Comment by graphemecluster** [comment]
I’ve been watching the iteration plan threads from 5.4 seeing my PR (#55600) on the list. I am on standby anytime for any necessary alternations from now, at least in March.

**Comment by jwalkerinterpres** [comment]
Is there anything Typescript community members can do to influence this list?

I think I can speak for every React dev on the planet when I say that https://github.com/microsoft/TypeScript/issues/29526 (improved syntax for destructuring an argument ... like the React `props` argument) has languished long enough.  The community has essentially reached a consensus on a desired syntax in that ticket (something that was *not* easy), and now all that's needed is developer will to implement.

I can't speak for anyone else, but personally I would trade *everything* on the 5.5 list for this one feature!

**Comment by aspirisen** [comment]
A question about [Investigate Recursive Object Type References](https://github.com/microsoft/TypeScript/issues/57034)
Will it help i.e. in [zustand](https://docs.pmnd.rs/zustand/guides/typescript) in avoiding writing interface for the state, and instead just infer the type from the initial state (create-function argument)?

**Comment by jcalz** [comment]
> * [Allow Implementing Functions That Return Conditional Types](https://github.com/microsoft/TypeScript/issues/33014)

Cross-linking #33912 and #56941

**Comment by narcis-ro** [comment]
Is there any chance after 10 years.. to introduce nameof?

Is it super complicated? Honest question

https://github.com/microsoft/TypeScript/issues/1579

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-5.4

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-5.4

**Comment by DanielRosenwasser** [comment]
Whoops - I've been posting in the wrong iteration plan. Sorry for the noise folks.

**Comment by nyngwang** [comment]
> I think I can speak for every TS React dev on the planet when I say that #29526 (improved syntax for destructuring an argument ... like the React `props` argument) has languished long enough.

I can't disagree more with all existing proposals in #29526. It will make TypeScript syntax very confusing.

TypeScript will make people's code type-safe. TypeScript will not make people's code confusing. All existing proposals are confusing.

Personally, I treat the parameter destructuring syntax as an anti-pattern. It's already a confusing shorthand syntax that looks like something half-done when you only rename a subset of the properties. Now they're proposing `old:new:Type` and `old::string`, etc to make it even more confusing. Optional rename in the middle? NO! No one will intuitively know that `string` here is to mark the `old` name as `string`! What were they doing!?

Without it, the problem of working with the destructing syntax can already be solved by extracting those in-place object types into standalone `type`s or `interface`s. It might be tedious for some, but at least it's NOT confusing, at all!

With any of those existing proposals, it will be really, really confusing. And you need to introduce a set of new rules. It does not solve any hard problems.

Not to make anyone feel bad. But it's important to consider different voices. TypeScripts will be fine without it.

Sincerely, and thanks for your reading.

**Comment by WORMSS** [comment]
> > I think I can speak for every TS React dev on the planet when I say that #29526 (improved syntax for destructuring an argument ... like the React `props` argument) has languished long enough.
> 
> I can't disagree more with all existing proposals in #29526. It will make TypeScript syntax very confusing.

This is the first I am hearing about this.. (I guess I've had my head in the sand for a while).. We already have a solution to this.. `({ a, b }: SomeType) => void`.. This makes sense, and already works.. 
This sounds like a massive problem waiting to happen if this gets implemented the way people are saying.

This type of stuff is going to push the whole "Javascript can run TS script directly, but just ignoring the types" concept even FURTHER AWAY! 
It seems like shooting yourself in the foot to try and solve something that is already solved.

**Comment by snarbies** [comment]
> But it's important to consider different voices.

Then why not add your voice to that issue? Respond to the arguments and examples presented there, there.

> This type of stuff is going to push the whole "Javascript can run TS script directly, but just ignoring the types" concept even FURTHER AWAY! 

Again, if you join the actual discussion you can respond to people who are addressing this exact concern (https://github.com/microsoft/TypeScript/issues/29526#issuecomment-1950286449). The only argument I see in that issue is that the double-colon syntax may actually *benefit* this cause. If there's an argument to the contrary, you should make it there so it can be properly considered.

**Comment by nyngwang** [comment]
@jwalkerinterpres 

> I think I can speak for every TS React dev on the planet

You can't, and you will not be able to.

**Comment by DanielRosenwasser** [comment]
For anyone here for the iteration plan: we are going to push the beta out about a week to make sure we can bring in some scheduled work.

**Comment by DanielRosenwasser** [comment]
@typescript-bot create release-5.5

**Comment by DanielRosenwasser** [comment]
No, bad.

**Comment by DanielRosenwasser** [comment]
Jake says he fixed it. @typescript-bot tell @jakebailey thank you and also

@typescript-bot create release-5.5

**Comment by WORMSS** [comment]
Surely there is a better way to interact with a bot than to have multiple people emailed about every request and then every response?

**Comment by Aloso** [comment]
@WORMSS but you can disable notifications for this thread (or limit them to \@mentions), if you don't want to be notified about new activity.
The bot exists to help contributors, who *do* want to get notified about messages from the bot.

**Comment by WORMSS** [comment]
I don't mind getting notifications.. don't want to get a notification about people talking TO the bot..

**Comment by Aloso** [comment]
GitHub doesn't provide such a feature. And I don't understand your complaint, it is just a minor inconvenience for you, but a big help for contributors.

**Comment by DanielRosenwasser** [comment]
Hey all, 5.5 Beta is now out!

- Blog post: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/
- Release tag: https://github.com/microsoft/TypeScript/releases/tag/v5.5-beta

**Comment by Jack-Works** [comment]
for anyone founding their `.d.ts` file augmentation no longer working (a breaking change not mentioned in the blog), see https://github.com/microsoft/TypeScript/issues/58324

**Comment by DanielRosenwasser** [comment]
@typescript-bot sync release-5.5

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-5.5

**Comment by Stam098c** [comment]
![OKX_1717516680882.jpg](https://github.com/microsoft/TypeScript/assets/139982250/a5373845-3a8d-4a07-b1f4-6bcd3c4f96cc)

**Comment by AlttiRi** [comment]
> 2024-06-04	**TypeScript 5.5 RC Release**

There will no `5.5.0-rc` on NPM?
https://www.npmjs.com/package/typescript?activeTab=versions

Only `5.5.0-beta` until  `5.5.0` is released?

**Comment by DanielRosenwasser** [comment]
Hey all, my apologies on the delays - that's mostly on me, but as always, I'll note that the schedule is aspirational and not a promise on exact dates.

`5.5.1-rc` is now on npm - the blog post and the tagged release will be out on GitHub soon. Thanks for your patience!

**Comment by DanielRosenwasser** [comment]
[The blog post is out for the RC](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-rc/), as is the git tag `v5.5-rc` (and [GitHub release](https://github.com/microsoft/TypeScript/releases/tag/v5.5-rc)).

**Comment by DanielRosenwasser** [comment]
The RC got pushed back 2 days (June 6th) (typical) so the stable release will go out 2 days later (June 20th) (typical).

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-5.5

**Comment by Anonymous4078** [comment]
```js
Property 'once' does not exist on type 'EventEmitter'. Did you mean to access the static member 'EventEmitter.once' instead?
``` 
I am get this error after update to 5.5.2? My code has not change. How fix?

**Comment by Anonymous4078** [comment]
Pls fix

**Comment by DanielRosenwasser** [comment]
@Anonymous4078 if you are having problems and you believe you're hitting a bug, please file a separate issue.

**Comment by HolgerJeromin** [comment]
Was 5.5.2 withdrawed? 
I can not find it on [nuget.org](https://www.nuget.org/packages/Microsoft.TypeScript.MSBuild) anymore and it crashes Intellisense in my VS2022 Version 17.10.3 (on 4 machines)

**Comment by DanielRosenwasser** [comment]
@HolgerJeromin yes, there was an issue with the NuGet package due to assumptions of the internal layout for TypeScript. @joj and others are investigating that.

**Comment by kronodeus** [comment]
@DanielRosenwasser What is the status of the LSP support in this release? I see it in the iteration plan to "define an initial sketch" but there's nothing about it in the release notes. Are we any closer to getting it?

**Comment by jakebailey** [comment]
These iteration plans are only a prospective list; in this case I had other critical work that preempted me working on anything tangible LSP.

What use case do you have where LSP would be valuable?

**Comment by kronodeus** [comment]
@jakebailey We met with Daniel a few months ago to discuss our project. It's a TypeScript-based DSL with a custom file extension for which we need to implement our own VS Code extension. Our DSL is a subset of TypeScript so we need to disallow certain things and provide custom completions, etc. We implemented some of this as a `tsserver` plugin, but we don't want our customers to have `tsconfig.json` files in their projects. We don't intend to provide any of the same configuration options you get with a `tsconfig.json`. We have our own config file. We want them to simply install the VS Code extension and for everything to work.

It is possible to load a `tsserver` plugin inside a VS Code extension without requiring the user to have a `tsconfig.json`, but since there is only one instance of `tsserver` running at a time in VS Code, this plugin would then be active for all of the user's TypeScript projects unless they disable the extension.

Our options are thus: (A) Fork the internal `typescript-language-features` extension, (B) implement an extension from scratch using a community-developed LSP wrapper like [vtsls](https://github.com/yioneko/vtsls), or (C) implement an extension from scratch using `tsserver` directly with our own LSP adapter layer.

**Comment by jakebailey** [comment]
I don't really see how LSP would help that situation; LSP will within reason only change the way tsserver talks to the editor. It'd still be the same `ProjectService` under the hood, with the same gotchas. What you're describing sounds more suited to plugging into something like [`volar`](https://volarjs.dev/), the system that vue, mdx, etc, use to slap their custom languages on top of TS.

In any case, I think this is the wrong place to discuss it (pinging everyone interested in the 5.5 release process); the update is just that "I didn't have time to work on it". The current LSP thinking is to slowly onboard calls away from the old protocol onto the new one, so it's not going to be like one day we aren't LSP and one day we are, either.

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-5.5 and LKG

**Comment by DanielRosenwasser** [comment]
5.5.3 is out with the NuGet/VS issues fixed. Thanks for your patience everyone!

**Comment by MunMunMiao** [comment]
Will https://github.com/microsoft/TypeScript/issues/26242 be implemented in the next version, as it is so important to library developers?

**Comment by DanielRosenwasser** [comment]
@typescript-bot bump release-5.5 and LKG

**Comment by yuhuung** [comment]
Is there any link for `Improved Performance for Git Branch Switching Scenarios`? @DanielRosenwasser Thank you!
