### PR TITLE
When contextual type doesnt find property in unit type, use the index signature from unit type(fix the incorrectly used union type to get the signature)

### LINKED ISSUE #27949: Fail to get contextual type when an index signature exists
**TypeScript Version:**  3.2.0-dev.20181017

**Code**

```ts
interface Options {
    m(x: number): void;
    [key: string]: unknown;
}
declare function f(options: number | Options): void;
f({
    m(x) {},
});
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts:7:7 - error TS7006: Parameter 'x' implicitly has an 'any' type.`

Was introduced by #27849. For some reason it only happens when `options` is a union. Discovered in `jquery` on DefinitelyTyped.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #27949

### CODE REVIEW

**Comment by weswigham** [comment]
Build failure seems unrelated; it's happening elsewhere. I'm guessing tslint updated or something?
