### ISSUE TITLE
Types acquisition seems to be broken after upgrading from 4.8.3 to 4.8.4

### ISSUE THREAD

**Issue by ernestostifano** [microsoft/TypeScript#50984]
# Bug Report

### 🔎 Search Terms

`v4.8.4` was released yesterday, so I just looked at the last 24h issues and found none.

### 🕗 Version & Regression Information

- This changed between versions `4.8.3` and `4.8.4`

### ⏯ Playground Link

N/A.

## my-test.test.ts
```ts
describe('Hello, World!', () => {
    it('should have correct value', () => {
        expect("Hello, World!").toEqual('Hello, World!');
    });
});
```

<details>
<summary>Errors</summary>

```txt
TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
```
```txt
TS2582: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
```
```txt
TS2304: Cannot find name 'expect'.
```

</details>

<details>
<summary>Installed Types</summary>

```json
{
    "@types/jest": "29.0.0",
    "@types/node": "18.7.0",
    "@types/react": "^18.0.20",
    "@types/react-dom": "^18.0.6",
    "@types/testing-library__jest-dom": "^5.14.5"
}
```

</details>

<details>
<summary>Typescript Config</summary>

## tsconfig.base.js
```json
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "ESNext",
        "moduleResolution": "Node",
        "resolveJsonModule": true,
        "allowUnreachableCode": false,
        "lib": ["ESNext"],
        "allowJs": false,
        "checkJs": false,
        "noEmit": false,
        "noEmitOnError": true,
        "declaration": true,
        "emitDeclarationOnly": true,
        "declarationMap": true,
        "strict": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "esModuleInterop": false,
        "forceConsistentCasingInFileNames": true,
        "useDefineForClassFields": true,
        "removeComments": false,
        "allowSyntheticDefaultImports": true
    }
}
```

## tsconfig.js
```json
{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": {
        "declarationDir": "./types"
    },
    "files": ["./src/index.ts"],
    "include": ["./tsconfig.d.ts", "./src/jest.setup.ts", "**/*.test.ts"]
}
```

</details>

### 🙁 Actual behavior

`describe`, `it` and `expect` are not recognised even if Jest type definitions are installed.

Everything was working fine until `v4.8.4`, changing `^4.8.3` with `4.8.3` fixes the issue.

### 🙂 Expected behavior

Jest types to be properly recognised.

**Comment by arjndr** [comment]
Can confirm, happened to me with a number of other packages too. Downgrading to an earlier version helped.

**Comment by jakebailey** [comment]
Note that this isn't actually type acquisition (ATA), but something else, e.g. resolving global types or something.

The first thing I'll note is that you have `"module": "esnext"` and `"moduleResolution": "node"`, which is something that we're actually considering making an error (#50985), so I'm not sure if fixing that would be helpful.

That being said, I've tried to reproduce this using your example, but I don't get any errors. Can you construct one in a repo somewhere? Does anyone else have an example that works?

The only cherry-pick that I can imagine being related is #50747. Skimming it, I'm noticing some potential bugs show in the test baselines where we're resolving things to files like `ndex.d.ts` (no `i`). @sheetalkamat

**Comment by jakebailey** [comment]
Things appear to work fine so long as you set `nodeLinker: node-modules`, so this appears to be a bug in Yarn's PnP patch for TypeScript. I'd consider reporting this on their issue tracker as it's likely their patch has incorrectly applied to the new patch release of TypeScript, especially if they are touching the same internal code that a PR like #50747 has modified (which we had to change for a bugfix).

**Comment by lucasbeckps** [comment]
Fixed! [Yarnpkg Berry #4093](https://github.com/yarnpkg/berry/pull/4903)
