### ISSUE TITLE
TypeScript incorrectly deducing 'false' type when variable might be changed by a function

### ISSUE THREAD

**Issue by darkf** [Microsoft/TypeScript#13160]
**TypeScript Version:**  2.1.4

**Code**

```ts
var flag = false;

function f() { flag = true; }
f();

if(flag === true) {
	console.log("...");
}

```

**Expected behavior:**

No error, `flag` may be `true` (and in this case is).

**Actual behavior:**

Compiler complains:

    test.ts(6,4): error TS2365: Operator '===' cannot be applied to types 'false' and 'true'.

Despite this being incorrect.

Note that, oddly, the following works as expected:

```ts
var flag = false;

(function() { flag = true; })();

if(flag === true) {
	console.log("...");
}
```

**Comment by aluanhaddad** [comment]
Please see #9998

**Comment by darkf** [comment]
@aluanhaddad Which part specifically is pertinent? (It's a long issue.)

FWIW I wouldn't consider this behavior adequate nor expected, since it's outright rejecting valid code that used to work in 2.0, and especially given it behaves differently with IIFEs vs named functions.

I'm quite surprised that tsc cannot deduce that the function quite directly modifies `flag` here.

**Comment by aluanhaddad** [comment]
@darkf see also #11498 which is a special case of #9998
