### ISSUE TITLE
Ternary operator parse error (TS 2.5)

### ISSUE THREAD

**Issue by alexanderby** [Microsoft/TypeScript#18204]
**TypeScript Version:**  2.5.2

**Code**

`> tsc script.js --allowJs --outFile result.js`
```ts
var xMapper = isXPeriod ?
    (createPeriodCaster(props.x.period)) :
    (function (x) {
        return x;
    });
```

**Expected behavior:**

Should compile OK

**Actual behavior:**

```
script.js(2,24): error TS1005: '=' expected.
script.js(3,5): error TS8010: 'types' can only be used in a .ts file.
script.js(3,19): error TS1005: ')' expected.
script.js(5,6): error TS1005: ':' expected.
```

TypeScript 2.4.1 worked OK.

**Comment by alexanderby** [comment]
Another example of errored file https://github.com/d3/d3-interpolate/blob/master/src/string.js

**Comment by j-oliveras** [comment]
Duplicated/related to #16241 (see my last comment).

Tested, and your sample works with 2.4.2 and not 2.5.2.

Seems like the compiler has some ambiguity errors with ternary operator with both (ts ans js).

**Comment by mhegazy** [comment]
Possibly related to https://github.com/Microsoft/TypeScript/issues/18123

**Comment by sandersn** [comment]
Thanks @j-oliveras for the pointer. This is indeed a dupe of #16241 &mdash; it now manifests with the `function` keyword because `function(number): void` is parsed as a (JSDoc) type since 2.4.

The workaround is to not parenthesize the true branch of the ternary, because this makes the parser think that it could be looking at the start of an arrow function.
