### ISSUE TITLE
Named parameters/arguments in function call

### ISSUE THREAD

**Issue by ivogabe** [microsoft/TypeScript#467]
C# allows adding names of arguments in a function call:

``` csharp
CalculateBMI(weight: 123, height: 64);
```

See http://msdn.microsoft.com/en-us/library/dd264739.aspx

 In TypeScript's source this is also done, but with comments:

``` typescript
emitLinesStartingAt(nodes, /*startIndex*/ 0);
```

Can we have named arguments in TypeScript like this:

```
emitLinesStartingAt(nodes, startIndex: 0);
```

This can add some compile time checking, for instance when you type `count: 0` you will get an error.

I think we should add a restriction that the order of the arguments cannot be changed. Example:

``` typescript
function foo(first: number, second: number) {}
var z = 3;
foo(second: z++, first: z);
```

An error should be thrown on the last line, because changing the order of the arguments (to `foo(z, z++)`) in the generated javascript would cause unexpected behavior.

Also this can be useful for functions with lots of optional arguments:

``` typescript
function foo(a?, b?, c?, d?, e?) {}
foo(e: 4);
foo(d: 8, 5); // e will be 5
```

Generates

``` javascript
function foo(a, b, c, d, e) {}
foo(void 0, void 0, void 0, void 0, 4);
foo(void 0, void 0, void 0, 8, 5);
```

**Comment by mindplay-dk** [comment]
@basarat in Typescript, interfaces are "free" - there is no run-time footprint at all, which is why I prefer this approach:

```
interface StartParams {
    isFoo?: boolean;
    isBar?: boolean;
    isBaz?: boolean;
}

function start(p: StartParams) {
    // ...
}

start({ isFoo:true, isBaz:false });
```

It's almost like having named arguments, though not quite, since you still have to unpack the arguments inside the function. I often find this approach to be safer and easier to refactor over time though. YMMV.

**Comment by kitsonk** [comment]
(Said originally this on #5857)
Personal opinion... it is anti-TypeScript design goals:

> 8. Avoid adding expression-level syntax.

Non-goal:

> 1. Exactly mimic the design of existing languages. Instead, use the behavior of JavaScript and the intentions of program authors as a guide for what makes the most sense in the language.

Object destructuring in ES6 with the combination of the terse object literal declarations in ES6 (both downward emittable) are more than sufficient to cover this type of functionality.  TypeScript isn't trying to be a new language, it is trying to be a superset of JavaScript.  This sounds a lot like a new language.

**Comment by alanouri** [comment]
@RyanCavanaugh Parameter destructuring mostly does cover this but the syntax with TS can be pretty bad if you want to support 0 arguments.  Let's say you want a function that logs two booleans, taking 0, 1, or 2 parameters:

```typescript
function log({a = true, b = true} = { a: true, b: true }) {
	console.log(a, b);
}

log();
log({a: false});
log({b: false});
log({a: false, b: false});
```

In ES6 without TS you could just do this:
```function log({a = true, b = true} = {}) { ... }```

But that doesn't work for TS because the types won't be equivalent and you get an error, so you have to repeat the structure twice.

Is there a better way of doing this in TS?

**Comment by alanouri** [comment]
Hmm, I'm actually not seeing an error for this on TS Playground.  Perhaps this didn't work in TS 1.5 but has been fixed in 1.6 or 1.7?  This is the error I'm getting in 1.5 when I use just `{}` for the default argument:

`error TS2459: Build: Type '{}' has no property 'refreshGrid' and no string index signature.`

**Comment by mhegazy** [comment]
@alanouri, that was an TS 1.7 enhancement, you can read more about it in https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#improved-checking-for-destructuring-object-literal

**Comment by alanouri** [comment]
Oh, yes that's exactly this issue.  Perfect, thanks for the enhancement, I think this works perfectly now.

**Comment by amcdnl** [comment]
@mhegazy - I have something similar throwing the same error...

```
export function httpGet(path?: string, ...middlewares : Function[]) { };
```

and is used like:

```
class Controller {
  @httpGet('/:id')
  async get(ctx: Context) { .... }
}
```

which throws ....

```
30   @httpGet('/:id')
     ~~~~~~~~~~~~~~~~

src/api/Controller.ts(30,3): error TS1241: Unable to resolve signature of method decorator when called as an expression.
```

**Comment by bill-mybiz** [comment]
@alanouri gives a great example of a default case [above](https://github.com/Microsoft/TypeScript/issues/467#issuecomment-162099608), but I just wanted to give a non-default example. I know this issue is closed, but it's the first hit on google and I wanted to explicitly show another example using destructuring for others like me who don't understand what this means. 

```
function log({a = true, b = true} = { }) {
    console.log(a, b);
}
```
is basically syntactic sugar for 
```
function log({a = true, b = true}: {a?: boolean, b?: boolean} = { }) {
    console.log(a, b);
}
```
But this does several things and this may not be obvious to others (like me) who are relatively new to TS. It gives defaults to individual values, as well as a default to the entire value.

Here is another example without some of the defaults:
```
                // params    // shape
function logNum({num, a, b}: {num: number, a?: boolean, b?: boolean}) {

    console.log(num, a, b); // << uses destructuring
}
```
It can be called using:
```
logNum({num: 123});
logNum({num: 123, a: false});
```
A default could then be added:
```
                                                                          // default
function logNum2({num, a, b}: {num: number, a?: boolean, b?: boolean} = { num: 123 }) {
    console.log(num, a, b);
}
logNum2();
```

There are many more possibilities, but the important part is that you are defining a single parameter object, the shape of that object, and sometimes defining optional/default values. Destructuring is then pulling out the individual args inside the implementation, as in the line `console.log(num, a, b);`.

For me, this is immensely useful for readability and refactorability especially with large-ish method signatures like in some factory functions.

**Comment by mindplay-dk** [comment]
I wanted named arguemnts for a while, and I changed my mind.

Javascript already has idiomatic named arguments, in the form of parameter objects.

In Typescript, these are even more useful, because you can declare an interface, defining all the possible parameter types.

Thanks to declaration merging, decorators/plugins/etc can even decorate such an interface with new possible parameters.

It's quite flexible - more so than named arguments would be. But more importantly, it's idiomatic - there is myriad JS code in the wild using the parameter object pattern for just about anything.

As for defaults, the typical JS approach is not to do it at the moment when you *receive* the parameters, but rather to do in when you *consume* one of the parameters - so rather than establishing defaults up front, typically we specify the default when we look up the parameter, e.g. something like `$.post(options.url || DEFAULT_URL)`.

In other words, JS developers are used to seeing the default specified at the point where you consume an optional parameter, not where you received it. This also has the advantage of being able to very the default in each case, e.g. `options.url || DEFAULT_URL` in one case, and `options.url || ANOTHER_URL` in another case.

I think this feature is unnecessary, and in recent years, in other languages, I find myself leaning towards the parameter object pattern, for any large-ish method signature, such as factory functions, as it tends to refactor more easily without BC breaks.

Having optional arguments in a signature, tends to indicate that those arguments aren't directly or closely related, and often then a parameter object is preferable to me.

Anyways, just putting that out there for anyone to ponder, if you're still obsessing about the lack of named arguments. I rarely miss them anymore :-)

**Comment by Zorgatone** [comment]
Is there a way to automatically assign destructured constructor parameters to the class instance,
like it is possible adding the private/public/protected keyword in front of the parameter name?

**Comment by basarat** [comment]
> is there a way to automatically assign destructured constructor parameters to the class instance,
> like it is possible adding the private/public/protected keyword in front of the parameter name

Nope :rose:

**Comment by webmobiles** [comment]
I'm using the  example of @bill-mybiz , but i don'get the default value for 'name' variable. is this the right way to use  destructuring object literal?

import { Component } from '@angular/core';
export class Hero {
  id: number;
  name: string;
  constructor( {id  , name }: {id: number, name?: string } = { id:3, name: 'defaulthero'} ) {
    console.log( id, name);
    this.id = id;
    this.name = name;
  }
}

@Component({
  selector: 'my-app',
  template: `<h1>{{title}}</h1><h2>Hero {{hero3.id}} {{hero3.name}}</h2>`,
})
export class AppComponent    {
  title = 'Tour of Heros';
  public hero3: Hero;


  ngOnInit() {

    //this.hero3  = new Hero (  ) ;  // work
    //this.hero3  = new Hero (  {} ) ; // does not work
    this.hero3  = new Hero ( {id: 0} ) ;  // does not work, default value 'defaulthero' not assign, just i get 'undefined'
  }
}

**Comment by RoyTinker** [comment]
In my experience, the primary utility of named parameters is to increase readability at call sites by providing a sort of inline documentation -- a sort of "here's what this argument is, so you (the developer) don't have to look it up".

Yes, JS provides idiomatic named arguments already, in the form of parameter objects. However, a very large number of libraries have functions/methods with multiple formal parameters.

Since TypeScript is meant as ES<edge> + type annotations/checking, I don't think named parameters makes any sense as an output transformer. However, I think they *would* be very useful as an optional, syntax-only, semantic no-op --- a sort of cleaner alternative to inline comments that could improve readability.

A setTimeout example:
```
setTimeout(() => {
  console.log("Print this after a while");
}, waitTime: 1000);
```

Here the `waitTime` annotation is *nice* and reduces cognitive load by a small amount (in my opinion). It feels like a kind little "here I gave it a name" to other developers; whereas an inline comment like `/* waitTime */` would look ugly and almost insulting , hence we only ever see it when working with arcane libraries or long function signatures.

Somewhat orthogonally, I imagine named parameters *might* also be useful for verifying arguments against other TypeScript (or JS+types) code, with errors thrown when the names don't match. But I haven't thought enough about that case to say much more...

**Comment by aluanhaddad** [comment]
@RoyTinker that seems like something which should be proposed for standardization into ECMAScript. Adding it on the TypeScript side introduces a massive likelihood for collisions with the subset.

**Comment by RoyTinker** [comment]
@aluanhaddad Good point, thanks. Although I imagine they'd have a similar concern about collisions with potential future features 🤷‍♂️

**Comment by elijah-schow** [comment]
Named parameters are handy when you need to add a new argument to a legacy API. In this scenario, destructuring isn't an option because it would break existing function calls.

#### Without named parameters:
``` typescript
login(Model.Email, Model.Password, undefined, undefined, undefined, Model.invitationID)
```
Notice the 3 nasty `undefined`s for unused optional arguments.

#### With named parameters:
``` typescript
login(email: Model.Email, password: Model.Password, invitationID: Model.invitationID)
```

**Comment by aleksey-bykov** [comment]
@RyanCavanaugh 

can we at least allow named arguments **in the same order** as parameters go?

point is the names help a lot when it comes to reading the code

since the order of arguments and parameters always the same there is no problem with matching

with that said the emit can just drop these names (for the sake of transpile to js scenario)

if the type information is available the argument names are forced to match the parameter names

please consider reopening this issue

**Comment by RyanCavanaugh** [comment]
It's pretty risky to add expression syntax in that position; I don't think what is essentially documentation meets the bar for that.

In TS we just use `fn(/* paramName */ arg)` when the meaning is not obvious from context. We had a lint rule to enforce the matching as well (though this turns out to be expensive)

**Comment by mindplay-dk** [comment]
> can we at least allow named arguments in the same order as parameters go?

Just a thought, but - given the example above...

```js
setTimeout(
    () => console.log("Print this after a while"),
    1000 // waitTime
);
```

And the other one...

```js
login(
    Model.Email,
    Model.Password,
    undefined, // no first name
    undefined, // no last name
    undefined, // dob (not available on this form)
    Model.invitationID
)
```

Looks better to me: you didn't need to repeat the words "email" and "password", since those words figure in the arguments you're passing, and it makes room to explain why you're omitting certain values.

The upshot of this is that you're not at risk of the actual argument names changing... I mean, normally, changing an argument name is not a breaking change - call sites aren't affected.

Also, arguments in JS functions obtain names for positional arguments only at call-time inside the function scope - if you create dependency on argument names, arguably (hah!) that might actually be considered a change to the semantics of the language?

**Comment by zlamma** [comment]
@mindplay-dk  The callee parameters are not always so close on levels of abstraction as the arguments of the call, and the arguments can also be ambiguous. If that's the case, the argument names don't really help in understanding the call. 

Consider the contrived example of:
`transferCredits(from: AppInfo.AppOwnerCompanyAccount, to: Model.LoggedInUserAccount)`
vs 
`transferCredits(AppInfo.AppOwnerCompanyAccount, Model.LoggedInUserAccount)`.


In all cases, this was about introducing an *optional feature*. It can be only applied where needed. Also if anyone really prefers any other way, like comments above, they could still rather use that.

**Comment by mindplay-dk** [comment]
@zlamma the main problem with this idea as a compile-time feature, is the semantic mismatch: if somebody renames a positional argument, that's not traditionally a breaking change at any call-site - if we allow named arguments at call-sites for positional arguments, renaming a positional argument is now a breaking change; but you can't reasonably expect neither JS or TS library vendors to version their packages as major releases every time they rename an argument, because, according to how JS *works*, positional arguments are assigned names only within the local scope of the function, at call-time.

So the whole discussion is kind of a non-starter: it's simply not how JS works. No matter how much I like (and would like to have) this feature, even if you took this to the TC39, I think they would reject it more or less outright, because it would be a breaking change to the language.

I think you're going to have to resign yourself to using parameter objects in your own code - and, when you need to use third-party library code, and positional arguments cause serious readability problems for you, you will have to either PR and help improve those libraries, or, proxy third-party functions in custom wrapper-functions that do use parameter objects.

I simply don't see any other ways to approach this - even the vestigial naming feature (as you or someone else proposed) where you can name parameters only when also supplied in positional argument order, doesn't make sense, since, again, changing the names of positional arguments isn't supposed to be a breaking change.

**Comment by RoyTinker** [comment]
@mindplay-dk Great points - it seems clear that named positional parameters as a check and/or an output transformer are inadvisable in both TS and JS.

However, please see my (comment above) [https://github.com/Microsoft/TypeScript/issues/467#issuecomment-320798866] - that isn't supposed to be capable of causing breaking changes. It would only be a nicer alternative to using inline `/* parameterName */` comments.

**Comment by RoyTinker** [comment]
@mindplay-dk I just had a thought. What if named parameters were added as a semantic no-op (call site documentation) as I mentioned above, but also an "experimental" TS compiler feature that would throw errors for mismatched TS-to-TS parameter names? In my mind, this could cause breaking changes (when library APIs or type annotations change, etc.), but only when someone wants that behavior.

**Comment by hpoul** [comment]
@RoyTinker fwiw, when (only) implemented as a semantic no-op this starts to look a lot more like an IDE feature, than a language construct. https://www.youtube.com/watch?v=ZfYOddEmaRw

**Comment by zlamma** [comment]
@mindplay-dk  - whether this is a breaking change is rather subtle. It certainly is not a breaking change for any existent code, both libraries as well as their callers, the syntax is not used in it as it is unavailable. The behavior is breaking just to 'expectations about new code', which is much much milder.  

Whether renaming an argument should be a breaking change also depends on context. Machines can only care about position for optimization, but human intentions in the program are certainly to provide an argument that means 'this and that' - it's quite likely that when the name changes, it no longer means 'this and that', so it's reasonable to notify human that he should re-think it. I, for one, would rather appreciate this and not make much fuss even if it turned out that I just need to do the trivial chore of changing the name.

As to refactoring the problem away, using a `{}` object Is not merely a syntactic difference. Function arguments may be preferred for ease of currying or performance (new object in memory and extra garbage collection burden).

In all cases, all of the points you are making about breakiness applied to any language that introduced the feature mid-life. Notably, C# did this in 4.0 and did not cause a revolution.

**Comment by RoyTinker** [comment]
@zlamma Good points -- it's good to know details on other languages. There's one important difference b/t TypeScript and those languages: TypeScript is transpiled to ES, and one of its [stated goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals) (#&#x200b;8) is to "avoid adding expression-level syntax" -- of course, excluding type annotations. Goal #&#x200b;9 is to "use a consistent, fully erasable, structural type system".

Since this feature would contribute to compile-time checks, would be fully erasable, and would not affect compiler output, I think it's arguable that it falls under goal #&#x200b;9 instead of #&#x200b;8.

**Comment by mindplay-dk** [comment]
> What if named parameters were added as a semantic no-op (call site documentation) as I mentioned above, but also an "experimental" TS compiler feature (opt-in-only) that would throw errors for mismatched TS-to-TS parameter names?

@RoyTinker but it's the same problem: it's a breaking change to TS, in the sense that anyone versioning their packages using SEMVER will now have to version a parameter name change as a breaking change: package authors don't do that at this time, and even if they did, packages written in TS are going to get compiled and release as JS, and the versioning (normally) follows the TS (as the source and output JS are typically one package/repo) - and now you have non-breaking changes in the JS versioned as breaking, which, again, points at a (however minor) change to language semantics.

**Comment by HamedFathi** [comment]
Maybe it's strange and stupid, but why can not you do that in this way?

for example

```js
private test(a:number, b:number, c?:number, d?:number, e?:number) { 
}
```
use it like
```js
private test(1, 2, e::5) // I am not sure about :: !
{
}
```
so, Typescript compiler can generate the js like

```js
private test(1, 2, undefined, undefined, e) { 
}
```

Anyway, I'm not professional in this area

**Comment by mindplay-dk** [comment]
@HamedFathi the syntax is not the issue at all - you should read through some of my recent comments.

**Comment by sheerun** [comment]
Related: https://github.com/Microsoft/vscode/issues/16221

**Comment by DominikDitoIvosevic** [comment]
@RyanCavanaugh would it be possible to reconsider only a case where parameter order is as original? Whenever I have multiple parameters of same type (like string) it's a mess trying to figure out which of them is for which value.

**Comment by RyanCavanaugh** [comment]
No, because the concern of syntactic conflict with a future version of ECMAScript still stands.

We use the `/*name*/` syntax when this occurs

**Comment by wongjiahau** [comment]
Just for those who wanted this feature, you can actually emulate it using **object-destructuring** since ES6.  For example,
```js
// Definition
function send({message, to}) {
    if(to === "console") { console.log(message) }
    else if(to === "window") { window.alert(message) }
    else { console.log("Unknown channel : " + to); }
}

// Example of usage
send({message: "Hello world", to: "console"})
send({message: "Hello world", to: "window"})

// Tested in Google Chrome 
```

**Comment by qoh** [comment]
What if I wish to do something like this?

```typescript
constructor({
  private id: string,
  private name: string,
  private email: string,
}) { }
```

What TypeScript requires me to do to achieve that is not very nice:

```typescript
constructor({ id, name, email }: {
  id: string,
  name: string,
  email: string,
}) {
  this.id = id
  this.name = name
  this.email = email
}
```

**Comment by zenozen** [comment]
@qoh This is what I do. Not super pretty, with two issues
1. `Shape` doesn't work very well with methods
2. When `strict` is enabled, all the properties will have to have `!`

```ts
type Shape<T> = { [P in keyof T]: T[P] }

class X {
  public id!: string
  public name!: string
  public email!: string

  constructor(obj: Shape<X>) {
    Object.assign(this, obj);
  }
}
```

**Comment by mindplay-dk** [comment]
@wongjiahau's [example](https://github.com/microsoft/TypeScript/issues/467#issuecomment-404408760) with ES6 object destructuring is probably the closest we can realistically get to named arguments in TS without departing from JS semantics?

That pattern is already idiomatic to JS, and engines likely already optimize for it.

Perhaps we should start asking how to better *enable* that pattern in TS instead?

So how do we improve on this:

```ts
function send({message = "Hello", to}: {message: string; to: string}) {
  // ...
}
```

Repeating every argument (property) name is a bit clunky, but it's also the only real problem - call sites are perfectly readable with an object literal, and such calls are completely idiomatic to JS since the dawn of time, so no real problem there IMO.

Here's an idea for a simple sugar to abbreviate the example above:

```ts
function send(${ message = "Hello", to: string }) {
  // ...
}
```

This syntax would work in argument lists only - it just declares a single argument that desugars to an ES6 object spread, with an anonymous type assembled from the argument-names/types, which can be either declared with `:` or inferred from a default const initialization with `=`.

The syntax would be more or less exactly that of property-declarations in a class.

I believe this approach has a few advantages over actual named arguments:

1. You can have more than one set of named arguments:
   `function foo(${ a: string, b: string }, ${ c: string, d: string })`

2. You can dynamically define named arguments at call sites:
   `bar({ ...defaults, ...overrides, some: value })`

3. Named arguments are properly grouped - so mixing positional and named arguments is clear:
    `function baz(a: number, ${ b: string, c: string }, d = "default")`

I think there's a bunch of advantages to building on establishes semantics and well-known patterns, rather than inventing an entirely new language feature.

Thoughts?

**Comment by DominikDitoIvosevic** [comment]
@mindplay-dk I actually like this proposal quite a lot. Do we need the $ tho? I guess the parser could know what we want even without it

**Comment by mindplay-dk** [comment]
> Do we need the $ tho? I guess the parser could know what we want even without it

@DominikDitoIvosevic No, I don't think it works without some sort of operator?

    function foo({ a: string }) {}

The parser would see this as destructuring of the arguments, I think?

It can't know if `string` is type or a variable-name, so it's ambiguous with destructuring the property `a` into a variable named `string`, isn't it?

**Comment by kataik** [comment]
Hi everyone, I'm a bit confused. I can use object destruct to force the input object approach on my function's customers only if I have the luxury to change the function signature. For functions requiring backward compatibility or functions I consume but not own, this is not a solution.

**Comment by zlamma** [comment]
I must say that, to me, all the suggestions to refactor the problem away using a `{}` object are not satisfactory as a 'language-wide' solution to the problem, no matter the syntactic sugar.

It's important to note that refactorings to an object parameter bring a difference to the programs that isn't merely syntactic. Multiple function arguments are not only more performant (no new heap object allocation/garbage collection) but also make for simple partial application using [`bind`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) (which will also be more performant than any object-based alternative). Given that, even if `{}` is professed as "the JavaScript's natural way of passing named arguments", the convention will never reach full adoption within the language. A convention that is opinionated against the language's own features of some unique value will never become a language-level good practice. As an example, Google's JS style guide [does recognize](https://google.github.io/styleguide/jsguide.html#formatting-param-name-comments) that it can be _'infeasible'_ to refactor functions' multiple parameters away.

I still stand by the conviction that this is a safe-to-introduce and a positive feature, and it is so even in the event of _'plain JS libraries changing their param name but not changing their SemVer'_. See [this previous comment of mine](https://github.com/microsoft/TypeScript/issues/467#issuecomment-354537675) which I now updated, adding some more efforts to demonstrate that making the compilation break even in this case is an added value to the users of TypeScript in what seems to be pretty much any real-life development setups.

**Comment by Rocamonde** [comment]
@mindplay-dk 
You mention that 
> changing the names of positional arguments isn't supposed to be a breaking change.

This reminds me of that argument for C++ named arguments, according to [proposal N4172](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4172.htm):

> Objection #3: Named arguments make parameter names part of a function's interface, so that changing the parameter names can affect call sites
> We were initially concerned about this as well. To get an idea about the magnitude of this problem, we surveyed some large open-source libraries to see how often parameter names change in the declarations of the public API functions (i.e., the names that users would use when making calls to these functions).
> 
> For each library, we chose a recent release and a release from several years ago, examined the diff between the two versions, and recorded the number of parameter name changes. Only name changes that preserved the types of the parameters were considered, as a change to the type of a parameter typically breaks a function's interface already. The table below summarizes our findings. For more details, please see [1].

> **Given the low number of parameter name changes relative to the sizes of these libraries over periods of several years, we believe that code breakage due to parameter name changes would not be a significant problem in practice.** 

I am sure that little popular libraries tend to frequently rename parameters within their development flow from stable version to another -- as this generally indicates poor coding practices. Clearly, if the function signature is replaced because of a semantic change, then it is only natural that this change breaks compatibility to some extent. 

If code clarity and quality is in mind, well-planned projects should almost never refactor their parameters, and the cases where this would be so can also apply to any other user-defined identifier within the language.

Regarding your point about parameter scope, as TypeScript transpiles to JavaScript, this is not a problem. This only affects function call sites, so named parameters could be syntactic sugar that requires the function signature type to be present at compile time, and replace the named call with a positional call.

**Comment by Rocamonde** [comment]
On another note, I don't think that adding this feature would be almost like "a new language", while it is true that object destructuring *could* be enough to solve this. However, currently the way it is it makes duplicating the object attributes, making it quite unreadable. It was one of the things that I disliked the most when I started learning TypeScript. When functions are annotated in-place, code formatters break the one-liners and split the signature into many many lines, making it super ugly. So this ends up making the type be extracted to an interface.

Solving this in a nice way would require adding another syntactic feature significantly different to current object type annotation principles.

The most obvious way that someone would expect to avoid duplication:
```typescript
function foo({firstParameter, anotherParameter}: {firstParameter: string, anotherParameter: number}) {}
```
would imply, as suggested, removing the destructuring and just leaving the interface
```typescript
function foo({firstParameter: string, anotherParameter: number}) {}
```
But in order for this to work, the interpreter would have to either (a) not consider the declaration an interface, or (b) inject the interface attributes to the scope, and this would not be very beautiful, as it would be inconsistent with current behaviour. So the most natural solution is dropping the braces and adding syntactic sugar to function calls, which is not incompatible with type annotation as this feature is not currently allowed in call site.

**Comment by d8corp** [comment]
> On another note
```typescript
function test1 ({a:: string}) {}
function test2 ({a: b: string}) {}
function test3 ({a: b: number | string = 1}) {}
```

**Comment by zlamma** [comment]
With no disrespect, all suggestions to enhance the object-passing argument (e.g. comments [1](https://github.com/microsoft/TypeScript/issues/467#issuecomment-668275555), [2](https://github.com/microsoft/TypeScript/issues/467#issuecomment-544887925), [3](https://github.com/microsoft/TypeScript/issues/467#issuecomment-425710010) etc.), as much as they are an improvement that would be great for TypeScript, are actually off-topic to this thread (a workaround at most).

As such, I'd like to suggest to raise them as separate suggestions/move the discussion to the existing suggestions (e.g. [this one](https://github.com/microsoft/TypeScript/issues/29526)) because this thread still requests for the named arguments for reasons that cannot be satisfied with passing objects (see [this comment for justification](https://github.com/microsoft/TypeScript/issues/467#issuecomment-586537123)).
