### PR TITLE
Fix inference from enum object type to generic mapped type

### LINKED ISSUE #30218: Inference of the Enum object as a Record fails in TS3.3.3333
**TypeScript Version:**  3.4.0-dev.201xxxxx and 3.3.3333

**Search Terms:** enum, record

**Code**

```ts
declare function enumValues<K extends string, V extends string>(
    e: Record<K, V>): V[];

enum E {
  A = 'foo',
  B = 'bar'
}

let x:E[] = enumValues(E);
```

**Expected behavior:**
No type error, because K is inferred to be `'A' | 'B'` and `V` is inferred to be `'foo' | 'bar'`.

**Actual behavior:**
Type error after TS 3.3:
```
error TS2322: Type 'string[]' is not assignable to type 'E[]'.
```
It appears that `K` and `V` are chosen to be the lower bound `string`.

### PR DESCRIPTION
**Pull request by ahejlsberg**
This PR fixes a break introduced by #29253. We now exclude index signatures when inferring from an enum object type to a generic mapped type.

Fixes #30218.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -14960,12 +14960,10 @@ namespace ts {
                     }
                     // If no inferences can be made to K's constraint, infer from a union of the property types
                     // in the source to the template type X.
-                    const valueTypes = compact([
-                        getIndexTypeOfType(source, IndexKind.String),
-                        getIndexTypeOfType(source, IndexKind.Number),
-                        ...map(getPropertiesOfType(source), getTypeOfSymbol)
-                    ]);
-                    inferFromTypes(getUnionType(valueTypes), getTemplateTypeFromMappedType(target));
+                    const indexType = source.symbol && source.symbol.flags & SymbolFlags.Enum && getEnumKind(source.symbol) === EnumKind.Literal ?
```
Comment (weswigham) [inline src/compiler/checker.ts]: Rather than all this stuff, we shouldn't we just filter the `enumNumberIndexInfo` singleton from the result of `getIndexTypeOfType` so intersection-based inferences still work out?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yeah, that works.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -14960,12 +14960,9 @@ namespace ts {
...
                     // If no inferences can be made to K's constraint, infer from a union of the property types
                     // in the source to the template type X.
-                    const valueTypes = compact([
-                        getIndexTypeOfType(source, IndexKind.String),
-                        getIndexTypeOfType(source, IndexKind.Number),
-                        ...map(getPropertiesOfType(source), getTypeOfSymbol)
-                    ]);
-                    inferFromTypes(getUnionType(valueTypes), getTemplateTypeFromMappedType(target));
+                    const indexInfo = getIndexInfoOfType(source, IndexKind.String) || getNonEnumNumberIndexInfo(source);
+                    const sourcePropsType = indexInfo && indexInfo.type || getUnionType(map(getPropertiesOfType(source), getTypeOfSymbol));
```
Comment (weswigham) [inline src/compiler/checker.ts]: This isn't including the index signature type in the union with the named property types, whereas it was before. Doesn't seem intentional and is potentially an undesirably break, since now properties will be _ignored_ for inference when an index signature exists.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: It matches what we do for `keyof T`, e.g. if `T` has a numeric index signature, we include `number` in the index type (and thus forget about any numerically named properties).

Comment (weswigham) [reply src/compiler/checker.ts]: Sure, but that's _not_ how we operate with homorphic constraints in play, and that erasure of information is typically undesirable during inference. Take when we infer to `interface F<T extends string> { kind: T; [idx: string]: string}` - never inferring to the `kind` field's value seems like a mistake to me; even though the index signature "makes the property redundant" in the key space, the information is still there and still quite useful.

IMO, rather than producing a union we should probably be inferring from _each_ value (indexes and properties alike) we find to the target template, rather than producing a union to infer with (and adjusting the inference priority for these inferences to allow a union result to handle the intersection-with-incompatable-index case).

Comment (ahejlsberg) [reply src/compiler/checker.ts]: But here we specifically _know_ we're inferring to a non-homomorphic mapped type. And, we're in the final part where we're inferring to the _template type_, not specific properties.

Comment (weswigham) [reply src/compiler/checker.ts]: Right, but the `source` is just some object type. If I'm inferring from `{x: "x", [idx: string]: string}` to `{[X in K]: Foo<X, T>}`, while technically `{[X in string | "x"]: Foo<X, T>}` producing `{[idx: string]: Foo<string, T>}` is... _ok_, `{x: Foo<"x", T>; [idx: string]: Foo<string, T>;}` would preserve more data for contextual typing and completions, which is _always_ desirable. And to top that off, if we infer from `{x: 42} & {[idx: number]: string}` to `{[X in K]: Foo<X, T>}`, producing `{[X in "x" | number]: Foo<X, T>}` which is `{x: Foo<"x", T>; [idx: number]: Foo<number, T>}` and inferring to both is just straight up required.

Especially if you consider `Foo<X, T>` could be defined along the lines of `X extends "x" ? T : never`, so the presence of that explicit `"x"` prop could change its meaning quite a bit!
