### ISSUE TITLE
error TS2339: Property 'length' does not exist on type 'never'

### ISSUE THREAD

**Issue by doberkofler** [microsoft/TypeScript#33138]
**TypeScript Version:**  3.6.2

**Search Terms:**

**Code**

```ts
function getValue(): string {
	return '1';
}

function isNumber(value: any): value is number {
	return typeof value === 'number' && !Number.isNaN(value) && Number.isFinite(value);
}

function main() {
	let value = getValue();

	if (isNumber(value) && value.length === 4) {
		value++;
	}
}

main();
```

**Expected behavior:**
The compare in the line `if (isNumber(value) && value.length === 4)` in the above example would always fail but did compile without type error in TypeScript 3.5.3.

**Actual behavior:**
In TypeScript 3.6.2 the line generates `error TS2339: Property 'length' does not exist on type 'never'` and I do not understand why this would be a type error?

**Playground Link:** 

**Related Issues:**

**Comment by jack-williams** [comment]
This is caused by #31838 which is marked as a breaking change.

In 3.5 the type of `value` after the type guard `isNumber` is `string & number` which is semantically equivalent to never but has an apparent type with property `length`.

In 3.6 the type of `value` after the type guard `isNumber` is eagerly reduced to `never` which does not have the property `length`.
