### ISSUE TITLE
Compiler fails to find external module referenced by two different files

### ISSUE THREAD

**Issue by michael-terry** [Microsoft/TypeScript#2192]
(Also posted on StackOverflow: https://stackoverflow.com/questions/28844917/typescript-cant-find-external-module-when-referenced-by-two-different-files)

I may be missing something obvious, but Typescript's module resolver for commonjs isn't working as expected.

Given the following directory structure and files:

* ./first/shared.ts
* ./first/second/class_a.ts
* ./first/second/class_b.ts
* ./third/class_c.ts

Where:

* class_a references shared.ts
* class_b references class_a.ts and class_c.ts
* class_c references shared.ts

Specifically:

shared.ts:
```typescript
class Shared{}
export = Shared;
```

class_a.ts:
```typescript
import Shared = require('../shared');
class A{}
export = A;
```
class_b.ts:
```typescript
import A = require('./class_a');
import C = require('../../third/class_c');
class B {}
export = B;
```
class_c.ts:
```typescript
import Shared = require('../first/shared');
class C {}
export = C;
```

All compile individually, except class_b.ts, using the following compiler invocation:

`tsc --module commonjs class_b.ts`

Compiling class_b.ts fails with the error that it can't find shared.ts:

`../../third/class_c.ts(1,25): error TS2307: Cannot find external module '../first/shared'.`

Note that if you reverse the order of imports in class_b.ts, you get a different error:

`class_a.ts(1,25): error TS2307: Cannot find external module '../shared'.`

It seems the compiler is finding shared.ts the first time it is imported, but not the second time.

This is with tsc 1.4.1.0.

**Comment by mhegazy** [comment]
the problem is how files are named when relative path are used. as a work around, wither call the compiler from the root directory, or pass in absolute paths.

**Comment by canmrt** [comment]
Can you provide an example of how to run a gulp task from the root directory to bypass this issue?

**Comment by mhegazy** [comment]
@canmrt how is this happening with grunt or gulp? if i understand correctly, you have a build file, possibly at the root of your project, and you will always be calling it from the same place.. is that accurate? what is the issue you are seeing?

**Comment by niemyjski** [comment]
+1 with a external module.

**Comment by sneerin** [comment]
have the same issue, without any path, I had next schema
server.ts -> uses few imports e.g. import require('mongoose') etc.. 
from server.ts I'm refering to modile dto/elmyDatasource.ts and it's working fine, once I'm adding same imports to dto/elmyDatasource.ts  this module not able to find in server.ts. Is there any way to reuse imports in all files?

**Comment by sneerin** [comment]
log is next : [gulp-typescript] 2304 Cannot find name 'DBBackend'.
> file: /Users/mdomarev/workspace/singularex/angular-typescript-gulp-seed/server/server.ts:
> [35] 

/Users/mdomarev/workspace/singularex/angular-typescript-gulp-seed/node_modules/gulp-typescript/release/output.js:161
                var references = file.original.ts.referencedFiles.map(function
                                              ^
TypeError: Cannot read property 'ts' of undefined

**Comment by sneerin** [comment]
Is there any workaround for this, without this workaround I can't use external files at all

**Comment by ivogabe** [comment]
@sneerin It looks like you're using an older version of gulp-typescript, can you try upgrading to the latest release?

**Comment by sneerin** [comment]
I updated and now having even more troubles, I have a class:
 class Backend {
        public server:any;

        private dbUtils:DbUtils;

        constructor() {
          //  debug.log("starting server");
          //  this.startServer();

            debug.log("init mongo");
            this.initDb();

            debug.log("init routes");
            this.initRoutes();

        }

        startServer():void {
            this.server = restify.createServer();
            this.server.use(restify.bodyParser());
            this.server.listen('8080', ()=> {
                debug.log('listening port: 8080');
            })
        }


and this during compilation cause next that happened for commented part of the file( : 

> file: /Users/mdomarev/workspace/singularex/angular-typescript-gulp-seed/server/server.ts:
> [66]           //  this.startServer();
/Users/mdomarev/workspace/singularex/angular-typescript-gulp-seed/node_modules/gulp-typescript/release/output.js:162
                var references = file.original.ts.referencedFiles.map(function

**Comment by sneerin** [comment]
I don't know what's wrong, but I'm about to giveup using typescript, I did many tricks, and it finally compiles, however when I'm staring node.js sever it is said my require imports with relative path wasn't able to find.

**Comment by sneerin** [comment]
is there any good structured with classes and modules sample of code for server node.js and commonjs modules?

**Comment by mhegazy** [comment]
@sneerin can you share the full application, or more error information. i can not piece together what you are trying to do from the information provided.

**Comment by chicoxyzzy** [comment]
you can just
```typescript
import * as EventEmitter from 'eventemitter3';
```
having eventemitter3 in `node_modules` to reproduce `Cannot find external module 'eventemitter3'.` error

**Comment by gravidThoughts** [comment]
@mhegazy 
"the problem is how files are named when relative path are used. as a work around, wither call the compiler from the root directory, or pass in absolute paths."

How do I call the compiler from a root directory in a VS studio project?

**Comment by gravidThoughts** [comment]
My situation is slightly different than OP I am not using tsc directly.
Clean blank node.js console project, VS 2013 Update 5.
`npm install inversify --save-dev`

app.ts
```
import inversify = require('node_modules/inversify/source/inversify');
var kernel = new inversify.Kernel();
```
The above builds without issue, I get my lovely intellisense.
I get the following runtime error.
```
Debugger listening on port 5858
module.js:338
    throw err;
          ^
Error: Cannot find module 'node_modules/inversify/source/inversify'
    at Function.Module._resolveFilename (module.js:336:15)
...
```

**Comment by mhegazy** [comment]
@gravidThoughts, in TS 1.6 we now have support to importing types from npm packages. your package author needs to export the typings. inversify package author will need:
- build with `--declarations` (generate `inversify.d.ts`)
- set `typings` field in `package.json` to point to `inversify.d.ts`

with that in place, you should be able to do something like:
```ts
import * from "inversify"
```
and it should work for your typings and at runt time.

You can find more about this in https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages
and check out the typescript package definition here: https://github.com/Microsoft/TypeScript/blob/c9170b81a8f69994c1c03af50a10aafd9c75c524/package.json#L23

**Comment by gravidThoughts** [comment]
@mhegazy That sounds great. I look forward to it.
2 Questions.
First, does the package author need to do the same for their bower package?
Second, I still have to use a absolute path for my internal project modules.

vehicle.ts (same directory as app.ts)
```
export class vehicle{ ... }
export class car extends vehicle { ... }
```
app.ts
```
import vehicle = require('vehicle');
var myCar = new vehicle.Car();
```
Above still gets the runtime exception can't find module. Using an absolute path works.

Is this the same issue as encountered by the OP?

**Comment by mhegazy** [comment]
> First, does the package author need to do the same for their bower package?

there is not a special bower package handling. what are your expectations here?

> Second, I still have to use an absolute path for my internal project modules.

if the file is local, use relative path to find it, e.g. `require("./vehice")`

**Comment by gravidThoughts** [comment]
>there is not a special bower package handling. what are your expectations here?

Typescript enabled components are distributed in Bower. Will 1.6 behavior be the same for Bower packages if they distribute a d.ts and specify typings in bower.json.

>  if the file is local, use relative path to find it, e.g. require("./vehice")

I have posted a new issue concerning this.#4857
