### ISSUE TITLE
Custom types files (e.g. lib.d.ts) are being ignored when upgrading from Typescript 4.3.5 to 4.4.4

### ISSUE THREAD

**Issue by makanti** [microsoft/TypeScript#46820]
# Bug Report

### 🔎 Search Terms

typescript, custom types files, ignored types, lib.d.ts

### 🕗 Version & Regression Information

- This change occurred between versions 4.3.5 and 4.4.0

We have been using custom types from a root `types/` directory. After the upgrade, the custom type files (e.g. lib.d.ts) are being ignored and hence, the compiler throws errors.

### 💻 Code
 
Here is my `tsconfig`:
```{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "allowJs": true,
    "checkJs": false,
    "jsx": "preserve", 
    "sourceMap": true,
    "noEmit": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "preserveSymlinks": true
  },
  "include": [
    "types",
    "src"
    ...
  ]
}
```

Project structure:
```
> src
> types
     > lib.d.ts
     > config.d.ts
.....
```

### 🙂 Expected behavior

I expect extending Typescript Global object from within `lib.d.ts`:

```
declare namespace NodeJS {
  interface Global {
    $T: TestHelper;
  }
}
```
 to be making $T available globally

### 🙁 Actual behavior

`Cannot find name '$T'.` 

![Screenshot 2021-11-16 at 09 30 59](https://user-images.githubusercontent.com/5037924/141959318-50fe7c0f-ad80-43a3-91dc-a5cf5f1a774b.png)

**Comment by RyanCavanaugh** [comment]
Can you provide a repo or zip file? I don't have enough information to make this work in 4.3.5.

**Comment by makanti** [comment]
Closing this as the issue above had nothing to do with 4.3.5. Thank you @RyanCavanaugh
