### PR TITLE
fix fragment resolving behavior with `jsx: preserve` and `jsxFragmentFactory: null`

### LINKED ISSUE #60095: [NewErrors] 5.7.0-dev.20240929 vs 5.6.2
The following errors were reported by 5.7.0-dev.20240929, but not by 5.6.2
[Pipeline that generated this bug](https://typescript.visualstudio.com/TypeScript/_build?definitionId=48)
[Logs for the pipeline run](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=163770)
[File that generated the pipeline](https://github.com/microsoft/typescript-error-deltas/blob/main/azure-pipelines-gitTests.yml)

This run considered 800 popular TS repos from GH (after skipping the top 0).

<details>
<summary>Successfully analyzed 453 of 800 visited repos</summary>

| Outcome | Count |
|---------|-------|
| Detected interesting changes | 78 |
| Detected no interesting changes | 375 |
| Git clone failed | 7 |
| Package install failed | 102 |
| Project-graph error in old TS | 10 |
| Too many errors in old TS | 208 |
| Unknown failure | 20 |

</details>

## Investigation Status
| Repo | Errors | Outcome |
|------|--------|---------|
|a16z-infra/ai-town|3| |
|a16z-infra/companion-app|1| |
|adobe/react-spectrum|5| |
|alan2207/bulletproof-react|2| |
|alangpierce/sucrase|1| |
|antfu-collective/ni|1| |
|apache/superset|1| |
|AykutSarac/jsoncrack.com|1| |
|bitwarden/clients|46| |
|Blazity/next-enterprise|1| |
|captbaritone/webamp|1| |
|compiler-explorer/compiler-explorer|4| |
|CopilotKit/CopilotKit|2| |
|dinerojs/dinero.js|1| |
|documenso/documenso|1| |
|Dokploy/dokploy|3| |
|dotansimha/graphql-code-generator|1| |
|dotansimha/graphql-yoga|1| |
|facebook/docusaurus|1| |
|feathersjs/feathers|2| |
|getsentry/sentry-javascript|1| |
|getumbrel/llama-gpt|1| |
|graphql-kit/graphql-voyager|2| |
|heyxyz/hey|3| |
|i18next/next-i18next|2| |
|ikatyang/emoji-cheat-sheet|2| |
|immich-app/immich|1| |
|immutable-js/immutable-js|1| |
|ionic-team/stencil|4| |
|ItzCrazyKns/Perplexica|1| |
|ixartz/Next-js-Boilerplate|1| |
|jackyzha0/quartz|3| |
|joe-bell/cva|1| |
|kysely-org/kysely|1| |
|labring/FastGPT|1| |
|leptonai/search_with_lepton|1| |
|majodev/google-webfonts-helper|1| |
|mapbox/mapbox-gl-js|1| |
|marp-team/marp|1| |
|mayooear/gpt4-pdf-chatbot-langchain|1| |
|metricsgraphics/metrics-graphics|1| |
|microsoft/azuredatastudio|10| |
|misskey-dev/misskey|12| |
|netless-io/flat|2| |
|ngrx/platform|1| |
|nodejs/nodejs.org|1| |
|noodle-run/noodle|1| |
|Nutlope/aicommits|2| |
|Nutlope/roomGPT|1| |
|pixijs/pixijs|5| |
|pubkey/rxdb|3| |
|react-cosmos/react-cosmos|1| |
|react-hook-form/react-hook-form|2| |
|recharts/recharts|12| |
|reduxjs/redux-toolkit|1| |
|reduxjs/reselect|1| |
|refined-github/refined-github|1| |
|resend/react-email|1| |
|runtipi/runtipi|6| |
|SawyerHood/draw-a-ui|1| |
|scalar/scalar|1| |
|shadcn-ui/ui|1| |
|slab/quill|4| |
|spacedriveapp/spacedrive|1| |
|streetwriters/notesnook|2| |
|t3-oss/create-t3-app|1| |
|th-ch/youtube-music|1| |
|trpc/trpc|1| |
|twentyhq/twenty|1| |
|ueberdosis/tiptap|8| |
|Uniswap/web3-react|1| |
|upscayl/upscayl|1| |
|urql-graphql/urql|19| |
|vercel/commerce|1| |
|vercel/nextjs-subscription-payments|1| |
|vercel/platforms|1| |
|wandb/openui|1| |
|windingwind/zotero-pdf-translate|4| |

### LINKED ISSUE #60132: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
Hi, 
JavaScript and TypeScript Nightly version `5.7.20240928` and subsequent versions report the above message.

Next.js 13 or 14, pages router
Windows 10 with WSL2
VSCode 1.93.1

This is a React Fragment and there are several workarounds, but none of them are desired:
- import React obviously
- change `"jsx": "preserve"` -> to `"jsx": "react-jsx"` in `tsconfig.json` in which case Next will slap you 
image
- change to `div` or whatever :)

image

image
image

On a side note **ESLint** doesn't pick it up when linting, but then again it's misleading.
Thanks!

### LINKED ISSUE #60137: [NewErrors] deploys-pr-build-5.7.0-pr-60122-2 vs 5.6.2
The following errors were reported by deploys-pr-build-5.7.0-pr-60122-2, but not by 5.6.2
[Pipeline that generated this bug](https://typescript.visualstudio.com/TypeScript/_build?definitionId=48)
[Logs for the pipeline run](https://typescript.visualstudio.com/TypeScript/_build/results?buildId=163820)
[File that generated the pipeline](https://github.com/microsoft/typescript-error-deltas/blob/main/azure-pipelines-gitTests.yml)

This run considered 800 popular TS repos from GH (after skipping the top 0).

<details>
<summary>Successfully analyzed 453 of 800 visited repos</summary>

| Outcome | Count |
|---------|-------|
| Detected interesting changes | 38 |
| Detected no interesting changes | 415 |
| Git clone failed | 7 |
| Package install failed | 103 |
| Project-graph error in old TS | 10 |
| Too many errors in old TS | 207 |
| Unknown failure | 20 |

</details>

## Investigation Status
| Repo | Errors | Outcome |
|------|--------|---------|
|a16z-infra/ai-town|2| |
|adobe/react-spectrum|4| |
|alangpierce/sucrase|1| |
|antfu-collective/ni|1| |
|ariakit/ariakit|1| |
|bitwarden/clients|46| |
|compiler-explorer/compiler-explorer|6| |
|daybrush/moveable|3| |
|dream-num/univer|2| |
|feathersjs/feathers|2| |
|graphql-kit/graphql-voyager|2| |
|ikatyang/emoji-cheat-sheet|2| |
|ionic-team/stencil|4| |
|jackyzha0/quartz|5| |
|majodev/google-webfonts-helper|1| |
|mapbox/mapbox-gl-js|1| |
|microsoft/azuredatastudio|10| |
|misskey-dev/misskey|12| |
|netless-io/flat|2| |
|ngrx/platform|1| |
|Nutlope/aicommits|2| |
|pixijs/pixijs|5| |
|pubkey/rxdb|2| |
|react-hook-form/react-hook-form|2| |
|recharts/recharts|12| |
|reduxjs/redux-toolkit|1| |
|refined-github/refined-github|1| |
|runtipi/runtipi|5| |
|SawyerHood/draw-a-ui|1| |
|slab/quill|4| |
|spacedriveapp/spacedrive|1| |
|streetwriters/notesnook|2| |
|th-ch/youtube-music|1| |
|ueberdosis/tiptap|8| |
|urql-graphql/urql|19| |
|vuejs/core|2| |
|wandb/openui|1| |
|windingwind/zotero-pdf-translate|4| |

### PR DESCRIPTION
**Pull request by iisaduan**
fixes regressions after #59933
- [#60095](https://github.com/microsoft/TypeScript/pull/60095), [#60132](https://github.com/microsoft/TypeScript/pull/60095): Allow `React` to remain an unresolved import even if not explicitly referenced when using `jsx: preserve`
  - see [#60137](https://github.com/microsoft/TypeScript/issues/60137) for this PR's test results
- other regressions: Fragments with factory set to `null` will be typed as `anyType`, just like pre- [#59933](https://github.com/microsoft/TypeScript/pull/59933), and we shouldn't issue errors on them. For more info, see [#38720 (comment)](https://github.com/microsoft/TypeScript/pull/38720#discussion_r440434169)
  - fragments with `null` should not show up as `errorType` in the baselines

fixes #60095, fixes #60132, fixes #60137

### CODE REVIEW

**Comment by iisaduan** [comment]
@typescript-bot pack this

**Comment by iisaduan** [comment]
@typescript-bot test top800
@typescript-bot test tsserver top400
@typescript-bot user test this
@typescript-bot user test tsserver
@typescript-bot run dt
@typescript-bot perf test this faster

File: tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types [hunk 1]
```diff
@@ -3,31 +3,24 @@
 === jsxFactoryAndJsxFragmentFactoryNull.tsx ===
 declare var h: any;
 >h : any
->  : ^^^
 
 <></>;
-><></> : any
->      : ^^^
+><></> : error
```
Comment (Andarist) [inline tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types:8]: This has changed to an error type and yet there are no errors reported for this test now. It looks suspicious to me but I'm not entirely sure if this is incorrect

**Comment by iisaduan** [comment]
Our testing pipeline doesn't test a repo if the previous version didn't build, so the errors hit by https://github.com/microsoft/TypeScript/pull/60095 don't show up in the tests. I re-ran the test pipeline today comparing to a different version, and I'll link the results once they come in, but in the meantime I've manually been checking the repos reported in the weekend deltas report

**Comment by iisaduan** [comment]
Results of this version vs 5.6 no longer show the unresolved react errors: https://github.com/microsoft/TypeScript/issues/60137

File: tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types (hunk 1 above)
Comment (weswigham) [reply tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types:8]: Yeah, jake is right, error types in tests with `.error` baselines print as `any`, since it's assumed to be unimportant. An `error` type in a test WITHOUT a `.error` baseline, conversely, usually means there was a silent error of some kind that you need to look in to, which is why it's printed differently! Now, I imagine this is just because we skip call resolution here, but we should probably be returning `anyType` here, rather than `errorType`, since there's no errors anywhere in the test. Not that it's *that* important.

Comment (iisaduan) [reply tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types]: @jakebailey @weswigham I fixed it. It looks like it was a bug in the first place because there was an improper use of `||` (`errorType || anyType` is still errorType)

Comment (jakebailey) [reply tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types]: I don't think you actually need to conditionally return any on error; error is functionally any. The baselines are more or less cosmetic imo and I wish we didn't special case the baseline printout...

Comment (iisaduan) [reply tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types]: Hmmmm.... fixing the rest of these means issuing new errors or running into https://github.com/microsoft/TypeScript/issues/18217 at getJsxNamespaceAt`. I think the correct way to improve the error types in the baselines is to issue a "cannot resolve jsx namespace" error (since the namespaces in the test don't resolve in the way the compiler expects a JSX namespace to be properly defined), but I don't want to fix that in this regression-fixing PR (it could make things confusing).

Comment (iisaduan) [reply tests/baselines/reference/jsxFactoryAndJsxFragmentFactoryNull.types]: The `errorTypes` left in the baselines are unrelated to this change, or the previous PR.

**Comment by iisaduan** [comment]
@typescript-bot pack this
@typescript-bot run dt
@typescript-bot test tsserver top400

**Comment by iisaduan** [comment]
re-carousel error disappearing is good, it was a regression.

**Review by weswigham — APPROVED** [review]
We should look into getting those remaining `error`s in the baselines swapped to `any`s (or adding error messages on them if appropriate), but that's for another time.
