### ISSUE TITLE
Tsc crash ("Debug Failure. False expression:")

### ISSUE THREAD

**Issue by kpreisser** [Microsoft/TypeScript#10522]
Hi,
I think the following code should not cause tsc to crash:

**TypeScript Version:**  Version 2.1.0-dev.20160824

**Code** (test1.ts)

```ts
export let a;
export = {};
```

**Expected behavior:**
```
test1.ts(2,1): error TS2309: An export assignment cannot be used in a module with other exported elements.
```

**Actual behavior:** 
```
C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:37652
                throw e;
                ^

Error: Debug Failure. False expression:
    at Object.assert (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:1289:23)
    at Object.fail (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:1294:19)
    at Object.findMap (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:211:15)
    at getDeclarationOfAliasSymbol (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:13935:23)
    at checkExternalModuleExports (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26465:39)
    at checkExportAssignment (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26441:13)
    at checkSourceElement (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26609:28)
    at Object.forEach (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:185:30)
    at checkSourceFileWorker (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26661:20)
    at checkSourceFile (C:\Users\VPC\AppData\Roaming\npm\node_modules\typescript\lib\tsc.js:26647:13)
```

Note: The error seems to have been introduced with commit e900952d3d941524c2de373512693a8421eee22d (with c9f62f33d4d87dbb4a40ba5a28bb1085c683def2 I'm getting the expected error message).

Thanks!

**Comment by andy-ms** [comment]
Related to #10460

**Comment by sandersn** [comment]
It's pretty close to a dupe. I'll fix it with #10460.

**Comment by sledorze** [comment]
@mhegazy wondering if this issue has the correct Version (2.1.0 vs 2.0.1) ???? (I see the version used in the report is 2.1.0-dev.20160824)

**Comment by sandersn** [comment]
Fix is up at #10538

**Comment by Ciantic** [comment]
tsc --version
Version 2.2.0-dev.20161210

Error: Debug Failure. False expression

My only TS file is test.ts with this:

```
import { Collapse } from '@blueprintjs/core';
```

very odd.

**Comment by Ciantic** [comment]
Here is cloneable gist: https://gist.github.com/Ciantic/60e9dbe330922cfc41086e255820df62

```
npm install
tsc
...\typescript\lib\tsc.js:1796
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
                ^

Error: Debug Failure. False expression:
```

**Comment by mhegazy** [comment]
@Ciantic, this is a different issue. the debug message is the same for all debug asserts. I have filed a new issue to track this: https://github.com/Microsoft/TypeScript/issues/12827

seems that the problem is that `@blueprintjs/core` augments `tether`, but does not have a dependency on `@types/tether` in package.json. 

Installing the `@types/tether` should avoid this error. but really the fix should be in `@blueprintjs/core`  package.json.

either ways, the compiler should not crash, and #12827 tracks fixing that.
