### ISSUE TITLE
[BUG] Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isJsonSourceFile'.

### ISSUE THREAD

**Issue by magic-akari** [Microsoft/TypeScript#28762]
**TypeScript Version:**  3.2.1

**Search Terms:**

**Code**

```ts
declare global {
  const React: typeof import("react");
  const ReactDOM: typeof import("react-dom");
}

export {};
```

**Expected behavior:**

**Actual behavior:**
```
> tsc

/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:71026
                throw e;
                ^

Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isJsonSourceFile'.
    at Object.cast (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:1158:22)
    at getTypeOfVariableOrParameterOrPropertyWorker (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:29354:41)
    at getTypeOfVariableOrParameterOrProperty (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:29334:48)
    at getTypeOfSymbol (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:29603:24)
    at resolveImportSymbolType (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:33159:45)
    at getTypeFromImportTypeNode (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:33141:25)
    at getTypeFromTypeNode (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:33460:28)
    at checkImportType (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:43996:13)
    at checkSourceElement (/Users/akari/Developer/test/node_modules/typescript/lib/tsc.js:46921:28)
```
**Playground Link:** 
https://gist.github.com/magic-akari/aa10dfb809268eb4f63d5749d113a93a

**Related Issues:**

**Comment by li2568261** [comment]
had a similar issue.wait......

**Comment by sheetalkamat** [comment]
Seems like we are doing something wrong when getting import type for module 
```ts
// global.d.ts
declare global {
  const React: typeof import("./module");
}
export {};

// module.d.ts
export as namespace ReactDOM;
export function foo(): string;
```

**Comment by luvies** [comment]
I got this issue while using webpack's dev server (in a project based on create-react-app). It will compile fine initially, but it will then throw this error whenever it attempts to re-compile.

**Comment by tmkn** [comment]
> I got this issue while using webpack's dev server (in a project based on create-react-app). It will compile fine initially, but it will then throw this error whenever it attempts to re-compile.

Can confirm, that's my issue as well after updating to 3.2.1

**Comment by weswigham** [comment]
This seems to be fixed in `master`, but not in `3.2` - will have to see by what change.

**Comment by weswigham** [comment]
Ah, no, it's not fixed in master, i just had an outdated `master` in my laptop. Regression introduced by #28453 - now that it's resolving aliases prior to merging, a sourcefile _can_ end up merged with a property (it used to merge with the alias declaration instead), and that should be handled.

**Comment by Favna** [comment]
Same issue, also went from 3.1.3 to 3.2.1. I tried making the change suggested by @li2568261, however our project requires esModuleInterop to build at all.

(It's a React Redux frontend building with babel-loader, awesome-typescript-loader and through webpack)

**Comment by A-Atrash** [comment]
I have the same error with different cause (I guess): 
```
yarn start v0.17.8
$ ts-node ./src/engine/server/server 

/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:1325
        return Debug.fail("Invalid cast. The supplied value " + value + " did not pass the test '" + Debug.getFunctionName(test) + "'.");
                     ^
Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isJsonSourceFile'.
    at Object.cast (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:1325:22)
    at getTypeOfVariableOrParameterOrPropertyWorker (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:35591:41)
    at getTypeOfVariableOrParameterOrProperty (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:35567:48)
    at getTypeOfSymbol (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:35856:24)
    at getExternalModuleMember (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:32495:64)
    at getTargetOfImportSpecifier (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:32530:20)
    at getTargetOfAliasDeclaration (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:32562:28)
    at resolveAlias (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:32595:30)
    at checkAliasSymbol (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:55749:26)
    at checkImportBinding (/Users/aa/.nvm/versions/node/v6.10.3/lib/node_modules/typescript/lib/typescript.js:55778:13)
error Command failed with exit code 1.
```
Any idea?

**Comment by weswigham** [comment]
@A-Atrash with what version of the compiler? This fix is only in `typescript@next`.

**Comment by magic-akari** [comment]
I have installed `typescript@next` and get the error 
```
global.d.ts:2:9 - error TS2502: 'React' is referenced directly or indirectly in its own type annotation.

2   const React: typeof import("react");
```

while the `ReactDOM` works as expected.

Any idea?

**Comment by weswigham** [comment]
Does something in the react module somehow depend on the global declaration you add? Offhandedly, that's what I can think of.

**Comment by A-Atrash** [comment]
@weswigham I solved it by downgrading to TypeScript 3.1 (if this any makes sense!)

**Comment by magic-akari** [comment]
> Does something in the react module somehow depend on the global declaration you add? Offhandedly, that's what I can think of.

I have no idea. I never modified `@types/react` or other libs, The [gist](
https://gist.github.com/magic-akari/aa10dfb809268eb4f63d5749d113a93a) will reproduce the error with `typescript@next`.

I am going to export the types of React as global Object, for I import React in html's script tag via CDN.
The gist works with `typescript@3.1.6`, crashes on `typescript@3.2.1`.
And `typescript@next` gives me the error.

**Comment by livthomas** [comment]
I am still getting the same error in **TypeScript 3.2.2** where it should have been fixed.
```
ERROR in : Error: Debug Failure. Invalid cast. The supplied value [object Object] did not pass the test 'isJsonSourceFile'.
    at Object.cast (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:1325:22)
    at getTypeOfVariableOrParameterOrPropertyWorker (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:35591:41)
    at getTypeOfVariableOrParameterOrProperty (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:35567:48)
    at getTypeOfSymbol (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:35856:24)
    at checkVariableLikeDeclaration (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:54043:41)
    at checkVariableDeclaration (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:54116:20)
    at checkSourceElement (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:56137:28)
    at Object.forEach (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:210:30)
    at checkVariableStatement (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:54126:16)
    at checkSourceElement (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:56106:28)
    at Object.forEach (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:210:30)
    at checkSourceFileWorker (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:56305:20)
    at checkSourceFile (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:56277:13)
    at getDiagnosticsWorker (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:56352:17)
    at Object.getDiagnostics (/home/myprofile/myproject/node_modules/typescript/lib/typescript.js:56338:24)
    at /home/myprofile/myproject/node_modules/typescript/lib/typescript.js:87001:85
```

**Comment by eugene1g** [comment]
@livthomas the betas work for me e.g. `3.3.0-dev.20190110`

**Comment by davidLeonardi** [comment]
Still having this issue with typescript@next ,  which is now 3.4.0-dev[31st jan 2019]

**Comment by edsilv** [comment]
Same issue with typescript@next `3.5.0-dev`.

**Comment by weswigham** [comment]
Do you have a small repro?

**Comment by edsilv** [comment]
@weswigham https://github.com/IIIF-Commons/iiif-metadata

I solved it by updating stencil to `0.18.0`. Try setting it back to `0.16.2` to reproduce.

As far as I can tell it's the contents of `globals.d.ts` that are causing the build error. So not sure why updating stencil made a difference...

**Comment by weswigham** [comment]
Stencil `0.16.2` uses TS `3.2.2` internally (irrespective of what version you install above it), which'd be why upgrading stencil fixed it for you :P

**Comment by edsilv** [comment]
Right... Makes sense!
