### ISSUE TITLE
"Type instantiation is excessively deep and possibly infinite." error when upgrading from 4.4.4 to 4.5.2

### ISSUE THREAD

**Issue by sinbino** [microsoft/TypeScript#46848]
# Bug Report

### 🔎 Search Terms

* Type instantiation is excessively deep and possibly infinite

### 🕗 Version & Regression Information

When compiling the source that imports the @sinclair/typebox package using tsc 4.5.2
```ts
import { Static, Type } from '@sinclair/typebox'
```
The following error will occur.
```ts
node_modules/@sinclair/typebox/typebox.d.ts:239:104 - error TS2589: Type instantiation is excessively deep and possibly infinite.

239 export declare type StaticConstructor<T extends readonly TSchema[], U extends TSchema> = new (...args: [...{
                                                                                                           ~~~~~
240     [K in keyof T]: Static<T[K]>;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
241 }]) => Static<U>;
    ~~
```
Compiling the same code with tsc 4.4.4 succeeds.
There have been a few reports of similar issues, but this is the difference between 4.4.4 and 4.5.2. It could be a different problem.

https://unpkg.com/@sinclair/typebox@0.20.5/typebox.d.ts
Probably, tsc 4.4.4 interprets this type definition file correctly, but tsc 4.5.2 does not.

### ⏯ Playground Link

No tsc 4.5.2 in playground.

### 💻 Code

```ts
import { Static, Type } from '@sinclair/typebox'
```
Just import it.

### 🙁 Actual behavior

In tsc 4.5.2  (and 4.6.0-dev.20211117), receive the error "Type instantiation is excessively deep and possibly infinite.

### 🙂 Expected behavior

tsc 4.5.2 should compile as successfully as tsc 4.4.4.

**Comment by gudleik** [comment]
This has been fixed in typebox: https://github.com/sinclairzx81/typebox/issues/119

**Comment by sinbino** [comment]
@gudleik
Thanks for telling me!
