### ISSUE TITLE
Type guard functions seem to only set the type when used directly

### ISSUE THREAD

**Issue by jvanoostveen** [Microsoft/TypeScript#10172]
**TypeScript Version:**  typescript@beta (2.0)

**Code**

```ts
// Setup
interface A {
  value: string;
}
interface B {
  property: string;
}
type AorB = A | B;

let isB = (obj: any): obj is B => {
  return obj.hasOwnProperty('property');
};
// Setup end


let output = (obj: AorB) => {
  if (isB(obj)) {
    console.log(obj.property); // <-- works

    let values = (new Array(100)).map(a => obj.property); // <-- Property 'property' does not exist on type 'A | B'
    console.log(values);
  }
};


let someObj: B = { property: 'value' };
output(someObj);
```

**Expected behavior:**
`obj.property` within the `map` should still know its type. This works fine in pre-2.0.

**Actual behavior:** 
The compiler does not recognise `property` as part of `obj` within the `map`.

**Comment by jvanoostveen** [comment]
In some of our existing code I get the following error on similar structures:
`Error TS2339: Property 'value' does not exist on type 'never'.`

**Comment by kitsonk** [comment]
This is a dupe of #7719 and so many others.  Specifically the comment is [here](https://github.com/Microsoft/TypeScript/issues/7719#issuecomment-202684512) as to why it is the way it is.  The team is considering allowing parameters to be declared as `const` to indicate they will not be changed within a function.

**Comment by jvanoostveen** [comment]
Looks like I searched for the wrong terms :). Continue on the referenced issue then.
