### ISSUE TITLE
Can't extend WeakMap in type-checked JS files

### ISSUE THREAD

**Issue by zombie** [microsoft/TypeScript#56664]
### 🔎 Search Terms

WeakMap constructors return type JSDoc

### 🕗 Version & Regression Information

- This is the behavior in every version I tried.  I opened #23551 5 years ago, but it got closed in error, as it was never fixed.

### ⏯ Playground Link

https://www.typescriptlang.org/play?filetype=js#code/MYGwhgzhAEDCD2J4CcCyYAO0CmAPALtgHYAmMA6tmANbpYDeAUNNMPERPsgK7D4oAKAJTQmLFhG4ZsyYQG5m0AL6MlQA

### 💻 Code

```js
class ColorMap extends WeakMap {
  constructor() {
    super();
  }
}
```

### 🙁 Actual behavior

> color.js(1,24): error TS2510: Base constructors must all have the same return type.

I tried a few different workarounds, like adding @template generic params, or forcing types using @type JSDoc, but nothing seems to work.

### 🙂 Expected behavior

No error.

**Comment by MartinJohns** [comment]
> but it got closed in error, as it was never fixed.

It was fixed, but then subsequently broken by #28052  (as mentioned in [this comment](https://github.com/microsoft/TypeScript/pull/28052/files#r528390266)). @ExE-Boss opened the PR #41635, but it was never completed.

**Comment by fatcerberus** [comment]
Looks like an exact duplicate of https://github.com/microsoft/TypeScript/issues/23551?

**Comment by MartinJohns** [comment]
@fatcerberus He mentioned that issue in the "Version & Regress Information" section. The issue was fixed, but then broken and not fixed again: https://github.com/microsoft/TypeScript/issues/56664#issuecomment-1839168729
