### ISSUE TITLE
Promise.all returns Promise<Promise<T>[]>

### ISSUE THREAD

**Issue by msklvsk** [Microsoft/TypeScript#7566]
**TypeScript Version:** 

1.8.9

**Code**

```ts
Promise.all([Promise.resolve('')]);  // has type Promise<Promise<string>[]>
```

**Expected behavior:**
The expression has type `Promise<string[]>` as in 1.8.7
**Actual behavior:** 
The expression has type `Promise<Promise<string>[]>`

**Comment by jods4** [comment]
+1
This is a regression in 1.8.9.
Our build pipeline has a dep. on TS `~1.8.0`. 
When 1.8.9 was fetched we started getting type errors in code like this:
```typescript
let [{ content: x }, { content: y }] = Promise.all([fetch('x'), fetch('y')]);
// error TS2459: Type 'Promise<HttpResponseMessage>' has no property 'content' and no string index signature
```

**Comment by MarcusNoble** [comment]
I have a reproducible example here: https://gist.github.com/MarcusNoble/522b1fea7077be0af59a

**Comment by MarcusNoble** [comment]
This is caused by 1589e4f57e39aa6c5bb9e0be39f60191cf94f8b9 limiting the depth of type inference to 5. There is no way of overriding this behaviour. 

@vladima Are you able to weigh in on this?

**Comment by vladima** [comment]
yes, I can repro this.

**Comment by jods4** [comment]
I don't fully understand what happens under the hood here, but is this error message the one you'd expect? Shouldn't we have some kind of "type inference failed" error (or at least warning) for cases that go beyond whatever depth you set?

It is a bit surprising and unhelpful that TS decides the expression is `Promise<T>[]` when it is `T[]` without a warning. A message about failing to infer would have led me to the workaround of specifying types explicitly.

**Comment by donaldpipowitch** [comment]
A bug fix release as 1.8.10 would be nice.

**Comment by jpsfs** [comment]
Has this made 1.8.10?

**Comment by hbakhtiyor** [comment]
still reproduce at `1.8.10` version

```ts
    getResults(): Promise<string[]> {
        const results: string[] = [];
        const promises = results.map(result => {
            return Promise.resolve(result);
        });

        return Promise.all(promises);
    }
```

```
error TS2322: Type 'Promise<Promise<string>[]>' is not assignable to type 'Promise<string[]>'.
  Type 'Promise<string>[]' is not assignable to type 'string[]'.
    Type 'Promise<string>' is not assignable to type 'string'.

```

**Comment by mhegazy** [comment]
The fix is in TS 2.0 as noted from the "Milestone".

**Comment by jppellerin** [comment]
Any workaround until 2.0 is released?

**Comment by tht13** [comment]
Revert to typescript 1.8.7 is what I had to do

**Comment by XS-Z** [comment]
Just confirm that the bug still can be reproduced in 1.8.10.
What I did is that set the <TAll> explicitly. 
`let promises: Promise<user_profile>[] = links.map(lnk => getUserProfileByURL(lnk));
// Promise.all(promises).then(profiles => {
//     resolve(profiles);    // the editor says that the type of profiles is Promise<user_profile>[] 
// }, (err: any) => reject(err));
Promise.all<user_profile>(promises).then(profiles => {
    resolve(profiles);
}, (err: any) => reject(err));`
