### PR TITLE
Do not walk up control flow containers for `this`

### LINKED ISSUE #14860: Property does not exist on type '(Anonymous class)'
**TypeScript Version:**
Version 2.2.1
Version 2.3.0-dev.20170325

**Code**

```ts
while (0);

new class {
    methodA() {
        this;
    }
};

new class {
    methodB() {
        this.methodB;
    }
};
```

**Expected behavior:**
No errors.

**Actual behavior:**
testbug.ts(11,14): error TS2339: Property 'methodB' does not exist on type '(Anonymous class)'.

And if you replace `this.methodB` with `this.methodA` it typechecks fine when it should not.
This didn't happen in earlier versions, Version 2.0.0 works as expected.

### PR DESCRIPTION
**Pull request by sandersn**
Do not walk up control flow containers for `this`. References to `this` should not continue looking outside their immediate container to narrow. 

Introduced by #11458, which allows narrowing of captured variables inside methods of class expressions. That meant `this` also attempted to narrow outside its container, which meant that references to `this` were cached as if they were references to a single variable named "this", even though they came from different class expressions.

Fixes #14860

### CODE REVIEW

**Comment by sandersn** [comment]
@sheetalkamat @mhegazy can you take a look?
