### ISSUE TITLE
Type inference in JSX broke in nightly build

### ISSUE THREAD

**Issue by ulrichb** [Microsoft/TypeScript#27986]
**TypeScript Version:**  3.2.0-dev.20181019

**Search Terms:** react jsx type inference

**Code**
```ts
import * as React from "react";

interface ErrorResult {
    readonly error: true
}

interface AsyncLoaderProps<TResult extends {}> {
    readonly asyncLoad: () => Promise<TResult>;
    readonly children: (result: Exclude<TResult, ErrorResult>) => React.ReactChild;
}

class AsyncLoader<TResult extends {}> extends React.Component<AsyncLoaderProps<TResult>> {
    render() { return null; }
}

async function load(): Promise<{ success: true } | ErrorResult> {
    return { success: true };
}

class SomeComponent extends React.Component<{}> {

    render() {
        return (
            <AsyncLoader asyncLoad={load}>{result =>
                <div>{result.success}</div>
            }
            </AsyncLoader>
        );
    }
}
```

TSC call: `npx tsc -t es2017 -m commonjs --jsx react --strict src/TypeScriptIssue.tsx`

(Without `--strict` there is no compile error.)

**Expected behavior:**
No compile error.

**Actual behavior:**
```
src/TypeScriptIssue.tsx:24:26 - error TS2322: Type '() => Promise<ErrorResult | { success: true; }>' is not assignable to type '() => Promise<{ success: true; }>'.
  Type 'Promise<ErrorResult | { success: true; }>' is not assignable to type 'Promise<{ success: true; }>'.
    Type 'ErrorResult | { success: true; }' is not assignable to type '{ success: true; }'.
      Type 'ErrorResult' is not assignable to type '{ success: true; }'.
        Property 'success' is missing in type 'ErrorResult'.

24             <AsyncLoader asyncLoad={load}>{result =>
                            ~~~~~~~~~

  src/TypeScriptIssue.tsx:8:14
    8     readonly asyncLoad: () => Promise<TResult>;
                   ~~~~~~~~~
    The expected type comes from property 'asyncLoad' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<AsyncLoader<{ success: true; }>> & Readonly<{ children?: ReactNode; }> & Readonly<AsyncLoaderProps<{ success: true; }>>'
```

This is a regression in 3.2.0. Code compiles in 3.1.3.

**Comment by DanielRosenwasser** [comment]
Likely a duplicate of #27948

**Comment by weswigham** [comment]
> Likely a duplicate of #27948

:doubt: It's probably not; that only has to do with tags with multiple signatures.

**Comment by ulrichb** [comment]
@weswigham  I really don't know why, ... but since updating `@types/react` (and having a current TS version) the exact same issue appeared again:

![image](https://user-images.githubusercontent.com/388796/53250094-00fe6600-36ba-11e9-84e2-011d8e86b3a3.png)

I've tacked it down and it happened exactly with `@types/react@16.7.21` (version `@types/react@16.7.20` and before works fine).

I've generated a diff of these two versions: [Compare.pdf](https://github.com/Microsoft/TypeScript/files/2894517/Compare.pdf)

And here are the full packages: [both_versions.zip](https://github.com/Microsoft/TypeScript/files/2894521/both_versions.zip)

Could you maybe have a look at this?

**Comment by weswigham** [comment]
@ulrichb could you open a new issue so it's easier to track?

**Comment by ulrichb** [comment]
@weswigham Of course. [Here it is](https://github.com/Microsoft/TypeScript/issues/30057).
