### ISSUE TITLE
Chaining from Promise<any> incorrectly results in Promise<any>

### ISSUE THREAD

**Issue by ChrisGrohHS** [Microsoft/TypeScript#14292]
**TypeScript Version:**  2.2.1

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
var t = Promise.resolve<any>(null).then(() => "ABC");
var x: Promise<number> = t;// No error, t is Promise<any> but should be Promise<string>
```

**Expected behavior:**
t is typed as Promise\<string\>
Error noting that Promise\<string\> is not assignable to Promise\<number\>

**Actual behavior:**
No error

**Comment by emirotin** [comment]
I think it's part of the bigger problem

Let's look at this code

```
const fetchConfig = (apiUrl: string): Promise<Config> => {
	return fetch(apiUrl)
	.then(response => response.json())
	.then(data => data as Config) <!-- here
}
```

At the line marked with the comment I expect `data` to be of type `any` because it's essentially anything returned by the server parsed as JSON. So it should be convertible to any type.

Nevertheless TS reports 

```
ERROR in ./src/setup/load-config.ts
(33,16): error TS2352: Type 'Response' cannot be converted to type 'Config'.
```

So it's thinking the original `fetch` is returning `Promise<Response>` and thus the entire chain of `.then`s is typed in this way.

**Comment by lucky7id** [comment]
I was going crazy trying to figure this one out, but I think @emirotin hit it on the head. Replicated on 2.2.1, after upgrading from 2.1.4 in hopes of an updated lib

**Comment by jods4** [comment]
Hitting this as well. There is a repo (TS 2.2.1) of @emirotin 's problem right here: 
https://github.com/jods4/aurelia-webpack-build/blob/master/demos/06-ASPNET/App/app.ts#L6

I expect that `.then(response => response.json())` results in `Promise<any>` but it seems TS prefers the other `.then` overload and returns a `Promise<Response>`, which is plain wrong.

Adding an explicit generic type, as done in the repo example, works around the problem:
`.then<any>(r => r.json())`

**Comment by mhegazy** [comment]
Should be fixed in latest.
