### ISSUE TITLE
Type inference has failed by parameter order (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#19858]
Intended degradation?

cc @ahejlsberg 

**TypeScript Version:** master

**Code**

```ts
declare function f<a>(as1: a[], as2: a[], cmp: (a1: a, a2: a) => number) 
f(Array.from([0]), [], (a1, a2) => a1 - a2);
f(Array.from([]), [0], (a1, a2) => a1 - a2);
```

**Expected behavior:**

no error

**Actual behavior:**

```
$ node built/local/tsc.js index.ts -t es6 --strictNullChecks
index.ts(3,36): error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
index.ts(3,41): error TS2363: The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
```

**Comment by mhegazy** [comment]
```ts
c:\test\sandbox7>type a.ts
declare function f<a>(as1: a[], as2: a[], cmp: (a1: a, a2: a) => number): void;

f(Array.from([0]), [], (a1, a2) => a1 - a2);
f(Array.from([]), [0], (a1, a2) => a1 - a2);

c:\test\sandbox7>tsc --v
Version 2.7.0-dev.20171109

c:\test\sandbox7>tsc a.ts --lib es6

c:\test\sandbox7>echo %ERRORLEVEL%
0
```

**Comment by mhegazy** [comment]
I think your example is not correct, and you are looking at a result of https://github.com/Microsoft/TypeScript/pull/19745.

**Comment by falsandtru** [comment]
> c:\test\sandbox7>tsc a.ts --lib es6

You have to enable strictNullChecks option.

**Comment by falsandtru** [comment]
> you are looking at a result of #19745.

Seems like your are right but this result is bad. @ahejlsberg Is this you intended result?

**Comment by gcnew** [comment]
#19745 fixes a legitimate issue. However, I do agree that the exhibited behaviour here is also a bug.

The problem is that `Array.from([])` should either be:
 - contextually typed
 - inferred as `<T> T[]`, i.e. an array of a "to be specified" generic type

Currently the call to `Array.from` is eagerly resolved to `Array.from<{}>` while before it was incorrectly resolved to `Array.from<never>`.

In any case, the root cause is https://github.com/Microsoft/TypeScript/issues/9366.

**Comment by ahejlsberg** [comment]
It is indeed a regression caused by #19745 where we make no inferences from the `never` element type of an empty array literal. Another way we could solve #19576 (the issue addressed by #19745) is to give inferences from the element type of empty array literals *lower priority* than all other inferences. That would still fix #19576 but wouldn't affect the code in this issue.
