### ISSUE TITLE
`cb: (x: T) => void` not assignable to `cb: (x: T) => void` when it has an overload: "'any' is not assignable to 'never'"

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript#23352]
**TypeScript Version:**  2.9.0-dev.20180411

**Code**

```ts
declare function provide<T>(cb: (x: T) => void): void;
declare function provide<T>(cb: (x: T[keyof T]) => void): void;

declare function provider<T>(provide: (cb: (x: T) => void) => void): void;
provider(provide);
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(4,10): error TS2345: Argument of type '{ <T>(cb: (x: T) => void): void; <T>(cb: (x: T[keyof T]) => void): void; }' is not assignable to parameter of type '(cb: (x: never) => void) => void'.
  Types of parameters 'cb' and 'cb' are incompatible.
    Types of parameters 'x' and 'x' are incompatible.
      Type 'any' is not assignable to type 'never'.
```

Worked in `typescript@2.9.0-dev.20180327`, broken in `typescript@2.9.0-dev.20180328`.

**Comment by weswigham** [comment]
I've opened a PR with a potential fix for the first, and opened a new issue for the second (since it seems to have a separate root cause) so this issue can just track the first.

**Comment by RyanCavanaugh** [comment]
The fix here seems to have nonzero perf impact and we haven't seen any other reports. Punting for now.
