### ISSUE TITLE
Union types are not being narrowed correctly in generic functions in 4.3

### ISSUE THREAD

**Issue by TomPeters** [microsoft/TypeScript#44404]
# Bug Report

Narrowing of a union type based on generic types does not work correctly in `else` branches in TS 4.3.

This likely relates to the changes made in https://github.com/microsoft/TypeScript/pull/43183

### 🔎 Search Terms

generic, narrow, union types, 4.3

### 🕗 Version & Regression Information

This changed between versions 4.2.3 and 4.3

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.3.2&ssl=13&ssc=2&pln=1&pc=1&strict=true#code/GYVwdgxgLglg9mABGApigJgZwCpwHICGATkXAO7YAWK2AngA4oA8AYjEZlIigB5QpgsiAN6JgcOAC5EnIjDABzRAF8ANIgDKKCAnTc+AoaIBGxabPlLlAPgAUUSpelsOXAD6btugJQiAUIiBiDDAiLaUBJgAgiwS9o6K3r7CAUFpOmCYcAA2KAB02XAK8ZZ54nDeANypgco13NmYKP5paQD0bYgAkohkcCDZeryM0IgOMJhjcL1wRADWiMbaBCBNY9RjDM2YlP2Di81gxKRkGMFI45PGRASQlFOIAAZaGeiP9ekIWbkFRSWKeVMRCqiA6iAAoiRZtIAAqkRhEKC0RAAciBKMQ6DgKEmYDgXF4Ey4CE2jFRLk4iA8L10KLy9Tq9VAkFgJIi0VicFsADcCNkQChnOxKdSvIJvNJefzmhNEBSuClWkEiCgoCAiEgAETlTXnRBSgXVNJ1ZRAA)

### 💻 Code

```ts
function needsToNarrowTheType<First extends { foo: string }, Second extends { bar: string }>(thing: First | Second) {
    if (hasAFoo(thing)) {
        console.log(thing.foo);
    }
    else {
        // I would expect this to work because the type should be narrowed in this branch to `Second`
        console.log(thing.bar); // Error: Property 'bar' does not exist on type 'First | Second'.
    }

    function hasAFoo(value: First | Second): value is First {
        return "foo" in value;
    }
}
```

### 🙁 Actual behavior

In the `else` branch, the type of `thing` is `First | Second`.

### 🙂 Expected behavior

In the `else` branch. the type of `thing` is `Second`.

**Comment by fabb** [comment]
looks similar to my issue:


```ts
type Value = string | number | boolean | unknown[] | null
type ValueObject<V extends Value> = Record<string, V | undefined>
type ResponsiveValue<V extends Value> = V | ValueObject<V>

const isValue = <V extends Value>(object: ResponsiveValue<V>): object is V => !isObject(object)
const isValueObject = <V extends Value>(object: ResponsiveValue<V>): object is ValueObject<V> => isObject(object)
const isObject = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && !Array.isArray(value)

const responsiveSome = <V extends Value>(value: ResponsiveValue<V>, callbackfn: (value: V) => boolean) => {
    if (isValue(value)) {
        return callbackfn(value)
    } else {
        // BUG in 4.3: value should have type ValueObject<V>, but has ValueObject<V> | Value
        return Object.values(value).some(v => (typeof v === 'undefined' ? false : callbackfn(v)))
    }
}

```



<details><summary><b>Output</b></summary>

```ts
"use strict";
const isValue = (object) => !isObject(object);
const isValueObject = (object) => isObject(object);
const isObject = (value) => typeof value === 'object' && !Array.isArray(value);
const responsiveSome = (value, callbackfn) => {
    if (isValue(value)) {
        return callbackfn(value);
    }
    else {
        // BUG in 4.3: value should have type ValueObject<V>, but has ValueObject<V> | Value
        return Object.values(value).some(v => (typeof v === 'undefined' ? false : callbackfn(v)));
    }
};

```


</details>


<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```


</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.3.2#code/C4TwDgpgBAaghgGwK7QLxQM7AE4EsB2A5lAD5T5IC2ARhNqVNQPZMIRz4NL4DW+TAd3wBtALoMKCBAFgAUKEixEKAPLUAVhADGwADwwoEAB7AI+ACYYlyCAD4o6AEram2c7qx4iAGlhcLEABmBBDmtnIK0M4YYEz4GLgAbhDwNvqGJmaW1ij26AZkqaoa2now4bJyWnFYULgYRWhQ6camFlaNtgAUTCU6AFxQ0bHxSSnKEPq2AJSDvZo6dR0O9gCE9WoLwD19wNNVNcBLjZulDs0GrVkdE93zpYPDNWONU7NQ94v1ORCnOlMrJZ-bafPYHeJHDa7c5dRITQbcPiCfDvOE2JZDFxuDw4AiEXyI-hCPL2SJMQJQNEoByodAAclBdKgADJmVBVgBBbDYOAgAB09S5PJAsIm+0qsmqEKg2AgMWeyQAykxKE0Wpl2j9ulSII85SMEslXuVfFpEAhqHAtDxAvhBqKbIMYNNAcxWOwUYCAN5yKB+uoUrr1RoOlDTF0+2T+6MyiDAJDYThmqSW6220MQcXRgC+hgQGGgkZj-oA9CWoAAhACqAHE6pwACx8gDMgx1mAAFkwkAhzFAO3BklBIj9gVNfNQkEcBzcbGPygxGr7i7H44moMC+TqMBnpnyMCqILDAV0yRTEjT6dxzEEQuYmQB+KCBRAFqCDZMWq02-Cw8NZ-1szkIDZCAA)

**Comment by thw0rted** [comment]
I found a regression that I *think* might be the same one.  (If not I can certainly open a new ticket?)

[Playground example](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgKgdwPYHEBTAO0KgEtYAeTAGgQFUA+BAbwCgEuEAHAVxDJKCUJBjwEUQsAAmuYsgCeCCAC4sAbnaduPKLgiF4hGSPDQ4iAPp91DLd14ChsBAHNCiPgAoAlHbZJTz4oYhUAC3IwADobDQQAXx0ufkFhME8EHwA3YGQ7X0CISJibBABeBFzkeKSk9hQ0DABhSOQZAEYEQgAPQ2IZDBwCEjJKKmI+AFsQMnoQXFxkaWIWDkdUlyDZeSUVCoQAZgddfUNjUzLKgDM8jK16xvQEVvJ2gCZuvpJBrDwiUgUahicjENzzRbLYCrNjJJxpVxSHYKZSISoAIgAEuR0ScUmcjIZLnwDrdkPd2PV2DIjKgpEh5JAED11MMAWNqNDFPQuUwtOxyNcEN4eghQZBobBCLgha92h1CutuD1oiTKtA+IQHgKhSKxcQJcQpTKXm0ZO9FXCVWqVFBNdqdcLReKIJLpbKzV0AD5e5n6w3Gj1vc2WxzWg4arWU7RAA)

````ts
abstract class TwoGeneric<T, U> {
    public abstract readonly t: T;

    protected abstract _u: U;
    public get u(): U { return this._u; }
    public set u(val: U) { this._u = val; }
}

class Child1 extends TwoGeneric<number, boolean> {
    public readonly t = 3;
    protected _u = false;
}

class Child2 extends TwoGeneric<string, boolean> {
    public readonly t = "Hi";
    protected _u = false;
}


declare const x: TwoGeneric<any, any>;

if (x instanceof Child1) {
    x.u = true;
}
if (x instanceof Child2) {
    x.u = true;
}

if (x instanceof Child1 || x instanceof Child2) {
    x.u = true;  // Type 'boolean' is not assignable to type 'U'.  'U' could be instantiated with an arbitrary type which could be unrelated to 'boolean'.(2322)
}
````

Note that this works without errors in 4.2.x but fails in 4.3.x due to the "improved" narrowing.

The two standalone type-narrowing checks work, but the narrowed union fails. Inside the `||` conditional, Intellisense hints that `x` is `Child1 | Child2`.  The type of `x.u` is the same for both, but it still fails with the error message in the comment.

**Comment by fabb** [comment]
> looks similar to my issue:
> 
> ```ts
> type Value = string | number | boolean | unknown[] | null
> type ValueObject<V extends Value> = Record<string, V | undefined>
> type ResponsiveValue<V extends Value> = V | ValueObject<V>
> 
> const isValue = <V extends Value>(object: ResponsiveValue<V>): object is V => !isObject(object)
> const isValueObject = <V extends Value>(object: ResponsiveValue<V>): object is ValueObject<V> => isObject(object)
> const isObject = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && !Array.isArray(value)
> 
> const responsiveSome = <V extends Value>(value: ResponsiveValue<V>, callbackfn: (value: V) => boolean) => {
>     if (isValue(value)) {
>         return callbackfn(value)
>     } else {
>         // BUG in 4.3: value should have type ValueObject<V>, but has ValueObject<V> | Value
>         return Object.values(value).some(v => (typeof v === 'undefined' ? false : callbackfn(v)))
>     }
> }
> ```
> 
> Output
> Compiler Options
> **Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.3.2#code/C4TwDgpgBAaghgGwK7QLxQM7AE4EsB2A5lAD5T5IC2ARhNqVNQPZMIRz4NL4DW+TAd3wBtALoMKCBAFgAUKEixEKAPLUAVhADGwADwwoEAB7AI+ACYYlyCAD4o6AEram2c7qx4iAGlhcLEABmBBDmtnIK0M4YYEz4GLgAbhDwNvqGJmaW1ij26AZkqaoa2now4bJyWnFYULgYRWhQ6camFlaNtgAUTCU6AFxQ0bHxSSnKEPq2AJSDvZo6dR0O9gCE9WoLwD19wNNVNcBLjZulDs0GrVkdE93zpYPDNWONU7NQ94v1ORCnOlMrJZ-bafPYHeJHDa7c5dRITQbcPiCfDvOE2JZDFxuDw4AiEXyI-hCPL2SJMQJQNEoByodAAclBdKgADJmVBVgBBbDYOAgAB09S5PJAsIm+0qsmqEKg2AgMWeyQAykxKE0Wpl2j9ulSII85SMEslXuVfFpEAhqHAtDxAvhBqKbIMYNNAcxWOwUYCAN5yKB+uoUrr1RoOlDTF0+2T+6MyiDAJDYThmqSW6220MQcXRgC+hgQGGgkZj-oA9CWoAAhACqAHE6pwACx8gDMgx1mAAFkwkAhzFAO3BklBIj9gVNfNQkEcBzcbGPygxGr7i7H44moMC+TqMBnpnyMCqILDAV0yRTEjT6dxzEEQuYmQB+KCBRAFqCDZMWq02-Cw8NZ-1szkIDZCAA)

@andrewbranch this bug still happens in 4.5.4. Should I create a separate issue for this?

**Comment by fabb** [comment]
True, thanks!
It’s still a regression, but maybe there really is no use case that cannot be transformed like this.
