### ISSUE TITLE
Supports `exports` pointing to a TypeScript file, which keeps consistent with `main`

### ISSUE THREAD

**Issue by pd4d10** [microsoft/TypeScript#48369]
# Bug Report

In some cases, we want to import from the source code instead of the compiled, which is perfectly implemented by the `main` field:

```json
// package.json
{
  "main": "./src/index.ts"
}
```

While it seems not to work at the newly introduced `exports` field

### 🔎 Search Terms

https://github.com/microsoft/TypeScript/issues/46452
https://github.com/microsoft/TypeScript/issues/48084

### 🕗 Version & Regression Information

- This is the behavior in every version (*the latest stable and nightly versions*) I tried

### ⏯ Playground Link

This is about the package.json behavior, and the playground seems can't reproduce it.

### 💻 Code

```json
// the library's package.json
{
  "exports": {
    ".": "./src/index.ts"
  }
}
```

```ts
// trying to use this library
import { xxx } from 'my-lib'
```

### 🙁 Actual behavior

It would show a `ts2037` error message:

```
Cannot find module 'my-lib' or its corresponding type declarations. ts(2307)
```

### 🙂 Expected behavior

Works correctly, just like the `main` field's behavior.

**Comment by Jamesernator** [comment]
ESM/packages support in TS is not shipping yet, but it's hopefully gonna ship in [TypeScript 4.7](https://github.com/microsoft/TypeScript/issues/48027).

You can try it out by using `typescript@next`, you'll need to change a tsconfig setting though [as mentioned here in the handbook](https://www.typescriptlang.org/docs/handbook/esm-node.html)

**Comment by Jamesernator** [comment]
Currently TypeScript [doesn't actually officially support importing modules with a `.ts` extension](https://github.com/microsoft/TypeScript/issues/37582). The fact that `"main"` works today at all is probably more of an accident from however TypeScript is parsing and resolving the fields in `package.json`.

The current [advice in the handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) is for packages to use `"types": "./src/index.ts"` instead.

My guess is you're either wanting this behaviour for either usage in Deno or in something like `ts-node`. In the first case, Deno has it's own language server because of the aformentioned issue of not supporting `.ts`, and in the latter (e.g. `ts-node`) yeah it's a bit of a pain you can't currently put `"main": "./index.js"` and have ts-node resolve it correctly yet.

**Comment by RyanCavanaugh** [comment]
@weswigham thoughts?

**Comment by weswigham** [comment]
Uhh, I mean, I guess it should work, given how our resolution historically proceeds, and currently doesn't. Workaround for now is just to say `.js` instead of `.ts` in the export map - that's enough to get us to find the source `.ts`.

Fix is pretty simple for us - in `moduleNameResolver.ts` in `loadJSOrExactTSFileName` we currently have a check for a bunch of `.d.ts`y extensions to explicitly allow exact matches to those - we could add all the `.ts`y extensions to that list, too, for the desired effect here.

**Comment by weswigham** [comment]
Like, [this](https://github.com/weswigham/TypeScript/commit/bf03421f6f5a4a52862b30fe5f602d88fcfe2204) is probably the change we'd need to make to support this, I suppose.

**Comment by DanielRosenwasser** [comment]
Is this a possible foot-gun though? Is there a reason why this behavior is desirable?

**Comment by milesj** [comment]
Just my 2 cents, but if you want to provide TS files as the entry point, just use `main`? It _doesn't need to_ use `exports`.

**Comment by Jamesernator** [comment]
> Just my 2 cents, but if you want to provide TS files as the entry point, just use `main`? It _doesn't need to_ use `exports`.

`"exports"` can do more than just specify the main entry point, like if this were supported then things like:

```json
{
    "exports": {
        "./subname": "./src/libs/subname-impl.ts"
    }
}
```

would presumably be supported as well.

Although there is the question as to whether actually supporting this is a good idea or not, like the fact `"main"` works at all today seems fairly inconsistent given that TypeScript doesn't usually allow importing directly from `.ts` extensions. (i.e. `import ... from "./file.ts";` is not supported).

---

In either case, it would probably be worth making it so that resolution in node12/nodenext is at least consistent for both `"main"` and `"exports"`, either officially supporting `.ts` resolutions or not.

Existing resolution probably relies on it in places, so removing support there would probably not be a non-breaking change. Such places going forward though probably won't be able to rely on it with `"exports"` being a thing anyway, so if it's not supported in `"exports"` in node12/nodenext resolution, it's probably better to turn it off for `"main"` as well.

**Comment by vjpr** [comment]
Same error over here. I actually cannot get anything to do with exports working with 4.7.0-beta. 

I have tried all iterations:

```
  "exports1": {
    ".": {
      "types1": "./src/index.ts",
      "import": {
        "default": "./lib/index.js",
        "types": "./lib/index.js",
        "types1": "./src/index.ts",
        "default1": "./src/index.ts"
      }
    }
  },
  "exports2": {
    ".": "./lib/index.js"
  },
  "exports": {
    ".": {
      "import":"./lib/index.js"
    }
  }
```

**Comment by milesj** [comment]
@vjpr I got this work rather easily as seen here: https://github.com/milesj/packemon/pull/122/files

If you look at my test file here https://github.com/milesj/packemon/blob/master/tests/testPackemonImports.ts, you'll see that I'm importing from `packemon/babel`, which is using `exports`. I'm also ensuring that referential equality works as expected.

Be sure your `moduleResolution` is set to `nodenext`.

**Comment by vjpr** [comment]
@milesj Try removing the `main` field. For me this then starts throwing the "cannot find module" error.

**Comment by vjpr** [comment]
@milesj Your package is also set to `"type": "commonjs",`...does it work if you change to `module`?

**Comment by vjpr** [comment]
After debugging the source code I now understand the issue better which is just as weswigham said:

> Workaround for now is just to say .js instead of .ts in the export map - that's enough to get us to find the source .ts.
> https://github.com/microsoft/TypeScript/issues/48369#issuecomment-1081258778

Just to make it clear for anyone else:

https://github.com/microsoft/TypeScript/blob/3d3fa0c0c83050d26390ef5773c471e15c8f1b21/src/compiler/moduleNameResolver.ts#L1505-L1525

`loadJSOrExactTSFileName` will only resolve for `.dts` files. If this fails, then it tries to remove the `.js` extension and add ` .ts` extension.

The fix is just to remove `&& isDeclarationFileName(candidate)`.
