### ISSUE TITLE
lib.es2020.intl.d.ts conflicts with lib.es5.d.ts

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#42128]
# Bug Report

### 🕗 Version & Regression Information

- Regressed by #41880

### ⏯ Playground Link

N/A

### 💻 Code

No code required, build any code with `target: es2020`

### 🙁 Actual behavior

```
node_modules/typescript/lib/lib.es2020.intl.d.ts(307,9): error TS2717: Subsequent property declarations must have the same type.  Property 'localeMatcher' must be of type 'string | undefined', but here has type '"lookup" | "best fit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(311,9): error TS2717: Subsequent property declarations must have the same type.  Property 'formatMatcher' must be of type 'string | undefined', but here has type '"basic" | "best fit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(312,9): error TS2717: Subsequent property declarations must have the same type.  Property 'weekday' must be of type 'string | undefined', but here has type '"long" | "short" | "narrow" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(313,9): error TS2717: Subsequent property declarations must have the same type.  Property 'era' must be of type 'string | undefined', but here has type '"long" | "short" | "narrow" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(314,9): error TS2717: Subsequent property declarations must have the same type.  Property 'year' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(315,9): error TS2717: Subsequent property declarations must have the same type.  Property 'month' must be of type 'string | undefined', but here has type '"long" | "short" | "narrow" | "numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(316,9): error TS2717: Subsequent property declarations must have the same type.  Property 'day' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(317,9): error TS2717: Subsequent property declarations must have the same type.  Property 'hour' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(318,9): error TS2717: Subsequent property declarations must have the same type.  Property 'minute' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(319,9): error TS2717: Subsequent property declarations must have the same type.  Property 'second' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(321,9): error TS2717: Subsequent property declarations must have the same type.  Property 'timeZoneName' must be of type 'string | undefined', but here has type '"long" | "short" | undefined'.
```

### 🙂 Expected behavior

No errors

**Comment by saschanaz** [comment]
@batisteo Do you mind to fix it? I think some of your changes should go `es5.d.ts` instead.

**Comment by batisteo** [comment]
Right, i'll have a look.
