### ISSUE TITLE
Assertion function & Type guards for Record types broken on 5.0 

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript#53379]
### 🔎 Search Terms
* asserts
* assertion function
* type guard
* record

### 🕗 Version & Regression Information

Worked on 4.9, broken since 5.0 

Probably introduced by #52984

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=5.0.2#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXywGcB5AIwCtwMAKHALnjQGtUcB3VASgZwMPgBK4HDGAAeQhhhZUAcwA08KKgCeAPgBQG0JFgIU6bHiWFCIGBjKVMtBs1YduJsxf68ig4aIlSZCpapq8PBaECAY8ABuUBDIIAwA3gC+8AC88KjIEBAAhADcGliI1ERWVNTRsSCcnPAJGsHBlXEAdMoqGAAWfvAA9L3w5jAi8IQyYAgArC0ADC0ATBpJWlCm5pYU5c3VWtttql09-YMwwzCj41OzC0A)

### 💻 Code

```ts
declare function isObject(o: unknown): o is Record<string, any>

declare function assertObject(o: unknown): asserts o is Record<string, any>  

let value: {} = null!;
if(isObject(value)) {
    value.anything // error since 5.0.2
}

assertObject(value)

value.anything // error since 5.0.2
```

### 🙁 Actual behavior

`Property 'anything' does not exist on type '{}'.(2339)`

### 🙂 Expected behavior

No error, narrowing / assertion should work fine.

**Comment by ahejlsberg** [comment]
Hmm, looks like the strict subtype relation considers `{}` and `Record<string, any>` to be mutual subtypes. That's an oversight and apparently we don't have test coverage for that combination. It should be the case that `{}` is a strict supertype of `Record<string, any>`, similar to `{}` being a strict supertype of `Record<string, unknown>`.
