### ISSUE TITLE
Using void in generic overloads (changed between 1.0.3 and 1.1)

### ISSUE THREAD

**Issue by poelstra** [microsoft/TypeScript#939]
The following code used to work in TS <= 1.0.3, but stopped working in TS 1.1.

``` ts
interface Promise<T> {
    /* ... */
}

interface Deferred<T> {
    resolve: (value: T) => void;
    reject: (error: Error) => void;
    promise: Promise<T>;
}

interface VoidDeferred extends Deferred<void> {
    resolve: (value?: void) => void;
}

function makeDeferred<T extends void>(): VoidDeferred;
function makeDeferred<T>(): Deferred<T>;
function makeDeferred<T>(): Deferred<T> {
    // Dummy code
    return {
        resolve: function () { },
        reject: function () { },
        promise: null
    };
}

var normalDeferred = makeDeferred<number>(); // this is line 26
normalDeferred.resolve(3);

var voidDeferred = makeDeferred<void>();
voidDeferred.resolve(); // Note: no need to pass an 'undefined' value
```

The idea is that the `T extends void` overload of `makeDeferred()` returns a VoidDeferred, on which I can call `resolve()` without an argument. For non-void Deferred's, I _do_ have to pass an argument to `resolve()`.

When running it against the latest master, I get the following:

```
$ node ../TypeScript/built/local/tsc.js -m commonjs promise.ts
promise.ts(26,35): error TS2344: Type 'number' does not satisfy the constraint 'void'.
promise.ts(27,24): error TS2345: Argument of type 'number' is not assignable to parameter of type 'void'.
```

Apparently, it's trying to match 'number' to the 'void' type, which fails, but it doesn't try to use the more generic overload that follows (as it did in 1.0.3).
Changing the order of the overloads doesn't help, as the returned type then becomes a 'normal' Deferred<void> (not a VoidDeferred), which requires passing an argument to resolve(), e.g. `resolve(undefined)`.

Is there a better way of doing this?
Ideally even without having that VoidDeferred type?
I'm thinking of something like a 'specialization' of the interface just when T happens to be void, or maybe even that the compiler allows ommitting the argument if its type is void?

**Comment by fredgalvao** [comment]
What if the `makeDeferred` is actually a constructor? Type parameters are not allowed on constructors, so it doesn't work that easy...

The scenario is the Promise implementation (from [lib.es6.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts), but other 3rd party definitions have the same issue):

```typescript
interface PromiseConstructor {
	new <T>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
}
```

With that, 
```typescript
//we can have a Promise<void> and use it properly, because the value on resolve is optional:
new Promise<void>((resolve, reject)=> {
	resolve();
});

//but now we can't guarantee types on any other promise
new Promise<string>((resolve, reject) => {
	resolve(); // this doesn't even generate warnings, and I guess it should
}).then((expectedToBeString) => {
	expectedToBeString === void 0
});
```

Some libraries' definitions, like [bluebird.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/bluebird/bluebird.d.ts), make the value on resolve mandatory, so that it can enforce type on properly typed promises like this:
```typescript
declare class Promise<R> implements Promise.Thenable<R>, Promise.Inspection<R> {
	constructor(callback: (resolve: (thenableOrResult: R | Promise.Thenable<R>) => void, reject: (error: any) => void) => void);
}

//Expected
new Promise<string>((resolve, reject) => {
	resolve(); // [ERROR] Supplied parameters do not match any signature of call target.
});

//Not expected, we can't work with void Promises.
new Promise<void>((resolve, reject) => {
	resolve(); // [ERROR] Supplied parameters do not match any signature of call target.
});
```

With the current restrictions on constructor customization, I don't see how to work this out. Is there anything in works on the `void` type that could solve this? Is there any other way to define/overload this case without making it too loose?

Any guidance is welcome!
