### ISSUE TITLE
Need to reference typings files explicitly after upgrade to 1.7.5 from 1.7.3

### ISSUE THREAD

**Issue by zdychacek** [Microsoft/TypeScript#6183]
Hi,

after upgrading to the newest version of TS (1.7.5), I have to specify references to typings files explicitly.

In previous versions there wasn't need to do this. Both Visual Studio Code and Sublime text IDEs were able to infer typings automagically.

Now I need to specify reference to typings index `/// <reference path="../../../typings/tsd.d.ts" />` in each file explicitly.

The interesting part of this problem is, that only IDE is complaining that `Cannot find module ...`, however code is transpiled without `tsc` complaining.

So I don't know if this issue is related to TS compiler or some IDE TS intellisence server.

I don't like this new behavior and I'd like to know the motivation behind this new behavior in the newest release?

My `tsconfig.json`:

```
{
    "compilerOptions": {
        "noImplicitAny": true,
        "target": "es6",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitOnError": true,
        "moduleResolution": "node",
        "module": "commonjs"
    },
    "filesGlob": [
        "**/*.ts",
        "../typings/tsd.d.ts",
        "!node_modules/**/*"
    ],
   "files": [...]
}
```

Thanks for your answer,

O.

**Comment by mhegazy** [comment]
Is this still an issue. if so we will need more information to be able to help. a sample project showing the problem will be ideal.
