### ISSUE TITLE
Default values don't widen types of destructed values in function parameters (regression)

### ISSUE THREAD

**Issue by falsandtru** [Microsoft/TypeScript#29189]
**TypeScript Version:**  3.3.0-dev.20181228

**Search Terms:**

**Code**

```ts
declare function f(g: (as: string[]) => void): void
f(([_1, _2 = undefined]) => undefined)
```

**Expected behavior:**

pass

**Actual behavior:**

Error at `_2`:

```
Error TS2322: Type 'undefined' is not assignable to type 'string'.
```
**Playground Link:** 

**Related Issues:**

**Comment by ahejlsberg** [comment]
This regression is caused by #28967.
