### ISSUE TITLE
Duplicate identifiers on windows

### ISSUE THREAD

**Issue by otbe** [Microsoft/TypeScript#9049]
Hi,

Im getting a lot of `Duplicate Identifiers` errors on [windows builds](https://ci.appveyor.com/project/otbe/dwatch/build/0.4.56) for my current project. This does not happen on [OS X](https://travis-ci.org/Mercateo/dwatch/jobs/136357578) or [linux](https://travis-ci.org/Mercateo/dwatch/jobs/136357577). There are also no such errors on my local environment (OS X) with fresh new `node_modules`.

Whats wrong with windows? :)

Im using typescript@next (typescript@1.9.0-dev.20160609-1.0). Project is at https://github.com/Mercateo/dwatch

**Comment by unional** [comment]
In your `tsconfig.json`, you need to add this:

```js
{
  "exclude": [
    "typings/globals",
    "typings/modules"
    ...
  ]
}
```

**Comment by otbe** [comment]
@unional thanks for answering! But build is still [broken](https://ci.appveyor.com/project/otbe/dwatch/build/0.4.58)
I wonder why it works on OS X/Linux and is broken on windows. Besides errors from ```typings/``` there are also errors from ```node_modules/```, which are excluded too...

**Comment by unional** [comment]
Sorry, nevermind. The `exclude` is not needed.

**Comment by GrayChoi** [comment]
@otbe 
My project has same problem.
Did you resolve it?

**Comment by mhegazy** [comment]
Can you share the tsconfig? When did this start happening? What is the version of node?

**Comment by unional** [comment]
I think that's his tsconfig.json:
https://github.com/Mercateo/dwatch/blob/master/tsconfig.json

Since it is using `github-electron`, maybe he needs to specify `nolib`?

**Comment by yortus** [comment]
Which node versions does this occur on? Node v6 changed some casing behaviour around drive letters (hence only affects windows, not OSX/linux) that can impact typescript projects. If compiling works with node v4/5 but not with v6, it may be related. See #8837.

**Comment by otbe** [comment]
@mhegazy @unional yes this is my tsconfig https://github.com/Mercateo/dwatch/blob/master/tsconfig.json

@GrayChoi no :(

@yortus all ci build environments are using node 5 (I guess 5.1) and locally Im using node 6.2.1. 

I think it starts when upgrading typescript 1.8.10 to typescript@next. Unfortunately I need a nightly because of the broken async/await type inferring thing in 1.8.10.

**Comment by mhegazy** [comment]
I do not see how this used to work with TS 1.8.* or on OSX anyways. but excluding the duplicate types from typings, resolved most of the issues, then that left me with one error of not found module for `inversify`. adding a path mapping to it, gets the compilation working clean. here is the tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "jsx": "react",
    "baseUrl":  ".",
    "paths": { "inversify": [ "node_modules/inversify-dts/inversify/inversify.d.ts" ] }
    // "noImplicitAny": true
  },
  "exclude": [
    "node_modules",
    "app/node_modules",
    "dist",
    "coverage",
    "generated",
    "assets",
    "typings/main",
    "typings/main.d.ts",
    "typings/browser",
    "typings/browser.d.ts"
  ]
}
```

**Comment by otbe** [comment]
@mhegazy 
inversify is referenced in ```index.ts``` by ```///``` (see https://github.com/otbe/dwatch/blob/update-notification/app/src/index.tsx#L1) and there are no folders ```typings/main``` or ```typings/browser``` anymore in typings 1.0. So don't know whats went wrong on your installation.

**Comment by unional** [comment]
```js
    "typings/main",
    "typings/main.d.ts",
    "typings/browser",
    "typings/browser.d.ts"
```
is not needed as he is using `typings@1.*`, it does not have those files anymore.

**Comment by otbe** [comment]
Downgraded to typescript 1.8.10 and it works again -> https://ci.appveyor.com/project/otbe/dwatch
So typescript@next is somehow broken on windows...

**Comment by mhegazy** [comment]
my bad. still i am not getting it to build on TS 1.8.10.

```txt
c:\test\9049\dwatch>tsc --v
Version 1.8.10

c:\test\9049\dwatch>typings --v
1.0.4

c:\test\9049\dwatch>type tsconfig.json
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "jsx": "react"
    // "noImplicitAny": true
  },
  "exclude": [
    "node_modules",
    "app/node_modules",
    "dist",
    "coverage",
    "generated",
    "assets"
  ]
}

c:\test\9049\dwatch>tsc
app/src/utils/IOC.ts(1,63): error TS2307: Cannot find module 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(17,36): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(25,36): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(37,54): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(38,53): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(41,41): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(43,50): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(44,44): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(46,56): error TS2503: Cannot find namespace 'inversify'.
node_modules/inversify-dts/inversify-binding-decorators/inversify-binding-decorators.d.ts(47,44): error TS2503: Cannot find namespace 'inversify'.

```

**Comment by otbe** [comment]
@mhegazy are you on branch "update-notification" of https://github.com/otbe/dwatch?
inversify should be referenced in ```app/src/index.ts```

**Comment by mhegazy** [comment]
no i was on master. sorry about that.. but i can not reproduce any issues on windows.

```txt
c:\test\9049\dwatch2>git status
On branch update-notification
Your branch is up-to-date with 'origin/update-notification'.
nothing to commit, working directory clean

c:\test\9049\dwatch2>tsc --v
Version 1.9.0-dev.20160610-1.0

c:\test\9049\dwatch2>tsc

c:\test\9049\dwatch2>echo %ERRORLEVEL%
0
```

**Comment by otbe** [comment]
@mhegazy 
Mh curious. Which node version?
Using node 5.11.0 on windows builds.

**Comment by mhegazy** [comment]
node 6.2.0, windows 10.

**Comment by otbe** [comment]
Mh build fails with node 6.2.1 :(
https://ci.appveyor.com/project/otbe/dwatch/build/0.4.62

**Comment by mhegazy** [comment]
@otbe if this is still an issue, can you please share a minimal repro project?
