### ISSUE TITLE
Duplicate identifier error for d.ts files in Visual Studio 2017

### ISSUE THREAD

**Issue by odrozd** [microsoft/TypeScript#14565]
**TypeScript Language Version:**  2.2
**Visual Studio Typescript tooling Version** 2.1.5

I am having trouble with typescript errors like TS2300: duplicate identifier 'export=' and TS2374: Duplicate string index signature. This errors appear in error window, but projects builds successful. This errors appear only with VS2017. 

### Env Details:
1. Type definitions are installed via nuget to default folder: project root/scripts/typings/

2. For **build** I use nuget package Microsoft.TypeScript.MSBuild" version="2.2.1

3. tsconfig is NOT used**, instead here are setting from csproj:
```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <TypeScriptTarget>ES5</TypeScriptTarget>
    <TypeScriptJSXEmit>None</TypeScriptJSXEmit>
    <TypeScriptCompileOnSaveEnabled>True</TypeScriptCompileOnSaveEnabled>
    <TypeScriptNoImplicitAny>False</TypeScriptNoImplicitAny>
    <TypeScriptModuleKind>AMD</TypeScriptModuleKind>
    <TypeScriptRemoveComments>False</TypeScriptRemoveComments>
    <TypeScriptOutFile>
    </TypeScriptOutFile>
    <TypeScriptOutDir />
    <TypeScriptGeneratesDeclarations>False</TypeScriptGeneratesDeclarations>
    <TypeScriptNoEmitOnError>True</TypeScriptNoEmitOnError>
    <TypeScriptSourceMap>True</TypeScriptSourceMap>
    <TypeScriptMapRoot />
    <TypeScriptSourceRoot />
    <TypeScriptStrictNullChecks>false</TypeScriptStrictNullChecks>
    <TypeScriptNoFallthroughCasesInSwitch>true</TypeScriptNoFallthroughCasesInSwitch>
    <TypeScriptLib>dom,es5,es2015.promise</TypeScriptLib>
  </PropertyGroup>
```

I assume I see this errors because VS2017 somehow downloaded @types to this folder: ~\AppData\Local\Microsoft\TypeScript\node_modules\@types\ and there is conflict between this types definitions and those types installed via nuget, if this is the cause I am not sure how disable this feature in VS2017 and honor only nuget installed d.ts?

I would appreciate any help to this issue.

Here is screenshot:
![vs2017_typescript_error](https://cloud.githubusercontent.com/assets/16099116/23770993/fd63fdd6-051d-11e7-915d-b5f852855584.jpg)

**Comment by mhegazy** [comment]
Can you share your project file? or steps to reproduce this behavior?

**Comment by odrozd** [comment]
I can share stripped proj file with only typescript related information, not sure if it helps. 
[IssueVS2017csproj.zip](https://github.com/Microsoft/TypeScript/files/832431/IssueVS2017csproj.zip)

Regarding steps to reproduce, there isn't I just open VS and in 20-30 seconds I start see this errors in error window, please note project builds successful, VS point to this errors in d.ts files. Also my team-members also have this issue with vs2017.

Another screenshot:
![vs2017_typescript_error2](https://cloud.githubusercontent.com/assets/16099116/23773623/bfadc9b2-0528-11e7-9c6d-e882b33cffaa.jpg)

Also I will try to create project from scratch with similar settings and check if this issue exist.

**Comment by Serivy** [comment]
I was just about to add a new issue but I believe this is the same issue I am having. I have managed to replicate it in a simple project (our production project is much more complicated and uses nuget but still suffers from the issue). 

To reproduce:
1) git clone https://github.com/Serivy/TS5055.git
2) Open TS5055.sln with visual studio 2017.
3) Compile the project (so that the artefact file1.d.ts is created)
4) Close visual studio 2017
5) Open TS5055.sln with visual studio 2017 and open the Error List.
6) Wait 40 seconds.
7) The errors should pop up.
![ts5055](https://cloud.githubusercontent.com/assets/9199253/23784293/1143af1c-059c-11e7-830e-fca38da4711c.jpg)

I have used each RC build of VS2017 and i can say it was fine until the very last RC (which i think was using the TS2.2 plugin) which i was hoping would be fixed in the release but can confirm i get it in the release as well. This is only for design time as compile time is always correct.

My speculation is that visual studio plugin is sourcing it's own list of files to run through the language service which includes definition files it generates. I have also had it pull .d.ts files from the gulp-typescript package inside a node_modules folder which was listed as exclude in the tsconfig.json.

Any more information required let me know as I have a few cases where this is an issue.

**Comment by stewart-r** [comment]
Affected by this too - Agree with @Serivy that it seems to be VS sourcing definition files that conflict with ones already in the solution. 

Searching for (find in files) one the duplicate identifiers in my solution throws up the same identifier in the typings inside the solution AND one from ...appdata/Local/Microsoft/Typescript/node_modules/@types/...

**Comment by odrozd** [comment]
I am also can replicate this issue from scratch:
1. Add new MVC5 project,
2.  Add any ts file
3.  Install jQuery typing via nuget 
4.  open тгпуе installed jquery.d.ts file in VS editor or wait 20-30 second

Also if I am manually delete typings from folder: "~\AppData\Local\Microsoft\TypeScript\node_modules\@types\" errors disappear after several seconds, but when reopen VS this folder populated again causing this errors to appear again.

**Comment by UsherNet** [comment]
Same problem has existed with VS2017 since RC.  It would be good to a) understand it, b) make it go away!

**Comment by ArtemAvramenko** [comment]
Steps to reproduce:

1. Create ASP.NET Web Application (C#)
2. Choose MVC template
3. Install-Package jquery.TypeScript.DefinitelyTyped
4. Open jquery.d.ts

![error](https://cloud.githubusercontent.com/assets/11413326/23853938/a8307a6a-07f7-11e7-87d4-aa69c4a81bb9.png)

**Comment by jurion** [comment]
Same problem with WebForms project.
![image](https://cloud.githubusercontent.com/assets/5483208/23862701/1a47cd9c-07e4-11e7-8fba-bd639d5b661f.png)

**Comment by ArtemAvramenko** [comment]
Another error: Duplicate string index signature
![duplicate_string_index](https://cloud.githubusercontent.com/assets/11413326/23899842/6f506bf6-08bf-11e7-9097-1354e8f4d4c4.png)
"

**Comment by LbISS** [comment]
The same problem. Just opened solution which worked fine on VS2015 with new VS2017 - can't build, errors:
 All declarations of 'iterator' must have identical modifiers.
Duplicate string index signature

**Comment by KunleSmart** [comment]
I have same problem as indicated by @LbISS. This also include Error	TS2300	Duplicate identifier 'ng'.

**Comment by intoxopox** [comment]
Also triggered by cleaning and rebuilding the solution.

**Comment by styfle** [comment]
@mhegazy Thanks for the quick fix!
Is there a workaround while we are waiting for the fix to be released?

**Comment by odrozd** [comment]
@mhegazy Could you please clarify that this fix will be available with Visual Studio 2017 Update 1?

**Comment by wdunn001** [comment]
So I hope this helps I was also afflicted by this. I had to remove typings from scripts in my package.json then delete the typings folder from 

  "scripts": {
    "postinstall": "typings install",
    "typings": "typings"
  }

and remove any typings or @types folder from node_module. This can also be cause by having typings installed locally and globally.

**Comment by MattFromGer** [comment]
I upgraded to 15.1 (26403.0) today and I still get the errors...

**Comment by intoxopox** [comment]
Still happens in 26403.3 as well.

**Comment by jjoekoullas** [comment]
Quick and dirty hack to get around this while waiting for a proper fix:

1. Comment out all of the devDependencies in `%localappdata%\Microsoft\TypeScript\package.json`.
Mine currently looks like:
```
{
  //"devDependencies": {
  //  "@types/angular": "^1.6.14",
  //  "@types/angular-strap": "^2.2.31",
  //  "@types/angular-ui-router": "^1.1.36",
  //  "@types/bootstrap": "^3.3.32",
  //  "@types/clipboard": "^1.5.33",
  //  "@types/handlebars": "^4.0.32",
  //  "@types/jquery": "^2.0.41"
  //}
}
```

2. Delete all the folders in `%localappdata%\Microsoft\TypeScript\node_modules\@types`

After a VS restart, clean, rebuild everything is back to normal (for me at least).

**Comment by odrozd** [comment]
@jjoekoullas I tried this approach, but it appears that after some time or after VS restart, some background process bring back this dependencies to package.json and typings get downloaded again which causes errors to appear again (this was my case)

I am still wondering based on which rules or settings, concrete dev dependencies appear in package.json file, e.g. how typescript know which dependencies I need...

**Comment by jjoekoullas** [comment]
@odrozd sorry, forgot to mention to make `%localappdata%\Microsoft\TypeScript\package.json` read-only

**Comment by odrozd** [comment]
@jjoekoullas  you make my day)) I'll try it asap

**Comment by DsanchezPerez** [comment]
It seems these are not solutions but work arounds and hacks.  I found that turning off the Type Script compiler in the VS Solution files is good also but Microsoft should be fixing this issue to be honest.

**Comment by intoxopox** [comment]
Though improved, Still happens in 26403.7 after re-compile.

**Comment by mahmoudelgawad** [comment]
the same, still errors exists
![image](https://cloud.githubusercontent.com/assets/27723764/25122109/141c17e6-2424-11e7-9d02-daa686c7acb1.png)

**Comment by odrozd** [comment]
Guys, I am pretty sure that they will address this issue in scope of update typescript plugin for VS 2017, current plugin support only TypeScript 2.1 and they work to bring new version [here](https://github.com/Microsoft/TypeScript/issues/14529) 

Anyway it would be great to get confirmation or other update regarding current issue state from TS team members.

**Comment by billti** [comment]
The latest VS Preview (https://www.visualstudio.com/en-us/news/releasenotes/vs2017-Preview-relnotes#15.2.26412.01) includes SxS support for TypeScript versions, and should fix most of the above issues also. By end of week (or early next week) the Preview will be updated again to (hopefully) address all the issues outlined above.

There were a couple of factors impacting VS here. One was the issue @mhegazy fixed above around semantic errors in JS files, and another just recently discovered that @zhengbli fixed with #15080 where the project structure was getting confused. Apologies for the pain & frustration these have caused.

**Comment by AndreR** [comment]
Even with the preview, I still get those errors.

**Comment by boomtopper** [comment]
I have found adding a typescript config file to the root of my project fixes Duplicate Identifiers found in the nuget jquery typings and the typings that is buried somewhere in  my home folder.

**Comment by billti** [comment]
If you can share a repro @AndreR we can look into it. Do you have TypeScript source files in your project, or just JavaScript?

**Comment by AndreR** [comment]
@billti Unfortunately it's an internal project, so I can't share it unfortunately. I get exactly 684 errors, all duplicate identifiers. The errors appear in various places, mostly the d.ts files. For example:

- cldr.js-event.d.ts:23 (export=)
- devexpress-web.d.ts (hundreds of errors)
- jquery.d.ts (export= again)

There is also this strange thing, that it tries to access C:/MyProjectFolder/packages/globalize.TypeScript.DefinitelyTyped.0.3.1/Content/Scripts/typings/cldr.js/cldr.js.d.ts, which doesn't even exist. I don't know, why it tries to load it.

I have a tsconfig.json in my root folder:

`{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": true,
    "noEmitOnError": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es2015"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}`

**Comment by billti** [comment]
Thanks for the info @AndreR . It sounds like possibly a different issue than those above, which were largely due to errors from JavaScript files or projects getting recalculated randomly - both of which should be fixed in the preview.

What added the "packages" folder to your project? Is this a NuGet install location?

Are you seeing the same errors from build on the command line? If so, you could try the `--traceResolution` flag to see if that shows you what is sucking in the unexpected file.

If this still look like a bug in TypeScript, could you open a new issue for it with a summary of the info to date? Thanks.

**Comment by AndreR** [comment]
@billti I can't reproduce the error right now. I somehow must have found a workaround for it, but I can't tell you exactly what I did.

The packages folder was indeed added by NuGet. Unfortunately, I haven't checked the command line build back then.

If this error should appear again, I will tell you.

**Comment by nh43de** [comment]
This happened after doing a web deploy. Seemed the language service was including some of the temporary deployment code in the obj\ directory (specifically, "obj\Release\net461\win7-x86\PubTmp\Out\wwwroot").

Just want to note that doing a clean does not seem to clean these temporary files.

**Comment by Antonariy** [comment]
This happened during build too. I'm developing core mvc app keeping some scripts  in Views directory, and they are copied to output directory with corresponding property being set) after build. So they stay in Debug and Release folders. 

This problem can be solved by setting output in project settings outside project directory or by calling rmdir command after build event. But not publishing problem, which includes ts files in any directory. PubTmp creates after rmdir and it is always in obj\ .

Laguage service is scanning whole project folder for .ts files. It should ignore output folders for each configuration and "obj" folder. Or it should scan only ProjectItems in IDE, ignoring files that are not included in project tree.

**Comment by deanpodgornik** [comment]
Today I had the same problem. Solution: Updating VS to 15.2 (26430.6)

**Comment by Antonariy** [comment]
**deanpodgornik**

I have the save version. And i have found solution for PubTmp: https://github.com/dotnet/sdk/issues/980

**Comment by jurion** [comment]
Same, solved to VS to 15.2 (26430.6) solved my problem

**Comment by mahmoudelgawad** [comment]
Still typescript Errors Version 15.2 (26430.12) visual studio 2017
Duplicate identifiers

**Comment by Jehoel** [comment]
I still get this issue after updating to 15.2.

In ASP.NET Web Application projects I'm able to avoid this issue by downgrading the project TypeScript version from 2.2 to 2.1, however in Website projects (that don't use a `.csproj` file, but use `.sln` directly) there is no way to specify a TypeScript version so I cannot work-around this issue.

**Comment by mhegazy** [comment]
can you share a project or some repro steps?

**Comment by Manojb86** [comment]
I resolved this issue following below steps,
1. Go to "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\TypeScript\Microsoft.TypeScript.targets", 
Please look for TypeScriptCompileBlocked being defined as FALSE inside of the <PropertyGroup>. 
2. IF it's defined as false, go back to .csproj file and add the following section,
<PropertyGroup>
  <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
</PropertyGroup>

Build the project again.

**Comment by styfle** [comment]
@Manojb86 Doesn't that mean that Visual Studio won't compile your TS files?
At least thats what the [docs](http://www.typescriptlang.org/docs/handbook/compiler-options-in-msbuild.html#typescriptcompileblocked) seem to say.

**Comment by robertmclaws** [comment]
@mhegazy Please reopen this issue, it is still a problem.

**Comment by geirsagberg** [comment]
I acquired this problem today after upgrading to VS2017 15.3 Preview 3.

**Comment by AndreR** [comment]
Yes, the problem definitely still occurs in the most recent versions.

**Comment by billti** [comment]
@AndreR - your prior update on this issue stated:

> I can't reproduce the error right now. I somehow must have found a workaround for it, but I can't tell you exactly what I did

So did this recur for you? Is it still intermittent, or do you have a consistent repro? Do you have something you can share with us to try and recreate? (Same questions to you @geirsagberg ).

Are you seeing these errors in TypeScript or JavaScript files? What version of TypeScript is being used (this is configurable in Tools / Options)?

Unfortunately there is a large number of possible configurations and settings, and this is also a perfectly legitimate and valid error in many projects which can be hard to troubleshoot. Without detailed info and preferably a repro, this is going to be hard to figure out. If it is occurring when it shouldn't, then it must be something quite specific to your setup (I'm using 15.3 daily, and I've never seen it when it wasn't a valid error).

**Comment by ttutko** [comment]
I believe we are seeing the same thing on 15.3 RTM. Unfortunately I am not allowed to share our project but since upgrading to 15.3, with no code changes, I get the following:
Build: Duplicate identifier 'Transport' (in file lib.d.ts)
Build:Property 'name' does not exist on type 'Transport'. (in file communication.ts <-- this is our code)
Build:Duplicate identifier 'Transport'. (in file signalr.d.ts)

If I then open any of those files by double-clicking the entry in the error window, a duplicate error message shows up only this time it has the "Code" column of the error list filled in with either TS2339 or TS2300)

**Comment by sk29110** [comment]
I am using visual studio 2015 1.0.0-preview2-003131 but I am getting 
Build:Duplicate identifier 'export='
Build:Duplicate number index signature

**Comment by Andrey-Anatolyevich** [comment]
I had the same problem. Here is what I've fixed it with:
First, I've removed compiled .js and .js.map files from the project.
Then, I've installed TS 2.5 SDK, and set "<TypeScriptToolsVersion>2.5</TypeScriptToolsVersion>" in .csproj file.
After reloading the project, I didn't have the error ever again.
I'm not sure which step solved the issue, but I believe it may be helpful to somebody.

**Comment by david-grogan** [comment]
I'm still experiencing this too, I thought the @Andrey-Anatolyevich solution fixed it for a bit, but then it came back again. Also tried the @jjoekoullas fix, but that didn't help.

I'm getting either 181 or 362 errors, mostly "duplicate identifier" errors from index.d.ts and jquery.d.ts, plus a few other library typings; and a handful of other error types as well.

I'm using VS 2017 15.3.3, TS 2.5, and have updated all my typings to the latest versions.

The errors disappear when I restart VS (cleaning the solution does nothing), not sure what triggers their reappearance, but it doesn't appear to have anything to do with building or debugging the app, nor saving any changes to a TS file to trigger a recompilation; the errors just show up after about 5-10 mins (even if I open the solution and just leave it sitting there, doing absolutely nothing).

**Comment by mhegazy** [comment]
@david-grogan can you report this issue through ["Report a problem" tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017 ), this will allow us to capture some additional information to be able to debug the issue.

Also CC @billti and @amcasey

**Comment by david-grogan** [comment]
done.

**Comment by david-grogan** [comment]
After installing VS 2016 15.3.4 this issue seems to have gone away.

**Comment by david-grogan** [comment]
I spoke too soon, after using it for three days without the errors appearing they just came back again.  ¯\_(ツ)_/¯

**Comment by jeroenlandheer** [comment]
Still having the same issues with VS2017 15.4.1

**Comment by mhegazy** [comment]
@jeroenlandheer and @david-grogan can you share a repro project?

**Comment by billti** [comment]
Are those affected all NOT using tsconfig.json (i.e. all your build settings are in the MSBuild properties in the VS project file)? I have noticed that on occassion the project context we create for such project (which we call "external" projects), will automatically also include all the type definitions under the types cache location (which the workaround linked to effectively disables). 

If you could confirm (and even better, if you switch to using a tsconfig.json does the issue go away), that would be very helpful.

**Comment by david-grogan** [comment]
I got the problem with or without a .tsconfig (generally I don't use one).

@mhegazy I can't share the project I'm working on, and don't really have too much time to try and create a new repro project.

**Comment by jeroenlandheer** [comment]
@david-grogan Sorry, but this is an internal project, I can't share it. 

- I'm not using a tsconfig, 
- the duplicates come from the typings libraries, one of the two is in the nuget packages folder, the other in the scripts/typings folder of my web project. 
- It's an ASP.Net MVC NetFramework project.
- Typescript tools version 2.3

Some packages that cause this:
- knockout.TypeScript.DefinitelyTyped
- jQuery.TypeScript.DefinitelyTyped
- moment.TypeScript.DefinitelyTyped
- etc. 

Hope this helps

**Comment by tasosss** [comment]
@mhegazy do you want me to send you my project(in private)?

**Comment by billti** [comment]
@jeroenlandheer So you do have two copies of each .d.ts in the project? One from NuGet and one in scripts/typings? Is there a reason you need both included?

**Comment by Matti-Koopa** [comment]
For me it helped to select the project in the Solution Explorer, then go to the menu option PROJECT and click "Convert to Web Application".

**Comment by jeroenlandheer** [comment]
@billti If you install a nuget package, you get 2 copies. One is in the "packages" folder of your solution where the nuget package is extracted, the other is in the "Scripts/typings" directory of your web project. 

I'm using now npm to get around this and use tsconfig & gulp to compile my typescript. I've disabled typescript compiler in the project.

**Comment by davewilton** [comment]
I was getting this error when using dojo-typings installed via npm. Because these don't installed into the @types folder I referenced them manually in the "Include" of tsconfig. For some reason this causes all of the duplicate errors.

Instead I went back to my old way of creating a tsc.d.ts in the project root which includes the references:
```
tsc.d.ts
/// <reference path="node_modules/dojo-typings/dojo/1.11/dojo.d.ts" />
/// <reference path="node_modules/dojo-typings/dojo/1.11/modules.d.ts" />
/// <reference path="node_modules/dojo-typings/dojox/1.11/dojox.d.ts" />
/// <reference path="node_modules/dojo-typings/dijit/1.11/dijit.d.ts" />
/// <reference path="node_modules/dojo-typings/dojox/1.11/modules.d.ts" />

```

**Comment by ArtemAvramenko** [comment]
Still reproduced in 15.4.4 when jasmine.d.ts is installed.

**Comment by ManuelHaas** [comment]
Reproduced with 15.4.4 and knockout (`npm install --save @types/knockout`) with TS 2.3 and TS 2.6.1

Why is this bug closed btw?

**Comment by ManuelHaas** [comment]
What works for me was deleting the folder 

> C:\Users\[Username]\AppData\Local\Microsoft\TypeScript

Don't know if this has side effects - currently it seems to work

**Comment by ManuelHaas** [comment]
@mhegazy @billti  I create a project with which the bug can be reproduced. How can I sent it to you?

**Comment by milax** [comment]
It is not fixed, please reopen the bug

**Comment by billti** [comment]
@ManuelHaas If you can send it to billti at microsoft dot com, then I'll take a look.
Reopening while investigating....

**Comment by ManuelHaas** [comment]
@billti you have mail ;)

**Comment by billti** [comment]
Thanks @ManuelHaas . I got the project and can see the problem.

In your case it's because the knockout definitions are indeed included twice. Here's why.

In your solution folder (one up from the project) you have a `node_modules` folder containing the `@types\knockout` package. So when your project opens and the TypeScript project is created, and it sees the `import * as ko from "knockout";` in the source file, it walks up looking for a `node_modules\@types\knockout` folder, sees this, and includes the knockout definitions.

However in the `tsconfig.json` for your project you also have `"typeAcquisition": {"enable": true}`, which means it will go fetch the type definitions for the libraries it detects in use and include them. It sees knockout being used, so it goes fetches the knockout library into the cache. Thus, two distinct copies of the knockout definitions are included, leading to `duplicate...` errors.

There are a few ways you can fix this:

1. Delete the `@types\knockout` NPM package you have in your solution - but I'm guessing the TypeScript project uses this.
2. In your `"typeAcquisition"` settings, add the entry `"exclude": ["knockout"]` - this way it won't go automatically acquire this package again.

Arguably we should also not go fetch & include a type definition for a package we already are including from under one of the type root (CC @RyanCavanaugh ).

**Comment by RyanCavanaugh** [comment]
> Arguably we should also not go fetch & include a type definition for a package we already are including from under one of the type root

Agreed. The code already *should* work this way - only ATA `knockout` when it shows up in the `unresolvedImports` list; but `knockout` *was* resolved so it shouldn't be in that list. I'll debug and figure out why that's happening.

**Comment by ManuelHaas** [comment]
@billti: Excluding knockout from typeAcquisition worked for me. Thanks a lot!

**Comment by david-grogan** [comment]
I disabled the @jjoekoullas workaround and disabled typeAcquisition via a .tsconfig and it seems to have fixed the problem for me also (crossing my fingers, the timing on this bug wasn't predictable).

You should also probably add the typeAcquisition option to the project properties (and a default setting to the VS options), for those of us not using a tsconfig.json (not a fan of the profusion of javascript config files, gulp, etc., I just want a single project file). 

I don't want VS to be doing stuff like this in the background for me, if I want a reference I'll add it manually.

**Comment by rezelute** [comment]
The error (Duplicate identifier export=) was happening to me randomly and I was managing to get around it by simply re-installing the typing using Nuget Package Manager. Today however, I have installed the latest version of visual studio and this workout no longer applies. There seems to be a conflict between "Scripts/typings/jquery/jquery.d.ts" and "packages/jquery.TypeScript.DefinitelyTyped.3.1.2/Content/Scripts/typings/jquery/jquery.d". Even when i specify in the tsconfig.json the typeRoots to be only [ "Scripts/typings" ], it still doesnt work. 

I tried @jjoekoullas fix however it still happens to me. How did you disable typeAcquisition via a .tsconfig?

My project was a website however I have just tested converting it to an application project and it seems to be working better (because the packages folder lives outside the web directory). However, when you install another typing via NuGet (I was using Mustache) then it complains again about "export=".

**Comment by david-grogan** [comment]
To disable typeAcquisition see @billti's comment above: https://github.com/Microsoft/TypeScript/issues/14565#issuecomment-348328648

**Comment by RyanCavanaugh** [comment]
Fix available; PR pending soon

There are actually two issues here:
 * Due to a bug in how we reused program structure, we were wrongly considering `knockout` to be an unresolved module during cached program rebuilds. PR up soon
 * A *separate* bug is that the NodeJS project system adds `node` to the ATA `include` list even though there may be a local `@types/node` package in the project folder. The workaround is simple; just add `"exclude": ["node"]` to the `typeAcquisition` block in your tsconfig. Logged #20402

**Comment by rezelute** [comment]
But i dont have any node folders in my project, the conflict is happening from the packages folder and the typings one in "Scripts". The strange thing is that it works for a certain period and then when I make changes to some of my TS files, it randomly shows the errors again which means that i can't re-compile (and thus produce my exported JS files).
I have tried the typeAcquisition but still no luck.

Any ideas?

![untitled](https://user-images.githubusercontent.com/13378850/33661607-a1746f5e-da80-11e7-914f-9351df5f9c05.png)

**Comment by billti** [comment]
You should remove the jquery type definition from under your `scripts/typings` folder if it already comes via the NuGet package.

**Comment by JiriZidek** [comment]
@billti: removing nugetted typings breaks TFS build running on buildserver !
Strange is that I solved this by uninstlalling duplicated packages in npm commandline in March, now after installing it reappeared... I'll try use same medicine...

**Comment by rezelute** [comment]
Removing it from typings seems to work fine. The problem is that sometimes the typings folder is coming back for some reason and i have to keep on deleting it. Why is it that when you install the package via nuGet package manager that it installs both the package and the typing?

**Comment by JiriZidek** [comment]
It is necessary tu run npm -D --save --save-dev _package@name_ for each offending typing file.
Tricks:
- you have to run it in scope of %AppData%\....\ where the offending file sits, there is one with version 2.6 and one in upper folder
- by running npm -list you can see what packages npm considers shoudl exist - if you see listed it, it wil download it again, even after you deleted the folder

**Comment by rezelute** [comment]
I dont quite understand. I installed the typing via "nuget package manager for solution" not npm. There is no npm usage in the project. So i am guessing that visual studio has npm running in the background which eventually re-downloads it or something when it notices that it is missing.

**Comment by JiriZidek** [comment]
TS & VS from some version 2.2 implicitly uses node.js infrastructure (so even you did not install it, you have it) and it uses npm packaging by default. It collides with older "nuget only" apporach.

**Comment by tomek14** [comment]
Any updates on this? I don't have Intelisense in .js files becouse of this. My project is using TypeScript and JavaScript files, when I set `typeAcquisition = true` Intelisense in JavaScript files works but in TypeScript i got error of Duplicate Identifier becouse my TypeScript project uses `@types` to build in CI pipeline. Maybe there is some kind of workaround on this ?

**Comment by shelland** [comment]
Is this issue still active? I still have hundreds of build errors for jquery typings (VS 2017 15.5.0, ASP.NET Core 2.0). I'm spending my time fighting with typescript instead of writing my code and i can not continue a work because my JS files are not being generated.

**Comment by shelland** [comment]
![image](https://user-images.githubusercontent.com/426582/36942470-16b45392-1fa5-11e8-8f1c-697f7be0160b.png)

jquery typings were installed using NPM, i didn't user NuGet for this.

**Comment by mhegazy** [comment]
@shelland can u share your project or a sample showing the same behavior?

**Comment by a688** [comment]
I was encountering this extremely annoying error recently and setting "typeAcquisition": {"enable": false} fixed it. I am only using TypeScript to process .ts files with plain es5 code in an MVC5 project. I don't see how this is still an issue a year after this was first reported.

**Comment by tommai78101** [comment]
For me I encountered multiple `Duplicate identifier "DataTransfer"` error messages.

I received this error after I did the following:

- Installed latest Node.js and npm globally on a fresh installation of Windows.
- Installed the following packages globally:
    `babel-eslint`
    `eslint`
    `eslint-config-defaults`
    `eslint-plugin-import`
    `eslint-plugin-react`
- Opened a JavaScript project file (company internal project file, aka, non-open source)

I fixed it (or rather, I suppressed the errors) with the following:

```json
{
	"compilerOptions": {
		"allowJs": true,
		"noEmit": true,
		"lib": ["es6"]
	},
	"compileOnSave": false,
	"exclude": [
		"node_modules",
		"typings",
		"*.d.ts",
		"*.ts"
	],
	"typeAcquisition": {
		"enable": false,
		"exclude": [ "node" ]
	}
}
```

**Comment by ArtemAvramenko** [comment]
The problem is reproduced when I open a project from a directory with junction to another disk (mklink /J command).

**Comment by ArtemAvramenko** [comment]
The problem is reproduced when I open a project from a directory with junction to another disk (mklink /J command). If I create junction from D: to C:,  Visual Studio shows me duplicates in same file:
* C:\MyProject\some.d.ts
* D:\MyProject\some.d.ts

**Comment by alochana9** [comment]
**RESOLVED BY BELOW STEPS**
I got errors related to d.ts and duplicate identifier errors while deploying my application.
I opened containing Folder - properties - removed read only option in the bottom.
Clicked on Apply and OK.
Restarted visual studio , opened solution , clean,build and published again .
And all errors related d.ts  cleared off.
Hope this helps someone.

**Comment by 3x0dv5** [comment]
I found that "untick" the Enable project references helped with "ts2300 duplicate identifier Promise"

![image](https://user-images.githubusercontent.com/250271/57193137-ef460400-6f2f-11e9-89a1-a37d074f0373.png)

**Comment by jurion** [comment]
Resolved for me as well using this tsconfig : 
{
	"typeAcquisition": {
		"enable": false,
		"exclude": ["node"]
	},
    "compilerOptions": {
    },
    "files": [
        
    ]
}

Visual Studio 2019.

**Comment by RyanCavanaugh** [comment]
Closing - please log a fresh bug with concrete repro steps if you encounter this unexpectedly. Thanks!

**Comment by Bosch-Eli-Black** [comment]
I was able to reproduce this with VS2022, so I've created a fresh bug with a minimal repro and steps to reproduce: https://github.com/microsoft/TypeScript/issues/36294 🙂

The root cause seems to be using Yarn 2 or Yarn 3 with a project that has workspaces, as Yarn 2/3 creates hardlinks for the projects in the workspace, and this throws TS for a loop.

Thanks to @ArtemAvramenko's comment (https://github.com/Microsoft/TypeScript/issues/14565#issuecomment-407825854) for pointing me in the right direction! 🙂
