### PR TITLE
Stricter type for ES5 Intl, redefine ES2020 intl

### LINKED ISSUE #42128: lib.es2020.intl.d.ts conflicts with lib.es5.d.ts
# Bug Report

### 🕗 Version & Regression Information

- Regressed by #41880

### ⏯ Playground Link

N/A

### 💻 Code

No code required, build any code with `target: es2020`

### 🙁 Actual behavior

```
node_modules/typescript/lib/lib.es2020.intl.d.ts(307,9): error TS2717: Subsequent property declarations must have the same type.  Property 'localeMatcher' must be of type 'string | undefined', but here has type '"lookup" | "best fit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(311,9): error TS2717: Subsequent property declarations must have the same type.  Property 'formatMatcher' must be of type 'string | undefined', but here has type '"basic" | "best fit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(312,9): error TS2717: Subsequent property declarations must have the same type.  Property 'weekday' must be of type 'string | undefined', but here has type '"long" | "short" | "narrow" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(313,9): error TS2717: Subsequent property declarations must have the same type.  Property 'era' must be of type 'string | undefined', but here has type '"long" | "short" | "narrow" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(314,9): error TS2717: Subsequent property declarations must have the same type.  Property 'year' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(315,9): error TS2717: Subsequent property declarations must have the same type.  Property 'month' must be of type 'string | undefined', but here has type '"long" | "short" | "narrow" | "numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(316,9): error TS2717: Subsequent property declarations must have the same type.  Property 'day' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(317,9): error TS2717: Subsequent property declarations must have the same type.  Property 'hour' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(318,9): error TS2717: Subsequent property declarations must have the same type.  Property 'minute' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(319,9): error TS2717: Subsequent property declarations must have the same type.  Property 'second' must be of type 'string | undefined', but here has type '"numeric" | "2-digit" | undefined'.
node_modules/typescript/lib/lib.es2020.intl.d.ts(321,9): error TS2717: Subsequent property declarations must have the same type.  Property 'timeZoneName' must be of type 'string | undefined', but here has type '"long" | "short" | undefined'.
```

### 🙂 Expected behavior

No errors

### PR DESCRIPTION
**Pull request by batisteo**
Fixes #42128

### CODE REVIEW

**Comment by orta** [comment]
Thanks! This looks good to me 👍🏻

**Comment by longlho** [comment]
@orta this should be revised/reverted. List of numbering system & calendar are NOT part of the ECMA402 spec. They conform to Unicode Locale Identifier semantic restriction, but the list can change every CLDR version which is separate from ECMA402.

Reference of failure upstream: https://github.com/formatjs/formatjs/issues/2616

**Comment by nstepien** [comment]
@longlho Can't TS keep up with CLDR versions regardless?

**Comment by longlho** [comment]
no because every browser version potentially ships with a different CLDR/libicu version. The release cadence is different. The spec also intentionally does not rely on this except for things like:
- Sanctioned units: https://402.ecma-international.org/7.0/#table-sanctioned-simple-unit-identifiers
- Simple digits mappings: https://402.ecma-international.org/7.0/#table-numbering-system-digits

An implementation can be spec-compliant if shipped with a newer/older CLDR version.

**Comment by RyanCavanaugh** [comment]
@longlho I'm not seeing why this needs a revert. We can update this file out-of-band to include whatever the largest current list is without loss of correctness relative to just `string`. Can you clarify?

**Comment by longlho** [comment]
So the problem is I can ship an implementation with `calendar: foo` and that's totally spec-compliant. An implementation is not required to implement all or subset of those calendars.

**Comment by longlho** [comment]
The es5 change is ok though, because the spec dictates that if you pass in an invalid option like `3-digit` instead of `2-digit` it will throw a `RangeError`.

**Comment by RyanCavanaugh** [comment]
> So the problem is I can ship an implementation with calendar: foo and that's totally spec-compliant. 

Make sense. From a practical perspective, is this a thing that happens with regularity, or is it worth catching a subtle typo like `"ethiopian"` for the sake of making someone write `"foo" as any` ?

**Comment by longlho** [comment]
Hmm I can see the argument for typo but I think at the end of the day you'd still need to manually do like `isCalendarSupport('ethiopia')` regardless and that should determine runtime capability. Besides, calendar names kinda... looks like typo (e.g `ethioaa` is shorthand for `ethiopic-amete-alem`. It used to be called `ethiopia` in CLDRv82 but changed to `ethioaa` in CLDRv83).

**Comment by RyanCavanaugh** [comment]
This has been merged for six weeks without visible complaint from user code, so I'm willing to let this go out in 4.2 and revert if we find people in the wild hitting it if the problem is that it's only possibly-too-strict on an input side.

**Comment by longlho** [comment]
Does it help if I just make a PR to revert it? 
This is neither here nor there because the reality is people rarely deal with non-`gregory` calendar & non-`latin` numbering system so you won't get direct complaints other than from `formatjs` which powers all the ECMA402 polyfills :( Our users won't be able to compile w/ TS4.2 basically (See https://github.com/formatjs/formatjs/issues/2616 as a reference)

**Comment by nstepien** [comment]
@longlho Why is it ok for formatjs to use an enum there, but not TS? 🤔

**Comment by longlho** [comment]
because that's the set of stuff we specifically support :) so if you're using formatjs you only get access to those calendar/numbering systems.

**Comment by nstepien** [comment]
Right, so an alternative fix would be for formatjs to do this:
```patch
-export interface DateTimeFormatOptions extends Intl.DateTimeFormatOptions {
+export interface DateTimeFormatOptions extends Omit<Intl.DateTimeFormatOptions, 'calendar'> {
```

**Comment by longlho** [comment]
Those are 2 separate problems though. I'm saying TS provides low level type def for ECMA402 API and right now it's in unspec'ed land with `calendar` & `numberingSystem`.
