### ISSUE TITLE
checkGrammarImportDeclarationNameInStrictMode does not check whether nameText is actually a reserved word or not

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#2849]
See https://github.com/Microsoft/TypeScript/pull/2684#issuecomment-94633608

>With this change, `import * as set from "set";` no longer compiles - `error TS1212: Identifier expected. 'set' is a reserved word in strict mode` (because name.originalKeywordKind is set to SetKeyword). Is this intentional? Or should the checks for originalKeywordKind check that it's between First and LastKeyword/ReservedWord/FutureReservedWord before generating the diagnostic?

>Such code compiles with 1.5 alpha with no issue.

https://github.com/Microsoft/TypeScript/blame/7f8e21b/src/compiler/checker.ts#L12033-L12061

Perhaps it should call isReservedWordInStrictMode on nameText before calling grammarErrorOnNode?
