### ISSUE TITLE
tsc colours diagnostics when stdout is not a TTY, splitting "error TS2304" and breaking output parsing (regressed in 6.0)

### ISSUE THREAD

**Issue by leo-heath** [microsoft/TypeScript#63888]
### 🔎 Search Terms

pretty, color, colour, ANSI, TTY, terminal detection, piped output, NO_COLOR

### 🕗 Version & Regression Information

- `typescript@7.0.2`
- also reproduces on `@typescript/native-preview@7.0.0-dev.20260707.2` and `@typescript/native-preview@7.0.0-dev.20260611.2`
- **regressed in TypeScript 6.0** — 5.6.3 and 5.9.3 behave correctly, so the Go port appears to have inherited this rather than introduced it

### ⏯ Playground Link

N/A — CLI output behaviour.

### 💻 Code

```sh
mkdir -p fx
printf '{"compilerOptions":{"noEmit":true,"skipLibCheck":true,"types":[]},"include":["*.ts"]}' > fx/tsconfig.json
printf 'export const x = doesNotExist\n' > fx/a.ts

# note the pipe/redirect — stdout is NOT a terminal
npx tsc@7.0.2 -p fx > out.txt 2>&1
grep -c 'error TS' out.txt
```

### 🙁 Actual behavior

`grep -c 'error TS'` prints **0**, on a build that failed with one error.

`out.txt` contains ANSI escapes even though stdout is a file:

```
^[[96mfx/a.ts^[[0m:^[[93m1^[[0m:^[[93m18^[[0m - ^[[91merror^[[0m^[[90m TS2304: ^[[0mCannot find name 'doesNotExist'.
```

The escapes land **between `error` and `TS2304`**, so the substring `error TS` does not exist anywhere in the output. Any tool that greps for it sees a clean build.

Same fixture, `tsc -p fx` redirected to a file, across versions:

| version | output | `grep -c 'error TS'` | ESC bytes |
|---|---|---|---|
| 5.6.3 | plain | 1 | 0 |
| 5.9.3 | plain | 1 | 0 |
| 6.0.3 | coloured | **0** | 4 |
| 7.0.2 | coloured | **0** | 4 |

Workarounds that do work on 7.0.2: `--pretty false`, and `NO_COLOR=1`.

Two related observations:

1. **`FORCE_COLOR=0` is ignored** — output stays coloured.
2. **`"pretty": false` in `tsconfig.json` is ignored** — output stays coloured. Only the CLI flag and `NO_COLOR` take effect. That looks like a separate bug; happy to split it out if you'd prefer.

### 🙂 Expected behavior

`--pretty` should default to `false` when stdout is not a TTY, as it did through 5.9 and as the docs describe ("Enable color and formatting… default: `true` unless piping to a file").

`tsc --help` on 7.0.2 states `--pretty … default: true` unconditionally, so this may be intentional — but if so it is a breaking change to CLI output for every consumer that parses it, and the docs and the pre-6.0 behaviour both say otherwise.

### Why it matters

This is silent rather than noisy. The build still exits non-zero, so CI *gates* are unaffected — but anything that reads the text gets the wrong answer with no signal. In our monorepo two real `Cannot find name` errors reached a commit because a script asked `pnpm typecheck | grep -c 'error TS'` and got `0`. The failure was initially misdiagnosed as an incremental-build-cache bug, since a passing grep and a failing build look identical from the outside.

`error TS` is the natural thing to match, it is what a decade of tsc output has printed, and it is the one substring the colouring reliably breaks.

**Comment by jakebailey** [comment]
FORCE_COLOR set to any value forces color, it's not a parsed thing.

Are you thinking of NO_COLOR?

In any case we absolutely have TTY detection, so I don't know why this wouldn't be working for you. Do you have FORCE_COLOR set and that's overriding everything?

**Comment by leo-heath** [comment]
Thanks for the quick reply, and for pushing back on this.

You were right. We traced it and `FORCE_COLOR=0` turns out to be set automatically in the environment these runs happen in, so it was present for every measurement I took and I never thought to check. With it unset, the same fixture does exactly what you'd expect:

```
tsc -p fx > out.txt 2>&1     # stdout redirected, not a terminal

                      grep -c 'error TS'   ESC bytes
  FORCE_COLOR=0               0                4
  unset                       1                0
```

So TTY detection is working fine and the report doesn't stand. The rest of it goes the same way: 6.0.3 and 7.0.2 both write plain output when redirected, so there's no 6.0 regression either. What I'd actually measured is that 5.6 and 5.9 don't read `FORCE_COLOR` at all while 6.0 does, which made that version boundary look like it meant something. And `"pretty": false` in tsconfig is honoured too, it was just being overridden the whole time.

Closing this, sorry for the detour.

One thing I did think was worth mentioning, since you said it isn't parsed: `0` means "off" in most other places, which is how we came to set it that way to begin with.

supports-color's readme:

> For situations where using `--color` is not possible, use the environment variable `FORCE_COLOR=1` (level 1), `FORCE_COLOR=2` (level 2), or `FORCE_COLOR=3` (level 3) to forcefully enable color, or `FORCE_COLOR=0` to forcefully disable.

And Node does the same in `lib/internal/tty.js`, where only `''`, `'1'`, `'true'`, `'2'` and `'3'` map to a colour depth and anything else falls through to monochrome:

```js
if (env.FORCE_COLOR !== undefined) {
  switch (env.FORCE_COLOR) {
    case '':
    case '1':
    case 'true':
      warnOnDeactivatedColors(env);
      return COLORS_16;
    ...
    default:
      return COLORS_2;
  }
}
```

Which is why on Node 26.7.0 `FORCE_COLOR=0 node -e 'null.x'` gives you an uncoloured stack trace and `FORCE_COLOR=1` gives you a coloured one, while tsc reads that same `0` the other way.

Completely fine if that's deliberate, and we're switching to `NO_COLOR` regardless since that behaves properly. Just flagging it because it was an easy one to trip over.

Thanks again for taking the time.

**Comment by jakebailey** [comment]
FWIW FORCE_COLOR handling is not consistent; `picocolors` forces colors if it exists at all, which was what I had modelled. Perhaps copying chalk would have made more sense, or Node's, yeah. It's annoying.

**Comment by jakebailey** [comment]
I'm going to leave this open because I'd like to make this work better for 7.1
