### PR TITLE
Contextually type binding initializers

### LINKED ISSUE #5762: Default initializers for binding elements are not contextually typed appropriately
The following example should error; instead, it passes because `v` is not contextually typed and instead gets the `any` type:

```ts
interface Foo {
    prop: (x: string) => number;
}

function f({ prop = v => v }: Foo) {
}
```

The following example should be free of errors; instead the compiler errors on `prop` with an assignability error:

```ts
interface Foo {
    prop: [string, number];
}

function f({ prop = ["hello", 1234] }: Foo) {
}
```

Error:

```
foo.ts(5,14): error TS2322: Type '(string | number)[]' is not assignable to type '[string, number]'.
  Property '0' is missing in type '(string | number)[]'.
```

Similarly, with string literal types:

```ts
interface Foo {
    prop: "foo" | "bar"
}

function f({ prop = "foo" }: Foo) {
}
```

Error:

```
foo.ts(5,14): error TS2322: Type 'string' is not assignable to type '"foo" | "bar"'.
  Type 'string' is not assignable to type '"bar"'.
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #5762

Previously they were not contextually typed, which meant that lambdas got completely incorrect types, and that types that rely on contextual typing, like tuples and string literal types, did not work correctly.

### CODE REVIEW

**Comment by sandersn** [comment]
I forgot to re-run tests after merging from master and one of the new tests failed. I'll fix it and update the PR.

**Comment by sandersn** [comment]
The baselines were missing Mohamed's improved serialisation of binding elements that doesn't print the initialiser as part of the type.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7845,6 +7851,16 @@ namespace ts {
                 if (isBindingPattern(declaration.name)) {
                     return getTypeFromBindingPattern(<BindingPattern>declaration.name, /*includePatternInType*/ true);
                 }
+                if (isBindingPattern(declaration.parent)) {
+                    const parentDeclaration = declaration.parent.parent;
+                    const name = declaration.propertyName || declaration.name;
+                    if (isVariableLike(parentDeclaration) &&
+                        parentDeclaration.type &&
+                        (name.kind === SyntaxKind.Identifier || name.kind == SyntaxKind.StringLiteral)) {
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: You don't have any tests right now for when the name is a string literal.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: In which case, wouldn't that be computed? What about the following case?

```ts
interface Foo {
    prop: (x: string) => number;
}

function f({ ["prop"]: local = v => v }: Foo) {
}
```

Comment (sandersn) [inline src/compiler/checker.ts]: This JSON-like syntax is allowed, which is the StringLiteral case, I believe:

```ts
function f( { "prop": local = v => +v }: Foo) {
}
```

The code you give is a ComputedPropertyName, I believe. I'll test all four.

Also, I used `==` instead of `===` by mistake. I'm not sure how the linter missed that.

Comment (sandersn) [inline src/compiler/checker.ts]: Yup, looks like ComputedPropertyName was missing. Thanks for the help finding and fixing the oversight.

**Comment by DanielRosenwasser** [comment]
:+1:
