### ISSUE TITLE
Error when passing a tuple array as the children prop in JSX

### ISSUE THREAD

**Issue by srmagura** [Microsoft/TypeScript#30711]
**TypeScript Version:**  3.4.0-dev.201xxxxx

**Search Terms:** JSX children, multiple children, single child, jsx single child was provided

**Code**

```ts
import * as React from 'react'

type Tab = [string, React.ReactNode]  // [tabName, tabContent]

interface Props {
    children: Tab[]
}

function TabLayout(props: Props) {
    return <div/>
}

export class App extends React.Component<{}> {
    render() {
        return <TabLayout>
            {[
                ['Users', <div/>],
                ['Products', <div/>]
            ]}
        </TabLayout>
    }
}
```

**Expected behavior:**

No error. This was the behavior in TS 3.2 and earlier.

**Actual behavior:**

     .\node_modules\.bin\tsc --jsx react .\index.tsx

index.tsx:15:17 - error TS2745: This JSX tag's 'children' prop expects  type '[string, ReactNode][]' which requires multiple children, but only a single child was provided.

This error starting appearing after upgrading to TS 3.3+.    Minimal test case uploaded to https://github.com/srmagura/ts-children-repro.

**Comment by cjdell** [comment]
I can confirm this same issue when upgrading the TS version to 3.4 from 3.2. 

For some reason an array literal in TSX is interpreted as a single child. Can workaround it by using manual `React.createElement` but obviously not convenient.

**Comment by weswigham** [comment]
>For some reason an array literal in TSX is interpreted as a single child.

Eeeyeah, because when the factory function is called, it is. Look at the difference between `{[
                ['Users', <div/>],
                ['Products', <div/>]
            ]}` and `{['Users', <div/>]}{['Products', <div/>]}` in the transpiled output - the two are meaningfully different. The type of `children` is supposed to be the type of `children` as you access it within the body of the element (which react says should actually be opaque btw), however from that we can't actually tell weather that means a single child with an array type or multiple children with the element type are allowed upon usage (meaning we should be allowing both). For our react type definitions, we've kinda been running types backwards - we start with the component's internal types and attempt to map them out into the arguments that component expects. The issue with that is there's a few cases (like here) where there are multiple input mappings which could result in the same internal type (namely: a single argument of the array type vs a list of the array element types) because of the flattening `react` currently does when only a single element is passed for `children`. (And what's great is that this convention is on the table to be [changed](https://github.com/reactjs/rfcs/pull/107) and is currently hard-coded into the compiler)

In any case. That all actually has nothing to do with this issue, which is actually caused by the contextual tuple type not propagating correctly (and the error is a little confusing since it's assuming the problem is an arity one (it is kinda?) which doesn't help, since then there's no further elaboration). A `const` cast, ie `[
                ['Users', <div/>],
                ['Products', <div/>]
            ] as const` can work around the problem until the fix is in, I believe.
