### PR TITLE
Improve soundness of indexed access types

### LINKED ISSUE #27895: Change in generic behavior between 3.0.1 and >=3.1.1
**TypeScript Version:**  3.2.0-dev.20181011
This code worked in 3.0.1, and is broken >=3.1.1.

**Search Terms:**
"is not assignable to type"

**Code**

```ts
export interface Entity {
    id: number | string;
}

export type IdOf<E extends Entity> = E['id'];

export interface EntityState<E extends Entity> {
    ids: IdOf<E>[];
    entities: { [key: string]: E, [key: number]: E };
}


export function getAllEntities<E extends Entity>(state: EntityState<E>): E[] {
    const { ids, entities } = state;
    return ids.map(id => entities[id]);
}

export function getEntity<E extends Entity>(id: IdOf<E>, state: EntityState<E>): E | undefined {
    const { ids, entities } = state;

    if (!ids.includes(id)) {
        return undefined;
    }

    return entities[id];
}
```

For completeness, I'll just mention that I intend for users to create subinterfaces of `Entity` and `EntityState` for their domain types (like `@ngrx/entity`), overriding `id` to be a more restrictive type. This is why the `IdOf` type is important. E.g.,

```ts
interface Task extends Entity {
    id: string;
    due: Date;
    title: string;
}

interface TaskState extends EntityState<Task> {
    // Inherits EntityState#ids as string[]
    currentTask?: string;
}
```

**Expected behavior:**
The code compiles without error.

**Actual behavior:**
```
BUILD ERROR
projects/entity/src/lib/entity-state.utils.ts(13,5): error TS2322: Type '{ [key: string]: E; [key: number]: E; }[E["id"]][]' is not assignable to type 'E[]'.
  Type '{ [key: string]: E; [key: number]: E; }[E["id"]]' is not assignable to type 'E'.
    Type 'Entity' is not assignable to type 'E'.
projects/entity/src/lib/entity-state.utils.ts(23,5): error TS2322: Type '{ [key: string]: E; [key: number]: E; }[E["id"]]' is not assignable to type 'E | undefined'.
  Type 'Entity' is not assignable to type 'E'.
    Type '{ [key: string]: E; [key: number]: E; }[E["id"]]' is not assignable to type 'E'.
      Type 'Entity' is not assignable to type 'E'.
```

**Playground Link:** 
[Playground Link](http://www.typescriptlang.org/play/#src=export%20interface%20Entity%20%7B%0D%0A%20%20%20%20id%3A%20number%20%7C%20string%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20IdOf%3CE%20extends%20Entity%3E%20%3D%20E%5B'id'%5D%3B%0D%0A%0D%0Aexport%20interface%20EntityState%3CE%20extends%20Entity%3E%20%7B%0D%0A%20%20%20%20ids%3A%20IdOf%3CE%3E%5B%5D%3B%0D%0A%20%20%20%20entities%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20E%2C%20%5Bkey%3A%20number%5D%3A%20E%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Aexport%20function%20getAllEntities%3CE%20extends%20Entity%3E(state%3A%20EntityState%3CE%3E)%3A%20E%5B%5D%20%7B%0D%0A%20%20%20%20const%20%7B%20ids%2C%20entities%20%7D%20%3D%20state%3B%0D%0A%20%20%20%20return%20ids.map(id%20%3D%3E%20entities%5Bid%5D)%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20getEntity%3CE%20extends%20Entity%3E(id%3A%20IdOf%3CE%3E%2C%20state%3A%20EntityState%3CE%3E)%3A%20E%20%7C%20undefined%20%7B%0D%0A%20%20%20%20const%20%7B%20ids%2C%20entities%20%7D%20%3D%20state%3B%0D%0A%0D%0A%20%20%20%20if%20(!ids.includes(id))%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20entities%5Bid%5D%3B%0D%0A%7D)

**Related Issues:** 
I did not find any that seemed similar, but I'm also unsure what the actual underlying problem is. I did [ask on StackOverflow](https://stackoverflow.com/q/52798934/4450643), and they suggested I ask here.

### LINKED ISSUE #30603: Function can return wrong values despite type
**TypeScript Version:**  3.4.0-dev.20190326

**Search Terms:** Function Generic Extends Keyof Property

**Code**

```ts
interface Type {
  a: 123;
  b: "some string";
}

function get123<K extends keyof Type>(): Type[K] {
  return 123;
}
```

**Expected behavior:**
The function `get123` would yield an error as the return type might not be correct as it depends on `K`.

**Actual behavior:**
No error for `get123`. That function would obviously always return 123. 

**Playground Link:** [Example on TypeScript Playground](https://www.typescriptlang.org/play/#src=interface%20Type%20%7B%0D%0A%20%20a%3A%20123%3B%0D%0A%20%20b%3A%20%22some%20string%22%3B%0D%0A%7D%0D%0A%0D%0Afunction%20get123%3CK%20extends%20keyof%20Type%3E()%3A%20Type%5BK%5D%20%7B%0D%0A%20%20return%20123%3B%0D%0A%7D%0D%0A)

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we improve soundness of indexed access types in a number of ways:

* When an indexed access `T[K]` occurs on the source side of a type relationship, it resolves to a union type of the properties selected by `T[K]`, but when it occurs on the target side of a type relationship, it now resolves to an intersection type of the properties selected by `T[K]`. Previously, the target side would resolve to a union type as well, which is unsound.
* Given a type variable `T` with a constraint `C`, when an indexed access `T[K]` occurs on the target side of a type relationship, index signatures in `C` are now ignored. This is because a type argument for `T` isn't actually required to have an index signature, it is just required to have properties with matching types.
* A type `{ [key: string]: number }` is no longer related to a mapped type `{ [P in K]: number }`, where `K` is a type variable. This is consistent with a string index signature in the source not matching actual properties in the target.
* Constraints of indexed access types are now more thoroughly explored. For example, given type variables `T` and `K extends 'a' | 'b'`, the types `{ a: T, b: T }[K]` and `T` are now considered related where previously they weren't.

Some examples:

```ts
function f1(obj: { a: number, b: string }, key: 'a' | 'b') {
    obj[key] = 1;    // Error
    obj[key] = 'x';  // Error
}

function f2(obj: { a: number, b: 0 | 1 }, key: 'a' | 'b') {
    obj[key] = 1;
    obj[key] = 2;  // Error
}

function f3<T extends { [key: string]: any }>(obj: T) {
    let foo = obj['foo'];
    let bar = obj['bar'];
    obj['foo'] = 123;  // Error
    obj['bar'] = 'x';  // Error
}

function f4<K extends string>(a: { [P in K]: number }, b: { [key: string]: number }) {
    a = b;  // Error
    b = a;
}
```

Previously, none of the above errors were reported.

Fixes #27895.
Fixes #30603.

### CODE REVIEW

**Comment by jack-williams** [comment]
Has the behaviour that was added in #27490 been taken out? The following function did error, but not under the new rules.
```ts
function fun<U extends { a: T }, T, K extends 'a'>(u: U, k: K, shambles: T): U[K] {
  u[k] = shambles; // was error
  return u[k];
}

const result: number = fun<{ a: number }, unknown, 'a'>({ a: 42 }, 'a', 'a string');
```

**Comment by ahejlsberg** [comment]
> Has the behaviour that was added in #27490 been taken out?

Yes, but that behavior wasn't right. For an indexed access `T[K]` we flat out didn't explore any constraints on the target side when both `T` and `K` were generic, which is quite inconsistent. For example, if you change the assignment in your example from `u[k] = shambles` to `u['a'] = shambles` there is no error before or now.

The real (and orthogonal) issue in your example is that we treat an assignment to `T[K]` as an assignment to `C[K]`, where `C` is the constraint of `T`. I discuss the reasons in my comment [here](https://github.com/Microsoft/TypeScript/issues/27470#issuecomment-426073500). The unsoundness caused by that rule continues to exist (and would be quite a bit harder to remove).

What has changed with this PR is that for a `T[K]` on the target side of a relation we now ignore index signatures in the constraint of `T`. That's definitely the right thing to do (because a type argument for T isn't actually required to have an index signature, it is merely required to have properties with matching types) and that's what really fixes the issue in #27470.

It's all rather involved!

**Comment by ahejlsberg** [comment]
@weswigham Can you take a look at why this is failing on `PragmaPsuedoMap`?

**Comment by weswigham** [comment]
Looks like we're pulling out some unexpected index signatures from the target or something? The bug should repro in the test harness, will just need to copy the relevant types into a test file.

**Comment by ahejlsberg** [comment]
@weswigham It's actually identifying an unsafe coercion. It used to be that `PragmaPseudoMap["reference"]` was (unsoundly) assignable to `PragmaPseudoMap[K]`, where `K extends keyof PragmaPseudoMap`, which, in combination with parameter bi-variance (because the compiler isn't yet using `--strictFunctionTypes`), caused the explicit type annotation on `(arg: PragmaPseudoMap["reference"]) => ...` to be accepted. That's no longer the case, and that's a good thing.

The easy fix is to explicitly cast the array parameter to `forEach` to the appropriate type.

**Comment by ahejlsberg** [comment]
@typescript-bot test this

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by jack-williams** [comment]
Thanks for the detailed write-up @ahejlsberg. 

> The real (and orthogonal) issue in your example is that we treat an assignment to T[K] as an assignment to C[K], where C is the constraint of T. I discuss the reasons in my comment here. The unsoundness caused by that rule continues to exist (and would be quite a bit harder to remove).

True, though did you not add behaviour to prevent pulling down `C` when `T` and `K` were both generic variables which is no longer in this PR? I understand that the original issue that prompted the fix is now correctly handled for other (more sensible) reasons, but discarding a sound rule seems a shame! Though, the rule is abit ad-hoc!

**Comment by ahejlsberg** [comment]
With latest commits there are three RWC projects with new errors. The errors in two of the projects are minor and identify unsoundness that we previously didn't catch. The last project, `fp-ts`, which already has massive inverted pyramids of error messages, now looks even more daunting. It makes heavy use of indexed access types and when they occur in target positions we create intersection types instead of union types. There are several new errors that appear to be correct with the stricter checking, but it's hard to tell.

**Comment by ahejlsberg** [comment]
@typescript-bot test this

**Comment by ahejlsberg** [comment]
@typescript-bot run dt

**Comment by ahejlsberg** [comment]
Summary of RWC and DT test runs:

* Two RWC projects have new unsoundness errors that we previously didn't catch.
* The (old) copy of the fp-ts project in RWC has new errors, but the actual [fp-ts](https://github.com/gcanti/fp-ts) project on GitHub has no new errors. We should consider refreshing fp-ts in RWC.
* Two DT projects have new unsoundness errors that we previously didn't catch.

All of the new errors are good catches and the fixes are easy (explicit casts to explicitly permit the unsound behavior), so I think this PR is good to go.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9837,16 +9844,16 @@ namespace ts {
             return numberIndexInfo !== enumNumberIndexInfo ? numberIndexInfo : undefined;
         }
 
-        function getIndexType(type: Type, stringsOnly = keyofStringsOnly): Type {
-            return type.flags & TypeFlags.Union ? getIntersectionType(map((<IntersectionType>type).types, t => getIndexType(t, stringsOnly))) :
-                type.flags & TypeFlags.Intersection ? getUnionType(map((<IntersectionType>type).types, t => getIndexType(t, stringsOnly))) :
+        function getIndexType(type: Type, stringsOnly = keyofStringsOnly, noIndexSignatures?: boolean): Type {
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: Yes, we should filter out the `any`, `string` and `number` types following the call to `getConstraintTypeFromMappedType` when `noIndexSignatures` is true. We only care about removing actual string index signatures here, so there's no need to propagate into index types or other instantiable types.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -11985,6 +12025,12 @@ namespace ts {
             return !!(getObjectFlags(type) & ObjectFlags.Anonymous) && isEmptyObjectType(type);
         }
 
+        function isStringIndexSignatureOnlyType(type: Type): boolean {
+            return type.flags & TypeFlags.Object && getPropertiesOfType(type).length === 0 && getIndexInfoOfType(type, IndexKind.String) && !getIndexInfoOfType(type, IndexKind.Number) ||
+                type.flags & TypeFlags.UnionOrIntersection && every((<UnionOrIntersectionType>type).types, isStringIndexSignatureOnlyType) ||
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: I want to exclude unions and intersections that contain anything but object types (e.g. instantiable types) which wouldn't happen if I just accessed props/indexes on the types directly. I really just care about pure string index signature types and unions/intersections thereof. Anything else can just go through the regular code path.

[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts]: Doesn't that mean the predicate you want here is
```ts
return (type.flags & TypeFlags.Object || (type.flags & TypeFlags.UnionOrIntersection && every((<UnionOrIntersectionType>type).types, t => !!(t.flags & TypeFlags.Object) || !!(t.flags & TypeFlags.Intersection && every((t as IntersectionType).types, t => !!(t.flags & TypeFlags.Intersection))))))
    && (getPropertiesOfType(type).length === 0 && getIndexInfoOfType(type, IndexKind.String) && !getIndexInfoOfType(type, IndexKind.Number))
```
?

[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: I'm not sure how that's better? There's no reason to check the properties and index signatures of unions and intersections themselves if we're already checking the constituents.

File: src/compiler/checker.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (jack-williams) [reply src/compiler/checker.ts]: Seems like that might lead to a better fix for this #29699?

File: src/compiler/checker.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts]: Because, as I said, as written this fails to flag `{} & {[idx: string]: whatever}` as index-signature only?

[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: But we eliminate empty object types from intersections so that shouldn't occur.

[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts]: We don't though - we leave around _one_ empty object in an intersection type always (to keep around its implied-objectiness). We eliminate redundant ones. Usually (I've seen a couple cases where that fails to occur because we use `isEmptyAnonymousObjectType` for that check and so only remove redundant _anonymous_ empty objects!).

[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: If I'm not mistaken, we only keep around an empty object type if there are no other object types in the intersection. So, for `{} & { [key: string]: xxx }` we do indeed eliminate the `{}`.

[the remark this answers is not in the document]
Comment (weswigham) [reply src/compiler/checker.ts]: @ahejlsberg empty mapped types (eg, `{[K in never]: whatever}`) are for sure kept around - they're not _anonymous_ object types at all.

[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts]: That's fine, I don't care about optimizing strange combinations of empty mapped types and pure string index signature types. I really think the check is fine as is.

**Comment by ahejlsberg** [comment]
Marking this as a breaking change since it *will* break existing unsound assignments. It's our classic dilemma. We get better at checking something and thus find new errors that _could_ happen, even if they currently don't.

**Comment by vilic** [comment]
@ahejlsberg This feature actually brings tons of problems for us to migrate.

We heavily relies on type calculation, but for example:

```ts
type SourceUnion = {value: number} | {value: string};

function foo<TType>(): void {
  type TValue = Extract<SourceUnion, {value: TType}>['value'];
  type TTarget = Extract<SourceUnion, {value: TType}>['value'];

  let value!: TValue;
  let target: TTarget = value;
}
```

In this case we are expecting two `Extract<SourceUnion, {value: TType}>['value']` to be identical, but as they are written separately, the compiler doesn't think so. We can define an alias for this type in this case to make it work, but in many cases it's not possible without introducing "unnecessary" generic types (e.g. the `value` and `target` above is in different places).

In fact we have already turned off `strictFunctionTypes` a long time ago, the benefit it brings is really limited to the overhead writing correct types.

**Comment by ahejlsberg** [comment]
@vilic It's a tricky problem. In general, allowing an indexed access type `T[K]` to be assignable to itself isn't even sound:

```ts
function flip<T, K extends keyof T>(obj: T, k1: K, k2: K) {
    const temp = obj[k1];
    obj[k1] = obj[k2];
    obj[k2] = temp;
}

let x = { a: 'abc', b: 42 };
flip(x, 'a', 'b');  // Bam!
```

In fact, it is only sound when `T` and `K` represent the same object and the same key. However, saying that nothing (other than `any`) is assignable to an indexed access isn't practical, so it becomes a game of *which* unsoundness to permit in order for the feature to be useful. One rule we've always had is that any given type (and, by extension, any `T[K]` for identical `T` and `K`) is by definition assignable to itself, and that's the basic unsoundness we permit. But your example above doesn't qualify because we don't see `TValue` and `TTarget` as identical types. So, the types need to match by the stricter assignability rules, and they don't. Previously they did, but that really wasn't correct.

It might be helpful to see a more real world example of code that is broken to understand if we missed something. But beyond that, you may need to add type assertions.

**Comment by vilic** [comment]
@ahejlsberg Thanks for the explanation. And I found a workaround for this situation by introducing a conditional type rather than using `[]`:

```
type Property<TObject, TKey extends keyof TObject> = TObject extends any
  ? TObject[TKey]
  : never;
```

**Comment by jcalz** [comment]
Cross-linking to #24085 and #27808 which are made more desirable by this change.

**Comment by fatcerberus** [comment]
At first I thought this was a good change but, while it definitely improves soundness, ends up being kind of restrictive in practice.  It totally breaks this simple case, for example:

```ts
declare function frob<T>(value: T): T;

interface Thing
{
    pig: string;
    cow: number;
    ape: boolean;
}

const t: Thing = { pig: "it's fat", cow: 1208, ape: true };
const ks = Object.keys(t) as (keyof Thing)[];
for (const k of ks) {
    t[k] = frob(t[k]);  // what do you mean, "error"?!
}
```

To make the above work in TS 3.5 you can either:

1. Narrow `k` to a single possibility at each iteration (not reasonable - I wouldn’t have bothered writing a loop otherwise :wink:)
2. Use a cast, which gives up *much more* type safety than we gained from this change.

I understand why this happens: the compiler doesn’t know exactly what `k` is, so it can’t prove it will access the same property on both sides.  But the restriction turns out to be onerous: metaphorically, we now have a `herbivore | carnivore` and the compiler is telling us we have to feed it `type dirt = meat & plant` because we can’t prove which one it is.

#31837, IMO is a reasonable compromise: it relaxes this only for assignments between two indexed access types, thereby allowing the above case (and several others) to work again.

**Comment by jcalz** [comment]
>Narrow `k` to a single possibility at each iteration (not reasonable - I wouldn’t have bothered writing a loop otherwise 😉)

This reminds me of my ill-fated #25051 request (and its more solution-agnostic cousin #30581).  I want to say "for each possible narrowing of `k`, check that `t[k] = frob(t[k]);` compiles.  If so, great.  If not, that's the error."  I'd love to be able to tell the compiler to *pretend* that I wrote a bunch of identical `case` statements without having to go through it.  Oh well.

**Comment by fatcerberus** [comment]
It’s even worse in the case of a generic key (`T[K]` where at least `K` is a generic type variable), because then you *can’t* narrow it: not even the *compiler* knows what the possibilities are.  `K extends keyof T` -> `K` might as well just be its upper bound for this purpose, no matter what you do.

**Comment by jack-williams** [comment]
I think having a `unique keyof` type might work, and could be implicitly created at the point a `keyof` type is assigned to a const. Index access types with equal `unique keyof` types will act covariantly rather that creating a conservative write type.

**Comment by fatcerberus** [comment]
> for each possible narrowing of k, check that t[k] = frob(t[k]); compiles. If so, great. If not, that's the error

This sounds great in theory but realistically even if you only consider singleton narrowings, it works out to something like `O(n^m)` complexity (where `n` is average size of a `keyof` union and `m` is the number of unique key variables involved) which probably wouldn’t be practical.  Interesting idea, though.

**Comment by jcalz** [comment]
@fatcerberus Yeah, my suggestion in #25051 was that the developer would have to explicitly opt into such analysis for a particular variable in a particular scope (e.g., `type switch(k) { t[k] = frob(t[k]); }`) which would minimize such complexity explosion... at the expense of the introduction of a new proof-assistant-style type witness syntax which would undoubtedly scare and confuse more people than it would help.

**Comment by ahejlsberg** [comment]
> At first I thought this was a good change but, while it definitely improves soundness, ends up being kind of restrictive in practice. It totally breaks this simple case, for example

That particular example is broken because it is written in terms of non-generic types (which typically isn't the case). An indexed access `T[K]` where neither `T` nor `K` is generic is immediately resolved and produces a union of the property types on the source side of an assignment or an intersection of the property types on the target side of an assignment. This means the checker no longer sees the same indexed access type on both sides.

The example works in higher order form:

```ts
declare function frob<T>(value: T): T;

function frobify<T extends object>(t: T) {
  const ks = Object.keys(t) as (keyof T)[];
  for (const k of ks) {
    t[k] = frob(t[k]);
  }
}
```

Here we have the same `T[K]` on both sides of the assignment and we allow that per my comment [here](https://github.com/microsoft/TypeScript/pull/30769#issuecomment-498428559).

**Comment by fatcerberus** [comment]
Given that `T` and `K` are the same type on both sides of an assignment (assuming `K` is a union and not a single key), how common is it *in the real world* that an assignment of the form `T[K] = T[K]` is going to use different keys on both sides?  Given the code I’ve written myself in the past, I would think this is far outweighed by the cases where the key is the *same* (as you would usually write code like this as part of some kind of cloning operation), and adding this restriction therefore ends up being onerous.

I’m not debating that `T[K] = someArbitraryThing` shouldn’t be restricted; the restriction makes perfect sense there.  It just might be worth relaxing it for `T[K] = T[K]` (even outside of generics) given the typical coding patterns I’ve encountered.

**Comment by NickHeiner** [comment]
```ts
type O = {
    key1: string;
    key2: boolean;
};

function setOptions(o1: O, o2: O, key: keyof O) {
    // Error: Type 'string | boolean' is not assignable to type 'never'.
    o1[key] = o2[key];
}
```

[Playground](https://typescript-play.js.org/#code/C4TwDgpgBA8lC8UDeAoK6oGsIgIwC4oBnYAJwEsA7AcwG40NsQAmQgIwHsOAbCAQ0r0AvvRQAzAK6UAxsHIdKxCMBhg5CogAoOBWABooHVvqw5CTDmNgBKZA3Q6A2kwC6CQ82c4XwoA)

In general, I think I understand the benefits of this change. But is it too much to ask that TS be smart enough to recognize when `key` is the same value on the LHS and RHS, and thus permit it?

**Comment by ahejlsberg** [comment]
@NickHeiner See my comment above for why it is an error with non-generic types. Meanwhile, it works if you introduce a type variable for the key:

```ts
function setOptions<K extends keyof O>(o1: O, o2: O, key: K) {
    o1[key] = o2[key];  // Ok
}
```

**Comment by NickHeiner** [comment]
Presumably you're referring to your comment that:

> An indexed access T[K] where neither T nor K is generic is immediately resolved and produces a union of the property types on the source side of an assignment or an intersection of the property types on the target side of an assignment.

Proximately, this explains why it doesn't work, but at a root level, I'm still not sure why it *shouldn't*. Anyway, the workaround you've given is reasonable. 

Thank you for all your work on programming languages over the years!

**Comment by TidyIQ** [comment]
This change causes a bug that sets a type to "never" even though the type is already defined. Bug issue referenced [here](https://github.com/microsoft/TypeScript/issues/32375)

[Playground link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgGIHsoFsDKY6TIDeAsAFDLIDaA1hAJ4BcyAzmFKAOYC6zpFlZDGAQANgBMWfcoMG0GzNhxA9pA2ZWAsAkiABucUcHHMARunSiIcEAG4ZGzSwBqh42YtWb99RtFxTMQB1YzAAC2YQAFcsQKgfR0oWMPQAdwAFOBYWVMxxAH4PS2s7B0cDUSiIRXYuBI0AX3rKJrLkdAAHCBBC5HNi7wdWsgbyciswIUxcfEhmDGw8AhQAXmIHGAs1WWExSW2NUzgoA8ctXQr3IUMWCAAaNtktVyMTa9Fbh99Zf0DREPE4WYAAYvolkBUqswAETQx7IUa+REtcjDcigSCwRAoHAQMCoEQSF5VdJQTosAA8DgAKsgIAAPSAgSTIOj0dAwNDTJaENZsjlcxaze4OVB0xndFn8zkLGbLKjU7hUaG7CQsaHcZB8hgC2U8iAKpUqwmSDVg5AAaXFTKlOpl3OFhuVqtNStQmu17PtQvliudJvVbu45AAfOsBJtsMxqfUXfN6mzmBb6pDqoK5ZAnca9oGqO6qBbuD5EeQEOgQGxkOJ0Dh0Fg8WEuFrkAAKDpkjpSZC4-Em4kQUnkgCUzD06GMWrD-EcZYrkyIU2wdyEJuXbOXqYRzfb5OagkjGYNB+4ADoXSwqC6lWyPRDDFVi0A)

**Comment by k8w** [comment]
```ts
interface State {
    a: string,
    b: boolean
}
declare let state: State;

function setState<K extends keyof State>(key: K, value: State[K]): void {
    // This works
    state[key] = value;

    // State[K] is not correctly inferenced
    if (key === 'a') {
        // Error: Type 'State[K]' is not assignable to type 'string'
        state.a = value;
    }
    else if (key === 'b') {
        // Error: Type 'State[K]' is not assignable to type 'boolean'
        state.b = value;
    }
}

// State[K] is correctly inferenced here
setState('a', 'xxx');   // Succ as expected
setState('b', true);    // Succ as expected
setState('a', true);    // Error as expected
setState('b', 'xxx');   // Error as expected
```

@ahejlsberg indexed access with generics now works differently inside & outside a function.

**Comment by quixot1c** [comment]
> * Given a type variable `T` with a constraint `C`, when an indexed access `T[K]` occurs on the target side of a type relationship, index signatures in `C` are now ignored. This is because a type argument for `T` isn't actually required to have an index signature, it is just required to have properties with matching types.

@ahejlsberg  If "a type argument for `T` isn't actually required to have an index signature", why is indexed access still allowed on the source side of a type relationship?

**Comment by ahejlsberg** [comment]
> If "a type argument for T isn't actually required to have an index signature", why is indexed access still allowed on the source side of a type relationship?

An indexed access `T[K]` doesn't actually require `T` to have an index signature. It's more helpful to think of it as a property access. As long as `K` is known to reference the name of a property in `T` (i.e. because `K` is a literal type like `"foo"`), then `T[K]` is permitted. However, an indexed access `T[string]` does require `T` to have an index signature.

**Comment by craigphicks** [comment]
The errors in this test case seem wrong to me:
```
function f3<T extends { [key: string]: any }>(obj: T) {
    let foo = obj['foo'];
    let bar = obj['bar'];
    obj['foo'] = 123;  // Error  - (its writable and matches the parameters why error?)
    obj['bar'] = 'x';  // Error - (ditto)
}
```
This function format exists if errors are desired:
```
function f5<T extends Readonly<{ [key: string]: any }>>(obj: T) {
    let foo = obj['foo'];
    let bar = obj['bar'];
    obj['foo'] = 123;  // Error
    obj['bar'] = 'x';  // Error
}
declare const obj: {
  foo: boolean;
  bar: boolean;
};
f5(obj);
```
Shouldn't TypeScript assume the user is reading the function parameters and trust them not to call `f3` because of the `any` type and the fact that it is non-readonly?
