### ISSUE TITLE
Uninstantiated modules cannot be declared prior to merged class and instantiated module

### ISSUE THREAD

**Issue by kersam-bl** [Microsoft/TypeScript#1414]
We are having a compile error which popped up recently after trying to upgrade to TypeScript 1.3:

```typescript
module MyClass {
  export interface Someinterface {
    foo(): void;
  }
}

class MyClass {
  constructor() {
  }
}

module MyClass {
  export class Manager {
  }
}

export = MyClass;
```

We compile the code with tsc Test.ts --module AMD
It used to work fine with TypeScript 1.0.1.0, but when compiling with 1.3.0.0 it gives us the follwing error:
Test.ts(1,8): error TS2434: A module declaration cannot be located prior to a class or function with which it is merged
