### ISSUE TITLE
Typescript 4.4.2 with yarn 3.x. Cannot find modules

### ISSUE THREAD

**Issue by gizmooo** [microsoft/TypeScript#45681]
# Bug Report
typescript cannot find all installed dependencies

![sc](https://user-images.githubusercontent.com/15375870/131721810-7d877c15-c7cc-4d39-83d0-e6216e94898a.png)

### 🔎 Search Terms

yarn imports

### 🕗 Version & Regression Information

- does not work yarn v3.0.1 & typescrtipt v4.4.2
- works with yarn v3.0.1 & typescript v4.3.5 
- works with npm & typescrtipt v4.4.2

### 💻 Code

```json
{
  "compilerOptions": {
    "lib": [
      "WebWorker",
      "DOM",
      "DOM.Iterable",
      "ESNext",
      "ScriptHost"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": false,
    "noEmit": false,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "prod/build",
    "baseUrl": "./",
    "paths": {
      "MEDIA/*": ["dev/media/*"],
      "IMAGES/*": ["dev/media/images/*"],
      "TYPES/*": ["dev/js/types/*"]
    }
  },
  "exclude": ["node_modules"],
  "files": [
    "./dev/js/entry.ts"
  ],
  "include": ["dev", "./dev/js/global.d.ts"]
}
```

### 🙁 Actual behavior

Typescript v.4.4.x does not work with yarn version 3.x

### 🙂 Expected behavior

Typescript v.4.4.x finds all dependencies with yarn 3.x

**Comment by DanielRosenwasser** [comment]
Looks like Yarn Plug'n'Play might have had to specially handle TS4.4. Check out https://github.com/yarnpkg/berry/issues/3350.

According to https://github.com/yarnpkg/berry/issues/3372#issuecomment-910056546, you might be able to get around it by running 

```sh
yarn set version canary && yarn
```

**Comment by gizmooo** [comment]
Yeah! it really works! Thanks

**Comment by merceyz** [comment]
> Looks like Yarn Plug'n'Play might have had to specially handle TS4.4

Sadly we have to rebuild the patch (https://github.com/microsoft/TypeScript/pull/35206) for almost every minor TypeScript release
https://github.com/yarnpkg/berry/blob/464618c2f7baba46a79d66849c1eda00cad1132e/packages/plugin-compat/extra/typescript/gen-typescript-patch.js#L18-L80

**Comment by gizmooo** [comment]
Yarn released version 3.0.2 compatible with 4.4.x typescript :)

```shell
yarn set version latest
```

**Comment by eltonio450** [comment]
it seems to work on Mac but not on Linux (WSL)

how does the patch rebuild work? It seems to be related to a resolution hash that is not the same on both platforms

below is the diff in my yarn.lock when I `yarn install` on Linux after it has been done on Mac

![image](https://user-images.githubusercontent.com/6675365/132090574-32e61efe-8f4e-4bf3-b4b9-f39a064b683a.png)

I am not sure If it is related to this issue or yarn itself

thank you

**Comment by michael-kudrik** [comment]
Found this article that helped me: https://plainenglish.io/blog/getting-started-with-yarn-3-and-typescript-125e7b537e6c
