### ISSUE TITLE
Upgrade JQuery version 3.2,it's throws lint error

### ISSUE THREAD

**Issue by AshokkumarBalasubramanian** [Microsoft/TypeScript#17887]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

In my application, I have used the interface as like below.It's works fine in JQuery 2.0

interface JQuery{
data(key: any): any;
}

When upgrade a version to JQuery 3.2,It's throws the below lint errors.

**All declarations of 'JQuery' must have identical type parameters.
interface JQuery<TElement extends Node, HTMLElement>
namespace JQuery**

Typescript Version: 2.3.4

How to resolved the issue or modify the interface?

**Comment by aluanhaddad** [comment]
The newer versions of `npm:@types/jquery` changed the `JQuery interface to be generic in 2 type parameters.

The error is correct and means exactly what it says.

To resolve it change your declaration to match
```ts
interface JQuery<TElement extends Node, HTMLElement> {
    data(key: any): any;
}
```

**Comment by AshokkumarBalasubramanian** [comment]
Hi @aluanhaddad ,

As per your solution resolved the lint errors,but throws compilation error.Please check the below error

**All declarations of 'JQuery' must have identical type parameters.**

**Comment by aluanhaddad** [comment]
@AshokkumarBalasubramanian sorry, I made an error, there is only one type argument.
It needs to be
```ts
interface JQueryStatic<TElement extends Node = HTMLElement> {
}
interface JQuery<TElement extends Node = HTMLElement> {
}
```
instead.

**Comment by AshokkumarBalasubramanian** [comment]
Hi @aluanhaddad ,

As per your suggestion,I have modify the interface as like below,but throws both Lint Errors and compilation errors.

interface JQuery<TElement extends Node **=** HTMLElement> {
    data(key: any): any;
}

declare namespace simple {
    function sampleApp(): JQuery<Element, HTMLElement>;
}

**Lint Error :** 

**,** Expected.

**Compilation Errors:**

../../node_modules/@types/jquery/index.d.ts(2955,63): error TS2304: Cannot find name 'Iterable'.
error TS2707: Generic type 'JQuery<TElement>' requires between 0 and 1 type arguments.

**Comment by aluanhaddad** [comment]
Update to typescript 2.4.2
