### PR TITLE
Do not always instantiate jsx signatures

### LINKED ISSUE #21028: No string literal type for optional property in JSX
**TypeScript Version:**  2.7.0-dev.20180104

**Code**

```ts
import * as React from "react";

interface Props {
    x?: "a" | "b";
}
class MyComponent<P extends Props = Props> extends React.Component<P> {}
const m = <MyComponent x="a"/>
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.tsx(7,24): error TS2322: Type '{ x: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<MyComponent<Props>> & Readonly<{ children?: ReactN...'.
  Type '{ x: string; }' is not assignable to type 'Readonly<Props>'.
    Types of property 'x' are incompatible.
      Type 'string' is not assignable to type '"a" | "b" | undefined'.
```

This was working in `2.7.0-dev.20180103`.
There is no error if `x` is made non-optional.
But discovered in `react-leaflet` on DefinitelyTyped. There are also errors in `react-router` that look similar.

### PR DESCRIPTION
**Pull request by weswigham**
When I changed jsx to actually do inference, I hadn't realized that JSX had been instantiating signatures during its use in the `getContextualType` code path. Since that path doesn't specify a `sourceAttributesType` (because we're in the process of calculating it), signatures were being instantiated with `{}` (in the associated issue, this meant that props was set to `{}` and then `{}` was used to contextually type the attributes, rather than `P extends { x?: "a" | "b" }`). Now, if `sourceAttributesType` is `undefined`, we do _not_ instantiate the signatures at all, which is what the contextual typing code actually expects.

Fixes #21028

### CODE REVIEW

**Comment by weswigham** [comment]
Note, the bug @andy-ms reported (#21028) is responsible for troublesome breaks in [dt](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22788), so this fix should make it into the initial 2.7 drop, not 2.8.
