### PR TITLE
Check for keyof constraint type instead of syntactic check

### LINKED ISSUE #24080: Conditional type breaks generic inference on jsx in 2.9
In code below constructing generic jsx element `el1` works in 2.8.3, but breaks on `2.9.0-dev.20180512`. Constructing `el2` in `2.9.0-dev.20180512` works fine - shouldn't these be completely equivalent?

**TypeScript Version:**  2.9.0-dev.20180512

**Search Terms:** jsx conditional

**Code**

```ts
type FunctionPropertyNames<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T];
class TestObject {
    a: string = '';
    b: number = 1;
    c: () => void = () => { };
}
interface TestProps<T> {
    model: T;
    foo: FunctionPropertyNames<T>;
}
function Test<T>(props: TestProps<T>) { return <></>; }
const model = new TestObject();

const el1 = <Test model={model} foo="c" />;
const el2 = <Test<TestObject> model={model} foo="c" />;
```

**Expected behavior:**
Compilation passes without errors.

**Actual behavior:**
```
test.tsx:14:33 - error TS2326: Types of property 'foo' are incompatible.
  Type 'string' is not assignable to type '"c"'.

14 const el1 = <Test model={model} foo="c" />;
                                   ~~~~~~~
```

**Playground Link:**  
n/a since playground doesn't support jsx

**Related Issues:** 
Possibly related to https://github.com/Microsoft/TypeScript/issues/23724

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #24080

Downside: `T extends string | symbol | number` will now produce literals. (technically a break)
Upside: `T extends string | symbol | number` will now produce literals. (probably desirably, given any one of those on their own would produce literals)

### CODE REVIEW

**Comment by ahejlsberg** [comment]
I'm not sure I like this. It's really odd that `T extends string` and `T extends string | number | symbol` gives you literal types, but `T extends string | number` does not!

**Comment by weswigham** [comment]
@ahejlsberg So I've generalized it to just being a type variable constrained to any of string or number or symbol (rather than exactly one of them)... and there's no diff to any tests, `user` tests, or `rwc` tests. I think it's a relatively safe change.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -20577,11 +20568,10 @@ namespace ts {
                     // this a literal context for literals of that primitive type. For example, given a
                     // type parameter 'T extends string', infer string literal types for T.
                     const constraint = getBaseConstraintOfType(contextualType) || emptyObjectType;
-                    return isTypeParameterWithKeyofConstraint(contextualType) && maybeTypeOfKind(candidateType, TypeFlags.StringLiteral | TypeFlags.NumberLiteral | TypeFlags.UniqueESSymbol) ||
-                        constraint.flags & TypeFlags.String && maybeTypeOfKind(candidateType, TypeFlags.StringLiteral) ||
-                        constraint.flags & TypeFlags.Number && maybeTypeOfKind(candidateType, TypeFlags.NumberLiteral) ||
-                        constraint.flags & TypeFlags.Boolean && maybeTypeOfKind(candidateType, TypeFlags.BooleanLiteral) ||
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: The line that checks for `TypeFlags.Boolean` isn't necessary. The logic already covers unions of literal types, and `TypeFlags.Boolean` is just a convenience flag we set on the built-in `true | false` union.
