### ISSUE TITLE
Incorrect "Cannot find name" when importing default value

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript#26391]
**TypeScript Version:** 3.0.1

**Search Terms:** Cannot find name import default

**Code**

```ts
// fetch.d.ts
declare function fetch(url: string): Promise<any>;
export = fetch;
declare namespace fetch {
  export { fetch as default };
}

// index.ts
import f from "./fetch";
f("url"); // error TS2304: Cannot find name 'f'
```

**Expected behavior:** Name should be found

**Actual behavior:** Cannot find name. Interestingly `import { default as f } from "./fetch";` works.

**Playground Link:** (It doesn't support modules :/)

**Related Issues:** Couldn't find one

**Comment by IIIristraM** [comment]
I also face the issue with default import from a js file with `exports.default = Component`. `import Component from '...'` worked fine in version `2.8.4` Now it woks only with `import {default as 
 Component} from '...'`.

There is `"allowSyntheticDefaultImports": true` in my `tsconfig`, setting option to `false` resolves the issue, but creates much more troubles in my project.

Probably this is related issue.

**Comment by RyanCavanaugh** [comment]
This appears to be fixed now
