### PR TITLE
Unknown properties are assignable to `Object` in union

### LINKED ISSUE #15254: Can't assign object to variable of type `Object | undefined`
**TypeScript Version:**  nightly (2.3.0-dev.20170413)

**Code**

```ts
const x: Object | undefined = { a: 0 };
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(1,33): error TS2322: Type '{ a: number; }' is not assignable to type 'Object | undefined'.
  Object literal may only specify known properties, and 'a' does not exist in type 'Object | undefined'.
```

Works in `typescript@2.3.0-dev.20170412`!

### PR DESCRIPTION
**Pull request by sandersn**
For the last week or so they have been treated as excess properties when assigning to a union type containing Object, but not when assigning directly to Object type.

Fixes #15254

### CODE REVIEW

**Comment by andy-ms** [comment]
Maybe `Object | string === Object` before?

**Comment by sandersn** [comment]
Oh, subtype reduction? Maybe.
