### ISSUE TITLE
Up-to-date typings (like lib.dom.d.ts) for older versions

### ISSUE THREAD

**Issue by AbakumovAlexandr** [microsoft/TypeScript#27236]
## Search Terms

typings

## Suggestion

The proposal is to introduce a maintenance-friendly mechanism to be able to use up-to-date typings in older versions of TypeScript.

## Use Cases
Often, we can't just bump up the TS version due to limitations in dependencies. However, JS and DOM APIs are constantly evolving and typings like `lib.dom.d.ts` are frequently updated to reflect those. But we have to wait until we're able to switch to the latest TS to use the newest APIs without tricks like tons of `any` casting, introducing temporary typings (which might not work with conflicting API changes).

## Examples
Here is a specific use case. Angular 6 forces the maximum TypeScript version to be 2.9.2. However, IndexedDb-related types were added starting from TS 3 only. The following pretty basic code to start working with IndexedDb won't compile with TS 2.9.2:
```
const storage: StorageManager = navigator.storage;
```
due to an error:

> Property 'storage' does not exist on type 'Navigator'.

But it perfectly compiles with TS 3.0.3.

So, we'd like some mechanism to alleviate this. For example, it could be a `@types` package which replaces `lib.dom.d.ts` from the current TS compiler by the newest one available in the latest TS.

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by RyanCavanaugh** [comment]
Isn't this just `noLib` + whatever distribution mechanism you prefer for the replacement files?

**Comment by RyanCavanaugh** [comment]
Closing due to lack of follow-up
