### ISSUE TITLE
Newly added files not registered as belonging to composite projects

### ISSUE THREAD

**Issue by mntnoe** [microsoft/TypeScript#38976]
**TypeScript Version:**  3.8-rc to 4.0.0-dev.20200608

**Search Terms:**
composite, watch directories

**Code**

```
git clone https://github.com/mntnoe/ts-build-repro/
cd ts-build-repro
node build-watch
```
The node script will invoke the TS solution builder API to watch the `src` project, then add and import a file to it.

Also check out the scenario using a watch program (`program-watch.js`), as the error is displayed briefly in this case.

**Expected behavior:**
Project recompiles successfully.

**Actual behavior:**
Project fails with `src/main.ts(2,8): error TS6307: File '.../ts-build-repro/src/bar.ts' is not listed within the file list of project '.../ts-build-repro/src/tsconfig.json'. Projects must list all files or use an 'include' pattern.`

**Related Issues:**

I believe the issue was introduced by https://github.com/microsoft/TypeScript/pull/35615, as the issue started with TS 3.8. Adding `watchDirectories: false` works around the problem.

**Comment by sheetalkamat** [comment]
Fixed by #39030
