### ISSUE TITLE
Errors: "(TS) 'const' initializer in an ambient context must be a string or numeric literal" and "(TS) Initializers are not allowed in ambient contexts."

### ISSUE THREAD

**Issue by J242** [microsoft/TypeScript#29448]
![typescripterrorsinvs](https://user-images.githubusercontent.com/12087945/51284859-fc5bd900-19ba-11e9-9cc3-9426ab9c0296.JPG)

Can anyone help with these TypeScript errors I get intermittently when attempting to compile in Visual Studio 2017? They include:

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS1254	(TS) A 'const' initializer in an ambient context must be a string or numeric literal.	C:\Projects\MusicLists\MusicListsApp\WebPresentation (tsconfig or jsconfig project)	C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\ivy_switch\compiler\ivy_switch_on.d.ts	12	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS1254	(TS) A 'const' initializer in an ambient context must be a string or numeric literal.	C:\Projects\MusicLists\MusicListsApp\WebPresentation (tsconfig or jsconfig project)	C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\ivy_switch\compiler\legacy.d.ts	19	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS1039	(TS) Initializers are not allowed in ambient contexts.	C:\Projects\MusicLists\MusicListsApp\WebPresentation (tsconfig or jsconfig project)	C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\common\http\src\response.d.ts	253	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS1039	(TS) Initializers are not allowed in ambient contexts.	C:\Projects\MusicLists\MusicListsApp\WebPresentation (tsconfig or jsconfig project)	C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\common\http\src\response.d.ts	259	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS1039	(TS) Initializers are not allowed in ambient contexts.	C:\Projects\MusicLists\MusicListsApp\WebPresentation (tsconfig or jsconfig project)	C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\application_init.d.ts	26	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS1039	(TS) Initializers are not allowed in ambient contexts.	C:\Projects\MusicLists\MusicListsApp\WebPresentation (tsconfig or jsconfig project)	C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\linker\query_list.d.ts	36	Active

 Thanks!

**Comment by J242** [comment]
Yeah, I think you're right, but I don't know how to upgrade Visual Studio's Type Script compiler. The things I'm reading say Visual Studio now works on a per project basis and suggest changing the project's TypeScript Build in the project's properties which shows 2.8. I believe this will upgrade the codebase not the compiler.

**Comment by J242** [comment]
I tried downloading and installing the latest TypeScript SDK for Visual Studio 2017 from: https://www.microsoft.com/en-us/download/details.aspx?id=55258. 

I'm assuming this would upgrade Visual Studio's version of TypeScript. 

|I still received the following errors upon build:

1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker ps --filter "status=running" --filter "name=dockercompose6946136170613312467_webpresentation_" --format {{.ID}} -n 1
1>Domain -> C:\Projects\MusicLists\MusicListsApp\Domain\bin\Debug\netcoreapp2.1\Domain.dll
1>Application -> C:\Projects\MusicLists\MusicListsApp\Application\bin\Debug\netcoreapp2.1\Application.dll
1>Persistence -> C:\Projects\MusicLists\MusicListsApp\Persistence\bin\Debug\netcoreapp2.1\Persistence.dll
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\common\http\src\response.d.ts(253,21): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\common\http\src\response.d.ts(259,19): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\application_init.d.ts(26,21): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\ivy_switch\compiler\ivy_switch_on.d.ts(12,35): error TS1254: Build:A 'const' initializer in an ambient context must be a string or numeric literal.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\ivy_switch\compiler\legacy.d.ts(19,35): error TS1254: Build:A 'const' initializer in an ambient context must be a string or numeric literal.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\linker\query_list.d.ts(36,22): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\common\http\src\response.d.ts(253,21): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\common\http\src\response.d.ts(259,19): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\application_init.d.ts(26,21): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\ivy_switch\compiler\ivy_switch_on.d.ts(12,35): error TS1254: Build:A 'const' initializer in an ambient context must be a string or numeric literal.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\ivy_switch\compiler\legacy.d.ts(19,35): error TS1254: Build:A 'const' initializer in an ambient context must be a string or numeric literal.
1>C:\Projects\MusicLists\MusicListsApp\WebPresentation\node_modules\@angular\core\src\linker\query_list.d.ts(36,22): error TS1039: Build:Initializers are not allowed in ambient contexts.
1>Done building project "WebPresentation.csproj" -- FAILED.

**Comment by slobadx** [comment]
I have the same problem, my solution works in local but not in azure. Azure throws the same  TS1039 Error.
I am working with Angular 7.2 and core 2.2

**Comment by rahul-aut-ind** [comment]
I had the same problem in my local. Turns out the typescript package installed globally in system and local to the project were little different. Changing the same in local (package.json) to reflect the global version of typescript installed( via npm) after taking latest of typescript ( npm i -g typescript) solved the issue for me.
____ 
Root cause of this issue for me was "tsc" command fails when invoked from inside of a script written in package.json

## Hope this helps!!
