### ISSUE TITLE
Compile error going from 3.4.5 to 3.5.0-rc with Pick

### ISSUE THREAD

**Issue by alamothe** [microsoft/TypeScript#31531]
Hello,
I have a simple code which compiles with `3.4.5` but not `3.5.0-rc`. Simplest version:
```ts
type T = {
	from: number,
	to: number,
}

function set<K extends 'from'|'to'>(key: K): Pick<T, K> {
	return {
		[key]: 10,
	}
}
```

In `3.5.0-rc` the error is:
```
... - error TS2322: Type '{ [x: string]: number; }' is not assignable to type 'Pick<T, K>'.
```

In `3.4.5` there is no error. 

The code looks fine to me, but I am not sure if this is a bug or expected, or if there's a workaround. Thanks!

**Comment by nmain** [comment]
I think the error is correct:

```ts
const foo = set<"from" | "to">("from");
console.log(foo.to); // typescript says number, runtime says undefined
```

**Comment by ahejlsberg** [comment]
This is an effect of #30769. The error is indeed the intended behavior.

**Comment by alamothe** [comment]
Thanks for explaining!
