### ISSUE TITLE
3.1rc (js) regression: writing to property of a global variable redefines entire variable type

### ISSUE THREAD

**Issue by brendankenny** [Microsoft/TypeScript#27099]
**TypeScript Versions:**  3.1.0-rc.20180911, 3.1.0-dev.20180914

Not an issue in 3.1.0-dev.20180831 (bisected to #26908)

**Search Terms:**
does not exist global write module

**Code**
```js
// test.js
const INPUT = process.argv;
process.env.ENV_VAR = 'val';

module.exports = INPUT;
```

Run `tsc --noEmit --allowJs --checkJs` with `@types/node` available (see below for a non-node example).

**Expected behavior:**
No error.

**Actual behavior:**
`error TS2339: Property 'argv' does not exist on type 'typeof process'.`

Not a problem in typescript code. When all the example lines are present, the definition and type definition of `process` now point to the `process.env.ENV_VAR` line instead of to `@types/node`.

To get the bug, either `module.exports` needs to be set or a file needs to be required or imported, so I assume it being a module is important. Writing to anything on `process` seems to trigger it, not just a sub-property (so e.g. `process.env = {ENV_VAR: 'val'};` would also trigger the bug, though probably not a good idea in real code :).

**Comment by brendankenny** [comment]
bisecting leads to #26908.

It seems to occur for any globals, e.g.
```js
window.name = '55';
window.console.log(5); // error TS2339: Property 'console' does not exist on type 'typeof window'.

module.exports = 'anything';
```

It looks like issue #27057 may be the same issue, but it's difficult to tell from the description there (I haven't cloned and run the project given in the example).

**Comment by sandersn** [comment]
Notably, doesn't happen in Typescript.

**Comment by sandersn** [comment]
Repros on 3.0 with an expando initializer, like `window.name = {}`. The bug is more visible now that initializers aren't required to be more visible. The core of the problem is in iniitalizeTypeChecker:

```ts
if (!isExternalOrCommonJsModule(file)) {
  mergeSymbolTable(globals, file.locals!);
}
```

CommonJS modules should still merge with globals, because, in JS, the compiler allows undeclared identifiers to act as namespaces in exactly the way assignment to `window` works.
