### ISSUE TITLE
Promise.all doesn't work with TypeScript 2.3.3 and Bluebird but worked in 2.2.2

### ISSUE THREAD

**Issue by zaggino** [Microsoft/TypeScript#16055]
**TypeScript Version:**  2.3.3

**Code**

```ts
/*
package.json
{
  "name": "test",
  "scripts": {
    "init": "tsc --init",
    "build": "tsc"
  },
  "dependencies": {
    "@types/bluebird": "3.5.4",
    "bluebird": "3.5.0",
    "typescript": "2.3.3"
  }
}
tsconfig.json
{
  "compilerOptions": {
    "target": "ES2015",
    "module": "commonjs"
  }
}
*/

import * as Bluebird from 'bluebird';

class Foo {
  bar() {
    return 'foo-bar';
  }
}

function getPromise(): Promise<Foo> {
  return Promise.resolve(new Foo());
}

function getBluebird(): Bluebird<Foo> {
  return Bluebird.resolve(new Foo());
}

async function main() {
  const case1 = await getPromise();
  case1.bar();
  const case2 = await getBluebird();
  case2.bar();
  const [ case3 ] = await Promise.all([ getPromise() ]);
  case3.bar();
  const [ case4 ] = await Promise.all([ getBluebird() ]);
  case4.bar();
}
```

**Expected behavior:**
all cases compile fine

**Actual behavior:**
case4 fails with `Property 'bar' does not exist on type 'Bluebird<Foo>'.` even though case2 passes fine

**note:** changing typescript to `2.2.2` from `2.3.3` fixes the issue so this seems like a bug/breaking change?

```
Zaggi@ZAGGI-PC MINGW64 /d/dev/test
$ npm install && npm run build
test@ D:\dev\test
`-- typescript@2.2.2

npm WARN test@ No description
npm WARN test@ No repository field.
npm WARN test@ No license field.

> test@ build D:\dev\test
> tsc


Zaggi@ZAGGI-PC MINGW64 /d/dev/test
$ npm install && npm run build
test@ D:\dev\test
`-- typescript@2.3.3

npm WARN test@ No description
npm WARN test@ No repository field.
npm WARN test@ No license field.

> test@ build D:\dev\test
> tsc

index.ts(41,9): error TS2339: Property 'bar' does not exist on type 'Bluebird<Foo>'.
```

**Comment by makiJS** [comment]
+1

**Comment by rbuckton** [comment]
This was fixed in the Bluebird definition files starting with `@types/bluebird@3.5.6` and later. I would recommend updating to `@types/bluebird@3.5.14` as that is the most recent version for TypeScript 2.3 and later.
