### PR TITLE
Check for circular constraints in fillMissingTypeArguments (2)

### LINKED ISSUE #28873: typesafe-joi blows up TypeScript 3.2+
**TypeScript Version:**  3.3.0-dev.20181205

**Search Terms:**

Maximum call stack size exceeded

**Code Repo:**

https://github.com/hjkcai/typesafe-joi

**Reproduction:**

```bash
mkdir typesafe-joi-issue && cd typesafe-joi-issue
yarn add typescript@next @types/node typesafe-joi joi
echo '{"compilerOptions":{"strict":true}}' > tsconfig.json
echo 'import * as Joi from "typesafe-joi"; console.log(Joi)' > index.ts
npx tsc -p .
```

**Expected behavior:**

tsc should work. 

I admit that typesafe-joi uses lots of type recursion, but it works fine in TypeScript 3.1. After upgrading to TypeScript 3.2, the error comes.

**Actual behavior:**

tsc itself encountered 'Maximum call stack size exceeded' (No stack trace printed)

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #28873. Supersedes #28971.

### CODE REVIEW

File: tests/baselines/reference/typeArgumentDefaultUsesConstraintOnCircularDefault.errors.txt [hunk 1]
```diff
@@ -15,4 +16,12 @@ tests/cases/compiler/typeArgumentDefaultUsesConstraintOnCircularDefault.ts(5,19)
                       ~~~~~
 !!! error TS2322: Type '{}' is not assignable to type 'string'.
 !!! related TS6500 tests/cases/compiler/typeArgumentDefaultUsesConstraintOnCircularDefault.ts:1:37: The expected type comes from property 'value' which is declared here on type 'Test<string>'
+    
+    // Simplified repro from #28873
+    
+    class C1<T extends C1 = any> {}  // Error, circular constraint
+                       ~~
+!!! error TS2313: Type parameter 'T' has a circular constraint.
```
Comment (weswigham) [inline tests/baselines/reference/typeArgumentDefaultUsesConstraintOnCircularDefault.errors.txt]: Uhhhh. I don't think it's great for us to error here, TBH. That `T` should extend `C1<any>` is pretty clear.

**Comment by ahejlsberg** [comment]
Closing in favor of #29179.
