### ISSUE TITLE
Fail to get contextual type when an index signature exists

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#27949]
**TypeScript Version:**  3.2.0-dev.20181017

**Code**

```ts
interface Options {
    m(x: number): void;
    [key: string]: unknown;
}
declare function f(options: number | Options): void;
f({
    m(x) {},
});
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts:7:7 - error TS7006: Parameter 'x' implicitly has an 'any' type.`

Was introduced by #27849. For some reason it only happens when `options` is a union. Discovered in `jquery` on DefinitelyTyped.
