### ISSUE TITLE
typescript/lib/es5.ts' not found, typescript/lib/dom.ts' not found, es2015.promise' has unsupported extension

### ISSUE THREAD

**Issue by cekvenich** [microsoft/TypeScript#32275]
I compile in node with version 3.5.2 .ts code to .js using the example compiler from here:
https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
passing in options like this:

`
 target: ts.ScriptTarget.ES5,
            allowJs: true,
            skipLibCheck: true,
            lib: [ 
               'dom', 'es5', 'es2015.promise'
            ]
`

and I get a warnings:
typescript/lib/es5.ts' not found, typescript/lib/dom.ts' not found, es2015.promise' has unsupported extension

Bug.

**Comment by AviVahl** [comment]
When using the programmatic api, "lib" contains strings with full file name:
```
lib: ['lib.es2017.d.ts', 'lib.dom.d.ts']

**Comment by cekvenich** [comment]
thx. works. closing.

**Comment by cekvenich** [comment]
Sorry, one more question: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery`.

I do have types/jquery in packages, but I still get above. I would rather not declare in each file. What can I do to remove?

**Comment by j-oliveras** [comment]
Probably you need `moduleResolution` set to `node`.
