### ISSUE TITLE
ObjectLiteralType - Assignment Operator Fails, property type missmatch. Similarly cast fails

### ISSUE THREAD

**Issue by wesleyolis** [Microsoft/TypeScript#24984]
The inferred types for object literals were their properties for "string literal" is string and not object literal string value, is in consistent with explicit typing. Object Literals properties inferred type are of weaker constraint than the explicit type declaration, they should be identical. This also occurs with literal numbers.
```
type CastObjectLiteral = {a :'stringLiteral' }

const value = {a : 'stringLiteral'}

let assignable : CastObjectLiteral;

assignable = value; // This doesn't even work in the @next versions.
/*
error TS2322: Type '{ a: string; }' is not assignable to type 'CastObjectLiteral'.
  Types of property 'a' are incompatible.
    Type 'string' is not assignable to type '"stringLiteral"'.
*/


notCallable(value)  // doesn't work in latest @next versions
/*
test.ts:20:13 - error TS2345: Argument of type '{ a: string; }' is not assignable to parameter of type 'CastObjectLiteral'.
*/

notCallable(value as CastObjectLiteral); // Works in @next, but doesn't work in 2.6.2

assignable = value as CastObjectLiteral;    // Work in @next
assignable = <CastObjectLiteral>value;     // Work in @next

```

**Comment by RyanCavanaugh** [comment]
Please use the issue template, even if this isn't your first bug. It's very helpful for us.

This is the intended behavior because `value.a` is still mutable. The OP doesn't provide a definition for `notCallable` so I'm not sure what the intent of it is.

**Comment by RyanCavanaugh** [comment]
@wesleyolis see #10195
