### ISSUE TITLE
TS 2.1.1 appears to be losing prototype for class extending Array.

### ISSUE THREAD

**Issue by DeegC** [Microsoft/TypeScript#12193]
**TypeScript Version:**  2.1.1

The following Typescript line:

```ts
this.roots = new EntityArray<EntityInstance>( this.rootEntityName(), this, undefined );
```

works fine in 2.0.3 but not in 2.1.1.  After executing the line the prototype for ```this.roots``` should be EntityArray.  In 2.1.1 it is just Array.  See attached screen shots below.  This is causing a problem because a few lines later I call a method defined in EntityArray but I get an error saying the function does not exist:

```ts
this.roots.create(initialize, options);
```

Produces: "this.roots.create is not a function..."

I wasn't able to recreate the error using the playground so I created two branches in my project, one for files generated with 2.0.3 and one generated with 2.1.1.  The pertinent file is zeidon.js:

https://github.com/DeegC/UTC/blob/typescript-2.0.3/angular/app/zeidon.js
https://github.com/DeegC/UTC/blob/typescript-2.1.1/angular/app/zeidon.js

There aren't that many differences in the generated .js file so I'm guessing the problem is in how the constructor for EntityArray is generated.  Here's the diff for just the constructor:

``` var EntityArray = (function (_super) {
     __extends(EntityArray, _super);
     function EntityArray(entityName, oi, parentEi) {
-        _super.call(this);
-        this.currentlySelected = 0;
-        this.entityName = entityName;
-        this.oi = oi;
-        this.parentEi = parentEi;
+        var _this = _super.call(this) || this;
+        _this.currentlySelected = 0;
+        _this.entityName = entityName;
+        _this.oi = oi;
+        _this.parentEi = parentEi;
+        return _this;
     }
```

If necessary I can give instructions for running my app.  Let me know if you need any more info.

## 2.0.3:
![typescript2 0 3](https://cloud.githubusercontent.com/assets/1933757/20235849/ccd9703c-a86c-11e6-92d5-1a5705757052.png)

## 2.1.1:
![typescript2 1 1](https://cloud.githubusercontent.com/assets/1933757/20235848/ccd77e58-a86c-11e6-9e7c-74ebaeccb82b.png)

**Comment by aluanhaddad** [comment]
Duplicate of #11919

**Comment by mhegazy** [comment]
Please see https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work for extending built ins.
