### ISSUE TITLE
TS2.9 narrows `{}|undefined` to never after string checks (regression from 2.8)

### ISSUE THREAD

**Issue by mprobst** [microsoft/TypeScript#25179]
**TypeScript Version:**  2.9.2

**Search Terms:** string never undefined jQuery

**Code**

```ts
declare const childSelector: {}|undefined;
declare const elem: HTMLElement;
if (typeof childSelector === 'string') {
  // childSelector is never (bug?)
  const childElement: HTMLElement|null = elem.querySelector(childSelector);
  // childElement is now null
  if (!childElement) {
    throw new Error('...');
  }
  // childElement is now never
  childElement.addEventListener('click', () => 1);
}
```

**Expected behavior:**

TypeScript understands that `childSelector` must be `string` in the block. This is what TS 2.8 did.

**Actual behavior:**

TypeScript infers `childSelector` to be never, then outsmarts the user's type annotation of `HTMLElement|null` to be just `null`, then deducts that in the last line, it must be never.

**Playground Link:** http://www.typescriptlang.org/play/#src=declare%20const%20childSelector%3A%20%7B%7D%7Cundefined%3B%0D%0Adeclare%20const%20elem%3A%20HTMLElement%3B%0D%0Aif%20(typeof%20childSelector%20%3D%3D%3D%20'string')%20%7B%0D%0A%20%20%2F%2F%20childSelector%20is%20never%20(bug%3F)%0D%0A%20%20const%20childElement%3A%20HTMLElement%7Cnull%20%3D%20elem.querySelector(childSelector)%3B%0D%0A%20%20%2F%2F%20childElement%20is%20now%20null%0D%0A%20%20if%20(!childElement)%20%7B%0D%0A%20%20%20%20throw%20new%20Error('...')%3B%0D%0A%20%20%7D%0D%0A%20%20%2F%2F%20childElement%20is%20now%20never%0D%0A%20%20childElement.addEventListener('click'%2C%20()%20%3D%3E%201)%3B%0D%0A%7D

**Comment by andy-ms** [comment]
The real problem is narrowing `childSelector` to never. If you just take `function f(childElement: HTMLElement|null) { ... }` the rest of the code works.

So the bug is basically:
```ts
function stringify(anything: {} | undefined): string {
    return typeof anything === "string" ? anything.toUpperCase() : "";
}
```

**Comment by weswigham** [comment]
@mhegazy did we want to change our narrowing behavior? `typeof` doesn't narrow to subtypes right now - it just picks relevant union members. I could also say
```ts
function stringify(anything: { toString(): string } | undefined): string {
    return typeof anything === "string" ? anything.toUpperCase() : ""; // Property 'toUpperCase' does not exist on type 'never'.
}
```
and expect narrowing to work, but today it will not.

**Comment by mhegazy** [comment]
So what changed since 2.8?

**Comment by weswigham** [comment]
AFAIK it didn't work in 2.8.

![image](https://user-images.githubusercontent.com/2932786/41936732-048af214-7943-11e8-85e1-bf0b6ebd9bb7.png)

And looking at the git blame, it's work like this since at least 1.8.

**Comment by mprobst** [comment]
I haven't looked again, but this code (at least in the longer version
above) compiled in our code base with 2.8, but fails with 2.9.

**Comment by weswigham** [comment]
Was `strictNullChecks` only enabled with 2.9? That'd cause the discrepancy.

**Comment by mprobst** [comment]
No, we had strictNullChecks enabled since before 2.7.
