### PR TITLE
Correctly narrow unconstrained type parameters

### LINKED ISSUE #9618: Control flow type analysis error with type parameter
**TypeScript Version:**  2.0.0 (typescript@beta)

**Code**

```ts
// test.ts
function test<T>(data: string | T) {
  if (typeof data === 'string') {
    return JSON.parse(data);
  } else {
    return data;
  }
}
```

**Expected behavior:**
Compile without error

**Actual behavior:** 
`test.ts(4,23): error TS2345: Argument of type 'string | T' is not assignable to parameter of type 'string'.
  Type 'T' is not assignable to type 'string'.`

Works fine in typescript@1.8.10 and earlier

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #9618

This makes sure that a union type that includes a type parameter is still usable as the actual type that the type guard narrows to.

@RyanCavanaugh @weswigham this fix works, but I don't feel like I could adequately explain why it's a good idea, much less as a comment in the code. Can you take a look and propose some better explanation than the two-line comment?

### CODE REVIEW

**Comment by sandersn** [comment]
After sleeping on it, here's a decent explanation for this example:

```ts
function parsesForSure(data: string | T): T {
  if (typeof data === 'string') {
    return JSON.parse(data);
  }
  else {
    return data;
  }
}
```

Currently, `data` in the true branch has the type `string | T` even though the user clearly wants just `string`. However, it turns out `T` is technically correct in the first branch: what if `T='literal type'` or `T=Path=string & { _brand }`? So `T` should stay, but we want to express the idea that, in the true branch, `T` has to be a subclass of string.

In other words, the type guard asserts that `data` is at least `string`, even if it happens to be T (a subclass). So the fix is to intersect string | T with string & T to get (string | T) & string & T. This ensures that all members from all types that pass the type guard are available in the body of the if.

An alternate fix would make a new type parameter with a constraint, `T extends string`. But this is inconvenient and means almost the same thing as `T & string` in this context.

Note that this intersection is only needed in the true branch. In the false branch, we just remove concrete types, and for type variables we should theoretically use the type subtraction operator ... which doesn't exist yet. If it did, the type for `data` in `typeof data !== 'string'` would look something like  `T - string`.

**Comment by sandersn** [comment]
@ahejlsberg I got rid of the intersection code and just use the emptyObjectType facts. Can you take a look?

**Comment by ahejlsberg** [comment]
:+1:
