### ISSUE TITLE
4.7 circular type annotation regression

### ISSUE THREAD

**Issue by DavidRigglemanININ** [microsoft/TypeScript#50688]
# Bug Report

### 🔎 Search Terms

"Return type annotation circularly references itself"

### 🕗 Version & Regression Information

The code works in 4.6.4 and stopped working when attempting to upgrade to 4.7+. I also verified the issue still appears in 4.8.X

- This changed between versions 4.6.4 and 4.7

### ⏯ Playground Link

https://github.com/davidmdm/myzod

Issue has been reported with https://github.com/davidmdm/myzod/issues/52

Note that I am not the author of the linked library but rather a user. The author appears to be busy at the moment, so I was creating this ticket to see if the problem was a potential regression on the TypeScript side that could be fixed here instead if that is indeed the root cause.

### 💻 Code

https://github.com/davidmdm/myzod/blob/master/src/types.ts

### 🙁 Actual behavior

The code fails with the following errors

```
node_modules/myzod/libs/types.d.ts:256:40 - error TS2577: Return type annotation circularly references itself.

256     and<K extends AnyType>(schema: K): IntersectionResult<this, K>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/myzod/libs/types.d.ts:306:40 - error TS2577: Return type annotation circularly references itself.

306     and<K extends AnyType>(schema: K): IntersectionResult<this, K>;
```

### 🙂 Expected behavior

The code compiles successfully.

**Comment by andrewbranch** [comment]
It looks pretty circular to me. These types are too big and complex for us to investigate a root cause. If you can produce a small, standalone reproduction and convince yourself it should work, we can take a look. But definitely the library author is going to be in the best position to untangle this; sorry 😕

**Comment by Fireboltofdeath** [comment]
> It looks pretty circular to me. These types are too big and complex for us to investigate a root cause. If you can produce a small, standalone reproduction and convince yourself it should work, we can take a look. But definitely the library author is going to be in the best position to untangle this; sorry 😕

I believe I have a small repro for this issue as I encountered an identical situation. This works fine before 4.7 but after 4.7 it causes a circularity error. It appears to only cause an error whenever you use a conditional type on a constrained type parameter.

I'm not sure whether a circularity error is the desired behavior here but I believe I was able to narrow the regression to https://github.com/microsoft/TypeScript/pull/31455

[Playground](https://www.typescriptlang.org/play?ts=4.7.4#code/KYDwDg9gTgLgBAbwL4ChSVnAlgOxsKAMwEMBjYOAeTBiwhwB4AVAPkRQEgAvLMARgaU4ofDgAmAZzgBBKFGIBPQTTqNiOBSy0AKAHT6IMABYEJALioBKC9Vr0GAbSYAaOPt0BVHDzC3Vs+QUBShYAXRYAbhROHwAmQWEQUUkZOUVlOzUNLRY9A2NTG2sqFXsnV3cvHz96AMV4kPComN4AZgSRYHEpOqUarM0dd0MTKHMrG1LGcrd9Kt5+3vbGyJRUFBgFMAp53ynmNgBeOCZE5Kl+hlxCAjgANTYAfnu4CxxgADcCZoB6P5OjFgpGIIMAJDgAOTwADu0AA1hstjtvAspr0BKw4McEHAHHDsDg4HDgAoIIQTqELEw8aEzl0Upd1Jo4M9dpdqXDwq84O8vlA4Ehfv8AEIAV3gBQkFFhUARm22cDZaLSCnimOxuPxuCJJLJFIsSsyzBpbEFiIVhv8Kva6sQmoJOtJ5KYlJONLp3RKRuutweLJeb0+tzNKDEwFIABtiFAKKR6BJ4BAaHxJkacKKALYAIwIqzDkejsfjiZosVTqgYCaguAA5nnw1GY3A4zgE3AkzBWuX7FmIBAI8B1KsUC22z5tmI+Fj28ndD4+NoO7FXB3WpYoqP4OPgGJYtOO3w57xYovSyuaGuN8W4NuxK197OfK1TzBlzPO+uUEA)

**Comment by andrewbranch** [comment]
For @typescript-bot:

```ts repro
export {}
export interface Option<T> {
	zip1<O extends Array<Option<any>>>(...others: O): Option<[T, ...UnzipOptionArray1<O>]>;

	zip2<O extends Array<Option<any>>>(...others: O): Option<[T, ...UnzipOptionArray2<O>]>;

	zip3<O extends Array<Option<any>>>(...others: O): Option<[T, ...UnzipOptionArray3<O>]>;
}

type UnzipOption<T> = T extends Option<infer V> ? V : never;

/// This doesn't work
type UnzipOptionArray1<T> = { [k in keyof T]: T[k] extends Option<any> ? UnzipOption<T[k]> : never };

/// But these work
type UnzipOptionArray2<T> = { [k in keyof T]: UnzipOption<T[k]> };
type UnzipOptionArray3<T> = { [k in keyof T]: T[k] extends Option<infer V> ? V : never };

declare const opt1: Option<number>;
declare const opt2: Option<string>;
declare const opt3: Option<boolean>;

const zipped1 = opt1.zip1(opt2, opt3);
const zipped2 = opt1.zip2(opt2, opt3);
const zipped3 = opt1.zip3(opt2, opt3);
```

**Comment by andrewbranch** [comment]
@typescript-bot agrees. Thank you @Fireboltofdeath!

**Comment by DavidRigglemanININ** [comment]
So unfortunately, trying out 4.9.4, while this error no longer appears, I do get this error that did not exist prior to 4.7: "error TS2589: Type instantiation is excessively deep and possibly infinite." Is this another regression or is there a way to work around this?

**Comment by Nicolas469** [comment]
In the meantime, could we add something like
// @ts-ignore
to allow the build to succeed ?
