### ISSUE TITLE
typescript-for-nodejs-in-5-minutes.html

### ISSUE THREAD

**Issue by oskude** [microsoft/TypeScript#27220]
would be nice to have a typescript-for-nodejs-in-5-minutes.html, like https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html but for nodejs.

i dont know what im doing, but tried the following:

mod.ts
```
class Mod {
	hello (wat: string) {
		return "hello " + wat;
	}
}
module.exports = Mod;
```

main.ts
```
const Mod = require("./mod");
const mod = new Mod();
console.log(mod.hello(42));
```

did a typescript 3.0.3 dance (with tips from random sites)
```
❯ npm install typescript
❯ npm install @types/node
❯ ./node_modules/.bin/tsc --lib es2018 --module commonjs --target es2018 main.ts mod.ts
main.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Mod'.

1 const Mod = require("./mod");
        ~~~

  mod.ts:1:7
    1 class Mod {
            ~~~
    'Mod' was also declared here.

mod.ts:1:7 - error TS2451: Cannot redeclare block-scoped variable 'Mod'.

1 class Mod {
        ~~~

  main.ts:1:7
    1 const Mod = require("./mod");
            ~~~
    'Mod' was also declared here.
```

and tsc created a mod.js
```
class Mod {
    hello(wat) {
        return "hello " + wat;
    }
}
module.exports = Mod;
```

and main.js:
```
const Mod = require("./mod");
const mod = new Mod();
console.log(mod.hello(42));
```

and both work in nodejs v10.10.0:
```
❯ node main.js 
hello 42
```

now i wonder:

- why do i get tsc error TS2451?
- why dont i get tsc error TS2451 in nodejs?
- why dont i get tsc error for `mod.hello(42)`?
- why does tsc create the js file(s) even if there are errors?
- do/can we have `tsc` default values for nodejs javascript? (so we users dont have to look them up, nor update. something like `tsc --nodejs` and `tsc --nodejs-lts`)
- can/could we simply do `tsc main.ts` and tsc figures out the rest? (like nodejs does)
- what else am i doing wrong?

cheers.

**Comment by AlCalzone** [comment]
Use export and import, so your files are treated as modules:
```
// mod.ts
export class Mod {
	hello (wat: string) {
		return "hello " + wat;
	}
}

// main.ts

import { Mod } from "./mod";
const mod = new Mod();
console.log(mod.hello(42));
```
