### ISSUE TITLE
Incompatible change in indexer type inference

### ISSUE THREAD

**Issue by csnover** [Microsoft/TypeScript#1655]
Value type of indexers is ending up now as `undefined` when implicitly created from another type on the RHS as in the following test case:

```ts
var bar:{ [key:string]: boolean; };
var foo = bar = {};
foo['a'] = true; // error TS2323: Type 'boolean' is not assignable to type 'undefined'.
```

**1.3: OK**
**master: Error on line 3**

Bisect:

```
83d9aed005502523ac3ef7198d92c51c8f2bb211 is the first bad commit
commit 83d9aed005502523ac3ef7198d92c51c8f2bb211
Author: Anders Hejlsberg <andersh@microsoft.com>
Date:   Mon Oct 13 06:56:15 2014 -0700

    Correct contextual typing with union types

:040000 040000 d3d0d2e65cdd5b895f2bf257e6256dad815be97c a93480ba990a856a4f585a4d57c80a0f533c087f M	src
```

Also please let me know which of my terminology is horribly broken in this description so I can be more precise in the future :)

**Comment by DanielRosenwasser** [comment]
I think I've found the "offending" line: https://github.com/Microsoft/TypeScript/commit/83d9aed005502523ac3ef7198d92c51c8f2bb211#diff-c3ed224e4daa84352f7f1abcd23e8ccaR4717

If you change your example to the following, you'll get no error:

```TypeScript
var bar:{ [key:string]: boolean; };
var foo = bar = { hello: true};
foo['a'] = true;
```

Which is *very* weird, because I don't actually think (or to be frank, entirely know) if that is actually a *problem*.

I think the real issue is the following in `checkBinaryExpression`:

```TypeScript
case SyntaxKind.EqualsToken:
    checkAssignmentOperator(rightType);
    return rightType;
```

Shouldn't this return the left side?

**Comment by RyanCavanaugh** [comment]
Interesting bug; discussed with @JsonFreeman and @jonathandturner.

Usually the type of a contextually-typed expression is not *observable*, i.e. in all other cases but assignment expressions, the type of a contextually-typed expression is immediately used in an assignment compatibility check and is never the source of an inference. Assignment expressions are a sort of "naked singularity" where it's possible to directly observe a type formed from contextual typing.

There is an actual bug relative to spec here because the index signature should have been widened. That would 'fix' the post example, but add an implicit `any` in `foo` and thus still be a breaking change.

One option, maybe, is to change the spec language `or the Undefined type if the object literal is empty` to `or the index signature type if the object literal is empty`. I'm not sure if there would be unintended impact from that.

The more invasive change would be to somehow change assignment expressions to produce more intuitive types. Consider code like this:
```ts
interface Foo {
	bar?: number;
}

var x: Foo;
var y = x = {}; // Expected y: Foo, probably (?)
console.log(y.bar); // Error, 'bar' is not in {}

var z = x = { qua: 10 }; // Expected z: { qua: number; bar?: number } (??)
console.log(z.qua); // Currently not an error; no error desired
```

**Comment by JsonFreeman** [comment]
Regarding @RyanCavanaugh's point:
"the type of a contextually-typed expression is immediately used in an assignment compatibility check and is never the source of an inference".

This is mostly true right now, but in type argument inference, we do contextually (inferentially) type an expression, and then infer from it. Namely:

```ts
function foo<T>(x: { [s: string]: T }): T {}
foo({ x: true });
```

Here, we have an indexer of type boolean, which results from contextually typing the object literal, and then inferring from that. So this would need to continue to work as well.

I will also add that imbuing the right hand side expression with contextual information from the left hand side never felt like modeling anything natural. In my mind, it was a trick where we abused contextual typing to get something to be assignable. That's why we got rid of parts of it when we added union types. The only thing contextual typing seems to accurately model is the typing of function expression parameters, because there truly is a piece of data (the parameter) flowing from the left type into the right type.

If we *do* go back to the model where contextual typing "fills in the gaps" between the target type and the source type, we might also consider doing this for optional properties. For example:
```ts
var x: { p? }
var y = x = {};
y.p; // now an error, but maybe should not be
```

**Comment by jonathandturner** [comment]
Adding @ahejlsberg so that he can weigh in.

**Comment by JsonFreeman** [comment]
@csnover I have an idea for this bug. The problem now is that the type of foo is getting poisoned with the indexer from bar. I can try to make foo have the type `{}`, which will not prohibit you from indexing into it. Is this sufficient for you, or do you need foo to actually have the indexer?

**Comment by csnover** [comment]
I can just explicitly put a type on the variable declaration in the code, so the new behaviour isn’t a big deal from a usability perspective. This only showed up in one place, it’s not a pattern we’re really using, but since it is a breaking change I did report it.

I admit I don’t 100% understand the discussion of the underlying cause of the defect to be able to say anything authoritative. In my mind, assignment operator associativity in JS is right-to-left, so the original test case ought to be equivalent to this code, which does work in 1.4:

```ts
var bar:{ [key:string]: boolean; } = {};
var foo = bar;
foo['a'] = true; // works
```

The only other option I think makes any sense is for `foo` to become implicit any as mentioned before, but this would of course also be a breaking change (just less conceptually broken in my mind).

**Comment by JsonFreeman** [comment]
It is a subtle problem, I agree. The problem with treating it like `var foo = bar` is per @RyanCavanaugh's point above. In his example, you'd want to be able to access z.qua, which you could not do if you made z have the same type as x.

**Comment by JsonFreeman** [comment]
But I'm glad to hear it is not a blocking issue.

**Comment by JsonFreeman** [comment]
@csnover, to explain my fix a little more concretely, in the following
```ts
var bar: { [key:string]: boolean; };
var foo = bar = {};
```
foo would get the same type as it would in
```ts
var bar: { [key:string]: boolean; } = {};
var foo = {};
```
It is just like your intuition, except that instead of bar getting assigned to foo, the object literal gets assigned to foo.

**Comment by JsonFreeman** [comment]
@ahejlsberg and I have discussed a fix for #1446 that I believe would fix this issue as well. It would cause foo to have an indexer of type 'any'.

**Comment by DanielRosenwasser** [comment]
What exactly was the fix that we went with here? There doesn't appear to be a spec change, and I'm not clear what #1795 did to fix anything.

**Comment by JsonFreeman** [comment]
I think the fix to the present bug was a side effect of #1795. Specifically, in this bug, the object literal on the left had an indexer of type undefined. #1795 included changes to widening, which now causes the undefined to be widened to an any, thereby removing the error in this bug. The failure to widen was actually an implementation bug, and not a design change, so there would be no spec impact for that aspect of the PR.
