### ISSUE TITLE
Module Augmentation fails when exports are declared in an ExportClause

### ISSUE THREAD

**Issue by EvanCahill** [Microsoft/TypeScript#8427]
**TypeScript Version:**

nightly (1.9.0-dev.20160502)

**Code**

```ts
// ext1.d.ts
declare module "State" {
    interface IState {
        num: number;
    }
    export { IState };
}

// ext2.d.ts
declare module "State" {
    interface IState {
        str: string;
    }
    export { IState };
}

//app.ts
import { IState } from "State";

function test(state: IState): void {
    console.log(state.num);
    console.log(state.str);
}

// tsconfig.json
{
    "files": [
        "app.ts",
        "ext1.d.ts",
        "ext2.d.ts"
    ]
}
```

**Expected behavior:**
The "State" module and IState interface declarations should be merged and the code should compile without errors.

**Actual behavior:**
The declaration files report error `TS2300: Duplicate identifier 'IState'`

**Workaround:**
The above errors do not occur when both IState interfaces are exported inline using the export modifier instead of in a ExportClause.
NOTE: If the first is exported inline and the second is exported in an ExportClause then the second declaration errors with `TS2482: Export declaration conflicts with exported declaration of 'IState'`.

**Comment by mhegazy** [comment]
The behavior is what i would expect. the error message could be better.

also note, you do not need the `export` modifier. all declarations are implicitly exported in an ambient context. so this is is semantically equivalent to your sample:
```ts
// ext2.d.ts
declare module "State" {
    interface IState {
        str: string;
    }
}
```

**Comment by EvanCahill** [comment]
If the two are semantically equivalent then why does the the former producer errors while the later does not? That is, if both interface declarations omit the export and are implicitly exported instead then the code compiles.

With regards to the use of the `export` keyword I included it as that is how the declarations are generated by the compiler when compiling with `--module system|amd`, `--outFile` and `--declaration`. For a little more context on the problem I have 3 projects all setup with the above compiler options. The first two projects both have a State.ts file which declare the IState interface. The third project consumes the other two. If I export the IState interface in both places using an inline export then everything compiles and works as desired. If instead I export them in an ExportClause then I get the duplicate identifier errors.

**Comment by deni35** [comment]
It seems I also stumbled on this problem.

```
import gulp = require("gulp"); // import declaration conflicts with local declaration of gulp

gulp["devTask"] = function () {
    if (process.env.NODE_ENV !== 'production') return gulp.task.apply(this, arguments);
}

module gulp {
    interface Gulp {
        devTask(name: string): void;
    }
}
```

I don't understand is this error a bug or not?
If not, why I can merge interfaces in my modules, but can't merge with not mine module? 
What does ```Domain: Error Messages``` mean? As I understand you just want to replace error text?

**Comment by mhegazy** [comment]
looking at this again, this is the same issue as https://github.com/Microsoft/TypeScript/issues/8140.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/8140.

**Comment by deni35** [comment]
All the same I don't understand. Should it work or not?
Now I changed variable name:

```
import _gulp = require("gulp");

_gulp["devTask"] = function () {
    if (process.env.NODE_ENV !== 'production') return _gulp.task.apply(this, arguments);
}

declare module gulp {
    interface Gulp {
        devTask(name: string): void;
    }
}
```
Now there is no errors, but _gulp still hasn't my function.

**Comment by mhegazy** [comment]
> All the same I don't understand. Should it work or not?

I think it should not work, and it should be an error. currently it is not an error, but it does not work as expected.


> Now there is no errors, but _gulp still hasn't my function.

you should use module augmentation instead:

```ts
import gulp = require("gulp");

// augment the module
declare module "gulp" {
    interface Gulp {
        devTask(name: string): void;
    }
}

gulp.devTask = function () {
    if (process.env.NODE_ENV !== 'production') return gulp.task.apply(this, arguments);
}
```

**Comment by deni35** [comment]
You code throws error.
`declare module "gulp" {   // duplicate identifier ' "gulp" '`

**Comment by mhegazy** [comment]
what version of TS are you using?

**Comment by deni35** [comment]
Typescript for Microsoft Visual Studio 1.8.29.0.

**Comment by mhegazy** [comment]
looks like you are running into #7545, which has been fixed after 1.8.

**Comment by deni35** [comment]
What is current version?
At npm I see 1.8.10. At this repository I see 1.9.0.
Here is https://www.microsoft.com/en-us/download/details.aspx?id=48593 at all version 1.8.6.0 (But my currently installed 1.8.29.0).

**Comment by mhegazy** [comment]
`tsc --v`

What is available currently is the nightly builds (`npm install typescript@next`).

**Comment by deni35** [comment]
> tsc --v
I mean something kind of 
`console.log( TypeScript.version );`
Because I'm not sure what VS is using.

Ok, I installed typescript@next. And read this https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio 
Do I really must to edit the registry? Why not make just TS path option in Visual Studio?

**Comment by mhegazy** [comment]
VS stores options in the registry as well :)

**Comment by MoonStorm** [comment]
Still a problem in 2.0.3, using the compiler from the command line. In my case, I'm trying to augment the ``Observable`` class. Ironic, since this is exactly the example in the guide. 

The difference is that the ``Observable`` is available through ``rxjs``
```
import {Observable} from 'rxjs'

declare module 'rxjs' {
    interface Observable<T> {
        intercept():void;
    }
}
```

**Comment by shaunluttin** [comment]
We're seeing a similar error. After doing `npm install ag-grid --save`, we tried to augment the module as follows. 

```
// augmentation.d.ts
import agGrid = require("ag-grid");

declare module "ag-grid" {
    interface ColDef {
        str: string;
    }
}
```

On build with `tsc 2.4.1` we see the following error: 

> node_modules/ag-grid/main.d.ts(135,10): error TS2484: Export declaration conflicts with exported declaration of 'ColDef'.
