### ISSUE TITLE
3.5.1 (regression): "string cannot be used to index T" where T is Record<string, any>

### ISSUE THREAD

**Issue by lll000111** [microsoft/TypeScript#31661]
This is new as of 3.5.1, there was no error in 3.4.5.

Error message: 

```
TS2536: Type 'string' cannot be used to index type 'T'
```

Obviously wrong, since `T` is defined as `Record<string, any>`.

```js
function isString (thing: unknown): thing is string {
    return typeof thing === 'string';
}

function clone<T extends Record<string, any>>(obj: T): T {
    const objectClone = {} as T;

    for (const prop of Reflect.ownKeys(obj).filter(isString)) {
        objectClone[prop] = obj[prop];
    }

    return objectClone;
}
```

[Playground Link](http://www.typescriptlang.org/play/index.html#src=function%20isString%20(thing%3A%20unknown)%3A%20thing%20is%20string%20%7B%0D%0A%20%20%20%20return%20typeof%20thing%20%3D%3D%3D%20'string'%3B%0D%0A%7D%0D%0A%0D%0Afunction%20clone%3CT%20extends%20Record%3Cstring%2C%20any%3E%3E(obj%3A%20T)%3A%20T%20%7B%0D%0A%20%20%20%20const%20objectClone%20%3D%20%7B%7D%20as%20T%3B%0D%0A%0D%0A%20%20%20%20for%20(const%20prop%20of%20Reflect.ownKeys(obj).filter(isString))%20%7B%0D%0A%20%20%20%20%20%20%20%20objectClone%5Bprop%5D%20%3D%20obj%5Bprop%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20objectClone%3B%0D%0A%7D%0D%0A) &mdash; It will not show an error until the Playground uses the new TS 3.5.x

![Unbenannt-1](https://user-images.githubusercontent.com/25476357/58584348-61bbb280-8256-11e9-8238-36bd6972628d.png)

**Comment by felix9** [comment]
Here's a similar case I ran into:
```typescript
interface Bag {
  [key: string]: number;
}

function put<T extends Bag>(a: T, k: string, v: number): void {
  a[k] = v;
}
```

Compiling that produces this:

```
$ tsc test.ts
test.ts:6:3 - error TS2536: Type 'string' cannot be used to index type 'T'.

6   a[k] = v;
    ~~~~

Found 1 error.
```

**Comment by RyanCavanaugh** [comment]
This is the intended behavior but I need to write several pages of documentation for "How do index signatures in generic constraints work [if at all]"

**Comment by felix9** [comment]
Confusingly, this will compile without error (though `--noImplicitAny` will complain):
```typescript
interface Bag {
  [key: number]: boolean;
}
function put<T extends Bag>(a: T) {
  a["x"] = "y";
}
```

**Comment by ahejlsberg** [comment]
This is an effect of #30769 and a known breaking change. We previously allowed crazy stuff like this with no errors:

```ts
function foo<T extends Record<string, any>>(obj: T) {
    obj["s"] = 123;
    obj["n"] = "hello";
}

let z = { n: 1, s: "abc" };
foo(z);
foo([1, 2, 3]);
foo(new Error("wat"));
```

In general, the constraint `Record<string, XXX>` doesn't actually ensure that the caller has a string index signature, it merely ensures that the properties of the argument are assignable to type `XXX`. So, in the example above you could effectively pass *any* object and the function could write to *any* property without *any* checks.

In 3.5 we enforce that you can only write to an index signature element when we *know* that the object in question has an index signature. So, you need a small change to the `clone` function:

```ts
function clone<T extends Record<string, any>>(obj: T): T {
    const objectClone = {} as Record<string, any>;

    for (const prop of Reflect.ownKeys(obj).filter(isString)) {
        objectClone[prop] = obj[prop];
    }

    return objectClone as T;
}
```

With this change we now know that `objectClone` has a string index signature.

**Comment by felix9** [comment]
I'm still a little confused by that explanation. Given this dubious bit of code, in both `--strict` and non-strict mode, the only complaint is the `baggish["z"] = 3` line. I'm not sure why that line in particular gets to be the fatal error, and the only fatal error?

```typescript
interface Bag {
  [k: string]: number;
}

function put1(bag: Bag) {
  bag["z"] = 3;
}

function put2<T extends Bag>(baggish: T) {
  baggish["z"] = 3;
}

const bag: Bag = {};
put1(bag);
put2(bag);

type Point = {x: number};
const point = {x: 3};
put1(point);
put2(point);

**Comment by lll000111** [comment]
> In general, the constraint Record<string, XXX> doesn't actually ensure that an argument has a string index signature, it merely ensures that the properties of the argument are assignable to type XXX.

I don't accept this "explanation".

Why is there even a place for the key type in `Record<keyType, valueType` if it has no meaning???

**Comment by lll000111** [comment]
Also: Why would it EVER complain &mdash; in Javasdcript! &mdash; if I use a string as index in an object? By using `Record` I already told TS that it is meant to be a generic map object. The explanation does not make sense.

In general, coming from (the more strict!) Flow, all those many errors I now have in TypeScript when I iterate over my objects (using Object.keys) that "there is no index signature" are really, really... strange.

**Comment by patroza** [comment]
Not sure if this helps the case: `const typedKeysOf = <T>(obj: T) => Object.keys(obj) as Array<keyof T>`

**Comment by lll000111** [comment]
@patroza If that helps, and maybe in general anyway (I have not thought about wider implications), what if `Object.keys` and `Reflect.ownKeys` were declared that way (TS standard lib), instead of as `Array<string | number | symbol>` ?

As an experiment I changed the definition in lib.es2015.refelect.d.ts 

from (`PropertyKey` is `string | number | symbol`)

```js
function ownKeys(target: object): PropertyKey[];
```

to

```js
function ownKeys<T extends object>(target: T): Array<keyof T>;
```

and everything is PERFECT now!

So maybe the underlying TS-lib definition can be looked and any maybe changed?

**Comment by patroza** [comment]
@lll000111 yea I was also surprised that the standard library didn't implement it this way at least for `Object.keys`, but I suppose it may have backwards incompatibility implications.

**Comment by ahejlsberg** [comment]
@patroza For the reason `Object.keys` isn't typed as `(keyof T)[]`, see https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208.

**Comment by patroza** [comment]
@ahejlsberg makes sense, thanks for shedding light on it. We can constrain it ourselves with for example the helper I posted, when we need it. That's good enough for me.

**Comment by ahejlsberg** [comment]
@felix9 The distinction becomes evident when you consider both input (parameter) and output (function result) positions. Imagine that `put1` and `put2` returned the object passed to them:

```ts
function put1(bag: Bag): Bag {
  bag["z"] = 3;
  return bag;
}

function put2<T extends Bag>(baggish: T): T {
  baggish["z"] = 3;  // Error
  return baggish;
}

const p1: Point = put1({ x: 3 });  // Error
const p2: Point = put2({ x: 3 });
```

Following a call to `put1` you now have a `Bag` and `Bag` is not assignable to `Point`. And because the argument has been promoted to `Bag`, the function is permitted to write to any property.

However, following a call to `put2` you still have a `Point`. So, the type checker needs to restrict the function to only allow writing to properties that are *known* to exist in `T`. In other words, it should only allow assignments to `T[K]` where `K` is a `keyof T` or something constrained to `keyof T`. In effect, constraining a type parameter to `Bag` merely checks that `T` *is assignable* to `Bag`, but it doesn't imply that `T` *is* a `Bag`.

**Comment by bajtos** [comment]
(1)
> In effect, constraining a type parameter to `Bag` merely checks that `T` _is assignable_ to Bag, but it doesn't imply that `T` _is a_ Bag.

Here is the part I find highly confusing:
- when I write `class Foo extends Bag`, it means `Foo` _is_ a `Bag`
- when I write `function put<Foo extends Bag>`, it DOES NOT mean that `Foo` _is_ a `Bag`

As I am reading the discussion above, it seems to me that `{x: 3}` should not be assignable to `Bag` type, because it does not have any indexer property to satisfy the `Bag` interface.

If that was the case, the the example `put2({x: 3})` above would trigger a compilation error.

(2)
Now going back to `foo` example:

```ts
function foo<T extends Record<string, any>>(obj: T) {
    obj["s"] = 123;
    obj["n"] = "hello";
}
```

IMO, the code above is valid in the sense that it's ok to assign to `s` and `n` properties, because `Record<string, any>` does allow that. What I don't consider as correct is to call `foo` with such `obj` value that does not have indexer property mapping arbitrary key to `any` value.

I think a more correct definition of `foo` would say that the Record type has only keys of `T`, something along the following lines:

```ts
function foo<T extends Record<keyof T, any>>(obj: T) {
    obj["s"] = 123;
    obj["n"] = "hello";
}
```

Such code is triggering the following error for me: `Element implicitly has an 'any' type because type 'Record<keyof T, any>' has no index signature.ts(7017)`, which is a good sign that we are doing something wrong here. Personally, I would expect a different error - `Property 's' does not exist on type 'T'`.

Because `foo` wants to work with `s` and `n` properties, I think it should list them in the Record template arguments.

```ts
function foo<T extends Record<keyof T | 's' | 'n', any>>(obj: T) {
    obj["s"] = 123;
    obj["n"] = "hello";
}
```

That way the compiler can verify:
- inside `foo` that we are accessing only those `obj` properties that exist on `T`
- code calling `foo` provides `obj` value that allows `s` and `n` properties

(3)
When I think about the `clone` function mentioned earlier in the discussion, I would rewrite it as follows:

```ts
function clone<T extends Record<keyof T, any>>(obj: T): T {
  const objectClone = {} as T;

  const ownKeys = Reflect.ownKeys(obj) as (keyof T)[];
  for (const prop of ownKeys.filter(isString)) {
    objectClone[prop] = obj[prop];
  }

  return objectClone;
}
```

This seems to work with TypeScript v3.5, although I am surprised that `Reflect.ownKeys` is returning `string[]` instead of `(keyof T)[]`.

Thoughts?

**Comment by ahejlsberg** [comment]
> As I am reading the discussion above, it seems to me that {x: 3} should not be assignable to Bag type, because it does not have any indexer property to satisfy the Bag interface.

That would one way to do it. However, it is very common to initialize map-like objects using object literals, and for an object literal we know the exact set of properties from which to compute an implicit index signature. So we permit the assignment for types originating in object literals.

> When I think about the clone function mentioned earlier in the discussion, I would rewrite it as follows

I'd write it like this:

```ts
function clone<T extends object>(obj: T): T {
  const objectClone = {} as T;
  const ownKeys = Reflect.ownKeys(obj) as (keyof T)[];
  for (const prop of ownKeys) {
    objectClone[prop] = obj[prop];
  }
  return objectClone;
}
```

No need to use index signatures anywhere. And, to recap, for the reason `Reflect.ownKeys` is not typed as `(keyof T)[]`, see https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208.

**Comment by fatcerberus** [comment]
Just throwing my two cents in: In general I expect `T extends SomeType` (where `SomeType` is structural) to mean that `T` has *at least* the properties of `SomeType`, as that is what structural subtyping is all about, typically.

So my first instinct is that `T extends Record<...>` should likewise mean that T always has an index signature.  But then I realize that this implies an index signature stands in for “all possible properties” which can’t be the case as this would be a bald faced lie: it’s physically impossible for an object to have “all possible properties”.  So the best we can do is to say “it *can* have all possible properties”, in which case the current constraint behavior makes perfect sense.

**Comment by russelldavis** [comment]
I'm trying to understand this change, but having trouble with the current explanations. In particular, it's unclear why the change should apply specifically to a generic type `T extends Bag` and *not* to a regular non-generic `Bag`. For example, the "previously allowed crazy stuff" (from https://github.com/microsoft/TypeScript/issues/31661#issuecomment-497138929) is still allowed if you change `function foo<T extends Record<string, any>>(obj: T)` to `function foo(obj: Record<string, any>)`. It's equally crazy in that context, no?

@ahejlsberg, you tried to address the distinction at https://github.com/microsoft/TypeScript/issues/31661#issuecomment-497474815, but it seems like that explanation has a similar problem. Your example shows that the new behavior prevents `put2` from adding an extra (unknown) property and returning it as the original type (a `Point`). However, the following code compiles without any errors:

```
function put3(point: Point): Point {
  point["z"] = 3;
  return point;
}

const p3: Point = put3({ x: 3 });
```

So, again, why should the generic code be restricted more than the non-generic equivalent? I've been trying to unpack the following for a clue:

> In effect, constraining a type parameter to Bag merely checks that T is assignable to Bag, but it doesn't imply that T is a Bag.

But again it's not clear how this is different from non-generic parameters -- if I pass a value to a non-generic parameter of type `Bag`, isn't it also just an assignability check? Isn't ~everything just an assignability check in a structural type system?

I think it will help a lot to see some specific examples of real-world errors this is intended to fix (if you only have time for a quick response, this would be the most helpful). So far, the compelling error cases I've seen (the "previously allowed crazy stuff" mentioned above) seem to be a result of the special behavior of `Record<string, any>` being assignable to any type.

Are there many errors you're seeing that don't involve that? If not, I would put forth an alternate proposal: for generic constraints, only ignore index signatures equivalent to `Record<string, any>`, and go back to the old behavior for all others.

This would hopefully make the language simpler and more consistent, and save @RyanCavanaugh from having to write [several pages of documentation](https://github.com/microsoft/TypeScript/issues/31661#issuecomment-497135373) 😄  (would love to hear your take on this, Ryan, and/or Anders).

**Comment by russelldavis** [comment]
> I would put forth an alternate proposal: for generic constraints, only ignore index signatures equivalent to `Record<string, any>`

Thinking about this a bit more, this still doesn't feel great in terms of consistency, though at least it would be a more targeted special case. A better, even more targeted change would be to not ignore any index signatures, but to ignore the "`Record<string, any>` is assignable to any type" rule when it appears as a generic constraint.

That would eliminate the "previously allowed crazy stuff" while preserving expected/consistent behavior everywhere else (including the code from the top of this issue). I'm curious how much existing code it would break (though it may also uncover new errors that even #30769 doesn't catch).

If anyone can point me to any context/history/motivation for the "`Record<string, any>` is assignable to any type" rule, that would also be helpful.

**Comment by fatcerberus** [comment]
So having thought about this some more, particularly in light of #31102, it turns out the aforementioned "crazy stuff" is still allowed, and for the same reason even.  We've only closed the loophole for generics, but this is still fine:

```ts
type X = { [key: string]: number };
type Y = { pig: number, cow: number, ape: number };

let y: Y = { pig: 812, cow: 1208, ape: -128 };
let x: X = y;
x.whale = 9001;  // yeah, there's no way this is fitting on the elevator.
console.log(y);
```

As long as the above continues to work, I suspect we will never see the end of issues like #31808... ☹️

**Comment by fatcerberus** [comment]
> But again it's not clear how this is different from non-generic parameters -- if I pass a value to a non-generic parameter of type Bag, isn't it also just an assignability check? Isn't ~everything just an assignability check in a structural type system?

I kind of agree with this, but then again I kind of don't.  The difference is that in the generic case, you have a type variable `T` whose type you don't actually know.  You can't do an actual structural comparison against it--all you know that it's a subset of its `extends` constraint (for whatever "subset" means structurally); there is no lower bound so this could in fact be very, *very* specific.  That seems subtly different from the non-generic case, where you *do* know the exact type, and the unsoundness is merely a consequence of not enforcing contravariance.  In other words, the assignment of `y` to `x` should be an error *only* because the object is mutable, whereas even in that case it still would be a valid type to use for `T`.  At least, that's my thinking, anyway.

That being said, it does still look like inconsistency from an *end-user point of view*, and that's probably all that matters.

**Comment by russelldavis** [comment]
@fatcerberus thanks for the input. I'm not 100% sold on the reasoning without seeing concrete examples, but either way I agree with your final point. If there are practical reasons for the change, we should focus on those.

**Comment by seancheung** [comment]
What about this?

> `target` can be indexed while `source` cannot?

```typescript
function deepMerge<T1 extends Record<string, any>, T2 extends Record<string, any>>(
  source: T1,
  target: T2
): T1 & T2 {
  Object.keys(target).forEach(key => {
    if (source[key] == null) {
      source[key] = target[key];
    } else if (typeof source[key] === 'object') {
      if (typeof target[key] === 'object') {
        deepMerge(source[key], target[key]);
      } else {
        source[key] = target[key];
      }
    } else {
      source[key] = target[key];
    }
  });

  return source as any;
}
```
![image](https://user-images.githubusercontent.com/5442563/59250536-29ef3a80-8c5a-11e9-9764-2c51939d6b77.png)

**Comment by BBGONE** [comment]
Yep, this new intended feature broke my project. I'm weeping. Why to introduce such ugly quirks to resolve simple matters?

This does not work anymore. **Such a good language is turning into unusable mess**

```
export interface IIndexer<T> {
    [name: string]: T;
}

function assignStrings<T extends U, U extends IIndexer<any>>(target: T, source: U): T {
    if (isNt(target)) {
        target = <any>{};
    }
    if (!isSimpleObject(source)) {
        return target;
    }
   
    const keys = objectKeys(source), len = keys.length;
  
    for (let i = 0; i < len; i += 1) {
        const p = keys[i], tval = target[p], sval = source[p];
        if (isSimpleObject(sval)) {
            target[p] = assignStrings(tval, sval);
        } else if (isString(sval)) {
            target[p] = sval;
        }
    }

    return target;
}
```

**Comment by haohello** [comment]
Any update on the deepMerge type implementation? I'm also stuck on this.

**Comment by haohello** [comment]
How about this one: 
`
export const deepMerge = <T extends object = object, U extends object = object>(a: T, b: U) => {
    let result = Object.assign(a, b)
    for (const key in a) {
        if (!a[key] || (b.hasOwnProperty(key) && typeof b[(key as unknown) as keyof U] !== 'object')) continue

        Object.assign(result, {
            [key]: Object.assign(a[key], b[(key as unknown) as keyof U])
        })
    }

    return result
}
`

**Comment by BBGONE** [comment]
Inside deepMerge it's better to cast all to any. No need to strongly type  it.

**Comment by Amourspirit** [comment]
Here is what I came up with. [TypeScript Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAECqAuBLE0DeBYAUNH0AOArgEYiLDQTxhLkAiApvXgMID2eAngDwAqAfAAoqAJwDm9eAC5oPAJTSeaLLhXREAM2hCwYidAC8h6ADsCIELKXZVN4RILDj0EePgBuZTegBfTzY1aLnqIxpRgxsD0rJq01PSWGNZeuHbwDk7G9ADu0LHw9Nq68AB0rjyIALYFspaQ0OEcHkmqvs0qAYWuaqFUEVGaAILCwmAcCX7J0MCsPVN4BtAA2gC69TANK02TuJ16dRvLssXqrMIAomDAABYCAgBulvp8aHPFhBA3D24+slvb0Kl0q8KmA8LdjNIGo9nghkMUGEw2JwuA1BMYamt6sZGhMVK1kh14Bw8P1nDouoZ9NAAOSsIgAK3owHg1OgADI2WSitAAIRGVDecZtLzTWbAeZU1DQYoy3bwTFSxYAa3oHGklGEIVEy0h2J+PgVSxVaoo8E1xm1uo4Pj+2wA8gymSVjRABOKjidzpcbkqDM9Ev9VOLlasqbCQPDGCx2NxUW68CHfrivILbZNAY45pieGm8cmcBmnEF3J58bhCCQyKbqFWALL0XQMdRgMzwCC8aD0AAe+WMABMYHTGcyFkOnQAaOCdnv0fuDx0jqlj5mCPv0ZutiDSWCTmXFdhSGQrIXJAD0p+gZy7YAqeBA9GkV3g8DwW-P9Ig6kQfb79+KmXgU8ADY8AAFmEAAvCou1YU8AEZT3zaB73lOwIFbBZw0jREYwENcNxANsk2FHAsIRPB610AQ0NbXcZQPYjkkLAF6HQwi0zLHAK1IcgwhoaAAEkIAdYd4AEIcrRPLxmPEhl2U5IkSWiaAhwMIxaQXFl5N5IYRg4YpEAgXTRlk+kag4iZuKrPiq3IyjxAAcVnBsyA7btewHFTNNHTTJ1gacPPnUSfNEwRiwUOjiggVgHEiLc4GPK0rCY+xMzIqN7IKYtIui2LWMY3BOPwYgeOrfi7IbcQ3JnOcvOCpdNLC8kJAi6UZVy4Q4qtRKsWtAMvA6HkOri4p7wteArik2xUqLZqSxInwkNFSgKBizr6AWYbWKiq4NDE4ikI6LChJEp05UsDk4CQCMTs0gQtoxfqbE9LRlvlY1ulWvKpsmDpTuZN5hFYeBgeJehiiuSA7SyYwAAUgZJYQiWKYAwHMe61siSdjUepCVDezsUCpLblVVZZcwGzQBGO4S7voCwfsDQa5UWAQPrqAhjCVYxWBh2oYGNZSeEORn-n+kpIAgRBRGMOVJ0VY0dTQbwfgp7ZvDVyYCcyLIeDmhZi1Z9mYE57nefRTFBc0YXNeSdKmEygQdb17k6nFyd6YK9XCYgDansDaBxeKSXpdl7KXlJjglZJxXVbxwr45wIq8wW5OUhm5xdogbCKMqrK5pyzH8oszBWiwAm+wWf2qAgJVpH9lQPnYPAtUkBuvGMG8H2gAAiHnoHUTVzAgHvE8W1OsA18uZhW1gq4mGu6+SrwICySoKlb5fthAVhUaQGZpB7gA5ehpauIg1upGBYdYVgQFHifmm8ccJk7qppFpOqnWpF-mjwIHRL1yQrQAg3d242A4PQHQ0hoAACY4LwN-oGCoMwJrSAQUg-4fZRjSAAMxwSQkVVoU9MAEwlFvMktcgELVXuvTe4DVB4B0PATIwhD61gID+a0AB1OIwgR6EImM-V+XcP5z2XCyTBXEAFOmockEBYCx6QOgTgWBajYGCKfpPJoBMqi6ErmGa6OdHYCknH2ScrBJx4GIstO+4Md6iAEHo8QfZiLnimDPOxo1WCONcW4IAA)
````ts
class Util {
    public static DeepCopy<T>(target: T): T {
        if (target === null) {
            return target;
        }
        if (target instanceof Date) {
            return new Date(target.getTime()) as any;
        }
        if (target instanceof Array) {
            const cp = [] as any[];
            (target as any[]).forEach((v) => { cp.push(v); });
            return cp.map((n: any) => Util.DeepCopy<any>(n)) as any;
        }
        if (typeof target === 'object' && target !== {}) {
            const cp = { ...(target as { [key: string]: any }) } as { [key: string]: any };
            Object.keys(cp).forEach(k => {
                cp[k] = Util.DeepCopy<any>(cp[k]);
            });
            return cp as T;
        }
        return target;
  }
    public static MergeDefaults<T extends object = object, U extends object = object>(defaults: U, ...opt: T[]) {
        // Example: https://jsfiddle.net/6p4rzmxo/1/
        let result = Util.DeepCopy(defaults);
        Util.DeepMerge(result, ...opt);
        return result;
    }
    public static IsObject(obj: any) {
        return (obj && typeof obj === 'object' && !Array.isArray(obj));
    }
    public static DeepMergeGeneric<T extends object = object, U extends object = object>(target: T, ...sources: U[]): any {
        return Util.DeepMerge(target, ...sources);
    }
    public static DeepMerge<T extends object = object>(target: T, ...sources: any[]): any {
        if (!sources.length) {
        return target;
        }
        const source = sources.shift();

        if (Util.IsObject(target) && Util.IsObject(source)) {
        for (const key in source) {
            if (Object.prototype.hasOwnProperty.call(source, key)) {
            const el = source[key];
            if (Util.IsObject(el)) {
                if (!(target[(key as unknown) as keyof T])) {
                Object.assign(target, { [key]: {} });
                };
                const newTarget = target[(key as unknown) as keyof T];
                Util.DeepMerge(newTarget as Object, el);
            } else {
                Object.assign(target, { [key]: source[key] });
            }
            }
        }
        }
        return this.DeepMerge(target, ...sources);
    }
}
````

**Comment by MichaelCereda** [comment]
This has been already commented by still adding it here for completeness and to help devs struggling with a simpler case.  
In case you're creating a setter with some logic `(Object.keys(fieldsData) as (keyof T)[])` guarantees that all the values in the array generated by  `Object.keys` are keys of T.

Here's an example
```typescript
public set fields(fieldsData: T) {
    (Object.keys(fieldsData) as (keyof T)[])
      .forEach((fd) => {
        this._fields[fd] = fieldsData[fd];
      });
  }
```

**Comment by aprilmintacpineda** [comment]
I ran into this:

```ts
export function pick<T extends Record<string, any>>(
  obj: T,
  ...props: string[]
): Partial<T> {
  return Object.entries(obj).reduce<Partial<T>>((accumulator, [key, value]) => {
    if (props.includes(key)) accumulator[key] = value;
    return accumulator;
  }, {});
}
```

managed fixed it through comments above:

```ts
export function pick<T extends Record<string, any>>(
  obj: T,
  ...props: string[]
): Partial<T> {
  return Object.entries(obj).reduce<Partial<T>>((accumulator, [key, value]) => {
    if (props.includes(key)) accumulator[key as keyof T] = value; // <- crucial as keyof T
    return accumulator;
  }, {});
}
```
