### ISSUE TITLE
Regression in type inference of tuples since 4.1

### ISSUE THREAD

**Issue by johan13** [microsoft/TypeScript#42925]
# Bug Report

Typescript does no longer infer the type of `PickLastInTuple<T>` in the example below as `(arg: any) => any`.

(The code comes from [this Medium article](https://minaluke.medium.com/typescript-compose-function-b7512a7cc012).)

### 🔎 Search Terms

Tuples, Inference

### 🕗 Version & Regression Information

This behavior changed between typescript@4.2.0-dev.20210104 and typescript@4.2.0-dev.20210105 and is still there in typescript@4.3.0-dev.20210223.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/C4TwDgpgBAggTgS1AeQHYQGKqgXigCgEM4BzALikNRAEpcA+S6gbgChXRIoAFBAYwDWAGUIBnYAElUAFQCuYADYQAPNKgQAHsAioAJqKYgA2gF1GeNZu16DRgHQO4EcRQSoAZhDhQAqgBpKUlRXDy8oIRMoAH5wqAp0ADcvNg5waBFxLG5iQgBbCG04aTTVdS0dfVhEFHQsU3MeHPzC0WVeQQzJGXklVXp6IwAGEzYgA)

### 💻 Code

```ts
type ArityOneFn = (arg: any) => any;
type PickLastInTuple<T extends any[]> = T extends [...rest: infer U, argn: infer L] ? L : never;
type LastFnParameterType<T extends ArityOneFn[]> = Parameters<PickLastInTuple<T>>[0];
```

### 🙁 Actual behavior

```
error TS2344: Type 'PickLastInTuple<T>' does not satisfy the constraint '(...args: any) => any'.
  Type 'unknown' is not assignable to type '(...args: any) => any'.
    Type '{}' provides no match for the signature '(...args: any): any'.

3 type LastFnParameterType<T extends ArityOneFn[]> = Parameters<PickLastInTuple<T>>[0];
                                                                ~~~~~~~~~~~~~~~~~~
```

### 🙂 Expected behavior

Successful compilation.

**Comment by ahejlsberg** [comment]
This is an effect of more accurate constraint checking in 4.2. Specifically, in `Parameters<PickLastInTuple<T>>` we end up inferring from `ArityOneFn[]` (the constraint of `T`) to `[...infer U, infer L]`. That would previously infer `ArityOneFn` for `L`, but we now make no inferences because an array type isn't considered to have a last fixed element.

The issue can be fixed by inferring the array element type when `T` isn't a tuple type:

```ts
type PickLastInTuple<T extends any[]> = T extends [...rest: infer U, argn: infer L] ? L : T[number];
```

That works with 4.2 as well as earlier versions.

**Comment by johan13** [comment]
Thank you @ahejlsberg for the explanation and for the workaround! I will close the ticket.
