### ISSUE TITLE
Directly exported functions wrapping the dynamic import causes issues when run in "parallel"

### ISSUE THREAD

**Issue by enisdenjo** [microsoft/TypeScript#51696]
# Bug Report

When wrapping the dynamic `import`, exporting the function directly and building for CommonJS, the built artifact will contain a `var _a` outside of the function's scope which will cause issues when importing in "parallel", for example with `Promise.all`.

### 🔎 Search Terms

dynamic import, import, hoist, outside scope, `var _a`

### 🕗 Version & Regression Information

- This is a regression starting from version `4.9.0-dev.20221019` introduced with #49663

### ⏯ Playground and reproduction link

- [**Reproduction repo enisdenjo/ts-issue-dynamic-import**](https://github.com/enisdenjo/ts-issue-dynamic-import)
- [Playground link with relevant code](https://www.typescriptlang.org/play?module=1#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwEZQQDWwKAkgLaSwBiKAFGAIYwAWAXHAM4xSYoBzAJRwA3gCg4cTFWgxGLVkPEBfcUA)

### 💻 Code

```ts
// importFn.ts

export async function importFn(path: string) {
  return import(path);
}
```

The transpiled code will have problems with parallelism, running the following:

```ts
// assuming neither module exists
Promise.all(["idontexist-1", "idontexist-2"].map(importFn));
```

will raise an error: "Cannot find module '**idontexist-2**'" while importing **idontexist-1**.

### 🙁 Actual behavior

```ts
// importFn.js

"use strict";
var _a; // 👈 outside func scope
Object.defineProperty(exports, "__esModule", { value: true });
exports.importFn = void 0;
async function importFn(path) {
    return _a = path, Promise.resolve().then(() => require(_a));
}
exports.importFn = importFn;
```

### 🙂 Expected behavior

```ts
// importFn.js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.importFn = void 0;
async function importFn(path) {
    var _a; // 👈 inside func scope
    return _a = path, Promise.resolve().then(() => require(_a));
}
exports.importFn = importFn;
```

**Comment by Josh-Cena** [comment]
Duplicate of #51554 and fixed by https://github.com/microsoft/TypeScript/pull/51562
