### ISSUE TITLE
Something broken in language server in 2.5

### ISSUE THREAD

**Issue by cevek** [Microsoft/TypeScript#16616]
**TypeScript Version:**  2.4.0 / nightly (2.5.0-dev.201xxxxx)

**Code**

```js
var ts = require('typescript');
var fs = require('fs');
var files = {};
var rootFileNames = ['1.tsx'];
rootFileNames.forEach(fileName => {
    files[fileName] = { version: 0 };
});

var options = {
    "module": 1,
    "target": 1,
    "jsx": 2,
    "configFilePath": "tsconfig.json"
}
var fileName = rootFileNames[0];
const servicesHost = {
    getScriptFileNames: () => rootFileNames,
    getScriptVersion: (fileName) => files[fileName] && files[fileName].version.toString(),
    getScriptSnapshot: (fileName) => {
        if (!fs.existsSync(fileName)) {
            return undefined;
        }
        return ts.ScriptSnapshot.fromString(fs.readFileSync(fileName).toString());
    },
    getCurrentDirectory: () => process.cwd(),
    getCompilationSettings: () => options,
    getDefaultLibFileName: (options) => ts.getDefaultLibFilePath(options),
};

const services = ts.createLanguageService(servicesHost, ts.createDocumentRegistry())
var output = services.getEmitOutput(fileName);
var diagnostics = services.getCompilerOptionsDiagnostics()
    .concat(services.getSyntacticDiagnostics(fileName))
    .concat(services.getSemanticDiagnostics(fileName));

console.log(diagnostics);
```

1.tsx
```ts
import * as React from 'react';
<div className="foo"></div>
```

**Expected behavior:**
no error

**Actual behavior:**
 messageText: 'Cannot find module \'react\'.',

It works with 2.4

**Comment by andy-ms** [comment]
This was broken by #16494. The default `fileExists` used to use `getOrCreateEntry`, now it just uses `containsEntryByPath`, so if a file hasn't already been loaded by services, we think it doesn't exist. @sheetalkamat

**Comment by sheetalkamat** [comment]
This is working as intended. As documented [here](https://github.com/Microsoft/TypeScript/blame/master/src/services/types.ts#L166),  language service host needs to implement fileExists, readFile and readDirectory to be able to correctly resolve the modules (otherwise only ambient modules would be resolved). We were earlier using getScriptSnapshot internally to check if the file exists which was not the intended use of that function.
I changed the servicesHost in your declaration as 
```typescript
const servicesHost = {
    getScriptFileNames: () => rootFileNames,
    getScriptVersion: (fileName) => files[fileName] && files[fileName].version.toString(),
    getScriptSnapshot: (fileName) => {
        if (!fs.existsSync(fileName)) {
            return undefined;
        }
        return ts.ScriptSnapshot.fromString(fs.readFileSync(fileName).toString());
    },
    getCurrentDirectory: () => process.cwd(),
    getCompilationSettings: () => options,
    getDefaultLibFileName: (options) => ts.getDefaultLibFilePath(options),
    fileExists: ts.sys.fileExists,
    readFile: ts.sys.readFile,
    readDirectory: ts.sys.readDirectory,
};
```
And it is compiling correctly.

cc @DanielRosenwasser

**Comment by cevek** [comment]
I just copy pasted example from here https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services

**Comment by sheetalkamat** [comment]
@DanielRosenwasser is updating the example

**Comment by DanielRosenwasser** [comment]
Done!

**Comment by sheetalkamat** [comment]
Leave a comment

**Comment by cevek** [comment]
@sheetalkamat Thank you
