### ISSUE TITLE
error TS2303: Circular definition of import alias 'default'.

### ISSUE THREAD

**Issue by panuhorsmalahti** [Microsoft/TypeScript#3018]
Hi, I'm switching to ES6 modules. The type definition below worked fine in 1.5.0-alpha, but gives an error in 1.5.0-beta

```
declare var io: SocketIOClientStatic;

declare module 'socket.io-client' {
    export default io;
}
```

It seems that error TS2303: Circular definition of import alias 'default' is always given when the export default is a variable. At least the error message is misleading. The earlier form 'export = io' is not allowed in ES6 output mode.

**Comment by panuhorsmalahti** [comment]
While the following compiles, it seems like a hack and only allows one of the constructor functions to be typed:
```
declare var io: SocketIOClientStatic;

interface SocketIOClientStatic {
    (host: string, details?: any): SocketIOClient.Socket;
    (details?: any): SocketIOClient.Socket;
}

declare module 'socket.io-client' {
    function Constructor(host: string, details?: any): SocketIOClient.Socket;

    export default Constructor;
}
```

**Comment by mhegazy** [comment]
repo:

```ts
declare var io: any;

declare module 'module' {
    export default io;
}
```
error TS2303: Circular definition of import alias 'default'.

**Comment by SergioMorchon** [comment]
The same when trying to update knockout, jquery etc. DefinitelyTyped definitions. We now aren't able to use them with ES6 and ES5/3 with the same d.ts file :S
