### ISSUE TITLE
A binding pattern without rest element can have a trailing comma

### ISSUE THREAD

**Issue by ikatyang** [Microsoft/TypeScript#24628]
**TypeScript Version:**  2.9.1/3.0.0-dev.20180602

**Search Terms:** 
- trailing comma
- binding pattern
- A rest parameter or binding pattern may not have a trailing comma.

**Code**

```ts
declare const anything: any[];

let a;

[
  a,
] = anything;

let [
  b,
] = anything;

```

**Expected behavior:**
no error

**Actual behavior:**
```
test.ts:6:4 - error TS1013: A rest parameter or binding pattern may not have a trailing comma.

6   a,
     ~
```

Per [ECMAScript Spec](https://tc39.github.io/ecma262/#prod-ArrayBindingPattern), the trailing comma is allowed in a binding pattern without rest element.

> ![image](https://user-images.githubusercontent.com/8341033/40882146-c18110e6-670b-11e8-94b9-cabc451c25e9.png)

**Playground Link:**  
[link](http://www.typescriptlang.org/play/index.html#src=declare%20const%20anything%3A%20any%5B%5D%3B%0D%0A%0D%0Alet%20a%3B%0D%0A%0D%0A%5B%0D%0A%20%20a%2C%0D%0A%5D%20%3D%20anything%3B%0D%0A%0D%0Alet%20%5B%0D%0A%20%20b%2C%0D%0A%5D%20%3D%20anything%3B%0D%0A)

**Related Issues:** 

(from prettier/prettier#4624)

**Comment by mhegazy** [comment]
PRs welcomed.

**Comment by alexandrLamdan1995** [comment]
declare const anything: any[];

let a;

[
  a
] = anything;

let [
  b,
] = anything;

[23:31:52] Found 0 errors. Watching for file changes.

Correct me if i wrong

**Comment by mhegazy** [comment]
thanks @alexandrLamdan1995

**Comment by bakkot** [comment]
@mhegazy I'm still seeing this on master:

```
$ cat in.ts
let a; [a,] = <any>[];

$ git rev-parse --short HEAD
7eaa78846e

$ gulp local
[...]

$ node built/local/tsc.js in.ts
in.ts:1:10 - error TS1013: A rest parameter or binding pattern may not have a trailing comma.

1 let a; [a,] = <any>[];
           ~
```

Looks like this was introduced in #22262. I'll submit a PR in a moment here.

**Comment by BLRplex** [comment]
Will anyone try to fix it? Windows update - crash + BSOD, skype update - crash, Typescript update - crash. Do you have testers for your own products? The worst QA in all over the world... And that is Microsoft.

**Comment by j-f1** [comment]
It’ll be fixed by #24672 @BLRplex.

**Comment by BLRplex** [comment]
@j-f1 Hope it will not reopened again in few days. Thanks

**Comment by vaskevich** [comment]
Can this fix make it into into an earlier release, e.g., 2.9.2? We use [Prettier](https://github.com/prettier/prettier/issues/4624) and either we have to rip out all trailing commas or upset the TS compiler to update to 2.9.

**Comment by vaskevich** [comment]
As a workaround for anyone who stumbles into this issue, you can just append `// prettier-ignore` to an offending line and Prettier will not add a trailing comma there to satisfy TS.
