### ISSUE TITLE
globalThis property access errors are behind noImplicitAny, not noImplicitThis

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#30139]
Now that globalThis is available, top-level `this` also has a more precise type, and issues the normal noImplicitAny element access errors for unknown properties:

```ts
if (this['unknown']) { ... } // error, `typeof globalThis` has no index signature
if (this.unknown) { ... } // error, `typeof globalThis` has no index signature
this.onmousemove = function () { /* ok, and this: Window */ }
```

We have a conflict: traditionally, "x has no index signature" errors are produced when noImplicitAny is on. Also traditionally, "this has type any" errors are produced when noImplicitThis is on.

Technically, top-level `this` no longer has type any, so it's *technically* correct to issue the errors from behind noImplicitAny. But people might expect to see them only when noImplicitThis is on instead.

Let's discuss at the next design meeting.

**Comment by sandersn** [comment]
No complaints so far. I think this is fine where it is.

**Comment by IgorKurkov** [comment]
Hi! Faced this issue `Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.`
Any updates?

**Comment by sandersn** [comment]
Can you explain more about your expectations and usage?

1. Is your usage the same as the bug's example?
2. Do you expect *no* error or a *different* error?
2. Do you have `noImplicitAny: true` but `noImplicitThis: false`? That's the only configuration that would no longer have an error if this bug were fixed.

**Comment by KevinGruber** [comment]
@sandersn I have exactly that problem
with the config `noImplicitAny: true` and `noImplicitThis: false`

It worked fine in lower versions (ts 4.2.*)
but since the upgrade to ts4.3 it is behaving like that 

do you have any idea?

**Comment by sandersn** [comment]
@KevinGruber nothing comes to mind except maybe external changes to `@types/node`. Can you open a new issue with more detail about the error you get?

**Comment by nulldreams** [comment]
@KevinGruber I managed to remove this message with the property "noImplicitAny": false.

ts 4.3.5

**Comment by bennycode** [comment]
I am getting this error when bumping `@types/node` from 15.12.4 to 16.7.10.

I have the following defined in my code:

```
import {APIClient} from '../../APIClient';

declare global {
  module NodeJS {
    interface Global {
      client: APIClient;
    }
  }
}

global.client = new APIClient(APIClient.URL_DEMO, 'global-demo-api-key');
^----- here I am getting the error: TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.
```

**Comment by mstaicu** [comment]
@bennycode I had the same issue with exactly the same use case as yours. Seems that the latest [@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.global.d.ts) has the following type definition file content

```
declare var global: typeof globalThis;
```

Seems that at some point it had a different [content](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ef49ffb4c80e2b4dc1eb84d6faba47478cd6f3b1/types/node/globals.global.d.ts)

```
declare var global: NodeJS.Global & typeof globalThis;
```

What I ended up doing is this ( porting your changes ):

```
declare global {
  function client(): APIClient;
}
```

or

```
declare module globalThis {
  function client(): APIClient;
}
```

**Comment by hazemalabiad** [comment]
@mstaicu Where to put those definitions? in `global.d.ts`? In which folder?

**Comment by bennycode** [comment]
Thanks for helping me @mstaicu. My problem is that `client` is not a function but an instance of  `APIClient`. That's why the following definitions didn't work:

**Test:**

```ts
declare global {
  function client(): APIClient;
}

global.client = new APIClient(APIClient.URL_DEMO, "global-demo-api-key");
```

**Error:**

> TS2322: Type 'APIClient' is not assignable to type '() => APIClient'.   Type 'APIClient' provides no match for the signature '(): APIClient'.

**Test:**

```ts
declare global {
  client: APIClient;
}

global.client = new APIClient(APIClient.URL_DEMO, "global-demo-api-key");
```

**Error:**

> TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

**Test:**

```ts
declare module globalThis {
  function client(): APIClient;
}

global.client = new APIClient(APIClient.URL_DEMO, "global-demo-api-key");
```

**Error:**

> TS7017: Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.

I tried to use a getter and setter definition as these are supported [since TS 3.6](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#get-and-set-accessors-are-allowed-in-ambient-contexts) but it also didn't help:

**Test:**

```ts
declare global {
  get client(): APIClient;
}
```

**Error:**

> TS2304: Cannot find name 'client'.

**Test:**

```ts
declare module globalThis {
  get client(): APIClient;
}
```

**Error:**

> TS2304: Cannot find name 'client'.

You can find my attempts here: https://github.com/bennycode/ig-trading-api/pull/288

**Comment by mstaicu** [comment]
@bennycode what about the following:

```

declare global {
  var client: String;
}

global.client = "🙈";
```

Then access `global.client` where you need to

**Comment by ctjlewis** [comment]
Somehow, this only works when defining the following way:

```ts
declare module global {
  const MY_VAR: string;
}
```

The following do not work:

```ts
declare global { ... }

declare globalThis { ... }

declare module globalThis { ... }
```

Only `declare module global { ... }` works, no idea why.

**Comment by mr-chidex** [comment]
This works for me.
create a file say` types.d.ts`

in `types.d.ts`
```
import { PrismaClient } from '@prisma/client';

declare global {
  var prisma: PrismaClient | undefined;
}

```

Remember to add files in `tsconfig.json`
```
},
"files": ["src/types/types.d.ts"],
}
```

**Comment by Flaburgan** [comment]
Hello, sorry to revive this 2.5 years later, but I'm facing this issue with Node.
Node itself already define the global object in `@types/node/globals.global.d.ts`:
```js
declare var global: typeof globalThis;
```
So even if I added the solution above in my `typings.d.ts` file,  I still have the error. Any idea?

**Comment by oldium** [comment]
@Flaburgan I am using latest WebStorm IDE and had to use the following, no idea why:

```TypeScript
declare global {
    var my_var: string;
}
```

Either at the top of the TypeScript file using it, or in a file `include`d from `tsconfig.json`. I got better results in WebStorm with _Service-powered type engine_ for TypeScript enabled (for other type definitions).

Using `declare module global { ... }` did not work for me.

Edit: the IDE behaves strangely, after updates of the lines, the mouse hover shows the `any` type again, but otherwise the any-warning is gone. Anyway, this also does not solve the issue for 100%, so sorry for the noise.
