### ISSUE TITLE
Type inference for union of arrays broken

### ISSUE THREAD

**Issue by ulrichb** [Microsoft/TypeScript#27337]
**TypeScript Version:**  Version 3.1.0-dev.20180925

**Search Terms:** array this context type compatibility assignability

**Code**

```ts
interface Array<T> {
    equalsShallow<T>(this: ReadonlyArray<T>, other: ReadonlyArray<T>): boolean;
}

type ExtractArrayType<TArray> = TArray extends Array<infer T> ? T : never;

[
    { a: ["x"], b: [] },
    { a: [], b: ["x"] },
    { a: ["x", 2], b: ["x", 2] },
    { a: ["1"], b: [1] },
    { a: [1], b: ["1"] },
    { a: [null], b: [undefined] },
    { a: [undefined], b: [null] },
    { a: [{}], b: [{}] },
].forEach(({ a, b }) => {

    // Compiles:
    const assignedA: typeof a = b;
    const assignedB: typeof b = a;

    // Compiles (prove that ReadonlyArray<>-types are compatible):
    const assignedAReadonly: ReadonlyArray<ExtractArrayType<typeof a>> = b;
    const assignedBReadonly: ReadonlyArray<ExtractArrayType<typeof b>> = a;

    // error TS2684: The 'this' context of type '(string | number)[] | null[] | undefined[] | {}[]'
    // is not assignable to method's 'this' of type 'ReadonlyArray<string | number>':
    a.equalsShallow(b);
});
```

Works in TS 3.0.

Note that the error disappears when changing `equalsShallow()` to `equalsShallow<T>(this: Array<T>, other: Array<T>): boolean`.

Further note that the error disappears when extracting a type for `a` and `b` (instead of using the literal type inference).

**Expected behavior:** No compile error

**Actual behavior:** Compile error, see snippet

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=interface%20Array%3CT%3E%20%7B%0D%0A%20%20%20%20equalsShallow%3CT%3E(this%3A%20ReadonlyArray%3CT%3E%2C%20other%3A%20ReadonlyArray%3CT%3E)%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Atype%20ExtractArrayType%3CTArray%3E%20%3D%20TArray%20extends%20Array%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3B%0D%0A%0D%0A%5B%0D%0A%20%20%20%20%7B%20a%3A%20%5B%22x%22%5D%2C%20b%3A%20%5B%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%5D%2C%20b%3A%20%5B%22x%22%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%22x%22%2C%202%5D%2C%20b%3A%20%5B%22x%22%2C%202%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%221%22%5D%2C%20b%3A%20%5B1%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B1%5D%2C%20b%3A%20%5B%221%22%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5Bnull%5D%2C%20b%3A%20%5Bundefined%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5Bundefined%5D%2C%20b%3A%20%5Bnull%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%7B%7D%5D%2C%20b%3A%20%5B%7B%7D%5D%20%7D%2C%0D%0A%5D.forEach((%7B%20a%2C%20b%20%7D)%20%3D%3E%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Works%3A%0D%0A%20%20%20%20const%20assignedA%3A%20typeof%20a%20%3D%20b%3B%0D%0A%20%20%20%20const%20assignedB%3A%20typeof%20b%20%3D%20a%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Prove%20that%20ReadonlyArray%3C%3E-types%20are%20compatible%3A%0D%0A%20%20%20%20const%20assignedAReadonly%3A%20ReadonlyArray%3CExtractArrayType%3Ctypeof%20a%3E%3E%20%3D%20b%3B%0D%0A%20%20%20%20const%20assignedBReadonly%3A%20ReadonlyArray%3CExtractArrayType%3Ctypeof%20b%3E%3E%20%3D%20a%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20error%20TS2684%3A%20The%20'this'%20context%20of%20type%20'(string%20%7C%20number)%5B%5D%20%7C%20null%5B%5D%20%7C%20undefined%5B%5D%20%7C%20%7B%7D%5B%5D'%0D%0A%20%20%20%20%2F%2F%20is%20not%20assignable%20to%20method's%20'this'%20of%20type%20'ReadonlyArray%3Cstring%20%7C%20number%3E'%3A%0D%0A%20%20%20%20a.equalsShallow(b)%3B%0D%0A%7D)%3B%0D%0A) (no error because it's TS 3.0)

**Comment by andy-ms** [comment]
Simplified repro:
```ts
declare function f<T>(a: ReadonlyArray<T>, other: ReadonlyArray<T>): boolean;
declare const a: number[] | string[];
f(a, a);
```

**Comment by ahejlsberg** [comment]
This appears to be an effect of #27028 which I merged yesterday. The release-3.1 branch is not affected.

**Comment by ahejlsberg** [comment]
@andy-ms Your simplified repro above is already an error in 3.0. This is a correct simplified repro:

```ts
declare function f<T>(a: ReadonlyArray<T>, other: ReadonlyArray<T>): boolean;
declare const a: number[] | {}[];
f(a, a);
```

@ulrichb The upcoming 3.1 release is in the `release-3.1` branch, so `master` is technically the 3.2 release now (and has been for several days). We just hadn't bumped the version tag ([but that's done now](https://github.com/Microsoft/TypeScript/commit/e1fd0ea53e9f0f0bbcdb0d19d1745d58a29fc70e)).
