### ISSUE TITLE
TypeScript has ceased to infer any types automatically any more

### ISSUE THREAD

**Issue by Yuri6037** [microsoft/TypeScript#44296]
# Bug Report

### 🔎 Search Terms

TS7011, Function expression, which lacks return-type annotation, implicitly has an 'any' return type.

### 🕗 Version & Regression Information

I've just updated version of typescript compiler and now 99% of the code refuses to compile anymore all throwing that garbage error.

- This broke in version 4.3.2 was working fine in version 4.0.2 to 4.2.3.

### 💻 Code

```ts
export type ErrorHandler<TOutput> = (err: ServerError) => TOutput | void | undefined;
export interface IServerConnection {
post<TOutput = void, TInput = void>(path: string, object?: TInput, errorHandler?: ErrorHandler<TOutput>): Promise<TOutput>;
}
const obj = await connection.post<Session>("X", null, () => {
//Here TS does not understand that the ErrorHandler is of type Session (the post method takes TOutput = Session here) anymore it used to do it until today
    return null;
});
```

### 🙁 Actual behavior

99% of the code base of a large project is now unbuildable in CI due to CI always updating versions

### 🙂 Expected behavior

No compilation error

### Additional note

The update also broke most of the react code with the following error:
```
TS2612: Property 'context' will overwrite the base property in 'Component<TProps, TState, any>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
```

Adding an initializer is impossible as it's up to React to initialize the type.

EDIT: Finally found the version problem.
EDIT2: This may actually be related to a different problem: TypeScript genreates gabage code that is unparseable by webpack.
EDIT3: It's a webpack/electron defect: the generated code is actually ES6 however it's apparently unparseable by webpack with electron.
EDIT4: It's even worse now, trying to fix the problem makes it impossible to be fixed: TS refuses at all costs to build BigInt with target ES5 however webpack CANNOT build ES6.
EDIT5: I found a way to get TS to compile a part of the large code base again. TS has changed drastically it's parser of tsconfig:
Now target and module must be es2020 or it will error with 1 million errors of ES6 garbage and lib must be `"lib": ["es2020", "dom"],`. If lib has more values it will throw `TS2737: BigInt literals are not available when targeting lower than ES2020.`

It turns out TS has become a pain in the ass to integrate with Webpack + React + Electron
