### ISSUE TITLE
ERROR: "A computed property name in an interface must directly refer to a built-in symbol."

### ISSUE THREAD

**Issue by pmunin** [Microsoft/TypeScript#21000]
**TypeScript Version:**  2.6.2

**Code**
```ts
const notSerializable = Symbol("Notserializable");

interface MyState{
    [notSerializable]?:{
        numProp:number
    }
}
```
**Expected behavior:**
Compiles successfully

**Actual behavior:**
compilation error: "A computed property name in an interface must directly refer to a built-in symbol."

**Comment by andy-ms** [comment]
There's no error in `typescript@next`.

**Comment by Ixonal** [comment]
I just ran into the same error trying to do much the same thing, but with a const enum. Since a const enum gets converted to the raw constant value (in this case, a string), shouldn't it compile as well?

```typescript
const enum Foo {
  bar = "bar"
}

interface Baz {
  [Foo.bar]: any; //error: A computed property name in an interface must directly refer to a built-in symbol.
}
```
I would assume it would compile, since defining a computed property from a string literal compiles successfully.

```typescript
interface Baz {
  ["bar"]: any; //compiles successfully
}
```

**Comment by andy-ms** [comment]
@Ixonal That example also compiles without error in `typescript@next`.

**Comment by Ixonal** [comment]
Oh good! Thanks for looking into that.

**Comment by alexsasharegan** [comment]
I'm running 2.7.2 and having this compiler error.

<details>
<summary>TypeScript Compiler Output</summary>

```
src/option.ts(13,5): error TS1170: A computed property name in a type literal must directly refer to a built-in symbol.

13     [OptionVariant.None](): U;
       ~~~~~~~~~~~~~~~~~~~~


src/option.ts(14,5): error TS1170: A computed property name in a type literal must directly refer to a built-in symbol.

14     [OptionVariant.Some](val: T): U;
       ~~~~~~~~~~~~~~~~~~~~


src/option.ts(18,16): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

18         return matcher[OptionVariant.None]();
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~


src/option.ts(21,16): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

21         return matcher[OptionVariant.Some](this.option.value);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~


src/result.ts(23,5): error TS1170: A computed property name in a type literal must directly refer to a built-in symbol.

23     [ResultVariant.Ok](x: T): U;
       ~~~~~~~~~~~~~~~~~~


src/result.ts(24,5): error TS1170: A computed property name in a type literal must directly refer to a built-in symbol.

24     [ResultVariant.Err](e: E): U;
       ~~~~~~~~~~~~~~~~~~~


src/result.ts(28,16): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

28         return matcher[ResultVariant.Ok](this.result.value);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~


src/result.ts(31,16): error TS7017: Element implicitly has an 'any' type because type '{}' has no index signature.

31         return matcher[ResultVariant.Err](this.result.error);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

</details>

&nbsp;

![match](https://user-images.githubusercontent.com/16269252/36409448-cf51b7f0-15c8-11e8-8fdd-1ce94a534aa0.png)
![enum](https://user-images.githubusercontent.com/16269252/36409456-daa0cb64-15c8-11e8-84a0-48a568dd980b.png)

**Comment by andy-ms** [comment]
@alexsasharegan Could you post a complete example as plain text?

**Comment by alexsasharegan** [comment]
You know, you're right! Must be gremlins in my other machine's node_modules. My bad!

**Comment by alexsasharegan** [comment]
I figured it out. Running `tsc` calls the global binary. Sure, putting an npm script in the package.json that just does the same thing will call into local modules, but otherwise it's resolving my bash path. Doh 🤦🏻‍♂️

**Comment by sarbull** [comment]
I also got here, yay!

This was my quick fix.

```ts
const obj = {};
obj[e.name] = e;
return obj;
``

**Comment by zixia** [comment]
> [ts] A computed property name in a type literal must directly refer to a built-in symbol.

I got the above error message on my **VSCode** today. After upgrade typescript to 2.9.0-dev.20180430 (@next), it still there.

After I tried https://github.com/alexsasharegan/safe-types/blob/master/src/option.ts#L12-L26 from @alexeagle, I found out that the vscode will always show the error message but the `tsc` work without any problem.

So I upgrade my VSCode, then at last it does not show me that error message anymore.

Shared here for other _old_ VSCode users. ;^)
