### PR TITLE
Track source and target relationship stack depth seperately, only increase on change in value

### LINKED ISSUE #41617: TS 4.1 regression in type assertion of generic mapped type
**TypeScript Version:**  4.1.2

**Search Terms:** CFA, narrowing, generic, mapped type, conditional type, type assertion

**Code**

```ts repro
interface A { x: number }

declare function isA(a: unknown): a is A;

type FunctionsObj<T> = {
  [K in keyof T]: () => unknown
}

function g<
  T extends FunctionsObj<T>,
  M extends keyof T
>(a2: ReturnType<T[M]>) {
  if (isA(a2)) {
    // a2 is not narrowed
    a2.x // error, but should be ok
  }
}
```

**Expected behavior:**

Type of `a2` should be narrowed to `ReturnType<T[M]> & A`
It works this way in TS 4.0

**Actual behavior:**

Type of `a2` remains only `ReturnType<T[M]>`

**Playground Link:** https://www.typescriptlang.org/play?ts=4.1.0-beta#code/JYOwLgpgTgZghgYwgAgILIN7IB4C5kgCuAtgEbTIC+AUNQCYQIA2cUKMhICYwA9iMmABnVAAo4+TgGsQvAO4gAlPjiChaANy0wATwAOKAGKdufEEIDypAFYAeACoA+ZAF5M1ZMgDaAaUECpCB1eGGR7AF18UUVXZ2lZBWoaag4uHn5kAHNbDzDkCGxIEDp1YzSzSxsHRwAaXIBZfMKIYvVA4ND7akdxACZ8ACUIMEIoEHt9CAcvevDHGIxc4FDRYTE4XsUF3M8NgDpsZAB6I-yoKF4oXJoaIA

### LINKED ISSUE #43485: Perf regression: conditional type assignability
# Repro

`npm install @types/react`

index.ts
```ts
type Stuff<T> =
    T extends keyof JSX.IntrinsicElements
        ? JSX.IntrinsicElements[T]
        : any;

function F<T, U>(p1: Stuff<T>, p2: Stuff<U>) {
    p1 = p2; // Error
}
```

`tsc index.ts --noEmit --skipLibCheck --extendedDiagnostifcs`

# Effect

Check time increased from ~0.5s in b2d1f537f114ad401dd90bccc1b5ef75c589e423 to ~7.0s in 2643e65da4b59f2ae2fc37eefaedab6055f875ab (aka #30639).

Repro is reduced from a variance check of React's [ComponentProps](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/66993c2b188caa15b0be4824527aa9c2871c9eb6/types/react/index.d.ts#L826).

### LINKED ISSUE #44404: Union types are not being narrowed correctly in generic functions in 4.3
# Bug Report

Narrowing of a union type based on generic types does not work correctly in `else` branches in TS 4.3.

This likely relates to the changes made in https://github.com/microsoft/TypeScript/pull/43183

### 🔎 Search Terms

generic, narrow, union types, 4.3

### 🕗 Version & Regression Information

This changed between versions 4.2.3 and 4.3

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.3.2&ssl=13&ssc=2&pln=1&pc=1&strict=true#code/GYVwdgxgLglg9mABGApigJgZwCpwHICGATkXAO7YAWK2AngA4oA8AYjEZlIigB5QpgsiAN6JgcOAC5EnIjDABzRAF8ANIgDKKCAnTc+AoaIBGxabPlLlAPgAUUSpelsOXAD6btugJQiAUIiBiDDAiLaUBJgAgiwS9o6K3r7CAUFpOmCYcAA2KAB02XAK8ZZ54nDeANypgco13NmYKP5paQD0bYgAkohkcCDZeryM0IgOMJhjcL1wRADWiMbaBCBNY9RjDM2YlP2Di81gxKRkGMFI45PGRASQlFOIAAZaGeiP9ekIWbkFRSWKeVMRCqiA6iAAoiRZtIAAqkRhEKC0RAAciBKMQ6DgKEmYDgXF4Ey4CE2jFRLk4iA8L10KLy9Tq9VAkFgJIi0VicFsADcCNkQChnOxKdSvIJvNJefzmhNEBSuClWkEiCgoCAiEgAETlTXnRBSgXVNJ1ZRAA)

### 💻 Code

```ts
function needsToNarrowTheType<First extends { foo: string }, Second extends { bar: string }>(thing: First | Second) {
    if (hasAFoo(thing)) {
        console.log(thing.foo);
    }
    else {
        // I would expect this to work because the type should be narrowed in this branch to `Second`
        console.log(thing.bar); // Error: Property 'bar' does not exist on type 'First | Second'.
    }

    function hasAFoo(value: First | Second): value is First {
        return "foo" in value;
    }
}
```

### 🙁 Actual behavior

In the `else` branch, the type of `thing` is `First | Second`.

### 🙂 Expected behavior

In the `else` branch. the type of `thing` is `Second`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #41617
Fixes #43485
Fixes #44404

### CODE REVIEW

File: tests/baselines/reference/infiniteConstraints.errors.txt [hunk 1]
```diff
@@ -63,4 +64,6 @@ tests/cases/compiler/infiniteConstraints.ts(36,71): error TS2536: Type '"foo"' c
     
     type Conv<T, U = T> =
       { 0: [T]; 1: Prepend<T, Conv<ExactExtract<U, T>>>;}[U extends T ? 0 : 1];
+                              ~~~~~~~~~~~~~~~~~~~~~~~~
+!!! error TS2321: Excessive stack depth comparing types 'Conv<ExactExtract<U, T>, ExactExtract<U, T>>' and 'unknown[]'.
```
Comment (weswigham) [inline tests/baselines/reference/infiniteConstraints.errors.txt:68]: This was originally added because it had bad perf, and the test had a stack out error (circa #32079), however the error disappeared in #40971 and we just kidna didn't care (the test is for perf, after all). Turns out, the error should still be here, since the relationship does still infinitely expand.

**Comment by weswigham** [comment]
@ahejlsberg if you could take a look at this when you get a chance, that'd be great, thanks!

**Comment by andrewbranch** [comment]
@typescript-bot pack this

**Comment by amcasey** [comment]
@weswigham What's happening with this?

**Comment by weswigham** [comment]
There's another issue this fixes -
```ts
function f1<T, K1 extends keyof T, K2 extends keyof T[K1]>(
    x: T[K1][K2], y: Extract<T[K1][K2], string>) {
    x = y;
    y = x; // missing error
}

// for comparison, the equivalent comparison with bare, unconstrained type parameters
function f2<T>(x: T, y: Extract<T, string>) {
    x = y;
    y = x; // correctly has error
}
```

decomposing `T[K1][K2]` to its base constraint takes > 5 steps, so without this change, hits our limiter and throws up a `Maybe`, which makes the comparison succeed.

@ahejlsberg it'd be super nice if you could review this ❤️

**Comment by ahejlsberg** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
What if one of the sides has a constraint that keeps on generating deeper and deeper types? Won't we just keep on going and eventually hit the 100 level panic limiter and issue an error? Is that what we want?

**Comment by weswigham** [comment]
I think it is - a generative type should probably hit the issues-an-error limiter and not the quietly-pass-assignability limiter.

**Comment by ahejlsberg** [comment]
Hmm. But it just seems really odd that we would issue an error if nothing changes one one side, but if that side instead flip-flops between two types, then all of a sudden we're fine with it (because we produce a `Ternary.Maybe`).

**Comment by ahejlsberg** [comment]
In other words, our limiter is based on the notion that we count occurrences of cycles, and all of a sudden we're saying that a cycle of length one doesn't count at all. I'm not sure I can make that make sense.

**Comment by weswigham** [comment]
> Hmm. But it just seems really odd that we would issue an error if nothing changes one one side, but if that side instead flip-flops between two types, then all of a sudden we're fine with it (because we produce a Ternary.Maybe).

In such a case, we never _get_ to check the one side that "didn't change" _precisely because_ the other side decomposed forever. That's exactly why it makes sense to issue an error - we never even got to _look_ at the rhs because the lhs was expanding forever. If both the lhs _and_ rhs expand forever, we'll _still_ issue an error, because the lhs expanding forever will prevent us from even checking that the rhs expands forever. "This type expands forever" is a very distinct problem from "this type depends on a comparison which occurred in its history already" - the first we don't really have a reasonable operation to do (blindly allowing the assignment to anything isn't good - we're not even looking at the target!), while for the second, a `Ternary.Maybe` result (as a non-caching `True`, since we can assume a comparison in progress is a success while looking to disprove that) allows the comparison to continue on the other parts of the type structure.

> if that side instead flip-flops between two types, then all of a sudden we're fine with it (because we produce a Ternary.Maybe).

Specifically, I think this is at least more justifiable, since then we've actually explored _some_ structure on both sides, we just want to refrain from exploring too deeply. Whereas when we only ever explore how one side of the relationship expands, it's very hard to justify the assignment (why should a `T[A][B]` function as a `never` on the source side and be assignable to anything just because it's deeply generic? Meanwhile if we compare `T[A][B]` to `U[C][D]` we're more within our rights, imo, to just give up and say "it's too deeply generic on both sides and we don't wanna exhaustively explore this - just let it pass").

> In other words, our limiter is based on the notion that we count occurrences of cycles, and all of a sudden we're saying that a cycle of length one doesn't count at all. I'm not sure I can make that make sense.

Except it's not *actually* counting cycles because it has no knowledge of which side of the comparison (if any) was actually recurred on to produce the new pair of types, which is what it'd need to count that (specifically, it'd only check if the side we recurred on is deeply nested). What we're tracking right now is just occurrences in history, which doesn't correctly admit, say, the LHS looping forever while the RHS just sits there uninspected because we have yet to recur on it (which is turns out is very common, as pretty simple LHS constructs end up taking more than 5 steps to expand to a final constraint!)

_Ideally_, we'd only append to the `sourceStack`/`targetStack` when that side of the relationship is recurred on, but that would require threading more information through every recursive call of `isRelatedTo`. Maybe the `intersectionState` parameter could be hijacked to traffic this, but it probably wouldn't be pretty. Only appending an element when it changes is a decent approximation since we generally try very hard to not recur on a type and immediately produce the same comparison - generally speaking, we like to have every decomposition we perform change the type we decompose in _some way_, or we don't attempt the decomposition at all (specifically, we don't let a generic be directly constrained to itself - that's an error - it has to go through some cycle of deferred decompositions instead, which, under this scheme, will always result in new entries into the stack, and thus for a cycle to be detected).

**Comment by ahejlsberg** [comment]
Let's run the tests to get some more real world data on what the effect is.

**Comment by ahejlsberg** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by ahejlsberg** [comment]
Looks like we have an OOM in the immutable user test suite. Could be the case that we have a recursive relation where one side doesn't vary meaning we'll now go to 100 levels on the other side before we stop.

**Comment by weswigham** [comment]
It might just be because the PR is two months old and the last merge commit
doesn't have a fix for the crash we _used_ to have in immutable. Lemme
resync and rerun to check.

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by weswigham** [comment]
@typescript-bot perf test this

**Comment by ahejlsberg** [comment]
@weswigham I tried the PR on this example:

```ts
function f1<T, K1 extends keyof T, K2 extends keyof T[K1]>() {
    let v1: Extract<T, string> = 0 as any as T;  // Error
    let v2: Extract<T[K1], string> = 0 as any as T[K1];  // Error
    let v3: Extract<T[K1][K2], string> = 0 as any as T[K1][K2];  // No error
}
```

I was expecting an error on the last line, but I'm not seeing it. Any ideas?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -18272,20 +18273,27 @@ namespace ts {
...
                         }
                     }
-                    if (depth === 100) {
+                    if (sourceDepth === 100 || targetDepth === 100) {
                         overflow = true;
                         return Ternary.False;
                     }
                 }
+                const constantSource = sourceStack[sourceDepth] === source;
+                const constantTarget = targetStack[targetDepth] === target;
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:18282]: This doesn't seem right. Only elements at indices less than `sourceDepth` and `targetDepth` have meaningful values. This appears to compare an effectively random value with `source` or `target`. Or am I missing something?

Comment (ahejlsberg) [reply src/compiler/checker.ts:18282]: Don't you need something like this?

```ts
const constantSource = sourceDepth > 0 && sourceStack[sourceDepth - 1] === source;
const constantTarget = targetDepth > 0 && targetStack[targetDepth - 1] === target;
```

**Comment by ahejlsberg** [comment]
When I fix the `constantSource` and `constantTarget` checks, the example with `Extract<...>` starts erroring as expected. But then we have this inconsistent behavior:

```ts
type Foo<T> = { x: Foo<T> };
type Bar<T> = { x: Bar<T[]> };

function f2<U>() {
    let x: Foo<U> = 0 as any as Bar<U>;  // Error, excessive stack depth
}

type Foo1<T> = { x: Foo2<T> };
type Foo2<T> = { x: Foo1<T> };

function f3<U>() {
    let x: Foo1<U> = 0 as any as Bar<U>;  // No error!
}
```

I'm not sure the approach of checking "constantness" on one side is going to work. I'm thinking a better approach is to pass a flag to `isRelatedTo` that disables the `isDeeplyNestedType` check and then use that flag in cases where we are exploring a constraint.

**Comment by weswigham** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this
@typescript-bot perf test this

**Comment by weswigham** [comment]
@typescript-bot pack this for posterity

**Comment by weswigham** [comment]
All extended test suites (RWC, user, DT) look good. Let me try to remove the extra `isDeeplyNestedType` calls and give em another go - if they stay green we'll go with that, otherwise I'll revert that and go with this~

**Comment by weswigham** [comment]
Nope, scratch that - local tests fail if we remove them - the depth check guards are needed on the comparison of conditional constraints, otherwise we issue stack depth warnings when comparing conditional types that operate over recursive type aliases (rather than only erroring when their actual execution exceeds the instantiation limit). We need 'em so we stop recurring further into the (infinitely expanding) type, and instead gracefully try a different constraint form (eg, the distributive constraint instead of the non-distributive one, or vice-versa).

So this should be good to go as-is. @ahejlsberg anything else to add?

**Comment by fabb** [comment]
> Hey @weswigham, I've packed this into [an installable tgz](https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/109006/artifacts?artifactName=tgz&fileId=32F14BC1CCCC5B6DD6C83299C9148D3BA148907CCB93F5D7064C29EF2F37E2A902&fileName=/typescript-4.5.0-insiders.20210820.tgz). You can install it for testing by referencing it in your `package.json` like so:
> 
> ```
> {
>     "devDependencies": {
>         "typescript": "https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/109006/artifacts?artifactName=tgz&fileId=32F14BC1CCCC5B6DD6C83299C9148D3BA148907CCB93F5D7064C29EF2F37E2A902&fileName=/typescript-4.5.0-insiders.20210820.tgz"
>     }
> }
> ```
> 
> and then running `npm install`.
> 
> There is also a playground [for this build](https://www.staging-typescript.org/play?ts=4.5.0-pr-41821-43) and an [npm](https://www.npmjs.com/package/@typescript-deploys/pr-build/v/4.5.0-pr-41821-43) module you can use via `"typescript": "npm:@typescript-deploys/pr-build@4.5.0-pr-41821-43"`.;

This version still does not fix the issue for my case: https://github.com/microsoft/TypeScript/issues/44404#issuecomment-862361234

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -18868,7 +18891,7 @@ namespace ts {
                             else {
                                 targetKeys = nameType || constraintType;
                             }
-                            if (isRelatedTo(source, targetKeys, reportErrors) === Ternary.True) {
+                            if (isRelatedTo(source, targetKeys, RecursionFlags.Target, reportErrors) === Ternary.True) {
```
Comment (andrewbranch) [inline src/compiler/checker.ts:18894]: I added this one while resolving merge conflicts

**Comment by andrewbranch** [comment]
Apparently I didn’t pull recently enough to resolve all the conflicts 🤦

**Review by andrewbranch — APPROVED** [review]
