### PR TITLE
Remove technically unnecessary 'module' option from 'harness' config.

### LINKED ISSUE #40525: Nightlies not publishing
```
[07:04:48] Starting 'buildServerLibraryOut'...
##[error]src/harness/tsconfig.json(4,9): error TS1391: The `bundledPackageName` option must be provided when using outFile and node module resolution with declaration emit.
```

https://github.com/microsoft/TypeScript/runs/1105196341?check_suite_focus=true#step:4:132

Seems broken by https://github.com/microsoft/TypeScript/pull/39277

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #40525 

https://github.com/microsoft/TypeScript/runs/1105196341?check_suite_focus=true#step:4:132

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
Good job bot, ultimately you know I'm going to merge this in 30 minutes to see if it fixes the nightly publish.
