### ISSUE TITLE
Union of function signatures cannot be invoked because it lacks a call signature

### ISSUE THREAD

**Issue by Arnavion** [Microsoft/TypeScript#4612]
Reduced test case:

```typescript
var foo: ((arg: string) => void) | ((arg: any) => void);
foo(null);
```

1. With 1.5.3, this compiles fine. With 1.6-beta, this gives `error TS2349: Cannot invoke an expression whose type lacks a call signature.` null is assignable to both string and any so it should compile.

1. Maybe related - getting quickinfo for foo on the second line does throw an error `TypeError: Cannot read property 'flags' of undefined` in [playground](http://www.typescriptlang.org/Playground#src=var%20foo%3A%20((arg%3A%20string)%20%3D%3E%20void)%20%7C%20((arg%3A%20any)%20%3D%3E%20void)%3B%0Afoo(null)%3B%0A) even though it compiles fine with 1.5.3. I didn't try quickinfo on 1.6

1. If foo was `((arg: string) => void) | ((arg: number) => void);` (number instead of any in the second signature) then *both* 1.5.3 and 1.6 give that error, even though again null is assignable to both.

---

For motivation, the original code is https://github.com/Arnavion/libjass/blob/6606413/src/utility/promise.ts#L363 (the error is on handler). It's an implementation of the ES6 promise spec, specifically http://www.ecma-international.org/ecma-262/6.0/#sec-promisereactionjob - handler would be either the fulfilled callback or rejected callback and the argument passed to it would be either the resolution value or the rejection reason accordingly, hence its signature.

(I understand it would be more type-safe to have separate handlers for the two cases with one signature each from the union, but that complicates the implementation slightly.)

**Comment by Arnavion** [comment]
I guess it has to do with the fact that the union type doesn't contain call signatures unless the signature parameters match exactly in all constituents types [3.11.1.](https://github.com/Microsoft/TypeScript/blob/release-1.6/doc/spec.md#3.11.1) So does that mean the bug was in 1.5.3 to allow it to compile in the first place?

**Comment by mhegazy** [comment]
This a result from removing the aggressive subtype reduction that was in 1.5.* (see #3823). Now we are not reducing to subtypes, so the type still contain the two signatures. at time when the call resolution happen 3.11.1 takes effect, and no call signatures are found.

This is a breaking change from 1.5.3 (will add it to the docs). 

Also related to #3823

**Comment by Arnavion** [comment]
Does not reducing to a subtype with one signature help prevent any errors?

And is there a way to make this work with 1.6 while still keeping the union type?

**Comment by xLama** [comment]
@Arnavion 

You could use call, apply or bind. I know it´s very ugly but It works.

```
var foo: ((arg: string) => void) | ((arg: number) => void) = function(a:string):void{alert(a)};

foo.call(this, "a");
foo.call(this, 1);

```

**Comment by Arnavion** [comment]
Yeah. Splitting into two handlers is cleaner, so I'll go with that.

**Comment by mhegazy** [comment]
@Arnavion, the aggressive subtype reduction would causes cause these errors to disappear, but it also caused loss of information from the union type. the fix was to keep the union information as long as possible. Subtype reduction now is only happening on the lever of operators like conditional and Or (see #3823). in this sense something like:

```ts
var foo1: ((arg: string) => void)
var foo2:  ((arg: any) => void);

var foo = foo1 || foo2; 
foo(null); // works
```

**Comment by drarmstr** [comment]
Looks like we also get this error when both types are derived from the same base class and we try calling a method of the base class.  Is that expected as well?

    class Base {
        foo() { }
    }

    class Derived1 extends Base { }
    class Derived2 extends Base { }

    var spam : Derived1 | Derived2 = ...
    spam.foo(); <- error lacking call signature

**Comment by mhegazy** [comment]
@drarmstr, this should not be an error. i think there is something else going on. also this is an old issue. please file a new one with more information about your code and the version of the compiler you are using.

**Comment by RyanCavanaugh** [comment]
@drarmstr that code doesn't issue an error when I compile with the latest TypeScript

**Comment by drarmstr** [comment]
Yeah, the scenario was from a much more complicated code base.  If I can get a simpler test case to reproduce then I'll submit a new issue. I switched to using an interface for the common methods, though, and it's been working for me.

**Comment by bjnsn** [comment]
Hmmm. A scenario like following still throws this error in 1.8.7, which doesn't seem like it should:

    var arr:(Array<number>|Array<string>) = [5];
    arr.map(String);

However if making it more permissive:

    var arr:Array<number|string> = [5];
    arr.map(String);

or restricted:

    var arr:Array<number> = [5];
    arr.map(String);

fixes the error.

**Comment by DeDuckProject** [comment]
It seems this is still an issue in TS 2.4.2


```ts
export type MyControllerHandler = (e:MyValueEvent)=>void;
export type MyPatchHandler = (e: MyPatchEvent)=>void;

export type MyHandler = MyPatchHandler | MyControllerHandler;


declare const onChange: MyHandler;
onChange({}as any);  // Error:(42, 17) TS2349:Cannot invoke an expression whose type lacks a call signature. Type 'MyHandler' has no compatible call signatures.
```

**Comment by vartan** [comment]
I think this is still an issue in 2.6.2.

Here's pretty simple example:
```ts
class TestClass {
    public foo(x: string | null | number) {
    };
}
class TestClass2 {
    public foo(x: string | null) {
    }
}
const bar: (TestClass | TestClass2) = new TestClass();
bar.foo(null); // Cannot invoke an expression whose type lacks a call signature. 
               // Type '((x: string | number) => void) |
               //       ((x: string) => void)' has no compatible call signatures.
```

I am getting around it currently by casting to an interface with the "correct" union.

```ts
interface FooShim {
    foo(x: string | null | number): void;
}
(bar as FooShim).foo(null);
```

**Comment by dkoprowski** [comment]
I have this issue in 2.8.1, those workaround doesn't apply for me because I would like to overload a function.

Example of my overload:

```
type A = (b: boolean) => void;
type B = (a: string, b?: boolean) => void;

interface Props {
    handler: A | B
}

(bar as Props).handler(false);  //TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'A | B' has no compatible call signatures.
```

**Comment by RyanCavanaugh** [comment]
@dkoprowski You want `(bar.handler as A)(false)`
