### ISSUE TITLE
Project References Regression starting in Nightly 3.9.0-dev.20200313

### ISSUE THREAD

**Issue by warrenfalk** [microsoft/TypeScript#37406]
Project References do not appear be honored in tsserver starting in Nightly 3.9.0-dev.20200313.  This results in an error in Visual Studio code when importing `from 'some-pkg/dist/file'` when that file has not yet been built.

**TypeScript Version:**  3.9.0-dev.20200313 and later

**Search Terms:**

references tsserver

**Code**

Minimal reproduction project attached. [repro.zip](https://github.com/microsoft/TypeScript/files/4334616/repro.zip)

This seems to be an issue with tsserver, and so I can only reproduce it in Visual Studio Code (not with `tsc -b`).

The error is a regression starting in version 3.9.0-dev.20200313.  There was no error in 3.9.0-dev.20200312 and previous.

To reproduce, use attached [repro.zip](https://github.com/microsoft/TypeScript/files/4334616/repro.zip), here are simple instructions and the screenshot of the result.
```
unzip repro.zip
cd repro-ts-bug
yarn install
code .
code src1/one.ts
```
See issue in `3.9.0-dev.20200313`:
![image](https://user-images.githubusercontent.com/158330/76706212-30fd1a80-66bc-11ea-82df-072718f21279.png)

This should work because of a project reference to `src2/tsconfig.json` from `src1/tsconfig.json`, and it does work in the previous build of typescript.
___

You can see this is a regression.  Installing the previous version and reloading the window demonstrates no error.
```
yarn add typescript@3.9.0-dev.20200312
```

And reload window.  No issue in `3.9.0-dev-20200312`

![image](https://user-images.githubusercontent.com/158330/76706314-dfa15b00-66bc-11ea-9f0d-311f6c4b715a.png)

**Expected behavior:**

No error, as in second screenshot

**Actual behavior:**

Error:
```
Cannot find module '../dist2/two' or its corresponding type declarations.
```

**Playground Link:** 
Unable to demonstrate project reference issues with playground (as far as I know)

**Related Issues:**

**Comment by warrenfalk** [comment]
@sheetalkamat, it appears this problem began with the merge of PR #37370, "Move useSourceOfProjectReferenceRedirect to program so other hosts can use it too, enabling it for WatchHost" with commit a76a16696d7

Is this a regression, or am I misunderstanding something about how this _should_ work?

**Comment by sheetalkamat** [comment]
Don't repro the issue at all:


![image](https://user-images.githubusercontent.com/8052792/76785682-189c0700-6773-11ea-8b9c-89b2b9fb759e.png)

**Comment by warrenfalk** [comment]
Hmm, indeed, I can only reproduce it on _this_ machine.  It didn't occur to me to try other machines - sorry about that...

But something has definitely changed in 20200313, though, because on this machine every version before that works, but every version after does not.

I will try to see if I can see why.  Are there any hints you can give that might explain why this might work on one machine, but not on a nearly identical machine?

**Comment by sheetalkamat** [comment]
you could add `--traceResolution` and see whats going on in tsserver log..

**Comment by warrenfalk** [comment]
Ah, it was a vscode extension that I long forgot was there; I should have thought of that.  It appears to be interfering in some way that breaks after 20200313.  I don't need the extension so I am just removing it rather than look deeper.  Thanks for the pointer, and sorry about wasting your time.

**Comment by RyanCavanaugh** [comment]
@warrenfalk glad we got it figured out; thanks for following up
