### PR TITLE
Don't bind JSDoc type parameter in a TS file

### LINKED ISSUE #16358: @template tag takes effect in TypeScript code
**TypeScript Version:**   nightly (2.4.0-dev.20170608)

**Code**

```ts
interface I { n: number; }

class C<T extends I> {
    constructor(readonly t: T) {}

    /** @template U */
    static create<U extends I>(u: U): C<U> {
        return new C(u);
    }
}
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(7,41): error TS2344: Type 'U' does not satisfy the constraint 'I'.
src/a.ts(8,22): error TS2345: Argument of type 'U' is not assignable to parameter of type 'I'.
```

(Broken by #15856)

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #16358
Now that we no longer bind `@template` tags, had to add some code to `getSymbolAtLocation` to get find-all-references working again.
Also discovered #16411.

### CODE REVIEW

File: src/compiler/utilities.ts [hunk 1]
```diff
@@ -5274,6 +5280,10 @@ namespace ts {
 
     /* @internal */
     export function isDeclaration(node: Node): node is NamedDeclaration {
+        if (node.kind === SyntaxKind.TypeParameter) {
```
Comment (andy-ms) [inline src/compiler/utilities.ts]: In a TypeScript file, a TypeParameter in JSDoc is just a comment, albeit one that is parsed.
In a JavaScript file, it's actually a declaration.

**Comment by mhegazy** [comment]
@rbuckton can you please review this change.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -22551,10 +22551,16 @@ namespace ts {
             }
 
             if (entityName.parent!.kind === SyntaxKind.JSDocParameterTag) {
-                const parameter = ts.getParameterFromJSDoc(entityName.parent as JSDocParameterTag);
+                const parameter = getParameterFromJSDoc(entityName.parent as JSDocParameterTag);
                 return parameter && parameter.symbol;
             }
 
+            if (entityName.parent!.kind === SyntaxKind.TypeParameter && entityName.parent!.parent!.kind === SyntaxKind.JSDocTemplateTag) {
```
Comment (rbuckton) [inline src/compiler/checker.ts]: We don't compile with strictNullChecks (yet), and line 22553 is the only place in the whole file where we have a non-null expression. I'd rather we not use it here and remove the one above, as when the time comes and we do enable strictNullChecks, we could unintentionally miss a case because we added these too early.

File: src/services/findAllReferences.ts [hunk 3]
```diff
@@ -784,8 +784,8 @@ namespace ts.FindAllReferences.Core {
             return;
         }
 
-        const fullStart = state.options.findInComments || container.jsDoc !== undefined || forEach(search.symbol.declarations, d => d.kind === ts.SyntaxKind.JSDocTypedefTag);
-        for (const position of getPossibleSymbolReferencePositions(sourceFile, search.text, container, fullStart)) {
+        // Need to search in the full start of the node in case there is a reference inside JSDoc.
+        for (const position of getPossibleSymbolReferencePositions(sourceFile, search.text, container, /*fullStart*/ true)) {
```
Comment (rbuckton) [inline src/services/findAllReferences.ts]: Wouldn't this have been `true` if `container.jsDoc !== undefined`, or are we opening this up to all comments of the container because we need to find it on a node where we don't currently parse JSDoc comments in the parser?

Comment (andy-ms) [inline src/services/findAllReferences.ts]: That was a bad test in the first place, because if you `container` is the SourceFile, `container.jsDoc` will always be undefined, but calling `.getStart()` on the SourceFile could still skip past jsdoc comments.
We should probably never even bother with calling `.getStart()` in `getPossibleSymbolReferencePositions` anyway, because scanning to the start of a node is probably more expensive than just doing text search on the full range.

Comment (andy-ms) [inline src/services/findAllReferences.ts]: I made a PR for that: #16420
