### ISSUE TITLE
Auto-fixer for missing React import

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/TypeScript#21830]
```typescript
const element = <span />;
// [ts] 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

If the compiler settings have `jsx: "react"`, it seems like adding the import automatically could be a reasonable auto-fix?

```typescript
import * as React from "react";

const element = <span />;
```

**Comment by mhegazy** [comment]
?
![animation](https://user-images.githubusercontent.com/8000722/36043244-7ec82c80-0d83-11e8-806a-458299e265d8.gif)

**Comment by JoshuaKGoldberg** [comment]
Huh, that works for me.

But: looks like there's a VS Code bug if the element type isn't found (for non-native elements), neither auto-suggest picks up. I'll follow up with them. Thanks!

**Comment by mhegazy** [comment]
VSCode has nothing to do with what quick fixes show or not, that is all the ts server. can you share an example?

**Comment by JoshuaKGoldberg** [comment]
```typescript
import { observer } from "mobx-react";

import { SampleStore } from "./ClientAppStore";

export const Sample = observer(({ children, store }: IStoreProps<SampleStore>) => {
	return (
		<ExceptionHandler store={store.exceptionHandlerStore}>
			{children}
		</ExceptionHandler>
	);
});
```

```
[ts] Cannot find name 'ExceptionHandler'.
[ts] 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```

No lightning bolt / fix suggestions show up when the cursor is on the `ExceptionHandler` line. If I add `import * as React from "react";` to the imports list, it does show up.

![image](https://user-images.githubusercontent.com/3335181/36043958-e39976f8-0d85-11e8-82a5-9400d657d8e2.png)

**Comment by mhegazy** [comment]
Looks like this is fixed in latest. I think my change in https://github.com/Microsoft/TypeScript/pull/21755 did allow for this to work. can you give `typescript@next` a try?

**Comment by JoshuaKGoldberg** [comment]
It halfway works. Now, the opening tag for `ExceptionHandler` will give the `react` suggestion only, and the closing tag will give the `import ExceptionHandler` suggestion only.

**Comment by mhegazy** [comment]
Once you add the react fix, the other fix should show up as well. but i suppose we can do them in one and save you the extra command.

**Comment by guillaume86** [comment]
Not sure it's the same issue, but since updating to 2.8.1 from 2.7.2 I lost the quick fix for missing import of JSX elements. Typescript output in VS code do not have any errors.

**Comment by RyanCavanaugh** [comment]
Closing language service bugs related to the 6.0 implementation. For more information, see #62827
