### PR TITLE
Use inference for filling JSX attributes in getJsxElementInstanceType

### LINKED ISSUE #20891: Generic JSX props don't work properly when props contain generic functions
In 2.5.3, I was using JSX components with generic props containing functions successfully by wrapping stateful ones with stateless components, as also described in #6395 and in [this comment](https://github.com/Microsoft/TypeScript/issues/6395#issuecomment-352178978)

However, in 2.6.x and typescript@next, it breaks:

```src/bug.tsx(18,19): error TS2322: Type '{ a: T; b: T[]; c: (t: T) => number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Comp2<{}>> & Readonly<{ children?: ReactNode; }> &...'.
  Type '{ a: T; b: T[]; c: (t: T) => number; }' is not assignable to type 'Readonly<Props<{}>>'.
    Types of property 'c' are incompatible.
      Type '(t: T) => number' is not assignable to type '(t: {}) => number'.
        Types of parameters 't' and 't' are incompatible.
          Type '{}' is not assignable to type 'T'.
src/bug.tsx(32,18): error TS2322: Type '{ a: number; b: number[]; c: (x: number) => number; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Comp2<{}>> & Readonly<{ children?: ReactNode; }> &...'.
  Type '{ a: number; b: number[]; c: (x: number) => number; }' is not assignable to type 'Readonly<Props<{}>>'.
    Types of property 'c' are incompatible.
      Type '(x: number) => number' is not assignable to type '(t: {}) => number'.
        Types of parameters 'x' and 't' are incompatible.
          Type '{}' is not assignable to type 'number'.
```

**TypeScript Version:**  2.7.0-dev.20171224, 2.6.2

**Code**

```ts
import * as React from 'react';

interface Props<T> {
  a: T
  b: T[]
  c: (t: T) => number // This addition breaks it
}


class Comp2<T> extends React.Component<Props<T>> {
  render(){
    return null
  }
}


function Comp1<T>(props: Props<T>) {
    return <Comp2 {...props} /> // Error
}
  

const props = {
  a: 1,
  b: [2],
  c: (x: number) => x
}

const a = <Comp1 {...props} />

const b = <Comp2 {...props} /> // Same error

```

**Expected behavior:**

I expect it to work. It worked on 2.5.3

**Actual behavior:**

It breaks as soon as I add generic functions to the props

Config used:
```json
{
    "compilerOptions": {
      "outDir": "build/dist",
      "module": "commonjs",
      "target": "es5",
      "lib": ["es6", "dom"],
      "sourceMap": true,
      "allowJs": true,
      "jsx": "react",
      "moduleResolution": "node",
      "rootDir": "src",
      "forceConsistentCasingInFileNames": true,
      "noImplicitReturns": true,
      "noImplicitThis": true,
      "noImplicitAny": true,
      "strictNullChecks": true,
      "suppressImplicitAnyIndexErrors": true,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "strict": true
      //"noUnusedLocals": true
    },
    "exclude": [
      "node_modules",
      "build",
      "scripts",
      "acceptance-tests",
      "webpack",
      "jest",
      "src/setupTests.ts"
    ],
    "types": [
      "typePatches"
    ]
  } 
```

The example works as expected on 2.5.3.

### PR DESCRIPTION
**Pull request by weswigham**
Technically, stateless functional components _do_ do an inference pass internally during overload resolution, but `checkJsxAttributesAssignableToTagNameAttributes` doesn't use those results, since its agnostic to the component kind, but needs to have a correctly instantiated type in _all_ cases so inverted variance positions can be handled correctly in its assignability check.
Fixes #20891

### CODE REVIEW

File: tests/baselines/reference/tsxReactComponentWithDefaultTypeParameter3.errors.txt [hunk 1]
```diff
@@ -16,11 +20,15 @@ tests/cases/conformance/jsx/file.tsx(17,18): error TS2559: Type '{ a: string; }'
     
     // OK: we fille in missing type argument with empty object
```
Comment (sandersn) [inline tests/baselines/reference/tsxReactComponentWithDefaultTypeParameter3.errors.txt]: need to update comments here too (or move around the test cases I guess)

File: tests/baselines/reference/tsxReactComponentWithDefaultTypeParameter2.errors.txt [hunk 2]
```diff
@@ -1,31 +0,0 @@
...
-    interface Prop {
-        a: number,
-        b: string
-    }
-    
-    declare class MyComp<P = Prop> extends React.Component<P, {}> {
-        internalProp: P;
-    }
-    
-    // Error
```
Comment (sandersn) [inline tests/baselines/reference/tsxReactComponentWithDefaultTypeParameter2.errors.txt]: update this comment

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -15247,6 +15248,7 @@ namespace ts {
          *
          * @param openingLikeElement a non-intrinsic JSXOPeningLikeElement
          * @param shouldIncludeAllStatelessAttributesType a boolean indicating whether to include all attributes types from all stateless function signature
+         * @param sourceAttributesType Is the attributes type the user has actually passed, and is used to create interfences in the target type if present
```
Comment (sandersn) [inline src/compiler/checker.ts]: delete "has actually"
typo "inferences"

Comment (sandersn) [reply src/compiler/checker.ts]: As usual, I'm not convinced these `@param` tags are useful. The `@return` is, though.

Well, the second sentence for `elementType` is useful, I guess.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -15563,16 +15572,17 @@ namespace ts {
...
-            const targetAttributesType = isJsxIntrinsicIdentifier(openingLikeElement.tagName) ?
-                getIntrinsicAttributesTypeFromJsxOpeningLikeElement(openingLikeElement) :
-                getCustomJsxElementAttributesType(openingLikeElement, /*shouldIncludeAllStatelessAttributesType*/ false);
 
             // sourceAttributesType is a type of an attributes properties.
             // i.e <div attr1={10} attr2="string" />
             //     attr1 and attr2 are treated as JSXAttributes attached in the JsxOpeningLikeElement as "attributes".
             const sourceAttributesType = createJsxAttributesTypeFromAttributesProperty(openingLikeElement, checkMode);
 
+            // targetAttributesType is a type of an attributes from resolving tagName of an opening-like JSX element.
```
Comment (sandersn) [inline src/compiler/checker.ts]: is this code move important?

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -16430,6 +16440,24 @@ namespace ts {
             return getSignatureInstantiation(signature, getInferredTypes(context), isInJavaScriptFile(contextualSignature.declaration));
         }
 
+        function inferJsxTypeArguments(signature: Signature, sourceAttributesType: Type, context: InferenceContext): Type[] {
+            // Clear out all the inference results from the last time inferTypeArguments was called on this context
+            for (const inference of context.inferences) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: when is a context reused? I only see inferJsxTypeArguments being called right after creating a fresh context.

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts]: `sourceAttributesType` is now used in the `targetAttributesType` assignment expression; it's not just a code move.

File: src/compiler/checker.ts (hunk 5 above)
Comment (weswigham) [reply src/compiler/checker.ts]: Good point. It may be possible to reuse them in some way in the future, but I'm not doing so now.

File: src/compiler/checker.ts (hunk 4 above)
Comment (sandersn) [reply src/compiler/checker.ts]: Ah, I missed that. Thanks.
