### ISSUE TITLE
[3.5.1] Class index signature stopped working - property does not exist on type

### ISSUE THREAD

**Issue by aszczepanek** [microsoft/TypeScript#31691]
**TypeScript Version:**  3.5.1

**Search Terms:**
index signature, property does not exist

**Code**

```ts
export class Test {
  [k: string]: any;

  someMethod() {
    this.age = 3;
  }
}
```

**Expected behavior:**
There should be no error, age assignment is correct according to index signature.
It used to work in typescript 3.4.5

**Actual behavior:**
Error "Property 'age' does not exist on type 'Test'"

**Comment by ahejlsberg** [comment]
Argh, I recently fixed this in #31454, but neglected to update the separate code path we have for property access expressions.
