### ISSUE TITLE
Generic extending any becomes generic extending unknown

### ISSUE THREAD

**Issue by gportela85** [microsoft/TypeScript#39471]
**TypeScript Version:**  3.9.2 and 4.0.0 beta (works fine on 3.8.2 and below)

**Search Terms:** generic extend any unknown

**Expected behavior:** 
This code should compile just fine

**Actual behavior:** 
I get an error saying `Property 'error' does not exist on type 'T'.` Because `currentBaz: T extends unknown` instead extends `any. 

**Related Issues:**

**Code**
```ts
class Foo {
    public bar<T extends any>(baz: T[]): void {
        baz.forEach(currentBaz => {
            if (currentBaz.error) {
                console.log(currentBaz.error);
            }
        })
    }
}
```

<details><summary><b>Output</b></summary>

```ts
"use strict";
class Foo {
    bar(baz) {
        baz.forEach(currentBaz => {
            if (currentBaz.error) {
                console.log(currentBaz.error);
            }
        });
    }
}

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "declaration": true,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play/?ssl=9&ssc=2&pln=1&pc=1#code/MYGwhgzhAEBiD29oG8BQ0PQA4FcBGIAlsNHmAE4A8AKtAKYAeALnQHYAmMYrAngHwAKMgC8AXNGoBtALoBKcQDd4hdinSYNIgHQAzeOQCiYYAAsBwHOXJsmAITDDoAXj5qN7zIR3Rzl66zsHLTorfVk3D0iMYHhWCHgQOi0QeABzXysbe2Fg0PJZAG51KIwAX2L3UtkK8tKgA)

**Comment by IllusionMH** [comment]
This is intended change [Type Parameters That Extend `any` No Longer Act as `any`](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#type-parameters-that-extend-any-no-longer-act-as-any)

Also see discussion in that PR #29571

**Comment by gportela85** [comment]
@IllusionMH thanks
