### PR TITLE
record resolution for relative file name if file was found via absolu…

### LINKED ISSUE #2192: Compiler fails to find external module referenced by two different files
(Also posted on StackOverflow: https://stackoverflow.com/questions/28844917/typescript-cant-find-external-module-when-referenced-by-two-different-files)

I may be missing something obvious, but Typescript's module resolver for commonjs isn't working as expected.

Given the following directory structure and files:

* ./first/shared.ts
* ./first/second/class_a.ts
* ./first/second/class_b.ts
* ./third/class_c.ts

Where:

* class_a references shared.ts
* class_b references class_a.ts and class_c.ts
* class_c references shared.ts

Specifically:

shared.ts:
```typescript
class Shared{}
export = Shared;
```

class_a.ts:
```typescript
import Shared = require('../shared');
class A{}
export = A;
```
class_b.ts:
```typescript
import A = require('./class_a');
import C = require('../../third/class_c');
class B {}
export = B;
```
class_c.ts:
```typescript
import Shared = require('../first/shared');
class C {}
export = C;
```

All compile individually, except class_b.ts, using the following compiler invocation:

`tsc --module commonjs class_b.ts`

Compiling class_b.ts fails with the error that it can't find shared.ts:

`../../third/class_c.ts(1,25): error TS2307: Cannot find external module '../first/shared'.`

Note that if you reverse the order of imports in class_b.ts, you get a different error:

`class_a.ts(1,25): error TS2307: Cannot find external module '../shared'.`

It seems the compiler is finding shared.ts the first time it is imported, but not the second time.

This is with tsc 1.4.1.0.

### PR DESCRIPTION
**Pull request by vladima**
…te name. Fixes #2192.

The same file can be referenced using different relative names. For example:
```
 folder1
   |---folder2
   |      |---file1.ts
   |      |---folder3
```
if `folder3` is current directory then `file1.ts` can be referenced as `../file1.ts` or as `../../folder2/file1.ts`. Both these names are correct however now we'll record resolutions for both relative and and absolute names only for the first requested file i.e. `../file1.ts`. Subsequent request to find source file for `../../folder2/file1.ts` will fail to find it for relative name but will succeed to do it for absolute name and this result will be returned without recording association 'relative name' -> 'resolved file'. This means that calling `program.getSourceFile('../../folder2/file1.ts')` will return `undefined` though clearly this file is in the program. Solution: when lookup fails for relative name but succeeds for absolute - record association for relative as well. 

Also PR reduces nesting in `findSourceFile` and drops unnecessary calls to `CompilerHost.getCannonicalFileName` -  `FileMap` will do this internally anyways so there is no need to do it several times

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
I recall we made some optimization to avoid recalculating dependencies. Could there be an issue in caching for language service scenarios? For instance, let's say you have files `./A.ts` and `./B.ts`. It doesn't really matter what's in `B.ts`, it just matters that `A.ts` incorrectly references it:

```TypeScript
import "B";
```

Now you introduce `node_modules/B.d.ts`. Does the import of `B` suddenly work correctly?

**Comment by vladima** [comment]
@DanielRosenwasser no, it should be fine. We never directly interpret module name in import as file name. The whole process will look like:
- parse 'A.ts' 
- try to resolve imports in 'A' to actual module files
- (assuming that current module target is `CommonJS`) "B" is not relative name so run node resolution process to find module named "B". If it cannot be found then resolution fails and internally we'll record this in internal map on the `SourceFile`. `findSourceFile` will be called only if resolution succeeded.

**Comment by mhegazy** [comment]
:+1:
