### ISSUE TITLE
Expected 1 arguments, but got 2.ts(2554) error in reselect package after upgrading typescript 

### ISSUE THREAD

**Issue by jitenderchand1** [microsoft/TypeScript#45147]
# Bug Report

I am getting Expected 1 arguments, but got 2.ts(2554) error in `createSelector`  function from `reselect` after upgrading typescript to 4.1 from 4.0.5. 

The functionality is working fine as there is no change in reselect package. it is just typescript throwing type error. After adding  //@ts-ignore I was able to run my app but I could be figure the issue. 

<img width="830" alt="Screenshot 2021-07-22 at 9 21 42 PM" src="https://user-images.githubusercontent.com/19687185/126669482-da1ae5e9-d204-43f5-b562-4ca92f469e9d.png">

Note: The app was working fine with 4.0.5 version of typescript .

### 🕗 Version & Regression Information

```
"react": "17.0.2",
 "react-dom": "17.0.2",
 "react-scripts": "4.0.0",
 "reselect": "^4.0.0",
 "typescript": "4.1.3"
```

### ⏯ Playground Link

https://codesandbox.io/s/blissful-cache-9ow25?file=/src/App.tsx

### 💻 Code

```import "./styles.css";
import { createSelector } from "reselect";
export default function App() {
  const getAssignedInventoryLocations = createSelector(
    () => {},
    (locationList) => {
      return locationList;
    }
  );
  getAssignedInventoryLocations("first", "second");
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}
```

**Comment by RyanCavanaugh** [comment]
We'd need a version of this that didn't depend on `reselect` in order to investigate. The `createSelector` call has *97 overloads*; it's beyond human capacity to reason about what may have changed here.

**Comment by IllusionMH** [comment]
I think simplified example can be
```ts
declare function createSelector<S, R>(
	selector: (state: S) => R
): number;
declare function createSelector<S, P, R>(
	selector: (state: S, props: P, ...args: any[]) => R
): string;

// Resolves to first overload (returns function that expects only 1 argument in library)
const args0: string = createSelector(
	() => { }
);
const args1: string = createSelector(
	(state: number) => { state }
);

// Resolves to second overload (returns function that expects only 2+ arguments in library)
const args2: string = createSelector(
	(state: number, props: number) => { state + props }
);
```
[Playground](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210723#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzDigxAGUQJwMcYAeUgGngCUA+ACgFgAoASAGcKVGgC547fhmIgxpAJTwAvKxY85Y1MgC2AIxAwA3D1CRYCFOmx4CREuUqYa9JgAUmbLn0EPqMMRKkSWSYABxgcEP4xN3gAOnjYAHMo+ChUAE8AbQBdBWVVbnV4SRgsVESjbh4AemqWEH4cCAA3BvhqJCwYSXgcVpgIHChgcTgMZBhUfiQ0TFx8DAALYngQAA8Qqmm8CHT4AEZUmETtEFQMeDL4CCwdGFh0uR4wPB6k-gAGMRKyxKUbEDSezCGCeXjsPIqADe8AAvmpKi8phd3vtvhhSuV-oRAXYhI5QTxwZJpBptHoYJD4DCSSQ4QieDU6swGk1WtMOoIkSM+vpBsNRiBxpNphY5tYlit1ptMNtULt4AAmADURxOWjOGGmVxudweT24SLex34ivRmL+igBQPxvjBAVJ8E0un0oXCkTJLspSmhxUCCFVYQi03hhQMQA)

Return type for first two examples `args0`, `args1` will be from first overload which is `number` in simplified example and `<S, R>(state: S) => R` in lib.
Return type for third example `args2` will be from second overload which is `string` in simplified example and `<S, P, R>(state: S, props: P, ...args: any[]) => R` in lib.

Looks like it works as expected since in reported case non of selectors require 2 or more arguments therefore returned selector would expect only one argument - `state`.

**Comment by RyanCavanaugh** [comment]
Thanks for looking at it, @IllusionMH . If someone has a true regression-to-error here based on that repro (or anything else tractable), please log a new issue.

**Comment by jitenderchand1** [comment]
@IllusionMH Thanks for the answer, I have defined the argument in input selector. However, I have made one of them optional. in that case it is also throwing error. how can I get rid of this

https://codesandbox.io/s/blissful-cache-9ow25?file=/src/App.tsx

**Comment by IllusionMH** [comment]
For overloads order given in `reselect` definitions and the fact that function with one required parameter and other optional parameters still match first overload (that supposed to pass one argument to function) - first overload will be picked and it returns function that expects only one arguments.
As results you have correct suggestion that there is no need to pass second argument as no selectors would require it.

There may be few options:
1. Don't pass `props` as second parameters since none of selectors really depends on it.
1. Define selector as `(a: string, b: string | undefined) => {}` instead to make second parameter required and force corresponding overload, but the you won't be able to call selector with one argument.
1. Declare function like `callSelector` that would expect both `state` and `props`
1. Check in Redux/Reselect communities or StackOverflow what is preferred way to deal with selectors and their arguments.


Also picking first overload looks consistent with JS behavior in relation to `length` value of functions
```js
((state) => {}).length // 1
((state, props) => {}).length // 2
// but
((state, props = 'default') => {}).length // 1
```

**Comment by aqibnoborderz** [comment]
![Uploading Screenshot from 2022-05-30 15-44-31.png…]()
i wrote the apicode but in result and erro point it is giving ma error or expected one or 2 but got 3

any syuggestions how to solve this

**Comment by aqibnoborderz** [comment]
https://www.loom.com/share/f30c5642690b4c6a885105b15380ee9a

here is the loom
