### ISSUE TITLE
T implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer

### ISSUE THREAD

**Issue by pleerock** [microsoft/TypeScript#35546]
**TypeScript Version:**  3.7.3

**Code**

```ts
type Schema = {
    [key: string]: Number | String | Boolean | (() => Model<any>)
}

type Model<T extends Schema> = {

}

function model<T extends Schema>(type: Schema): Model<T> {
    return undefined as any
}

const User = model({
    id: Number,
    name: String,
    photo: () => Photo
})

const Photo = model({
    id: Number,
    filename: String,
    user: () => User
})
```

**Expected behavior:**

No errors. I need this technic to implement automatically inferred circular types. I already have a class-based implementation (you can see example [here](https://github.com/typeorm/typeorm/blob/master/docs/many-to-many-relations.md#bi-directional-relations)) and I basically want same with objects of course without manually defining its type. If it's not a bug, any advances on how to implement it keeping type inferred are highly appreciated. 

**Actual behavior:**

Gives following error:

`'User' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)`

**Playground Link:** http://www.typescriptlang.org/play/#code/C4TwDgpgBAygxgCwgWwIZQLxQN4FgBQURUA2gNYQgBcUAzsAE4CWAdgOYC6NAcgK7IAjCAygAfWI1ZsxUAEIB7eQBsIqFjIAUGgJSYAfFACy8gCYQlAHjUg92ggF8CBUJCOnzFgCpQIAD2AQLCa0sIgoqAZYePgOTvgAZrwscMBM8urI7pbefgFBIfBIaHoaLhA0heHaNMZm2QbRxFAMEMC8DOpJZvGsECZQqCHWsTH4cOn0UACqtMKYUJl1Go3ETCY8-EIMADQETSyoyOUSzOy7hMRgCPLA8jQ6+lAACte3Dnaj4yyTLzfy84tzMs9qt1lA+IJhOcmj0VAcjhVJGcQUReLMGPddBgDDNhO8CEA

**Comment by mttcr** [comment]
Hello,
I have another small snippet that shows a similar error:
```
class A<T>
{
	public readonly b = new B( this );
}
class B
{
	constructor( a: A<any> )
	{

	}
}
```

tsconfig.json:
```
{
	"compilerOptions": {
		"outDir": "build",
		"rootDir": ".",
		"alwaysStrict": true,
		"charset": "UTF8",
		"diagnostics": false,
		"experimentalDecorators": true,
		"keyofStringsOnly": true,
		"noEmitHelpers": true,
		"noImplicitAny": true,
		"noImplicitReturns": true,
		"noImplicitThis": true,
		"noUnusedLocals": true,
		"removeComments": false,
		"skipDefaultLibCheck": true,
		"skipLibCheck": true,
		"sourceMap": false,
		"strictBindCallApply": true,
		"suppressImplicitAnyIndexErrors": true,
		"target": "es5",
		"types": []
	},
}
```

output
```
C:\test>node_modules\.bin\tsc -version
Version 3.7.3

C:\test>node_modules\.bin\tsc
test.ts:3:18 - error TS7022: 'b' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

3  public readonly b = new B( this );
                   ~


Found 1 error.
```

It works with typescript 3.3.3.
It starts to fail with typescript 3.4.1.

The error happened when migrating our codebase from Typescript 3.2.2 to 3.7.3

**Comment by RyanCavanaugh** [comment]
Please only log bugs when a circularity error is issued when there *isn't* a circularity. These examples both contain plainly-visible cycles and the error is correct.

**Comment by mttcr** [comment]
Hm, ok, I just commented out because 
1. it was working on a previous version and so need to migrate a 1.5 million LOC typescript codebase
2. the build randomly fails: at first, I had no build error on my code base, i had some flacky errors in my CI builds (unfortunately, unable to reproduce) (could the error depend on the order of the files are processed? > see below)
3. The cycle is not that obvious as type B does not depend at all of the parameters of its constructors and is not generic. Type B is straightforward, so is attribute b in Type A, so I was thinking for type A. Sorry for the misunderstanding.

Also some checks :
```
class A<T> { public readonly b = new B( this ); }
class B { constructor( a: A<any> ) { } }
```
fails, ok.

```
class A<T> { public readonly b = new B( this ); }

class B { 
	public readonly a: A<any>;
	constructor( a: A<unknown> ) {
		this.a = a;
	}
}
```
fails, ok.
But, if I change the order of declarations of A and B:
```
class B { 
	public readonly a: A<any>;
	constructor( a: A<unknown> ) {
		this.a = a;
	}
}

class A<T> { public readonly b = new B( this ); }
```
No build error.
```
class B { 
	public readonly a: A<any>;
	constructor( a: A<any> ) {
		this.a = a;
	}
}

class A<T> { public readonly b = new B( this ); }
```
Fails (replaced _unknown_ by _any_)

**Comment by MickVanDuijn** [comment]
This also happens to me when I try to use the `aws-sdk`

```
import AWS from "aws-sdk";

async function handler() {
  const ssm = new AWS.SSM();
  const { Parameters = [], NextToken } = await ssm.getParametersByPath({ Path: "/prefix/" }).promise();
}
```

It infers `Parameters: AWS.ParameterList`, but gives me the same error on `NextToken`

```
'NextToken' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)
```

**Comment by Baldurans** [comment]
Having similar issue with very simple example

`
// ----------
// ALL OK here, myObject1 has all types detected
const myObject1 = {
    aaa: 50,
    bbb: () => {
        return myObject1.aaa;
    }
};

// ----------
// myObject2 has compilation error: (With strict mode ON)
// T implicitly has type 'any' because it does not have a type annotation
//     and is referenced directly or indirectly in its own initializer
const someFunc = (input: () => number): string => {
    input();
    return "test ";
};

const myObject2 = {
    aaa: 50,
    bbb: someFunc(() => {
        return myObject2.aaa;
    })
};
`

Would really want to know if this is temporary limitation or rather impossible to solve limitation?

**Comment by vshlos** [comment]
Small non-circular example. Error shows up on the line that says "error here"

Removing the line 2 down (the `property = records.property`, then there is no more error.
```javascript

export class Result {
    property?: string
}


export class MyObject {
    async get(property: string): Promise<Result> {
        return new Result();
    }
}

async function failingTest(queue: MyObject): Promise<void> {
    let property: string | null = null;
    let keepGoing = true;
    while (keepGoing) {
        if (!property) {
            property = "start";
        }
        const records = await queue.get(property); //ERROR HERE
        if (records.property) {
            property = records.property; //NO ERROR IF THIS LINE REMOVED
        }
        keepGoing = true;
    }
}
```

also if I break out the await onto 2 lines, the error goes away:
```javascript
...
        const promise = queue.get(property);
        const records = await promise;
...
```

**Comment by amatiasq** [comment]
Here's another snippet to reproduce it.

```ts
function setter<T>() {
	return <P extends keyof T>(key: P, handler: (self: T, val: T[P]) => void) => {
		return function(this: T, x: T[P]) {
            handler(this, x);
		};
	};
}

class Foo {
    readonly a: string = ''
	setA = setter<Foo>()('a', (self, val) => self)
}
```

[Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAZwKZSqgTgHgCoB8AFAJSIDeAUAJBbohZI4AKiqAHpmACbKIDWqAJ5xgiQkUFCAXImYAaRAAsAhjwA22WUTTrgsvIoBuK9QYDazALpkAvAURG4MbnYdVqteo0ShIsBCIoJRhkA0V2C2syKkQ4+IS41Q1sIJDkCJIAbhpqAF8c-Jy8ykoIdRVkPgAxODgKSgS6FW4EdSFEFVlkKCwYMABzRFtEAHJRmjQoAEFhlHRMXFq4YhIiUZVRxR1UPWNTN3m9EkoSoA)

**Comment by vobarian** [comment]
Simplified example:

```typescript
async function getAString(ignore?: string): Promise<string> {
  return "ok";
}

async function example() {
  let a: string | undefined = "a";
  for (let i = 0; i < 1; i++) {
    const b = await getAString(a); // ERROR
    a = b;
  }
}
```

Note:

- Error does not happen if the lines are not wrapped in a loop (even though it only loops once)
- Error does not happen if `| undefined` is removed on type of `a`
- Error does not happen if `a = b;` is removed or inlined to `a = await getAString(a);`
- Error does not happen if `getAString` is not async

[Playground Link](https://www.typescriptlang.org/play/#code/IYZwngdgxgBAZgV2gFwJYHsIwOYFNkCCAysgE6oTYAUq2E6puA-AFwwhkXYCUbACqXQBbVCFwAeDuUoA+GAG8AUDBiNkCUlgBE6ANZaA3IoC+ixaEixEKDFlwAPYEIAOAG1xVuC5THfIYwGxSXDAAPjBIACa4cBS4kTAAvDBawIY+cAwwVH4wqEkwAAwGeTDiMACMJagA1DVeSioqUJgcMABGBcAA7sCo-niEJNLUwNwlAPQTMACiAEpzAPJzPirABe1GKqbGQA)

I originally ran into this problem trying to use aws-sdk paginated service methods, which often have a `NextToken` property taking the place of `a` in my contrived example. The above was just as simplified as I could make it.

**Comment by swansontec** [comment]
I am getting this in an even simpler case:

```typescript
const [a, b = a] = [1]
```

You can [try it out](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=27&pc=1#code/MYewdgzgLgBA2gQwDQwEYwLwwQXU-ARhyA):

```
'a' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.
```

However, `a` should clearly be of type `number`, based on the way Javascript destructuring works.

**Comment by tianzhich** [comment]
I have a similar https://github.com/microsoft/TypeScript/issues/40279

**Comment by bolddp** [comment]
I came across this when the services in my backend needed to reference each other.

[Playground](https://www.typescriptlang.org/play?ts=3.8.3#code/MYGwhgzhAEDKCmAnAbgS2PAgtA3gKGmgiTQwCEAFRAezQBMkAuOVAOwHMR4AXa1gHgQp08MgD4A3AWjA+EbogCuwXogAUxYeSq1UDRM1htOPPoJIjxASlzTCs1hGpcAdCGrs1AciGksMuQVlVS8rKUJCbgALVAgXTT9KGnokaABeIgttZL0kcOgAX2lc1m5UADMATzUbfAiAx2d4Nw9vABUYmFjMrXhoTFD8osISsqrMEBAa23ro2JdRiuqwu2g5uITLHRTEF3YeGoWGUqWaobwivFBIGF9LGZ6-TG3cgxYOLl4BO4xMSWkHPIlCpqOpNr8XvpDMZPmYflgxLVVoCmi1PD4sqIGkDgqDBqt1vFMc8cvp0o8RCTdPpziNjmNlg97HJUe50R1ut1wX0yPjCMNoItxpNpnUIoShct8pFOkTelSdnsDlYjvATlUztIipdrlB3iYvvw2mIHmx5GBWBhmG18sBEPAwKpmNM0iabQDAsDVGo7Q6ndAXW6kbNZb7HaDyWHVLToPtuDVrUzBeUAwBCCWObgWjC1Nays1Zy19DKEqOgs6FVb27iKRCsPPzAvZ+DnS5XcB6+EAGWowHDiAeAAdFAAjEDoIhZsrACm-cmseAAd31sO+xLEakD0AXy-hmDU3d7-bliSsK0Iw7HE-N09nWIyO5XpjXvXEm5sru3S7gmLIB8xPZ9qoJ6UmeUiXIeQGgiBvxKvGKqShMUwrJBx7cmQcGHIhIorEAA)

**Comment by sKopheK** [comment]
Had updated my project that was with no TS error after 6 months and way too many errors popped up. If I count hours spend making TS compiler happy with a real benefits of it, TS clearly loses. Especially with changes like this, you can never be sure your code is fine after any update :(.

**Comment by rajeevnaikte** [comment]
Same issue troubling me while creating an utility for when-then chaining
![Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDqAWBTAdgFSc6BvAUNaA7hgBTAD2yAJgJYAu1FAXNMQJTQC8AfNAEZlkQiMMlZ5s4-ACdEtAK5TMufCui0MzddQgA6dSh29qVYloisANJOgBfANzibOcfuTFKiYNobJmbTjwiAJ5i+MoqMvKKEqr4RCia8No68ciGxpSmSeZWqvaOOE5AA)

**Comment by oldrich-svec** [comment]
I have the same issue with `await` keyword:

```
async function main() {
  const exec = (_: () => void): string => ''
  const fn = (_: number) => {}
  const y = await exec(() => fn(y))
  console.log(y)
}
```

Without `await` keyword I get

> Argument of type 'string' is not assignable to parameter of type 'number'.

With `await` keyowrd I get

> 'y' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

**Comment by sk-** [comment]
Here's another example with firebase auth and TS 4.2.3.

```js
const admin = require('firebase-admin');

async function test() {
  const auth = admin.auth();
  // The following 2 assignments work fine
  const result1 = await auth.listUsers(/** maxResult= */ 1000);
  const result2 = await auth.listUsers(/** maxResult= */ 1000, /** pageToken= */ undefined);
  /** @type {string | undefined} */
  let pageToken = 'token';
  while(true) {
    const result3 = await auth.listUsers(/** maxResult= */ 1000, pageToken);
    // If you comment the following line TS does not complain (but the code obviously won't work)
    pageToken = result3.pageToken;
    if (pageToken === undefined) {
      break;
    }
  }
}
```

**Comment by s97712** [comment]
I have the same issue [playground](https://www.typescriptlang.org/play?#code/N4WAUABBDGD2B2BnALhAFgUwDYAcMCcIBeCACgDcAuCYAXwEpiA+GiW8KOJVZDFYmhygQAhmOqZcBUqEjCo+DADNqpekSa8UAOjEihUBgBoh7MGfCzOCfpLyESFasAiKVZRhojlYASwAmbJ4sLmbW3BBaqCRWwnoS2PYyBsJuqsGRfMi6YinGpuC0QA).

```ts
  const helper = (v: {}) => { }
  const test = {
    aaa: helper({
      ref: ()=> test.aaa
    }),
  }

```
It's OK.

However, when I declaring the argument type of the helper function:
```ts
  const helper = (v: { ref: () => void }) => { }
  const test = {
    aaa: helper({
      ref: () => test.aaa
    }),
  }
```
I get the error:
`'test' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

**Comment by dustin-rcg** [comment]
Here's another example:

Code:

```
async function main() {
  let lastCursor: string | null = null;
  for (;;) {
    const { ids, cursor } = await request<{ ids: number[]; cursor: string}>({ cursor: lastCursor });
    lastCursor = cursor;
    if (!ids.length) break;
  }
}

async function request<T>({ cursor }: { cursor: string | null }) {
  return "whatever" as unknown as T;
}
```
Actual result: `'cursor' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.(7022)`

Typescript version 4.5.4

See [Playground](https://www.typescriptlang.org/play?#code/IYZwngdgxgBAZgV2gFwJYHsIwLbFRACgEoYBvAKBhgBsBTZG0ZAYQQCcR02AuGEZNvgDmMAD4wICatRgBeCVOoBuSvC4wCSpSQpUqUTPzIxUAExAAaGFHac2MAL5yYwAO54GbWgEcEtfgA8pCbmvJLYAEa0bADaALpK1rZcvPyCEEIOAHwEwTYcKYz8rAX2DkQqekUsyfby+XaVeqhwGgCEZiAAdHQZyAAWJBFewADWTQ7kk+SgkLCIKBhYXr7+yAEAKjl5tY68O6WpAsJiCtKOOqpeyOxYAESu-cDItABu0XcuIDBIoxDoriwoBgGxUDiAA)

Comment: This is a common pattern for iterating over paginated results using a cursor. The error goes away if I write
```
lastCursor = cursor as any;
```

**Comment by shaanaliyev** [comment]
Graphql example:


```
// typeDefs/comments.ts
const commentTypes = {
  comment: new GraphQLObjectType({
    name: 'Comment',
    fields: () => ({
      id: { type: graphql.GraphQLID },
      comment: { type: graphql.GraphQLString },
      customerId: { type: graphql.GraphQLString },
      customer: customer.external.getCustomerById, // <-
    }),
  }),
};
```
and 
```
// typeDefs/customers.ts
const customerTypes = {
  customer: new GraphQLObjectType({
    name: 'Customer',
    fields: () => ({
      id: { type: graphql.GraphQLString },
      username: { type: graphql.GraphQLString },
      email: { type: graphql.GraphQLString },
      password: { type: graphql.GraphQLString },
      comments: comment.external.commentsByCustomer, // <-
    }),
  }),
};
```
Here, the customer and comments part of the fields overlapped with each other.
I solved the problem by simply adding a type specifier.
`{ customer: GraphQLObjectType }` for `customerTypes` as `const customerTypes: { customer: GraphQLObjectType } = { ...`
and
`{ comment: GraphQLObjectType }` for `commentTypes` as `const commentTypes: { comment: GraphQLObjectType } = { ...`

In this case, you need to pay attention to the Graphql Depth Limit.

**Comment by ranma42** [comment]
Another example:
```ts
type Foo = { x: number };

async function bar(arg: Foo): Promise<void> {
  let foo: Foo | undefined = arg;

  while (foo) {
    const x = foo.x; // ERROR 7022
    foo = await makeFoo(x);
  }
}

function makeFoo(x: number): Foo | undefined {
  return Math.random() ? { x } : undefined;
}
```
[Playground](
https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvKAPAXFAdgVwFsAjCAJygF8BuAWACgGBDAZxFwGMoAzfT4AJZxcUYkzIAKcQHMc8OAEocABTJxCAlhAA8ANzgCAJgD40DKFAA2EYDwRyEUAD5Q+hiNwG4Ih5FBl0jPQWAO4AFgLWUBLcCApmwRZQHMIsthh+sXAAdBjUUAD0BVAAogBKZQDyZVAA7AAMAEyN5klZfkwhTAK2hEwA1hDyEhgKgRaUDJNBvPxCIn2Dw9h4RKRkSrCOLm4eXj4JFmQ2+GQiALJMwGHZZEy4huoS8QD8aJhUUDi7nt6GgZQgA)

**Comment by gfernandez-me** [comment]
@RyanCavanaugh

**Comment by ranma42** [comment]
@RyanCavanaugh is [this snippet](https://github.com/microsoft/TypeScript/issues/35546#issuecomment-1090193062) considered wrong or should I post it in a separate issue?
It would be very useful to have some explanation on why the compiler/ide/playground correctly types `foo.x` as `number` but is unable to propagate this type to the new `const x` binding.
iiuc this has something to do with `async/await` (namely, the same code snippet compiles just fine if I remove `await`)

**Comment by RyanCavanaugh** [comment]
That snippet has a circularity, so it's not a bug if a circularity error is issued.

**Comment by ranma42** [comment]
> That snippet has a circularity, so it's not a bug if a circularity error is issued.

The circularity is not very obvious (it looks like in all of the places where it is needed, the code already specifies an explicit type).
Additionally, it is quite unexpected that adding/removing `await` changes the circularity.

**Comment by ranma42** [comment]
I did not mean to just ask "fix my problem" and I probably failed to explain what I considered the wrong/weird behavior, sorry.

I agree that if my code is broken just because of circularity issues it is not worth fixing as a special case, but I would expect a consistent behavior between `await` vs non-`await`.
Instead, if the compiler error is a glitch introduced by (some internal desugaring of) `await` it might be worth investigating.

In the following snippets I am trying to explain the issue more in detail by expanding (my mental model of) what the compiler should infer about the code.
Note that I might be very wrong: this would explain why I do not understand the compiler responses; unfortunately the tools I tried (tsc/ide/playground) did not help me much, so I would appreciate a lot the insight of someone who knows the inner details of `tsc` and/or can provide a different mental model so that I can fix my expectation and reasoning.

Without `await` everything works just as I would expect:
```typescript
type Foo = { x: number };

async function bar(arg: Foo): Promise<void> {
  let foo: Foo | undefined = arg;
  // I assume that here the compiler knows foo: Foo | undefined; arg: Foo
  while (foo) {
    // I assume that here the compiler knows foo: Foo; arg: Foo;
    const x = foo.x;
    // I assume that here the compiler knows foo: Foo; arg: Foo; x: number
    foo = makeFoo(x);
    // I assume that here the compiler knows foo: Foo | undefined; arg: Foo; x: number
  }
}

function makeFoo(x: number): Foo | undefined {
  return Math.random() ? { x } : undefined;
}
```

With `await` apparently my assumptions do not hold true anymore:

```typescript
type Foo = { x: number };

async function bar(arg: Foo): Promise<void> {
  let foo: Foo | undefined = arg;
  // I assume that here the compiler knows foo: Foo | undefined; arg: Foo
  while (foo) {
    // I assume that here the compiler knows foo: Foo; arg: Foo;
    const x = foo.x;
    // I assume that here the compiler knows foo: Foo; arg: Foo; x: number
    // in fact, the playground infers `foo.x: number`, but apparently the type is not propagated to `x`
    // instead the compilation fails with an error
    foo = await makeFoo(x);
    // I assume that here the compiler knows foo: Foo | undefined; arg: Foo; x: number
    // but given the previous error, I am unsure if this makes sense at all
  }
}

function makeFoo(x: number): Foo | undefined {
  return Math.random() ? { x } : undefined;
}
```

Could you help me find out why it behaves differently with/without `await`?

I am not very knowledgeable of the internals of `tsc`, but I would definitely love to help fixing this if it considered a bug in the handling of `await` 😇 .

**Comment by RyanCavanaugh** [comment]
Please don't interpret any of this as impatience or offense; I'm not sure why this happens either and also find it odd!

What I'm trying to say is that circularity errors on circularities are not per se defects, and I'm not going to reallocate finite team resources away from fixing defects or implementing features toward addressing non-defects.

> Could you help me find out why it behaves differently with/without await?

The investigation itself here is the resource spend that I'm trying to avoid. Figuring out why a thing happens is usually 80% of fixing it.

**Comment by dustin-rcg** [comment]
> I am not very knowledgeable of the internals of `tsc`, but I would definitely love to help fixing this if it considered a bug in the handling of `await` 😇 .

`await` handles recursive promises, so it handles the types T, Promise<T>, Promise<Promise<T>>, ... for some T. I guess that there is a recursive type definition relating to promises (e.g. Awaited<T>) in the typescript codebase, which is where the circularity comes from, but not visible in our code examples.

**Comment by ranma42** [comment]
> `await` recursively resolves promises, so it resolves the types `T`, `Promise <T>`, `Promise<Promise<T>>`, ... etc. all down to just `T`, for some `T`. I guess that there is a recursive type definition relating to promises (e.g. `Awaited<T>`) in the typescript codebase, which is where the circularity comes from, but not visible in our code examples.

I tried reproducing it under this assumption and it looks the issue is not in the recursive type.
This does not compile even though the `await` has been replaced with a (trivial) polymorphic identity function.
```ts
type Foo = { x: number };

async function bar(arg: Foo): Promise<void> {
  let foo: Foo | undefined = arg;

  while (foo) {
    const x = foo.x; // ERROR 7022
    foo = myawait(makeFoo(x));
  }
}

function myawait<T>(x: T): T {
  return x;
}

function makeFoo(x: number): Foo | undefined {
  return Math.random() ? { x } : undefined;
}
```
Conversely, defining
```typescript
function myawait(x: Foo | undefined): Foo | undefined {
  return x;
}
```
would make the problem go away.

Another option is assigning a name to the result of `makeFoo(x)`; this compiles successfully:
```typescript
type Foo = { x: number };

async function bar(arg: Foo): Promise<void> {
  let foo: Foo | undefined = arg;

  while (foo) {
    const x = foo.x;
    const temp = makeFoo(x);
    foo = await temp;
  }
}

function makeFoo(x: number): Foo | undefined {
  return Math.random() ? { x } : undefined;
}
```

(the same code works even if `makeFoo` returns a `Promise`).
I guess that depends on how the type inference is driven (around loops and bindings?)

**Comment by LoganDark** [comment]
Posting here because this lint can show up when using default arguments.

```ts
export const X = { // typescript: 'X' implicitly has type 'any' because it does not have a type
	y: 5,      // annotation and is referenced directly or indirectly in its own initializer. (7022)
	z(_: number = X.y) {}
}
```

This doesn't happen in a class:

```ts
export class X { // no error
	static y = 5
	z(_: number = X.y) {}
}
```

The solution is to move the default into the body of the function:

```ts
export const X = { // no error
	y: 5,
	z(w?: number) {
		w ??= X.y
		// ...
	}
}
```

But in JS, the default argument is evaluated at call time, so it's not like Python where `X` is evaluated while the function object is being created. Even though I suppose it's possible to use something like an IIFE to call the function before `X` is finished initializing, TypeScript has enough flow analysis to make this an error:

```ts
export const X = { // typescript: 'X' is declared here.
	y: 5,
	z: ((w?: number) => {
		w ??= X.y // typescript: Block-scoped variable 'X' used before its declaration. (2448)
	})() // <--
}
```

and this not an error:

```ts
export const X = {
	y: 5,
	z: ((w?: number) => {
		w ??= X.y
	}) // <--
}
```

Default arguments should be handled like that as well, as evaluated only at call time.

Let me know if I should open a separate GitHub issue for this... since if all flow analysis makes this incorrect assumption, that would be a separate issue. But I think it might be just this lint, which rejects code that would otherwise be accepted.
