### ISSUE TITLE
Regression: Fix for error ts2657 no longer works

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript#43454]
# Bug Report

```tsx
const test = <a></a><b></b>
```

should have code fix

### 🕗 Version & Regression Information

Not works in 4.3.0-dev.20210329. Introduced in #37917 

### 🙁 Actual behavior

No code fix available

### 🙂 Expected behavior

Have code fix
