### PR TITLE
allowSyntheticDefaultImports resolves to modules instead of variables

### LINKED ISSUE #10429: Compilation errors with enabled `allowSyntheticDefaultImports` on 2.1 nightly
**TypeScript Version:**  2.1.0-dev.20160819

**Code**

self-contained project here: https://github.com/Strate/typescript-issues

**Expected behavior:**
No compilation errors

**Actual behavior:** 
If `allowSyntheticDefaultImports` *enabled* project compilation fails with:
```
3 let a = SomeClass.SomeEnum.one;
                    ~~~~~~~~

index.tsx(3,19): error TS2339: Property 'SomeEnum' does not exist on type 'typeof "/devel/src/github/Strate/typescript-issues/modules/SomeClass"'.


5 let b = <SomeClass />;
           ~~~~~~~~~

index.tsx(5,10): error TS2604: JSX element type 'SomeClass' does not have any construct or call signatures.
```
If `allowSyntheticDefaultImports` *disabled* project compilation succees
Typescript on version 2.0 beta works perfectly.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #10429 by improving the fix in #10096.

#10096 allowed aliasing of default imports, but did so by treating the module as a variable and resolving names on this 'variable'. This changes the check introduced in #10096 to resolve the name as a module if resolving the name on a module fails.

### CODE REVIEW

**Comment by sandersn** [comment]
@vladima @mhegazy can you take a look?

**Comment by mhegazy** [comment]
👍

**Comment by weswigham** [comment]
:+1:
