### ISSUE TITLE
Build:Property 'document' does not exist on type 'HTMLElement'

### ISSUE THREAD

**Issue by ChungNNVN** [Microsoft/TypeScript#15652]
**TypeScript Version:**  2.3 / nightly (2.2.0-dev.201xxxxx)

**Code**
public button: HTMLElement;
var doc= this.button.document;
```ts
Hi Guys,
I got build error after update project from TypeScript 1.1 to 2.3. I used Manage NutGet Packages option in Visual Studio 2015/2017
If I updated to TypeScript 1.1, this error will be passed build.

Please have a look on it, Thanks.
```

**Expected behavior:**
Build success in TypeScript 1.1 and can get document of button (HTMLElement)
**Actual behavior:**
Error when build in TypeScript 2.3: Property 'document' does not exist on type 'HTMLElement'

**Comment by mhegazy** [comment]
The standard library file changes with the different releases including bug fixes and removals of non-standard definitions. 

I could not find any definition in webstandard for `document` property on `HTMLButtonElement`. if you are confident that exists at run-time in your environment you can add

```ts
interface HTMLElement {
     document: Document;
}
```

**Comment by SaschaNaz** [comment]
Probably `ownerDocument` is what you want?

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
