### ISSUE TITLE
Strict object literal check fails when infered to type containing string literal type

### ISSUE THREAD

**Issue by erichillah** [Microsoft/TypeScript#7085]
Hi,
This issue might be linked to #6167 ( particularly widening i guess) or #6554,  but i did not find any details the bellow case: 
```typescript

interface Test {
	value: string;
	comparator:"equals"|"isGreater";
}

function applyTest(value: string, testval:Test) {
	return "ok";
}

let tt = {value: "test", comparator:"equals"};
applyTest("ko",tt);

```` 
when i compile using tsc (typescript@1.9.0-dev.20160215) i get a warning
```
test.ts(11,16): error TS2345: Argument of type '{ value: string; comparator: string; }' is not assignable to parameter of type 'Test'.
  Types of property 'comparator' are incompatible.
    Type 'string' is not assignable to type '"equals" | "isGreater"'.
      Type 'string' is not assignable to type '"isGreater"'.
```

**Comment by weswigham** [comment]
Apply a type annotation such as `let tt: Test = { ... }`. TS only infers string literal types in type positions and when contextually appropriate based on type information. Since TS doesn't do use-site analysis, `tt` gets typed soled by its definition, which is `{value: string, comparator: string}`, as there's no casts/annotations indicating it should use a literal type.
