### ISSUE TITLE
Definitions fail with duplicate namespace has no exported member after upgrade to 2.3.0 

### ISSUE THREAD

**Issue by tcoopman** [Microsoft/TypeScript#15400]
**TypeScript Version:**  2.3.0

The openlayers type definitions fail after an upgrade to typescript 2.3.0 (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15943#issuecomment-296960129) with an error that I can't explain by reading what's new (https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript).
I tried to create a PR to fix the issue, but that didn't work (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16139)

I also tried to create a minimal test case, but I haven't found a working minimal version yet.

**Comment by mhegazy** [comment]
@sandersn can you take a look

**Comment by tcoopman** [comment]
I've been able to create a minimal failing version:

index.d.ts
```ts
declare type GlobalObject = Object;

declare module ol {

    module color {
        function asArray(color: (ol.Color | string)): ol.Color;
    }
    type Color = ([number, number, number, number] | Uint8Array | Uint8ClampedArray);
   
    /**
     * @typedef {Array.<number>} ol.TileCoord
     */
    type TileCoord = [number, number, number];
}

declare module "openlayers" {
    export = ol;
}
```
And the failing test:
```ts
let color: ol.Color;
color = [255, 255, 255, 1.0];
color = ol.color.asArray(color);
```

This code works with 2.2.2 but gives this error with 2.3.0
```
index.d.ts(6,37): error TS2694: Namespace 'ol.ol' has no exported member 'Color'.
index.d.ts(6,58): error TS2694: Namespace 'ol.ol' has no exported member 'Color'.
```

If you remove this line: `@typedef {Array.<number>} ol.TileCoord`, the error is gone.

**Comment by tcoopman** [comment]
I cannot reproduce this with typescript 2.3.1, closing

**Comment by martinduparc** [comment]
Same problem with TypeScript 2.4
```node_modules/@types/openlayers/index.d.ts(146,30): error TS2694: Namespace 'ol.ol' has no exported member 'Collection'.
node_modules/@types/openlayers/index.d.ts(263,34): error TS2694: Namespace 'ol.ol' has no exported member 'Collection'.
node_modules/@types/openlayers/index.d.ts(291,37): error TS2694: Namespace 'ol.ol' has no exported member 'Color'.
```

**Comment by ashubham** [comment]
@sandersn I see the exact errors as @tcoopman is seeing albeit with `typescript 2.4.0`.
