### ISSUE TITLE
[Bug]: Control flow analysis fails to narrow Discriminated Union when destructuring in loop

### ISSUE THREAD

**Issue by mahjandora** [microsoft/TypeScript#63687]
### 🔎 Search Terms

discriminated union destructuring loop narrowing control flow

### 🕗 Version & Regression Information

This occurs in v5.4.2 and is still present in the latest typescript@next.

### 💻 Code

```ts
type Action = { type: 'A'; payload: string } | { type: 'B'; count: number };
const actions = [
  { type: 'A', payload: 'test' },
  { type: 'B', count: 42 }
] satisfies readonly Action[];
for (const { type, ...rest } of actions) {
  if (type === 'A') {
    // Error: Property 'payload' does not exist on type '{ payload: string; } | { count: number; }'
    console.log(rest.payload); 
  }
}

```

### 🙁 Actual behavior

The control flow analyzer fails to retain the narrowed type if the discriminant is destructured in the for...of loop declaration.

### 🙂 Expected behavior

The type guard on `type === 'A'` should successfully narrow the `rest` object to `{ payload: string }`.

**Comment by mahjandora** [comment]
I realize this is a known limitation where destructuring breaks control flow narrowing (tracked in #41548). Checking the discriminant on the parent object (action.type) directly resolves the inference issue. Apologies for the duplicate.
