### ISSUE TITLE
Uint8Array constructor doesn't accept possibly undefined argument

### ISSUE THREAD

**Issue by seishun** [microsoft/TypeScript#38446]
**TypeScript Version:**  Version 4.0.0-dev.20200509

**Search Terms:** uint8array optional parameter

**Code**

(with `"strictNullChecks": true`)

```ts
function from(ab: ArrayBuffer, offset?: number, length?: number) {
  return new Uint8Array(ab, offset, length);
}
```

**Expected behavior:**

The code compiles since the second and third parameters of the ArrayBuffer overload are optional per the [spec](https://tc39.es/ecma262/#sec-typedarray-buffer-byteoffset-length).

**Actual behavior:**

```
error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

**Playground Link:** 

[Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200508#code/GYVwdgxgLglg9mABMATnAtgCgIYCMBciAgiitgJ4BCIwwApigDSJy0DOdUA-IWCOrgbMANnTABzKAAseiPgIYBKRAG8AsAChEiFJxAokYOgHdEAVRhgoADhJlyOXM1bAOUEWMlTFAbk0BfIA)

**Related Issues:** 

Introduced in https://github.com/microsoft/TypeScript/pull/18367.

**Comment by MicahZoltu** [comment]
https://github.com/microsoft/TypeScript/blob/7b03835b779950e926a7281030fcf9b4dc4d5ffd/src/lib/es5.d.ts#L2211-L2215

Consider removing `ArrayBufferLike` from the middle overload when changing the last overload to have an optional second parameter.
```ts
new(length: number): Uint8Array; 
new(arrayOrArrayBuffer: ArrayLike<number>): Uint8Array; 
new(buffer: ArrayBufferLike, byteOffset?: number, length?: number): Uint8Array; 
```
