### ISSUE TITLE
Compilation errors with enabled `allowSyntheticDefaultImports` on 2.1 nightly

### ISSUE THREAD

**Issue by Strate** [Microsoft/TypeScript#10429]
**TypeScript Version:**  2.1.0-dev.20160819

**Code**

self-contained project here: https://github.com/Strate/typescript-issues

**Expected behavior:**
No compilation errors

**Actual behavior:** 
If `allowSyntheticDefaultImports` *enabled* project compilation fails with:
```
3 let a = SomeClass.SomeEnum.one;
                    ~~~~~~~~

index.tsx(3,19): error TS2339: Property 'SomeEnum' does not exist on type 'typeof "/devel/src/github/Strate/typescript-issues/modules/SomeClass"'.


5 let b = <SomeClass />;
           ~~~~~~~~~

index.tsx(5,10): error TS2604: JSX element type 'SomeClass' does not have any construct or call signatures.
```
If `allowSyntheticDefaultImports` *disabled* project compilation succees
Typescript on version 2.0 beta works perfectly.

**Comment by admmasters** [comment]
Yeah I'm getting issues with allowSyntheticDefaultImports as well for my TSX components that use default exports. Getting `error TS2604: JSX element type 'TestItem' does not have any construct or call signatures.` etc. All the errors go away when allowSyntheticDefaultImports is disabled.

**Comment by sandersn** [comment]
Looks like this was introduced by #10096. Commenting out the 3 lines of that PR makes the error go away.

**Comment by sandersn** [comment]
#10096 allows you to import `default` and give it an alias even from a module without an explicit `export default`, but it looks like it's interfering with the real `export default class SomeClass`.

**Comment by sandersn** [comment]
Yes, it is interfering. @vladima helped me improve #10096 so that it doesn't any more.
