### PR TITLE
Deprioritize declaration emit paths from baseUrl containing node_modules

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes `error TS2742: The inferred type of 'resolveParserPlugins' cannot be named without a reference to 'packages/compiler-core/node_modules/@babel/parser/typings/babel-parser'. This is likely not portable. A type annotation is necessary.` reported in #57117. (It bisected to #55015, though it’s not clear why, and doesn’t seem like that PR directly introduced the buggy behavior.)

Also worth noting that Vue should almost certainly not be using `baseUrl` at all.

### CODE REVIEW

**Review by sheetalkamat — APPROVED** [review]

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
Does this need a cherry-pick or are we okay with a temporary break in the beta?

**Comment by andrewbranch** [comment]
IMO the beta only exists to be a timestamp; it’s not a build anyone should use. Every beta is expected to have all the features and none of the bugfixes.

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick to release-5.4
