### ISSUE TITLE
Object Properties Spread with Generic Object Types not allowed

### ISSUE THREAD

**Issue by kitsonk** [Microsoft/TypeScript#15792]
**TypeScript Version:**  2.3.2

**Code**

[Playground Example](http://www.typescriptlang.org/play/#src=class%20Foo%3CP%3E%20%7B%0A%20%20setProperties(props%3A%20P)%20%7B%0A%20%20%20%20const%20newProps%20%3D%20%7B%20...props%20%7D%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Bar%3CP%20extends%20object%3E%20%7B%0A%20%20setProperties(props%3A%20P)%20%7B%0A%20%20%20%20const%20newProps%20%3D%20%7B%20...props%20%7D%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Baz%3CP%20extends%20%7B%20%5Bprop%3A%20string%5D%3A%20any%3B%20%7D%3E%20%7B%0A%20%20setProperties(props%3A%20P)%20%7B%0A%20%20%20%20const%20newProps%20%3D%20%7B%20...props%20%7D%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Qat%3CP%20extends%20object%20%3D%20object%3E%20%7B%0A%20%20setProperties(props%3A%20P)%20%7B%0A%20%20%20%20const%20newProps%20%3D%20%7B%20...props%20%7D%3B%0A%20%20%7D%0A%7D)

```ts
class Foo<P> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}

class Bar<P extends object> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}

class Baz<P extends { [prop: string]: any; }> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}

class Qat<P extends object = object> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}
```

**Expected behavior:**

That properties are spread on class `Bar`, class `Baz`, and class `Qat`.

**Actual behavior:**

All three cases report that `Spread types may only be created from object types.`  In all cases, the generic could be inferred to be of an object type, so the restriction seems to be arbitrary.

**Comment by mhegazy** [comment]
This is tracked by #10727 and fixed by #13288

**Comment by timocov** [comment]
@mhegazy but it works in 2.2.1 - it is blocker to updated to 2.3 for us :-(

**Comment by mhegazy** [comment]
> @mhegazy but it works in 2.2.1 - it is blocker to updated to 2.3 for us :-(

Not sure what you mean by that, this has always been an error..

```sh
c:\test>type b.ts
class Foo<P> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}

class Bar<P extends object> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}

class Baz<P extends { [prop: string]: any; }> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}

class Qat<P extends object> {
  setProperties(props: P) {
    const newProps = { ...props };
  }
}

c:\test>node c:\releases\2.2.1\tsc.js --version
Version 2.2.1

c:\test>node c:\releases\2.2.1\tsc.js b.ts
b.ts(3,24): error TS2698: Spread types may only be created from object types.
b.ts(9,24): error TS2698: Spread types may only be created from object types.
b.ts(15,24): error TS2698: Spread types may only be created from object types.
b.ts(21,24): error TS2698: Spread types may only be created from object types.

c:\test>node c:\releases\2.2.2\tsc.js --version
Version 2.2.2

c:\test>node c:\releases\2.2.2\tsc.js b.ts
b.ts(3,24): error TS2698: Spread types may only be created from object types.
b.ts(9,24): error TS2698: Spread types may only be created from object types.
b.ts(15,24): error TS2698: Spread types may only be created from object types.
b.ts(21,24): error TS2698: Spread types may only be created from object types.

c:\test>node c:\releases\2.3.2\tsc.js --version
Version 2.3.2

c:\test>node c:\releases\2.3.2\tsc.js b.ts
b.ts(3,24): error TS2698: Spread types may only be created from object types.
b.ts(9,24): error TS2698: Spread types may only be created from object types.
b.ts(15,24): error TS2698: Spread types may only be created from object types.
b.ts(21,24): error TS2698: Spread types may only be created from object types.
```

do you mean spread in JSX?

**Comment by timocov** [comment]
Oh, sorry - yes, we have this error in JSX. I just have decided that is the same errors - the symptoms very similar :)

**Comment by mhegazy** [comment]
That is tracked by https://github.com/Microsoft/TypeScript/issues/15742, fixed by https://github.com/Microsoft/TypeScript/pull/15789, and should be in TS 2.3.3 (out next week).

The fix should be in `typescript@next` already, give it a try and let us know if you are still running into issues.

**Comment by timocov** [comment]
@mhegazy This problem is gone, thanks!
