### ISSUE TITLE
Control flow type analysis error with type parameter

### ISSUE THREAD

**Issue by Agamnentzar** [Microsoft/TypeScript#9618]
**TypeScript Version:**  2.0.0 (typescript@beta)

**Code**

```ts
// test.ts
function test<T>(data: string | T) {
  if (typeof data === 'string') {
    return JSON.parse(data);
  } else {
    return data;
  }
}
```

**Expected behavior:**
Compile without error

**Actual behavior:** 
`test.ts(4,23): error TS2345: Argument of type 'string | T' is not assignable to parameter of type 'string'.
  Type 'T' is not assignable to type 'string'.`

Works fine in typescript@1.8.10 and earlier

**Comment by sandersn** [comment]
The reason this happens is that the new narrowing logic looks at each member of the union in turn to see if it can be eliminated by the guard: `string` is not eliminated by the guard 'typeof data === "string"`. But `T` is not eliminated by the guard either, since a `T` on its own could be `string`. 

This is wrong in the union case &mdash; `T` should not include `string` and should be eliminated by the guard. I'll look at how to fix it.

**Comment by sandersn** [comment]
After discussing with @RyanCavanaugh and @weswigham, I put a possible fix up at #10103. It turns out `T` is *technically* correct in the first branch: what if `T='literal type'` ? And Typescript has no way to express "T could be any type *except* string".

Instead, to express that idea that the type guard asserts that `data` is *at least* string, even if it happens to be `T`, the fix is to intersect `string | T` with `string & T` to get `(string | T) & string & T`. This ensures that all members from all types that pass the type guard are available in the body of the `if`.
