### ISSUE TITLE
Invoking methods from object iteration

### ISSUE THREAD

**Issue by DataTables** [Microsoft/TypeScript#13530]
**TypeScript Version:**  2.1.5

**Code**

```ts
class Params {
	public paramsInit () {
		for ( let prop in this ) {
			if ( typeof this[ prop ] === 'function' ) {
				let res = this[ prop ]();
			}
		}
	}
}

class Test extends Params {
	constructor () {
		super();
		this.paramsInit();
	}

	public param1 (): void {
		console.log( 'param1' );
	}
}
```

**Expected behavior:**

In TypeScript 2.0 the above compiles without any errors.

**Actual behavior:**

In TypeScript 2.1.5 I get:

> test.ts(5,15): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'Params[keyof this]' has no compatible call signatures.

I can see why tsc might not like invooking `this[ prop ]`, but I can't see any way to tell it that it is a valid function. I've tried using `as` in various combinations, but with no luck.

Is there a way to get this to compile in 2.1 without errors?

**Comment by ahejlsberg** [comment]
This works:

```ts
class Params {
    public paramsInit () {
        for ( let prop in this ) {
            if ( typeof this[ prop ] === 'function' ) {
                let res = (this[ prop ] as any)();
            }
        }
    }
}
```

**Comment by DataTables** [comment]
Thanks! Yes, that allows a clean compile with tsc 2.1.5.

So I guess the question becomes, is the 2.0 or 2.1 behaviour correct?

**Comment by ahejlsberg** [comment]
The current behavior is correct. The call without a type assertion is clearly not type safe, but previously we were not equipped to track the type of a computed property access so we would give an implicit `any` type to `this[prop]` (and you'd get an error with `--noImplicitAny`). Now, because of indexed access types (a.k.a. "lookup types") we can do a better job.

**Comment by DataTables** [comment]
Awesome - thanks very much.

Others have said it many times, and I as well, but going to say it again - TypeScript is excellent and a credit to all involved!
