### PR TITLE
Make contravariant inferences only from pure contravariant positions

### LINKED ISSUE #27337: Type inference for union of arrays broken
**TypeScript Version:**  Version 3.1.0-dev.20180925

**Search Terms:** array this context type compatibility assignability

**Code**

```ts
interface Array<T> {
    equalsShallow<T>(this: ReadonlyArray<T>, other: ReadonlyArray<T>): boolean;
}

type ExtractArrayType<TArray> = TArray extends Array<infer T> ? T : never;

[
    { a: ["x"], b: [] },
    { a: [], b: ["x"] },
    { a: ["x", 2], b: ["x", 2] },
    { a: ["1"], b: [1] },
    { a: [1], b: ["1"] },
    { a: [null], b: [undefined] },
    { a: [undefined], b: [null] },
    { a: [{}], b: [{}] },
].forEach(({ a, b }) => {

    // Compiles:
    const assignedA: typeof a = b;
    const assignedB: typeof b = a;

    // Compiles (prove that ReadonlyArray<>-types are compatible):
    const assignedAReadonly: ReadonlyArray<ExtractArrayType<typeof a>> = b;
    const assignedBReadonly: ReadonlyArray<ExtractArrayType<typeof b>> = a;

    // error TS2684: The 'this' context of type '(string | number)[] | null[] | undefined[] | {}[]'
    // is not assignable to method's 'this' of type 'ReadonlyArray<string | number>':
    a.equalsShallow(b);
});
```

Works in TS 3.0.

Note that the error disappears when changing `equalsShallow()` to `equalsShallow<T>(this: Array<T>, other: Array<T>): boolean`.

Further note that the error disappears when extracting a type for `a` and `b` (instead of using the literal type inference).

**Expected behavior:** No compile error

**Actual behavior:** Compile error, see snippet

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=interface%20Array%3CT%3E%20%7B%0D%0A%20%20%20%20equalsShallow%3CT%3E(this%3A%20ReadonlyArray%3CT%3E%2C%20other%3A%20ReadonlyArray%3CT%3E)%3A%20boolean%3B%0D%0A%7D%0D%0A%0D%0Atype%20ExtractArrayType%3CTArray%3E%20%3D%20TArray%20extends%20Array%3Cinfer%20T%3E%20%3F%20T%20%3A%20never%3B%0D%0A%0D%0A%5B%0D%0A%20%20%20%20%7B%20a%3A%20%5B%22x%22%5D%2C%20b%3A%20%5B%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%5D%2C%20b%3A%20%5B%22x%22%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%22x%22%2C%202%5D%2C%20b%3A%20%5B%22x%22%2C%202%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%221%22%5D%2C%20b%3A%20%5B1%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B1%5D%2C%20b%3A%20%5B%221%22%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5Bnull%5D%2C%20b%3A%20%5Bundefined%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5Bundefined%5D%2C%20b%3A%20%5Bnull%5D%20%7D%2C%0D%0A%20%20%20%20%7B%20a%3A%20%5B%7B%7D%5D%2C%20b%3A%20%5B%7B%7D%5D%20%7D%2C%0D%0A%5D.forEach((%7B%20a%2C%20b%20%7D)%20%3D%3E%20%7B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Works%3A%0D%0A%20%20%20%20const%20assignedA%3A%20typeof%20a%20%3D%20b%3B%0D%0A%20%20%20%20const%20assignedB%3A%20typeof%20b%20%3D%20a%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Prove%20that%20ReadonlyArray%3C%3E-types%20are%20compatible%3A%0D%0A%20%20%20%20const%20assignedAReadonly%3A%20ReadonlyArray%3CExtractArrayType%3Ctypeof%20a%3E%3E%20%3D%20b%3B%0D%0A%20%20%20%20const%20assignedBReadonly%3A%20ReadonlyArray%3CExtractArrayType%3Ctypeof%20b%3E%3E%20%3D%20a%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20error%20TS2684%3A%20The%20'this'%20context%20of%20type%20'(string%20%7C%20number)%5B%5D%20%7C%20null%5B%5D%20%7C%20undefined%5B%5D%20%7C%20%7B%7D%5B%5D'%0D%0A%20%20%20%20%2F%2F%20is%20not%20assignable%20to%20method's%20'this'%20of%20type%20'ReadonlyArray%3Cstring%20%7C%20number%3E'%3A%0D%0A%20%20%20%20a.equalsShallow(b)%3B%0D%0A%7D)%3B%0D%0A) (no error because it's TS 3.0)

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #27337.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -1,3 +1,6 @@
+
+
+
```
Comment (j-oliveras) [inline src/compiler/checker.ts]: I think that these newlines are strange.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -13798,7 +13801,12 @@ namespace ts {
 
             function inferFromSignature(source: Signature, target: Signature, skipParameters: boolean) {
                 if (!skipParameters) {
+                    const saveBivariant = bivariant;
+                    const kind = target.declaration ? target.declaration.kind : SyntaxKind.Unknown;
+                    // Once we descend into a bivariant signature we remain bivariant for all nested inferences
+                    bivariant = bivariant || kind === SyntaxKind.MethodDeclaration || kind === SyntaxKind.MethodSignature || kind === SyntaxKind.Constructor;
```
Comment (weswigham) [inline src/compiler/checker.ts]: Doesn't this only need to be set on the specifically contravariant comparison within `forEachMatchingParameterType`? Also, could we not use a single `variance` variable for both `bivariant` and `contravariant` context tracking (seeing as we have a variance enum already)?

Comment (ahejlsberg) [reply src/compiler/checker.ts]: The `contravariant` flag continues to track whether the position is co- or contra-variant, regardless of whether we've descended into a `bivariant` position. Doing it this way, using two separate boolean variables, makes the logic that flips the flag easy. I looked at keeping it in a single variable but didn't like the complexity that came with it.
