### PR TITLE
Updates Uint8ArrayConstructor to match MDN documentation.

### LINKED ISSUE #38446: Uint8Array constructor doesn't accept possibly undefined argument
**TypeScript Version:**  Version 4.0.0-dev.20200509

**Search Terms:** uint8array optional parameter

**Code**

(with `"strictNullChecks": true`)

```ts
function from(ab: ArrayBuffer, offset?: number, length?: number) {
  return new Uint8Array(ab, offset, length);
}
```

**Expected behavior:**

The code compiles since the second and third parameters of the ArrayBuffer overload are optional per the [spec](https://tc39.es/ecma262/#sec-typedarray-buffer-byteoffset-length).

**Actual behavior:**

```
error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.
```

**Playground Link:** 

[Playground Link](https://www.typescriptlang.org/play?ts=4.0.0-dev.20200508#code/GYVwdgxgLglg9mABMATnAtgCgIYCMBciAgiitgJ4BCIwwApigDSJy0DOdUA-IWCOrgbMANnTABzKAAseiPgIYBKRAG8AsAChEiFJxAokYOgHdEAVRhgoADhJlyOXM1bAOUEWMlTFAbk0BfIA)

**Related Issues:** 

Introduced in https://github.com/microsoft/TypeScript/pull/18367.

### PR DESCRIPTION
**Pull request by MicahZoltu**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array
```
new Uint8Array(); // new in ES2017
new Uint8Array(length);
new Uint8Array(typedArray);
new Uint8Array(object);
new Uint8Array(buffer [, byteOffset [, length]]);
```
While the previous constructors aren't significantly different from the new, they would prevent someone from doing `new Uint8Array(myBuffer, undefined, undefined)` since there was no overload that accepted undefined as a second parameter and buffer as first.
Fixes #38446

Fixes #

### CODE REVIEW

**Comment by seishun** [comment]
Perhaps the same change should be applied to all other TypedArrays.

**Comment by MicahZoltu** [comment]
> Perhaps the same change should be applied to all other TypedArrays.
Done.

File: src/lib/es5.d.ts [hunk 1]
```diff
@@ -2211,8 +2211,8 @@ interface Uint8Array {
 interface Uint8ArrayConstructor {
     readonly prototype: Uint8Array;
     new(length: number): Uint8Array;
-    new(arrayOrArrayBuffer: ArrayLike<number> | ArrayBufferLike): Uint8Array;
-    new(buffer: ArrayBufferLike, byteOffset: number, length?: number): Uint8Array;
+    new(arrayOrArrayBuffer: ArrayLike<number>): Uint8Array;
```
Comment (seishun) [inline src/lib/es5.d.ts:2214]: Rename into `array`?

Comment (MicahZoltu) [reply src/lib/es5.d.ts]: Fixed.

**Comment by orta** [comment]
OK, this looks good to me 👍

**Comment by ExE-Boss** [comment]
This also fixes this case:
```js
export class DataBlock extends Uint8Array {
	constructor(sizeOrBuffer, ...restArgs) {
		if (sizeOrBuffer instanceof ArrayBuffer) {
			// fine.
			super(sizeOrBuffer, ...restArgs);
		} else {
			Assert(typeof sizeOrBuffer === 'number');
			super(sizeOrBuffer);
		}
	}
}
```

Which previously failed for reasons similar to <https://github.com/microsoft/TypeScript/issues/14107>.

**Comment by sandersn** [comment]
Because this splits up `ArrayLike<number> | ArrayBufferLike`, this is a breaking change: It prevents passing exactly `Array<number> | ArrayBuffer`, for example.

I think this is fairly rare, but it happens once in a large internal Microsoft codebase.
