### ISSUE TITLE
TS2742: The inferred type of 'X' cannot be named without a reference

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [microsoft/TypeScript#60624]
### 🔎 Search Terms

ts2742, inferred type, bufbuild, protobuf, es, proto3

### 🕗 Version & Regression Information

- This changed between versions 5.6.3 and 5.7.x

### 🙁 Actual behavior

When using proto files with enums generated with @bufbuild/protoc-gen-es we've got this error on project build with typescript 5.7.x.

```
error TS2742: The inferred type of 'Price' cannot be named without a reference to '../../../../node_modules/@bufbuild/protobuf/dist/esm/private/enum.js'. This is likely not portable. A type annotation is necessary.

58 export const Price = /*@__PURE__*/ proto3.makeEnum(
                ~~~~~
```

### 🙂 Expected behavior

Project builds successfull with TypeScript <= 5.6.3.

**Comment by Andarist** [comment]
> Project builds successfull with TypeScript <= 5.6.3.

What's the emitted declaration for `Price` there?

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
@Andarist its enum generated from proto file
```proto
...
enum Price {
  PRICE_UNSPECIFIED = 0;
  PRICE_PAID = 1;
  PRICE_FREE = 2;
}
...
```

**Comment by Andarist** [comment]
This error is raised on:
```ts
export const Price = /*@__PURE__*/ proto3.makeEnum(
```

when attempting to generate a `.d.ts` for the containing file. I wonder what TS put before at this position:
```ts
// generated.d.ts
export declare const Price: ???
```

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
in d.ts file generated by @bufbuild/protoc-gen-es
buf.gen.yaml
```yaml
version: v1
plugins:
  - plugin: es
    out: src/protos
    opt: target=js+dts
  - plugin: connect-es
    out: src/protos
    opt:
      - target=js+dts
```
I see next lines
```ts
export declare enum Price {
  /**
   * @generated from enum value: PRICE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: PRICE_PAID = 1;
   */
  PAID = 1,

  /**
   * @generated from enum value: PRICE_FREE = 2;
   */
  FREE = 2,
}
```
when I build project with tsc (typescript 5.6.3) then in dist folder d.ts proto file looks like:
```ts
export const Price: import("../../../../node_modules/@bufbuild/protobuf/dist/esm/private/enum.js").EnumObject;
```
I don't know what else you want from me.

**Comment by RyanCavanaugh** [comment]
See https://github.com/microsoft/TypeScript/pull/58176#issuecomment-2052698294 and https://github.com/microsoft/TypeScript/issues/42873#issuecomment-2065572017
