### ISSUE TITLE
Fails to generate typescript declarations from JS when extending EventEmitter

### ISSUE THREAD

**Issue by vasco-santos** [microsoft/TypeScript#42405]
# Bug Report

### 🔎 Search Terms

- EventEmitter
- TS9006
- Declaration emit for this file requires using private name
- An explicit type annotation may unblock declaration emit

### 🕗 Version & Regression Information

- `typescript@4.0.5`
  - could not try this out with next versions as there are a few bugs already reported that will need to be fixed

This happened from 15th, more precisely after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50266 being merged and released.

### ⏯ Playground Link

I believe I cannot add JS here 😞 

You can look into `libp2p` before this PR being merged https://github.com/libp2p/js-libp2p/pull/846.

Commit hash to use: d19401aa4cafcf2237af90b677c743b0ff0f871e. Just need `npm i && npm run build`

### 💻 Code

```js
const { EventEmitter } = require('events')

class Manager extends EventEmitter {
  constructor () {
    super()
  }
}

module.exports = Manager

```

### 🙁 Actual behavior

Cannot generate typescript declaration file with errors like:

```sh
src/connection-manager/latency-monitor.js:2:1 - error TS9006: Declaration emit for this file requires using private name 'EventEmitter' from module '"events"'. An explicit type annotation may unblock declaration emit.

2  'use strict'
```

### 🙂 Expected behavior

Does not fail to build and generate the declaration files.

**Comment by RyanCavanaugh** [comment]
@weswigham seems WAI-ish, but is there anything more clever that could be done?

**Comment by weswigham** [comment]
Considering the TS equivalent, 
```ts
import { EventEmitter } from 'events'

class Manager extends EventEmitter {
  constructor () {
    super()
  }
}

export = Manager
```
works fine, and that JS should be bound _pretty similarly_ to the above TS now, I'm thinking it's _probably_ a bug somewhere in JS declaration binding.

**Comment by ExE-Boss** [comment]
What happens if:
```ts
import internal = require('events');
namespace EventEmitter {
	// Should just be `export { EventEmitter }`, but that doesn't work in TypeScript 3.4
	export { internal as EventEmitter };
}
```

in [`@types/node/events.d.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f044724b6d4471511112e8e3226a67d6a5939acb/types/node/events.d.ts#L48-L52) is changed into:
```ts
namespace EventEmitter {
	export { EventEmitter };
}
```

**Comment by weswigham** [comment]
Yeah, after looking at it, @ExE-Boss is right - this was fixed in 4.1. Check out the repro:

```ts repro
// @allowJs: true
// @checkJs: true
// @outDir: ./out
// @declaration: true
// @filename: node_modules/@types/node/index.d.ts
declare module "events" {
    import internal = require('events');
    class EventEmitter {
        member(): void;
    }
    namespace EventEmitter {
        // Should just be `export { EventEmitter }`, but that doesn't work in TypeScript 3.4
        export { internal as EventEmitter };
    }
    export = EventEmitter;
}

// @filename: file.js
/// &lt;reference types="node" />

const { EventEmitter } = require('events')

class Manager extends EventEmitter {
  constructor () {
    super()
  }
}

module.exports = Manager
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?checkJs=true&allowJs=true&outDir=.%2Fout&ts=4.1.3#code/PTAEAEEMBtoewO4CkDOAuUAXATgVwKYBQIEAxgBb6kDWqGOBxY4cumAIgJbYYB0wrTEwgATKtEjZImTnAB29PERLgAZp2j45kALb4McuGID6Oo7k0pg4TAE8ADviuGxwTnLEAPXiN6YUhGKkEtj4oGYiFmEARPgAblr+0aAA3oSgGaCcOvZw2JhZcpj42NrQoAC8oKEAjrjc+AAUAOTxiSjNAJQA3OmZwZAoKKAAoglFIzqcmMXYqX2ZmXo6AEYljZ0YcXCcIr2LAL4LoNp6KPaQpGFjiZPTs-OLiyQAyuSs0CKgAFa4KAVrUAAA3wnly+VSo3GmDuMxKoAOQIANKAVmwsORpKARHAnHJmgUEHlqIVQAAVBz4F6kbCcewFADMvAALMdFqDwQUUoVZmVQIMobcpnC5gd9pkjuywXkClUbhNhbNekdhGoNFpdPpQOpNLxvgEQGAADyhVQlLRXLCUlAVaIufDJYAAPkIhFI8n+kPlMMV8IOlWq+DqDRabSKHU6roGQ1AAFlINoAObw0HFDzDb2wh5pDLuuT-PCkTB5UAbR6ZFC4RzYDZ9I4qiJRXgcmXDKrxpMlIA)

So, good news OP! It already works in 4.1 and above!
