### ISSUE TITLE
Using typeof with a class before its declaration results in an error

### ISSUE THREAD

**Issue by voithos** [Microsoft/TypeScript#15307]
**TypeScript Version:**  2.3-rc

**Code**

```ts
const foo = typeof Bar;
class Bar {}
```

**Expected behavior:**
The code should compile properly. (And did compile fine in 2.2.1)

**Actual behavior:**
This results in a compilation error, "Class 'Bar' used before its declaration." Flipping the order fixes the problem.

In our case, the `typeof Bar` is actually used in an `extends Foo<typeof Bar>` clause of e.g. an interface declaration, but it exhibits the same behavior as this simpler example.

Alternatively, perhaps this was a bug in 2.2.1?

**Comment by mhegazy** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/15102. Fixed by https://github.com/Microsoft/TypeScript/pull/15239; Fix should be in `typescript@next` and the next TS 2.3 release (2.3.1).
