### PR TITLE
Partially revert #41044, restoring parameter destructurings in d.ts files

### LINKED ISSUE #50707: Duplicate identifier in function declaration due to stripped property renames
# Bug Report

### 🔎 Search Terms

TS2300

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.2
- Similar to #50483 and likely introduced by #41044
- Persists in 4.8.3, nightly, and #50538 (https://github.com/72636c/typescript-4.8-declaration-poc)

### ⏯ Playground Link

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZmGBeGAKA3jADgJxFgLhgEMAabPQmAIxgF8jNd8iwBXAW2oFMd6BKZAD4SMANQ0A3EA

### 💻 Code

```ts
const fn = ({ prop: a, prop: b }: { prop: number }) => a + b;
```

Or alternatively:

```ts
const fn = ({ prop: a }: { prop: number }, { prop: b }: { prop: number }) => a + b;
```

### 🙁 Actual behavior

.D.TS on TypeScript 4.8.2:

```ts
// error TS2300: Duplicate identifier 'prop'.
declare const fn: ({ prop, prop }: {
    prop: number;
}) => number;
```

https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBAZmGBeGAKA3jADgJxFgLhgEMAabPQmAIxgF8jNd8iwBXAW2oFMd6BKZAD4SMANQ0A3EA

### 🙂 Expected behavior

.D.TS on TypeScript 4.7.4:

```ts
declare const fn: ({ prop: a, prop: b }: {
    prop: number;
}) => number;
```

https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBAZmGBeGAKA3jADgJxFgLhgEMAabPQmAIxgF8jNd8iwBXAW2oFMd6BKZAD4SMANQ0A3EA

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #50707 (at least to the extent that we have the pre-4.8 behavior).

In a followup PR, I can remove these destructurings/bindings/whatevertheyrecalleds in the declaration emitter.

Note that the new errors added in #41044 remain. I guess the PR had two somewhat-related changes in it?

### CODE REVIEW

**Review by weswigham — APPROVED** [review]

**Review by andrewbranch — APPROVED** [review]

**Comment by jakebailey** [comment]
@typescript-bot cherry-pick this to release-4.8

Technically, this depends on #50538 but I'm curious to see if it'll work. Probably not.

**Comment by andrewbranch** [comment]
@typescript-bot cherry-pick this to release-4.8
