### ISSUE TITLE
Injectable is not a function

### ISSUE THREAD

**Issue by doncorsean** [Microsoft/TypeScript#14153]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When we bundle our app or load dynamically no decorators are found on objects.
i.e. 
```
Uncaught TypeError: core_1.Injectable is not a function
```

**Expected behavior**
App would run normally with no errors

**Minimal reproduction of the problem with instructions**
https://github.com/doncorsean/angular-demo
npm install
gulp buildDynamic
npm install http-server -g
http-server

**Please tell us about your environment:**
Red Hat, IDEA, npm, Play over Nginx

* **Angular version:** 2.4.7
    "@angular/common": "^2.4.7",
    "@angular/compiler": "^2.4.7",
    "@angular/core": "^2.4.7",
    "@angular/forms": "^2.4.7",
    "@angular/http": "^2.4.7",
    "@angular/platform-browser": "^2.4.7",
    "@angular/platform-browser-dynamic": "^2.4.7",
    "@angular/router": "^3.4.7",

* **Browser: all
 
Language: TypeScript

**Comment by mhegazy** [comment]
What makes you believe this is a TS bug and not project setup/configuration issue? can you point to the output generated by the compiler that is causing the issue, and what you would expect instead?

**Comment by GrzesiekGdn** [comment]
I have noticed the same error when I upgraded my package.json for system.js from 0.19 to 0.20.

**Comment by doncorsean** [comment]
@mhegazy There is no error during compilation, only at runtime. Injectable is provided by the Angular core.umd.js. A member of our team found that modifying the js that's created from "core_1.Injectable" to "core_1.default.Injectable" silences the error. 

Thx for the tip @GrzesiekGdn will try that now and see if it corrects the issue.

**Comment by doncorsean** [comment]
@GrzesiekGdn tried rolling systemjs back and same result.

**Comment by doncorsean** [comment]
@GrzesiekGdn issue was a combination of systemjs version and systemjs builder version

**Comment by wrldtrvllr** [comment]
Could you please provide more info on how you solved the issue? I'm having the exact same problem right now.

**Comment by jensbodal** [comment]
I think this is a systemjs issue not a typescript issue.  I'm still looking into a solution, but thought it would be worth noting I do not see this issue with `0.19.40` but immediately see it when I upgrade to the latest `0.20.10`.  Granted my error is slightly different, I'm assuming they are from the same cause.

> core_1.Component is not a function

```
  Evaluating http://192.168.56.20/src/app/ng-test.component.ts
  Evaluating http://192.168.56.20/src/app/app.module.ts
  Evaluating http://192.168.56.20/src/main.ts
  Loading src/main.ts
    at eval (ng-test.component.ts:3)
at Object.execute (ng-test.component.ts:10)
    at declarativeExecute (register-loader.js:673)
    at doEvaluate (register-loader.js:602)
    at doEvaluate (register-loader.js:589)
    at doEvaluate (register-loader.js:589)
    at ensureEvaluate (register-loader.js:535)
    at register-loader.js:132
    at ZoneDelegate.invoke (zone.js:365)
    at Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.invokeTask (zone.js:398)
    at Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
```

I then started incrementally upgrading from `0.19.40` and from what I can tell this specific issue popped up in `0.20.0-rc.2`;  `0.20.0-rc.1` did not have any issues.

**Comment by jensbodal** [comment]
Fixed for me by specifying the module to commonjs in systemjs settings using the latest systemjs (0.20.10).  

```
    typescriptOptions: {
      // Copy of compiler options in standard tsconfig.json
      "target": "es5",
      "module": "commonjs",
      "moduleResolution": "node",
      "sourceMap": true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "noImplicitAny": true,
      "suppressImplicitAnyIndexErrors": true
    },
```

**Comment by doncorsean** [comment]
Definitley system js/systemjs builder issue
