### PR TITLE
Set symbol on union that is returned from `getSpreadType`

### LINKED ISSUE #16694: 2.4 errors for missing index signature with object literal spread
**TypeScript Version:**  2.4.0

**Code**

```ts
import {CSSProperties} from 'glamorous'

export const a = (): CSSProperties => ({})

export const b = ({withA = false}): CSSProperties => ({
  ...withA ? a() : undefined,
})
```

**Expected behavior:**
No errors

**Actual behavior:**
TypeScript displays this error:
```
error TS2322: Type '{} | { [propertyName: string]: string | number | CSSProperties | undefined; alignContent?: "cente...' is
not assignable to type 'CSSProperties'.
  Type '{}' is not assignable to type 'CSSProperties'.
    Index signature is missing in type '{}'
```

The code works fine in 2.3.4 which is what I would expect. I return an object literal, there is nothing that should prevent it to be assigned to a more open type.
Without the tenery at the spread position the code gives no errors.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #16694

Previously, it was only set on a top-level type resulting from `getSpreadType`, and only if that top-level type was an object type. Now `checkObjectLiteral` uses `forEachType` to set the symbol on every object type in the union as well, if `getSpreadType` returns a union.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -13917,13 +13917,15 @@ namespace ts {
...
-                    (spread as ObjectType).objectFlags |= ObjectFlags.ObjectLiteral;
-                    spread.symbol = node.symbol;
-                }
+                // only set the symbol and flags if this is a (fresh) object type
+                forEachType(spread, t => {
+                    if (t.flags & TypeFlags.Object) {
+                        t.flags |= propagatedFlags;
+                        t.flags |= TypeFlags.FreshLiteral;
+                        (t as ObjectType).objectFlags |= ObjectFlags.ObjectLiteral;
+                        t.symbol = node.symbol;
```
Comment (weswigham) [inline src/compiler/checker.ts]: Won't this trample over the existing symbol on any object types spread?

Comment (mhegazy) [reply src/compiler/checker.ts]: Can we instead pass this symbol to getSpreadType and avoid the mutation after creating the type..

Comment (sandersn) [reply src/compiler/checker.ts]: @weswigham In its current state getSpreadType + the emptyObjectType check above will never trample an existing type. However, @mhegazy's idea is much less error-prone for future changes. Right now, getSpreadType is only called from places that have a symbol on hand anyway, since it's not a real type operator like it was planned to be.

Comment (sandersn) [reply src/compiler/checker.ts]: Done. It caused some churn in the ad-hoc JSX code, but it's probably worth it for the readability in checkObjectLiteral.
