### ISSUE TITLE
Feature request: lift the circular constraint for conditional types

### ISSUE THREAD

**Issue by isiahmeadows** [microsoft/TypeScript#26980]
## Search Terms

circular type conditional type

## Suggestion

Currently, `Last1` is valid, but seemingly-equivalent `Last2` is not:

```ts
type Head<T extends any[]> = T extends [infer X, ...any[]] ? X : never;

type Tail<T extends any[]> =
    ((...x: T) => void) extends ((x: any, ...xs: infer XS) => void) ? XS : never;

type Last1<T extends any[]> = {
  0: never,
  1: Head<T>,
  2: Last1<Tail<T>>,
}[T extends [] ? 0 : T extends [any] ? 1 : 2];

type Last2<T extends any[]> =
    T extends [] ? never :
    T extends [infer R] ? R :
    Last2<Tail<T>>;
```

My suggestion is to make `Last2` valid, since the recursion isn't necessarily unbounded.

## Use Cases

It'd make recursive conditional types a lot easier and more intuitive to write. It'd also eliminate the need to guard against impossible cases when using the workaround like when using `Last1` above. If you wanted to mandate termination, all I'd want is direct recursion - this makes it much easier to check for infinite recursion. (Other types are generally assumed to terminate, so you're only assessing control flow.)

## Examples

See above in the suggestion summary. Here's a concrete example of how [this file](https://github.com/kgtkr/typepark/blob/master/src/pipe.ts) (with [dependency](https://github.com/kgtkr/typepark/blob/master/src/list.ts)) would be simplified:

```ts
type Last<L extends any[], D = never> =
    L extends [] ? D :
    L extends [infer H] ? H :
    ((...l: L) => any) extends ((h: any, ...t: infer T) => any) ? Last<T> :
    D;

type Append<T extends any[], H> =
    ((h: H, ...t: T) => any) extends ((...l: infer L) => any) ? L : never;

type Reverse<L extends any[], R extends any[] = []> =
    ((...l: L) => any) extends ((h: infer H, ...t: infer T) => any) ?
        Reverse<T, Append<R, H>> :
        R;

type Compose<L extends any[], V, R extends any[] = []> =
    ((...l: L) => any) extends ((a: infer H, ...t: infer T) => any) ?
        Compose<T, H, Append<R, (x: V) => H>> :
        R;

export type PipeFunc<T extends any[], V> =
    (...f: Reverse<Compose<T, V>>) => ((x: V) => Last<T, V>);
```

Currently, you could achieve similar via [this](https://www.typescriptlang.org/play/index.html#src=type%20Last%3CL%20extends%20any%5B%5D%2C%20D%20%3D%20never%3E%20%3D%20%7B%0D%0A%20%20%20%200%3A%20D%2C%0D%0A%20%20%20%201%3A%20L%20extends%20%5Binfer%20H%5D%20%3F%20H%20%3A%20never%2C%0D%0A%20%20%20%202%3A%20((...l%3A%20L)%20%3D%3E%20any)%20extends%20((h%3A%20any%2C%20...t%3A%20infer%20T)%20%3D%3E%20any)%20%3F%20Last%3CT%3E%20%3A%20D%2C%0D%0A%7D%5BL%20extends%20%5B%5D%20%3F%200%20%3A%20L%20extends%20%5Bany%5D%20%3F%201%20%3A%202%5D%3B%0D%0A%0D%0Atype%20Append%3CT%20extends%20any%5B%5D%2C%20H%3E%20%3D%0D%0A%20%20%20%20((h%3A%20H%2C%20...t%3A%20T)%20%3D%3E%20any)%20extends%20((...l%3A%20infer%20L)%20%3D%3E%20any)%20%3F%20L%20%3A%20never%3B%0D%0A%0D%0Atype%20Reverse%3CL%20extends%20any%5B%5D%2C%20R%20extends%20any%5B%5D%20%3D%20%5B%5D%3E%20%3D%20%7B%0D%0A%20%20%20%200%3A%20R%2C%0D%0A%20%20%20%201%3A%20((...l%3A%20L)%20%3D%3E%20any)%20extends%20((h%3A%20infer%20H%2C%20...t%3A%20infer%20T)%20%3D%3E%20any)%20%3F%0D%0A%20%20%20%20%20%20%20%20Reverse%3CT%2C%20Append%3CR%2C%20H%3E%3E%20%3A%0D%0A%20%20%20%20%20%20%20%20never%2C%0D%0A%7D%5BL%20extends%20%5Bany%2C%20...any%5B%5D%5D%20%3F%201%20%3A%200%5D%3B%0D%0A%0D%0Atype%20Compose%3CL%20extends%20any%5B%5D%2C%20V%2C%20R%20extends%20any%5B%5D%20%3D%20%5B%5D%3E%20%3D%20%7B%0D%0A%20%20%20%200%3A%20R%2C%0D%0A%20%20%20%201%3A%20((...l%3A%20L)%20%3D%3E%20any)%20extends%20((a%3A%20infer%20H%2C%20...t%3A%20infer%20T)%20%3D%3E%20any)%20%3F%0D%0A%20%20%20%20%20%20%20%20Compose%3CT%2C%20H%2C%20Append%3CR%2C%20(x%3A%20V)%20%3D%3E%20H%3E%3E%0D%0A%20%20%20%20%20%20%20%20%3A%20never%2C%0D%0A%7D%5BL%20extends%20%5Bany%2C%20...any%5B%5D%5D%20%3F%201%20%3A%200%5D%3B%0D%0A%0D%0Aexport%20type%20PipeFunc%3CT%20extends%20any%5B%5D%2C%20V%3E%20%3D%0D%0A%20%20%20%20(...f%3A%20Reverse%3CCompose%3CT%2C%20V%3E%3E)%20%3D%3E%20((x%3A%20V)%20%3D%3E%20Last%3CT%2C%20V%3E)%3B), but as you can see, it's highly repetitive and boilerplatey:

```ts
type Last<L extends any[], D = never> = {
    0: D,
    1: L extends [infer H] ? H : never,
    2: ((...l: L) => any) extends ((h: any, ...t: infer T) => any) ? Last<T> : D,
}[L extends [] ? 0 : L extends [any] ? 1 : 2];

type Append<T extends any[], H> =
    ((h: H, ...t: T) => any) extends ((...l: infer L) => any) ? L : never;

type Reverse<L extends any[], R extends any[] = []> = {
    0: R,
    1: ((...l: L) => any) extends ((h: infer H, ...t: infer T) => any) ?
        Reverse<T, Append<R, H>> :
        never,
}[L extends [any, ...any[]] ? 1 : 0];

type Compose<L extends any[], V, R extends any[] = []> = {
    0: R,
    1: ((...l: L) => any) extends ((a: infer H, ...t: infer T) => any) ?
        Compose<T, H, Append<R, (x: V) => H>>
        : never,
}[L extends [any, ...any[]] ? 1 : 0];

export type PipeFunc<T extends any[], V> =
    (...f: Reverse<Compose<T, V>>) => ((x: V) => Last<T, V>);
```

(The original code snippet is linked to from [here](https://github.com/Microsoft/TypeScript/issues/5453#issuecomment-419636447) as a possible solution to the issue of `_.compose`, `_.flow`, and friends.)

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by isiahmeadows** [comment]
BTW, [here's the Wikipedia article on total functional programming](https://en.wikipedia.org/wiki/Total_functional_programming), where TS's type system models to a very large extent in my experience (probably unintentionally). And yes, this could enable a type-encoded quicksort across integers and potentially strings if they were made comparable, without even requiring the type system to remain Turing-complete.

-----

After including this, you could then permanently break the Turing-complete aspect by making a similar non-recursive check with indexed types. Note that AFAICT, the Turing-complete nature is dependent on indexed types not being checked for recursive cases. It *may* require support for corecursive functions, depending on how much code breaks.

**Comment by isiahmeadows** [comment]
Oh, and another reason to address Turing completeness and potentially kill it is because the [original "solution" to variadic composition](https://github.com/Microsoft/TypeScript/issues/5453#issuecomment-419636447) happens to hang when [plugged into the playground](https://www.typescriptlang.org/play/index.html#src=%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20foo0()%3A%20void%20%7B%0D%0A%20%0D%0A%7D%0D%0A%0D%0Afunction%20bar0()%3A%20void%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Afunction%20foo1(a%3A%20string)%3A%20%5Bstring%5D%20%7B%0D%0A%20%20return%20%5Ba%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20bar1(a%3A%20string)%3A%20%5Bstring%5D%20%7B%0D%0A%20%20return%20%5Ba%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20foo2(a1%3A%20string%2C%20a2%3A%20boolean)%3A%20%5Bstring%2C%20boolean%5D%20%7B%0D%0A%20%20return%20%5Ba1%2C%20a2%5D%3B%0D%0A%7D%0D%0A%0D%0Afunction%20foo21(a1%3A%20string%2C%20a2%3A%20boolean)%3A%20%5Bstring%5D%20%7B%0D%0A%20%20return%20%5Ba1%5D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20bar2(a1%3A%20string%2C%20a2%3A%20boolean)%3A%20%5Bstring%2C%20boolean%5D%20%7B%0D%0A%20%20return%20%5Ba1%2C%20a2%5D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Afunction%20compose%3CX%20extends%20any%5B%5D%2C%20Y%20extends%20any%5B%5D%2C%20Z%20extends%20any%5B%5D%3E(%0D%0A%20%20f%3A%20(...args%3A%20X)%20%3D%3E%20Y%2C%0D%0A%20%20g%3A%20(...args%3A%20Y)%20%3D%3E%20Z%0D%0A)%3A%20(...args%3A%20X)%20%3D%3E%20Z%20%7B%0D%0A%20%20return%20function%20(...args)%20%7B%0D%0A%20%20%20%20const%20y%20%3D%20f(...args)%3B%0D%0A%20%20%20%20return%20g(...y)%3B%0D%0A%20%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Aconst%20baz0%20%3D%20compose(%0D%0A%20%20foo0%2C%0D%0A%20%20bar0%0D%0A)%3B%0D%0A%0D%0Aconst%20baz21%20%3D%20compose(%0D%0A%20%20foo21%2C%0D%0A%20%20bar1%0D%0A)%3B%0D%0Aconst%20baz2%20%3D%20compose(%0D%0A%20%20foo2%2C%0D%0A%20%20bar2%0D%0A)%3B%0D%0A%0D%0A%0D%0Aalert(baz2('a'%2C%20false))%0D%0Aalert(baz21('a'%2C%20true))%0D%0Aalert(baz0())), due to a bug not very clear when just looking. It maxes out my computer's CPU without taking much memory at all, which is a pretty obvious problem, but it can happen when a type system is Turing-complete, but not sound enough to force you to be explicit about your intent (you see similar with C-like procedural languages and infinite loops with non-trivial logic, hence various [control-flow-sensitive lints](https://eslint.org/docs/rules/no-unmodified-loop-condition) for it).

**Comment by jcalz** [comment]
(Moving the conversation from #5453)

Regarding the `Last1<>` implementation, the official word is something like "don't do it". @ahejlsberg [said](https://github.com/Microsoft/TypeScript/pull/24897#issuecomment-401418254):
> It's clever, but it definitely pushes things well beyond their intended use. While it may work for small examples, it will scale horribly. Resolving those deeply recursive types consumes a lot of time and resources and might in the future run afoul of the recursion governors we have in the checker.
>
> Don't do it!

I would be enormously in favor of something that lets me express more recursive type functions without running afoul of the current pitfalls (warnings, hanging compiler, crashing compiler).  Not sure how to get there from here, though.   I suspect if the circularity warning were simply removed, the `Last2<>` implementation would bog down the compiler in the same way that `Last1<>` does.  Assuming that the type checker sometimes treats `T extends U ? X : Y` like `X | Y` for testing assignability, any recursion that depends on conditional types to express termination could be a problem.   

I'm not holding my breath for any solution involving a significant overhaul of the type checker.  Can we think of some addition which wouldn't break existing code but would allow some (bounded) type function iteration/recursion?

**Comment by jcalz** [comment]
Copying from the Design Notes for ease of linking.

@DanielRosenwasser [said](https://github.com/Microsoft/TypeScript/issues/27102#issue-360450113):
> # Recursive Types
> *    The intuition is not possible to form object graphs with circularities unless you defer somehow (either via laziness or state).
> *    Really there's no way to know if any arbitrary type will terminate.
> *    We can have limited types of recursion in the compiler, but the problem isn't whether or not the type terminates, it's how computationally intensive and memory heavy the resolution is.
> *    We have a meta-question: do we want people writing code like this?
>      * The motivating scenarios that people have are legitimate, but achieving them with these types is not necessarily going to work well for library consumers.
> *    Conclusion: we're not quite ready for this sort of thing.

**Comment by isiahmeadows** [comment]
May I add another compelling use case: you could lift the similar constraints on unions, intersections, and generic type parameters to address the possible results of `JSON.parse(string)` without a reviver:

```ts
type JSONResult = null | string | number | Record<string, JSONResult> | JSONResult[];
```

In this case, `JSONResult` can only really be these types, and anything else is entirely unreasonable. You can detect the safety and legality by ensuring that any cycles are abstracted through an object property of some kind. In the case of `Record<string, JSONResult>`, it's a `[key: string]` property, and in the case of `JSONResult[]`, it's a `[key: number]` property.

**Comment by fightingcat** [comment]
```typescript
type Last<T extends any[]> = T[Tail<T>['length']];
```

**Comment by jcalz** [comment]
cross-linking #30188

And calling @pirix-gh... I think since you are using recursive conditional types inside [ts-toolbelt](https://github.com/pirix-gh/ts-toolbelt) and committed them into the [typings for ramda](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/tools.d.ts#L68-L75) it would be useful for someone to either reiterate that this is a Bad Idea, or give some update if there is one.

And if there ever is an update here past ["don't do it"](https://github.com/Microsoft/TypeScript/pull/24897#issuecomment-401418254) and ["we're not ready for this"](https://github.com/Microsoft/TypeScript/issues/27102#issue-360450113), I'd expect to see some recursive conditional types included in the baseline tests for the language itself, so that future releases won't break them.

**Comment by pirix-gh** [comment]
> Quotes from https://github.com/microsoft/TypeScript/issues/5453#issuecomment-506847921

Can we discuss whether we can have official approval for the types provided in the **ts-toolbelt** or not?
Here's how the story started:

**Performance**
I created a [heavy test](https://gist.github.com/pirix-gh/02097996d2a1e4e7aa2d54b330451ea0) that shows the Minus type in action. It performs the Minus 216000 times in less than 4 seconds. This shows that TS can handle recursive types very well. But this is quite recent.

**Since when?**
This is thanks to Anders :tada: (#30769). He allowed me to switch from conditional types to indexed conditions (like a switch). And as a matter of fact, it improved performance by x6 (with everything being indexed).

**Is it safe?**
The lib also makes recursion safe with Iteration that will prevent any overflow from TypeScript. In other words, if I goes over 40 then it overflows and `Pos<I>` equals `number`. Thus stopping the recursion safely. Here's an example:
```ts
import {O, I, T} from 'ts-toolbelt'

// It works with the same principles `Minus` uses
type Assign<O extends object, Os extends object[], I extends I.Iteration = I.IterationOf<'0'>> = {
    0: Assign<O.Merge<Os[I.Pos<I>], O>, Os, I.Next<I>>
    1: O
}[
    I.Pos<I> extends T.Length<Os>
    ? 1
    : 0
]

type test0 = Assign<{i: number}, [
    {a: '1', b: '0'},
    {a: '2'},
    {a: '3', c: '4'},
]>
```

**Thoughts**
- Even though it is possible to write optimized recursive types, it requires being rigorous and it should not be approached by inexperienced ones that could write unsafe (heavy) types. This is why I created this repository to ensure the quality of the types.
- I did a test on 12 960 000 `Minus` operations to calculate the average cost of `Minus`. It took 125 seconds to complete the compilation. So a single `Minus` operation (~30 iterations) takes 9.65e-6 seconds to be performed.
- The library itself has a very low overhead (+2 seconds)
- This could be great for the future of TS, as we could write more features with the type system itself. Thus relieving the TS team from the constant demand for new features (at least partially).
- This is not about lifting circular constraints as they clearly signal problems. It's about approving or not types like the one above (which are able not to overflow).

**What now?**
- Can we debate about the pros/cons to make this **ts-toolbelt** approved or not?
- Can we talk about integrating such support into the TS project (like @jcalz asked)?
- Could TS be optimized to provide even better support? Here's some thoughts:
  - The compiler could compile the types themselves, thus saving that compilation time on shared packages. Basically, we don't want to recompute a type (like `Minus`) every time, we could just compute its output once, and this is what would end up in a generated `d.ts`. This could (maybe) be determined whether a type is waiting for arguments (can't be computed) or is argument-less (can be computed).
  - TypeScript could maybe avoid computing types that require arguments until they are provided with them. This could also help with performance as TS calculates all the possible outputs of a type that has generics. I especially think of mapped types that already have such behavior.
- Should I open a proposal?

@ahejlsberg @RyanCavanaugh @DanielRosenwasser

**Comment by pirix-gh** [comment]
Updated the example `T.Length<Os> extends I.Pos<I>` was reverted

**Comment by AnyhowStep** [comment]
@jcalz Circular conditional type police? I would like to turn myself in,

```ts
interface CompileError<_ErrorMessageT> {
    __compileError : never
}
type PopFront<ArrT extends readonly any[]> = (
    ((...arr : ArrT) => void) extends ((head : any, ...tail : infer TailT) => void) ?
    TailT :
    never
);
type PushFront<TailT extends readonly any[], HeadT> = (
    ((head : HeadT, ...tail : TailT) => void) extends ((...arr : infer ArrT) => void) ?
    ArrT :
    never
);
//////////////////////////////////
type AssertCanComposeImpl<
    F extends (...args : any[]) => any,
    ArrT extends readonly ((arg : any) => any)[],
    IndexT extends any[]
> = (
    {
        0 : unknown,
        1 : (
            [ReturnType<F>] extends Parameters<ArrT[0]> ?
            AssertCanComposeImpl<
                ArrT[0],
                PopFront<ArrT>,
                PushFront<IndexT, any>
            > :
            CompileError<[
                "Output",
                [ReturnType<F>],
                "of function",
                IndexT["length"],
                "cannot be input to function taking",
                Parameters<ArrT[0]>
            ]>
        )
    }[
        ArrT["length"] extends 0 ?
        0 :
        1
    ]
);
type AssertCanCompose<
    F extends (...args : any[]) => any,
    ArrT extends readonly ((arg : any) => any)[]
> = (
    number extends ArrT["length"] ?
    unknown :
    AssertCanComposeImpl<
        F,
        ArrT,
        []
    >
);
//////////////////////////////////
type ComposeImpl<
    F extends (...args : any[]) => any,
    ArrT extends readonly ((arg : any) => any)[],
    ParametersT extends any[],
    IndexT extends any[]
> = (
    {
        0 : (...args : ParametersT) => ReturnType<F>,
        1 : (
            [ReturnType<F>] extends Parameters<ArrT[0]> ?
            ComposeImpl<
                ArrT[0],
                PopFront<ArrT>,
                ParametersT,
                PushFront<IndexT, any>
            > :
            never
        )
    }[
        ArrT["length"] extends 0 ?
        0 :
        1
    ]
);
type Compose<
    F extends (...args : any[]) => any,
    ArrT extends readonly ((arg : any) => any)[]
> = (
    number extends ArrT["length"] ?
    (...args : Parameters<F>) => unknown :
    ComposeImpl<
        F,
        ArrT,
        Parameters<F>,
        []
    >
);
declare function compose<
    P extends any[],
    R extends any,
    ArrT extends readonly ((arg : any) => any)[]
> (
    f : (
        (...args : P) => (
            & R
            & AssertCanCompose<
                () => R,
                ArrT
            >
        )
    ),
    ...arr : ArrT
) : (
    Compose<(...args : P) => R, ArrT>
);

//Error: Expected at least 1 arguments, but got 0.
compose();

//(a: number, b: string) => unknown
const doNotKnowReturnType = compose(
    (a : number, b : string) => a+b,
    ...[]
);

//(a: number, b: string) => string
const one = compose(
    (a : number, b : string) => a+b
);

//(a: number, b: string) => Date | null
const many = compose(
    (a : number, b : string) => a+b,
    (s : string) => s.length > 2,
    (b : boolean) => Math.random() > 0.5 && b ? new Date() : null
);

//const cannotCompose: never
//
const cannotCompose = compose(
    /*
        CompileError<[
            "Output",
            [Date],
            "of function", 1,
            "cannot be input to function taking",
            [boolean]
        ]>
    */
    (a : number, b : string) => a+b,
    (s : string) => new Date(), //Uh oh, next function expects boolean
    (b : boolean) => Math.random() > 0.5 && b ? new Date() : null
);

```

[Playground](http://www.typescriptlang.org/play/#code/JYOwLgpgTgZghgYwgAgMIHsC2AHYAbCAUSinSgB4B9Y0qAWQgGdG4BzCAFQD5kBvAWABQyEckqUEWXARplkALmQgIAN2hCAvkLABPbCgAK6bADFS4cgEESHZBAAekEABNGyKBDjP0IPDuRwIDoA2gC6PAC8yAAUQqIx0QB0yXAkCsjWUBwAlMgRPCrowM65Dk6uCQAWns7pgToANMjJiWBw+OmgMNDIHO14OXkFRSXIAPxxon34tvKTIspqUELZANzaeoYAroyVZj5g5NMDdo4QLm4eXj5+AUFhTQASNdx5MfNVNenPXhxNLW0OopjoN8shCsVSmcLgkWqkoJ0QN0EZlQcNIeMPqiFB9FupBGshAB6EmksnkimUikbfQZZjQMCoQIYHDoRgQACSODw5A+JlO5TcSRSUFYbkU9TCuTB9QaWJsAvOFSu3l8-mi0VSrDqQWlPHq2QeHw5LgctjKSrcktCQki72EogEDviIgADOktiAANYgdAAdxAcudLoAjOlYsGXaJggAlCBgLZQEAcTbkExcUKKmEGVJwTDx6CMKw2YKu8KYyNRunsqCM5lSNmc7m8ytV0So0uhINtttGUzmQ6orjdntRgw7PYD8gm5xmpr1LgfNs8Oatl0s6REEhkcjBJej5AAIgA8lswNgz4eRwfo3GE0mU-o0xnrzej+gYMgYJ6EGBgD4r33UcZzNYJDwIEBWDASpDy7ICe0PBBAl9MBkAAIxQUAL1QsB0C-H8-x8ZA2i9UBWEAtde1zfNICgIsOzLRdKNEcJ4OyD4ND3NcO3A84oJgzMLRhd0JjXd1VzbEMPhtAl1kEXRaUselayZEAN0bFt4n5ISKmFRItXFO4QlCPUjNfbEdMuGobnVTVRR1HRTINMJbTeCN4hALZMAwhFLIyEteMg6DYIreJPR9f0QBxYMlJrOs1IbdkuWwHl4JMV94lRDLoxk+ImMJQQqSK4rKRpFB1KS5s+SzXS4VFQzrScoJzIVPyVRshItQcprHKNYMcygPMCzo81oQqa1XxA+xRsFIyXMEO13MdeDxJiOqxXSAahtoxg0WQO9E2TVN02ykQw0UJbR1jeNDsfCBn0Esa3C2mjC2LLJOx4USbwqpsUs0t8RAYuDmLHYx9gsIdTp7F7ht26HewnCHDimv4jKYm8V3gjzVHxNt2ODTj4J4iD+JCvyRJW6LJOklY5IU8rEvu6q-L0gyHKlIYzPlLIaqs641U6+yJV1LnnJkxbcS8ny+f8j7ArJzNvtENn6s26i4efUzwt9ANqdEX7ktStd0uJmxodhnbn2h+a8rpoRZwQPBUhQb8QF-f8oskVl2QBkQDFliaPhjQPmp5mbLXcazBY1LqRccsXdXmnhLq-cN4NVjbFAMUzU7bAAyfbsdEQvYoZVTfr9t9olMmMEarVFi5EDGqwJ+JslfOqEUURuCXT4NK8zwyc65uu5e4e3BGJIlZCgRRCHsfRfwgWo4FQgg4EYVCwy1LzzjARgmjQs9kFYdBUNdRIhG97BGxruTp81RRPO86Aj8ULeoDI7XvV1kBr58FvZA3gABy58ADSusDoPk2G8G+d8PianSC-HyR90if2-mLAA1GhTuyR5oFUfnAZ+0s37oQ-mAL+kFTIYMggAkAQCfAoCiPA9kqckEkNflANBFCqGsCcjgyeRDOGoPIcgWh-CuYABE14oAAD5KC2HgPA9CgGYHqHApm7C4DINIdw9C6DKGYJlDg180RDISJoYkUm0FkA8AAExmLQukNC6B0AbxAKZOga9KiJEGi4LANc7HIEvgAVmQPnQuzixhKAgH6ZAMjIBBJIcooRhUiSSAYahJCIAUK-WfrjZY6TVHZOQufX6mifYQFTkSAAVPBDc+Aty0F3E3I8p5zyXnriIYIiSIAgxvIeD8+F3aERAFeZAIZulHhyShdCmEQDYWInhN2HsiIkTIhRG8wRXHuM8CAXKVZWLBlqUSRBOiRFkOcbw4x+pTGIIsUY6hXNlDxL6TXJoJIACqlRkDoEqE0ZQjgRlrKig4JeB90JuI8Yg65UK9mBC8T4vxgRvCYCCTwMJESonjFiW82RyTFGpNkkIUlU9yVAA)

**Comment by pirix-gh** [comment]
@AnyhowStep I only use recursion in cases where the length of a tuple changes. For all the rest (in most cases) you should be able to use mapped types (it applies in this case). You can check out my implementation of `compose`:

https://github.com/pirix-gh/ts-toolbelt/blob/master/src/Function/Compose.ts

**Comment by AnyhowStep** [comment]
Someone on the TS gitter was asking for a compose function signature with arbitrary amounts of functions as inputs. So, I thought it was an interesting request.

I gave your impl a brief look.

Looks like mine composes forward and yours composes backwards?

Also, mine checks if the output of function N can be an input to function N+1 and gives an appropriate compile error (if a tuple is inferred)

**Comment by pirix-gh** [comment]
It composes forward, as it's a mapped type, but it will block at 40 yhea. And it does check for input-output, what do you mean?

**Comment by AnyhowStep** [comment]
I was referring to this part,

```

        CompileError<[
            "Output",
            [Date],
            "of function", 1,
            "cannot be input to function taking",
            [boolean]
        ]>
```

If they call the `compose()` function and the output of N doesn't feed into function N+1, it gives a compile-time error

**Comment by pirix-gh** [comment]
Pinging everyone following this. A PR allowing recurive types has been accepted by the TypeScript team. We can now write such recursive types, at the cost of using a library (and the way of writing them). So be careful when writing them.

https://github.com/microsoft/TypeScript/pull/33810

I'm not sure this can close this issue, but is nevertheless a great step forward.

**Comment by AnyhowStep** [comment]
@pirix-gh Can you toss in type-level generator trampolines to those tests, too? =P

**Comment by pirix-gh** [comment]
I'd rather love to see type providers one day to have top performance types.

**Comment by jcalz** [comment]
Is there any way to get a version of this that works in [the Playground](https://www.typescriptlang.org/play/)?  Or some guidance on how to do this without using an external library?  Like maybe we can make a self-contained "ts-toolbelt lite" that can be used inline as opposed to in a module hierarchy?  I'm hoping to minimize Stack Overflow and GitHub issue headaches.

**Comment by AnyhowStep** [comment]
@sandersn if I made a PR to add trampolines to the tests, would it be accepted?

The following file gives an example of what the test would look like,
https://github.com/AnyhowStep/tsql/blob/master/src/tuple-util/reverse.ts

It doesn't rely on external dependencies to work and can easily go beyond 1000+ iterations/recursive calls

**Comment by pirix-gh** [comment]
@jcalz, I'm working on a script that will make it work on the playground (flattening), will ping when it's done

**Comment by jack-williams** [comment]
There is the possibility that the current implementation relies on variance markers for conditional types, which are known to have bugs. When I've looked at fixing these issues I've run into problems where conditional types that were checked trivially now fail because they are checked structurally.

For instance, when investigating #31277 I got an infinite type error in something originating in `ts-toolbelt`. This was pre-3.7, and I haven't looked at how that affects things yet.

When I get a chance I'll see if the changes in #31277 caues any regressions in #33810.

**Comment by sandersn** [comment]
Erm, I was the one who merged that test. My intent in adding it to the test suite was not, **_not_** to support recursive types. It was to let us (and anybody who wants to follow [our user tests](https://github.com/microsoft/TypeScript/issues/33716)) know when we break the latest workarounds. That is, we'll consider that test passing even if there are compilation errors or OOMs.

We have a recursive type limit for a reason &mdash; people don't expect a compiler to do arbitrary computation, so compile-time programs that you write need to run fast. This is especially true for commonly-used libraries.

@AnyhowStep That particular test is for ts-toolbelt. Is ts-toolbelt trampolined? If not, I'm fine with adding a separate test in index.ts. @pirix-gh is that OK with you?

**Comment by AnyhowStep** [comment]
I don't think ts-toolbelt is trampolined. I can say I have not noticed a negative impact on performance due to trampolines, though.

Trampolines can be an important workaround, even when recursive types are not deeply nested. In the above linked issue, I only had a recursive type doing **two** iterations and TS still gave up (unless assigning the result to a temporary variable).

With the trampoline workaround, it works fine with 60+ iterations, whether I assign to a temporary variable or not.

I can make a separate PR that tests trampolines. I didn't even realize it was a thing that could be OK'd

**Comment by pirix-gh** [comment]
Nope, it's not trampolined, one of my goals was keep ts' memory as sane as I can. Recursive types do get limited by the compiler when they get too complex **internally** (instantiation depth). What I do for recursive types, and that is what @sandersn means by workaround, is that I use:

```ts
type RecursiveType<A, B...> =
	_RecursiveType<A, B...> extends infer X
	? X
	: never
```

This is in a sense a mini-trampoline, to allow combining recursive types together without hitting that instantiation depth error. I feel like this is already asking a lot from ts. But **if you remove the `extends infer X`** part you are left with a fully supported type, as it uses no trick IMHO... But if I were to remove this on the ts-toolbelt, types like `Curry` would certainly not be possible.

(Just to give an idea, ts-toolbelt standalone weighs `~40MB`, and with all its tests, it climbs up to `~90MB`).

**Comment by pirix-gh** [comment]
I think trampolines belongs to a separate PR. I'd be interested to see memory performance on them @AnyhowStep.

**Comment by AnyhowStep** [comment]
I've seen that `infer X` trick fail in many (of my) use cases. Which is why I opt for a full trampoline nowadays.

```ts
import {Reverse} from "./reverse";

export type X = Reverse<[
    //50
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

    //100
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

    //150
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

    //200
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

    //250
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,

    //287
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    1, 2, 3, 4, 5, 6, 7
]>;
```

```
> tsc

Files:                        34
Lines:                      7450
Nodes:                     21256
Identifiers:                6781
Symbols:                  214344
Types:                     92308
Memory used:              85343K
Assignability cache size:   2014
Identity cache size:           0
Subtype cache size:            0
I/O Read time:             0.00s
Parse time:                0.12s
Program time:              0.13s
Bind time:                 0.05s
Check time:                0.81s
transformTime time:        0.02s
Source Map time:           0.01s
commentTime time:          0.01s
I/O Write time:            0.00s
printTime time:            0.04s
Emit time:                 0.04s
Total time:                1.02s
```

**Comment by AnyhowStep** [comment]
https://github.com/AnyhowStep/ts-trampoline-test

**Comment by jcalz** [comment]
I am [reminded](https://gitter.im/Microsoft/TypeScript?at=5dcc1d4c92a84f79fe5d8176):

It's too late to decide that we're not ready for recursive conditional types; they're here already. Now let's make them safe and easy to use! Maybe some kind of `Defer<T, D, N>` where `T` is some arbitrarily self-referencing type, `D` is some default type in case `T` can't be resolved by recursing at most `N` levels deep, and you can leave off `N` and get the maximum value allowed by the compiler, which is something big.

Otherwise I either have to keep [giving answers like this one](https://stackoverflow.com/a/58841651/2887218) and/or [impersonating an officer of the law](https://github.com/microsoft/TypeScript/issues/26223#issuecomment-513187373).

**Comment by jcalz** [comment]
Hmm, [look at that! Recursive `flat()`](https://github.com/microsoft/TypeScript/pull/32131#issuecomment-622470657)!

**Comment by jcalz** [comment]
Oh wow #40002 🌟 🎉 🎆 👍
