### ISSUE TITLE
Regression for omitted lambda parameter with tuple args

### ISSUE THREAD

**Issue by ulrichb** [microsoft/TypeScript#30301]
**TypeScript Version:**  3.4.0-dev.20190309

**Search Terms:** 3.4 tuple lambda

**Code**

The following snippet compiles fine in TS 3.3 whereas it emits an error in TS 3.4.

```ts
type MyTupleItem = {};
type MyTuple = [MyTupleItem, ...MyTupleItem[]];

type GenericFunction<T extends MyTuple> = (...fromArgs: T) => void;

class GenericClass<T extends MyTuple> {
    from: T | undefined;
}

function createClass<T extends MyTuple>(f: GenericFunction<T>): GenericClass<T> {
    return new GenericClass<T>(/* ... use f */);
}

function consumeClass(c: GenericClass<[string, boolean]>) { }

// ERROR:
consumeClass(createClass(str => console.log(str.length)));

// WORKS:
consumeClass(createClass((str, _unused_num) => console.log(str.length)));
```

**Expected behavior:**

No compile error.

**Actual behavior:**

```plain
>npx tsc TypeScriptIssueNext.ts
TypeScriptIssueNext.ts:18:14 - error TS2345: Argument of type 'GenericClass<[string]>' is not assignable to parameter of type 'GenericClass<[string, boolean]>'.
  Property '1' is missing in type '[string]' but required in type '[string, boolean]'.

18 consumeClass(createClass(str => console.log(str.length)));
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Playground Link:** [Link](https://www.typescriptlang.org/play/#src=type%20MyTupleItem%20%3D%20%7B%7D%3B%0Atype%20MyTuple%20%3D%20%5BMyTupleItem%2C%20...MyTupleItem%5B%5D%5D%3B%0A%0Atype%20GenericFunction%3CT%20extends%20MyTuple%3E%20%3D%20(...fromArgs%3A%20T)%20%3D%3E%20void%3B%0A%0Aclass%20GenericClass%3CT%20extends%20MyTuple%3E%20%7B%0A%20%20%20%20from%3A%20T%20%7C%20undefined%3B%0A%7D%0A%0Afunction%20createClass%3CT%20extends%20MyTuple%3E(f%3A%20GenericFunction%3CT%3E)%3A%20GenericClass%3CT%3E%20%7B%0A%20%20%20%20return%20new%20GenericClass%3CT%3E(%2F*%20...%20use%20f%20*%2F)%3B%0A%7D%0A%0Afunction%20consumeClass(c%3A%20GenericClass%3C%5Bstring%2C%20boolean%5D%3E)%20%7B%20%7D%0A%0A%2F%2F%20ERROR%3A%0AconsumeClass(createClass(str%20%3D%3E%20console.log(str.length)))%3B%0A%0A%2F%2F%20WORKS%3A%0AconsumeClass(createClass((str%2C%20num)%20%3D%3E%20console.log(str.length)))%3B%0A)

**Comment by RyanCavanaugh** [comment]
@ahejlsberg thoughts on the priority of the contextual type vs the lambda?

**Comment by ulrichb** [comment]
What, 3.5? ... I think it's okay to defer it to a later 3.4.x version, because it's easily workaroundable. But 3.5?

**Comment by weswigham** [comment]
We haven't triaged _anything_ into a `3.4.2` yet. We'll worry about that once `3.4` actually ships :shipit:

**Comment by ulrichb** [comment]
Okay. Thanks for the update.

**Comment by ahejlsberg** [comment]
As written, the error in the example is correct. `GenericClass<T>` uses `T` as the type of a property, and, following instantiation, we end up with properties of type `[string]` and `[string, number]` which aren't assignable to each other.

Now, if the `from` property had type `GenericFunction<T>` you could argue that we should consider `GenericFunction<[string]>` to be assignable to `GenericFunction<[string, number]>` because `T` is *only* used in a rest parameter position. However, our generics variance measurement logic doesn't capture that nuance, and I'm not sure it is worth the added complexity.

**Comment by weswigham** [comment]
@ahejelsberg https://github.com/microsoft/TypeScript/pull/33020
