### ISSUE TITLE
TypeScript Tools for VS 2015 2.0.2.0 Beta not working (on Windows Server 2012??)

### ISSUE THREAD

**Issue by TianCNCA** [Microsoft/TypeScript#11110]
**TypeScript Version:**  2.0.2.0

I was using VS2015 Update 3 with the built-in TypeScript tool, version 1.8.6 succesfully. 

Today I tried to upgrade it using TypeScript Tools for VS 2015 2.0.2.0 Beta. After installing the tools successfully, there's no more auto-completion in VS (the syntax highlight is still there). And the Build command exits with error.

I decided to roll back to 1.8.6 so I uninstalled 2.0.2.0 Beta. I checked that the TypeScript folder under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft` and `C:\Program Files (x86)\Microsoft SDKs` are gone. But executing the TypeScript_Dev14Full.exe (1.8 version) doesn't recreate those folders again.

So I had to switch back to 2.0 again. I installed it once again. Now after opening my TypeScript project there is even no syntax highlighting, not to mention auto completion and Build, and upon open project properties it shows
```
An error occurred trying to load the page.
No exports were found that match the constraint: 
	ContractName	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
	RequiredTypeIdentity	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
```
I've been Googling for hours but I haven't found any workable solutions. One of the issues I found at https://github.com/Microsoft/TypeScript/issues/7519 bears the most similar symptoms and it suggests delete the `%localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache` folder. I did that and it did not work and it shows a message saying 'An exception has been encountered. This may be caused by an extension.' and it asks me to check the ActivityLog.xml 
[ActivityLog.txt](https://github.com/Microsoft/TypeScript/files/490784/ActivityLog.txt) here is the txt version since github doesn't support xml. Please take a look if it's helpful.

I haven't seen any other posts that describe situations similar to mine.

Please help.

**Expected behavior:**
TypeScript Tools for VS 2015 2.0.2.0 Beta work properly.

**Actual behavior:** 
It does not. See descriptions above.

**Comment by mhegazy** [comment]
Sounds like an installer issue. can you try to
- Uninstall all versions of TS you have installed
- Install latest Update 3: https://msdn.microsoft.com/en-us/library/mt752379.aspx (even if you have installer an earlier version of Update 3 already).
- Install TS 2.0.3 from https://www.microsoft.com/en-us/download/details.aspx?id=48593

If this does not work, please share your install logs for these operations. the install logs should be under `%TEMP%` and should have the prefix `dd_typescript*`.

**Comment by GopiAnnan** [comment]
I have the same issue using Typescript 2.0.3.
Using VS 2015 Professional with update 3 (Latest version , from  https://msdn.microsoft.com/en-us/library/mt752379.aspx)
Error : 
An error occurred trying to load the page.
No exports were found that match the constraint: 
	ContractName	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
	RequiredTypeIdentity	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider

Have attached Installation log files. 
[dd_TypeScript_Dev14_20160923221717_001_TypeScript_Dev14.msi.txt](https://github.com/Microsoft/TypeScript/files/490919/dd_TypeScript_Dev14_20160923221717_001_TypeScript_Dev14.msi.txt)
[dd_TypeScript_Dev14_20160923221717_000_TypeScript_SDK.msi.txt](https://github.com/Microsoft/TypeScript/files/490920/dd_TypeScript_Dev14_20160923221717_000_TypeScript_SDK.msi.txt)

**Comment by GopiAnnan** [comment]
@mhegazy 

I have the same issue ,

An error occurred trying to load the page.
No exports were found that match the constraint: 
	ContractName	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
	RequiredTypeIdentity	Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
Using VS 2015 Professional Edtion, With Update 3 from 

- Have installed Update 3 from Location : https://msdn.microsoft.com/en-us/library/mt752379.aspx)
- Have installed Typescript 2.0.3 for VS 2015.

Have attached Installation Logs.
[dd_TypeScript_Dev14_20160923221717.txt](https://github.com/Microsoft/TypeScript/files/490925/dd_TypeScript_Dev14_20160923221717.txt)
[dd_TypeScript_Dev14_20160923221717_001_TypeScript_Dev14.msi.txt](https://github.com/Microsoft/TypeScript/files/490926/dd_TypeScript_Dev14_20160923221717_001_TypeScript_Dev14.msi.txt)
[dd_TypeScript_Dev14_20160923221717_000_TypeScript_SDK.msi.txt](https://github.com/Microsoft/TypeScript/files/490927/dd_TypeScript_Dev14_20160923221717_000_TypeScript_SDK.msi.txt)

**Comment by mhegazy** [comment]
Just to make sure I understand the sequence correctelly, did you uninstall TS 2.* before installing update 3 or not?

**Comment by GopiAnnan** [comment]
@mhegazy 
I have uninstalled Typescript 2.0.3.
Repaired VS 2015 Update 3,
Installed again Typescript 2.0.3

Still the same issue, Have attached Typescript Logs and Batch Installation Logs.

Note: tried with 2.0.2 Beta as well . I had the same  @issue

[dd_TypeScript_Dev14_20160923234028_000_TypeScript_SDK.msi.txt](https://github.com/Microsoft/TypeScript/files/490951/dd_TypeScript_Dev14_20160923234028_000_TypeScript_SDK.msi.txt)
[dd_TypeScript_Dev14_20160923234028_001_TypeScript_Dev14.msi.txt](https://github.com/Microsoft/TypeScript/files/490952/dd_TypeScript_Dev14_20160923234028_001_TypeScript_Dev14.msi.txt)
[dd_TypeScript_Dev14_20160923234028.txt](https://github.com/Microsoft/TypeScript/files/490955/dd_TypeScript_Dev14_20160923234028.txt)

Update 3 Installation  Log

[dd_patch_KB3165756_20160923233130.txt](https://github.com/Microsoft/TypeScript/files/490956/dd_patch_KB3165756_20160923233130.txt)
[dd_patch_KB3165756_20160923233130_028_Preparation_patch_KB3165756.txt](https://github.com/Microsoft/TypeScript/files/490957/dd_patch_KB3165756_20160923233130_028_Preparation_patch_KB3165756.txt)
[dd_patch_KB3165756_20160923233130_028_Preparation_patch_KB3165756_{919C67A9-2DE8-4929-A910-CB85E009B5CB}.txt](https://github.com/Microsoft/TypeScript/files/490958/dd_patch_KB3165756_20160923233130_028_Preparation_patch_KB3165756_.919C67A9-2DE8-4929-A910-CB85E009B5CB.txt)

**Comment by mhegazy** [comment]
Can you try devenv /setup from a vs command prompet.

**Comment by GopiAnnan** [comment]
Cleared AppData\Roaming\VS\14.0 folder and tried devenv  /setup . still
have the same issue.

If I try with 1.8.4 typescript is trying to load. but that has conflict
with new version installation files. May be VS 2015 Repair will do for
Typescript 1.8.4.

But for 2.0.2 and 2.0.3  have the same issue.

**Comment by mhov** [comment]
I'm in the same boat.  I can't even get 1.8.x to work again.

**Comment by mhegazy** [comment]
I have not been able to set up a local machine to reproduce this issue. I would appreciate any information you can share about what was installed on the machine, and how you got to the broken state.

Also it would be great if you can tell me what versions of TS are installed using `Add or Remove Programs` now. 

Can you also share the versions of `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TypeScript\Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll` that you currently have.

**Comment by GopiAnnan** [comment]
When I have installed 2.0.3 ,  Initially there was no issue. But no
features were working. Its not highlighting any syntax, error or nothing.
Just only compile time it throws error.
Otherwise its just behaving like text file. Its no were near Visual studio
code.

Then I thought, this is due to multiple version of Typescript installed .
So.. To clear it I have uninstalled 1.8.4 and Deleted 1.0  from (C:\Program
Files (x86)\Microsoft SDKs\TypeScript) as there was no uninstall option.

After that I have started getting that error.

To Fix this, I have uninstalled 2.0.3 , UnInstalled VS 2015. Installed VS
2015 with Latest Update 3. Then Typescript 2.0.3. Now I don't see that
Error. But now I came to my old state, No syntax highlighting, not showing
errors. * Is this expected behavior or is there anything I am missing?*
* Is Visual Studio 2015 has same behavior as Visual Studio Code Or my
understanding is wrong?  *

Now.. For time being till VS 2015 start behaving smoothly with Typescript.
  I moved to Visual Studio Code. And have asked my team members to move
Visual Studio Code instead of VS 2015.

*Typescript Editor version is : 14.30921.1.0*

**Comment by TianCNCA** [comment]
It's good to know that I'm not the only person who's having this issue. My situation is exactly the same as @GopiAnnan 's , thanks for giving a better description.

To provide more information, 
**before it's broken**
OS: Windows Server 2012
VS: 2015 with the latest Update 3
TypeScript: 1.8

**after it's broken**
OS: Windows Server 2012
VS: 2015 with the latest Update 3
TypeScript: 2.0.2.0 Beta

My current `Microsoft.CodeAnalysis.TypeScript.EditorFeature` version is 14.300828.1.0

I actually tried TypeScript 2.0 the moment it was out but it wasn't successful (with all the same problems described in this post) so I rolled back to 1.8. I tried 2.0.2 last Friday hoping it would be different, but it was the same.

**Comment by mhegazy** [comment]
@TianCNCA, can you install TS 2.0.3, https://www.microsoft.com/en-us/download/details.aspx?id=48593 then share the install log `%TEMP%\dd_TypeScript*.log`?

**Comment by TianCNCA** [comment]
@mhegazy here are the files
[dd_TypeScript_Dev14_20160926151629_000_TypeScript_SDK.msi.log.txt](https://github.com/Microsoft/TypeScript/files/494031/dd_TypeScript_Dev14_20160926151629_000_TypeScript_SDK.msi.log.txt)
[dd_TypeScript_Dev14_20160926151629_001_TypeScript_Dev14.msi.log.txt](https://github.com/Microsoft/TypeScript/files/494033/dd_TypeScript_Dev14_20160926151629_001_TypeScript_Dev14.msi.log.txt)
[dd_TypeScript_Dev14_20160926151629.log.txt](https://github.com/Microsoft/TypeScript/files/494032/dd_TypeScript_Dev14_20160926151629.log.txt)

**Comment by mhegazy** [comment]
@yuit, any thoughts?

**Comment by mhov** [comment]
I fixed mine by completely uninstalling VS2015, wiping out all the AppData folders for VS, reinstalling VS2015 U3, then installing TS 2.0.3.

So while that doesn't help anyone not willing to nuke their VS install, I did remember something from my original install that might have help diagnose the issue.  When the 2.0.0 beta was released, I started the VS install package, but cancelled it mid-installation (since it suddenly occurred to me not to screw with my TS workflow the night before a big deploy).  TS 1.8.10 was working fine after that, but once I tried to install the proper TS 2.0.3 release, I lost all TS functionality in VS.  So perhaps something was modified mid-installation that wasn't rolled back when cancelled?

**Comment by TianCNCA** [comment]
@mhov That was not my case. I let my installations finish completely yet all TS functionalities don't work after that.

**Comment by JasonMcEvoy** [comment]
Same issue with Visual Studio 2015 enterprise Typescript broken and just white text. and js files now wont open just throw error

**Comment by yuit** [comment]
I am investigating the issue currently. I will post an update and hopefully a solution to this issue

**Comment by yuit** [comment]
I am trying to repo the problem locally on my machine. Following [steps](https://github.com/Microsoft/TypeScript/issues/11110#issuecomment-249343283) . From looking into logs file you guys share, it seem that (both VS and SDK install and no errors occur. However, in the AcitvityLog.xml, it seems that some components are not update and when tyring to load TypeScript LS, it can't find necessary stuffs

**Comment by GopiAnnan** [comment]
Here we are discussing about 2 issues.

1) Project properties Typescript Section shows this below Message   

An error occurred trying to load the page.
No exports were found that match the constraint: 
    ContractName    Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider
    RequiredTypeIdentity    Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ITypeScriptProjectProvider

2)  VS 2015 is not having any Syntax Highlighter with Latest Typescript 2.0.3 

To Fix First Issue : 

Uninstall  all version of TypeScript 2.0.3, 18.4, 1.0 what ever. 
Uninstall VS 2015
Restart Machine
Install VS 2015 
Install Typescript 2.0.3
This will solve the first issue. In Project properties , Typescript section you wont be seeing that error. 

But still you may have the second issue. Its not highlighting any syntax or error. Its just behaves like Text editor but at compile time it throws all compilation errors.

To  resolve 2nd issue, 
If you have installed web extension pack and web essentials uninstall those packages.  (This step may not be required, but that's what I have done)
Leave that VS 2015 instance open
Uninstall Typescript 2.0.3 using your Typescript Installer or Control Panel Programs.  This time you will get alert to close Visual Studio otherwise you have to reboot. Choose the option to reboot. So that VS 2015 will not get closed .  After TS installation you reboot your system.

Now you should be having working environment with TS 2.0.3 with VS 2015 with syntax highlight and error. And on top of this you can install Web Extension Pack if you want. 

I have periodically one more error, "NuGet Package instance used by another process, So it not able to upgrade". This may related anything with this?

@yuit I am using Windows 7 Ent.

**Comment by brianchance** [comment]
@GopiAnnan - thank you, the fix for the 2nd issue worked for me. I did not uninstall web extension pack or web essentials. 

@yuit I am using windows 10 pro

**Comment by mhegazy** [comment]
We have traced this back to Chakra issue on some OS's. we are following up on this and should have an update shortly.

**Comment by mhegazy** [comment]
We have a fix for this available. figuring out the release schedule for this. We should have more updates soon.

**Comment by deadZedd** [comment]
Had the same issue after upgrading from 1.8 to 2.0 (VS2015 U3, Win10):
 - no intellisense or automatic indentation
 - errors only show on build
 - syntax highligting was present

Solution: 
 - Uninstall TS 2.0.3
 - Repair Visual Studio Update 3 (latest patch), reboot
 - Install TS 2.0.3

**Comment by CrustyJew** [comment]
If anyone else is stumbling into this issue, I tried the uninstall, repair, reinstall method and it didn't work for me, but on a whim I just tried a repair of the TS 2.0.3 install and it worked. 

I had VS2013 U3 up at the time so the repair prompted me to close it or restart. I told it to close VS and restart it, it closed visual studio, immediately opened it back up, and prompted me the same question. I manually closed VS, then selected OK again and it completed the repair. With the installer still open and saying completed, I opened up VS 2015 and I have intellisense again.

Most of that's probably voodoo and not important, but bottom line, try a repair on TS 2.0.3 , it might fix it.

**Comment by mhegazy** [comment]
[TypeScript 2.0.6](https://github.com/Microsoft/TypeScript/releases/tag/v2.0.6) should be available now; please give it a try and let us know if there are other issues.

**Comment by nxplus** [comment]
I had these issues with VS2015 update 3 (as listed by @deadZedd ) and typescript 2.0.6, repairing VS and reinstalling typescript was not enough. 

I did the steps suggested by @paulvanbrenk (see issue #7519) and had success.. coloring, intellisense, auto format/indentation and completion works again.
