### ISSUE TITLE
Breaking change due to: "does not exist on type 'Storage'."

### ISSUE THREAD

**Issue by Akxe** [Microsoft/TypeScript#26083]
**TypeScript Version:**  above > 3.0.1 only (tested 2.9.2 and worked fine)

**Search Terms:**
does not exist on type 'Storage'., storage
**Code**

```ts
try {
	return JSON.parse(sessionStorage.playerPlayed);
} catch (error) {
	return {};
}
```

**Expected behavior:**
No error introduced after upgrade to 3.0.0 or above

**Actual behavior:**
Had to rewrite it to `JSON.parse(sessionStorage.getItem('playerPlayed') || '{}');`. I mean it is okay, but a note on this change would be apreciated.

**Playground Link:** 
http://www.typescriptlang.org/play/#src=JSON.parse(sessionStorage.playerPlayed)%0D%0AJSON.parse(sessionStorage.getItem('playerPlayed')%20%7C%7C%20'%7B%7D')%0D%0A

**Related Issues:** 
Not sure, non actually found.

**Comment by mhegazy** [comment]
This seems to be behaving per spec. see https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface

From the spec:

> The `getItem(key)` method must return the current value associated with the given key. If the given key does not exist in the list associated with the object then this method must return `null`.

you can use the pang operator to assert that the value is defined:

```ts
JSON.parse(sessionStorage.getItem('playerPlayed')!);
```

**Comment by Akxe** [comment]
The broken part is that now you can't access the keys using dot notation, but have to use the getItem/setItem methods. That has changed since 3.0.0, previously you could simply retrive them by accessing them.

**Comment by mhegazy** [comment]
:) D'oh..

Looks like we removed the index signature from the type.

You can work around this now by defining the index signature locally:

```ts
interface Storage {
    [key: string]: any;
}
```
