### ISSUE TITLE
Cannot export const enum in Export Declaration

### ISSUE THREAD

**Issue by EvanCahill** [microsoft/TypeScript#33060]
**TypeScript Version:**  3.6.1-rc

**Search Terms:** const enum export declaration TS2475

**Code**

```ts
// test.ts
const enum Test {}
export { Test };
```

**Expected behavior:**
The above code compiles without errors.

**Actual behavior:**
> test.ts:2:10 - error TS2475: 'const' enums can only be used in property or index access expressions or the right hand side of an import declaration or export assignment or type query.

**Playground Link:** 
http://www.typescriptlang.org/play/#code/MYewdgzgLgBApmArgWxgFTtGBvAvgKDgA8AHEAJ1m3U1lwG4g

**Related Issues:**
N/A

**Comment by EvanCahill** [comment]
Same code is working in 3.5.3. The issue is also present in typescript@next (3.7.0-dev.20190823).

**Comment by EvanCahill** [comment]
Seems like it was introduced in #28498.

**Comment by Shin-Ogata** [comment]
This issues is serious problem for me the following point. Do you plan to fix it?

* Problem: Cannot re-export "const enum" which would like to hide the namespace but reuse one from `.ts` file.

@third/namespace.d.ts

```ts
export namespace HiddenThirdModule {
    
    export const enum ReuseConst {
        AAA = 'aaa',
        BBB = 'bbb',
    }
}

```

exports.ts
```ts
import { HiddenThirdModule } from '@third';

import ReuseConst = HiddenThirdModule.ReuseConst;
export { ReuseConst };  // error: ts2475
```


* The follow cases are no problem.

1. direct re-export

@third/enum.d.ts

```ts
export const enum ReuseConst {
    AAA = 'aaa',
    BBB = 'bbb',
}

```

exports.ts
```ts
import { ReuseConst } from '@third';
// export { ReuseConst }; // error: ts2475
export { ReuseConst } from '@third';
```

2. from `d.ts` re-export
exports **.d** .ts
```ts
import { ReuseConst } from '@third';
export { ReuseConst }; // no-error
```

**Comment by willem-jan-ndaw** [comment]
I've noticed 3.7 beta is already announced yet this issue is still open. Should we consider this an undocumented Breaking change of 3.6 and live with it? or are there plans to get it fixed?

**Comment by vyushin** [comment]
He, stranger! 

Assume are you looking for soluton
`TS2475: 'const' enums can only be used in property or index access expressions or the right hand side of an import declaration or export assignment or type query.` ? :)


1) Enable `--preserveConstEnums` in tsconfig.
2) If you're export constant from other file, doesn't use named import, like this
```javascript
import { MyConst } from './constants.ts';
console.log(MyConst ); // Error
```
3) Import all from module, if you want using enum as JavaScript object
```javascript
import * as Constants from './constants.ts';
console.log(Constants); // {MyConst : {…}, __esModule: true}
```

These steps allow me use enums as enumerable JavaScript object in TypeScript 3.9.5.
I spend lot of time to find solution but I hope it help you with your issue ❤️

**Comment by guilhermesimoes** [comment]
> Import all from module, if you want using enum as JavaScript object
> // index.ts
> import * as Constants from './constants.ts';
> console.log(Constants); // {MyEnum: {…}, __esModule: true}

I don't think this is a solution, since this breaks tree-shaking

**Comment by ivana-g** [comment]
in my case removing the `const` from enum declaration fixed the issue and I didn't have to change  tsconfig. 

```
enum MyEnum {
  A, B, C,
}
```

But I wander why declaring the enum with a const like `const enum MyEnum {}` causes issues? Does anybody have a good explanation? Thanks,
