### ISSUE TITLE
async function bug?

### ISSUE THREAD

**Issue by yortus** [Microsoft/TypeScript#11376]
**TypeScript Version:**  nightly (2.1.0-dev.20161004)

**Code**

``` ts
// @target: es5
async function foo(): string { // OK, but should be error
    return 'foo';
}

let s = foo(); // OK, type of s is string, but should be Promise

s = s.concat('bar'); // OK, but runtime error 's.concat is not a function'
```

**Expected behavior:**
Compiler error on `foo` declaration about invalid return type annotation.

**Actual behavior:** 
Compiles without errors and crashes at runtime.

**Comment by vladima** [comment]
offending commit 203dab44122fea4bb2efb558a41ec098e4368bed
// CC: @rbuckton
