### ISSUE TITLE
Can't add globals to `window` in 5.3.2

### ISSUE THREAD

**Issue by beaugunderson** [microsoft/TypeScript#56569]
### 🔎 Search Terms

"globalThis", "window"

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and 5.3.2

### 💻 Code

I have a `src/globals.d.ts` file like this:

```ts
declare global {
  interface Window {
    xyz: {
      application: {
        doSomething(): void;
      };
    }
  }
}
```

In 5.2.2, I can use methods like `window.xyz.application.doSomething()` anywhere in my codebase.

In 5.3.2, I get this error on any usage:

```
src/SomeFile.tsx:183:12 - error TS2339: Property 'xyz' does not exist on type 'Window & typeof globalThis'.

183     window.xyz.application.doSomething();
               ~~~
```

I looked at the changelogs between 5.2.2 and 5.3.2 and did not see a potential cause.

If there is a way to `git bisect` through commits of the `typescript` module within my project I would be happy to do that to find the exact commit.

### 🙁 Actual behavior

`tsc` reports the error above.

### 🙂 Expected behavior

`tsc` reports no errors.

**Comment by beaugunderson** [comment]
After further research it appears that in 5.2.2 `src/globals.d.ts` shows up under `files` in `yarn tsc --showConfig` and in 5.3.2 it does not.

**Comment by beaugunderson** [comment]
A-ha!

I also had a `Globals.tsx` and hit this issue, which apparently changed behavior since 2016, and has now changed back in 5.3:

https://github.com/Microsoft/TypeScript/issues/7624#issuecomment-202501572

Renaming my `globals.d.ts` to `window.d.ts` solved my issue.
