### ISSUE TITLE
Better JSX extraneous property error range

### ISSUE THREAD

**Issue by Nathan-Fenner** [microsoft/TypeScript#33476]
The error range on extraneous JSX properties highlights the component name instead of the offending property:

**Current Behavior**:

```typescript
import * as React from 'react';

function Example(props: {x: number, y: string}) {
    return <>Hello, world.</>;
}

<Example x={3} y="a" z={6} />
 ~~~~~~~
```

**Desired Behavior**:

```typescript
import * as React from 'react';

function Example(props: {x: number, y: string}) {
    return <>Hello, world.</>;
}

<Example x={3} y="a" z={6} />
                     ~~~~~
```

in both cases, the error message is rightly

```
 Type '{ x: number; y: string; z: number; }' is not assignable to type 'IntrinsicAttributes & { x: number; y: string; }'.
   Property 'z' does not exist on type 'IntrinsicAttributes & { x: number; y: string; }'.
```

The situation seems to have been improved from #23117 but I feel that it could still be better by highlighting the offending property in particular.

**TypeScript Version:**  3.6.3 (also verified with 3.7.0-dev.20190914)

**Search Terms:** jsx error range extra property type error message

**Playground Link:** 

[playground](http://www.typescriptlang.org/play/?jsx=2#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdBArgHb7AQtwCiAHsuAA2WABRhiYVAC44Ab14yWTEACMsUADRwAnjNQwowFgHMAvgEo5dODbiUYTKFwA8APgASWQYIhaA7tCCACYAdM4A9K70pgzOfAJgwnC8ALyyAMymOikARMg5cABeaQBsWZFAA)

**Related Issues:** 
#23117

**Comment by DanielRosenwasser** [comment]
Thanks @Nathan-Fenner!
