### PR TITLE
Use the wildcard type for signature erasure

### LINKED ISSUE #23352: `cb: (x: T) => void` not assignable to `cb: (x: T) => void` when it has an overload: "'any' is not assignable to 'never'"
**TypeScript Version:**  2.9.0-dev.20180411

**Code**

```ts
declare function provide<T>(cb: (x: T) => void): void;
declare function provide<T>(cb: (x: T[keyof T]) => void): void;

declare function provider<T>(provide: (cb: (x: T) => void) => void): void;
provider(provide);
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(4,10): error TS2345: Argument of type '{ <T>(cb: (x: T) => void): void; <T>(cb: (x: T[keyof T]) => void): void; }' is not assignable to parameter of type '(cb: (x: never) => void) => void'.
  Types of parameters 'cb' and 'cb' are incompatible.
    Types of parameters 'x' and 'x' are incompatible.
      Type 'any' is not assignable to type 'never'.
```

Worked in `typescript@2.9.0-dev.20180327`, broken in `typescript@2.9.0-dev.20180328`.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #23352's first issue. We used `any` as a "type erasure placeholder" so that we could assume it would allow all assignability. It does, not, however, allow assignability to `never` (which is the cause of the issue). The `wildcardType` (an `any` variant) we introduced for inference awhile back _does_ admit assignability to `never`, and so fulfills the erasure duty better.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this

**Comment by sandersn** [comment]
@weswigham do the baselines look good for this change?

**Comment by weswigham** [comment]
DT was clean, rwc was mostly clean (just an elaboration change when relating jquery promise to normal promise in a case where there was already an error), user baselines were.... _probably_ clean? There's some noise there, but I think it's unrelated. Perf looks fine.

**Comment by RyanCavanaugh** [comment]
Closing due to closing the upstream bug
