### ISSUE TITLE
Compiling a directory with --outDir causes generation of paths not matching the source when some .ts files are symlinked

### ISSUE THREAD

**Issue by niieani** [microsoft/TypeScript#9414]
**TypeScript Version:**  either 1.8.10 and 2.0.0-dev.20160629

**Expected behavior:**
We're sharing code between frontend and backend projects in TypeScript by symlinking a directory with files that are common to both of them. 
The expected behavior is that the output directory mirrors the source directory - i.e. both the symlinked and real files are placed in their correct, respectful output directories when compiled.

**Actual behavior:** 
Files are placed into a generated directory structure that doesn't mirror the directory structure of the source, but that of the **resolved directory structure** from the _first common basedir_ between the _tsc_ project and the _parent directory_ of where the symlinks points to. If this explanation is not clear enough, I can provide an example.

Note: When the `rootDir` is defined, it is still not respected by `tsc`, which complains that:

> 'rootDir' is expected to contain all source files

Even though all the files or symlinks to files actually **are** contained under the `rootDir`.

**Comment by mhegazy** [comment]
symlinks are not fully supported. they are supported for node modules (i.e. npm link), other than that they are not used.

**Comment by bfsmith** [comment]
I have the same problem.  This was working in TS 1.8.10 but is not working in TS 2.0.3.  I have the following structure.

```
/client
  shared -> /shared // symlinked
/server
  shared/ -> /shared  // symlinked
/shared
```

I started getting this error after upgrading to TS 2.0.3.
`error TS6059: File '/shared/assert.ts' is not under 'rootDir' '/server'. 'rootDir' is expected to contain all source files.`

I've npm linked now instead.
```
/shared > npm link
/server > npm link shared
```
shared is now in node_modules with its .ts files.  After updating my imports to non-relative paths, running `tsc` still gets the 'rootDir' error above.

What is the expected best practice for this?

**Comment by RyanCavanaugh** [comment]
Project references are the preferred way to deal with these kinds of scenarios now

**Comment by dietergeerts** [comment]
> Project references are the preferred way to deal with these kinds of scenarios now
I tried that, and they are not working when you have a mono-repo which has mixed JS and TS packages.
