### ISSUE TITLE
Type [number,number] is not recognized correctly

### ISSUE THREAD

**Issue by twoeo** [Microsoft/TypeScript#12579]
**TypeScript Version:**  2.1.1 / nightly (2.2.0-dev.201xxxxx)
2.1.1

**Code**

```ts
type Data = [number, number];
let a:Data = [1,2,3,4,5].map(v=>[v, v+1]);
```

**Expected behavior:**
Compiled successfully.

**Actual behavior:**
> test.ts(3,5): error TS2322: Type 'number[][]' is not assignable to type '[number, number]'.
Property '0' is missing in type 'number[][]'.

It seems work well in 2.0, throw this error after update to 2.1

**Comment by aluanhaddad** [comment]
Error message is a bit off putting but I think the behavior is right.
You can add this to make it work
```ts
interface Array<T> {
  map(f: (x: T) => [T, T]): [T, T][];
}

type Data = [number, number];
let a: Data[] = [1, 2, 3, 4, 5].map(v => [v, v + 1]);
```

**Comment by twoeo** [comment]
Shouldn't `v=>[v, v+1]` be recognized as `[number, number]` instead of `number[][]` ?

**Comment by mhegazy** [comment]
Tuple types are only inferred in the presence of a contextual type. e.g. `let a: Data = [1, 2]`. the issue here is that the contextual type does not flow through `map`, since the return type position is not a generic argument inference site. issue https://github.com/Microsoft/TypeScript/issues/11152 is tracking fixing that.

**Comment by mhegazy** [comment]
closing in favor of https://github.com/Microsoft/TypeScript/issues/11152
