### ISSUE TITLE
Breaking change: Depth limit now hit for some types in 4.3

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript#43877]
# Bug Report

### 🔎 Search Terms

Depth limit  4.3

### 🕗 Version & Regression Information

- This changed between versions 4.2 and 4.3

### 💻 Code

Happens in a large codebase, I am currently unable to reproduce. The new error appears when a complex mapped & conditional type is used

### 🙁 Actual behavior

Multiple new: `error TS2589: Type instantiation is excessively deep and possibly infinite.`

### 🙂 Expected behavior

Type checks successfully  as in 4.2

##Note

I bisected and found that this [PR](https://github.com/microsoft/TypeScript/pull/30639) is introducing this break. While the behavior outlined there seems to be a net improvement, maybe a solution that doesn't break existing types can be found? Or if not this should be outlined in the 4.3 release notes as a breaking change.

**Comment by RyanCavanaugh** [comment]
cc @DanielRosenwasser fyi

**Comment by dragomirtitian** [comment]
@RyanCavanaugh @DanielRosenwasser I have a repro for the issue. It's not very small but it's the smallest I could get. This works with 4.2 but not 4.3:

[Playground Link](https://www.typescriptlang.org/play?ts=4.3.0-beta#code/C4TwDgpgBAsghiARhGEBOBzCAFNBLANzmAgGUBXSNUyAYwB4AVAPigF4pGoIAPEgOwAmAZygAlCLQD2aQfWHB8-DABooAYQA2cYcJqTmAKCgmoAfljosuQsTKV0+hi2OmAXFADeAXwDchw1BIWARkVEwcfCISJ2Embj4IIVEtHT06NQBVVg5MhIERDW1dJ1cTC3DrKLtY+ky1F1MoD0Z-QPBoSsjbGLo4rl4ClOL0yRU8waTC1JK6HK8yqDByRE08WhaAbQByZdX17YBdKAAyKEydvbXaI-8msDQpEloSQS3dx+fXo9Pzy8-JN9DndTA8ehB3mDohAfmcLh9wbdDH4AkFOlZutCKFQnPFJslxJIZHIFEpVEU0k5mPNMvw8FJ+IwpABJfgkNDCQH0-j0TyLTbYKB4fhQADWEBAUgAZpxDh5SHgALZgNZSkA2LF0JibcWSmWMQ5Gbw6iXS2VGQy8MAyYBQNFQBXK1Xq6q9SR4xIEmajWjzeBIFAYjU1Pr0Rb+sJB11kUOLJoRwMRYNu2hxONNUyMFTpjMhANdZP2HFaxibABEV3WAFFPSIy4ac1BmNncyYEwXo9jHCXyw8noCIIIa0N60Yms3w6FE1VwV3qD2K9Hh1NhKPDMw2u1grTuUzWezOS9uXV5gAKCa10RwfggcxQU+ijyZACU7FY5H4ov4UgA7iKPPwEAEOgr74oUD4eMKUroFAzKvmw76ft+f53syzRQIBwFoG0wrslKcC0NA3pOAs9wrNcZgeFIiAAFaAiCJhQnYlFQNRdEvAxSwAi8g4sWx9GLJWtDLskLESNIsjyIowrksRcycX2XyDiJIhiUSkmkjJahyQYClLpeakSSS0nKNpIxUv43hAA)

**Comment by DanielRosenwasser** [comment]
I'll let @RyanCavanaugh re-triage if appropriate, but if there's a good general fix here, it might be good to bring it to 4.3. There might be limitations though, and we might have to consider this "Working as Intended" or "Design Limitation".

**Comment by andykog** [comment]
Here's another repro (smaller than @dragomirtitian's):
[Playground link](https://www.typescriptlang.org/play?ts=4.3.4#code/PTAEHkCcEsHNoHYEMA2oDGB7AJgUwFygAWALiQA4DO+I8JRArgEYB0WAtsAO7QAeAtInTMkJTJGB4AZkgYoSlfnlzl+C4ExSYmwdkkolcEypHTBEeXiwUAoGyQCe5XKADCmBADcjh7AB4AFQA+UABeUABvG1BQAG0ABVBEUABrXAdMKVAAgF1CBDk0XF5DBGxKbISc0AB+SvjqwgCqmwBfAG47R2dQABFcGTkFfpVAgBpQAFVQYtLy7JDwqJiEpIRU9MzsnP4a-GiYqaqZktwyiuaG2oPD0AKUItPzo6uam9u3D29IXz9+wfklBG5ECVQmADkPODCkhNLg-JMqkFkaB9h96o13pccm1OjZEIZIDJ0C4APoAQUgkCQDkCIWWoCkFj8AGUTnMLkEABTkSC4bDQdCiAigLmeVAMEUBACUYRCTEwmBQuCQCGlhE8mGg2E6rTsWAQBlAAC9CBSqTS-gNZIDgX4Iq0Jg6UeFYjk8caWEyylzSXLQCRIJLpe0gA)
