### ISSUE TITLE
Typeguard with ""|undefined not working

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript#31156]
**TypeScript Version:**  3.3.0, and the version on TS playground (3.4.1 as of this writing)

**Search Terms:** typeguard, empty string literal, undefined, union

**Code**

```ts
//--strictNullChecks
type Falsy<T> = (
    | Extract<0, T>
    | Extract<
        (
            | false
            | null
            | undefined
            //Actually, only 0|NaN
            //But TS does not support NaN literal
            | number
            | ""
            | 0n
            | HTMLAllCollection
        ),
        T
    >
);
declare const emptyStrOrUndefined: Falsy<string | undefined>;
declare function isFalsy<T>(
    mixed: T
): mixed is Falsy<T>;

declare const s: string | undefined;
/*
    Hovering over this isFalsy() call gives me,
    function isFalsy<string | undefined>(mixed: string | undefined): mixed is "" | undefined

    This is as expected
*/
if (isFalsy(s)) {
    //Expected: s should be ""|undefined now
    //Actual: s is undefined
    if (s == undefined) {
        //Should be undefined now
        console.log(s);
    } else {
        //Expected: Should be "" now
        //Actual: s is `never`
        //Property 'length' does not exist on type 'never'.
        console.log(s.length);
    }
}

declare function isEmptyStrOrUndefined(mixed: any): mixed is "" | undefined;
if (isEmptyStrOrUndefined(s)) {
    //Expected: s should be ""|undefined now
    //Actual: s is undefined
    if (s == undefined) {
        //Should be undefined now
        console.log(s);
    } else {
        //Expected: Should be "" now
        //Actual: s is `never`
        //Property 'length' does not exist on type 'never'.
        console.log(s.length);
    }
}
```

**Expected behavior:**

`s` should be `""|undefined` where marked.

Also, unrelated, but this is where I would have liked a `NaN` literal in TS =/

**Actual behavior:**

`s` is `undefined`

**Playground Link:** [Here](https://www.typescriptlang.org/play/#src=%2F%2F--strictNullChecks%0D%0Atype%20Falsy%3CT%3E%20%3D%20(%0D%0A%20%20%20%20%7C%20Extract%3C0%2C%20T%3E%0D%0A%20%20%20%20%7C%20Extract%3C%0D%0A%20%20%20%20%20%20%20%20(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20false%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20null%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20undefined%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FActually%2C%20only%200%7CNaN%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%2F%2FBut%20TS%20does%20not%20support%20NaN%20literal%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20number%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20%22%22%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%200n%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20HTMLAllCollection%0D%0A%20%20%20%20%20%20%20%20)%2C%0D%0A%20%20%20%20%20%20%20%20T%0D%0A%20%20%20%20%3E%0D%0A)%3B%0D%0Adeclare%20const%20emptyStrOrUndefined%3A%20Falsy%3Cstring%20%7C%20undefined%3E%3B%0D%0Adeclare%20function%20isFalsy%3CT%3E(%0D%0A%20%20%20%20mixed%3A%20T%0D%0A)%3A%20mixed%20is%20Falsy%3CT%3E%3B%0D%0A%0D%0Adeclare%20const%20s%3A%20string%20%7C%20undefined%3B%0D%0A%2F*%0D%0A%20%20%20%20Hovering%20over%20this%20isFalsy()%20call%20gives%20me%2C%0D%0A%20%20%20%20function%20isFalsy%3Cstring%20%7C%20undefined%3E(mixed%3A%20string%20%7C%20undefined)%3A%20mixed%20is%20%22%22%20%7C%20undefined%0D%0A%0D%0A%20%20%20%20This%20is%20as%20expected%0D%0A*%2F%0D%0Aif%20(isFalsy(s))%20%7B%0D%0A%20%20%20%20%2F%2FExpected%3A%20s%20should%20be%20%22%22%7Cundefined%20now%0D%0A%20%20%20%20%2F%2FActual%3A%20s%20is%20undefined%0D%0A%20%20%20%20if%20(s%20%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2FShould%20be%20undefined%20now%0D%0A%20%20%20%20%20%20%20%20console.log(s)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2FExpected%3A%20Should%20be%20%22%22%20now%0D%0A%20%20%20%20%20%20%20%20%2F%2FActual%3A%20s%20is%20%60never%60%0D%0A%20%20%20%20%20%20%20%20%2F%2FProperty%20'length'%20does%20not%20exist%20on%20type%20'never'.%0D%0A%20%20%20%20%20%20%20%20console.log(s.length)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20isEmptyStrOrUndefined(mixed%3A%20string%7Cundefined)%3A%20mixed%20is%20%22%22%20%7C%20undefined%3B%0D%0Aif%20(isEmptyStrOrUndefined(s))%20%7B%0D%0A%20%20%20%20%2F%2FExpected%3A%20s%20should%20be%20%22%22%7Cundefined%20now%0D%0A%20%20%20%20%2F%2FActual%3A%20s%20is%20undefined%0D%0A%20%20%20%20if%20(s%20%3D%3D%20undefined)%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2FShould%20be%20undefined%20now%0D%0A%20%20%20%20%20%20%20%20console.log(s)%3B%0D%0A%20%20%20%20%7D%20else%20%7B%0D%0A%20%20%20%20%20%20%20%20%2F%2FExpected%3A%20Should%20be%20%22%22%20now%0D%0A%20%20%20%20%20%20%20%20%2F%2FActual%3A%20s%20is%20%60never%60%0D%0A%20%20%20%20%20%20%20%20%2F%2FProperty%20'length'%20does%20not%20exist%20on%20type%20'never'.%0D%0A%20%20%20%20%20%20%20%20console.log(s.length)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Related Issues:** Not that I could find

**Comment by jack-williams** [comment]
This looks like a bug to me. The current behaviour when the source type is a union (here `string | undefined`) is that the source is filtered against the candidate type (here `"" | undefined`) removing all types not related to the candidate. The type `string` is not related to `"" | undefined` and is therefore filtered out, returning `undefined` (which is related to `"" | undefined`).

When the source type is not a union then the code intersects the source with the candidate (`string & ("" | undefined)`), producing the right narrowing.

I think `getNarrowedType` should probably map over unions first, applying narrowing to each constituent, abit like `narrowTypeByTypeof`.

**Comment by RyanCavanaugh** [comment]
@andrewbranch fyi I didn't look fully into this, but generally assume @jack-williams is right 😉

**Comment by andrewbranch** [comment]
@RyanCavanaugh given the discussion in #31206, what should we bump the milestone to?

**Comment by andrewbranch** [comment]
Cross-posting from PR #31206 for visibility:

> We discussed this in a design meeting and decided there’s not currently a solution that’s worth the disruption it will bring. A hypothetical future where we can stop treating “branded primitives” as they exist today (e.g. `string & { __kind: 'path' }`) as possible value-containing types will help somewhat, and we also discussed this as an indicator that people often think about their object types as being closed, when in fact the type system doesn’t represent this at all (aside from excess property checking on fresh object literals).
>
> I may look into doing the correct thing when all constituents of both the original type and the predicate type are primitives, since intersections of those are more intuitive and fall out when empty. On the other hand, I’m not sure if we want that kind of logical branching—maybe it’s better just to keep it in its current slightly wrong but consistent state. At any rate, this PR is out of scope for that kind of change.

**Comment by AnyhowStep** [comment]
I need a sad face react =(

Thank you for the update, and the attempt!

**Comment by AnyhowStep** [comment]
This is a repro of a problem @G-Rath had,

```ts
//--strictNullChecks
declare const s: string | undefined;
declare function isEmptyStrOrUndefined(mixed: string|undefined): mixed is "" | undefined;
if (isEmptyStrOrUndefined(s)) {
    //Expected: s should be ""|undefined now
    //Actual: s is undefined
    if (s == undefined) {
        //Should be undefined now
        console.log(s);
    } else {
        //Expected: Should be "" now
        //Actual: s is `never`
        //Property 'length' does not exist on type 'never'.
        console.log(s.length);
    }
}


declare function isEmptyStr(mixed: string | undefined): mixed is "";
declare function isUndefined(mixed: string|undefined): mixed is undefined;
if (isEmptyStr(s) || isUndefined(s)) {
    //Expected: s should be ""|undefined now
    //Actual: s is undefined
    if (s == undefined) {
        //Should be undefined now
        console.log(s);
    } else {
        //Expected: Should be "" now
        //Actual: s is `never`
        //Property 'length' does not exist on type 'never'.
        console.log(s.length);
    }
}
```
[Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=33&pc=2#code/PTC0oZwFwJwSwMZQHIFcA26DCALApggNYQCwAUACYHoCGMeABAgPYB20DEAXJ7HKwHMGAHwapWVAGb88FANzkqCWvQaTxSOGwZwIAUQC2ABygBPAMqwA8jACqEvNNayAFAbgAPWT2jxBw8SkZCgBKHncvCh0IBgAiWJExBydZBTI4SQYXXUMTC2s7ZOCXCBCQhgBvcgYahhA9DyMCKG9OThxmDCiAI0Z4gKLnKNZmAHdq2pAAQSRUGnQfaKSgoYmajKyYgF4t5cdg8qqyWpO64HMOroZevZThsbXTlnZmdDwAOnRmARKQtJOAL4MPDoCCMI6nSbABpNJCtC6ddA9PoJEbjY6Qs4zKBzBZtXQMAAGzgAbngYITHicQAAFGDMJowMwMADkb0EUBwLIYFGYeBiIygwI8uiF2jMTVZpPJLPeVNqzwgrw+Xx+EE+eA5OD+jwB5D1ZHIimodEY6lYmm0OWMZksMDcnlavn4QlEgX2QzCDAisiW8TSShUZo0UC0rGi9hWrh9FB8fH87ruXpjS0TwTSG2y+ht+XtpREol0kY9rlKh0e9UazSd7URyLisQGUfu6OpwGxuMWBLTqwx60yJQYO1uB0q8pqIARVxuPd9aPHTDYSren2+v3+tSBILBY77p0rsJasYYU6R1xRDHne7bHfmXZixLwZIpC9p9MZzLZmoEnO5vP5l7MEKeAihw4qmJKLLSjAsoLoqyqrmqGpajqe4GgCQA)

**Comment by G-Rath** [comment]
[This is my reproduction repo](https://github.com/G-Rath/js-bugs/tree/ts-tree).

> src/index.ts:48:7 - error TS2367: This condition will always return 'false' since the types 'AST_NODE_TYPES.Literal' and 'AST_NODE_TYPES.TemplateLiteral' have no overlap.

48   if (argument.type === AST_NODE_TYPES.TemplateLiteral) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I came across this when upgrading @typescript-eslint/typescript-estree from 2.12.0 to 2.13.0 as part of [package update on `eslint-plugin-jest`](https://github.com/jest-community/eslint-plugin-jest/pull/490).

The change that caused this issue is that `StringLiteral` defines `value` as type `string`, where as in the past it was type `boolean | number | RegExp | string | null` (which is what it is defined as on its super class `LiteralBase`, which hasn't changed).

If I comment out the `value: string` on `StringLiteral`, it all just works.

I'm guessing the issue is that this becomes a branded type due to the generic :/

**Comment by schani** [comment]
I ran into this in real-world code.  This is an abbreviated reproduction of my case:

```
// This is necessary for the issue to occur
interface PrimitiveType {
    kind: "string"
}

interface ArrayColumnType {
    kind: "array";
    items: PrimitiveType | TableRefType;
}

// MultiRelationType is a specialized version of ArrayColumnType
interface MultiRelationType {
    kind: "array";
    items: TableRefType;
}

interface TableRefType {
    kind: "table-ref";
    tableName: string;
}

type ColumnType = PrimitiveType | ArrayColumnType | TableRefType;

export function isRelationType(t: ColumnType): t is (TableRefType | MultiRelationType) {
    return t.kind === "table-ref" || (t.kind === "array" && t.items.kind === "table-ref");
}

function makeColumnType(): ColumnType {
    return { kind: "array", items: { kind: "table-ref", tableName: "foo"}};
}

const foo = makeColumnType();
// Here foo can be one of PrimitiveType | ArrayColumnType | TableRefType.
if (isRelationType(foo)) {
    // Now we know foo is one of TableRefType | MultiRelationType.
    // But TS seems to think that foo is definitely a TableRefType:
    console.log(foo.tableName); // no error
}
```

**Comment by octogonz** [comment]
We encountered a vaguely similar problem in #41871.  The commonalities seem to be:
- using a **type guard** to narrow a type (the problem disappears if the type guard is inlined)
- the type guard returns a **type union**

The repro works with older compiler versions.

**Comment by octogonz** [comment]
We encountered a vaguely similar problem in #41871.  The commonalities seem to be:
- using a **type guard** (in our case, the problem disappears if the type guard is inlined)
- the type guard **checks for a type union**
- the type guard **receives another type union** as its input, and the narrowed type is (incorrectly) too narrow

Our repro works all the way back to TypeScript 2.0.10, so this problem apparently has been around for a while.

**Comment by DetachHead** [comment]
minimal example
```ts
declare function assert<T>(value: any): asserts value is T

declare const foo: number | string | boolean

assert<1 | string>(foo)

const bar = foo //string
```

**Comment by jtbandes** [comment]
I also ran into this problem:

```ts
function isEmptyOrUndefined(str: string | undefined): str is undefined | "" {
    return str == undefined || str === "";
}

function test(s: string | undefined) {
    if (isEmptyOrUndefined(s)) {
        let len = s?.length;  // error
    }
}
```

I'm going to work around it for now by returning `string | undefined` rather than trying to use it as a type guard.
