### ISSUE TITLE
3.5.1 doesn't compile TensorFlow

### ISSUE THREAD

**Issue by rix0rrr** [microsoft/TypeScript#31717]
I'm having a hard time figuring out whose fault this is, but 3.4 will compile a complex generic definition in the TensorFlow source, and 3.5 will reject it.

This is a semi-minimal snippet that reproduces the situation, works fine in 3.4 but not in 3.5:

```ts
type DataType = 'float32' | 'string' | 'int32';
type NumericDataType = 'float32' | 'int32';

export interface DataTypeMap {
    float32: Float32Array;
    int32: Int32Array;
    bool: Uint8Array;
    complex64: Float32Array;
    string: string[];
}

interface Tensor<D extends DataType = 'float32'> {
    dtype: DataType;
    data<D extends DataType = NumericDataType>(): Promise<DataTypeMap[D]>;
}

export interface StringTensor extends Tensor {
    dtype: 'string';
    dataSync(): string[];
    data(): Promise<string[]>;
}
```

Error:

```
test.ts:24:18 - error TS2430: Interface 'StringTensor' incorrectly extends interface 'Tensor<"float32">'.
  Types of property 'data' are incompatible.
    Type '() => Promise<string[]>' is not assignable to type '<D extends DataType = NumericDataType>() => Promise<DataTypeMap[D]>'.
      Type 'Promise<string[]>' is not assignable to type 'Promise<DataTypeMap[D]>'.
        Type 'string[]' is not assignable to type 'DataTypeMap[D]'.
          Type 'string[]' is not assignable to type 'string[] & Float32Array & Int32Array'.
            Type 'string[]' is missing the following properties from type 'Float32Array': BYTES_PER_ELEMENT, buffer, byteLength, byteOffset, and 6 more.

24 export interface StringTensor extends Tensor {
                    ~~~~~~~~~~~~


Found 1 error.
```

Looks like the type argument `D` used to be inferred to be `string` in 3.4, but is no longer inferred anymore in 3.5?

**Related Issues:** 

Also filed this to TensorflowJS: https://github.com/tensorflow/tfjs/issues/1645

**Comment by fatcerberus** [comment]
`DataTypeMap[D]` + `string[] & Float32Array & Int32Array` = #30769.

**Comment by lindner** [comment]
Would it be possible to use [typesVersions](https://devblogs.microsoft.com/typescript/announcing-typescript-3-1/#version-redirects-for-TypeScript-via-typesVersions) config to support varying versions of TypeScript?

**Comment by weswigham** [comment]
You can also change `StringTensor`'s `data` method to better match the base tensor method, eg:
```ts
export interface StringTensor extends Tensor {
    dtype: 'string';
    dataSync(): string[];
    data<D extends DataType = "string">(): Promise<DataTypeMap[D]>;
}
```
or alternatively, you can change the base `Tensor` to be more permissive:
```ts
interface Tensor<D extends DataType = 'float32'> {
    dtype: DataType;
    data(): Promise<DataTypeMap[keyof DataTypeMap]>;
}
```

**Comment by weswigham** [comment]
Although i think the method type parameter (which is only witnessed in the return) in `Tensor` is probably a mistake, and the two should probably simply be
```ts
interface Tensor<D extends DataType = 'float32'> {
    dtype: DataType;
    data(): Promise<DataTypeMap[D]>;
}

export interface StringTensor extends Tensor<"string"> {
    dtype: 'string';
    dataSync(): string[];
    data(): Promise<string[]>;
}
```
