### ISSUE TITLE
Regression - default initializer of `{}` ruins type intersected with `object`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#49480]
```ts repro
export interface BarProps {
    barProp?: string;
}

export interface FooProps {
    fooProps?: BarProps & object;
}

declare const foo: FooProps;
const { fooProps = {} } = foo;

fooProps.barProp;
//       ~~~~~~~
// error! Property 'barProp' does not exist on type '{}'.
```

**Comment by DanielRosenwasser** [comment]
@typescript-bot bisect good v4.7.3 bad main

**Comment by DanielRosenwasser** [comment]
Forgot to add `strictNullChecks`, but it shouldn't matter.

**Comment by fatcerberus** [comment]
> The change between v4.7.3 and main occurred at https://github.com/microsoft/TypeScript/commit/5aa0053c74f0c67b2cbedf9cee6607ead3b9dc45.

That’s the second time it’s done that…

**Comment by weswigham** [comment]
methinks the twoslasher is broken with latest TS - the bug workbench does the same thing.

**Comment by DanielRosenwasser** [comment]
First repros on `typescript@4.8.0-dev.20220528`

Merge list is https://github.com/microsoft/TypeScript/pulls?q=is%3Apr+merged%3A2022-05-27+is%3Aclosed

Likely introduced by https://github.com/microsoft/TypeScript/pull/49119

**Comment by ahejlsberg** [comment]
Yup, this is caused by #49119. It modified `simpleTypeRelatedTo` to consider `{}` a supertype of `object` in the `strictSubtypeRelation`. But really that should only be true for a non-fresh `{}`. In other words, we want `{} <: object <: fresh {}` in the strict subtype relation.

Also, for some reason we remove object literal freshness from the source side when relating to an intersection on the target side. Lost in history as to why, removing it doesn't change any baselines.

In combination, those two changes fix the issue. I will put up a PR.

**Comment by DanielRosenwasser** [comment]
> In other words, we want `{} <: object <: fresh {}` in the strict subtype relation.

You mean the reverse, right?

`fresh {}` &leq; `object` &leq; `{}`

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Argh, yes. I always read `<:` as is-supertype-of because it looks like an inheritance tree on its side. But you're right, it should be the other way around. I'll correct it.

**Comment by fatcerberus** [comment]
> Mermaid diagrams

I've never heard this term before.

Also, on @ahejlsberg's note, I've personally always felt like the arrows in inheritance diagrams go in the wrong direction (`cause <- effect` is weird), so I find `fresh {} ≤ object ≤ {}` to actually be *easier* to read.

**Comment by RyanCavanaugh** [comment]
It's super weird because I want class arrows to go one way but subtyping arrows to go the other way. Human brains are a mess.
