### ISSUE TITLE
window.screen.orientation does not work in typescript (v2.3.3) used in angular 2/4

### ISSUE THREAD

**Issue by harishkumar329** [Microsoft/TypeScript#20489]
Getting following error when I try to lock the screen orientation,

Property 'lockOrientation' does not exist on type 'Screen'

**Type script Code (v2.3.3)**
var lockFunction = window.screen.lockOrientation || window.screen.mozLockOrientation || window.screen.msLockOrientation || window.screen.orientation;

The same works with the following **JQuery code**
var lockFunction = window.screen.orientation.lock;
if($.isFunction(lockFunction)){
lockFunction.call(window.screen.orientation, 'landscape');
}
It is a native web app, not trying with ionic or PhoneGap.

Thanks in advance.

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.
