### ISSUE TITLE
[3.7] Mixin is broken with TypeScript 3.7 beta and compilerOptions.declaration = true

### ISSUE THREAD

**Issue by raymondfeng** [microsoft/TypeScript#33739]
**TypeScript Version:**  3.7-beta

**Search Terms:**

Mixin declaration

**Code**

The issue can be reproduced with the following files:

1. timestamp.ts
```ts
export type Constructor<T = {}> = new (...args: any[]) => T;

export function Timestamped<TBase extends Constructor>(Base: TBase) {
  return class extends Base {
    timestamp = Date.now();
  };
}
```
2. user.ts

```ts
import { Timestamped } from './timestamp';

// Simple class
export class User {
  name = '';
}

// User that is Timestamped
export class TimestampedUser extends Timestamped(User) {
  constructor() {
    super();
  }
}
```

3. tsconfig.json

```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "skipLibCheck": true,
    "strict": true,

    "incremental": false,

    "lib": ["es2018"],
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es2017",
    "sourceMap": true,

    // declaration true fails the compilation
    "declaration": true,

    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
```

**Expected behavior:**

tsc -p tsconfig.json should be successful as TS 3.6.x does.

**Actual behavior:**

```
src/user.ts:9:38 - error TS4020: 'extends' clause of exported class 'TimestampedUser' has or is using private name '(Anonymous class)'.

9 export class TimestampedUser extends Timestamped(User) {
                                       ~~~~~~~~~~~~~~~~~


Found 1 error.

```
**Playground Link:** 

**Related Issues:**

**Comment by MLoughry** [comment]
I'm encountering a similar error with a slightly different repro:

```ts
// wrapClass.ts
export function wrapClass(param: any) {
    return class Wrapped {
        foo() {
            return param;
        }
    }
}

// index.ts
import { wrapClass } from "./wrapClass";

export default wrapClass(0);
```

```
 error TS4082: Default export of the module has or is using private name 'Wrapped'.

3 export default wrapClass(0);
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This started reproing in 3.7.0-dev.20190927 (and works on 3.7.0-dev.20190926)

**Comment by raymondfeng** [comment]
@MLoughry Yeah, it's the same problem.

**Comment by raymondfeng** [comment]
@DanielRosenwasser any advice?

**Comment by raymondfeng** [comment]
@weswigham 👍
