### ISSUE TITLE
Dynamic TagName causing error after version upgrade

### ISSUE THREAD

**Issue by moog16** [microsoft/TypeScript#28892]
typescript version: 3.2.2
IDE: VS Code

Description:
I updated from v3.1.6 to v3.2.2. This is my code:

```
import * as React from 'react';

export interface Props {
  tag?: string,
};

const MyComponent: React.FunctionComponent<Props> = ({
  tag: Tag = 'div', children
}) => {
  return (
    <Tag> // this is causing the error
      {children}
    </Tag>
  );
};

```

Expected:
No error

Actual:
Error produced:
`[ts] Type '{ children: ReactNode; }' has no properties in common with type 'IntrinsicAttributes'. [2559]`

This seems like a regression as it worked in v3.1.6

**Comment by blake-newman** [comment]
properties in common with type 'IntrinsicAttributes'

**Comment by larrybotha** [comment]
typescript version: 3.2.2
IDE: Vim

Also experiencing this, but with `className` producing the error. I've resorted to using `React.createElement` as a workaround:

```javascript
    return React.createElement(tagName, {
      children,
	  className,
      ...restProps,
    });
```

**Comment by rmehlinger** [comment]
I'm also seeing this error.

**Comment by just-boris** [comment]
I have a similar problem. The most minimal code, that does not use React typings

```tsx
declare namespace React {
    function createElement(name: string, props: Record<string, any>): void
}

function render(TagName: string) {
    return <TagName className="bla" />;
}
```

Produces the error:

```
index.tsx:6:13 - error TS2322: Type '{ className: string; }' is not assignable to type '{}'.
  Property 'className' does not exist on type '{}'.

6     return <TagName className="bla" />;
              ~~~~~~~
```

<details>
<summary>tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "target": "es5",            
    "module": "commonjs",         
    "jsx": "react"
  }
}

```

(default, generated by `tsc --init`, just also provided `jsx` option)
</details>

<br>
Worked this around by using `React.createElement` directly, without JSX:

```js
return React.createElement(TagName, {className: 'bla'});
```

**Comment by moog16** [comment]
@just-boris - ideally we don't need to do that. My work around has just been adding this comment above my `<Tag...`: `// @ts-ignore  https://github.com/Microsoft/TypeScript/issues/28892`.

Arguably this is just as bad, since we turn off type checking.

**Comment by weswigham** [comment]
For anyone reading this: This error is pretty much correct and is because making a tag out of an arbitrary string isn't typesafe (rather: the element can be created but will potentially throw with `Target container is not a DOM element.` when rendered by `react-dom`). The `NeedsInvestigation` tag is, IIRC, just to find why it worked before we refactored how we handled JSX (it shouldn't have from what I know...). In your code, if you want to say that you have a valid html tag name, you should use `keyof React.ReactDOM` instead of `string` (which, FYI contains both the HTML and SVG elements - if you only intend for one or the other, you should select either `ReactSVG` or `ReactHTML` instead). `JSX.IntrinsicElements` contains no definition for the props for something of type `string` (that would require an index signature, which `react` does not define). This makes perfect sense - `react` has no idea how to make a `"foobar"` tag correctly. Within `react`'s types, `ReactType` is defined in a similar fashion (in terms of `JSX.IntrinsicElements`).

If anything, I'd say that the preferred workaround for anyone who finds this, rather than suppressing the error, is trying to rejigger their `string` type into the `keyof React.ReactDOM` (or `keyof JSX.IntrinsicElements`) union instead.

**Comment by moog16** [comment]
Thanks @weswigham I'll give that a go!

**Comment by mmtjhlee** [comment]
Since I updated typescript 2.9.x to 3.3.4000 I have been getting this errors too.

I was using keyof JSX.IntrinsicElements as a workaround and it worked twice, but once I added it to the third one it somehow caused my whole build process to stuck in an infinite loop. I tried to dig into the issue a bit using `node --inspect tsc` but only saw something stuck trying to union `undefined` with something else.

**Comment by rmehlinger** [comment]
Unfortunately I've found that even using `keyof React.ReactHTML` is not working:
```

interface CollapseHeaderProps {
  collapsed: boolean;
  HeaderTag: keyof React.ReactHTML;
  title: string | JSX.Element | React.ReactNode;
  toggle: () => void;
}

const CollapseHeader: React.SFC<CollapseHeaderProps> = props => {
  const {title, collapsed, toggle, HeaderTag} = props;
  return (
    <div onClick={toggle}>
      <HeaderTag>
        <Icon icon={collapsed ? 'plus' : 'minus'} />
        {title}
      </HeaderTag>
    </div>
  );
};

```

I still get 
```
error TS2604: JSX element type 'HeaderTag' does not have any construct or call signatures.
```

This is on TypeScript 3.2.4.

**Comment by pawelkleczek10c** [comment]
import { DetailedHTMLFactory, HTMLAttributes } from 'react';

export type DynamicTagNameType = DetailedHTMLFactory<HTMLAttributes<HTMLDivElement>, HTMLDivElement>;

**Comment by ceefour** [comment]
@moog16 THANK YOU! `// @ts-ignore` saves me :)

**Comment by lemoustachiste** [comment]
I was using `React.FunctionComponent` but that was giving an error. Other ones don't work because I am setting the component so sadly I am now using `any`, which I still think better than `@ts-ignore`.

**Comment by zposten** [comment]
This seems to work:

```tsx
export function DynamicTag(props: DynamicTagProps) {
  let {tag: Tag, ...rest} = props

  return <Tag {...rest} />
}

export type DynamicTagProps = React.HTMLAttributes<HTMLOrSVGElement> & {
  children: string
  tag?: keyof JSX.IntrinsicElements
}

DynamicTag.defaultProps = {tag: 'div'}
```

This is the calculated type of `tag`: 

![image](https://user-images.githubusercontent.com/13950246/69652914-fe111700-1037-11ea-8f2c-548807fbdb63.png)

**Comment by AryanJ-NYC** [comment]
```typescript
export const CallToAction: React.FC<Props> = ({ tag: Tag = 'button', children, ...props }) => (
  <Tag . {...props}>
    {children}
  </Tag>
);
type Props = {
  tag?: keyof JSX.IntrinsicElements;
} & React.HTMLAttributes<HTMLOrSVGElement>;
```

works for me.

**Comment by deadcoder0904** [comment]
I have the same issue & nothing here works for me. I have exactly the same case to make dynamic tag with default value as a string & I have to use `ref` as well as `className`. It just doesn't work.

Would love any help 🙏

**Comment by deadcoder0904** [comment]
I solved it by using `React.createElement` like:

```ts
const Example = () => {
   return React.createElement(
        Wrapper,
        {
          ref: myRef,
          className: myClassnames
        }
      )
}
```

**Comment by jaywcjlove** [comment]
```tsx
type DemoProps<T> = {
  tagName?: T extends string ? keyof JSX.IntrinsicElements : T;
}

export default function Demo<T>(props: DemoProps<T> = {}) {
  const { tagName: TagName = 'a' as any, ...other } = props;
  return <TagName {...other}></TagName>;
}
```

Use  `Demo` component.

```tsx
function Link() {
  return (
    <a href="https://github.com">www</a>
  );
}


function Example() => {
  
  return (
    <>
      <Demo tagName={Link}></Demo>
      <Demo tagName="a"></Demo>
    <>
  );
}
```

It's not perfect.....

**Comment by skpandey1294** [comment]
It will work

```import React, { FC } from 'react';

interfaceDynamicTagProps {
  text: string;
  tag?: keyof JSX.IntrinsicElements | string;
}

export const DynamicTag: FC<DynamicTagProps> = ({
  text,
  tag = 'span'
}) => {
  const ElementTag = tag as keyof JSX.IntrinsicElements;
  return (
    <ElementTag className={styles.HelpText} >
      {text}
    </ElementTag>
  );
}; ```

**Comment by RyanCavanaugh** [comment]
This is the intended JSX checking behavior, not a regression to restore. A value typed as `string` can name any custom element, so TypeScript has no prop type for `<Tag>` and cannot safely accept `children`, `className`, or other attributes.

With the dependency-free example from the discussion and `--jsx react`, TypeScript 3.1.6 accepts `<TagName className="bla" />`; TypeScript 3.2.2 reports TS2322 because `className` is not assignable to the empty prop type. TypeScript 3.1.x silently skipped that check for a broad string tag.

If the tag is restricted to known intrinsic elements, use `keyof JSX.IntrinsicElements` (or the corresponding React intrinsic-element key type) and supply only props valid for the possible elements. For a component value, use an appropriately parameterized component/element type rather than `string`.
