### ISSUE TITLE
typesctip 6 and package.json exports definitions

### ISSUE THREAD

**Issue by darkship** [microsoft/TypeScript#63318]
### 🔎 Search Terms

typescript 6, package.json exports

### 🕗 Version & Regression Information

- This changed between versions 5.9.3 and 6.0.2

### ⏯ Playground Link

https://github.com/darkship/ts6-bug

### 💻 Code

```ts
import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader"
```

### 🙁 Actual behavior

```
$ tsc --noEmit
src/index.ts:1:28 - error TS2307: Cannot find module 'three/examples/jsm/loaders/GLTFLoader' or its corresponding type declarations.

1 import type {  GLTF } from "three/addons/loaders/GLTFLoader"
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:3:40 - error TS7006: Parameter 'c' implicitly has an 'any' type.

3 const a = (b: GLTF)=> b.scene.traverse(c=>{
                                         ~


Found 2 errors in the same file, starting at: src/index.ts:1
```

### 🙂 Expected behavior

no error

### Additional information about the issue

Export in  three:0.153.0 and in @types/three:0.153.0 are defined as
```
    "exports": {
        //...
        "./addons/*": "./examples/jsm/*",
        //...
    }
```
which should allow to import anything from `./examples/jsm/`

**Comment by matheusschreiber** [comment]
Add `.js` in the module import.

```diff
- import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader"
+ import type { GLTF } from "three/examples/jsm/loaders/GLTFLoader.js"
```

**Comment by RyanCavanaugh** [comment]
This is not a 6.0 regression and is the behavior at least as far back as 5.5

**Comment by darkship** [comment]
I also noticed that my real project was still with `"module": "ESNext",` (not nodenext like in my code example) under TS 5.9.3 which is working but failed after upgrading to 6.0.2.

@matheusschreiber thanks, it helped.
