### ISSUE TITLE
Calling a public static method on an instance of a class causes error error TS2339: Property  does not exist on type, but error message is missleading

### ISSUE THREAD

**Issue by sunmountain** [Microsoft/TypeScript#25840]
**TypeScript Version:**  2.9.2 (does not work with 3.1.0-dev.20180717 also)

**Search Terms:** public static call instance T2339

**Code**
```ts
class Greeter {
    private times: number;
    private message: string;

    public static hello(what: string): void {
        console.log(what);
    }

    constructor(times: number, message: string) {
        this.times = times;
        this.message = message;
    }

    public doIT(): void {
        for (var i: number = 0;i<this.times; i++) {
            console.log(this.message,this.anotherMember());
        }
    }

    private anotherMember(): number {
        return Math.PI;
    }

}

var g: Greeter = new Greeter(3,'Hallo Welt!');

g.doIT();
g.doIT();
g.hello('sdws');
Greeter.hello('blah');
```

Expected behavior: provide a more meaningfull error message, such as "Property 'hello' is declared static and can not be called from an instance"

Actual behavior: doesn't compile, sample.ts:30:3 - error TS2339: Property 'hello' does not exist on type 'Greeter'.

**Playground Link:** http://www.typescriptlang.org/play/#src=class%20Greeter%20%7B%0D%0A%20%20%20%20private%20times%3A%20number%3B%0D%0A%20%20%20%20private%20message%3A%20string%3B%0D%0A%0D%0A%20%20%20%20public%20static%20hello(what%3A%20string)%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(what)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20constructor(times%3A%20number%2C%20message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.times%20%3D%20times%3B%0D%0A%20%20%20%20%20%20%20%20this.message%20%3D%20message%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20doIT()%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20for%20(var%20i%3A%20number%20%3D%200%3Bi%3Cthis.times%3B%20i%2B%2B)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(this.message%2Cthis.anotherMember())%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20anotherMember()%3A%20number%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20Math.PI%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%7D%0D%0A%0D%0Avar%20g%3A%20Greeter%20%3D%20new%20Greeter(3%2C'Hallo%20Welt!')%3B%0D%0A%0D%0Ag.doIT()%3B%0D%0Ag.doIT()%3B%0D%0Ag.hello('sdws')%3B%20%2F%2F%20this%20should%20work%0D%0AGreeter.hello('blah')%3B

**Related Issues:** no

**Comment by a-tarasyuk** [comment]
@mhegazy @ andy-ms seems issue related to method `reportNonexistentProperty`_(checker.ts),_ which does not handle differences between `instance` and `static` properties/methods. Is there any existing helper/util to check such cases?

**Comment by mhegazy** [comment]
do not think so. @sandersn any recommendations?

**Comment by sandersn** [comment]
I can't think of an existing utility, but I think you'd just have to add a check in `reportNonExistentProperty` for something like `getPropertyOfType(getDeclaredTypeOfSymbol(containingType.symbol), propNode.escapedText)`. If you get a property from that call, then you know that the static side has a property of desired name and can issue the improved error message.

(This is completely untested, so I may be way off base, but it's probably a good place to start.)
