### ISSUE TITLE
 error TS2502: 'thisArg' is referenced directly or indirectly in its own type annotation with tsc 4.6.4

### ISSUE THREAD

**Issue by simllll** [microsoft/TypeScript#48914]
# Bug Report

### 🔎 Search Terms

ts2502, lib.es.5

### 🕗 Version & Regression Information

works with tsc 4.6.3, but not anymore the latest one (4.6.4).

Nightly version works!

- This changed between versions 4.6.3 and 4.6.4

### 🙁 Actual behavior

running tsc results into:
```
node_modules/typescript/lib/lib.es5.d.ts:352:22 - error TS2502: 'thisArg' is referenced directly or indirectly in its own type annotation.

352     bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/typescript/lib/lib.es5.d.ts:352
```

tsconfig.json:
```
{
	"compilerOptions": {
		"outDir": "./dist",
		"rootDir": "./src",

		// target settings for node js
		"module": "ES2020",
		"target": "ES2021",
		"lib": ["ES2021"],

		// for CommonJS module imports
		"allowSyntheticDefaultImports": true,

		// other best practice configs
		"moduleResolution": "node",
		"strict": true,
		"noImplicitAny": false, // <-- get rid of this!
		"emitDecoratorMetadata": true,
		"composite": true,
		"experimentalDecorators": true,
		"strictPropertyInitialization": false,
		"resolveJsonModule": true,
		"sourceMap": true,
		"isolatedModules": false,
		"declaration": true
	},
	"exclude": ["node_modules", "**/__tests__"],
	"include": ["./src"]
}

```
### 🙂 Expected behavior

should work, it actually does (already again?) in the nightly, but I couldn't find any issue and therefore wanted to create one in case other people are stumpling on this too. Please feel free to close it, if this is already known or fixed by intention ;-).

**Comment by andrewbranch** [comment]
I can’t reproduce this in 4.6.4. I’m not too worried about it since you say it’s fixed in nightly, but I am curious. If you can provide a full repro I’ll take a look.

**Comment by simllll** [comment]
Hi @andrewbranch , simplest method is to check out https://github.com/simllll/node-radius-server and install tsc 4.6.4, run tsc (or npm run build) and you get the error message. I can try to narrow it down if this scenario is not helpful for you, but I think it's not related to the source files at all, so assuming this could be enough for reproduction?

**Comment by andrewbranch** [comment]
Wow, that is very strange. It only reproduces with `composite` enabled (so a tsbuildinfo file is produced). There have been some significant changes to that mode this cycle so I assume what you were seeing was a symptom of a problem that we knew about and fixed, or we fixed it accidentally. I wish I knew exactly what caused it / fixed it but it’s probably not worth the investigation into a fixed bug. Thanks for the report!

**Comment by babakfp** [comment]
@simllll 
@andrewbranch 

Hi 👋

Is this related?

https://github.com/fabian-hiller/valibot/discussions/476
