### ISSUE TITLE
Bug report about keyof with class implements.

### ISSUE THREAD

**Issue by acrazing** [Microsoft/TypeScript#17822]
**TypeScript Version:**  2.4.2

**Code**

```ts
/*!
 *
 * Copyright 2017 - acrazing
 *
 * @author acrazing joking.young@gmail.com
 * @since 2017-08-16 15:56:19
 * @version 1.0.0
 * @desc index.ts
 */

export interface IOptions {
  name: string;
}

export function config<T extends IOptions, K extends keyof T>(key: K, value: T[K]): void {
  console.log(key, value)
}

export interface IClass {
  config<T extends IOptions, K extends keyof T>(key: K, value: T[K]): void;
}

export class Class implements IClass {
  config<T extends IOptions, K extends keyof T>(key: K, value: T[K]): void {
    console.log(key, value)
  }
}
```

**Expected behavior:**

No Error

**Actual behavior:**

```
index.ts(23,14): error TS2420: Class 'Class' incorrectly implements interface 'IClass'.
  Types of property 'config' are incompatible.
    Type '<T extends IOptions, K extends keyof T>(key: K, value: T[K]) => void' is not assignable to type '<T extends IOptions, K extends keyof T>(key: K, value: T[K]) => void'. Two different types with this name exist, but they are unrelated.
      Types of parameters 'key' and 'key' are incompatible.
        Type 'K' is not assignable to type '"name"'.
          Type 'keyof T' is not assignable to type '"name"'.
```

**Comment by aluanhaddad** [comment]
This seems to work in 2.3.3 and error in nightly.

**Comment by ahejlsberg** [comment]
This is working as intended and is an effect of #16368. When relating the `config` methods in the example it isn't possible for the checker to conclude that the `T` type parameters are related because no parameters use `T` in a manner from which inferences can be made. This also means that in calls to `config` it isn't possible to infer type arguments for `T`, so such calls will always just default to the `IOptions` bound unless type arguments are explicitly specified--which in turn means the `T` type argument is pretty much pointless.

I suggest changing the declarations to:

```ts
export function config<K extends keyof IOptions>(key: K, value: IOptions[K]): void {
  console.log(key, value)
}

export interface IClass {
  config<K extends keyof IOptions>(key: K, value: IOptions[K]): void;
}

export class Class implements IClass {
  config<K extends keyof IOptions>(key: K, value: IOptions[K]): void {
    console.log(key, value)
  }
}
```

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
