### ISSUE TITLE
styled-components broken by #41841

### ISSUE THREAD

**Issue by sandersn** [microsoft/TypeScript#41886]
Found by overnight DT run for #41841 

Here's a standalone repro; it's not minimal but it doesn't depend on anything else.

```ts
interface FunctionComponent<P = {}> {
    defaultProps?: Partial<P>;
}
type ComponentType<P = {}> = FunctionComponent<P>;
export type KProps<C extends string | ComponentType<any>> =
    object extends object ? Omit<C, any> & Partial<C> : never;
export interface StyledK<C extends string | ComponentType<any>> {
    (props: KProps<C>): never
}
type Constraint<T extends ComponentType> = T ;
export type StyledComponentInnerComponent<C> = C extends StyledK<infer I> ? I : C;
export type SProblem<C extends ComponentType<any>> = C extends StyledK<any> ? Constraint<StyledComponentInnerComponent<C>> : number;
```

**Expected behavior:**
No error, as in 4.1.

**Actual behavior:**
Error in `SProblem` on `Constraint<StyledComponentInnerComponent<C>>`: 

```
error TS2344: Type 'StyledComponentInnerComponent<C>' does not satisfy the constraint 'ComponentType<{}>'.
  Type 'string | ComponentType<any> | C' is not assignable to type 'FunctionComponent<{}>'.
    Type 'string' has no properties in common with type 'FunctionComponent<{}>'.
      Type 'string | ComponentType<any>' is not assignable to type 'FunctionComponent<{}>'.
        Type 'string' has no properties in common with type 'FunctionComponent<{}>'.
```

**Comment by sandersn** [comment]
Here's a smaller repo. I think it better illustrates the problem:

```ts
interface StyledK<C extends string> {
    (props: {}): never
}
type Constraint<T extends { p }> = T ;
type Inner<C> = C extends StyledK<infer I> ? I : C;
export type SProblem<C extends { p }> = C extends StyledK<any> ? Constraint<Inner<C>> : number;
```

I guess before the `string` constraint on `C` from the outer `C extends StyledK<any> ? ...` got dropped? It kind of looks like this new error is correct.

**Comment by ahejlsberg** [comment]
> I guess before the string constraint on C from the outer C extends StyledK<any> ? ... got dropped? It kind of looks like this new error is correct.

Yes, that was the problem with not preserving substitution types in conditional types--constraints implied by outer conditional types were dropped. They're now preserved, which in this case reveals an error. If `C` is a `StyledK<any>` then `Inner<C>` is constrained to `string | C`, and `string` is not assignable to `{ p: any }`.

BTW, I have no earthly idea what these types are supposed to be doing!

**Comment by sandersn** [comment]
Presumably they made sense in situ. The standalone repro chops them up pretty badly. I'll go back to the original and try to figure out a workaround.

(There are nearby comments in the original along the lines of "I'm quitting now before my head starts hurting again." So.)

**Comment by sandersn** [comment]
Later: It seems like the `string` constraint was a low-fi `keyof JSX.IntrinsicElements` substitute, because switching to that now compiles successfully. I'm afraid that it's going to be a *lot* slower though.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50046
