### PR TITLE
Update baselines missed in PR

### PR DESCRIPTION
**Pull request by jakebailey**
#51580 had not been updated in a while and has some baseline changes.

I am not sure the behavior of `intraExpressionInferencesJsx` is desirable here. @Andarist

### CODE REVIEW

**Comment by weswigham** [comment]
It's definitely not desirable - I've been looking at it and it seems like #51580 and #52837 conflict semantically, to the tune of partially re-breaking what #52837 fixed. (Also the `null` thing, but that's just a change we made recently.)

In the meantime, we can revert #51580 to put `main` right again, imo.

**Comment by weswigham** [comment]
(Specifically, by no longer passing in the `checkMode`, we're missing the intra-expression sites in the nested expression. We should *probably* be specifying the checkMode, but be skipping the error reporting when checkMode isn't `Normal`, and I did a quick test of that - diff is [here](https://github.com/microsoft/TypeScript/compare/main...weswigham:TypeScript:fix-baselines?expand=1), but I haven't had time to check if all those baseline changes are OK)

**Comment by jakebailey** [comment]
Sent #53283.

File: tests/baselines/reference/intraExpressionInferencesJsx.errors.txt [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+      a={(x) => 10}
+      b={(arg) => { arg.toString(); }}
+    />;
+    
+    <Foo {...{
+      a: (x) => 10,
+      b: (arg) => { arg.toString(); },
+                    ~~~
+!!! error TS18046: 'arg' is of type 'unknown'.
+    }} />;
```
Comment (Andarist) [inline tests/baselines/reference/intraExpressionInferencesJsx.errors.txt:114]: From what I see this is the only "unwanted" change that has been found on `main`. However... this is exactly how regular call expressions work: [TS playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgApQPYAcDOAeAFQD5kBvAKGWTgC5kAKADzpzClAHMBKZAXhIIBuSsgBGdenCgc6BHv2QA3DMAAmwgL7lyMAK4gEYYBhDIAYhgyEi9LJlx102fMR4UqUCGF1RTeVcCKyAD0RJraeBYYIqQAdPHuVNQSjPIkAIwADAA0IlTiDFLcfCSJSdTSsWAYAMpsnPRcwuUauVQaWqHC5FH0ifGxZckMqSXIWW1JBZLSaWR5SUVVtfUgHI3NSa0i2xpN5EA). So perhaps... this was just working accidentally before. I feel like this should be a separate issue to make it work for both JSX and regular calls (if that's desired)

**Comment by Andarist** [comment]
> We should probably be specifying the checkMode, but be skipping the error reporting when checkMode isn't Normal, and I did a quick test of that - diff is [here](https://github.com/microsoft/TypeScript/compare/main...weswigham:TypeScript:fix-baselines?expand=1) - but I haven't had time to check if all those baseline changes are OK; they may just be highlighting even more scenarios where CheckMode isn't being propagated where it should be, ungh)

I took a look at those changes and I think that some of them are not desired.
