### PR TITLE
25840 - Add a more meaningful error message to the case when calling a public static method on an instance

### LINKED ISSUE #25840: Calling a public static method on an instance of a class causes error error TS2339: Property  does not exist on type, but error message is missleading
**TypeScript Version:**  2.9.2 (does not work with 3.1.0-dev.20180717 also)

**Search Terms:** public static call instance T2339

**Code**
```ts
class Greeter {
    private times: number;
    private message: string;

    public static hello(what: string): void {
        console.log(what);
    }

    constructor(times: number, message: string) {
        this.times = times;
        this.message = message;
    }

    public doIT(): void {
        for (var i: number = 0;i<this.times; i++) {
            console.log(this.message,this.anotherMember());
        }
    }

    private anotherMember(): number {
        return Math.PI;
    }

}

var g: Greeter = new Greeter(3,'Hallo Welt!');

g.doIT();
g.doIT();
g.hello('sdws');
Greeter.hello('blah');
```

Expected behavior: provide a more meaningfull error message, such as "Property 'hello' is declared static and can not be called from an instance"

Actual behavior: doesn't compile, sample.ts:30:3 - error TS2339: Property 'hello' does not exist on type 'Greeter'.

**Playground Link:** http://www.typescriptlang.org/play/#src=class%20Greeter%20%7B%0D%0A%20%20%20%20private%20times%3A%20number%3B%0D%0A%20%20%20%20private%20message%3A%20string%3B%0D%0A%0D%0A%20%20%20%20public%20static%20hello(what%3A%20string)%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(what)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20constructor(times%3A%20number%2C%20message%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.times%20%3D%20times%3B%0D%0A%20%20%20%20%20%20%20%20this.message%20%3D%20message%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20doIT()%3A%20void%20%7B%0D%0A%20%20%20%20%20%20%20%20for%20(var%20i%3A%20number%20%3D%200%3Bi%3Cthis.times%3B%20i%2B%2B)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20console.log(this.message%2Cthis.anotherMember())%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20anotherMember()%3A%20number%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20Math.PI%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%7D%0D%0A%0D%0Avar%20g%3A%20Greeter%20%3D%20new%20Greeter(3%2C'Hallo%20Welt!')%3B%0D%0A%0D%0Ag.doIT()%3B%0D%0Ag.doIT()%3B%0D%0Ag.hello('sdws')%3B%20%2F%2F%20this%20should%20work%0D%0AGreeter.hello('blah')%3B

**Related Issues:** no

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #25840

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -3315,6 +3315,7 @@ namespace ts {
                     function shouldWriteTypeOfFunctionSymbol() {
                         const isStaticMethodSymbol = !!(symbol.flags & SymbolFlags.Method) &&  // typeof static method
                             some(symbol.declarations, declaration => hasModifier(declaration, ModifierFlags.Static));
+
```
Comment (sandersn) [inline src/compiler/checker.ts]: please remove extra lines

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -17909,6 +17914,16 @@ namespace ts {
             diagnostics.add(resultDiagnostic);
         }
 
+        function isStaticPropertyExists(propNode: Identifier, containingType: Type): boolean {
+            if (!(getObjectFlags(containingType) & ObjectFlags.Class)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: do you need this check? I think hasModifier(Static) only returns true for properties that are declared on classes, and this is an error case, so the time needed for getTypeOfSymbol and hasModifier is not that much of a concern. In other words, I think you can just

```ts
return prop && prop.valueDeclaration && hasModifier(prop.valueDeclaration, ModifierFlags.Static)
```

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -17909,6 +17914,16 @@ namespace ts {
             diagnostics.add(resultDiagnostic);
         }
 
+        function isStaticPropertyExists(propNode: Identifier, containingType: Type): boolean {
```
Comment (sandersn) [inline src/compiler/checker.ts]: the is* pattern looks weird here. What about `typeHasStaticProperty`?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -17897,6 +17899,9 @@ namespace ts {
                     errorInfo = chainDiagnosticMessages(errorInfo, Diagnostics.Property_0_does_not_exist_on_type_1_Did_you_mean_2, declarationNameToString(propNode), typeToString(containingType), suggestedName);
                     relatedInfo = suggestion.valueDeclaration && createDiagnosticForNode(suggestion.valueDeclaration, Diagnostics._0_is_declared_here, suggestedName);
                 }
+                else if (isStaticPropertyExists(propNode, containingType)) {
+                    errorInfo = chainDiagnosticMessages(errorInfo, Diagnostics.Property_0_is_declared_static_and_can_not_be_called_from_an_instance, declarationNameToString(propNode));
+                }
```
Comment (sandersn) [inline src/compiler/checker.ts]: maybe this should work on element access too? I don't think it calls reportNonexistentProperty, but similar errors exist in getPropertyTypeForIndexType.

If you do have to copy the code into getPropertyTypeForIndexType, we should think about refactoring it later to call reportNonexistentProperty.

Either way, I'd like to see some tests of element access like `c["bar"]`.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -17897,6 +17899,9 @@ namespace ts {
                     errorInfo = chainDiagnosticMessages(errorInfo, Diagnostics.Property_0_does_not_exist_on_type_1_Did_you_mean_2, declarationNameToString(propNode), typeToString(containingType), suggestedName);
                     relatedInfo = suggestion.valueDeclaration && createDiagnosticForNode(suggestion.valueDeclaration, Diagnostics._0_is_declared_here, suggestedName);
                 }
+                else if (isStaticPropertyExists(propNode, containingType)) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: I think finding a static property is probably better than finding a possible typo, and about the same as finding it on the promised type. So probably this should go before the spelling suggestion check and possibly before the promised type check (if it's more convenient there).

File: tests/cases/fourslash/codeFixUndeclaredAcrossFiles1.ts [hunk 6]
```diff
@@ -28,7 +30,6 @@ verify.rangeIs(`
     m2(c: C): any {
         throw new Error("Method not implemented.");
     }
-    y: { [x: string]: any; };
```
Comment (sandersn) [inline tests/cases/fourslash/codeFixUndeclaredAcrossFiles1.ts]: why does this line disappear instead of changing to `z`?

File: tests/baselines/reference/classSideInheritance1.errors.txt [hunk 7]
```diff
@@ -16,9 +16,9 @@ tests/cases/compiler/classSideInheritance1.ts(13,3): error TS2339: Property 'bar
     var c: C2;
     a.bar(); // static off an instance - should be an error
       ~~~
-!!! error TS2339: Property 'bar' does not exist on type 'A'.
+!!! error TS2576: Property 'bar' is declared static and can not be called from an instance
```
Comment (sandersn) [inline tests/baselines/reference/classSideInheritance1.errors.txt]: I would leave off the elaboration (and 'declared') and instead mention the type name: "Property 'bar' is a static member of type 'A'."

File: src/compiler/checker.ts (hunk 2 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]:
```typescript
if (!(getObjectFlags(containingType) & ObjectFlags.Class)) {
```

This condition was added in order to check only class properties, and exclude cases like fn.length, fn.name etc. If there are better solutions to this, I would be appreciated if you could give me any ideas. Thanks in advance.

File: src/compiler/checker.ts (hunk 4 above)
Comment (a-tarasyuk) [reply src/compiler/checker.ts]: > maybe this should work on element access too?
Ok, I'll check, thanks

**Comment by mhegazy** [comment]
@sandersn can you take another look please.

File: src/compiler/checker.ts (hunk 2 above)
Comment (sandersn) [reply src/compiler/checker.ts]: I tried the above change myself and ended up with the following code:

```ts
function typeHasStaticProperty(propName: __String, containingType: Type) {
    const prop = containingType.symbol && getPropertyOfType(getTypeOfSymbol(containingType.symbol), propName);
    return prop && prop.valueDeclaration && hasModifier(prop.valueDeclaration, ModifierFlags.Static);
}
```

This actually catches 7 more tests that need to change, so I think it's an improvement.

**Comment by sandersn** [comment]
Thanks for the PR @a-tarasyuk! This is a nice contribution to our improved error messages effort.

**Comment by a-tarasyuk** [comment]
@sandersn Thank you very much for your help! 👍 :)
