### ISSUE TITLE
error TS2677: Type 'keyof E' is not assignable to type 'string'

### ISSUE THREAD

**Issue by AnyhowStep** [Microsoft/TypeScript#23724]
**TypeScript Version:**  Version 2.9.0-dev.20180426

**Search Terms:** keyof not assignable string

**Code**

```ts
//Just a minimal example, not what I am actually doing
function isKey<E> (str : string) : str is keyof E {
    return true;
}
```

**Expected behavior:**

Should compile fine. The body of the type guard may actually correctly assert that `str` is, indeed, `keyof E`

Works fine on TypeScript 2.8.3

**Actual behavior:**

```
error TS2677: A type predicate's type must be assignable to its parameter's type.
  Type 'keyof E' is not assignable to type 'string'.
    Type 'string | number | symbol' is not assignable to type 'string'.
      Type 'number' is not assignable to type 'string'
```

**Playground Link:** Works on the [playground](http://www.typescriptlang.org/play/#src=type%20SomeType%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5Bk%20in%20keyof%20T%5D%3A%20any%3B%0D%0A%7D%3B%0D%0A%0D%0Afunction%20deep%3CBase%2C%20Derived%20extends%20SomeType%3CBase%3E%3E()%20%7B%0D%0A%20%20%20%20const%20derived%3A%20Derived%20%3D%20null%20as%20any%3B%0D%0A%20%20%20%20const%20test%3A%20%7B%20test%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0A%20%20%20%20const%20both%3A%20Derived%20%26%20%7B%20test%20%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0A%0D%0A%20%20%20%20const%20works0%3A%20SomeType%3CBase%3E%20%3D%20derived%3B%0D%0A%20%20%20%20const%20works1%3A%20SomeType%3CDerived%3E%20%3D%20derived%3B%0D%0A%20%20%20%20const%20works2%3A%20SomeType%3C%7B%20test%3A%20string%20%7D%3E%20%3D%20test%3B%0D%0A%0D%0A%20%20%20%20%2F%2FThis%20fails%20unexpectedly%20%20%20%20%0D%0A%20%20%20%20const%20fails0%3A%20SomeType%3CBase%20%26%20%7B%20test%3A%20string%20%7D%3E%20%3D%20both%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20ConcreteBase%20%7B%0D%0A%20%20%20%20a%3A%20string%2C%0D%0A%20%20%20%20b%3A%20string%2C%0D%0A%7D%0D%0Ainterface%20ConcreteDerived%20%7B%0D%0A%20%20%20%20a%3A%20string%2C%0D%0A%20%20%20%20b%3A%20string%2C%0D%0A%20%20%20%20c%3A%20string%2C%0D%0A%7D%0D%0Aconst%20derived%3A%20ConcreteDerived%20%3D%20null%20as%20any%3B%0D%0Aconst%20test%3A%20%7B%20test%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0Aconst%20both%3A%20ConcreteDerived%20%26%20%7B%20test%20%3A%20string%20%7D%20%3D%20null%20as%20any%3B%0D%0A%0D%0Aconst%20works0%3A%20SomeType%3CConcreteBase%3E%20%3D%20derived%3B%0D%0Aconst%20works1%3A%20SomeType%3CConcreteDerived%3E%20%3D%20derived%3B%0D%0Aconst%20works2%3A%20SomeType%3C%7B%20test%3A%20string%20%7D%3E%20%3D%20test%3B%0D%0A%0D%0Aconst%20worksOutFine%3A%20SomeType%3CConcreteBase%20%26%20%7B%20test%3A%20string%20%7D%3E%20%3D%20both%3B)

**Related Issues:**

**Comment by mhegazy** [comment]
This is a breaking change in TS 2.9 (documentation should come soon) introduced by https://github.com/Microsoft/TypeScript/pull/23592. With https://github.com/Microsoft/TypeScript/pull/23592 `keyof` now returns all known keys of a types including `string`, `number` and `symbol` keys. and as such, the constraint on `keyof E` is now `string | number | symbol`.

If you are interested in getting only the string portions of the keys, use `Extract`: 

```ts
function isKey<E>(str: string): str is Extract<keyof E, string> {
    return true;
}
```

if your function is meant to handle *all* property names, including symbols, then consider widening the declaration of `str`:
```ts
function isKey<E> (str : string | number | symbol) : str is keyof E {
    return true;
}
```

**Comment by ahejlsberg** [comment]
Also, as a temporary measure you can use the new `--keyofStringsOnly` compiler option to revert to the old behavior.

**Comment by AnyhowStep** [comment]
Thanks for the swift response!

**Comment by abdatta** [comment]
However, if I specifically mention that my type has only string keys like this:
```ts
interface A { [k: string]: any; }
type b = keyof A;
```
still, I get the type of b as `string | number` as seen in the IntelliSense on vs code:
![image](https://user-images.githubusercontent.com/20218826/83761124-829dbb80-a693-11ea-9345-10c517bbb6b3.png)
Why is that so? Why is it not string only?

**Comment by SLGShark6** [comment]
For typescript 4, I use this in place of keyof as a current workaround to get accurate key types

```typescript
type KeyTypes<T> = {
    [K in keyof T]-?: K extends string ?
        string :
        K extends number ?
            number :
            K extends symbol ?
                symbol :
                never
}[keyof T];

type KeyOfType<T, KeyType extends string | number | symbol = KeyTypes<T>> = Extract<keyof T, KeyType>;
```
