### PR TITLE
Distribute indexes of indexed access types first

### LINKED ISSUE #27224: No contextual type from indexed access into intersection type
**TypeScript Version:**  3.1.0-dev.20180828

**Code**

```ts
type Keys = "a" | "b";

type OptionsForKey = { a: { cb: (p: number) => number } } & { b: {} };

declare function f<K extends Keys>(key: K, options: OptionsForKey[K]): void;

f("a", {
    cb: p => p,
});
```

**Expected behavior:**

No error.

**Actual behavior:**

`src/a.ts:8:9 - error TS7006: Parameter 'p' implicitly has an 'any' type.`

Broken by #26281

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #27224

This change is a small addition (plus a bunch of comments to illustrate the process) to `getSimplifiedIndexAccessType`. To begin, let me explain the original issue. The contextual typing issue reported boils down to this:

```ts
function g<
    K extends "a" | "b">(x: ({ a: string } & { b: string })[K], y: string) {
    x = y;
}
```
This assignment worked in 3.0, and it should continue to do so. However the distribution change broke that, and in `master` (and 3.1) this assignment fails. Why? This is why: We'd see `({ a: string } & { b: string })[K]` and distribute `K` into the intersection, producing `{ a: string }[K] & { b: string }[K]`. Then for each we would get its apparent type, which means its constraint. That produces `{ a: string }["a" | "b"] & { b: string }["a" | "b"]`, which in turn becomes `({ a: string }["a"] | { a: string }["b"]) & ({ b: string }["a"] | { b: string }["b"])`, which again becomes `(string | unknown) & (unknown | string)` which is simply `unknown` (or for constraint calculation, no constraint - which is subtly different in that no constraint means it's not assignable).

This changes this in two ways:
1. We distribute index types over the object type _before_ distributing into the object type.
2. We do not perform distributions over the inner object type until the index type is no longer instantiable (and therefore might becomes a union we would need to distribute).

This changes how the algebra of the above example proceeds. Starting with `({ a: string } & { b: string })[K]` we _do not_ simplify via distribution, then we get its constraint, `({ a: string } & { b: string })["a" | "b"]`. This distributes into `({ a: string } & { b: string })["a"] | ({ a: string } & { b: string })["b"]` which becomes `({ a: string }["a"] & { b: string }["a"]) | ({ a: string }["b"] & { b: string }["b"])` which becomes `(string & unknown) | (unknown & string)` which is now just `string` (as `unknown` is a noop in an intersection like `never` is in a union), which is our desired type.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this

**Comment by weswigham** [comment]
RWC build failed because master had some unaccepted diffs (which I have now accepted since they were just better error locations). The diff between master and this PR was null, so RWC is unaffected by this change.
