### PR TITLE
Allow contextually reserved names in import/export clauses

### LINKED ISSUE #2849: checkGrammarImportDeclarationNameInStrictMode does not check whether nameText is actually a reserved word or not
See https://github.com/Microsoft/TypeScript/pull/2684#issuecomment-94633608

>With this change, `import * as set from "set";` no longer compiles - `error TS1212: Identifier expected. 'set' is a reserved word in strict mode` (because name.originalKeywordKind is set to SetKeyword). Is this intentional? Or should the checks for originalKeywordKind check that it's between First and LastKeyword/ReservedWord/FutureReservedWord before generating the diagnostic?

>Such code compiles with 1.5 alpha with no issue.

https://github.com/Microsoft/TypeScript/blame/7f8e21b/src/compiler/checker.ts#L12033-L12061

Perhaps it should call isReservedWordInStrictMode on nameText before calling grammarErrorOnNode?

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Because keywords like `set`, `yield`, and `as` are only *contextually* reserved, they should be allowed as identifiers in import and exported clauses.

Fixes #2849.

Review commit-by-commit.

### CODE REVIEW

File: tests/cases/conformance/es6/modules/exportsAndImportsWithContextualKeywordNames01.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
+﻿// @module: commonjs
+// @target: es5
+
+// @filename: t1.ts
+let set = {
```
Comment (mhegazy) [inline tests/cases/conformance/es6/modules/exportsAndImportsWithContextualKeywordNames01.ts]: can you add "as" as well?

**Comment by mhegazy** [comment]
:+1:
