### ISSUE TITLE
typeof this.xxx gives "identifier expected" error.

### ISSUE THREAD

**Issue by vilic** [microsoft/TypeScript#1554]
![image](https://cloud.githubusercontent.com/assets/970430/5548641/780c2af6-8bb1-11e4-9bc2-b7ab25c90797.png)

Is this by design or a bug?

**Comment by juanevp** [comment]
Just to add another use case. Some time ago I made the type definitions for lodash and some of the supported signatures are really aliases for other methods. I had declared them like this:

```typescript
interface LoDashArrayWrapper<T> {
    rest(): LoDashArrayWrapper<T>;
    rest(
        callback: ListIterator<T, boolean>,
        thisArg?: any): LoDashArrayWrapper<T>;
    rest(n: number): LoDashArrayWrapper<T>;
    rest(pluckValue: string): LoDashArrayWrapper<T>;
    rest(whereValue: {}): LoDashArrayWrapper<T>;

    drop: typeof rest;

    tail: typeof rest;
}
```
This worked alright with version 1.0 of the compiler. But it doesn't compile any longer. And I don't see any other option besides duplicating the whole set of signatures for each alias as I cannot think of a TypeQueryExpression that expresses this.

**Comment by mwisnicki** [comment]
@juanevp How about function interface ?

```ts
interface LoDashArrayWrapper<T> {
    rest: LoDashArrayWrapperOperation<T>;
    drop: LoDashArrayWrapperOperation<T>;
    tail: LoDashArrayWrapperOperation<T>;
}

interface LoDashArrayWrapperOperation<T> {
	(): LoDashArrayWrapper<T>;
    (
        callback: ListIterator<T, boolean>,
        thisArg?: any): LoDashArrayWrapper<T>;
    (n: number): LoDashArrayWrapper<T>;
    (pluckValue: string): LoDashArrayWrapper<T>;
    (whereValue: {}): LoDashArrayWrapper<T>;
}
```

**Comment by RyanCavanaugh** [comment]
Approved. Should be extremely easy fix?

**Comment by Ciantic** [comment]
Is this related? I get `[ts] Identifier expected.` with following:

```

class UserState2 {
    @observable state = {
        name : "",
        id : "",
    };

    @action
    changeUser(user: typeof this.state) {
        Object.assign(this.state, user);
    }
}

export const userState2 = new UserState2();
```

It would be useful to be able to use `this.state` in above case.

**Comment by sam-s4s** [comment]
Hmmm I've just run into this problem :(

I'm defining an object in my class.
Then I'm defining another object that has a type param that needs to be the type of the above.

```
thing = {
    a: 1,
    b: 2
};
multi: CMultiDataset<typeof this.thing>;
```

In this case it is not appropriate to just change thing to a static variable and say `typeof ClassName.thing` because it will be different in each instance.

**Comment by weswigham** [comment]
@sam-s4s nowdays you aught to be able to write `CMultiDataset<this["thing"]>`, instead. Indexed acceses _do_ worth with `this` (a polymorphic one, even), unlike `typeof`.

**Comment by sam-s4s** [comment]
Thanks @weswigham - I did find out that I can do `CMultiDataset<ClassName['thing']>` which mostly gets me out of trouble :)

No combination I could find using `this` would work though...

**Comment by yxliang01** [comment]
> @sam-s4s nowdays you aught to be able to write `CMultiDataset<this["thing"]>`, instead. Indexed acceses _do_ work with `this` (a polymorphic one, even), unlike `typeof`.

I have just tried, but it doesn't work in TypeScript 3.4.4 though, @sam-s4s 's one works (`ClassName['thing']`). I think it might make more sense that `this` should work, instead of only able to use the "ClassName"?

**Comment by vegerot** [comment]
If I have something like 
```typescript
  public groupByTypes = ['None', 'Foo', 'Bar'] as const;
   
  public groupBy: typeof groupByTypes[number];
 ``` 
What is the proposed workaround?  And I cannot make `groupByTypes` static

**Comment by Feofilakt** [comment]
OMG, 7 years old design bug. Ok, see what would be after yet another 7.

**Comment by ubershmekel** [comment]
My use-case is I'm sending a callback to a library which has the wrong type specialization. I also don't want to have to remember this spot in the code in case these variables ever change their type. So it looks like

```
  async foundBob(player: any, bob: any) {
    player = player as typeof this.player;
    ^^ ts(2304) Cannot find name 'this'.
```

**Comment by Zzzen** [comment]
Have you tried `const player = playerTypeLess as this['player']` ? @ubershmekel

**Comment by royeradames** [comment]
> Have you tried `const player = playerTypeLess as this['player']` ? @ubershmekel

 TS2304: Cannot find name 'this'.

243     selectedPlanFilters? = [] as typeof this["filters"];

**Comment by muuvmuuv** [comment]
I get no errors for this in VS Code but from the Angular compiler. Did anyone has a workaround for TS2304? I would like to have FormGroup.value typed in ngSubmit function with `typeof this.formGroup.value`.

**Comment by Xriuk** [comment]
> I get no errors for this in VS Code but from the Angular compiler. Did anyone has a workaround for TS2304? I would like to have FormGroup.value typed in ngSubmit function with `typeof this.formGroup.value`.

More or less the same, it used to work while on Angular 14 (also tried with Angular 15), but with Angular 16 it compiles, then after a save it recompiles partially and this error pops up.
