### PR TITLE
Fix regression no codefix for ts2657

### LINKED ISSUE #43454: Regression: Fix for error ts2657 no longer works
# Bug Report

```tsx
const test = <a></a><b></b>
```

should have code fix

### 🕗 Version & Regression Information

Not works in 4.3.0-dev.20210329. Introduced in #37917 

### 🙁 Actual behavior

No code fix available

### 🙂 Expected behavior

Have code fix

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #43454

### CODE REVIEW

File: src/services/codefixes/wrapJsxInFragment.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ namespace ts.codefix {
         errorCodes,
         getCodeActions: context => {
             const { jsx } = context.program.getCompilerOptions();
-            if (jsx !== JsxEmit.React && jsx !== JsxEmit.ReactNative) {
+            if (!jsx || [JsxEmit.React, JsxEmit.ReactNative, JsxEmit.ReactJSX, JsxEmit.ReactJSXDev].indexOf(jsx) === -1) {
```
Comment (andrewbranch) [inline src/services/codefixes/wrapJsxInFragment.ts:9]: Why isn’t this allowed in `JsxEmit.Preserve`? The error still applies and the fix is still plausibly valid. Unless someone knows a good reason not to offer the fix, I would just do

```suggestion
            if (!jsx) {
```

And, by the way, even that should be unnecessary, since you should never get this error if you have `undefined` or `JsxEmit.None` anyway 🤔

**Review by andrewbranch — CHANGES_REQUESTED** [review]

**Review by andrewbranch — APPROVED** [review]
Thanks!
