### PR TITLE
resolve from outDir

### LINKED ISSUE #22208: foo.ts is resolved before foo.d.ts even if the latter is in files[]
This problem appears when compiling files separately, like we do under Bazel.
Imagine this simple app

`src/lib.ts`
```
export const a = 1;
```
`src/main.ts`
```
import {a} from './lib';
```

Imagine `lib.ts` was compiled separately, so there already exists
`dist/lib.d.ts`
```
export declare const a = 1;
```

Now, I want to compile `main.ts` as a separate program. Given  `src/tsconfig.json`

```
{
  "compilerOptions": {
    "rootDirs": [
      ".",
      "../dist"
    ],
    "outDir": "../dist",
    "declaration": true
  },

  "files": [
    "main.ts",
    // lib was compiled separately
    "../dist/lib.d.ts"
  ]
}
```

We see that `lib.d.ts` is already in the program before resolution begins. However the compiler resolves the import statement to the `lib.ts` file instead, adding it to the program, and tries to emit on top of an input, so the error is

```
$ ./node_modules/.bin/tsc -p src
error TS5055: Cannot write file '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/dist/lib.d.ts' because it would overwrite input file.
```

Okay, we didn't want `lib.ts` in the program, so we should just use `--noResolve` to prevent that, but it's also broken:
```
$ ./node_modules/.bin/tsc -p src --noResolve --traceResolution
======== Resolving module './lib' from '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/main.ts'. ========
Module resolution kind is not specified, using 'NodeJs'.
'rootDirs' option is set, using it to resolve relative module name './lib'.
Checking if '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/' is the longest matching prefix for '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/lib' - 'true'.
Checking if '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/dist/' is the longest matching prefix for '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/lib' - 'false'.
Longest matching prefix for '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/lib' is '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/'.
Loading 'lib' from the root dir '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/', candidate location '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/lib'.
Loading module as file / folder, candidate module location '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/lib', target file type 'TypeScript'.
File '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/lib.ts' exist - use it as a name resolution result.
======== Module name './lib' was successfully resolved to '/usr/local/google/home/alexeagle/Projects/repro_ts_resolving_ts/src/lib.ts'. ========
src/main.ts(1,17): error TS2307: Cannot find module './lib'.
```

So far our workaround at Google is one of:
- use Bazel sandboxing to make the inputs appear in different places
- use our own custom compiler which elides any emit to files we don't expect

However under Bazel we sometimes cannot sandbox (eg. on Windows) and cannot use our custom compiler (eg. when we are compiling it)
so we are stuck.

I found that `ts.CompilerOptions.suppressOutputPathCheck` could be a workaround, but `tsc` doesn't allow that flag from the command line.

### LINKED ISSUE #37378: --outDir command-line option not reflected in .tsbuildinfo
In https://github.com/microsoft/TypeScript/issues/37257 I discussed one way to host TS project references under Bazel, where each build step gets only `.d.ts` and `tsconfig.json` files from the referenced projects. This is broken because TS module resolution fails to locate the `.d.ts` files in their `outDir`.

In this issue, let's try a different approach for Bazel, to satisfy current TS module resolution, each build step should get the `.ts` sources of its referenced projects, and the `.tsbuildinfo` output as well.

Bazel is picky about the setting of `--outDir`, because it supports cross-compiled builds in distinct output locations. For example if you're on a Mac and building for local platform, the outDir is `<workspace root>/bazel-out/darwin-fastbuild/bin`. But if you're on a Mac and building for a docker image, you need native binaries to be for the target platform so outDir is `<workspace root>/bazel-out/k8-fastbuild/bin` and if you want binaries with debug information it's `<workspace root>/bazel-out/k8-dbg/bin`.

Since the outDir is platform-specific, we don't want to check in a config file that hard-codes it. So we prefer to always have Bazel pass the `--outDir` option on the command-line to `tsc`, rather than include it in the tsconfig files.

Now we come to the problem. TypeScript "composite" setting enables up-to-dateness checking in `tsc`. With this input structure, and trying to `tsc -p b`

```
a/a.ts
a/tsconfig.json (no outDir specified; a was compiled with tsc --outDir=bazel-out/darwin-fastbuild/bin/a)
b/b.ts
b/tsconfig.json
bazel-out/darwin-fastbuild/bin/a/a.d.ts
bazel-out/darwin-fastbuild/bin/a/tsconfig.tsbuildinfo
```

we get `b/b.ts(1,17): error TS6305: Output file '/private/var/tmp/_bazel_alx/df60115ea7f2a64e10fb4aa64b7d827f/sandbox/darwin-sandbox/54/execroot/ts_composite/a/a.d.ts' has not been built from source file '/private/var/tmp/_bazel_alx/df60115ea7f2a64e10fb4aa64b7d827f/sandbox/darwin-sandbox/54/execroot/ts_composite/a/a.ts'.`

This is because the compilation of a/tsconfig.json produces a .tsbuildinfo file with
```
 "options": {
      "project": "../../../../a/tsconfig.json",
      "outDir": "./",
  }
```
which forces us to hard-code the platform-dependent outDir into a/tsconfig.json like I've done here
https://github.com/alexeagle/ts_composite/pull/5

So the feature request here is for the `outDir` command-line option to be reflected in the .tsbuildinfo output (maybe others should be treated similarly for consistency)

### PR DESCRIPTION
**Pull request by alexeagle**
Under the new proposed `compilerOptions.resolveFromOutDir` boolean,
module resolution is attempted relative to the output folder.

This is analogous to loading from the rootDirs, however it allows
compilation where the output directory is configured on the command line
rather than in the tsconfig.json.

See the attached issue for context.

TODO:
- figure out what tests to add
- reason about whether this interacts correctly with other related
module resolution conditional logic
- verify this works in some Bazel projects where the problem is observed

Fixes #22208
Fixes #37378

### CODE REVIEW

**Review by sheetalkamat — CHANGES_REQUESTED** [review]
I think the suggestion was to compute outDir for the referenced project and not change module resolution.

**Comment by alexeagle** [comment]
Thanks @sheetalkamat I replied on the associated issue about why this design was chosen.

**Comment by sandersn** [comment]
Reading through the issue history, it looks like bazel doesn't need this PR anymore. I'm going to close it since I don't think @sheetalkamat 's concerns ever changed.

@alexeagle let me know if we should re-open this.
