### ISSUE TITLE
Expression produces a union type that is too complex to represent

### ISSUE THREAD

**Issue by MichaelTontchev** [microsoft/TypeScript#44075]
# Bug Report

### 🔎 Search Terms

union type that is too complex to represent

### 🕗 Version & Regression Information

TS version: 4.2.3
- This is the behavior in every version I tried, and I reviewed the FAQ for entries about union types too complex to represent

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/C4TwDgpgBA6glsAFgZWAJzgOwOYAU0D2kaoAPANJQQAewEmAJgM5RPpbYB8UAvFAN4BYAFABIANq4oWKOQC6ALlbscAbhEBfdcJEAzAK6YAxsDgFMVWmgCGJ-EQgkQFS3UYs2GHJwAUAdxswYiUAEQgIMAAlCGsGcwAbZ3gkVC88QmIyck5OABooAGsIECVyAEoBEVE0CGB9NAsA6yDHcSKQOW0NEREaMAISKAYII3jrGqhQSCgwiOjYhOcAFW4+Jdd6ZigAIX04eNNMESgoAH4oJeOoJXWaNy3+buET86Fnk4+ahcxEqHFKGTtAi6C6KGbhKIxOI-Zb-OScbQfKBPE5KebQxKkFbaXrUfqDYajcbQKbQXb7Q68KD4OAAWwQcAAbtAAD5QABihhMZgsbJC1joUDZAFE0IQ0EKoNFsMK8do+gNgEMRmMJqTqRh6aZmVTPBxJZh9LSAEaOSXGggEeIxXlQY1wbBYJVspggE1WyWGYa6LAQBgG-TxeKqIA)

### 💻 Code
I have a function that should be able to take an object along with a key name that will be present within that object, and it expects the key to be present within that object with a specific type, which in this example I hardcode to string to simplify the problem:

```
type WithStringProperty<K extends string> = {
	[P in K]: string;
};

function extractProperty<K extends string>(wrapper: WithStringProperty<K>, key: K) {
	return wrapper[key];
}
```

This much *works*. But when I make my `wrapper` parameter a little more complex by wrapping it in DeepReadonly, it fails with the error from the title:

```
function extractProperty<K extends string>(wrapper: DeepReadonly<WithStringProperty<K>>, key: K) {
	return wrapper[key];
}
```

DeepReadonly is from ts-essentials:

```
export declare type DeepReadonly<T> = T extends Builtin
  ? T
  : T extends {}
  ? {
      readonly [K in keyof T]: DeepReadonly<T[K]>;
    }
  : Readonly<T>;

export declare type Builtin = Primitive | Function | Date | Error | RegExp;
```

It doesn't seem like the combination should introduce some large combination of possible union types, but I guess I'm wrong?

### 🙁 Actual behavior

Error: Expression produces a union type that is too complex to represent

### 🙂 Expected behavior

No error

**Comment by RyanCavanaugh** [comment]
This really is computing a very large union in the background as TS tries to figure out the possible types of element access on `wrapper`. We may be able to defer this better but there's not much reason to write the function that way - is there an expanded example that shows why you want to write `DeepReadonly<` there?

**Comment by MichaelTontchev** [comment]
@RyanCavanaugh Yeah, the above is a minimal repro of the issue. In reality, the DeepReadonly wraps a slice of my Redux state, and the function above is actually part of a cache utility class that takes in the cache in my redux slice and wraps it so that it can easily be queried and written to. The reason I take in a field name is because the cache clients may pass in different structures they want cached, and parameterizing the field name allows them to handle the different cases.
So, roughly, I have a state slice that looks like
Map<ItemId, {
    itemMetadata: ICached<IMetadata>;
    // other stuff...
}>
And I want the cache utility class to take in an ID of an Item to retrieve/cache, access the map above, and then chache the metadata part inside. The "other stuff needs no caching".
Other clients of the cache class may have a similar two-level structure, but their field name won't be "itemMetadata", it may be "elementMetadata" (you may notice these are just placeholders :P )

**Comment by MichaelTontchev** [comment]
I should note: It's only when I introduced `WithStringProperty` that I started having problems. My entire Redux store is wrapped in a Deepreadonly and it's never had problems before.

**Comment by MichaelTontchev** [comment]
@RyanCavanaugh is there a way around this?

**Comment by SDAdham** [comment]
I am experiencing the same problem, but for me, it's highlighting JSON file content which is `array` content.

```
someFile.json:1:1 - error TS2590: Expression produces a union type that is too complex to represent.

     1 [
       ~
     2   {
       ~~~
   ...
341929   }
       ~~~
341930 ]
```

Previous TS version that it works with is `~4.0.2` just fine, I was trying to upgrade to `4.3.x`, I noticed no documentation about this, but I keep trying with different versions of TS.

**Comment by SDAdham** [comment]
Ok, reverting back to `typescript` v`4.0.2` didn't help. Since I upgraded some of my packages, and this issue came up, tracing which combination/package causing this issue is time consuming, i just took the json file out and it worked like a charm.

**Comment by richardscarrott** [comment]
@SDAdham  I experienced this in TS 3.9.7 where we have a load of static data defined in TS, e.g.

```ts
enum Thing {
    Foo = 'Foo',
    Bar = 'Bar',
    // +100s of others
}

interface Data {
   id: string;
   thing: Thing;
}

const data: Data[] = [{
   id: '123',
   thing: Thing.Foo
}, {
   id: '234',
   thing: Thing.Bar
},
// ... +100s of others
];
```

So I'm guessing TS treats it as a discriminating union before the type is loosened to just `Data`?

We found asserting `thing` as `Thing` solved the issue:
```ts
const data: Data[] = [{
   id: '123',
   thing: Thing.Foo as Thing
}, {
   id: '234',
   thing: Thing.Bar as Thing
},
// ... +100s of others
];
```

**Comment by mkantor** [comment]
This seems to have been fixed, though I'm not sure which pull request was responsible. [In 5.4 and later the example from the issue description has no type errors](https://www.typescriptlang.org/play/?ts=5.4.5#code/C4TwDgpgBA6glsAFgZWAJzgOwOYAU0D2kaoAPANJQQAewEmAJgM5RPpbYB8UAvFAN4BYAFABIANq4oWKOQC6ALlbscAbhEBfdcJEAzAK6YAxsDgFMVWmgCGJ-EQgkQFS3UYs2GHJwAUAdxswYiUAEQgIMAAlCGsGcwAbZ3gkVC88QmIyck5OABooAGsIECVyAEoBEVE0CGB9NAsA6yDHcSKQOW0NEREaMAISKAYII3jrGqhQSCgwiOjYhOcAFW4+Jdd6ZigAIX04eNNMESgoAH4oJeOoJXWaNy3+buET86Fnk4+ahcxEqHFKGTtAi6C6KGbhKIxOI-Zb-OScbQfKBPE5KebQxKkFbaXrUfqDYajcbQKbQXb7Q68KD4OAAWwQcAAbtAAD5QABihhMZgsbJC1joUDZAFE0IQ0EKoNFsMK8do+gNgEMRmMJqTqRh6aZmVTPBxJZh9LSAEaOSXGggEeIxXlQY1wbBYJVspggE1WyWGYa6LAQBgG-TxeKqIA).
