### ISSUE TITLE
isArray type guards still causing issues in latest nightly build 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/TypeScript#42768]
# Bug Report

### 🔎 Search Terms
- isArray

### 🕗 Version & Regression Information

Tested in 4.3.0-dev.20210211 which 

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PTAEFkE9QYwewCYFNQHM5IM6gBZIE5JA)

### 💻 Code

In the VS Code codebase, we are still seeing the `isArray` type guards causing problems with the latest TS 4.3 nightly build. 

Here's an example from [this file](https://github.com/microsoft/vscode/blob/907050807608bfe4705a426e819815e97f2429be/src/vs/workbench/api/common/extHostTypeConverters.ts#L1275)

The type of `DocumentSelector` is `string | vscode.DocumentFilter | readonly (string | vscode.DocumentFilter)[]`

```ts
	export function from(selector: vscode.DocumentSelector | undefined): languageSelector.LanguageSelector | undefined {
		if (!selector) {
			return undefined;
		} else if (Array.isArray(selector)) {
			return <languageSelector.LanguageSelector>selector.map(from);
		} else if (typeof selector === 'string') {
			return selector;
		} else {
			return <languageSelector.LanguageFilter>{
				language: selector.language,
				scheme: selector.scheme,
				pattern: typeof selector.pattern === 'undefined' ? undefined : GlobPattern.from(selector.pattern),
				exclusive: selector.exclusive
			};
		}
	}
```

These errors did not show up with `typescript@4.2.0-dev.20201207`. 

Here are the other errors:

```
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/services/extensions/common/abstractExtensionService.ts(545,58): Argument of type 'ILocalization[] | IAuthenticationContribution[] | IDebugger[] | { [location: string]: IView[]; } | ISnippet[] | IConfiguration | ... 12 more ... | undefined' is not assignable to parameter of type 'T'.
[watch-client    ]   'T' could be instantiated with an arbitrary type which could be unrelated to 'ILocalization[] | IAuthenticationContribution[] | IDebugger[] | { [location: string]: IView[]; } | ISnippet[] | IConfiguration | ... 12 more ... | undefined'.
[watch-client    ]     Type 'undefined' is not assignable to type 'T'.
[watch-client    ]       'T' could be instantiated with an arbitrary type which could be unrelated to 'undefined'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/services/extensions/common/abstractExtensionService.ts(700,6): Type 'ILocalization[] | IAuthenticationContribution[] | IDebugger[] | { [location: string]: IView[]; } | ISnippet[] | IConfiguration | ... 12 more ... | undefined' is not assignable to type 'T'.
[watch-client    ]   'T' could be instantiated with an arbitrary type which could be unrelated to 'ILocalization[] | IAuthenticationContribution[] | IDebugger[] | { [location: string]: IView[]; } | ISnippet[] | IConfiguration | ... 12 more ... | undefined'.
[watch-client    ]     Type 'undefined' is not assignable to type 'T'.
[watch-client    ]       'T' could be instantiated with an arbitrary type which could be unrelated to 'undefined'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/base/browser/ui/dropdown/dropdownActionViewItem.ts(175,99): Property 'getActions' does not exist on type 'readonly IAction[] | IActionProvider'.
[watch-client    ]   Property 'getActions' does not exist on type 'readonly IAction[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostTypeConverters.ts(1284,24): Property 'language' does not exist on type 'DocumentFilter | readonly (string | DocumentFilter)[]'.
[watch-client    ]   Property 'language' does not exist on type 'readonly (string | DocumentFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostTypeConverters.ts(1285,22): Property 'scheme' does not exist on type 'DocumentFilter | readonly (string | DocumentFilter)[]'.
[watch-client    ]   Property 'scheme' does not exist on type 'readonly (string | DocumentFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostTypeConverters.ts(1286,30): Property 'pattern' does not exist on type 'DocumentFilter | readonly (string | DocumentFilter)[]'.
[watch-client    ]   Property 'pattern' does not exist on type 'readonly (string | DocumentFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostTypeConverters.ts(1286,94): Property 'pattern' does not exist on type 'DocumentFilter | readonly (string | DocumentFilter)[]'.
[watch-client    ]   Property 'pattern' does not exist on type 'readonly (string | DocumentFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHostTypeConverters.ts(1287,25): Property 'exclusive' does not exist on type 'DocumentFilter | readonly (string | DocumentFilter)[]'.
[watch-client    ]   Property 'exclusive' does not exist on type 'readonly (string | DocumentFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHost.api.impl.ts(201,26): Property 'scheme' does not exist on type 'DocumentFilter | readonly (string | DocumentFilter)[]'.
[watch-client    ]   Property 'scheme' does not exist on type 'readonly (string | DocumentFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/workbench/api/common/extHost.api.impl.ts(204,58): Property 'exclusive' does not exist on type 'DocumentFilter | readonly (string | DocumentFilter)[]'.
[watch-client    ]   Property 'exclusive' does not exist on type 'readonly (string | DocumentFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/editor/common/modes/languageSelector.ts(58,11): Property 'language' does not exist on type 'LanguageFilter | readonly (string | LanguageFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/editor/common/modes/languageSelector.ts(58,21): Property 'pattern' does not exist on type 'LanguageFilter | readonly (string | LanguageFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/editor/common/modes/languageSelector.ts(58,30): Property 'scheme' does not exist on type 'LanguageFilter | readonly (string | LanguageFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/editor/common/modes/languageSelector.ts(58,38): Property 'hasAccessToAllModels' does not exist on type 'LanguageFilter | readonly (string | LanguageFilter)[]'.
[watch-client    ] [13:45:27] Error: /Users/matb/projects/vscode/src/vs/editor/common/modes/languageFeatureRegistry.ts(28,21): Property 'exclusive' does not exist on type 'LanguageFilter | readonly (string | LanguageFilter)[]'.
[watch-client    ]   Property 'exclusive' does not exist on type 'readonly (string | LanguageFilter)[]'.
```

@orta @RyanCavanaugh I believed that https://github.com/microsoft/TypeScript/pull/41851 was supposed to fix these issues. Can you please take a look at our errors and me know if we need to change anything on the VS Code side or if these are unexpected errors

**Comment by orta** [comment]
That's likely the result of https://github.com/microsoft/vscode/pull/102413 which used to rely on some of the changes - I've shipped https://github.com/microsoft/vscode/pull/116571 which reverts those changes too

**Comment by mjbvz** [comment]
Thanks for taking a look. After merging that commit however, I'm still seeing these errors. I tested with both the latest nightly and the 4.2-rc.

It looks like this location for example is using the standard `Array.isArray` function: https://github.com/microsoft/vscode/blob/868fb4c39f3e07899d7e88317510fcdab13b2849/src/vs/workbench/api/common/extHostTypeConverters.ts#L1338

**Comment by orta** [comment]
It looks like this code only worked on nightly builds of 4.2 while the isArray narrowing was still in and before it got pulled out prior to the RC. Correctly narrowing via this check isArray seems to be a lot of trade-offs which we've concluded broke too much prod code. I've re-opened https://github.com/microsoft/TypeScript/issues/31155 which is the underlaying issue (switch 'instanceof' with 'Array.isArray' for this explanation https://github.com/microsoft/TypeScript/issues/31155#issuecomment-487595398

You can try this playground with [any of the prod builds](https://www.typescriptlang.org/play?ts=4.2.1-rc&ssl=1&ssc=1&pln=23&pc=1#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgGUyQHMBXTY4AMQQBtUo4BvAKAEgphMATCJWgJ5xaRMhWAB+AFxwAzjCjJiAbnacefQXOwALYAFtJM+YpKqOXXvyFhMMBkmlyFS8wHoAVB-ZwPcACo6CLJwYFAQAG4I3GiIIQj6YLQGwCjA3IhIcDB6cACqAJLZOurcAHQ+Hm5qlppCOpiyAILYuLKy-hBNtLQAshAxtLJOAEYQEMlE5qV1cKDYtKSyCBFGcGMTXEiqAL4sLKCQsNkCYHiEJOSUAMrAydgw0HAAvM6mxHAAPgSiV9R0DC+cAASrVrE0oFBMAIADwmJRAi5iSg0ehoAB8qhY6FISAeCD4cQAoiAFksVsAABSyO7AB7QGRIv63e6PKAAShkG0mWVYbAQ6DglJgp2AEEFNNZT2eMrgAHJ4SQ5ezmOwLDBSFAslghsBzDs5rrEILKRCoQIysEzdDqbT6RyVXz1ZqspK6WyysBVlABJTgiSyctVuz9Yaaaq2M6tXAAIQxt32z2kxZBvXsPZ7IA) in the versions (and then try `4.2.0-dev.20201207`)

IMO, this probably needs code changes on the vscode side

**Comment by mjbvz** [comment]
Thanks. The function itself hasn't changed but we did make one of the type `ReadonlyArray` instead of a normal `Array`. I don't fully understand the typing discussion going on.  I guess a minimal example of the problem would be:

```ts
declare const x: string | readonly string[]

if (!Array.isArray(x)) {
	x.toLocaleLowerCase() // Property 'toLocaleLowerCase' does not exist on type 'string | readonly string[]'.
}
```

I'll look into adding casts or something to workaround this

**Comment by orta** [comment]
Roughly what's happening: a `readonly string[]` is a subset of `string[]` (because the mutable bits are removed in the type system by being marked readonly) which means that it doesn't  pass the narrowing how you'd think/expect it to, but it passes a different part of the narrowing check which says 'keep this type' because of the `any[]` result in `Array.isArray`

I agree its a bug though, you'd expect that to work which was why we originally tried to propagate the readonly through

**Comment by wangweixuan** [comment]
I ran into a similar problem. I believe that `Array.isArray` should be considered as a type guard of `ReadonlyArray<any>` instead of `Array<any>`, i.e.
```typescript
interface ArrayConstructor {
    isArray(arg: any): arg is readonly any[];
}
```

This fixes the present issues and produces expected behavior. I also believe it better reflects the behavior of that function. See the following test cases:
```typescript
declare const foo: number | number[];

declare const bar: number | readonly number[];

// Original version:
declare function isArray(arg: any): arg is any[];

if (isArray(foo)) {
  foo.indexOf(42); // ✅ pass; 'foo' is number[]
  foo.indexOf("Not a number"); // ✅ error
} else {
  foo + 1; // ✅ pass
}

if (isArray(bar)) {
  bar.indexOf(42); // ❌ unexpected: 'foo' becomes any[]
  bar.indexOf("Not a number"); // ❌ unexpected: should error
} else {
  bar + 1; // ❌ unexpected: should pass
}

// Fixed version:
declare function isArrayFixed(arg: any): arg is readonly any[];

if (isArrayFixed(foo)) {
  foo.indexOf(42); // ✅ pass; 'foo' is number[]
  foo.indexOf("Not a number"); // ✅ error
} else {
  foo + 1; // ✅ pass
}

if (isArrayFixed(bar)) {
  bar.indexOf(42); // ✅ pass; 'bar' is readonly number[]
  bar.indexOf("Not a number"); // ✅ error
} else {
  bar + 1; // ✅ pass
}
```

**Comment by wangweixuan** [comment]
It's covered in #17002 and will potentially be fixed in #42316.

**Comment by RedCMD** [comment]
can confirm
`Array.isArray()` type narrowing is broken with `readonly` arrays

<img width="410" height="165" alt="Image" src="https://github.com/user-attachments/assets/e37858e4-8681-4af2-b173-acd5766fe7d7" />

```ts
const arr = [] as readonly string[];
if (Array.isArray(arr)) {
	arr;
}
```

---

without `readonly`
<img width="309" height="169" alt="Image" src="https://github.com/user-attachments/assets/821fa1ab-c04c-4b0e-9c6e-4ae5409a5768" />

---

my use case in VSCode

<img width="668" height="145" alt="Image" src="https://github.com/user-attachments/assets/2aabceb5-6888-4286-b0d8-3c080424a7ae" />
