### ISSUE TITLE
Destructuring an array into incompatible type no longer throws an error

### ISSUE THREAD

**Issue by saravanaj** [Microsoft/TypeScript#14768]
**TypeScript Version:**  2.2.1 / 2.1.4

**Code**

```ts
let foo: Array<number> = [1, 2, 3, 4];
let bar: Array<number> = { ...foo };
```

When I try to compile with `tsc@2.1.4`, I get the following error:

> error TS2322: Type '{ [n: number]: number; length: number; }' is not assignable to type 'number[]'.
> Property 'push' is missing in type '{ [n: number]: number; length: number; }'.

With `tsc@2.2.1` I no longer get an error. This should not compile as `bar` is not of type `Array<number>`.

**Comment by mhegazy** [comment]
Should be fixed in latest.
