### ISSUE TITLE
`gulp runtests` broken

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#18505]
I followed history and this was broken by #18462. @weswigham 

```
/home/andy/TypeScript/src/harness/compilerRunner.ts:190
        describe(this.testSuiteName + " tests", () => {
        ^
TypeError: describe is not a function
    at CompilerBaselineRunner.initializeTests (/home/andy/TypeScript/src/harness/compilerRunner.ts:190:9)
    at runTests (/home/andy/TypeScript/src/harness/runner.ts:30:24)
    at beginTests (/home/andy/TypeScript/src/harness/runner.ts:201:5)
    at startTestEnvironment (/home/andy/TypeScript/src/harness/runner.ts:219:5)
    at Object.<anonymous> (/home/andy/TypeScript/src/harness/runner.ts:222:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /home/andy/TypeScript/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/andy/TypeScript/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/andy/TypeScript/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/home/andy/TypeScript/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by weswigham** [comment]
I'd blame me, too. I'll get right on it.

**Comment by andy-ms** [comment]
`jake runtests` is broken also so the error must be something they share in common.

**Comment by weswigham** [comment]
There are two `var` statements in the parallel host file that need to be under a "if (typeof describe === " undefined")` check.
