### ISSUE TITLE
Support @typedef importing a CommonJS default exported class as type into another file

### ISSUE THREAD

**Issue by TheLarkInn** [Microsoft/TypeScript#23375]
**TypeScript Version:**  2.9.0-dev.20180412

**Search Terms:** import("./") jsdoc JavaScript TypeScript CommonJs

**Code**
https://github.com/webpack/webpack/blob/10282ea20648b465caec6448849f24fc34e1ba3e/lib/Chunk.js#L477 Chunk.js 

```js
module.exports = Chunk; // Chunk is a class as seen linked above
```

```js
/**
 * @typedef { import("./Chunk.js") } Chunk
 */

// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
No error, and that the Class is a Type that can be referenced. 
**Actual behavior:**
```
lib/ChunkGroup.js:8:15 - error TS1340: Module './Chunk.js' does not refer to a type, but is used as a type here.

* @typedef { import("./Chunk.js") } Chunk
```
**Playground Link:**  
Not possible because this is across two separate CommonJS modules.

**Comment by sandersn** [comment]
`module.exports = Chunk` is currently not an alias like `export = Chunk` is, so only the value meaning of the class gets exported. Basically, Javascript should use the same infrastructure as Typescript, instead of a hacked-on imitation.

I have a fix that does this, but it breaks the change in #23228, which relies on the incorrect structure. (#23228 allows both `module.exports = Chunk` and `module.exports.staticFunction = () => 12` in the same file)

I'll put up a PR after I get everything working. In the meantime, the branch I'm working in is js/module-exports-is-alias
