### ISSUE TITLE
Feature detection code does not compile with 2.0.2

### ISSUE THREAD

**Issue by reppners** [Microsoft/TypeScript#10662]
**TypeScript Version:**  2.0.2

**Code**

```ts
function selectText( elem:HTMLInputElement, start:number, end:number )
{
    if( elem.createTextRange )
    {
        var selRange = elem.createTextRange();
        selRange.collapse( true );
        selRange.moveStart( "character", start );
        selRange.moveEnd( "character", end );
        selRange.select();
    }
    else if( elem.setSelectionRange )
    {
        elem.setSelectionRange( start, end );
    }
    else if( elem.selectionStart )
    {
        elem.selectionStart = start;
        elem.selectionEnd = end;
    }
    elem.focus();
}
```

**Expected behavior:**
The function checks by presence of Function or Property on the HTMLInputElement what
code to apply to select the text in the input field and should compile fine because I think
that is a common way to do feature detection.

**Actual behavior:** 
It produces the following error:
`TS2339: Property 'createTextRange' does not exist on type 'HTMLInputElement'.`

Of course `HTMLInputElement` declares `createTextRange` as a Function `createTextRange(): TextRange;` but that should not stop me from treating the Function as a Property.

**Comment by mhegazy** [comment]
> Of course HTMLInputElement declares createTextRange as a Function createTextRange(): TextRange; but that should not stop me from treating the Function as a Property.

the issue here is that in lib.d.ts `HTMLInputElement` does **not** declare a property `createTextRange`. I could not find a reference for it on MDN either. 

You can augment the interface declaration for `HTMLInputElement` to define `createTextRange` as such:

```ts
interface HTMLInputElement {
    createTextRange?(): Range;
}

function selectText(elem: HTMLInputElement, start: number, end: number) {
    if (elem.createTextRange) {
        var selRange: Range = elem.createTextRange();
        selRange.collapse(true);

   }
}
```

**Comment by Arnavion** [comment]
(`createTextRange` is a non-standard IE-only property on some element types.)
