### ISSUE TITLE
Overload on constants requires cast for resolution

### ISSUE THREAD

**Issue by NoelAbrahams** [Microsoft/TypeScript#1723]
Hi,

**TS Version**: 1.4

In the following the first call to `doFoo` fails to compile because the overload resolution algorithm picks the general case:

```TypeScript
interface Bar {
    bar?: number;
    baz?: string;
}

interface Foo {
    foo(): string;
}

declare function doFoo(kind: 'Foo', bar?: Bar): Foo;
declare function doFoo(kind: string, bar: any): {}

var x = doFoo('Foo', { bar: 1 });
x.foo(); // Error: Property 'foo' does not exist on type '{}'.

var y = doFoo('Foo', <Bar> { bar: 1 });
y.foo(); // Okay
```

This is a breaking change because it used to work without the need for the cast in 1.3.

I feel this should compile because `{ bar: 1 }` is compatible with the `Bar` interface.

**Comment by RyanCavanaugh** [comment]
Doesn't seem specific to string overloads. This has the potential to break a lot of scenarios.

```ts
declare function doFoo(bar?: { baz?: string; bar: number; }): string;
declare function doFoo(bar?: any): number;

var x = doFoo({ bar: 1 }); // x: number, should be x: string
x = 3; // should error
```

**Comment by RyanCavanaugh** [comment]
Bisected to https://github.com/Microsoft/TypeScript/commit/81eaae0afa37ff150456ccc058a153ebb0f0c428 from #919

**Comment by ahejlsberg** [comment]
@JsonFreeman @RyanCavanaugh @mhegazy I have a proposed fix for this in #1774.

**Comment by JsonFreeman** [comment]
Here is a similar case without any:
```ts
declare function doFoo(bar?: { bar: number; baz?: string; }): string;
declare function doFoo(bar?: { bar: number }): number;

var x = doFoo({ bar: 1 }); // x: number, should be x: string
x = 3; // should error
```
