### ISSUE TITLE
Generic argument inference no longer working for specific case

### ISSUE THREAD

**Issue by MPeloquin** [microsoft/TypeScript#39080]
**TypeScript Version:**  >3.9.2

**Search Terms:** generic argument inference TS2345

**Code**

```ts
declare namespace React {
    type WeakValidationMap<T> = {
        [K in keyof T]?: null extends T[K] ? string : string
    };

    interface FunctionComponent<P = {}> {
        propTypes?: WeakValidationMap<P>;
    }
}

type A<T1> = <T2>() => React.FunctionComponent<T1 & T2>;

function B<T>(_: A<T>) {}

interface C {
    r: String;
}

function myFunction<T2>(): React.FunctionComponent<C & T2> {
    return {};
}

B(myFunction) // Error
B<C>(myFunction) // No error
```

**Expected behavior:** In v3.8.3, the code above did not have any compilation error.

**Actual behavior:** Compilation error TS2345 when I do not explicitly pass the generic type.

**Playground Link:** [Link](https://www.typescriptlang.org/play/?ts=4.0.0-dev.20200614&ssl=24&ssc=17&pln=1&pc=1#code/CYUwxgNghgTiAEA7KBbEBnADlMCBKIOALvAN4CwAUPDfEQJ6YIDqhA1gGpQQCWwURHgHtEAWSiYAPABUAfPAC8ZKrVXwA2gGl4PRPDYh6QgGbxpAXQD8ALiQBXCBHggAHkRCJg6M1vPxL8OhEMLoA5vC2QSGIoSq0AL4A3FRxNLruMMY4CABidohggiIAwkIomCIeRJIACopk8fIU1Go0mDBCmNKMGDbwrFCc3HwCwmIStbLJLTTxVHOUVAxM8ACCMgCM8koyAEyyABQAlIryBMQAdHkFRYil5ZWI1dIb8ABkZvvTVMb5hWPwABCMkOAH1bOs5CdSAsqOkQJlsvBisoZvAYLYAMrBMLTWGUX43AEoejXf4iPaHI62c6FK5-W73CqIKqSFEfaT7VGqOBEOwwPQwvEpSiAg4ksm3I5UYHFQ4ShljI5AA)

Note: I use React, here I only included the minimal React interfaces to reproduce the issue. The issue is also reproducible with React code directly [here](https://www.typescriptlang.org/play/?jsx=2&ssl=16&ssc=2&pln=12&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4BYAKCpgE8wk4BBAHgBUBGAPjgF452AJi4AKAJR8eydDAB0AYVyQAdkmUw29JOw5wAZHDbCK1SpgCuyjMAjK4AIXaiA+gC5mTiQG8qAXypUwOpIUJjojPJwPpRwsXBQ7gDKMFBBAOYm-qYWVjA2diC0AGKW1rZComLu0hgKSrZqGloskQZGPNFx8Ugw5lB2ImA4YADOcO5G+nDyVXAAUokAGrIAogA2SCCNklFUXV1Evf0CNXJFUChpW+pRsndDEKO+XAASSGtrECwA9Key55drjAuCYur5MgFKPYRIUSrl8mIqI55KJYaU8rZEZQgA)

**Comment by weswigham** [comment]
Looks to be caused by https://github.com/microsoft/TypeScript/pull/37261 - the erased signature seems ok, in theory, but because it erases to `any`, `any & T1` becomes just `any`, and we lose the ability to infer to `T1`. If we erase to `unknown` instead, this should work - `unknown` will still behave like `any` in unions still, though (and prevent inference to other union members), which makes me wonder if erasing to a unique anti-any-type-thing might be better - something which evaporates in both unions _and_ intersections, but otherwise behaves `any`ish.

**Comment by davidje13** [comment]
I'm wondering if this is the same issue (also works in 3.8 and fails in 3.9):

```ts
interface Input<V> { v: V }
const inner = <V>(fn: <T extends Input<V>>(t: T) => null) => null;
export default () => inner(<T extends Input<string>>(t: T) => null); // <-- error here
```

Calling `inner<string>(...)` explicitly works.

This shorter example has the same general structure (an argument which is a function with a complicated parameter), but there's too much going on for me to be sure it's the same bug.

**Comment by RyanCavanaugh** [comment]
This behaves as expected now
