### ISSUE TITLE
Question about module augmentation

### ISSUE THREAD

**Issue by hriss95** [Microsoft/TypeScript#10950]
**TypeScript Version:**  1.8.0 and nightly (2.1.0-dev.20160916)

Hello, I've come across the problem of using a definition from DefinitelyTyped using typings to get the latest version and having to augment a module to add API that the folks at DefinitelyTyped rightfully do not want declare as it is internal. However, the module that they use exports using the `export =` assignment and this causes the compiler to complain and I am not sure if that intended or a bug. 
Here is a dummy example to recreate the problem
**Code**

```ts
// File a.d.ts
declare module "foo" {
	function internal(a: number): void;
	namespace internal {
		export var x: number;
		export function f(x: number, y: number): number;
	} 

	export = internal;
}

// File a-extension.d.ts

/// <reference path='./a.d.ts' />

declare module "foo" {
	namespace internal {
		export function f2(x: string): number;
	}
}
```

**Expected behavior:**

Unless this is intended I would expect for this to compile cleanly and be able to use f2 as a member of the exported namespace

**Actual behavior:** 

`a.d.ts(8,2): error TS2309: An export assignment cannot be used in a module with other exported elements.`

Since I want to have the latest version of the definition file I get from DefinitelyTyped I cannot really change anything in that file( `a.d.ts` in the dummy example ) so if there is any other way in which I can do what I want to do with `a-extension.d.ts` please let me know. Thank you in advance for the help :+1:

**Comment by RyanCavanaugh** [comment]
The intended fix is to remove the `namespace internal {` wrapper (the `export =` effectively "unwraps away" the namespace). I believe declaring a new top-level export is an error prior to 2.0, however, so you'll need to wait for that.

**Comment by aluanhaddad** [comment]
I was able to get this to work in 2.1.0-dev.20160916 by removing the `namespace internal {` from the augmentation file as @RyanCavanaugh said and also changing
```TypeScript
/// <reference path="./a.d.ts" />
```
to
```TypeScript
import * as foo from 'foo';
```

**Comment by hriss95** [comment]
@aluanhaddad I am not sure I understand that. Could you please paste the whole snippet of code for `a-extension.d.ts` ?

**Comment by aluanhaddad** [comment]
@hriss95
_a-extensions.d.ts_
```TypeScript
import * as foo from "foo";

declare module "foo" {
    export function f2(x: string): number;
}
```
_foo-consumer.ts_
```TypeScript
import * as foo from 'foo';

const bar = foo.f2(foo.f(foo.x, foo.x).toString());
```

Note this will not work this ~1.8.0 and was tested with 2.1.0-dev.20160916
