### PR TITLE
Always make a new jsxAttributes type, dont reuse emptyObjectType

### LINKED ISSUE #22796: TSX arguments type with index signature does not allow for elements without attributes.
**TypeScript Version:**  2.8.0-dev.20180322

**Search Terms:** 
jsx 
jsx type not assignable 
jsx attributes
tsx type not assignable 
tsx attributes
tsx index signature 

**Code**

See entire example here: https://github.com/nicojs/typescript-issue-jsx-attributes-not-assignable

```ts
// global.d.ts
declare namespace JSX {
    type Element = string;
}
```

```ts
// elements.ts
/// <reference path="./globals.d.ts" />
type AttributeValue = number | string | Date | boolean;

export interface Attributes {
    [key: string]: AttributeValue;
}
export function createElement(name: string, attributes: Attributes | undefined, ...contents: string[]) {
    return name;
}
```

```tsx
// test.tsx
import  * as elements from './elements';

function Button(attributes: elements.Attributes | undefined, contents: string[]) {
    return '';
}
const b = <Button></Button>
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "jsxFactory": "elements.createElement",
    "jsx": "react"
  }
}
```

**Expected behavior:**

No compiler error

**Actual behavior:**

```
test.tsx(7,11): error TS2322: Type '{}' is not assignable to type 'Attributes | undefined'.
  Type '{}' is not assignable to type 'Attributes'.
    Index signature is missing in type '{}'.
```

*Note:* This did work in typescript 2.6.

**Playground Link:** 

Sorry, as this bug spans multiple files, I wasn't able to create a playground link. However, you can reproduce it like this:

```
git clone git@github.com:nicojs/typescript-issue-jsx-attributes-not-assignable.git
cd typescript-issue-jsx-attributes-not-assignable
npm i
npx tsc
```

**Related Issues:** none that I could find.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #22796

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -15392,7 +15392,7 @@ namespace ts {
             if (hasSpreadAnyType) {
                 return anyType;
             }
-            return typeToIntersect && spread !== emptyObjectType ? getIntersectionType([typeToIntersect, spread]) : (typeToIntersect || spread);
+            return typeToIntersect && spread !== emptyObjectType ? getIntersectionType([typeToIntersect, spread]) : (typeToIntersect || spread === emptyObjectType ? createJsxAttributesType() : spread);
```
Comment (sandersn) [inline src/compiler/checker.ts]: can you break this into 3 lines? There might be a more understandable formulation, too, since you're dealing with two related predicates.
