### ISSUE TITLE
TS 5 Regression. tsconfig extends stop resolving references to node_modules

### ISSUE THREAD

**Issue by Vidda777** [microsoft/TypeScript#53314]
# Bug Report
### 🔎 Search Terms

TS 5, tsconfig, extends, node modules

### 🕗 Version & Regression Information

5.0.2

In latest stable build, 4.9.5, tsconfig extends resolve correctly references to libraries on node modules. However, after trying out 5.0.2 it has stop working

- This changed between versions 4.9.5 and 5.0.2

### ⏯ Playground Link

No Playground, I quickly check and there is no support for tsconfig, package.json,...

### 💻 Code

No code, it's just configuration. Having a package.json declaring

```
 "devDependencies": {
    "@mylibrary/commons": "1.0.0",
    "typescript": "5.0.2"
  }
```

and a tsconfig with:
`"extends": "@mylibrary/commons/configs/tsconfig.backend.json",`

### 🙁 Actual behavior

The command `tsc --build` finish with error:

```
tsconfig.json:2:14 - error TS6053: File '@mylibrary/commons/configs/tsconfig.backend.json' not found.

2   "extends": "@mylibrary/commons/configs/tsconfig.backend.json",

```

### 🙂 Expected behavior

The command `tsc --build` finish correctly.

**Comment by ilogico** [comment]
This is most likely because `@mylibrary/commons` has an `exports` field on package,json without exporting the file.

**Comment by jakebailey** [comment]
I don't think we consider `exports` for `tsconfig`, just paths. But, I could be wrong.

I think what we need is the layout of whatever `@mylibrary/commons` is (plus maybe package.json). Bascially, a minimal repro, as this issue isn't enough.

**Comment by ilogico** [comment]
The reason I said is because I hit this problem when upgrading to 5.0 and I fixed it by adding an entry to the `exports` map.

**Comment by jakebailey** [comment]
Oh, very interesting!

**Comment by RyanCavanaugh** [comment]
I think this is a bug, AFAIK `extends` lookups should always be done as CJS lookups. Probably we'll have to revisit that logic at some point...

**Comment by ilogico** [comment]
Subpath exports are not specific to ESM.
In fact, I would say ignoring `exports` was the bug, even if fixing it is a breaking change.

**Comment by ilogico** [comment]
And considering this to be a bug and "fixing" it is also a breaking change.

**Comment by ilogico** [comment]
I don't want to discuss the semantics of breaking changes. Of course I accept that fixing bug might be a desirable breaking change, that was my initial point.
I think it's reasonable to assume that TS would use the same lookup algorithm as NodeJS and that everything else is a bug, a quirk, non-standard behaviour or whatever you want to call it. But if you think it's more important to keep the previous behaviour, I would say that's reasonable as well.

But maybe there's a middle ground where the lookup is done in the standard way (looking at the exports field) and then falling back to the directory structure as it did before.

**Comment by ilogico** [comment]
I just saw this is actually configurable and described in the release notes: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#resolvepackagejsonexports

**Comment by lukeshiru** [comment]
IDK if this is useful for the conversation and for debugging, but I had my `exports` field with this property set for a while now:

```json5
"exports": {
  // ...
  "./*.json": "./lib/*.json"
  // ...
}
```

And I still get the "File not found" error when trying to import it from other packages, which indeed is a regression from my point of view, but also indicates that the fix isn't "just using exports," because the "*" syntax [is valid](https://nodejs.org/api/packages.html#packages_package_entry_points), and also having to specify file by file in the exports field is kinda unrealistic.

Hope I'm adding something useful to the conversation and this isn't just unwanted noise.

**Comment by mike-lischke** [comment]
I just upgraded to TS 5 and found the same issue with one my own node packages ([antlr4-c3 repo](https://github.com/mike-lischke/antlr4-c3, [npm](https://www.npmjs.com/package/antlr4-c3)). With TS 5 I now get the error 

> Cannot find module 'antlr4-c3' or its corresponding type declarations.ts(2307)

Needless to say that I did not change any bit in the project where I'm using the node package. Just upgrading to TS 5 broke the import.

I played a bit with other node module resolution settings, but nothing helped. What sticks out when looking in the bundled node package is that there's no index.js file in the root folder. All the code is in the `out/` folder.

**Comment by jakebailey** [comment]
@mike-lischke This issue is about tsconfig's extends clause. Your issue is unrelated; please file a separate issue.

**Comment by Vidda777** [comment]
Hi, sorry for not answering sooner. What @ilogico said seems reasonable as a workaround, adding the config file as an export entry in the package.json of the library. We don't have it there and maybe this is the way to enforce it to be "exportable". Thanks for the tip.

However, the current TS 5.0.2 behaviour is a regression to what previous 4.x did. So here's the point, as I didn't see a 5.0 changelog announcing this as a breaking change (and the corresponding how-to fix), I assume this is a legit regression bug. 

Thanks to all who have contributed to the post. Sorry if I didn't add a fully reproducible environment, I though it was straighforward case. 

Anyway, here's the part of the package.json and the capture of the library structure
```
"exports": {
    ".": {
      "import": "./dist/mjs/src/main/index.js",
      "require": "./dist/cjs/src/main/index.js"
    },
    "./configs/jest.config.js": {
      "require": "./configs/jest.config.js"
    },
    "./configs/.eslintrc.backend.js": {
      "require": "./configs/.eslintrc.backend.js"
    },
    "./configs/.prettierrc.js": {
      "require": "./configs/.prettierrc.js"
    }
  },
```
![image](https://user-images.githubusercontent.com/16993908/226265394-5cced80a-aa6f-43a3-8a99-3f051278fc78.png)

**Comment by jakebailey** [comment]
> I assume this is a legit regression bug.

Yes, note the label on the issue.

**Comment by andrewbranch** [comment]
It looks like the current behavior was accepted as being intentional in https://github.com/microsoft/TypeScript/issues/48665, and implemented in https://github.com/microsoft/TypeScript/pull/50955. Are we wanting to reconsider that decision, or did we just forget to mark it as a breaking change?

**Comment by andrewbranch** [comment]
Yeah, it looks like the exports pattern trailer feature flag is just missing.

**Comment by andrewbranch** [comment]
We decided this was intentional, minus the wildcard issue, which I’ll put up a fix for shortly. If a package wants to make its tsconfig.json available for extending, and has an `"exports"` in its package.json, it needs to make sure the tsconfig is reachable via those `"exports"`.

**Comment by barca-reddit** [comment]
> We decided this was intentional, minus the wildcard issue, which I’ll put up a fix for shortly. If a package wants to make its tsconfig.json available for extending, and has an `"exports"` in its package.json, it needs to make sure the tsconfig is reachable via those `"exports"`.

Hello. Apologies if this is a silly question, but is this fix for wildcard exports going to be part of Typescript 5.0.3? I checked the milestones page for 5.0.3 and 5.1.0 and it wasn't part of it.

I also tested the fix with `typescript@next`, but I was still getting the same error as before:

```js
// package.json
{
    "name": "@repo/config",
    "exports": {
        "./*.json": {
            "require": "./typescript/*.json"
        }
    }
}

// tsconfig.json (elsewhere in the monorepo)
{
    "extends": "@repo/config/typescript/tsconfig.browser.json",
}
// ❌ File '@repo/config/typescript/tsconfig.browser.json' not found.
```

Essentially all I am asking is when is this going to be available in nightly or main versions of TS?

Cheers!

**Comment by barca-reddit** [comment]
> If it's not working in nightly, then that's a problem.

Apologies for the false alarm. After spending some more time to setup everything from scratch on a clean repository, I got the nightly version to work correctly with wildcards, **so the fix is indeed working**.

> I just had the bot open a PR to pull the fix back into 5.0, since I think we wanted that.

Just one quick question if you don't mind - if I understand correctly, this means that when the next version of Typescript releases (5.0.3), this fix will be included in it, and until then I can use nightly versions?

Cheers!

**Comment by jakebailey** [comment]
If we take it, 5.0.3.

**Comment by barca-reddit** [comment]
> If we take it, 5.0.3.

I am not entirely certain what to "take it" means, but nevertheless I appreciate the response and your help. Will just be keeping an eye on the release notes.

Cheers again! :+1:

**Comment by jakebailey** [comment]
See #53557. @DanielRosenwasser 

"If" was a little too loose; we definitely wanted this to be backported to 5.0, per design meeting discussion. We just have to merge the cherry-pick before release.

**Comment by naftalimurgor** [comment]
Still experiencing the same issue. Was this fully resolved?

**Comment by kirillgroshkov** [comment]
> Still experiencing the same issue. Was this fully resolved?

Yes, we also noticed the regression in 5.3.2 (while it was working in 5.2.2).

**Comment by jakebailey** [comment]
The original issue here is most definitely fixed. If you are having a problem in a recent release, please file a new issue.

If you are using ts-node, maybe you are seeing https://github.com/microsoft/TypeScript/issues/56492.

**Comment by kirillgroshkov** [comment]
> If you are using ts-node, maybe you are seeing #56492.

It turned out to be exactly that, thank you for the pointer 🙏

**Comment by milon27** [comment]
yes facing the same issue

**Comment by RyanCavanaugh** [comment]
Please open a new issue with repro steps if you're having a problem
