### ISSUE TITLE
property accessor creates intersection type instead of union

### ISSUE THREAD

**Issue by simonhaenisch** [microsoft/TypeScript#31694]
**TypeScript Version:**  3.5.1 (also happens with `@next`)

**Search Terms:** ternary, ternary intersection/union, property accessor intersection/union

**Code**

```ts
interface FooBar {
  foo: string;
  bar: number;
}

const set = (foobar: FooBar, key: 'foo' | 'bar', value: string) => {
  foobar[key] = key === 'foo' ? value : Number(value);
};
```

or

```ts
class FooBar {
  foo?: string;
  bar?: number;

  set(key: 'foo' | 'bar', value: string) {
    this[key] = key === 'foo' ? value : Number(value);
  }
}
```

**Expected behavior:**

Works (it did up to version 3.4.5).

**Actual behavior:**

An intersection type is inferred for `foobar[key]` (or `this[key]`), however I think it should be a union type.

```
index.ts:7:3 - error TS2322: Type 'string | number' is not assignable to type 'string & number'.
  Type 'string' is not assignable to type 'string & number'.
    Type 'string' is not assignable to type 'number'.

7   foobar[key] = key === 'foo' ? value : Number(value);
    ~~~~~~~~~~~
```

```
index.ts:6:3 - error TS2322: Type 'string | number' is not assignable to type 'undefined'.
  Type 'string' is not assignable to type 'undefined'.

6   this[key] = key === 'foo' ? value : Number(value);
    ~~~~~~~~~
```

**Playground Link:** 

Useless because this used to work up to version 3.4.5 (and the playground is stuck at version 3.3.3).

**Related Issues:**

Maybe #9239

If I use an if/else instead of the ternary operator, it works because it's easier to figure out the type of `this[key]`:

```ts
if (key === 'foo') {
  this[key] = value;
} else {
  this[key] = Number(value);
}
```

**Comment by krryan** [comment]
Can narrow the versions down here more: this worked correctly in `3.5.0-dev.20190523` and fails in `3.5.0-dev.20190525`.

**Comment by jack-williams** [comment]
This is caused by #30769, and I think this is working as intended.

An intersection is inferred for `this[key]` because it occurs in a write position, and therefore you must be able to safely write to _all_ possible keys denoted by `key`. 

The narrowing you apply to `key` occurs in the RHS expression of the assignment, and is therefore invisible to the assignment itself. The checker simply sees the type of the RHS expression which is `string | number`.

The reason the `if` works is because the narrowing of `key` contains the assignment itself. At the point of the assignment `key` will have been narrowed to a single key and therefore you know precisely what value is safe to assign - there is no need to be conservative and assume you could write to all possible keys.

**Comment by krryan** [comment]
Then this is a huge problem, because it’s “sound” and “conservative” to the point that we can’t use it.
We have a generic function that takes something like `<In extends { kind: string }, Out extends { kind: string }, OutKind extends Out['kind']>(in: In, handle: (value: { kind: In }) => Out[], outKinds: OutKind[])`. The whole point of the constraint is to ensure that the final array actually covers the result of the callback function. But now `Out['kind']` is being treated as an impossible intersection of strings, and no possible value can be substituted there. We can’t control TS seeing this as RHS or LHS. We can’t even cast something in a useful way that would maintain TS checking things for us.

**Comment by simonhaenisch** [comment]
@jack-williams thanks for explaining, that makes sense.

> The narrowing you apply to `key` occurs in the RHS expression of the assignment, and is therefore invisible to the assignment itself.

So, the problem is that the expression returns a union type `string | number`, whereas it should return something like `string if key === 'foo' | number if key === 'bar'`, which the assignment could then take into account. Doesn't sound like it's easy to implement though.

BTW is it expected to have breaking changes in minor version changes? Then I need to read the changelog more carefully from now on 🤓

**Comment by nmain** [comment]
> BTW is it expected to have breaking changes in minor version changes? Then I need to read the changelog more carefully from now on 🤓

See https://github.com/Microsoft/TypeScript/issues/14116

**Comment by jack-williams** [comment]
Those two signatures are significantly different, and the error in the first is warranted. 

The first says that the `OutKind` is assignable to the property `kind` in `Out`, but the converse is not necessary true. For example: take `Out = { kind : "a" }` and `OutKind = never`. The resulting array `Outkind[]` must be the empty array that you can never write to.

The second says that `Out` is assignable to the type `{ kind: OutKind }`, and implicitly `Out['kind']` is assignable to `OutKind`.

**Comment by jack-williams** [comment]
@simonhaenisch 

> So, the problem is that the expression returns a union type string | number, whereas it should return something like string if key === 'foo' | number if key === 'bar' (or maybe something more like string if key === 'foo' else number), which the assignment could then take into account. Doesn't sound like it's easy to implement though.

Yes exactly! You would need a dependent type or stronger reasoning with conditional types.
