### ISSUE TITLE
Unable to read properties off object spread in generic function parameter (regression with 4.6.1-rc)

### ISSUE THREAD

**Issue by danvk** [microsoft/TypeScript#47865]
# Bug Report

I noticed a regression between TypeScript 4.6.0-beta and 4.6.1-rc in my repo where parameters to generic functions that use object spread sometimes get an unusable type.

### 🔎 Search Terms

- object spread
- 4.6.1-rc

### 🕗 Version & Regression Information

- This changed between versions 4.6.0-beta and 4.6.1-rc.

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhAIFEA8BcCcCGBjW4AOikFsDO4AzeAe23EQDtwBTadea3fTWAC3AApqA6Ac2-AByYLlgBXACbUKsXMABcoydNgBJCYICUAkMACwAKFrpi8NLACe6alDhJUAJWJjY1AApZEeADwAVGnDSEvii8ACWFLwAfOAAvOChEbwBrhTB4L6G4OAA-OAO1MimEt6JkQA0CQhJUVng8hkpQfgABgAkAN4RBNTw4AD6AMqwWLAAvvKd3b3gHjhjwFMUPX0FomMtdXkdANoA1uARs55kAD7ge9QWxAS2CCiwTi7uJ7jea7BRALoNZbxjdQa-loqXS7S6yxmQxGZgmSxWx3mmwM2W2+0OVDmXh+VXCkQBKPq4A6YwA3IZDFJkAAbLA2AhiCioMLEKi8aiwPxNNIhaqRKIcOosVhA8p1ViUCTU3oNDiYHC4Bowe6OZyuLE+XxRTRxGIAN2IYQkYoMmgaBqN5IMhnZsA4wmFCgIxGIwFgrvkACMsIJKhwOs7iJVuCHcNSxLxcGMdbEYh06kUKKJid74GM4glw5HSdlgMBwMQDkdfINwAAWbgANm4AAYALSejmIcCelzgCjENDF0sV6sARjr8GQCdZuGI0u41OIvH9qejVvnFIMtvtwEd8kDbo9qd9mYj+FjxJHSbQHTnGbD+5z4DzBaLVE9ndYx7HE6nM7PWEXBm-QA)

### 💻 Code

(see comment below for a simpler repro: https://github.com/microsoft/TypeScript/issues/47865#issuecomment-1039290983)

```ts
/** Extract params from an express path (e.g. '/students/:studentId'). */
export type ExtractRouteParams<T extends string> = string extends T
  ? Record<string, string>
  : T extends `${infer _Start}:${infer Param}/${infer Rest}`
  ? {[k in Param | keyof ExtractRouteParams<Rest>]: string}
  : T extends `${infer _Start}:${infer Param}`
  ? {[k in Param]: string}
  : {};

declare function get<T extends string>(
  path: T,
  handler: (params: ExtractRouteParams<T>) => void,
): void;

get('/path/:foo/to/:bar', ({foo, ...slugs}) => {
  const {bar} = slugs;  // ok in TS 4.6.0-beta but not in TS 4.6.1-rc
  console.log({bar});
});

get('/path/:foo/to/:bar', slugs => {
  const {bar} = slugs;  // ok in both
  console.log({bar});
});
```

### 🙁 Actual behavior

Using object spread in a function parameter produces an unusable type in TS 4.6.1-rc.

The type of `slugs` in the first example is:

     slugs: { bar: string; }

in TypeScript 4.6.0-beta but:

    slugs: Omit<ExtractRouteParams<T>, "foo">

in TypeScript 4.6.1-rc.

These are both the same (assuming `T = "/path/:foo/to/:bar"`) but the latter doesn't let me read any properties off of it.

### 🙂 Expected behavior

I should be able to read `bar` off of `slugs`.

**Comment by danvk** [comment]
Here's a simpler repro that doesn't involve template literal types. This (correctly) passes the type checker with TS 4.5.5 but raises a spurious error with 4.6.1-rc.

```ts

interface Slugs {
  foo: string;
  bar: string;
}

function call<T extends object>(obj: T, cb: (val: T) => void) {
  cb(obj);
}

declare let obj: Slugs;
call(obj, ({foo, ...rest}) => {
  console.log(rest.bar);
  //               ~~~ Property 'bar' does not exist on type 'Omit<T, "foo">'. ts(2339)
});
```

**Comment by RyanCavanaugh** [comment]
Bisected to #47337

**Comment by RyanCavanaugh** [comment]
@gabritto seems like we're failing to assign the inferred type to `rest` here; `T` shouldn't be appearing at all
