### ISSUE TITLE
types field in package.json exports doesn't work

### ISSUE THREAD

**Issue by tjx666** [microsoft/TypeScript#51862]
# Bug Report

### 🔎 Search Terms

types, package.json, exports, import entry points

### 🕗 Version & Regression Information

`typescript`: `^4.9.4`

Reproduce:

1. `git clone https://github.com/tjx666/ts-exports-development`
2. `git reset --hard 70706c6845b0d8c1e55e4ab53619b91c77bcc37d`
3. `pnpm install`
4. `cd packages/app`
5. `tsc --noEmit`

### ⏯ Playground Link

[Reproduce Repo](https://github.com/tjx666/ts-exports-development/tree/d0eb57cdf0c1f8cdb5260dc2f6f9083479046d50)

### 💻 Code

monorepo project structure:

```txt
.
├── node_modules
│   ├── tsup -> .pnpm/tsup@6.5.0_typescript@4.9.4/node_modules/tsup
│   └── typescript -> .pnpm/typescript@4.9.4/node_modules/typescript
├── package.json
├── packages
│   ├── app
│   │   ├── node_modules
│   │   │   └── tools -> ../../tools
│   │   ├── package.json
│   │   ├── src
│   │   │   └── index.ts
│   │   └── tsconfig.json
│   └── tools
│       ├── dist
│       │   ├── index.d.ts
│       │   ├── index.js
│       │   └── index.mjs
│       ├── package.json
│       ├── src
│       │   └── index.ts
│       └── tsconfig.json
├── pnpm-lock.yaml
└── pnpm-workspace.yaml
```

In packages/app/src/index.ts

```typescript
// error: Cannot find module 'tools' or its corresponding type declarations
import { add } from 'tools';

console.log(add(2, 4));
```

In packages/tools/src/index.ts

```typescript
export function add(a: number, b: number) {
    return a + b;
}
```

the package.json of package tools

```json
{
    "name": "tools",
    "version": "1.0.0",
    "description": "",
    "scripts": {
        "build": "tsup src/index.ts --dts --format esm,cjs"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "exports": {
        ".": {
            "types": "./dist/index.d.ts",
            "import": {
                "development": "./src",
                "default": "./dist/index.mjs"
            },
            "require": {
                "development": "./src",
                "default": "./dist/index.js"
            }
        }
    }
}
```

### 🙁 Actual behavior

![image](https://user-images.githubusercontent.com/41773861/207024426-aa1d639a-1bab-4370-bf1f-02b6319a2749.png)

### 🙂 Expected behavior

No error

**Comment by UchihaVeha** [comment]
Same problem after the update from 4.9.3 to 4.9.4. It looks like it happened with monorepo. I am using yarn 3.3.0 workspaces

**Comment by andrewbranch** [comment]
You are using `"moduleResolution": "node"` which does not support package.json `exports`. The value `"node"` represents the resolution of Node 10, which never included package.json `exports` support. (I recently renamed this value to `"node10"` in #51901.) For modern Node, you need to use `"module": "node16"` or `"nodenext"`, which will also set the correct `moduleResolution` option that supports package.json `exports` and other newer resolution features.
