### PR TITLE
Improved subtype compatibility rules for types of object literals

### LINKED ISSUE #1446: No common supertype between {optional, optional} and {required, absent}
We made the change that an object type with a missing property cannot be a subtype of an object with an optional property. This made subtype choose better results in some cases, because it fixed cases of nonantisymmetry in the subtype relation. But now there are cases where you get an error in type argument inference because a pair of type has no common supertype.
```ts
interface I {
    a?: string;
    b?: string;
}

var i: I;

function foo<T>(p1: T, p2: T) { }

foo(i, { a: "" }); // Error because neither type is a supertype of the other
```

One interpretation is that in this case `I` should be the common supertype. To make this happen, we would say that instead of a missing property being a supertype of an optional, it is a subtype. In this view, missing and required are both specific cases of optional, and optional is a supertype of both.

Another fix is a change in type argument inference. If finding a common supertype does not yield a result, we can have another round where we use assignability. In the above example, this would not produce an error, since the object literal is assignable to `I`. 

The issue here is that it may lead to results that depend on the order of the arguments. Both would select the first type in the following case:
```ts
interface I1 {
   a?: string
}
interface I2 {
   b?: string
}
var i1: I1, i2: I2;
foo(i1, i2);
```
Both proposed fixes would choose I1 because it is first, whereas now we at least get an error consistently no matter the argument order.

### LINKED ISSUE #1448: Contextually typed object literal cannot be assigned if its indexer is undefined and it is also missing some other property
```ts
interface Foo {
    [s: string]: string;
    b: string;
}
<Foo>{ } // Error, neither type is assignable to the other
```

This is similar to #1447, but is a breaking change because of how we type indexers in object literals. It used to be that that the contextual index type seeded the type for the object literal's indexer, but now it does not (when we introduced union types). It now has the type undefined, which means it is only assignable to (not from) the contextual indexer. This exacerbates the problem of #1447 when indexers are involved.

### LINKED ISSUE #1655: Incompatible change in indexer type inference
Value type of indexers is ending up now as `undefined` when implicitly created from another type on the RHS as in the following test case:

```ts
var bar:{ [key:string]: boolean; };
var foo = bar = {};
foo['a'] = true; // error TS2323: Type 'boolean' is not assignable to type 'undefined'.
```

**1.3: OK**
**master: Error on line 3**

Bisect:

```
83d9aed005502523ac3ef7198d92c51c8f2bb211 is the first bad commit
commit 83d9aed005502523ac3ef7198d92c51c8f2bb211
Author: Anders Hejlsberg <andersh@microsoft.com>
Date:   Mon Oct 13 06:56:15 2014 -0700

    Correct contextual typing with union types

:040000 040000 d3d0d2e65cdd5b895f2bf257e6256dad815be97c a93480ba990a856a4f585a4d57c80a0f533c087f M	src
```

Also please let me know which of my terminology is horribly broken in this description so I can be more precise in the future :)

### LINKED ISSUE #1723: Overload on constants requires cast for resolution
Hi,

**TS Version**: 1.4

In the following the first call to `doFoo` fails to compile because the overload resolution algorithm picks the general case:

```TypeScript
interface Bar {
    bar?: number;
    baz?: string;
}

interface Foo {
    foo(): string;
}

declare function doFoo(kind: 'Foo', bar?: Bar): Foo;
declare function doFoo(kind: string, bar: any): {}

var x = doFoo('Foo', { bar: 1 });
x.foo(); // Error: Property 'foo' does not exist on type '{}'.

var y = doFoo('Foo', <Bar> { bar: 1 });
y.foo(); // Okay
```

This is a breaking change because it used to work without the need for the cast in 1.3.

I feel this should compile because `{ bar: 1 }` is compatible with the `Bar` interface.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #1446.
Fixes #1448.
Fixes #1655.
Fixes #1723.

With this PR the type of an object literal has increased subtype compatibility until it is widened, similar to how we treat null and undefined in expressions.

In #919 we tightened subtyping rules such that optional properties are required to be present in subtypes. This change is desirable because it makes subtyping more selective to the benefit of union types and overload resolution.

However, #919 is too strict in certain situations involving object literals. For example, the object literal `{ a: "foo" }` is not considered a subtype of `{ a: string; b?: string; }` because it is missing the optional member `b`. That just doesn't seem right. But at the same time it is entirely meaningful to say that `{ a: string }` is a supertype (and not a subtype) of `{ a: string; b?: string; }`.

The interesting fact here is that when an object literal omits optional properties, *we can say for certain those optional properties aren't present*, and it is therefore safe to consider it a subtype. But once we infer a variable's type from an object literal, that variable might acquire additional properties that we don't know about and we need to be stricter.

And that's the gist of this PR: The type of an object literal is a subtype of a given type T even when it is missing optional properties from T, but once the object literal type is widened to a regular type that is no longer the case.

An example:

```typescript
interface Item {
    name: string;
    description?: string;
}

declare function foo(item: Item): string;
declare function foo(item: any): number;

var x1 = foo({ name: "Sprocket" });  // x1 of type string
var x2 = foo({ name: "Sprocket", description: "Bumpy wheel" });  // x2 of type string
var x3 = foo({ name: "Sprocket", description: false });  // x3 of type number

var o1 = { name: "Sprocket" };
var o2 = { name: "Sprocket", description: "Bumpy wheel" };
var o3 = { name: "Sprocket", description: false };

var y1 = foo(o1);  // y1 of type number
var y2 = foo(o2);  // y2 of type string
var y3 = foo(o3);  // y3 of type number
```
Note the difference between `x1` and `y1`. In the `x1` case, the object literal argument is considered a subtype of `Item`. It omitted `description` so we know for sure `description` isn't anything else. But in the `y1` case, `o1` has type `{ name: string }` and might very well have a `description` property that isn't of type string. So we can't consider it a subtype.

The PR fixes #1446 and provides a better solution to #1723 (effectively removing the fix in #1774). It also fixes #1448 and #1655 which were caused by incorrect tracking of null and undefined types in unwidened types.

### CODE REVIEW

File: tests/baselines/reference/indexer2.errors.txt [hunk 1]
```diff
@@ -1,20 +0,0 @@
...
-
-
-==== tests/cases/compiler/indexer2.ts (1 errors) ====
-    interface IHeapObjectProperty {}
-    interface IDirectChildrenMap { 
-            hasOwnProperty(objectId: number) : boolean; 
-            [objectId: number] : IHeapObjectProperty[]; 
-    }    
-    var directChildrenMap = <IDirectChildrenMap>{}; 
-                            ~~~~~~~~~~~~~~~~~~~~~~
```
Comment (RyanCavanaugh) [inline tests/baselines/reference/indexer2.errors.txt]: :+1: good change here

**Comment by JsonFreeman** [comment]
To clarify, are we keeping change #1774? I think it would only make a difference for object literals returned from contextually typed function expressions.

File: src/compiler/types.ts [hunk 2]
```diff
@@ -1283,12 +1283,15 @@ module ts {
         Union               = 0x00004000,  // Union
         Anonymous           = 0x00008000,  // Anonymous
         FromSignature       = 0x00010000,  // Created for signature assignment check
-        Unwidened           = 0x00020000,  // Unwidened type (is or contains Undefined or Null type)
+        ObjectLiteral       = 0x00020000,  // Originates in an object literal
+        ContainsUndefined   = 0x00040000,  // Type is or contains Undefined or Null type
+        ContainsLiteral     = 0x00080000,  // Type is or contains object literal type
```
Comment (JsonFreeman) [inline src/compiler/types.ts]: ContainsObjectLiteral

File: src/compiler/types.ts [hunk 3]
```diff
@@ -1283,12 +1283,15 @@ module ts {
         Union               = 0x00004000,  // Union
         Anonymous           = 0x00008000,  // Anonymous
         FromSignature       = 0x00010000,  // Created for signature assignment check
-        Unwidened           = 0x00020000,  // Unwidened type (is or contains Undefined or Null type)
+        ObjectLiteral       = 0x00020000,  // Originates in an object literal
+        ContainsUndefined   = 0x00040000,  // Type is or contains Undefined or Null type
```
Comment (JsonFreeman) [inline src/compiler/types.ts]: Or null, right?

File: src/compiler/types.ts (hunk 2 above)
Comment (JsonFreeman) [inline src/compiler/types.ts]: Also, why do you need both ObjectLiteral and ContainsLiteral?

File: src/compiler/types.ts (hunk 3 above)
Comment (JsonFreeman) [inline src/compiler/types.ts]: I think null should be part of the name

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -2807,15 +2807,19 @@ module ts {
             }
         }
 
-        function getUnwidenedFlagOfTypes(types: Type[]): TypeFlags {
-            return forEach(types, t => t.flags & TypeFlags.Unwidened) || 0;
+        function getWideningFlagsOfTypes(types: Type[]): TypeFlags {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: It is clear what this does, but please put a comment explaining when it should be called. It would seem very easy to forget to call it.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -3692,12 +3696,13 @@ module ts {
...
                 var result = Ternary.True;
                 var properties = getPropertiesOfObjectType(target);
+                var requireOptionalProperties = relation === subtypeRelation && !(source.flags & TypeFlags.ObjectLiteral);
                 for (var i = 0; i < properties.length; i++) {
                     var targetProp = properties[i];
                     var sourceProp = getPropertyOfType(source, targetProp.name);
                     if (sourceProp !== targetProp) {
                         if (!sourceProp) {
-                            if (relation === subtypeRelation || !(targetProp.flags & SymbolFlags.Optional)) {
+                            if (!(targetProp.flags & SymbolFlags.Optional) || requireOptionalProperties) {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Seems like this should be `&&`. I'm not sure how this was ever working.

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -4104,13 +4105,18 @@ module ts {
...
-                symbol.target = p;
-                if (p.valueDeclaration) symbol.valueDeclaration = p.valueDeclaration;
-                members[symbol.name] = symbol;
+                var propType = getTypeOfSymbol(p);
+                var widenedType = getWidenedType(propType);
+                if (propType !== widenedType) {
+                    var symbol = <TransientSymbol>createSymbol(p.flags | SymbolFlags.Transient, p.name);
+                    symbol.declarations = p.declarations;
+                    symbol.parent = p.parent;
+                    symbol.type = getWidenedType(getTypeOfSymbol(p));
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Use widenedType, you already computed it.

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -4104,13 +4105,18 @@ module ts {
...
+                    symbol.target = p;
+                    if (p.valueDeclaration) symbol.valueDeclaration = p.valueDeclaration;
+                    p = symbol;
+                }
+                members[p.name] = p;
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: What is the actual change here? It seems the check `propType !== widenedType` is the only new thing, but that's just an optimization, right? Or am I missing something

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -5485,7 +5480,9 @@ module ts {
                             }
                         }
                     }
-                    return propTypes.length ? getUnionType(propTypes) : undefinedType;
+                    var result = propTypes.length ? getUnionType(propTypes) : undefinedType;
+                    typeFlags |= result.flags;
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Yes, this is important

**Comment by ahejlsberg** [comment]
@JsonFreeman No, #1774 (and it's funny effects on error reporting) is reverted by this.

File: src/compiler/checker.ts (hunk 6 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Doh!

File: src/compiler/types.ts (hunk 2 above)
Comment (ahejlsberg) [inline src/compiler/types.ts]: The ObjectLiteral flag better enables us to check if a type originated in an object literal (as opposed to contains one).  It replaces the old isTypeOfObjectLiteral function that was kind of convoluted.

File: src/compiler/checker.ts (hunk 5 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: No, it's correct. It says "if the target property is not optional (i.e. if it is a required property) *or* if we require optional properties to be present in the source".

File: src/compiler/checker.ts (hunk 7 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Right, the new thing is the added optimization.

**Comment by JsonFreeman** [comment]
:+1:
