### ISSUE TITLE
Problem with interpreting of union into context

### ISSUE THREAD

**Issue by luboid** [Microsoft/TypeScript#3149]
I am working with 1.5.0-beta

```javascript
export interface IPrcbNumOptions {
    options?: any;
    events?: any;
}

@customAttribute('prcb-num')
@inject(Element)
export default class PrcbNum {
  @bindable options: IPrcbNumOptions|string;
  @bindable value: number|string;

  constructor(element:Element) {
  }

  bind(executionContext, aaa:IPrcbNumOptions|string) {
    if (typeof aaa === 'string') {
      // this is ok
      this.options = JSON.parse(aaa);
    }
    if (typeof this.options === 'string') {
     //error TS2345: Argument of type 'string |IPrcbNumOptions' is not assignable to parameter of type 'string'.  
      //Type 'IPrcbNumOptions' is not assignable to type 'string'.
      this.options = JSON.parse(this.options);
    }
  }
}
```

**Comment by ahejlsberg** [comment]
See #2523.
