### ISSUE TITLE
T[K] not assignable even when it's 'any'

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript#23940]
**TypeScript Version:**  2.9.0-dev.20180430

**Code**

```ts
interface I {
    x: any;
}
type Foo<T extends number> = T;
declare function f<K extends keyof I>(type: K): Foo<I[K]>;
```

**Expected behavior:**

No error.

**Actual behavior:**

```ts
src/a.ts:5:53 - error TS2344: Type 'I[K]' does not satisfy the constraint 'number'.

5 declare function f<K extends keyof I>(type: K): Foo<I[K]>;
```

This was broken by #23768 (fc2f16ca3c85788f1c734454604f103b2dbc4c10): tested that it worked in the commit before it, 4e401ca3616841d3636b8dcbbee9405fdcfaec81 .

Discovered in `ember-data` on DefinitelyTyped.
