### ISSUE TITLE
TS2345 or TS2322 with generics when in multiple modules

### ISSUE THREAD

**Issue by Delagen** [Microsoft/TypeScript#8806]
**TypeScript Version:** 

1.8.10

**Code**

node_modules/module1/test.example.ts
```ts
import {
	Observable
} from "rxjs";

export class ExampleServiceInstance<T> {
	private dataObservable: Observable<T>;

	constructor(data: () => Observable<T>) {
		this.dataObservable = data();
	}

	get data(): Observable<T> {
		return this.dataObservable;
	}

	reset(): Observable<T> {
		return this.dataObservable;
	}
}
```

app/test.ts

```ts
import {
	Observable,
} from "rxjs";

import {ExampleServiceInstance} from "module1/test.example";

declare type ExampleData = Object[];

class ExampleService {
	private service: ExampleServiceInstance<ExampleData>;

	constructor() {
		this.service = new ExampleServiceInstance<ExampleData>(()=>Observable.of(<ExampleData> []));
	}

	get data(): Observable<ExampleData> {
		return this.service.data;
	}

	load(): Observable<ExampleData> {
		return this.service.reset();
	}
}

```

**Expected behavior:**
NO TS errors

**Actual behavior:** 

test.ts 
(13,58): error TS2345: Argument of type '() => Observable<Object[]>' is not assignable to parameter of type '() => Observable<Object[]>'.
  Type 'Observable<Object[]>' is not assignable to type 'Observable<Object[]>'.
    Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
(17,10): error TS2322: Type 'Observable<Object[]>' is not assignable to type 'Observable<Object[]>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
(21,10): error TS2322: Type 'Observable<Object[]>' is not assignable to type 'Observable<Object[]>'.

**Comment by mhegazy** [comment]
looks like the same issue in https://github.com/Microsoft/TypeScript/issues/6496.

**Comment by Delagen** [comment]
I think something not. No multiple declarations, no d.ts files at all

**Comment by Delagen** [comment]
Even rxjs module is resolved to the same in both files

**Comment by mhegazy** [comment]
I do not see how you would get this error if `observable` in both file resolve to the same declaration. can you share the otuput of `tsc --traceResolution` on this sample?

**Comment by Delagen** [comment]
When I upgraded to 1.9.0-dev which support this option (1.8.10 does not support) error gone.

**Comment by Delagen** [comment]
Error when I using ts-loader in webpack with same options.

**Comment by mhegazy** [comment]
looks like an issue for https://github.com/TypeStrong/ts-loader then.
