### ISSUE TITLE
Change in generic behavior between 3.0.1 and >=3.1.1

### ISSUE THREAD

**Issue by chrisbouchard** [Microsoft/TypeScript#27895]
**TypeScript Version:**  3.2.0-dev.20181011
This code worked in 3.0.1, and is broken >=3.1.1.

**Search Terms:**
"is not assignable to type"

**Code**

```ts
export interface Entity {
    id: number | string;
}

export type IdOf<E extends Entity> = E['id'];

export interface EntityState<E extends Entity> {
    ids: IdOf<E>[];
    entities: { [key: string]: E, [key: number]: E };
}


export function getAllEntities<E extends Entity>(state: EntityState<E>): E[] {
    const { ids, entities } = state;
    return ids.map(id => entities[id]);
}

export function getEntity<E extends Entity>(id: IdOf<E>, state: EntityState<E>): E | undefined {
    const { ids, entities } = state;

    if (!ids.includes(id)) {
        return undefined;
    }

    return entities[id];
}
```

For completeness, I'll just mention that I intend for users to create subinterfaces of `Entity` and `EntityState` for their domain types (like `@ngrx/entity`), overriding `id` to be a more restrictive type. This is why the `IdOf` type is important. E.g.,

```ts
interface Task extends Entity {
    id: string;
    due: Date;
    title: string;
}

interface TaskState extends EntityState<Task> {
    // Inherits EntityState#ids as string[]
    currentTask?: string;
}
```

**Expected behavior:**
The code compiles without error.

**Actual behavior:**
```
BUILD ERROR
projects/entity/src/lib/entity-state.utils.ts(13,5): error TS2322: Type '{ [key: string]: E; [key: number]: E; }[E["id"]][]' is not assignable to type 'E[]'.
  Type '{ [key: string]: E; [key: number]: E; }[E["id"]]' is not assignable to type 'E'.
    Type 'Entity' is not assignable to type 'E'.
projects/entity/src/lib/entity-state.utils.ts(23,5): error TS2322: Type '{ [key: string]: E; [key: number]: E; }[E["id"]]' is not assignable to type 'E | undefined'.
  Type 'Entity' is not assignable to type 'E'.
    Type '{ [key: string]: E; [key: number]: E; }[E["id"]]' is not assignable to type 'E'.
      Type 'Entity' is not assignable to type 'E'.
```

**Playground Link:** 
[Playground Link](http://www.typescriptlang.org/play/#src=export%20interface%20Entity%20%7B%0D%0A%20%20%20%20id%3A%20number%20%7C%20string%3B%0D%0A%7D%0D%0A%0D%0Aexport%20type%20IdOf%3CE%20extends%20Entity%3E%20%3D%20E%5B'id'%5D%3B%0D%0A%0D%0Aexport%20interface%20EntityState%3CE%20extends%20Entity%3E%20%7B%0D%0A%20%20%20%20ids%3A%20IdOf%3CE%3E%5B%5D%3B%0D%0A%20%20%20%20entities%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20E%2C%20%5Bkey%3A%20number%5D%3A%20E%20%7D%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Aexport%20function%20getAllEntities%3CE%20extends%20Entity%3E(state%3A%20EntityState%3CE%3E)%3A%20E%5B%5D%20%7B%0D%0A%20%20%20%20const%20%7B%20ids%2C%20entities%20%7D%20%3D%20state%3B%0D%0A%20%20%20%20return%20ids.map(id%20%3D%3E%20entities%5Bid%5D)%3B%0D%0A%7D%0D%0A%0D%0Aexport%20function%20getEntity%3CE%20extends%20Entity%3E(id%3A%20IdOf%3CE%3E%2C%20state%3A%20EntityState%3CE%3E)%3A%20E%20%7C%20undefined%20%7B%0D%0A%20%20%20%20const%20%7B%20ids%2C%20entities%20%7D%20%3D%20state%3B%0D%0A%0D%0A%20%20%20%20if%20(!ids.includes(id))%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20undefined%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20entities%5Bid%5D%3B%0D%0A%7D)

**Related Issues:** 
I did not find any that seemed similar, but I'm also unsure what the actual underlying problem is. I did [ask on StackOverflow](https://stackoverflow.com/q/52798934/4450643), and they suggested I ask here.

**Comment by mattmccutchen** [comment]
Looking into it

**Comment by mattmccutchen** [comment]
This was caused by #26698.  The old behavior to check assignability of the indexed access type `{ [key: string]: E; [key: number]: E; }[E["id"]]` to `E` was to take the base constraint of both the object type and the index type, which gave `{ [key: string]: E; [key: number]: E; }[string | number] = E`, which worked.  The new behavior takes the constraint of the object type, and if there isn't one, jumps straight to the base constraint of the whole indexed access type, so it goes to `Entity` and misses `E`.

**Comment by chrisbouchard** [comment]
Is this considered a regression? Or, if this is the intended new behavior, is there a suggested workaround?
