### ISSUE TITLE
Debug Failure. Did not expect SourceFile to have an Identifier in its trivia

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/TypeScript#28532]
**TypeScript Version:**  3.2.0-dev.20181110

**Search Terms:**
- Debug failure

**Bug**
While editing files in the VS Code codebase using typescript@next, I'm seeing errors like:

```
Err 6692  [14:17:51.720] Exception on executing command {"seq":1371,"type":"request","command":"quickinfo","arguments":{"file":"/Users/matb/projects/vscode/extensions/typescript-language-features/src/languageProvider.ts","line":36,"offset":28}}:

    Debug Failure. Did not expect SourceFile to have an Identifier in its trivia

    Error: Debug Failure. Did not expect SourceFile to have an Identifier in its trivia
        at addSyntheticNodes (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:115874:30)
        at createSyntaxList (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:115890:13)
        at processNodes (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:115853:27)
        at visitNodes (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:16122:24)
        at Object.forEachChild (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:16354:24)
        at SourceFileObject.NodeObject.forEachChild (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:115830:23)
        at createChildren (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:115862:14)
        at SourceFileObject.NodeObject.getChildren (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:115807:56)
        at getTokenAtPositionWorker (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:92632:43)
        at getTouchingToken (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:92619:16)
        at Object.getTouchingPropertyName (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:92611:16)
        at Object.getQuickInfoAtPosition (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:116866:27)
        at IOSession.Session.getQuickInfoWorker (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:124610:62)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123662:61)
        at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125199:88
        at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125190:28)
        at IOSession.Session.executeCommand (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125199:33)
        at IOSession.Session.onMessage (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125221:35)
        at Interface.<anonymous> (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:126479:27)
        at emitOne (events.js:116:13)
        at Interface.emit (events.js:211:7)
        at Interface._onLine (readline.js:282:10)
        at Interface._normalWrite (readline.js:424:12)
        at Socket.ondata (readline.js:141:10)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:250:11)
        at Socket.Readable.push (_stream_readable.js:208:10)
        at Pipe.onread (net.js:594:20)
```

This causes the editor to get out sync. Errors start showing up in unexpected locations and don't go away

Here's a log: [tsserver.log](https://github.com/Microsoft/TypeScript/files/2582877/tsserver.log)

Will look for more compact repo steps.

@DanielRosenwasser I don't think we can't pick up TS 3.2 for vscode insiders until this is addressed

**Comment by andy-ms** [comment]
Looks like there is an earlier error:
```
Cannot read property 'get' of undefined

TypeError: Cannot read property 'get' of undefined
    at resolveModuleNamesReusingOldState (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:86092:92)
    at processImportedModules (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:87374:35)
    at findSourceFile (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:87186:17)
    at processImportedModules (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:87410:25)
    at findSourceFile (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:87186:17)
    at args (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:87043:85)
    at getSourceFileFromReferenceWorker (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:87010:34)
    at processSourceFile (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:87043:13)
    at processRootFile (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:86873:13)
    at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:85886:60
    at Object.forEach (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:223:30)
    at Object.createProgram (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:85886:16)
    at synchronizeHostData (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:116718:26)
    at Object.getProgram (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:116801:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:120764:53)
    at ConfiguredProject.Project.updateGraph (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:120721:42)
    at ConfiguredProject.updateGraph (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:121134:63)
    at Object.updateProjectIfDirty (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:121443:45)
    at ConfiguredProject.Project.getLanguageService (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:120450:28)
    at IOSession.Session.getApplicableRefactors (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:124979:32)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123852:61)
    at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125199:88
    at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125190:28)
    at IOSession.Session.executeCommand (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125199:33)
    at IOSession.Session.onMessage (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125221:35)
    at Interface.<anonymous> (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:126479:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by mjbvz** [comment]
@sheetalkamat Can you please take a look at this

**Comment by mjbvz** [comment]
This is caused by having the [ts-lint plugin](https://github.com/Microsoft/typescript-tslint-plugin) active. Tested with TS 2.0-dev 20181115. The plugin works fine with TS 3.1.4

The first exception I see is:

```
Err 221   [11:56:45.527] Exception on executing command {"seq":31,"type":"request","command":"references","arguments":{"file":"/Users/matb/projects/vscode/extensions/typescript-language-features/src/features/documentHighlight.ts","line":12,"offset":9}}:

    child.getStart is not a function

    TypeError: child.getStart is not a function
        at getTokenAtPositionWorker (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:92909:89)
        at getTouchingToken (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:92894:16)
        at Object.getTouchingPropertyName (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:92886:16)
        at Object.findReferencedSymbols (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:98576:27)
        at Object.findReferences (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:117308:41)
        at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123812:68
        at callbackProjectAndLocation (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123865:13)
        at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123839:24
        at forEachProjectInProjects (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123822:17)
        at combineProjectOutputWorker (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123837:13)
        at combineProjectOutputForReferences (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123795:13)
        at IOSession.Session.getReferences (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:124829:34)
        at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:123975:61)
        at /Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125531:88
        at IOSession.Session.executeWithRequestId (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125522:28)
        at IOSession.Session.executeCommand (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125531:33)
        at IOSession.Session.onMessage (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:125553:35)
        at Interface.<anonymous> (/Users/matb/projects/vscode/node_modules/typescript/lib/tsserver.js:126811:27)
        at emitOne (events.js:116:13)
        at Interface.emit (events.js:211:7)
        at Interface._onLine (readline.js:282:10)
        at Interface._normalWrite (readline.js:424:12)
        at Socket.ondata (readline.js:141:10)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:250:11)
        at Socket.Readable.push (_stream_readable.js:208:10)
        at Pipe.onread (net.js:594:20)
```


[tsserver.txt](https://github.com/Microsoft/TypeScript/files/2586824/tsserver.txt)

**Comment by sheetalkamat** [comment]
looking..

**Comment by sheetalkamat** [comment]
@mjbvz I am unable to repro this. I tried in code-insiders as well as running all the commands that you ran from tsserver manually. I used build from master branch that I built from 6cee7c308039de7f9d89472dd8de47755491f7f5 Which build are you using? I installed `typescript-tslint-plugin` which is   `"version": "0.0.6"`

**Comment by mjbvz** [comment]
I tested on TS 2.0-dev 20181115 with tslint plugin 0.0.6. I'm on Mac OS. This repos with any ts file I've tested in the VS Code source. Just make an edit the introduces an error then undo it.

**Comment by mjbvz** [comment]
I believe I has fixed this with https://github.com/Microsoft/typescript-tslint-plugin/commit/90879e3b3a481f3ba78ab2169678f60a6e8021dd. The fix was to avoid mutating the array of code fixes returned to us and to return a copy instead. 

I do not know why this worked on 3.1.4 and on older versions of 3.2@next, but broke recently. The proper typings for `bind` that come with 3.2 helped to catch this though

**Comment by andy-ms** [comment]
Maybe we should do #16312 to forbid users from mutating arrays we return.
