### ISSUE TITLE
TypeScript 2.5 "unused type parameter" breaks existing code

### ISSUE THREAD

**Issue by benny-medflyt** [Microsoft/TypeScript#18370]
**TypeScript Version:**  2.5.2

**Code**

```ts
type Foo<s> = object;
```

This worked fine in TypeScript 2.4, but causes the following error in 2.5.2:

    error TS6133: 's' is declared but never used.

This change in TypeScript is breaking massive amounts of code that use phantom type parameters. And there doesn't seem to be any workaround.

**Comment by RyanCavanaugh** [comment]
You can turn off no unused variables, or name them with a leading underscore (`Foo<_s>` will not cause an error).

**Comment by benny-medflyt** [comment]
I tried adding a leading underscore:

```ts
type Foo<_s> = object;
```

Still causes the same error (`'s' is declared but never used.`)

Switching off `noUnusedLocals` does work, but at the great expense of loosing that feature

**Comment by gcnew** [comment]
I'm interested in what you use phantom type parameters for, as they are not enforced by the compiler. If a type parameter is not referenced in the type's body, it's not considered during checking.

**Comment by benny-medflyt** [comment]
> I'm interested in what you use phantom type parameters for, as they are not enforced by the compiler. If a type parameter is not referenced in the type's body, it's not considered during checking.

You are right, it turns out that the code in the style above was actually from some older experiments with phantom types, that we don't actually use.

The way we actually use phantom types with correct type checking is by adding a dummy field:

```ts
export class Q<s> {
    protected dummy: [Q<s>, s];
}
```

**Comment by RyanCavanaugh** [comment]
Logged  #18420
