### ISSUE TITLE
Linux and mac problem with --watch option with a tsconfig.json « "include": ["app/**/*.ts"] » 

### ISSUE THREAD

**Issue by JulioJu** [Microsoft/TypeScript#21444]
**TypeScript Version:** 2.8.0-dev.20180127 or 2.6.2

**OS:** Linux x86_64

**Node Version:** 9.4.0

**Search Terms:** 
* "is:issue is:open watch"

**Steps to reproduce:**

1. `mkdir ~/essaiTS && cd $_`

2 . ~/essaiTS/tsconfig.json
```json
{
    "include": [
        "app/**/*.ts"
    ]
}
```
3. ~/essaiTS/app/file.ts
```typescript
console.log('aaa');
```
4. ` node node_modules/typescript/bin/tsc --watch --listEmittedFiles`
    * We could see a new file ~/essaiTS/app/file.js with:
```javascript
console.log('aaa');
```
5.  ~/essaiTS/app/file.ts
```typescript
console.log('aaa');
console.log('bbb');
```
**Expected behavior:**
At  ~/essaiTS/app/file.js. 
we must have:
```javascript
console.log('aaa');
console.log('bbb');
```
**Actual behavior:**
As in step 4., we have instead only:
```javascript
console.log('aaa');
```
With TypeScript 6.2 we could see in terminal : 
```
3:14:46 PM - File change detected. Starting incremental compilation...
3:14:47 PM - Compilation complete. Watching for file changes.
```
~~With TypeScript 2.8.0-dev.20180127 there is no messages.~~ (error on my part, with TypeScript 2.8.* console is just cleared: see my following comment.)
**Notes:**
* No problems with compilation option `--watch` if essaiTS is in folder /tmp. 
    To test you could use command line: `cp -R ~/essaiTS /tmp && cd /tmp/essaiTS && node node_modules/typescript/bin/tsc --watch --listEmittedFiles`, then edit file /tmp/essaiTS/app/file.ts.
* There is no problems with option `--watch` for files in  ~/essaiTS/app/folder/.

**Related Issues:**
Maybe: https://github.com/Microsoft/TypeScript/issues/20739

**Comment by sheetalkamat** [comment]
Can you please provide what you see when you provide option ```--listFiles``` with ```--watch``` and without ```-watch```. can you please let us know where the tsc is invoked from in your repro steps.. In short i am looking for[ current working directory](https://nodejs.org/api/process.html#process_process_cwd) being used.

**Comment by JulioJu** [comment]
With **typescript@next** (today typescript@2.8.0-dev.20180130)
### Under  ~/essaiTS
1. `cd ~/essaiTS`
2.  `$ node node_modules/typescript/bin/tsc --listFiles`
```
/home/julioju/essaiTS/node_modules/typescript/lib/lib.d.ts
/home/julioju/essaiTS/app/file.ts
```
3. `$ node node_modules/typescript/bin/tsc --listFiles --watch`
```
11:52:26 PM - Starting compilation in watch mode...


/home/julioju/essaiTS/node_modules/typescript/lib/lib.d.ts
/home/julioju/essaiTS/app/file.ts
11:52:28 PM - Compilation complete. Watching for file changes.
```
*then when we change ~/essaiTS/file.ts*
```
11:53:36 PM - File change detected. Starting incremental compilation...


/home/julioju/essaiTS/node_modules/typescript/lib/lib.d.ts
/home/julioju/essaiTS/app/file.ts
11:53:36 PM - Compilation complete. Watching for file changes.

```
==> ***~/essaiTS/file.js is not changed.***
### Under  /tmp/essaiTS
1. `cp -R ../essaiTS /tmp && cd /tmp/essaiTS`
2. `$ node node_modules/typescript/bin/tsc --listFiles`
```
/tmp/essaiTS/node_modules/typescript/lib/lib.d.ts
/tmp/essaiTS/app/file.ts
```
3. `$ node node_modules/typescript/bin/tsc --listFiles --watch`
```

11:54:29 PM - Starting compilation in watch mode...


/tmp/essaiTS/node_modules/typescript/lib/lib.d.ts
/tmp/essaiTS/app/file.ts
11:54:31 PM - Compilation complete. Watching for file changes.

```
*then when we change /tmp/essaiTS/file.ts*
```
11:56:27 PM - File change detected. Starting incremental compilation...


/tmp/essaiTS/node_modules/typescript/lib/lib.d.ts
/tmp/essaiTS/app/file.ts
11:56:27 PM - Compilation complete. Watching for file changes.
```

==> ***/tmp/essaiTS/file.js is changed accordingly.***

**Comment by JulioJu** [comment]
Same problem if we are in /taa/essaiTS (no emit app/file.js file on incremental compilation). 

It's very strange. There is no problems in folder /tmp/essaiTS, or folder /tmp/tmp/tmp/essaiTS. (file  app/file.js is emitted on incremental compilation)

The filesystem of my /tmp is tmpfs (Ram memory). But when we compile under other folder with filesystem tmpfs like /dev/shm or /run/user/1000 I have same problem (no emit app/file.js file on incremental compilation). 

In /tmp/essaiTS, if I use `tsc --watch` located outside /tmp/essaiTS, there is no problem too. (file  app/file.js is emitted on incremental compilation)

This bug is it confirmed ?

I'm on Arch Linux. If you want I can try tomorrow on a Live Ubuntu 17.10.

**Comment by JulioJu** [comment]
On Arch Linux I've disabled the automatic mount of a filesystem tmpfs in /tmp (https://wiki.archlinux.org/index.php/Tmpfs#Disable_automatic_mount). You could test than /tmp is not a mount point of a tmpfs filesystem thanks to the command `df -h`. 

When /tmp is not a mount point of a tmpfs filesystem, there is the same problem with other folders (no emit app/file.js file on incremental compilation). 

So on my computer, under Arch Linux, before there was no problem of incremental compilation because /tmp was a mount point of a tmps filesystem. 

Characteristics of my laptop is: "CPU:       Dual core Intel Core i5 M 520 (-MT-MCP-) speed/max: 1222/2395 MHz"

**Comment by JulioJu** [comment]
The problem was introduced between TypeScript 2.6.0-dev.20170929 and 2.6.0-dev.20170930. I've tested with TypeScript 2.6.0-dev.20170929: no problems, ~/essaiTS/app/file.js is emitted on `--watch` mode.  Opposite, TypeScript `2.6.0-dev.20170930` does not emits  ~/essaiTS/app/file.js on `--watch` mode.

**Comment by JulioJu** [comment]
I don't know if it's useful, but I've done a `git bisect`. 


`$ git log --pretty=short`:


```
commit 6997e9b7316b081f8731d131139c7d7f1bba9092 (HEAD, refs/bisect/bad)
Merge: 7f7d0c6c7b 8ac01d76f5
Author: Sheetal Nandi <shkamat@microsoft.com>

    Merge pull request #17269 from Microsoft/watchImprovements

commit 7f7d0c6c7b9b27c46d2d24c9bcf698bc81dc06d5 (refs/bisect/good-7f7d0c6c7b9b27c46d2d24c9bcf698bc81dc06d5)
Author: Wesley Wigham <wwigham@gmail.com>

    Baseline public API (#18897)
```

**Comment by sheetalkamat** [comment]
Thank you for information.. Sorry for delay mentioning, but could you run the same experiments with ```--extendedDiagnostics``` This would help us identify which kind of watch notifications we are receiving to get better understanding of the issue. The change you have mentioned was a big change to revamp how tsc --watch works so narrowing the issue further would help immensely. We use node's fs.watch and fs.watchFile to determine the updates and those apis are very OS dependent and hence need your help in investigating...

**Comment by JulioJu** [comment]
Yes, I've seen it's a big merge.

I've explored more thanks git bisect but it's hard because there are lot of changes, lot of break, and there is a lot of changes.

```
89c61e797c794515a06a3719ca95e37d97783d6e is the first bad commit
commit 89c61e797c794515a06a3719ca95e37d97783d6e
Author: Sheetal Nandi <shkamat@microsoft.com>
Date:   Thu Aug 3 00:27:46 2017 -0700

    Modify the api in builder so that it tracks changed files
````

At 89c61e797c794515a06a3719ca95e37d97783d6e, you could see an error message when you use incremental compilation (see message below). It was introduced by   c814d8e8 and was resolved by 59d07dc.  

`$ node ~/essaiTS/lib/tsc.js --watch`, then edit and save the file ~/essaiTS/app/file.ts.
```

9:31:02 PM - Compilation complete. Watching for file changes.


error TS18003: No inputs were found in config file '/home/.........../essaiTS/tsconfig.json'. S
pecified 'include' paths were '["app/**/*.ts"]' and 'exclude' paths were '[]'.
error TS18003: No inputs were found in config file '/home/............./essaiTS/tsconfig.json'. S
pecified 'include' paths were '["app/**/*.ts"]' and 'exclude' paths were '[]'.
9:31:09 PM - File change detected. Starting incremental compilation...


9:31:09 PM - Compilation complete. Watching for file changes.


error TS18003: No inputs were found in config file '/home/.............../essaiTS/tsconfig.json'. S
pecified 'include' paths were '["app/**/*.ts"]' and 'exclude' paths were '[]'.
error TS18003: No inputs were found in config file '/home/.................../essaiTS/tsconfig.json'. S
pecified 'include' paths were '["app/**/*.ts"]' and 'exclude' paths were '[]'.
9:31:24 PM - File change detected. Starting incremental compilation...


9:31:24 PM - Compilation complete. Watching for file changes.
```

* (Note: from e068475 to 69e5abd5b7(parent of c814d8e8) I've found some crashes. The watching compilation doesn't start with different errors).

I hope now it's ok !

**Comment by JulioJu** [comment]
With typescript@2.8.0-dev.20180131
`$ node node_modules/typescript/bin/tsc --watch --extendedDiagnostics`

```
3:29:18 AM - Starting compilation in watch mode...


Synchronizing program
FileWatcher:: Added: PathInfo: /home/julioprayer/essaiTS/app/file.ts
FileWatcher:: Added: PathInfo: /home/julioprayer/essaiTS/node_modules/typescript/lib/lib.d.ts
DirectoryWatcher recursive:: Added: PathInfo: /home/julioprayer/essaiTS/node_modules/@types
Files:                   2
Lines:               19880
Nodes:               91612
Identifiers:         31615
Symbols:             24072
Types:                6571
Memory used:        55909K
I/O Read time:       0.00s
Parse time:          0.46s
Program time:        0.47s
Bind time:           0.23s
Check time:          1.23s
transformTime time:  0.03s
commentTime time:    0.00s
I/O Write time:      0.00s
printTime time:      0.01s
3:29:27 AM - File change detected. Starting incremental compilation...


Synchronizing program
FileWatcher:: Added: PathInfo: /home/julioprayer/essaiTS/app/file.ts
Files:              2
3:29:37 AM - Starting compilation in watch mode...


Synchronizing program
FileWatcher:: Added: PathInfo: /home/julioprayer/essaiTS/app/file.ts
FileWatcher:: Added: PathInfo: /home/julioprayer/essaiTS/node_modules/typescript/lib/lib.d.ts
DirectoryWatcher recursive:: Added: PathInfo: /home/julioprayer/essaiTS/node_modules/@types
Files:                   2
Lines:               19879
Nodes:               91605
Identifiers:         31613
Symbols:             24072
Types:                6571
Memory used:        55493K
I/O Read time:       0.00s
Parse time:          0.47s
Program time:        0.48s
Bind time:           0.22s
Check time:          1.28s
transformTime time:  0.02s
commentTime time:    0.00s
I/O Write time:      0.00s
printTime time:      0.01s
Emit time:           0.05s
Total time:          2.04s
3:29:39 AM - Compilation complete. Watching for file changes.


DirectoryWatcher recursive:: Added: PathInfo: /home/julioprayer/essaiTS/app

```
Then when we edit the file ~/essaiTS/app/file.ts 
```
3:31:09 AM - File change detected. Starting incremental compilation...


Synchronizing program
Files:                   2
Lines:               19880
Nodes:               91612
Identifiers:         31615
Symbols:             21765
Types:                  61
Memory used:        48057K
I/O Read time:       0.00s
Parse time:          0.00s
Program time:        0.00s
Bind time:           0.00s
transformTime time:  0.00s
printTime time:      0.00s
Emit time:           0.01s
Check time:          0.00s
commentTime time:    0.00s
I/O Write time:      0.00s
Total time:          0.01s
3:31:09 AM - Compilation complete. Watching for file changes.
```

**Comment by JulioJu** [comment]
Same as below, but in /tmp/essaiTS folder

```
3:36:28 AM - Starting compilation in watch mode...


Synchronizing program
FileWatcher:: Added: PathInfo: /tmp/essaiTS/app/file.ts
FileWatcher:: Added: PathInfo: /tmp/essaiTS/node_modules/typescript/lib/lib.d.ts
DirectoryWatcher recursive:: Added: PathInfo: /tmp/essaiTS/node_modules/@types
Files:                   2
Lines:               19880
Nodes:               91612
Identifiers:         31615
Symbols:             24072
Types:                6571
Memory used:        55758K
I/O Read time:       0.00s
Parse time:          0.47s
Program time:        0.48s
Bind time:           0.23s
Check time:          1.38s
transformTime time:  0.02s
commentTime time:    0.00s
I/O Write time:      0.00s
printTime time:      0.01s
Emit time:           0.04s
Total time:          2.13s
3:36:30 AM - Compilation complete. Watching for file changes.


DirectoryWatcher recursive:: Added: PathInfo: /tmp/essaiTS/app
```

Then when we edit file /tmp/essaiTS/app/file.ts

```
3:37:43 AM - File change detected. Starting incremental compilation...


Synchronizing program
Files:                   2
Lines:               19879
Nodes:               91605
Identifiers:         31613
Symbols:             21765
Types:                  61
Memory used:        47876K
I/O Read time:       0.00s
Parse time:          0.00s
Program time:        0.00s
Bind time:           0.00s
transformTime time:  0.00s
printTime time:      0.00s
Emit time:           0.00s
Check time:          0.00s
commentTime time:    0.00s
I/O Write time:      0.00s
Total time:          0.01s
3:37:43 AM - Compilation complete. Watching for file changes.
```

**Comment by sheetalkamat** [comment]
I am sorry for asking for more information but with console clearing that happens with --watch the actual useful information got lost.  I have merged #21537 that will not clear the screen on updates so we wont loose the diagnostic information. Can you please run this with and when tonights typescript nightly drop is generated. 

I would appreciate if you can run this with these all options: ```--watch --listFiles --listEmittedFiles --extendedDiagnostics```

Out of the above log i can tell that the paths for the watch seem incorrect with something like too many dots with home directory.... ```/home/............/essaiTS/app/file.ts``` but the log would help understand if any directory watch or file watch gets invoked at all..

I again apologize for asking you to run this again. Hopefully this time we will get all the information we need.

**Comment by JulioJu** [comment]
The dots in « `/home/............/essaiTS/app/file.ts` » replace only the name of my home folder. Dots replace only a folder name who has only ASCII characters and who is 11 characters long. Now, I replace the name of my home folder by « julioju »

@sheetalkamat no problems ;-) ! It's cool if I can help :-) ! Have you noticed than I've found accuracy the problematic commit ? It's 89c61e7. You could see it's a very small commit :-) ! You could see explanations [on my comment above](https://github.com/Microsoft/TypeScript/issues/21444#issuecomment-362136494).

With  TypeScript 2.8.0-dev.20180203

**In ~/essaiTS**
```
$ node node_modules/typescript/bin/tsc --watch --listFiles --listEmittedFiles --extendedDiagnostics
Current directory: /home/julioju/essaiTS CaseSensitiveFileNames: trueundefinedFileWatcher:: Added: PathInfo: /home/julioju/essaiTS/tsconfig.jsonundefined5:43:53 PM - Starting compilation in w
atch mode...


Synchronizing program
CreatingProgramWith::
  roots: ["/home/julioju/essaiTS/app/file.ts"]
  options: {"watch":true,"listFiles":true,"listEmittedFiles":true,"extendedDiagnostics":true,"configFilePath":"/home/julioju/essaiTS/tsconfig.json"}
FileWatcher:: Added: PathInfo: /home/julioju/essaiTS/app/file.ts
FileWatcher:: Added: PathInfo: /home/julioju/essaiTS/node_modules/typescript/lib/lib.d.ts
DirectoryWatcher recursive:: Added: PathInfo: /home/julioju/essaiTS/node_modules/@types
TSFILE: /home/julioju/essaiTS/app/file.js
/home/julioju/essaiTS/node_modules/typescript/lib/lib.d.ts
/home/julioju/essaiTS/app/file.ts
Files:                   2
Lines:               19886
Nodes:               91626
Identifiers:         31622
Symbols:             24085
Types:                6579
Memory used:        55095K
I/O Read time:       0.00s
Parse time:          0.46s
Program time:        0.47s
Bind time:           0.23s
Check time:          1.19s
transformTime time:  0.02s
commentTime time:    0.00s
I/O Write time:      0.00s
printTime time:      0.01s
Emit time:           0.04s
Total time:          1.94s
5:43:55 PM - Compilation complete. Watching for file changes.


DirectoryWatcher recursive:: Added: PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Elapsed: 1ms Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Elapsed: 1ms Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
FileWatcher:: Close: PathInfo: /home/julioju/essaiTS/app/file.ts
DirectoryWatcher recursive:: Elapsed: 1ms Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
5:44:06 PM - File change detected. Starting incremental compilation...


Synchronizing program
CreatingProgramWith::
  roots: ["/home/julioju/essaiTS/app/file.ts"]
  options: {"watch":true,"listFiles":true,"listEmittedFiles":true,"extendedDiagnostics":true,"configFilePath":"/home/julioju/essaiTS/tsconfig.json"}
FileWatcher:: Added: PathInfo: /home/julioju/essaiTS/app/file.ts
/home/julioju/essaiTS/node_modules/typescript/lib/lib.d.ts
/home/julioju/essaiTS/app/file.ts
Files:              2
Lines:          19887
Nodes:          91633
Identifiers:    31624
Symbols:        21775
Types:             58
Memory used:   56389K
I/O Read time:  0.00s
Parse time:     0.00s
Program time:   0.00s
Bind time:      0.00s
Total time:     0.00s
5:44:06 PM - Compilation complete. Watching for file changes.
```

**In /tmp/essaiTS**

```
$ node node_modules/typescript/bin/tsc --watch --listFiles --listEmittedFiles --extendedDiagnostics
Current directory: /tmp/essaiTS CaseSensitiveFileNames: trueundefinedFileWatcher:: Added: PathInfo: /tmp/essaiTS/tsconfig.jsonundefined5:45:47 PM - Starting compilation in watch mode...


Synchronizing program
CreatingProgramWith::
  roots: ["/tmp/essaiTS/app/file.ts"]
  options: {"watch":true,"listFiles":true,"listEmittedFiles":true,"extendedDiagnostics":true,"configFilePath":"/tmp/essaiTS/tsconfig.json"}
FileWatcher:: Added: PathInfo: /tmp/essaiTS/app/file.ts
FileWatcher:: Added: PathInfo: /tmp/essaiTS/node_modules/typescript/lib/lib.d.ts
DirectoryWatcher recursive:: Added: PathInfo: /tmp/essaiTS/node_modules/@types
TSFILE: /tmp/essaiTS/app/file.js
/tmp/essaiTS/node_modules/typescript/lib/lib.d.ts
/tmp/essaiTS/app/file.ts
Files:                   2
Lines:               19887
Nodes:               91633
Identifiers:         31624
Symbols:             24085
Types:                6579
Memory used:        55432K
I/O Read time:       0.00s
Parse time:          0.46s
Program time:        0.47s
Bind time:           0.27s
Check time:          1.20s
transformTime time:  0.02s
commentTime time:    0.00s
I/O Write time:      0.00s
printTime time:      0.01s
Emit time:           0.05s
Total time:          1.99s
5:45:49 PM - Compilation complete. Watching for file changes.


DirectoryWatcher recursive:: Added: PathInfo: /tmp/essaiTS/app
FileWatcher:: Trigger: /tmp/essaiTS/app/file.ts 1 PathInfo: /tmp/essaiTS/app/file.ts
FileWatcher:: Elapsed: 1ms Trigger: /tmp/essaiTS/app/file.ts 1 PathInfo: /tmp/essaiTS/app/file.ts
5:48:12 PM - File change detected. Starting incremental compilation...


Synchronizing program
CreatingProgramWith::
  roots: ["/tmp/essaiTS/app/file.ts"]
  options: {"watch":true,"listFiles":true,"listEmittedFiles":true,"extendedDiagnostics":true,"configFilePath":"/tmp/essaiTS/tsconfig.json"}
TSFILE: /tmp/essaiTS/app/file.js
/tmp/essaiTS/node_modules/typescript/lib/lib.d.ts
/tmp/essaiTS/app/file.ts
Files:                   2
Lines:               19886
Nodes:               91626
Identifiers:         31622
Symbols:             21775
Types:                  61
Memory used:        47983K
I/O Read time:       0.00s
Parse time:          0.00s
Program time:        0.00s
Bind time:           0.00s
Check time:          0.00s
transformTime time:  0.00s
printTime time:      0.00s
Emit time:           0.01s
commentTime time:    0.00s
I/O Write time:      0.00s
Total time:          0.01s
5:48:12 PM - Compilation complete. Watching for file changes.
```

**Comment by JulioJu** [comment]
Confirmed on Arch Linux, Ubuntu and Mac with the following zsh script :
```zsh
#!/bin/zsh
# -*- coding: UTF8 -*-

# The corresponding issue is:
#   https://github.com/Microsoft/TypeScript/issues/21444
# « Linux: Problem with --watch when we compile in folder outside /tmp mounted
# by systemd as tmpfs filesystem
# with tsconfig.json « "include": ["app/**/*.ts"] » »
# ≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠

RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -e ~/essaiTS ]
then
    echo -n ${RED}"Please delete ~/essaiTS"${NC}
    return 14
fi

which yarn
if [ `echo $?` -ne 0 ]
then
    echo -n ${RED}"Please install yarn and node before running this \
    script.\n\n"${NC}
    return 15
fi

mkdir -p ~/essaiTS/app
cd ~/essaiTS
cat << EOF > ~/essaiTS/tsconfig.json
{
    "include": [
        "app/**/*.ts"
    ]
}
EOF
cat << EOF > ~/essaiTS/app/file.ts
console.log('');
EOF
cat << EOF > ~/essaiTS/app/file.js
console.log('');
EOF
yarn add typescript@next
node node_modules/typescript/bin/tsc --watch &
sleep 2
echo -n ${RED}'Please Wait 10 secondes:\n\n'${NC}
sleep 10
cat << EOF >> ~/essaiTS/app/file.ts
console.log('');
EOF
diffCommand='diff ~/essaiTS/app/file.ts ~/essaiTS/app/file.js'
echo $diffCommand
eval $diffCommand
isDiff=`echo $?`
echo "echo \$? = " $isDiff
if [ $isDiff -eq 0 ]
then
    echo ${RED}'~/essaiTS/app/file.ts et ~/essaiTS/app/file.js are the same.\
    '${NC}
else
    echo ${RED}'~/essaiTS/app/file.ts et ~/essaiTS/app/file.js are different.\
        '${NC}
fi
echo -n '\n\n'
echo 'File ~/essaiTS/app/file.ts'
echo '≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠'
cat ~/essaiTS/app/file.ts
echo '---End of file--'
echo -n '\n\n'
echo 'File ~/essaiTS/app/file.js'
echo '≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠≠'
cat ~/essaiTS/app/file.js
echo '---End of file--'

echo -n '\n\n---Stopping Typescript compiler---'
kill $!
echo -n '\n--Done---\n\n'
echo -n ${RED}'Your typescript version is: '\
    `eval 'node node_modules/typescript/bin/tsc\
    --version'`'\n\n'
```
@sheetalkamat if you want tomorrow I can test on Windows with [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about).

**Comment by sheetalkamat** [comment]
@JulioJu  thank you for the log, I was able to repro this in our test framework using the repro log.. I am looking into fixing this. Thanks again for all the efforts to get the repro.

**Comment by sheetalkamat** [comment]
@JulioJu I have a fix for this in #21693. Would it be possible to actually try this out to see if this fixes your issue.

**Comment by JulioJu** [comment]
Ok thanks @sheetalkamat it resloves the problem ! 

```
$ cd ~/TypeScript
$ git checkout master
$ git pull
$ git merge fileChangeThroughDeleteAndCreate
$ yarn install && gulp clean && gulp local
$ cd ~/essaiTS
$ cp -R ~/TypeScript/built/local/ .
$ node ~/essaiTS/local/tsc.js --watch --listFiles --listEmittedFiles --extendedDiagnostics
Current directory: /home/julioju/essaiTS CaseSensitiveFileNames: trueundefinedFileWatcher:: Added: PathInfo: /home/julioju/essaiTS/tsconfig.jsonundefined10:47:54 AM - Starting compilation in
watch mode...


Synchronizing program
CreatingProgramWith::
  roots: ["/home/julioju/essaiTS/app/file.ts"]
  options: {"watch":true,"listFiles":true,"listEmittedFiles":true,"extendedDiagnostics":true,"configFilePath":"/home/julioju/essaiTS/tsconfig.json"}
FileWatcher:: Added: PathInfo: /home/julioju/essaiTS/app/file.ts
FileWatcher:: Added: PathInfo: /home/julioju/essaiTS/local/lib.d.ts
DirectoryWatcher recursive:: Added: PathInfo: /home/julioju/essaiTS/node_modules/@types
TSFILE: /home/julioju/essaiTS/app/file.js
/home/julioju/essaiTS/local/lib.d.ts
/home/julioju/essaiTS/app/file.ts
Files:                   2
Lines:               19885
Nodes:               91619
Identifiers:         31620
Symbols:             24085
Types:                6582
Memory used:        60008K
I/O Read time:       0.00s
Parse time:          0.49s
Program time:        0.50s
Bind time:           0.21s
Check time:          1.18s
transformTime time:  0.02s
commentTime time:    0.00s
I/O Write time:      0.00s
printTime time:      0.01s
Emit time:           0.04s
Total time:          1.93s
10:47:56 AM - Compilation complete. Watching for file changes.


DirectoryWatcher recursive:: Added: PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Elapsed: 1ms Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Elapsed: 1ms Trigger: /home/julioju/essaiTS/app/4913 PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
DirectoryWatcher recursive:: Elapsed: 0ms Trigger: /home/julioju/essaiTS/app/file.ts PathInfo: /home/julioju/essaiTS/app
FileWatcher:: Trigger: /home/julioju/essaiTS/app/file.ts 1 PathInfo: /home/julioju/essaiTS/app/file.ts
FileWatcher:: Elapsed: 0ms Trigger: /home/julioju/essaiTS/app/file.ts 1 PathInfo: /home/julioju/essaiTS/app/file.ts
10:48:02 AM - File change detected. Starting incremental compilation...


Synchronizing program
CreatingProgramWith::
  roots: ["/home/julioju/essaiTS/app/file.ts"]
  options: {"watch":true,"listFiles":true,"listEmittedFiles":true,"extendedDiagnostics":true,"configFilePath":"/home/julioju/essaiTS/tsconfig.json"}
TSFILE: /home/julioju/essaiTS/app/file.js
/home/julioju/essaiTS/local/lib.d.ts
/home/julioju/essaiTS/app/file.ts
Files:                   2
Lines:               19886
Nodes:               91626
Identifiers:         31622
Symbols:             21775
Types:                  63
Memory used:        61539K
I/O Read time:       0.00s
Parse time:          0.00s
Program time:        0.00s
Bind time:           0.00s
Check time:          0.00s
transformTime time:  0.00s
printTime time:      0.01s
Emit time:           0.01s
commentTime time:    0.00s
I/O Write time:      0.00s
Total time:          0.01s
10:48:02 AM - Compilation complete. Watching for file changes.
```

**Comment by JulioJu** [comment]
I've changed the title, because maybe (probably) it could occur also on MS Windows, not only in Linux and Mac. Actually not tested on MS Windows.

**Comment by JulioJu** [comment]
Hi @sheetalkamat 
Is it normal if I experience the same issue in typescript@next (Version 2.8.0-dev.20180302) ?
No issues with the last commit cbef5c29b5d8b17f6bd17adbd35ba9ab9e6df0b1, all work when I compile the project at this commit. But doesn't work with Version 2.8.0-dev.20180302. I don't uderstand why ? #21693 is it merged into  typescript@next ?
Thanks in advance.
