### ISSUE TITLE
Cannot find module 'source-map'

### ISSUE THREAD

**Issue by Legends** [Microsoft/TypeScript#21942]
- latest webpack
- latest node runtime
- latest TS version

What does the error message tell me ???

This can happen after installing a package.
Tried to uninstall them all, but it seems, that my project is now messed up and I can't get it to transpile anymore...

PS C:\inetpub\wwwroot\WebPack_TypeScript_Setup_Example> `tsc`

> node_modules/@types/uglify-js/index.d.ts(9,32): error TS2307: Cannot find module 'source-map'.
> node_modules/@types/webpack/index.d.ts(20,30): error TS2307: Cannot find module 'source-map'.

**Comment by Legends** [comment]
**This package causes this error, uninstalling it helps, but then I have not full intellisense support in my webpack.config.js anymore.**

`npm uninstall @types/webpack`

**Comment by j-oliveras** [comment]
The installed version of source-map, don't include definitions (first version that include them is 0.5.7).

You can try with:
```npm install @types/source-map@0.5.2```

**Comment by Legends** [comment]
@j-oliveras This works!
But one question:
Why does it work with `source-map v0.5.2` and not with the latest `source-map v0.5.7` ?
