### ISSUE TITLE
New errors with RxJS on 2.4.1

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#16593]
When using the TS 2.4.1 and RxJS 5.4.1 (latest), I get a new error that I didn't have before upgrading to using TS 2.4.1.

You may already be aware of this—it is an insiders build after all—but thought I should point it out just in case.

```
❯ yarn list typescript
└─ typescript@2.4.1-insiders.20170615

❯ yarn list rxjs
└─ rxjs@5.4.1

❯ tsc
node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

**Comment by DanielRosenwasser** [comment]
CC @benlesh. This is actually a bug that's been caught. `Subject<T>#lift<R>` should be producing an `Observable<R>` but has always been producting an `Observable<T>`

**Comment by masaeedu** [comment]
@OliverJAsh There was a long debate about this in reactivex/rxjs#1234. It's always seemed to me like the bug is in rxjs, in that that override in Subject shouldn't be there in the first place.

**Comment by DanielRosenwasser** [comment]
So since then the signature has been changed [to this](https://github.com/ReactiveX/rxjs/blob/4694a27a1ed06615ebc3bb6507f4fd6941760096/src/Subject.ts#L46).

I don't understand why back then it wasn't just

```ts
lift<R>(operator: Operator<T, R>): Observable<R> 
```

and it looks like the compiler finds the current signature (i.e. the following)

```ts
lift<R>(operator: Operator<T, R>): Observable<T> 
```

to be questionable as well.

**Comment by masaeedu** [comment]
@DanielRosenwasser The problem is that they've been trying to use `Subject`s in a way that is fundamentally type-unsafe. I don't know if anything's changed in the year since that discussion happened, but in terms of the actual JS they want a `Subject<T>`, when transformed by an operator that takes `T`s and produces `R`s, to *still* produce a `Subject` (one that forwards all its values to `this`), instead of an `Observable<R>`. The reason they want to do this has something to do with two way communication in the websocket subject implementation.

None of this makes sense from the type system perspective, because it only makes sense to define `lift` for `Observable`s. It just so happens that a `Subject<T>` is also an `Observable<T>`, but its implementation of `lift<R>` should be no different. The only sensible fix (and one which mirrors how the types are defined in Java/.NET, is to just delete this method and revisit what is going on in the websocket code). There's more details in the issue I linked, but the way they are using subjects can mask runtime bugs.

**Comment by DanielRosenwasser** [comment]
Thanks for the explanation @masaeedu!

Couldn't this be solved by creating a `TypeUnsafeSubject` or something that lifts to `Observable<any>`?

**Comment by DanielRosenwasser** [comment]
CC @david-driscoll

**Comment by DanielRosenwasser** [comment]
I just saw this will be fixed for RxJS 6.0 thanks to https://github.com/ReactiveX/rxjs/pull/2540 (@hearnden).

**Comment by AneelaBrister** [comment]
Hi there, is the solution in the meantime to not go to Typescript 2.4? Thanks

**Comment by michaeldaw** [comment]
@AneelaBrister Typescript version 2.3.4 seems to continue to work.

**Comment by sflemingDCP** [comment]
What's the workaround here?

**Comment by ljmerza** [comment]
using typescript 2.3.4 or rxjs 6 alpha
    npm install `rxjs@6.0.0-alpha.0`

**Comment by parkganesh** [comment]
Using typescript 2.3.4 worked. rxjs 6 alpha gave an unmet peer dependency with angular/router

**Comment by WizardCloud** [comment]
I uninstalled typescript 2.4.1 and installed 2.3.4, it was resolved.

**Comment by claudiuconstantin** [comment]
`rxjs 6.0.0-alpha.0` still won't fix it for me, I'm still getting:

```
ERROR in [at-loader] ./node_modules/rxjs/Subject.d.ts:16:22
    TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

**Comment by floodedcodeboy** [comment]
I've used typescript 2.4.0 with rxjs 5.4.1 and that works fine.

**Comment by OliverJAsh** [comment]
@floodedcodeboy I just tested typescript 2.4.1 and rxjs 5.4.1, to no avail:

```
❯ npm list typescript
├── typescript@2.4.1

❯ npm list rxjs
├── rxjs@5.4.1

❯ tsc
node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

Sounds like the only solution is to upgrade to rxjs 6 alpha.

**Comment by sflemingDCP** [comment]
rxjs@6.0.0-alpha.0 and typescript 2.3.4 worked for me.

**Comment by OliverJAsh** [comment]
@sflemingDCP This issue is specifically about using rxjs with TypeScript 2.4.x.

**Comment by floodedcodeboy** [comment]
@OliverJAsh incorrect ... if you had read my post correctly ... I referenced 2.4.0 ...  not 2.4.1 - make sure your package.json file references 2.4.0 exactly - not ^2.4.0 or ~2.4.0 which will upgrade you to 2.4.1

**Comment by OliverJAsh** [comment]
@floodedcodeboy You're correct. 2.4.0 works but 2.4.1 does not. I will update the issue title.

Confusingly, the [releases page](https://github.com/Microsoft/TypeScript/releases) lists 2.4.1 as "2.4":

![image](https://user-images.githubusercontent.com/921609/27642307-4a696900-5c16-11e7-9bdc-8271e95c75e0.png)

**Comment by kitsonk** [comment]
> Confusingly, the releases page lists 2.4.1 as "2.4"

It isn't confusingly in as much as every minor release of TypeScript has followed that pattern for an extended period of time.  Because of some internal challenges, from what I understand, `#.#.0` will never be the final release of a version of TypeScript.  The first patch public release will always be `#.#.1` and tagged appropriately in npm.

**Comment by Koslun** [comment]
Is it not be possible to simply override the type definition to ignore this error?

Upgrading to an alpha release does not seem like an ideal fix, in particular because I am not sure that our current dependencies truly support that, Angular 4 in particular. Just hope that RxJS 6 will release soon-ish so libraries such as Angular can incorporate it as the supported version. In the case of Angular that would happen either in the next major release scheduled for September or at the worst case the major release after that, around March 2018.

So I think not fixing this in another way could have a pretty tangible effect.

**Comment by fmorriso** [comment]
As others have already pointed out, **_at least until this issue is fully resolved_**, being **_precise_** about which version of TypeScript and RxJS you specify is **_crucial_** for working around this issue, especially for Angular-CLI apps.  

The relevant entries in my package.json are shown below. Notice the **_absence_** of any ~ or ^ characters in the version number:

```
    "dependencies": {
 
       "rxjs": "5.4.1"

    }

    "devDependencies" : {

        "typescript": "2.4.0"

    }

```
My app was generated using Angular-CLI 1.1.3

**Comment by Koslun** [comment]
The issue in the RxJS repo: https://github.com/ReactiveX/rxjs/issues/2539

**Comment by shaamuji** [comment]
Replaced typescript from ^2.4.1 to 2.4.0 worked for me

**Comment by IrickNcqa** [comment]
Discussed here as well [https://github.com/Microsoft/TypeScript/issues/16777](url)

**Comment by ufthelp** [comment]
Thanks @floodedcodeboy . Your solution worked for me.

**Comment by DanielRosenwasser** [comment]
Hey all, you can get around this using the `--noStrictGenericChecks` flag. Sorry for the inconvenience.

**Comment by aluanhaddad** [comment]
Why not use an augmentation to resolve this. The following works with  TypeScript@2.4.1
```ts
// augmentations.ts
import {Operator} from 'rxjs/Operator';
import {Observable} from 'rxjs/Observable';

declare module 'rxjs/Subject' {
  interface Subject<T> {
    lift<R>(operator: Operator<T, R>): Observable<R>;
  }
}
```

**Comment by dhniels** [comment]
@claudiuconstantin im having the issue. still getting error TS2415 for Subject<T> and WebSocketSubject<T> with typescript 2.4.1 even after updating rxjs to 6.0.0-alpha.0

**Comment by Koslun** [comment]
> edit: may be a result of unmet peer dependencies?

Unmet peer dependency errors in this instance just means that those angular dependencies require RxJS 5.0.1 or higher, but below 6. Angular could still work with RxJS higher than they have specified, as they often work with higher versions of TypeScript. But I think you're always at risk of some part of Angular not working or an arbitrary patch or minor version update breaking your build.

So use the solution proposed by @aluanhaddad  instead, unless you for some other reason want to use the next version of RxJS already.

**Comment by claudiuconstantin** [comment]
@aluanhaddad, nice work, all good if you directly use `rxjs `in your project. What if a certain package in your project also uses the "bad" rxjs? You'll also get the error from there and until the maintainer fixes the problem you're stuck. Any workaround for that?

**Comment by Koslun** [comment]
@claudiuconstantin If another dependency directly depends on it, i.e. not just a peer dependency, you have RxJS in your project the same way you have it if you depended on it directly. So the augmentation should work just as well.

**Comment by fletchsod-developer** [comment]
fyi the fix already landed on RxJS 5.4.2 (<a href="https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#542-2017-07-05">changelog</a>), you can either close this issue or leave it open.

**Comment by benlesh** [comment]
@DanielRosenwasser @OliverJAsh FYI: This was resolved with the release of rxjs 5.4.2, and this issue can be closed.

## All: rxjs 5.4.2 resolves this issue.


Either way, this issue can be closed as it was a bug in rxjs, not TypeScript.
