### ISSUE TITLE
The new EventListener definition is not backwards compatible and/or has an error

### ISSUE THREAD

**Issue by weswigham** [Microsoft/TypeScript#21948]
**TypeScript Version:**  2.7.0-dev.201xxxxx

I think was broken by #21889, and is not one of the changes listed as a fixed bug in the PR, so may be unintentional. The change has consequently has broken a handful of our RWC tests. Specifically, very common patterns like

**Code**

```ts
this._pseudoStatesToggle.addEventListener("DOMAttrModified", (mutationEvent: MutationEvent): boolean => {
                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!!! error TS2345: Argument of type '(mutationEvent: MutationEvent) => boolean' is not assignable to parameter of type 'EventListener'.
!!! error TS2345:   Type 'boolean' is not assignable to type 'void | { handleEvent(evt: Event): void; }'.    
                    return true;
                });
```

The change is that the webworker lib file now defines `EventListener` as:
```ts
type EventListener = (evt: Event) => void | { handleEvent(evt: Event): void; };
```
but it was:
```ts
interface EventListener {
    (evt: Event): void;
}
```
There also used to be a type:
```ts
declare type EventListenerOrEventListenerObject = EventListener | EventListenerObject;
```
that some RWC tests rely on (and this type looks to be what the alias is emulating).

**Comment by falsandtru** [comment]
https://github.com/Microsoft/TSJS-lib-generator/pull/352 breaks the acceptability (type safety) of interfaces depended on EventListener type. This is large breaking change. This change should be reverted.

**Comment by weswigham** [comment]
`EventListenerOrEventListenerObject` is also relied upon by some real code bases. Also,
```ts
type EventListener = (evt: Event) => void | { handleEvent(evt: Event): void; };
```
is probably just straight wrong, even by original intent, since that is parsed as "A function with an argument of type Event and a return type of either (void OR an object with a handleEvent method)" and not "(A function that returns void with an argument of type Event) OR (an object with a handleEvent method)."
