### ISSUE TITLE
Incorrectly inferred type never for variables with strictNullChecks

### ISSUE THREAD

**Issue by e98cuenc** [Microsoft/TypeScript#9322]
**TypeScript Version:** 

nightly (1.9.0-dev.20160623-1.0)

**Code**

```ts
let foo = [];
foo.push('x');
```

**Expected behavior:**

No errors, TypeScript should infer the type `any[]` for the variable `foo`.

**Actual behavior:** 

tsc without any command line option behaves as expected, but when used with `--strictNullChecks` it emits the error:

    foo.ts(2,10): error TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

**Comment by aluanhaddad** [comment]
Working in 1.9.0-dev.20160624-1.0

**Comment by RyanCavanaugh** [comment]
Failing for me as described in current master

**Comment by aluanhaddad** [comment]
@RyanCavanaugh I had misconfigured project. I can indeed reproduce the error. Sorry for the confusion.

**Comment by ahejlsberg** [comment]
This is working as intended. The inferred type for `foo` is `never[]` because we don't widen types in `--strictNullChecks` mode. Full details in #8944.
