### PR TITLE
Restore delayed merge check to getTypeFromJSDocValueReference

### LINKED ISSUE #34685: JSDoc type reference resolves incorrectly if checked before the constructor function it refers to
```js
// @filename: mod1.js
var Workspace = {}
Workspace.Project = function () { }
Workspace.Project.prototype = {
  isServiceProject() { }
}
// @filename: test.js
/** @param {Workspace.Project} p */
function demo(p) {
  p.isServiceProject()
}
```

Expected: no error, and `p.isServiceProject(): void`.

Actual: no error if you compile `tsc mod1.js test.js`, but an error with `tsc test.js mod1.js`:

Property 'isServiceProject' does not exist on type 'typeof Project'.

From chrome-devtools-frontend, failed in https://github.com/microsoft/TypeScript/pull/34603

### PR DESCRIPTION
**Pull request by sandersn**
This is needed when a function merges with a prototype assignment. The resulting *merged* symbol is a constructor function marked with SymbolFlags.Class. However, the merge doesn't happen until getTypeOfFuncClassEnumModule is called, which, in the getTypeReferenceType code path, doesn't happen until getTypeFromJSDocValueReference. That means the check for SymbolFlags.Class is missed.

Previously, getTypeFromJSDocValueReference had a weird check `symbol !== getTypeOfSymbol(symbol).symbol`, which, if true, ran getTypeReferenceType again on `getTypeOfSymbol(symbol).symbol`. For JS "aliases", this had the effect of dereferencing the alias, and for
function-prototype merges, this had the effect of ... just trying again sfter the merge had happened.

This is a confusing way to run things. getTypeReferenceType should instead detect a function-prototype merge, cause it to happen, and *then* run the rest of its code instead of relying on try-again logic at
the very end. However, for the RC, I want to fix this code by restoring the old check, with an additional check to make sure that #33106 doesn't break again:

```ts
const valueType = getTypeOfSymbol(symbol)
symbol !== valueType.symbol && getMergedSymbol(symbol) === valueType.symbol
```

I'll work on the real fix afterwards and put it into 3.8.

Fixes #34685

### CODE REVIEW

**Comment by sandersn** [comment]
Not yet!

**Comment by sandersn** [comment]
https://github.com/microsoft/TypeScript/issues/34707

**Comment by sandersn** [comment]
@typescript-bot cherry-pick this to release-3.7
