### PR TITLE
Instantiate generic ElementType declarations

### LINKED ISSUE #53939: JSX.ElementType from #51328 doesn't instantiate defaulted type parameters correctly
In DT, preact dependents like preact-i18n have failures in their tests when they should not:

```ts
preact-i18n-tests.tsx:26:13 - error TS2786: 'span' cannot be used as a JSX component.
  Its type '"span"' is not a valid JSX element type.

26     return <span>{test}</span>;
```

preact's ElementType looks like this:

```ts
	export type ElementType<P = any> =
		| {
				[K in keyof IntrinsicElements]: P extends IntrinsicElements[K]
					? K
					: never;
		  }[keyof IntrinsicElements]
		| ComponentType<P>;
```

Replacing `P` with `any` and deleting the type parameter fixes the problem:
```ts
	export type ElementType =
		| {
				[K in keyof IntrinsicElements]: any extends IntrinsicElements[K]
					? K
					: never;
		  }[keyof IntrinsicElements]
		| ComponentType<any>;
```

Broken by #51328. Looks like almost the right test case was added to catch this, but not quite.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #53939

### CODE REVIEW

**Review by RyanCavanaugh — APPROVED** [review]

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -30690,6 +30682,11 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         return jsxNamespace && getSymbol(jsxNamespace.exports!, JsxNames.LibraryManagedAttributes, SymbolFlags.Type);
     }
 
+    function getJsxElementTypeSymbol(jsxNamespace: Symbol) {
+        // JSX.ElementType [symbol]
```
Comment (sandersn) [inline src/compiler/checker.ts:30686]: maybe should be jsdoc 
and I'm not convinced getJsxElementTypeSymbol needs to be its own function -- is it parallel to some other getJSX* functions?

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -30690,6 +30682,11 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         return jsxNamespace && getSymbol(jsxNamespace.exports!, JsxNames.LibraryManagedAttributes, SymbolFlags.Type);
     }
 
+    function getJsxElementTypeSymbol(jsxNamespace: Symbol) {
+        // JSX.ElementType [symbol]
+        return jsxNamespace && getSymbol(jsxNamespace.exports!, JsxNames.ElementType, SymbolFlags.Type);
```
Comment (sandersn) [inline src/compiler/checker.ts:30687]: probably don't need to check jsxNamespace when its type doesn't include undefined

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -30826,11 +30823,31 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+            if (length(params) >= typeArguments.length) {
+                const args = fillMissingTypeArguments(typeArguments, params, typeArguments.length, inJs);
+                return length(args) === 0 ? declaredManagedType : getTypeAliasInstantiation(managedSym, args);
+            }
+        }
+        if (length((declaredManagedType as GenericType).typeParameters) >= typeArguments.length) {
+            const args = fillMissingTypeArguments(typeArguments, (declaredManagedType as GenericType).typeParameters, typeArguments.length, inJs);
+            return createTypeReference((declaredManagedType as GenericType), args);
+        }
+        return undefined;
```
Comment (sandersn) [inline src/compiler/checker.ts:30848]: what does it mean for to return undefined here if declaredManagedType is defined, but doesn't hit either of the previous two returns?

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -30826,11 +30823,31 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
...
+        const type = instantiateAliasOrInterfaceWithDefaults(sym, isInJSFile(location));
+        if (!type || isErrorType(type)) return undefined;
         return type;
     }
 
+    function instantiateAliasOrInterfaceWithDefaults(managedSym: Symbol, inJs: boolean, ...typeArguments: Type[]) {
+        const declaredManagedType = getDeclaredTypeOfSymbol(managedSym); // fetches interface type, or initializes symbol links type parmaeters
+        if (managedSym.flags & SymbolFlags.TypeAlias) {
+            const params = getSymbolLinks(managedSym).typeParameters;
+            if (length(params) >= typeArguments.length) {
```
Comment (sandersn) [inline src/compiler/checker.ts:30839]: a type alias with all its type arguments provided will return `undefined` from this function. Why not return the type alias itself? Does getJsxElementTypeTypeAt only return a type if the JSX.ElementType is a type alias with defaulted parameters?

Looking at getJsxManagedAttributesFromLocatedAttributes, all these questions really originate there, because this code is abstracted from it.

**Review by sandersn — CHANGES_REQUESTED** [review]
Some questions about when the retrieved type is undefined.

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts:30686]: This mimics the comment in some of jsx namespace lookup functions, which this function does paralllel.

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts:30687]: `getJsxNamespaceAt` quite literally has a `return undefined!; // TODO: GH#18217` in it, and we check its' results for defined-ness in _most_ other places because of this. It just has inaccurate types and I'm not really sure why. Old API compat?

File: src/compiler/checker.ts (hunk 3 above)
Comment (weswigham) [reply src/compiler/checker.ts:30848]: The type arguments couldn't be instantiated, usually because there weren't enough defaulted type arguments plus passed in arguments. (This code was just extracted from manufacturing the `LibraryManagedAttributes` type and reused)

File: src/compiler/checker.ts (hunk 4 above)
Comment (weswigham) [reply src/compiler/checker.ts:30839]: > a type alias with all its type arguments provided will return undefined from this function.

...No? A type alias with an insufficient number of arguments to handle the `typeArguments` passed in (which is zero for `ElementType`, so any amount will do, but 2 for `LibraryManagedAttributes`) will return `undefined.

Comment (sandersn) [reply src/compiler/checker.ts:30839]: It took a lot of staring, but I figured out that: I misread `>=` as `>`.

**Review by sandersn — APPROVED** [review]
