### ISSUE TITLE
Regression: Initialization of static property with chained method call gives TS2448

### ISSUE THREAD

**Issue by andrewbrown** [Microsoft/TypeScript#14312]
**TypeScript Version:**  2.2.1 , installed via npm

**Code**

```ts
// Environment Summary:  Visual Studio Code 1.9.1 with the following installed:
//
//    > npm list
//    test@0.0.1 C:\Users\abrown\src\test
//    +-- @types/jquery@2.0.40
//    +-- jquery@3.1.1
//    `-- typescript@2.2.1
//
namespace TestNamespace {
    export class TestClass {
        // Contrived, just to support showing a minimal example:
        private static getTemplate(): JQuery { return $(document); }

        // TypeScript error:
        // test.ts(7,53): error TS2448: Block-scoped variable 'find' used before its declaration.
        private static jq = TestClass.getTemplate().find("whatever");

        // But OK here:
        private static test() {
            var jq = TestClass.getTemplate().find("whatever");
        }
    }
}

```

**Expected behavior:**
Compiles without error

**Actual behavior:**
test.ts(7,53): error TS2448: Block-scoped variable 'find' used before its declaration.

Both .getTemplate() and JQuery.find() return JQuery.  So I cannot see why chaining a call to .find() would give the error above.  Reviewed the TypeScript spec but could not locate anything that spoke to this.

**Notes:**
This compiled successfully in TypeScript 2.1.6

**Comment by HolgerJeromin** [comment]
I have similar include order problems with TS2.2 (worked in TS2.1) but had not the time to analyse.

**Comment by HolgerJeromin** [comment]
My Problem was a wrong compilation order. I had in tsconfig.json 
```json
 "include": [
      "*.ts"
    ],

```
This automagically worked for my complex code.
With TS2.2 i have to add every file in the correct order. 
No real problem for me, as i had a `_references.ts` file with all files available which i included instead the `*.ts`.

**Comment by alexeagle** [comment]
Affects google-internal code as well.

**Comment by sandersn** [comment]
@andrewbrown I couldn't get your example to repro with 2.2 or `typescript@next`. Could it be there is some external factor, possibly an ordering problem like @HolgerJeromin found? @alexeagle does the google-internal code use `"include": ["*.ts"]` too?

**Comment by andrewbrown** [comment]
@sandersn I just reattempted the repro today using the same module versions as listed in the original bug report, and no longer see the error.  I'm not sure why I was hitting this before, but you can consider my example "no repro."  Thanks for looking at it.

**Comment by DanielRosenwasser** [comment]
@alexeagle are you still running into this?

**Comment by alexeagle** [comment]
We worked around this by re-ordering the declarations in 3 files. I can dig
up a repro if you need it.

**Comment by sandersn** [comment]
Yes, I would appreciate it.

**Comment by alexeagle** [comment]
```
$ npm install typescript@2.2.1
$ cat > repro.ts
class X {
  static f = X.configure;
  static configure() { }
}
$ ./node_modules/.bin/tsc repro.ts
repro.ts(2,16): error TS2448: Block-scoped variable 'configure' used before its declaration.
```

**Comment by sandersn** [comment]
Thanks. Looks like it still repros on master.

**Comment by gcnew** [comment]
The `class X` repro seems like expected behaviour to me. Statics should be set in the order they appear.

**Comment by sandersn** [comment]
Static methods are initialized before properties, and are therefore available to static property initializers.

**Comment by sandersn** [comment]
Fix is up at #15010
