### ISSUE TITLE
(regressions) Property 'something' does not exist on type '{}' and Types of parameters 'field' and 'value' are incompatible

### ISSUE THREAD

**Issue by pocesar** [Microsoft/TypeScript#18941]
**TypeScript Version:**  nightly (2.6.0-dev.20171004)

**Code**

Many things broke (on unchanged code) when using lodash type definitions with latest nightly. The inferring is kinda broken (and it's not allowing parameters to be overloaded)

**Expected behavior:**

To work: 

```ts
[].forEach((field: keyof Data.AddressDataSetMixin) => {
  //...
})
//...
_.reduce(citizens, (name, citizen) => {
      if (citizen.address && citizen.address.id === address.id) {
        return citizen.name
      }
      return ''
    }, '')
//...
const findBase = (field: string) => {
  return _.find(definitions, (def) => def.field === field)!.id
}
```

**Actual behavior:**

Doesnt:

```ts
[].forEach((field: keyof Data.AddressDataSetMixin) => {
 //...
 /*
[ts]
Argument of type '(field: "number" | "id" | "name" | "date" | "type" | "street" | "full" | "picture" | "cadastrador...' is not assignable to parameter of type '(value: string, index: number, array: string[]) => void'.
  Types of parameters 'field' and 'value' are incompatible.
    Type 'string' is not assignable to type '"number" | "id" | "name" | "date" | "type" | "street" | "full" | "picture" | "cadastrador" | "las...'.
 */
})
//...
_.reduce(citizens, (name, citizen) => {
/*
Argument of type '(name: string, citizen: RemoteArrayProxy<CitizenDataSet>) => string | undefined' is not assignable to parameter of type 'MemoIterator<RemoteArrayProxy<CitizenDataSet>, string | undefined>'.
  Types of parameters 'name' and 'prev' are incompatible.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.'
*/
      if (citizen.address && citizen.address.id === address.id) {
        return citizen.name
      }
      return ''
    }, '')
// ...
const findBase = (field: string) => {
  /*
 Property 'field' does not exist on type '{}'
  */
  return _.find(definitions, (def) => def.field === field)!.id
}
```

**Comment by andy-ms** [comment]
Was probably broken by #18654? See if setting `"strictFunctionTypes": false` works.

**Comment by pocesar** [comment]
yes, it works
