### ISSUE TITLE
"Class XXX used before its declaration" breaking change in 2.3.0

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/TypeScript#15102]
**TypeScript Version:**  typescript@rc 2.3.0

**Code**

```ts
export interface IconProps {
    size?: number;
}

// I use this to create a type that has `size` non-nullable 
// (because it always present due to `defaultProps`
type SafeProps = IconProps & typeof Icon.defaultProps;

export default class Icon extends React.Component<IconProps, any> {
    static defaultProps = {
       size: 10
    };

    render() {
        // cast to SafeProps to safely extract `size`
        const { size } = this.props as SafeProps
        return <div style={{ size }} />
    }
}
```

**Expected behavior:**
It compiles. This actually works in 2.2.2

**Actual behavior:**

`Class 'Icon' used before its declaration` on line `type SafeProps = IconProps & typeof Icon.defaultProps;
`

Is this an intended breaking change?

**Comment by sandersn** [comment]
Looks like references to block-scoped variables should be allowed inside `typeof` in a type.

**Comment by gcnew** [comment]
There is a similar PR for `const` - https://github.com/Microsoft/TypeScript/pull/14700. May it get merged as well?

**Comment by sandersn** [comment]
Yes, I'll go ahead and merge it after resolving conflicts.

**Comment by andy-ms** [comment]
This is still showing errors if the class and its use are in separate files.

**a.ts**
```ts
let foo: typeof C;
```

**b.ts**
```ts
class C {}
```

**tsconfig.json**
```json
{
  "compilerOptions": {
      "outFile": "foo"
  }
}
```

Shows: `src/a.ts(1,17): error TS2449: Class 'C' used before its declaration.`

**Comment by mhegazy** [comment]
tracking as https://github.com/Microsoft/TypeScript/issues/15998

**Comment by tsofist** [comment]
One more case for **2.3.2** and **2.4.0-dev.20170519**:
```ts
export default Some2; //Error:(1, 16) TS2449:Class 'Some2' used before its declaration.

class Some {
    private todo: string;
}

class Some2 {
    private num: number;
}
```
OK for **2.2.2**
It's a same bug?

**Comment by mhegazy** [comment]
> It's a same bug?

that is a new one :)

**Comment by napalm684** [comment]
Same issue with a const:

`export const appConfig: IAppConfig = {
     // Properties with values
};`

![image](https://user-images.githubusercontent.com/8197405/26933757-77fee110-4c35-11e7-8c1e-ef6efe100b3a.png)

**Comment by fsoikin** [comment]
>> It's a same bug?

> that is a new one :)

Should this issue be reopened? Or a new one filed?

**Comment by andy-ms** [comment]
@napalm684 That's because `appConfig` shadows the outer `appConfig`, so it looks like you're trying to initialize a variable to itself.

@tsofist If that is in a single file, I think it's legitimate, because classes aren't hoisted like functions are.

**Comment by fsoikin** [comment]
@andy-ms but this worked just fine before 2.3. The `export default` would just be lowered to the end of the module, that's all:

```
// Compiled for AMD and ES3
define( [...], function() {
   function Some() {
      this.num = 0;
   }
   return Some;
}
```

And the current behavior is a breaking change. Meaning, we have to fix up our codebases to conform.

**Comment by andy-ms** [comment]
If it won't work in a genuine ES6 environment, we won't allow it, even if it happened to work with another kind of emit.
