### PR TITLE
Fix error on extends in declaration file with importHelpers

### LINKED ISSUE #12724: 'extends' is not compiling when used inside declaration file and importHelpers option is switched on
**TypeScript Version:**  2.1.4 / 2.2.0-dev.20161207

**Code**

```ts
interface Animal {
	type: string;
}

export declare class Pet implements Animal {
	public type: string;
	public name: string;
	constructor();
}

export declare class Dog extends Pet {
	public breed: string;
	constructor();
}
```

**Expected behavior:**
Compiles successfully.

**Actual behavior:**
Compilation fails with the following error:
```
error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.
```

The same source code compiles fine on TypeScript 2.1.1. Installed `tslib` package has version 1.2.0.

### PR DESCRIPTION
**Pull request by rbuckton**
The call to `checkExternalEmitHelpers` for the `__extends` helper was incorrectly reporting an error when `extends` was used in a declaration file with `--importHelpers` and a missing `tslib.d.ts` file.

Fixes #12724

### CODE REVIEW

**Comment by rbuckton** [comment]
@mhegazy I chose to be explicit about the check as I wanted to avoid walking up the spine to check for an ambient context every time we call this function. `extends` currently is the only case where this matters.

**Comment by dtabuenc** [comment]
I'm also seeing this on destructuring in angular2:
`node_modules/@angular/core/src/metadata/di.d.ts(178,48): error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.`

The d.ts it's complaining about is:
```javascript
    (selector: Type<any> | Function | string, {descendants, read}?: {
        descendants?: boolean;
        read?: any;
    }): any;
    new (selector: Type<any> | Function | string, {descendants, read}?: {
        descendants?: boolean;
        read?: any;
    }): Query;
```

I don't get why it says tslib cannot be found though. A `--traceResolution` shows that tslib is succesfully resolved from `node_modules` folder many times.

**Comment by mhegazy** [comment]
@dtabuenc, have you tried with `typescript@next`?

**Comment by dtabuenc** [comment]
Yeah I tried with with typescript@next installed minutes before I posted.
