### ISSUE TITLE
Update typescript from 4.2.4 to 4.6.4,get error

### ISSUE THREAD

**Issue by keyiis** [microsoft/TypeScript#48947]
When I update typescript from 4.2.4 to 4.6.4,I get error
```
D:/douyin/src/index.ts(1,15): error TS6059: File 'D:/douyin/common/index.ts' is not under 'rootDir' . 'rootDir' is expected to contain all source files.
```
If I downgrade owngrade typescript to 4.2.4,it works. Therefore, the new version of typescript must have made some adjustments, which led to the problem。I used `gulp-typescript` to build my app,below is directory structure
```
d:/douyin
---src
    ---index.ts
---common
    ---index.ts
---tsconfig.json
---gulp.js
```
**tsconfig.json**
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "removeComments": true,
        "skipLibCheck":true,
        "sourceMap": true,
        "declaration": false,
        "pretty": true,
        "lib": [
            "es2015",
            "es2016",
            "es2017"
        ],
        "baseUrl": ".",
        "paths": {
            "@common/*": [ "src/common/*" ]
        }
    }
}
```
**src/index.ts**
```
import {a} from '@common';
...
```
gulp.js
```
const PROJECT_PATH='D:/douyin/src',DIST_PATH='D:/douyin/dist';
gulp.src([`${PROJECT_PATH}/**/*.ts`], { base: `${PROJECT_PATH}` }).pipe(tsProject()).pipe(gulp.dest(DIST_PATH));

**Comment by MartinJohns** [comment]
It's a gulp-typescript issue: https://github.com/ivogabe/gulp-typescript/issues/667#issuecomment-994017484

**Comment by keyiis** [comment]
@MartinJohns Thks reply! If I don't use gulp-typescript, is there any other alternative?
