### ISSUE TITLE
Generic argument type inference regression in TS 3.4

### ISSUE THREAD

**Issue by ulrichb** [Microsoft/TypeScript#30074]
**TypeScript Version:**  3.4.0-dev.20190223

**Search Terms:** 3.4 inference generic readonly 

**Code**

The following snippet emits an error in TS 3.4 whereas in TS 3.3 it compiles fine.

```ts
class ErrorResult {
    readonly isError = true;

    static combine(errorResults: ReadonlyArray<ErrorResult>): ErrorResult {
        return new ErrorResult(/* ... combine errorResults ... */);
    }
}

//

function extractAndCombineErrorResults<T, TErrorResult extends ErrorResult>(
    allResults: ReadonlyArray<T | TErrorResult>,
    combine: (details: ReadonlyArray<TErrorResult>) => TErrorResult,
): ReadonlyArray<T> | TErrorResult {

    return /* dummy result: */ [];
}

//

interface SomeResult {
    isSomeResult: true
}

const allResults: ReadonlyArray<SomeResult | ErrorResult> = [];

// Here the inference doesn't work anymore:
const result1: ReadonlyArray<SomeResult> | ErrorResult =
    extractAndCombineErrorResults(allResults, ErrorResult.combine);

// Explicit generic args work:
const result2: ReadonlyArray<SomeResult> | ErrorResult =
    extractAndCombineErrorResults<SomeResult, ErrorResult>(
        allResults, ErrorResult.combine);
```

Command line: `npx tsc TypeScriptIssue.ts`

**Expected behavior:**
No compile error.

**Actual behavior:**

TSC emits

```plain
TypeScriptIssue30074.ts:28:7 - error TS2322: Type 'ErrorResult | readonly (ErrorResult | SomeResult)[]' is not assignable to type 'ErrorResult | readonly SomeResult[]'.
  Type 'readonly (ErrorResult | SomeResult)[]' is not assignable to type 'ErrorResult | readonly SomeResult[]'.
    Type 'readonly (ErrorResult | SomeResult)[]' is not assignable to type 'readonly SomeResult[]'.
      Type 'ErrorResult | SomeResult' is not assignable to type 'SomeResult'.
        Property 'isSomeResult' is missing in type 'ErrorResult' but required in type 'SomeResult'.

28 const result1: ReadonlyArray<SomeResult> | ErrorResult =
         ~~~~~~~
```

**Playground Link:** [(works in TS 3.3)](https://www.typescriptlang.org/play/#src=class%20ErrorResult%20%7B%0A%20%20%20%20readonly%20isError%20%3D%20true%3B%0A%0A%20%20%20%20static%20combine(errorResults%3A%20ReadonlyArray%3CErrorResult%3E)%3A%20ErrorResult%20%7B%0A%20%20%20%20%20%20%20%20return%20new%20ErrorResult(%2F*%20...%20combine%20errorResults%20...%20*%2F)%3B%0A%20%20%20%20%7D%0A%7D%0A%0A%2F%2F%0A%0Afunction%20extractAndCombineErrorResults%3CT%2C%20TErrorResult%20extends%20ErrorResult%3E(%0A%20%20%20%20allResults%3A%20ReadonlyArray%3CT%20%7C%20TErrorResult%3E%2C%0A%20%20%20%20combine%3A%20(details%3A%20ReadonlyArray%3CTErrorResult%3E)%20%3D%3E%20TErrorResult%2C%0A)%3A%20ReadonlyArray%3CT%3E%20%7C%20TErrorResult%20%7B%0A%0A%20%20%20%20return%20%2F*%20dummy%20result%3A%20*%2F%20%5B%5D%3B%0A%7D%0A%0A%2F%2F%0A%0Ainterface%20SomeResult%20%7B%0A%20%20%20%20isSomeResult%3A%20true%0A%7D%0A%0Aconst%20allResults%3A%20ReadonlyArray%3CSomeResult%20%7C%20ErrorResult%3E%20%3D%20%5B%5D%3B%0A%0A%2F%2F%20Here%20the%20inference%20doesn't%20work%20anymore%3A%0Aconst%20result1%3A%20ReadonlyArray%3CSomeResult%3E%20%7C%20ErrorResult%20%3D%0A%20%20%20%20extractAndCombineErrorResults(allResults%2C%20ErrorResult.combine)%3B%0A%0A%2F%2F%20Explicit%20generic%20args%20work%3A%0Aconst%20result2%3A%20ReadonlyArray%3CSomeResult%3E%20%7C%20ErrorResult%20%3D%0A%20%20%20%20extractAndCombineErrorResults%3CSomeResult%2C%20ErrorResult%3E(%0A%20%20%20%20%20%20%20%20allResults%2C%20ErrorResult.combine)%3B)

**Possibly related:** #29435

**Comment by ahejlsberg** [comment]
This is working as intended and is an effect of #29847. In your example, we now end up making inferences from the `allResults` parameter which we previously wouldn't do. Therefore, in the `result1` assignment we now infer `SomeResult | ErrorResult` for `T`, and we'll make that inference even if you omit the type annotation for `result1` (where previously we'd then infer `{}` for `T`).

**Comment by ulrichb** [comment]
Hi @ahejlsberg,

ah, now I see that in TS 3.3 the inference comes from the result assignment (without, it inferred `ReadonlyArray<SomeResult | ErrorResult> | ErrorResult`).

Many thanks for your reply!

---

I've now found an alternative solution to make inference work again (based on the second `combine` argument, which fixates `TErrorResult`) using `Exclude<T, TErrorResult>` for the result.

```TS
// ...

function extractAndCombineErrorResults<T, TErrorResult extends ErrorResult>(
    allResults: ReadonlyArray<T>,
    combine: (details: ReadonlyArray<TErrorResult>) => TErrorResult,
): ReadonlyArray<Exclude<T, TErrorResult>> | TErrorResult {

    return /* dummy result: */ [];
}

//

const allResults: ReadonlyArray<SomeResult | ErrorResult> = [];

const result: ReadonlyArray<SomeResult> | ErrorResult =
    extractAndCombineErrorResults(allResults, ErrorResult.combine);
```
