### PR TITLE
Add heuristic for extracting irreducible `null` and `undefined` types from intersections of unions

### LINKED ISSUE #33130: Expression produces a union type that is too complex to represent
**TypeScript Version:**  3.6.2

**Search Terms:**
- union type
- partial

**Repo**
1. `git clone https://github.com/Microsoft/typescript-template-language-service-decorator`
1. `npm install`
1. Open `src/template-language-service-decorator.ts`
1. On line 44, remove the any cast on the line:

    ```ts
        for (const { name, wrapper } of this._wrappers) {
            (intercept[name] as any) = wrapper(languageService[name]!.bind(languageService));
        }
    ```

1. Try compiling the project

**Expected behavior:**
This compiles with TS 3.4

**Actual behavior:**
Compile fails with TS 3.5+

```
src/template-language-service-decorator.ts:44:13 - error TS2590: Expression produces a union type that is too complex to represent.

44             intercept[name] = wrapper(languageService[name]!.bind(languageService));
               ~~~~~~~~~~~~~~~
```

The code likely needs to be rewritten here but I'm opening this issue to make sure the error is expected

**Playground Link:** 

**Related Issues:**

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #33130

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot test this
@typescript-bot user test this
@typescript-bot run dt

**Comment by weswigham** [comment]
For the third time today, once again the tser baselines are just today's as yet uncaptured/accepted update (just changes in upstream projects), so are clean~

**Comment by sandersn** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -9996,6 +9996,16 @@ namespace ts {
             return true;
         }
 
+        function extractIrreducible(types: Type[], flag: TypeFlags) {
+            if (every(types, t => !!(t.flags & TypeFlags.Union) && some((t as UnionType).types, tt => !!(tt.flags & flag)))) {
```
Comment (sandersn) [inline src/compiler/checker.ts]: could you add Null and Undefined to TypeFlags.IncludesMask to avoid the second check?

actually, would it be possible to add a special TypeFlags.EveryUnion that gets calculated in `addTypesToIntersection` and then added to `includes`? This uses up another TypeFlags, but is faster than trying to return two things. So..maybe not worth it.

I do notice that the two calls to extractIrreducible might iterate `typeSet` twice whenever it contains all-unions, but doesn't have any `null` or `undefined`s.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -10114,6 +10124,12 @@ namespace ts {
                         // reduced we'll never reduce again, so this occurs at most once.
                         result = getIntersectionType(typeSet, aliasSymbol, aliasTypeArguments);
                     }
+                    else if (extractIrreducible(typeSet, TypeFlags.Undefined)) {
+                        result = getUnionType([getIntersectionType(typeSet), undefinedType], UnionReduction.Literal, aliasSymbol, aliasTypeArguments);
```
Comment (sandersn) [inline src/compiler/checker.ts]: shouldn't we run both, for large intersections of the form `x | null | undefined & ...`?

**Comment by ahejlsberg** [comment]
Hmm, that perf run definitely looks odd. Seems like _everything_ slowed down by 5-7%.

**Comment by weswigham** [comment]
@typescript-bot perf test this

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: we do - note the recursive `getIntersectionType` call (which is needed to recalculate includes for the now filtered type set)

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts]: > could you add Null and Undefined to TypeFlags.IncludesMask to avoid the second check?

Nope, because we're looking for members-of-members that are undefined-or-null. We'd need 3 brand new flags (null and undefined are already used to track weather the intersection itself contains them). We only have two unused type flags, sooo.... Yeah. This already bails early in every common scenario, the worst case where it's not needed is soemthing like a 52 element union where the first 51 contain `undefined`, but the 52nd contains `null`, which is irreducible and, notably, will trigger the "excessively large union" check in the `else` clause once the filtering fails, and cease to do _any_ more work. So the "worst case" is either the case where it needs to occur and all the work needs to be done, or where it's very close to that but not, and will likely be converted to `any`, anyway.

**Comment by weswigham** [comment]
@typescript-bot cherry-pick this into release-3.6
