### ISSUE TITLE
Union Type inference not working in class (ts version 1.4)

### ISSUE THREAD

**Issue by erichillah** [microsoft/TypeScript#1706]
Hi,
Union type inference is not working inside classes functions. For example trying to compile the below code : 

``` TypeScript
type NameOrNameArray = string | string[];

class NameCreator {

    constructor(public name:NameOrNameArray) {}

    createName():string {
        if (typeof this.name === "string") {
            return name;
        }
        else {
            this.name.forEach((elem)=>{
                console.log(elem);
            });
            return this.name.join(" ");
        }
    }
}
```

gives the error : 

```
Property 'forEach' does not exist on type 'string | string[]'.
```

The same code works well when using a function. Same error in Visual studio and in the Playground.

**Comment by erichillah** [comment]
I am able to remove the error only by using explicit cast
````TypeScript
(<string[]>this.name).forEach((elem)=>{
    console.log(elem);
 });
 return (<string[]>this.name).join(" ");
````

**Comment by ahejlsberg** [comment]
Type guards only work on simple variables, not properties of an object, so you need to copy the property into a local variable.
```TypeScript
type NameOrNameArray = string | string[];

class NameCreator {

    constructor(public name: NameOrNameArray) {}

    createName(): string {
        var name = this.name;  // Copy into variable
        if (typeof name === "string") {
            return name;
        }
        else {
            name.forEach(elem => {
                console.log(elem);
            });
            return name.join(" ");
        }
    }
}
```
We have this restriction because we want to track (to the best of our abilities) that there are no assignments to the variable in the guarded section. This is pretty much impossible to do correctly for properties without extensive flow and alias analysis. For example:
```typescript
function printString(s: string) { ... }
class Foo {
    name: string | string[];
    foo() {
        if (typeof this.name === "string") {
            this.bar();
            printString(this.name);  // Ok?
        }
    }
    bar() {
        this.name = ["hello"];
    }
}
```
This is just a simple example. You can construct increasingly impossible ones with little effort.

A possible alternative to our current design is to allow type guards to work on dotted names of the form `x.y.z` or `this.x.y.z` and to ignore the effects of assignments to such names (or parts of them). But it would mean that we wouldn't catch errors like the one in the example above.

**Comment by erichillah** [comment]
Thanks, i get a much better undertanding of type guard. The use of class properties or 'global variables' doesn't really make sense as it's pretty much impossible to make sure that the condition `typeof this.name === "string" ` will still be true accross the type guarded scope. So i guess it'll still be confusing to allow dotted name in type guards.

**Comment by antoinerousseau** [comment]
is this issue going to be fixed?

**Comment by RyanCavanaugh** [comment]
We still need to work out the exact semantics of how this would work. It's less clear exactly what forms should be allowed since non-local effects are much easier on class members. Consider, for example:

```ts
class Thing {
	x: string|number;
	
	ensureXisString() {
		this.x = this.x.toString();
	}	
	
	someMethod() {
		if(typeof this.x === 'number') {
			this.ensureXisString();
			// Narrowed to this.x: number here, which is 100% wrong
		}
	}
}
```

**Comment by danieljsinclair** [comment]
It would be nice if type guards recognised `Array.isArray()`

this doesn't seem to work either (v1.4) 
    `instanceof Array`

**Comment by ahejlsberg** [comment]
@danieljsinclair The `x instanceof Array` issue was fixed in #1657.

**Comment by RyanCavanaugh** [comment]
Tentatively approved. Need to see how this impacts real-world code.

**Comment by sparr** [comment]
I am encountering a similar problem with type inference inside an indexed type, is it the same bug or should I open a new one?

```
type Thing = { name: string; };
type Things = Array<Thing>;
type ThingOrThings = Thing | Things;

var thing: ThingOrThings = { name: "sam" };
thing.name = "pat"
// ts correctly infers that thing is a Thing that has .name
var things: ThingOrThings = [{ name: "sam" },{ name: "ash" }];
things[0].name = "pat"
things.map(x => x)
// ts correctly infers that things is a Things, an array I can index or .map()

interface ThingMap { [key: string]: ThingOrThings; }
var thingmap: ThingMap = { thing: { name: "sam" }, things: [{ name: "sam" },{ name: "ash" }] };
thingmap.thing.name = "pat";
// How is thingmap.thing here functionally different from thing above? they have the same contents and the same type
thingmap.things[0].name = "pat";
// How is thingmap.things here functionally different from things above? they have the same contents and the same type

```

**Comment by jakebailey** [comment]
Just looking at old issues; this one was fixed in TS 2.0 when control flow analysis was introduced.
