### ISSUE TITLE
@ts-ignore is broken in 3.6 when code line is broken into 2 line

### ISSUE THREAD

**Issue by regevbr** [microsoft/TypeScript#33256]
**Search Terms:**
@ts-ignore
ts-ignore
ignore
multiline
**Code**

```ts
const veryLongStructureNameWithFooInside = {
  foo: (x: number): Promise<number> => {
    return Promise.resolve(x);
  },
};
// @ts-ignore
veryLongStructureNameWithFooInside
  .foo() // Notice the line break here caused by prettier
  .then((result) => {
    console.log(result);
  })
  .catch((err) => {
    console.log(err);
  });
```

**Expected behavior:**

There should be no errors as `@ts-ignore` is set on the function call (works in 3.5.2)

**Actual behavior:**

In next version the following error occurs:
```bash
error TS2554: Expected 1 arguments, but got 0.

   .foo()
      ~~~~~

      foo: (x: number): Promise<number> => {
               ~~~~~~~~~
    An argument for 'x' was not provided.
```

**Playground Link:** 
[playground](https://typescript-play.js.org/?noImplicitAny=false#code/MYewdgzgLgBAbgUwE4E8Ay4DmBlKSCuwU+SCAcgIYC2CA6gJZQAWAYiCAJKT0AmCMAXhgBvAFAwYAM3YAuGAAoAHnLD4qAI2QBKOQAUkIKvQgIAPKo3IAfIJtiJE0sSRgY+w8YQA6UhBAAbRCUtAG5xGABfABpRCLCAeniYAAEoCABaekwwEFJRRFQMMBw8QmdyajpGVnYuCF4EcK9pEHktJuYEMHl5X3x-KC1bEXCJUEgA738QTF6ECH7BsIkI9okvYAooYCYe5CQhgTtRmHG-fymZ+X3Q8NWQoA)

**Comment by sandersn** [comment]
Here's a smaller repro:

```ts
const x = {
  foo: (x: number) => {
    return x;
  },
};
// @ts-ignore
x
.foo() // Notice the line break here caused by prettier
```

This is definitely a regression in 3.6, although the new behaviour seems right to me -- I believe ts-ignore is defined in terms of lines, not expressions. It makes ts-ignore + prettier hard to use consistently though.

**Comment by regevbr** [comment]
@sandersn is there a chance to add it to the 3.6.3 milestone instead? This bug causes me to be "stuck" on 3.5.3

Thanks :-)

**Comment by sandersn** [comment]
3.6.3 just snapped today, but I don't think it'll be in 3.6.4 either, because it seems to be

1. affecting few people 
2. simple-ish to work around
3. not in a core part of the language 
4. tricky to fix
5. arguably correct

**Comment by regevbr** [comment]
Will it be easier to add a way to ignore next x lines? I can't add the ts-ignore comment in between those 2 lines as it breaks javascript, and it might be useful to add the x lines features for other use cases where you want multiple lines ignored...

**Comment by lamontadams** [comment]
This is also affecting React tsx components broken across multiple lines, which is problematic because quite a few React components tend to have poor or unmaintained typings. Prior to 3.6 I could `ts-ignore` a single property assignment by putting it on one line and still have type support for the other properties exposed by a component. Now I have to ignore the entire component declaration when this happens - and it really frustrates my efforts to get the rest of my team sold on Typescript.

FYI - I wound up here after filing https://github.com/microsoft/vscode/issues/80715 against VSCode.

**Comment by sandersn** [comment]
@lamontadams Are you running to problems with React components interacting with prettier? If not, can you give an example of a non-prettier-induced problem?

@regevbr

ts-ignore is an intentionally simple feature. I'm loathe to add to it unless we can come up with a good, simple fix for this problem.

Here are some possible fixes:

1. Pre-format your code and put the ts-ignore where it should go:

```ts
x
// @ts-ignore
.foo()
```

2. Use prettier-ignore

https://prettier.io/docs/en/ignore.html

prettier-ignore (1) attaches to the following node and (2) ignores comments so you can stack both ignores:

```ts
// prettier-ignore
// @ts-ignore 
x.foo()
```

3. Maybe check before prettier formatting? This approach seems brittle since checking could happen at many points during the lifetime of source code.

**Comment by turadg** [comment]
> can you give an example of a non-prettier-induced problem?

I'm encountering this in 3.6.3 and 3.7.0-beta… not sure whether it's a different issue. What I see is that only the last ts-ignore on JSX props works. Examples here with Storybook dynamic values.

This
```
      <UITooltip
        // @ts-ignore
        position={select('Tooltip position', positions, positions[0])}
        // @ts-ignore
        variant={select('Tooltip variant', ['micro', 'none'], 'none')}
      >
```
fails with,
```
No overload matches this call.
  Overload 2 of 2, '(props: ButtonProps, context?: any): UILinkButton', gave the following error.
    Type 'string' is not assignable to type '"none" | "active" | "alert" | "basic" | "borderless" | "inverted" | "invertedWhite" | "revert" | "rounded" | "social" | "suggestion" | "white" | "whiteBorder" | "whiteBorderless" | "whiteBorderRounded" | undefined'.
  Overload 2 of 2, '(props: ButtonProps, context?: any): UILinkButton', gave the following error.
    Type 'string' is not assignable to type '"auto" | "fill" | undefined'.
```

The same as taking out the first ts-ignore. If I fix that first error, the remaining ts-ignore works,
```
      <UITooltip
        position={
          select('Tooltip position', positions, positions[0]) as PositionLabel
        }
        // @ts-ignore
        variant={select('Tooltip variant', ['micro', 'none'], 'none')}
      >
        {text('Tooltip text', "I'm a tooltip")}
      </UITooltip>
```

**Comment by sandersn** [comment]
@turadg that's a different issue that sounds like a bug or at least *different* surprising behaviour. Can you open a separate bug for it? I need a more complete repro to understand what is going on.

**Comment by lamontadams** [comment]
@sandersn the repro from @turadg looks similar to the issue I'm seeing in TSX files. It doesn't seem to be involved with prettier at all. See https://github.com/microsoft/vscode/issues/80715 for the example I put together when I thought this was just a vscode issue.

**Comment by sandersn** [comment]
@lamontadams yes you're running into #33795 that @turadg filed. Let's discuss the solution there.
