### PR TITLE
No error referring to UMD symbol in CommonJS modules

### LINKED ISSUE #22969: Namespace defined in .d.ts is no longer accessible from node .js file
**TypeScript Version:**  2.8.1

**Search Terms:** refers to a UMD global, but the current file is a module. Consider adding an import instead.

**Code**

externs.d.ts
```ts
export as namespace Puppeteer;
export interface TargetInfo {
  type: string;
  targetId: string;
  title: string;
  url: string;
  attached: boolean;
}
```

target.js
```js
const fs = require('fs');
class Target {
  /**
   * @param {!Puppeteer.TargetInfo} targetInfo
   */
  constructor(targetInfo) {}
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "noEmit": true,
    "allowJs": true,
    "checkJs": true,
    "target": "es2017"
  },
  "include": [
    "."
  ]
}
```

Setup
```bash
npm init
npm install --save-dev typescript
npm install --save-dev @types/node
npx tsc -p .
```

**Expected behavior:**
Everything runs successfully

**Actual behavior:**
`Target.js(4,15): error TS2686: 'Puppeteer' refers to a UMD global, but the current file is a module. Consider adding an import instead.`

When attempting to upgrade Puppeteer to use Typescript 2.8, we ran into this issue with our externs file. This previously worked on 2.7.2. See https://github.com/GoogleChrome/puppeteer/issues/2279

The externs file method we were using did feel pretty hacky. The error message is right in that we are using something defined as a UMD global in a node module. But I don't have a better solution.

### PR DESCRIPTION
**Pull request by sandersn**
In Javascript CommonJS modules, references in JSDoc can refer to UMD symbols, the way that they could before 2.8.

Fixes #22969

### CODE REVIEW

**Comment by mhegazy** [comment]
Please port to release-2.8 as well.

**Comment by sandersn** [comment]
OK, it's in 2.8 now.
