### PR TITLE
String literal apparent types with specific member types

### LINKED ISSUE #19837: Fails to get contextual type for string literal in array
**TypeScript Version:**  2.7.0-dev.20171108

**Code**

```ts
const x: 'a' | 'a'[] = ['a'];
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(1,7): error TS2322: Type 'string[]' is not assignable to type '"a" | "a"[]'.
  Type 'string[]' is not assignable to type '"a"[]'.
    Type 'string' is not assignable to type '"a"'.
```

Was broken by #19733 -- verified by testing with its merge commit and with the previous commit. @weswigham 
Detected by running DefinitelyTyped tests.

### PR DESCRIPTION
**Pull request by weswigham**
As mentioned in #19837, calculating the apparent type of union members correctly exposed some undesired behavior with respect to the contextual type produced by the union of a string literal type and an array. The root cause is the index signature in the global string type; so another way to fix the issue is to give string literal type more specific apparent types than the global string type. In this PR, I create a cached apparent type (similar to what we do for intersections) for string literal types which has exact types for the 0 through N properties of the string, based on the text of the literal, and then a more specific index signature based on those types. This also has the nice sideffect of giving you stronger types for `("foo")[2]` (`"o"`) or `keyof "someLiteral"` (all the names on `String` plus `"0"` - N; up to the length of the literal.). Only doing this for the apparent type saves us from comparing these properties during relationships, while still giving us the benefits of stronger property types than the indexer on the original apparent type gives.

Fixes #19837

### CODE REVIEW

**Comment by weswigham** [comment]
@mhegazy You'd probably want to take a look at this alongside my comment on the associated issue.
