### ISSUE TITLE
--pretty flag for build mode (for when tsc in not running in a tty)

### ISSUE THREAD

**Issue by heikomat** [Microsoft/TypeScript#30282]
## Search Terms

- pretty tty
- istty
- build pretty

## Suggestion

I'd like to force pretty outputs in build-mode, even if tsc is not running in a tty.

Currently only `process.stdout.isTTY` determines wether the output in build-mode will use the pretty option or not, and there is no way to overwrite this behaviour (at least none that i know of), as the `--pretty` flag only works in non-build-mode

## Use Cases

I have a monorepo-setup and would like to use a combination of "build-mode" "watch-mode" and "restart my application on successful build".

using [tsc-watch](https://github.com/gilamran/tsc-watch) (which basically spawns tsc and listens to the output) I do get exactly that, but with the caveat that the logs from tsc are now no longer in pretty mode, because tsc is not running in a tty.

Having the log-output in pretty mode would be benifical in this scenario, as it would be easier for a developer to spot errors. Having a `--pretty` flag for build-mode would allow just that, because tsc-watch just passes its arguments to tsc.

## Examples

**build + watch + restart app without pretty-flag:**
`tsc-watch --build --onSuccess 'npm start --prefix server'`
![2019-03-08__23-39-39](https://user-images.githubusercontent.com/20770029/54060027-7fe7b880-41fb-11e9-89c7-5f40076da66f.png)

**build + watch + restart app with pretty-flag:**
`tsc-watch --build --pretty --onSuccess 'npm start --prefix server'`
![2019-03-08__23-38-31](https://user-images.githubusercontent.com/20770029/54059984-5595fb00-41fb-11e9-99c3-116b7f6834e3.png)

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by RyanCavanaugh** [comment]
I'm really confused here. `--build` already supports `--pretty`, as your screenshot shows. What doesn't work today that you'd expect to work?

**Comment by heikomat** [comment]
@RyanCavanaugh This screenshot is doctored. It shows what I'd expect to happen (as described in the hidden description of this section in the issue template)

If you run tsc in build mode in a non interactive shell (aka `process.stdout.isTTY` is false) you won't get pretty output, even with `--pretty`

**Comment by sheetalkamat** [comment]
This may be issue with the project you are using to build your changes. With tsc `--pretty` is allowed and it will show you pretty result.
```
[10:24:04] Starting compilation in watch mode...

../../src/compiler/builder.ts:3:49 - error TS2304: Cannot find name 'ReusableDiagnosticRelatedInformation'.

3     export interface ReusableDiagnostic extends ReusableDiagnosticRelatedInformation {
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../src/compiler/builder.ts:7:30 - error TS2304: Cannot find name 'ReusableDiagnosticRelatedInformation'.

7         relatedInformation?: ReusableDiagnosticRelatedInformation[];
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../src/compiler/builder.ts:271:64 - error TS2304: Cannot find name 'ReusableDiagnosticRelatedInformation'.

271     function convertToDiagnosticRelatedInformation(diagnostic: ReusableDiagnosticRelatedInformation, newProgram: Program): DiagnosticRelatedInformation {
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../src/compiler/builder.ts:654:103 - error TS2304: Cannot find name 'ReusableDiagnosticRelatedInformation'.

654     function convertToReusableDiagnosticRelatedInformation(diagnostic: DiagnosticRelatedInformation): ReusableDiagnosticRelatedInformation {
                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[10:24:13] Found 4 errors. Watching for file changes.

```

**Comment by heikomat** [comment]
@sheetalkamat yes, the `--pretty` flag does work on its own, but **not in combination with `--build`!**

In Short, **This does happens:**
- `--pretty` on any shell: output is pretty
- `--build --pretty` on an interactive shell: output is pretty
- `--build --pretty` on a non-interactive shell: **output is not pretty**

In Short, **This should happens:**
- `--pretty` on any shell: output is pretty
- `--build --pretty` on an interactive shell: output is pretty
- `--build --pretty` on a non-interactive shell: **output is pretty**

**Comment by sheetalkamat** [comment]
@heikomat got it. Thanks for making it clear. This seems a bug in `tsc`
