### ISSUE TITLE
instanceof type inference broken in an "if -> else if  -> else if" chain

### ISSUE THREAD

**Issue by stkomarov** [Microsoft/TypeScript#11965]
**TypeScript Version:**  "typescript@2.0.6"

```ts
// A *self-contained* demonstration of the problem follows...
class Action1 {
  public constructor(public propA: string) {}
}

class ActionX {

}

class Action2 {
  public constructor(public propB: string) {}
}

class FooBar {

  public handleAction(action: Object): void {
    if (action instanceof Action1) {
      console.log(action.propA); // works
    } else if (action instanceof ActionX) {
      // The presense of this empty clause is essential
    } else if (action instanceof Action2) {
      console.log(action.propB); // throws compile error: Error TS2339: Property 'propB' does not exist on type 'never'.
    }
  }
}
```

**Expected behavior:**
The code to compile without an error.
**Actual behavior:** 
The code above throws a compile error:
Error TS2339: Property 'propB' does not exist on type 'never'.

A **workaround** for the issue is to use an explicit cast for the last "else if" clause: 

```ts
    } else if (action instanceof Action2) {
      const a = action as Action2;
      console.log(a.propB); // now it works
    }
```

**Comment by aluanhaddad** [comment]
This is by correct behavior. TypeScript has a structural type system and all type tests, even `instanceof` are structural. Since instances of `ActionX` are structurally equivalent to `{ }`, the type with non members, and since all types are assignable to `{}`, the type checker determines that the ensuing `else` branch is unreachable.

**Comment by stkomarov** [comment]
> This is correct, expected behavior. TypeScript has a structural type system and all type tests, even instanceof are structural. Since instances of ActionX are structurally equivalent to {}, the type with no members, and since all types are assignable to {}, the type checker determines that the ensuing else branch is unreachable.

The last else if clause is reachable, and the code worked just fine with TS 1.8.10.

As a side note, a workaround for the original issue is to use an explicit cast and the code will compile with typescript 2.0.6: 
`   if (action instanceof Action1) {
      console.log(action.propA); // works
    } else if (action instanceof ActionX) {
      // The presense of this empty clause is essential
    } else if (action instanceof Action2) {
      const a = action as Action2;
      console.log(a.propB); // now it works
    }
`

**Comment by aluanhaddad** [comment]
It is not reachable from the standpoint of structural assignability. Even though it is technically reachable at runtime, because `instanceof` at runtime at runtime compares two references, `instanceof` at compile time compares structurally. The following simplified example illustrates the behavior.
```ts
class FooBar {
    public handleAction(action: Object): void {
        if (action instanceof ActionX) {
            return;
        }
        action // has type never
    }
}
```
