### ISSUE TITLE
TypeScript gets into bad editing state with async arrow functions

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript#37522]
This seems to be an issue with 3.8 and newer. 3.7.5 doesn't exhibit this behavior.

There's a couple of ways to observe this. First, try writing out the following code character-by-character.

```ts
let x = async () => {
    
}
```

You'll get

```
let x = async () => {
        ~~~~~~~~
Cannot find name 'async'.
```

Alternatively, paste the full example into a buffer. Then erase the `c` in `async`.

```ts
let x = asyn () => {
    
}
```

Give it a second, then add it back. TypeScript doesn't seem to refresh its semantic diagnostics for some reason.

You'll get

```
let x = async () => {
        ~~~~
Cannot find name 'asyn'.
```

**Comment by DanielRosenwasser** [comment]
First time I can see this behavior is `3.8.0-dev.20191219`.

**Comment by DanielRosenwasser** [comment]
https://github.com/microsoft/TypeScript/pulls?q=is%3Apr+closed%3A2019-12-17..2019-12-19+is%3Aclosed is probably a reasonable filter to figure out what started this.

**Comment by DanielRosenwasser** [comment]
I'm not 100% sure, but I'm fairly certain this is caused by https://github.com/microsoft/TypeScript/pull/35731. It's one of the only parser changes, and switches a lot of parsing checks on arrow functions to check the modifier list instead of `ModifierFlags`. Maybe @andrewbranch (and even @CyrusNajmabadi, hi!) can help out here.

**Comment by andrewbranch** [comment]
I _am_ interested in incremental parsing and have a vague high-level familiarity with the algorithm, so if @sandersn runs out of time, wants a hand, or just wants to pawn this one off, I’d be happy to take a look.

**Comment by sandersn** [comment]
I'm very likely to be out of time for this release, and I'm not familiar with the algorithm. So I'll give it to you, @andrewbranch 

I remember that PR was the second attempt, after @PranavSenthilnathan and I abandoned the first attempt as "probably a bad idea". It might still be a bad idea!

**Comment by andrewbranch** [comment]
@DanielRosenwasser I can’t reproduce this in VS Code with 3.8.0-dev.20191219, 3.8.3, or current master, or in the playground. Are there any other tricks to get this to happen?

**Comment by andrewbranch** [comment]
@DanielRosenwasser are you still able to reproduce this?

**Comment by andrewbranch** [comment]
No one can reproduce this so I’m going to close... 😬
