### ISSUE TITLE
bug: TS7016 Could not find a declaration file for module

### ISSUE THREAD

**Issue by ikatyang** [Microsoft/TypeScript#14379]
**TypeScript Version:**  2.2.1 / nightly (2.3.0-dev.20170301)

**Command**

```
tsc try.ts --noImplicitAny
```

**Code**

try.ts
```ts
import { x } from 'test'; // error TS7016: Could not find a declaration file for module 'test'.
```

**module** `test`

- package.json

  ```json
  {
    "name": "test",
    "version": "1.0.0",
    "main": "lib/index"
  }
  ```
- lib/index.js

  ```js
  "use strict";
  exports.__esModule = true;
  exports.x = { test: "only" };
  ```

- lib/index.d.ts

  ```ts
  export interface X {
    test: "only";
  }
  export declare const x: X;
  ```

**Expected behavior:**

non-error

**Actual behavior:**

```
try.ts(1,19): error TS7016: Could not find a declaration file for module 'test'. '~/tsc-test/node_modules/test/lib/index.js' implicitly has an 'any' type.
```

It works fine with typescript@2.1.6, or specified `types` field in `package.json`:

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "lib/index",
  "types": "lib/index"
}
```

But I think this is a bug, since the [documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) said:

> Also note that if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so.

**Comment by mhegazy** [comment]
The behavior matches the documentation. the `index.d.ts` is not at the root, it is under `lib`. 

The request to look up `<value of package.json::main>.d.ts` is tracked for https://github.com/Microsoft/TypeScript/issues/9854

**Comment by dhruvdutt** [comment]
Edit your **tsconfig.json**

`"noImplicitAny": false`

**Comment by ikatyang** [comment]
It was not about how to hide the error message but for what strategy does TS use to find declaration files.

I used to think that the "root" means "main" field (`./lib/index.js` in this case)  in `package.json`, so that I just have to place `./lib/index.d.ts` next to `./lib/index.js`.

The fact is that the "root" means where `package.json` stands.

**Comment by dhruvdutt** [comment]
Ah! Alrighty. :+1:

**Comment by TrungRueta** [comment]
I know this question is old. But i got same issue and found way to resolve:
from tsconfig.json of module you made. add :
```json 
"typeRoots": [
            "lib"
        ],```
with "lib" is folder "outDir" value. Assume you put .d.ts files same place with .js file. and it will be good!

**Comment by bennyn** [comment]
> I used to think that the "root" means "main" field (`./lib/index.js` in this case) in `package.json`, so that I just have to place `./lib/index.d.ts` next to `./lib/index.js`.

I agree that [the documentation is quite misleading](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html). It should say "next to `package.json`" instead of "next to `index.js`".
