### ISSUE TITLE
User defined type guards not working with typed this

### ISSUE THREAD

**Issue by tnikodym** [Microsoft/TypeScript#12049]
**TypeScript Version:**  2.0.6

**Code**

```ts
abstract class Base {
    // Does not work    
    sameType<T extends Base>(this: T, arg: Base): arg is T {
        // TODO: check type here    
        return true;    
    }

    // Works    
    sameType2<T extends Base>(arg: Base): arg is T {
        // TODO: check type here    
        return true;    
    }
}

class Class1 extends Base {
    prop: string;
}

declare var a: Base;

if ((new Class1).sameType(a)) {
    // Note that hovering over the method call in vscode shows return type "arg is Class1", which indicates that the generic type was correctly infered. However, hovering over "a" on the next line shows type Base (expected: Class1)

    // Error: 'Property 'prop' does not exist on type 'Base'.'
    a.prop;
}

if ((new Class1).sameType2<Class1>(a)) {
    // No error here, works as expected. 
    a.prop;
}
```

**Expected behavior:**
The code should compile without error. 

**Actual behavior:** 
 Error: 'Property 'prop' does not exist on type 'Base'.'

**Comment by aluanhaddad** [comment]
That is not valid TypeScript code. Please post syntactically valid code.

**Comment by tnikodym** [comment]
@aluanhaddad Can you be more specific? The code compiles fine with **tsc 2.0.6** (apart from the one line commented with "Error: ..." that illustrates the issue).

**Comment by mhegazy** [comment]
Not sure i understand what the type argument is used for, but i would say this should be written as:
```ts
    sameType(arg: Base): arg is this {
        return true;    
    }
```

The method is instantiated once when the class is created and not at every call.

**Comment by jcomputer** [comment]
Here's an alternate illustration of this bug, which is still present in the most recent version ([tested on Typescript playground](http://www.typescriptlang.org/play/#src=interface%20Foo%20%7B%0D%0A%20%20%20%20foo%3A%20string%3B%0D%0A%7D%0D%0Ainterface%20Bar%20%7B%0D%0A%20%20%20%20bar%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Afunction%20isFoo1(object%3A%20%7B%7D)%3A%20object%20is%20Foo%20%7B%0D%0A%20%20%20%20return%20'foo'%20in%20object%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Identical%20to%20isFoo1%2C%20except%20it%20gives%20a%20type%20to%20%60this%60.%0D%0A%2F%2F%20Because%20I%20never%20use%20%60this%60%2C%20this%20function%20should%20be%0D%0A%2F%2F%20effectively%20identical.%0D%0Afunction%20isFoo2(this%3A%20void%2C%20object%3A%20%7B%7D)%3A%20object%20is%20Foo%20%7B%0D%0A%20%20%20%20return%20'foo'%20in%20object%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Union%20type%20using%20both%20values.%0D%0Alet%20test%3A%20Foo%20%7C%20Bar%3B%0D%0A%0D%0Aif%20(isFoo1(test))%20%7B%0D%0A%20%20%20%20%2F%2F%20Here%2C%20as%20expected%2C%20%60test%60%20can%20only%20be%20type%20%60Foo%60.%0D%0A%20%20%20%20test.foo%20%3D%20'hi'%3B%0D%0A%7D%0D%0A%0D%0Aif%20(isFoo2(test))%20%7B%0D%0A%20%20%20%20%2F%2F%20Here%2C%20the%20bug%20occurs%2C%20test%20is%20(Foo%7CBar)%20despite%0D%0A%20%20%20%20%2F%2F%20being%20type%20guarded%20by%20the%20function%20in%20the%20if%0D%0A%20%20%20%20%2F%2F%20statement.%0D%0A%20%20%20%20test.foo%20%3D%20'hi'%3B%0D%0A%7D)).

```
interface Foo {
    foo: string;
}
interface Bar {
    bar: string;
}

function isFoo1(object: {}): object is Foo {
    return 'foo' in object;
}

// Identical to isFoo1, except it gives a type to `this`.
// Because I never use `this`, this function should be
// effectively identical.
function isFoo2(this: void, object: {}): object is Foo {
    return 'foo' in object;
}

// Union type using both values.
let test: Foo | Bar;

if (isFoo1(test)) {
    // Here, as expected, `test` can only be type `Foo`.
    test.foo = 'hi';
}

if (isFoo2(test)) {
    // Here, the bug occurs, test is (Foo|Bar) despite
    // the type guard.
    test.foo = 'hi';
}
```
