### ISSUE TITLE
Doesn't compile with transition from 1.8 to 2.0

### ISSUE THREAD

**Issue by NN---** [Microsoft/TypeScript#9812]
**TypeScript Version:**  1.8.0 / nightly (2.0.0-dev.201xxxxx)

**Code**

```ts
var URL: URL;
```

**Expected behavior:**
This code is correct in 1.8 but not in 2.0.

From 2.0
```ts
a.ts(1,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'URL' must be of type '{ new (url: string, base?: string): URL; prototype: URL; createObjectURL(object: any, options?: O...', but here has type 'URL'.
```

**Actual behavior:** 
To be correct in 2.0 as well.

**Comment by mhegazy** [comment]
this is correct. The declaration previously was not correct. fixing this means that there is no constructor type for `URL`. 

this should work though:

```ts
var URL: {
    prototype: URL;
    new(url: string, base?: string): URL;
    createObjectURL(object: any, options?: ObjectURLOptions): string;
    revokeObjectURL(url: string): void;
}
```
