### ISSUE TITLE
Type, retrieved via function using generic class instance, loses its type information only when returned by class method.

### ISSUE THREAD

**Issue by FrogTheFrog** [microsoft/TypeScript#28521]
This bug is quite strange as it only occurs when returned by a class method method. Without generics or in functions everything works fine.

**TypeScript Version:**  3.2.0-dev.20181114

**Search Terms:**
generic this
generic this loses type 
generic method loses type 

**Code**

```ts
interface PrivateData<T> {
    parent: MyClass<T>;
}

function getPrivate<T>(self: MyClass<T>) {
    return {} as PrivateData<T>;
}

class MyClass<T = string> {
    public data: T | null = null;

    public method1() {
        const parent = getPrivate(this).parent;
        return parent;
    }

    public method2() {
        const parent = getPrivate(this).parent;
    }

    public method3() {
        const C = new MyClass();
        const parent = getPrivate(C).parent;
    }

    public method4() {
        const C = new MyClass();
        const parent = getPrivate(C).parent;
        return parent;
    }

    public method5() {
        const C = new MyClass();
        const parent = getPrivate(C as MyClass<string>).parent;
    }

    public method6() {
        const C = new MyClass();
        const parent = getPrivate(C as MyClass<string>).parent;
        return parent;
    }

    public method7() {
        const C = new MyClass();
        const parent = getPrivate(C as any as MyClass<string>).parent;
    }

    public method8() {
        const C = new MyClass();
        const parent = getPrivate(C as any as MyClass<string>).parent;
        return parent;
    }
}
```

**Expected behavior:**
`parent` in `method1`, `method4`, `method6` and `method8` should have `MyClass<T>` type.

**Actual behavior:**
When compiled in strict mode:
```
test.ts:12:12 - error TS7023: 'method1' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

12     public method1() {
              ~~~~~~~

test.ts:13:15 - error TS7022: 'parent' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

13         const parent = getPrivate(this).parent;
                 ~~~~~~

test.ts:26:12 - error TS7023: 'method4' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

26     public method4() {
              ~~~~~~~

test.ts:28:15 - error TS7022: 'parent' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

28         const parent = getPrivate(C).parent;
                 ~~~~~~


Found 4 errors.
```
Furthermore, while compiled declarations have the following types:
```ts
interface PrivateData<T> {
    parent: MyClass<T>;
}
declare function getPrivate<T>(self: MyClass<T>): PrivateData<T>;
declare class MyClass<T = string> {
    data: T | null;
    method1(): any;
    method2(): void;
    method3(): void;
    method4(): any;
    method5(): void;
    method6(): MyClass<string>;
    method7(): void;
    method8(): MyClass<string>;
}
```
VSCODE insists that `method8` (which has additional cast to `any` type as compared to `method6`) has `any` type in `3.2.0-dev.20181114`, however it works as intended in `v3.1.4`:
**3.2.0-dev.20181114:**
![Broken in 3.2.0-dev.20181114](https://user-images.githubusercontent.com/22381748/48549385-53203600-e8d8-11e8-941b-39b4b0787ed7.png)
**3.1.4:**
![Working in 3.1.4](https://user-images.githubusercontent.com/22381748/48549426-70550480-e8d8-11e8-928a-04a099d6f045.png)

**Workaround:**
Specify method's return type yourself. Typescript will then somehow manage to use correct type and even check if it matches specified type.

**Playground Link:** 
[Playground example](https://www.typescriptlang.org/play/index.html#src=interface%20PrivateData%3CT%3E%20%7B%0A%20%20%20%20parent%3A%20MyClass%3CT%3E%3B%0A%7D%0A%0Afunction%20getPrivate%3CT%3E(self%3A%20MyClass%3CT%3E)%20%7B%0A%20%20%20%20return%20%7B%7D%20as%20PrivateData%3CT%3E%3B%0A%7D%0A%0Aclass%20MyClass%3CT%20%3D%20string%3E%20%7B%0A%20%20%20%20public%20data%3A%20T%20%7C%20null%20%3D%20null%3B%0A%0A%20%20%20%20public%20method1()%20%7B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(this).parent%3B%0A%20%20%20%20%20%20%20%20return%20parent%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20public%20method2()%20%7B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(this).parent%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20public%20method3()%20%7B%0A%20%20%20%20%20%20%20%20const%20C%20%3D%20new%20MyClass()%3B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(C).parent%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20public%20method4()%20%7B%0A%20%20%20%20%20%20%20%20const%20C%20%3D%20new%20MyClass()%3B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(C).parent%3B%0A%20%20%20%20%20%20%20%20return%20parent%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20public%20method5()%20%7B%0A%20%20%20%20%20%20%20%20const%20C%20%3D%20new%20MyClass()%3B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(C%20as%20MyClass%3Cstring%3E).parent%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20public%20method6()%20%7B%0A%20%20%20%20%20%20%20%20const%20C%20%3D%20new%20MyClass()%3B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(C%20as%20MyClass%3Cstring%3E).parent%3B%0A%20%20%20%20%20%20%20%20return%20parent%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20public%20method7()%20%7B%0A%20%20%20%20%20%20%20%20const%20C%20%3D%20new%20MyClass()%3B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(C%20as%20any%20as%20MyClass%3Cstring%3E).parent%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20public%20method8()%20%7B%0A%20%20%20%20%20%20%20%20const%20C%20%3D%20new%20MyClass()%3B%0A%20%20%20%20%20%20%20%20const%20parent%20%3D%20getPrivate(C%20as%20any%20as%20MyClass%3Cstring%3E).parent%3B%0A%20%20%20%20%20%20%20%20return%20parent%3B%0A%20%20%20%20%7D%0A%7D%0A)

**Comment by rotu** [comment]
I think this is fixed in 5.1.6

**Comment by FrogTheFrog** [comment]
I can confirm that it has been fixed with the version 4.7.4.
