### ISSUE TITLE
Can't assign object to variable of type `Object | undefined`

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/TypeScript#15254]
**TypeScript Version:**  nightly (2.3.0-dev.20170413)

**Code**

```ts
const x: Object | undefined = { a: 0 };
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(1,33): error TS2322: Type '{ a: number; }' is not assignable to type 'Object | undefined'.
  Object literal may only specify known properties, and 'a' does not exist in type 'Object | undefined'.
```

Works in `typescript@2.3.0-dev.20170412`!

**Comment by sandersn** [comment]
also repros without strictnullchecks with `Object | string`. It's a really simple fix -- in addition to checking that target *is* `globalObjectType`, check that target *contains* `globalObjectType` if it's a union. I'm not sure why this recently stopped working.

**Comment by sandersn** [comment]
Fix is up at #15257

**Comment by ahejlsberg** [comment]
Looks like this was an unintended effect of #15057. Thanks for fixing.
