### ISSUE TITLE
Google feedback on TS 4.0

### ISSUE THREAD

**Issue by rrdelaney** [microsoft/TypeScript#41516]
This GitHub issue contains retroactive feedback on the TS 4.0 release from the team that is responsible for keeping Google's internal software working with the latest version of TypeScript. We successfully upgraded Google from TypeScript 3.9 to 4.0.5 on November 6th, 2020. We're submitting this feedback in the hopes that it's helpful in the future and to report our findings in compiler performance after upgrading.

## Executive Summary

*   We did not have significant difficulty in upgrading Google to TS 4.0.
*   There were no changes in the JavaScript emit that required reworking our tools.
*   We found our overall compilation performance to be flat across TypeScript 3.9 and 4.0.
*   Our [tsickle tool](https://github.com/angular/tsickle) was [updated](https://github.com/angular/tsickle/commit/39f36e82c3d29030a66cae8d48993951c8efcc95) to work with the new compiler API's.

*   Some changes to our TypeScript code were required to make it compile with TS 4.0, most of which were due to new compilation errors which were clearly communicated in the [release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#breaking-changes).

## Impact Summary

| Change                                    | Announced | Libraries Affected |
| ----------------------------------------- | --------- | ------------------ |
| Properties Overriding Accessors (and vice versa) is an Error | Yes       | 0.08%              |
| Operands for delete must be optional      | Yes       | 0.17%              |
| Uninitialized fields used before being defined   | No        | 0.01%              |

## [Properties Overriding Accessors (and vice versa) is an Error](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#properties-overriding-accessors-and-vice-versa-is-an-error)

**This was a well documented breaking change that we were able to automate fixes for.** We found quite a large number of these new errors across our codebase. To fix the errors and unblock ourselves we added `@ts-ignore` comments:

```diff
class A extends B {
+ // TODO: 'property' is defined as an accessor in class 'B', but is overridden
+ // here in 'A' as an instance property.
+ // tslint:disable-next-line:ban-ts-ignore
+ // @ts-ignore
  property: number[] = [];
}
```

## [Operands for delete must be optional](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#operands-for-delete-must-be-optional)

**This was a well documented breaking change that we were able to automate fixes for.** This was the most widespread breakage from TypeScript 4.0, however it was very easy for us to fix. We added a cast the object with a property being deleted to `any` to suppress this error:

```diff
- delete a.b.c;
+ // TODO: The operand of a 'delete' operator must be optional.
+ delete (a as any).b.c;
```

## Uninitialized fields used before being defined

This was the only breaking change we encountered that was not documented in the release notes. We were able to create an automated fixer for this error. TypeScript 4.0 (correctly) began reporting errors for this code sample:

```typescript
class A {
  foo?: number;
  bar = {
    x: 1,
    foo: this.foo // TS2729: Property 'foo' is used before its initialization.
  };
}
```

We were able to work around this error by changing the definition of `foo`:

```diff
class A {
- foo?: number;
+ foo!: number | undefined;
  bar = {
    x: 1,
    foo: this.foo // TS2729: Property 'foo' is used before its initialization.
  };
}
```
