### PR TITLE
Remove carve-out in conditional type instantiation that hopefully has been rendered unneeded

### LINKED ISSUE #50688: 4.7 circular type annotation regression
# Bug Report

### 🔎 Search Terms

"Return type annotation circularly references itself"

### 🕗 Version & Regression Information

The code works in 4.6.4 and stopped working when attempting to upgrade to 4.7+. I also verified the issue still appears in 4.8.X

- This changed between versions 4.6.4 and 4.7

### ⏯ Playground Link

https://github.com/davidmdm/myzod

Issue has been reported with https://github.com/davidmdm/myzod/issues/52

Note that I am not the author of the linked library but rather a user. The author appears to be busy at the moment, so I was creating this ticket to see if the problem was a potential regression on the TypeScript side that could be fixed here instead if that is indeed the root cause.

### 💻 Code

https://github.com/davidmdm/myzod/blob/master/src/types.ts

### 🙁 Actual behavior

The code fails with the following errors

```
node_modules/myzod/libs/types.d.ts:256:40 - error TS2577: Return type annotation circularly references itself.

256     and<K extends AnyType>(schema: K): IntersectionResult<this, K>;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/myzod/libs/types.d.ts:306:40 - error TS2577: Return type annotation circularly references itself.

306     and<K extends AnyType>(schema: K): IntersectionResult<this, K>;
```

### 🙂 Expected behavior

The code compiles successfully.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #50688

This is all good w/ our local test suite, but the extended suite is what matters as, iirc, that's what originally motivated this line. Still, we've changed some other stuff about conditional instantiation since the original change, so hopefully this weird carve-out just isn't needed for compatibility anymore.

### CODE REVIEW

**Comment by weswigham** [comment]
@typescript-bot user test this inline
@typescript-bot test this
@typescript-bot run dt

**Review by sandersn — APPROVED** [review]

**Review by ahejlsberg — APPROVED** [review]
I'm definitely good with removing that carve-out. In fact, I never really understood why it was needed in the first place.

**Review by andrewbranch — APPROVED** [review]
