### ISSUE TITLE
Cannot find module exported member 'default' namespace

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/TypeScript#24798]
**TypeScript Version:**  2.9.1, 3.0.0-dev.20180608

**Search Terms:** 
namespace no exported member default

**Code**

This is the smallest reproduction case I can find.

This seems to be a regression starting in 2.9.1. This worked in 2.8.3.

```ts
// main.ts
import other from "./other";
import * as other2 from "./other";

export const obj = {
  // Unexpected error: Cannot find namespace 'other'.
  [other.name]: 1,
  // Unexpected error (when above line commented out):
  // Namespace '"/Users/OliverJAsh/Development/typescript-playground/src/other"' has no exported member 'default'.
  [other2.default.name]: 1
};
```

``` ts
// other.ts
type Experiment<Name> = {
  name: Name;
};

declare const createExperiment: <Name extends string>(
  options: Experiment<Name>
) => Experiment<Name>;

export default createExperiment({
  name: "foo"
});
```

**Comment by mhegazy** [comment]
here is what i am seeing locally:

```sh
c:\test\24798>type main.ts
// main.ts
import other from "./other";
import * as other2 from "./other";

export const obj = {
    // Unexpected error: Cannot find namespace 'other'.
    [other.name]: 1,
    // Unexpected error (when above line commented out):
    // Namespace '"/Users/OliverJAsh/Development/typescript-playground/src/other"' has no exported member 'default'.
    [other2.default.name]: 1
};

c:\test\24798>type other.ts
// other.ts
type Experiment<Name> = {
    name: Name;
};

declare const createExperiment: <Name extends string>(
    options: Experiment<Name>
) => Experiment<Name>;

export default createExperiment({
    name: "foo"
});

c:\test\24798>type tsconfig.json
{
    "compilerOptions": {
        "target": "es5"
    }
}

c:\test\24798>tsc --v
Version 2.9.1

c:\test\24798>tsc

c:\test\24798>echo %ERRORLEVEL%
0
```

**Comment by OliverJAsh** [comment]
@mhegazy Ah, the error only appears when in watch mode:

```sh-session
$ cat src/main.ts
// main.ts
import other from "./other";
import * as other2 from "./other";

export const obj = {
  // Unexpected error: Cannot find namespace 'other'.
  [other.name]: 1,
  // Unexpected error (when above line commented out):
  // Namespace '"/Users/OliverJAsh/Development/typescript-playground/src/other-ts"' has no exported member 'default'.
  [other2.default.name]: 1
};


$ cat src/other.ts
// other.ts
type Experiment<Name> = {
  name: Name;
};

declare const createExperiment: <Name extends string>(
  options: Experiment<Name>
) => Experiment<Name>;

export default createExperiment({
  name: "foo"
});

$ cat tsconfig.json
{
    "compilerOptions": {
        "target": "es5",
        "outDir": "./target"
    },
    "files": [
        "./src/main.ts"
    ]
}

$ tsc --version
Version 2.9.1

$ tsc

$ tsc --watch
[18:15:01] Starting compilation in watch mode...

src/main.ts:7:4 - error TS2503: Cannot find namespace 'other'.

7   [other.name]: 1,
     ~~~~~


[18:15:02] Found 1 error. Watching for file changes.
```
