### ISSUE TITLE
Unable to cast to generic discriminated union

### ISSUE THREAD

**Issue by helmutschneider** [microsoft/TypeScript#39075]
**TypeScript Version:**  3.9.5

**Search Terms:** discriminated union, generics, cast

**Code**

```ts
enum Color {
    Red,
    Blue,
}
type Attributes = {
    [Color.Red]: {
        a: 'red'
    }
    [Color.Blue]: {
        b: 'blue'
    }
}
type ColorWithAttributes<T extends Color> = { color: T } & Attributes[T]
type ColorLike =
    | ColorWithAttributes<Color.Red>
    | ColorWithAttributes<Color.Blue>

function make<T extends Color>(color: T, args: Attributes[T]): ColorLike {
    const x: ColorWithAttributes<T> = {
        color,
        ...args,
    }
    
    return x as ColorLike // <-- fails with TS2352
}
```

**Expected behavior:**
Cast should not fail. Works correctly on 3.8.3.

**Actual behavior:**
Cast fails with error TS2352.

**Playground Link:** 
[Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=25&pc=1#code/KYOwrgtgBAwg9gGzgJygbwFBW1ASsAEwBoscAhBMYEgXwwBcBPAB2CgEF77kBLAIzD1gAZygBedKWwBteEmQA6fAQC6ALkk4tUAIYaA5MkL6pUOltmIUCilXWbt2Pgb6VgJrXTpNWsK8gB1HnoAC05ufkERAB4AFShgAA8hEAJRORQAPnF0KABjfw14migAMg4uXgEhYWlYlQYWNgzkABkeAGs2MVMAHz95INDwqqjhaJalQky+gZQhsMrImon-GzcZjAAzMBA8+h44ECgIHS64hOTQNLnkTIAKAvkiol1kAHNhDRHlkTqVACUGha7S6DmwBRAwnoUESwP8Cx+1RisWyEkwjgh-hImKgCnxOg+whxOHMOCM9DAyGOiV06X8oOAGDoQA)

**Related Issues:**

**Comment by RyanCavanaugh** [comment]
We should probably widen up the assertability constraint a little here

**Comment by RyanCavanaugh** [comment]
This is fixed. The original example reports TS2352 in TypeScript 3.9.5 and in 4.8.0-dev.20220527, but compiles in the adjacent 4.8.0-dev.20220528 build and current native TypeScript 7.1.0-dev.20260904.1.

That one-day boundary contains [#49119](https://github.com/microsoft/TypeScript/pull/49119), commit [`51b346d`](https://github.com/microsoft/TypeScript/commit/51b346d65a7d5e474a40113f72dc66106715a47a), an intersection-reduction change consistent with the corrected assertion behavior.
