### ISSUE TITLE
Incorrect type inference in promise.all

### ISSUE THREAD

**Issue by kogemrka** [microsoft/TypeScript#35626]
**TypeScript Version:**  3.7.x-dev.201xxxxx

**Search Terms:**

**Code**

```ts
interface A {
    a: number
}

interface B {
    b: number
}

function func(b: B): void {
    console.log(b.b)
}

async function as_a(): Promise<A | undefined> {
    return {a: 10}
}

async function as_b(): Promise<B> {
    return {b: 3}
}

autoExec()

async function autoExec() {
    const [t1, t2] = await Promise.all([as_a(), as_b()])
    func(t2)
}
```

**Expected behavior:**
Works correctly in typescript 3.6.4, but failed to compile in typescript@latest and typescript@next with error `Argument of type 'B | undefined' is not assignable to parameter of type 'B'.`

**Comment by matuella** [comment]
Possibly related to #34937

**Comment by PRR24** [comment]
Not sure, if this is the same problem or just related:
```js
class C1 {
    data1: number;
}

class C2 extends C1 {
    data2: number;
}

async test(): Promise<number> {
    let [c2, c1] = await Promise.all([
        Promise.resolve(<C2[]>[new C2()]),
        Promise.resolve(<C1[]>[new C1()]),
    ]);
    return c2[0].data2;
}

```
-> Error TS2551: Property 'data2' does not exist on type 'C1'. Did you mean 'data1'?

Works correctly with 3.6 but not with 3.7

**Comment by rbuckton** [comment]
This may have been fixed by #34501, as it does not seem to occur in TypeScript 3.9 onward.
