### ISSUE TITLE
Defining generic functional type fails

### ISSUE THREAD

**Issue by xp500** [Microsoft/TypeScript#17114]
**TypeScript Version:**  2.4.1

**Code**

```ts
class A {
}

class B extends A {
  prop: number
}

type C = <S extends A>(p: S) => void;

const a: C = (p: B) => {}
```

**Expected behavior:**
The function a `(p :B) => {}` should be a valid `C` because `B` extends `A`
**Actual behavior:**
Build fails with the following error
```
error TS2322: Type '(p: B) => void' is not assignable to type 'C'.
  Types of parameters 'p' and 'p' are incompatible.
    Type 'S' is not assignable to type 'B'.
      Type 'A' is not assignable to type 'B'.
        Property 'prop' is missing in type 'A'.
```
This used to work in `2.3.4`.

**Comment by kitsonk** [comment]
Dupe of #16985

**Comment by HerringtonDarkholme** [comment]
See this https://github.com/Microsoft/TypeScript/issues/16797#issuecomment-311883044

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
