### ISSUE TITLE
TS 1.8.9 only : Wrong type parameter inside Promise.all().then().

### ISSUE THREAD

**Issue by Jbo31** [Microsoft/TypeScript#7800]
**TypeScript Version:** 

1.8.9

**Code**

```ts
// A self-contained demonstration of the problem follows...
export interface IHiddenColumns {
    hiddenColumns: string;
}

export class HiddenColumnsLoader {

    public loadHiddenColumns(): Promise<void> {

        return new Promise<void>((resolve, reject) => {

            let promises: Promise<IHiddenColumns>[] = [];

            // push promises
           // .forEach(structureContent => {
           //      promises.push(this.loadStructureHiddenColumns(structureContent.rowSectionDefinition, structureContent.columnSectionDefinition, provider));
           // });

            Promise
                .all(promises)
                .then((results) => {

                    // results should be typeof IHiddenColumns[] and not Promise<IHiddenColumns[]>. See stack below
                    this.resolveResults(results);

                    resolve();
                })
        });
    }

    private resolveResults(loadPageResults: IHiddenColumns[]) {
        // resolve
    }
}
```

**Expected behavior:**
Compilation succeeded in Typescript 1.8.7.
Failed in 1.8.9

'results' inside Promise.all().then() should be considered typeof IHiddenColumns[]. Seems to be instead : Promise<IHiddenColumns[]>. See trace below.

**Actual behavior:** 
Compilation failed in 1.8.9 whereas it worked in 1.8.7 (and still works if I backward to 1.8.7).

Here is the stacktrace :
[11:39:07]
42                              this.resolveResults(gridModel, results);
                                                               ~~~~~~~

.../HiddenColumnsLoader.ts(42,37): error TS2345: Argument of type 'Promise<IHiddenColumns>[]' is not assignable to parameter of type 'IHiddenColumns[]'.
  Type 'Promise<IHiddenColumns>' is not assignable to type 'IHiddenColumns'.

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/7566. should be fixed in master and typescript@next.
