### ISSUE TITLE
Spread operator on function call won't work if the spreaded parameter is not the last

### ISSUE THREAD

**Issue by avshyz** [microsoft/TypeScript#39206]
**TypeScript Version:**  3.9.2

**Search Terms:** spread, rest operator, function call

**Code**

```ts
function foo(x: number, y: number, z: number, f: number, aleph: number) { }
function baz(x: number, y: number, z: number) { }

const args: [number, number, number] = [0, 1, 2];

baz(...args);        // working
foo(3, 1, ...args);  // working
foo(1, ...args, 2);  // COMPILER ERROR - Expected 5 arguments, but got 2 or more.(2556)
foo(...args, 3, 2);  // COMPILER ERROR - Expected 5 arguments, but got 2 or more.(2556)
```

**Expected behavior:** given every one of these lines works in js ([see mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_function_calls)), one could expect them to work. Especially given the first two lines worked

**Actual behavior:** The following compilation error
```
Expected 5 arguments, but got 2 or more.(2556)
input.ts(1, 36): An argument for 'z' was not provided.
```

**Playground Link:** [here](https://www.typescriptlang.org/play/index.html?ssl=9&ssc=20&pln=1&pc=1#code/GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOANIgJ455FmUBetBJFyL97AhgDbEAHABac2ASkQBvRAF8AsAChQkWAkSFujTKIbUd7ZrlZkJ0+QsUQEAZyiJupAObWcAbTptKH3d9IBdRABeRFcABkoARkoAJj8AbkVFDS0AOjSHZzEEpVQ0AGZIyjSUjOssxRR0KMRi0pixCtzap2tKAsRo8oUgA)

**Related Issues:** I actually posted it as a comment [here](https://github.com/Microsoft/TypeScript/issues/4130) but thought it might deserve an independent bug report

**Comment by dragomirtitian** [comment]
This actually works on 4.0 [Playground Link](https://www.typescriptlang.org/play/index.html?ts=Nightly#code/GYVwdgxgLglg9mABMOcAUAPAXIsIC2ARgKYBOANIgJ455FmUBetBJFyL97AhgDbEAHABac2ASkQBvRAF8AsAChQkWAkSFujTKIbUd7ZrlZkJ0+QsUQEAZyiJupAObWcAbTptKH3d9IBdRABeRFcABkoARkoAJj8AbkVFDS0AOjSHZzEEpVQ0AGZIyjSUjOssxRR0KMRi0pixCtzap2tKAsRo8oUgA)

This is probably due to https://github.com/microsoft/TypeScript/pull/39094

**Comment by avshyz** [comment]
Oh shame, you're right!
I thought 3.9.2 is the latest version, as it's the latest one shown in the playground.

Thanks for the quick reply

**Comment by MartinJohns** [comment]
> I thought 3.9.2 is the latest version, as it's the latest one shown in the playground.

@avshyz 3.9.2 is currently the latest version. TypeScript 4.0 has not yet been released (currently scheduled for August 2020), but it's available in the playground as a "nightly" version.
