### PR TITLE
Perform intersection reduction before and after getApparentType

### LINKED ISSUE #38542: 3.9 regression: TS2322 error around assignment of an inferred intersection to a union
**TypeScript Version:**  3.9.2, 4.0.0-dev.20200512

**Search Terms:** TS2322, "is not assignable to type"

**Code**

```ts
import * as reflect from 'jsii-reflect'; // Version ^1.5.0

export type ApiElement = reflect.Type | reflect.TypeMember | reflect.EnumMember;

export interface Data {
  readonly element: ApiElement;
}

// Note: reflect.Method and reflect.Initializer both directly or indirectly implement reflect.TypeMember
export function doSomething<T extends (reflect.Method | reflect.Initializer)>(element: T): Data {
  if (reflect.Method.isMethod(element)) {
    // Type 'T & Method' is not assignable to type 'Type'.
    return { element };
  }
  if (reflect.Initializer.isInitializer(element)) {
    // Type 'T & Initializer' is not assignable to type 'Type'.
    return { element };
  }
  // Type checking absolutely fine - why'd previous ones not?
  return { element };
}
```

**Expected behavior:**
It should work like it did in TypeScript 3.8

**Actual behavior:**
```
$ tsc --build
lib/index.ts:13:14 - error TS2322: Type 'T & Method' is not assignable to type 'ApiElement'.
  Type 'T & Method' is not assignable to type 'Type'.

12     return { element };
                ~~~~~~~

  lib/index.ts:6:12
    6   readonly element: ApiElement;
                 ~~~~~~~
    The expected type comes from property 'element' which is declared here on type 'Data'

lib/index.ts:17:14 - error TS2322: Type 'T & Initializer' is not assignable to type 'ApiElement'.
  Type 'T & Initializer' is not assignable to type 'Type'.

16     return { element };
                ~~~~~~~

  lib/index.ts:6:12
    6   readonly element: ApiElement;
                 ~~~~~~~
    The expected type comes from property 'element' which is declared here on type 'Data'
```

**Playground Link:** I stored my repro at https://github.com/RomainMuller/TypeScript39-Bug (public)

**Related Issues:** It appears likely related to the breaking change in #37195 (but not certain)

### LINKED ISSUE #38549: Regression: intersection of a generic type bound to a discriminated union with one of the union constituencies reduces to never
**TypeScript Version:**  3.9.2

**Search Terms:** Generic union intersection

**Code**

```ts
interface A {
  kind: "A";
  a: number;
}

interface B {
  kind: "B";
  b: number;
}

declare const shouldBeB: (A | B) & B;
const b: B = shouldBeB; // works

function inGeneric<T extends A | B>(alsoShouldBeB: T & B) {
  const b: B = alsoShouldBeB;
  //    ~ TS2739: Type 'T & B' is missing the following properties from type 'B': kind, b
}
```

**Expected behavior:**

No errors (were no errors on 3.8)

**Actual behavior:**

```
TS2739: Type 'T & B' is missing the following properties from type 'B': kind, b
```

**Playground Link:** [link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=18&pc=1#code/JYOwLgpgTgZghgYwgAgILIN4FgBQzkDWoAJgFzIBEqFA3LvnOSAK4C2ARtHTgL666hIsRCgBCmeoRLkKo2pPZM2nKNz45cxCAgA2cKCgQB7EAGcwyUwAsjzHcVERR5ABToAPslEBKZADIvbmMzC0UvZABeSxs7BycaZAB6ROQAdyMoAlN+HBhmEAQwYBNkUABxCBBoYAQAHgAVZAgAD0gQYlM0ZE9RAD4XOB1TIwBlGPtHZ2RGgJ8JPGRg82Qw8SjB4bHbCfjJZPx8AD9pkYAmAHYAZgBOcnqATwAHFAByGa8X0s7WYFNTUAA5sgwFYUDAjDodEZUoDkI8oEZnlAihBOjAEaxgU9XqIXuQiO0ADQrXDqIA)

**Related Issues:**

It seems to be related to #36696

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #38542.
Fixes #38549.

### CODE REVIEW

**Comment by DanielRosenwasser** [comment]
@typescript-bot cherry-pick this to release-3.9
