### ISSUE TITLE
vs plugin, 1.5beta regression: can not extend from class in external import

### ISSUE THREAD

**Issue by jasonswearingen** [Microsoft/TypeScript#3243]
this works in older versions.

when I have the following code in 1.5beta:

```
import refs = require("../refs");
var xlib = refs.xlib;

export class PjscBe extends xlib.ClassBase{}
```

I get the following error:
``` 265  Cannot find name 'xlib'.```

this issue goes away if I remove the extends.  I can use my external module in other ways just fine:
```var log = new xlib.diagnostics.logging.Logger(__filename); ```

**Comment by ahejlsberg** [comment]
Which older versions does it work in? Anyway, looks to me like the issue is that you're attempting to reference a variable (`xlib`) in a type name (`xlib.ClassBase`), which isn't possible. It should work if you change the declaration of `xlib` to be an `import`:
```typescript
import refs = require("../refs");
import xlib = refs.xlib;

export class PjscBe extends xlib.ClassBase {}
```
This will enable `xlib` to be used in both value and type positions.

**Comment by jasonswearingen** [comment]
I'm pretty sure this was working in the 1.4 vs plugin, but it might have been in 1.3.

thank you for the solution Anders, ```import xlib = refs.xlib;``` works.  I did not know you could ```import``` without the ```require``` syntax.
