### ISSUE TITLE
Explicit `never` return type in `catch` block & condition in `finally` marks the whole `finally` block as unreachable

### ISSUE THREAD

**Issue by d-fischer** [microsoft/TypeScript#63004]
### 🔎 Search Terms

finally, unreachable, condition, never

### 🕗 Version & Regression Information

- This builds fine in 3.2,
- produces a type error regarding the return type in 3.3 through 3.6,
- and starting 3.7, including the latest native preview, it produces the unreachable code error

### ⏯ Playground Link

https://www.typescriptlang.org/play/?noImplicitAny=false&ts=5.9.3#code/MYewdgzgLgBATgUwA4jlAXDAFAzBDMATwEoYBeAPhjAQDcE5zsFjMb7HKYBvAKBhhQAFnBAB3GAgDcvAL4zeoSLABmIEEzwRCYYNlYwACqIC2ASwgIAPGACuJgEYMqXPgKhxCPfgPgIotnBgMADMMgKyMMB4UMBCzKRuvogoaDjE4TCRKmZgeAA2+V5JAmYq2B62LN6+vkoQIPkIAHT5IADmWABEQghCXRk+ET6yclJAA

### 💻 Code

```ts
function report(e): never {
  throw e;
};

const foo = async (): Promise<number> => {
  try {
    return 3;
  } catch (e) {
    report(e);
  } finally {
    if (true) {
      console.log("heh");
    }
  }
};
```

### 🙁 Actual behavior

```
test.ts:11:5 - error TS7027: Unreachable code detected.

11     if (true) {
       ~~~~~~~~~~~
12       console.log("heh");
   ~~~~~~~~~~~~~~~~~~~~~~~~~
13     }
   ~~~~~

test.ts:12:7 - error TS7027: Unreachable code detected.

12       console.log("heh");
         ~~~~~~~~~~~~~~~~~~~
```

### 🙂 Expected behavior

Builds fine.

### Additional information about the issue

This error vanishes if I do any of the following:

- Remove the explicit `never` return type of `reportError` (although that resurfaces the return type error)
- Remove the call to `reportError` entirely, or the whole `catch` block
- Remove the `if` condition from the `finally` block, but leave in the `console.log` call

I found a similar issue #61259, but it does not include a `catch` block, which is integral to the issue here - although the issues might still be related. Similarly to that issue, the `finally` block also becomes reachable when adding another `return` to the `catch` block, but it is itself unreachable.

**Comment by Andarist** [comment]
https://github.com/microsoft/TypeScript/pull/61265 fixes this too

**Comment by RyanCavanaugh** [comment]
🤖 Thank you for your issue! I've done some analysis to help get you started. This response is automatically generated; feel free to 👍 or 👎 this comment according to its usefulness.

## Similar Issues

Here are the most similar issues I found
- (74%) [microsoft/typescript#34879](https://redirect.github.com/microsoft/typescript/issues/34879): "Unreachable code detected \(7027\)" false positive in 3\.7
- (74%) [microsoft/typescript#44911](https://redirect.github.com/microsoft/typescript/issues/44911): Awaiting a function that returns \`never\` or \`Promise\<never\>\` does not mark the code below as unreachable
- (73%) [microsoft/typescript#59138](https://redirect.github.com/microsoft/typescript/issues/59138): TypeScript does not recognize unreachable code after a method returning never is called outside of its defining scope
- (73%) [microsoft/typescript#39386](https://redirect.github.com/microsoft/typescript/issues/39386): unreachable code detected not work for if clause\.
- (73%) [microsoft/typescript#11307](https://redirect.github.com/microsoft/typescript/issues/11307): 'finally' clause not accounted for in control flow analysis
- (73%) [microsoft/typescript#61259](https://redirect.github.com/microsoft/typescript/issues/61259): Exhaustive switch case with returns can mark a finally block as unreachable
- (72%) [microsoft/typescript#37998](https://redirect.github.com/microsoft/typescript/issues/37998): Arrow function with never return type does not cause unreachable code when called
- (72%) [microsoft/typescript#55329](https://redirect.github.com/microsoft/typescript/issues/55329): The detection to unreachable code is inconsistent 
- (72%) [microsoft/typescript#28153](https://redirect.github.com/microsoft/typescript/issues/28153): In finally block, local variable is incorrectly typed as never with return in try block\.
- (72%) [microsoft/typescript#34955](https://redirect.github.com/microsoft/typescript/issues/34955): Why doesn't awaiting a Promise\<never\> change reachability?
- (71%) [microsoft/typescript#56049](https://redirect.github.com/microsoft/typescript/issues/56049): Unreachable code is not detected for methods that return \`never\`
- (71%) [microsoft/typescript#13154](https://redirect.github.com/microsoft/typescript/issues/13154): Need to return value in a "never" path
- (71%) [microsoft/typescript#53510](https://redirect.github.com/microsoft/typescript/issues/53510): Calling a function that returns never, not always triggers an unreachable code error
- (71%) [microsoft/typescript#49950](https://redirect.github.com/microsoft/typescript/issues/49950): Inconsistent unreachable code detection
- (71%) [microsoft/typescript#10973](https://redirect.github.com/microsoft/typescript/issues/10973): 'Never' is not checked for unreachability

If your issue is a duplicate of one of these, feel free to close this issue. Otherwise, no action is needed.

## Possibly Working as Intended

It looks like this behavior might be intentional. Here's what a computer had to say about it.
