### ISSUE TITLE
Invalid overload checking with equality comparer @1.6.0-beta

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/TypeScript#4619]
# Invalid overload checking with equality comparer @1.6.0-beta

Hi!

I'm currently checking my code with the new 1.6.0-beta versión, and founded the following.

## Code example

``` typescript
(<HTMLInputElement>element).value !== $(element).data("lastValue")
```
## Issue

It works on 1.5.3, but with 1.6.0-beta: `error TS2365: Operator '!==' cannot be applied to types 'string' and 'JQuery'.`.

## Help context

`$.fn.data` has the following overloads (from definitely typed, I had the commit 286c198898978cb6045076c3e47f823a02217b41):

``` typescript
    /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param key A string naming the piece of data to set.
     * @param value The new data value; it can be any Javascript type including Array or Object.
     */
    data(key: string, value: any): JQuery;
    /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param obj An object of key-value pairs of data to update.
     */
    data(obj: { [key: string]: any; }): JQuery;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     *
     * @param key Name of the data stored.
     */
    data(key: string): any;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     */
    data(): any;
```
## What I think...

It shoud choose `data(key: string): any;` but it seems to be working with some of the first or second ones.

OR

Simply checking the `$(element)` and ignoring the `.data("lastValue")`.

OR I should check my code and didn't see what is going on.

**Comment by SergioMorchon** [comment]
By updating my typings (now comit 9ce3cd4ded7536d40b8d65264ad729f442f5a052) it works!
The definitions:

``` typescript
    /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param key A string naming the piece of data to set.
     * @param value The new data value; it can be any Javascript type including Array or Object.
     */
    data(key: string, value: any): JQuery;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     *
     * @param key Name of the data stored.
     */
    data(key: string): any;
    /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param obj An object of key-value pairs of data to update.
     */
    data(obj: { [key: string]: any; }): JQuery;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     */
    data(): any;
```

**Notice the order** of the definitions... why?

**Comment by mhegazy** [comment]
The definition was wrong.  they used to work because of a compiler bug that was picking the last overload. when that was fixed, the issue with the typings manifested.

@DanielRosenwasser submitted a fix to Definitelytyped to updated the typings; so refreshing your local copy should be sufficient to avoid the issue.

**Comment by SergioMorchon** [comment]
Thank you for the explanation @mhegacy!
Fixed after updating my typings :)

**Comment by dardino** [comment]
I think that the correct definition may be this:
`   /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param key A string naming the piece of data to set.
     * @param value The new data value; it can be any Javascript type including Array or Object.
     */
    data(key: string, value: any): JQuery;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     *
     * @param key Name of the data stored.
     */
    data<T>(key: string): T;
    /**
     * Store arbitrary data associated with the matched elements.
     *
     * @param obj An object of key-value pairs of data to update.
     */
    data(obj: { [key: string]: any; }): JQuery;
    /**
     * Return the value at the named data store for the first element in the jQuery collection, as set by data(name, value) or by an HTML5 data-* attribute.
     */
    data<T>(): T;`

**Comment by mhegazy** [comment]
@dardino, this overload `data(obj: { [key: string]: any; }): JQuery;` simply means any object. i think this should not be there.
also this looks like a Definitelytyped issue.
