### ISSUE TITLE
Union type narrowing with generics not working in TS 3.5 RC strict mode

### ISSUE THREAD

**Issue by ford04** [microsoft/TypeScript#31456]
**TypeScript Version:**  3.5.0-rc / next

**Search Terms:** 3.5, 3.5 union, 3.5 strict

**Code**

test.ts:
```ts
function fooT<T = string>(bar: T[] | T | undefined) {
  if (bar !== undefined && !Array.isArray(bar))
    throw new Error("expected array")
  else if (bar !== undefined && bar.length === 0) console.log("empty array")
  else console.log("array or undef.")
}
```

CLI:
```
npx typescript@3.4.5 --strict true test.ts // compiles
npx typescript@next --strict true test.ts // error
```

**Expected behavior:**
Compiles and behaves like ts 3.4.5

**Actual behavior:**
Error:
```
test.ts:4:37 - error TS2339: Property 'length' does not exist on type 'T | T[]'.
  Property 'length' does not exist on type 'T'.
```

**Related Issues:**
Cannot judge, if it is a duplicate of https://github.com/microsoft/TypeScript/issues/31380 .
This is some specific case to base further evaluation on.

**Comment by ahejlsberg** [comment]
This is an effect of #30637. Previously, unconstrained type parameters were treated as if they had the constraint `{}` and therefore could never be `null` or `undefined`. That isn't correct because an unconstrained `T` can be instantiated at *any* type, including `null` or `undefined`. In 3.5 we now check it correctly. That specifically means that `bar !== undefined` doesn't imply that `T` disappears from the type in the false branch.

If you explicitly add a constraint to `T` you get the expected behavior:

```ts
function fooT<T extends {} = string>(bar: T[] | T | undefined) {
    // ...
}
```

**Comment by ford04** [comment]
thank you for clarification @ahejlsberg, should have read the changelog more carefully.
The new constraint is a bit more verbose, but makes sense to me logically.
Closing the issue!
