### PR TITLE
Abstract property access error in own constructor only

### LINKED ISSUE #19197: Abstract property access error occurs in non-abstract class constructors
**TypeScript Version:**  starting from 2.6.0-dev.20171010, 2.6.0-dev.20171015

**Code**

```ts
abstract class Animal {
  public abstract name: string;
}

class Cat extends Animal {
  public name = "Cat";
}

class Foo {
  constructor(animal: Animal) {
    animal.name;
  }
}

new Foo(new Cat());
```

**Expected behavior:**
No compilation error should occur.

**Actual behavior:**
`index.ts(11,12): error TS2715: Abstract property 'name' in class 'Animal' cannot be accessed in the constructor.`
This regression was introduced in #19005, as accessing an abstract property in *any* constructor causes this error, rather than the indented goal of disallowing abstract property accesses only in the constructors of abstract classes that are/extend the abstract class that the abstract property belongs to.

### PR DESCRIPTION
**Pull request by sandersn**
The new check forgot to make sure that the access of the abstract property was inside the constructor of the *declaring* class, not just *any* class. 

Fixes #19197

### CODE REVIEW

**Comment by sandersn** [comment]
@mhegazy since this error is new in 2.6, we should take this fix for 2.6.1.

**Comment by sandersn** [comment]
Good point. I added the check for `this` property accesses.

**Comment by sandersn** [comment]
@RyanCavanaugh mind taking another look?
