### ISSUE TITLE
Error `TS2448` with a static class fields

### ISSUE THREAD

**Issue by dmitriy-tarasov** [Microsoft/TypeScript#15734]
Hi guys,
I see compilation errors `TS2448` with a new version of typescript which looks like some ordering issue: 

**TypeScript Version:**  2.3.2 

**Code**

*test.ts*:
```ts
namespace C {
    export class Name {
        private static funcData = A.AA.func();
        private static someConst = A.AA.foo;
        
        constructor(parameters) {}
    }
}
```
*typings.d.ts*:
```ts
declare namespace A {
    module AA {
        function func();
        const foo = "";
    }
}
```
*tsconfig.json:*
```json
{
    "compilerOptions": {
        "target": "es5",
        "outFile": "./out.js"
    },
    "include": [
        "*.ts" 
    ]
}
```
If I define `files` section in `tsconfig.json` with an explicit and correct files order (`.d.ts` first) such problem will be gone.

**Expected behavior:**
Compiled successfully.
Worked well with TS 2.2 version

**Actual behavior:**
Compilation error: 
```text
test.ts(3,37): error TS2448: Block-scoped variable 'AA' used before its declaration.
test.ts(3,40): error TS2448: Block-scoped variable 'func' used before its declaration.
test.ts(4,38): error TS2448: Block-scoped variable 'AA' used before its declaration.
test.ts(4,41): error TS2448: Block-scoped variable 'foo' used before its declaration.
```

**Note**: It's also reproduced with typescript@next

There are a couple of workarounds I found: 
- Add appropriate imports, like: `import func = A.AA.func`
- Explicitly define files order with a `.d.ts` files at the top (if a project infrastructure allows you to do so)
