### ISSUE TITLE
First JSX attribute always throws the error "Property does not exist on type '{}'" 

### ISSUE THREAD

**Issue by jpdery** [microsoft/TypeScript#25861]
**Typescript Version**: 2.9.2

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./lib",
    "lib": [
      "es2015",
      "es2016",
      "es2017"
    ],
    "jsx": "react",
    "jsxFactory": "createElement",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "experimentalDecorators": true
  }
}
```

index.ts
```typescript
namespace global {
	declare namespace JSX {
		interface ElementClass extends Object { }
	}
}
```

Component.tsx

```typescript
function createElement(Type: any, attributes: any, ...children: Array<any>): any {
	return null
}

class Component {
	public prop1: string = ""
	public prop2: string = ""
}

var test = (
	<Component prop1="test" prop2="test" />
)
```

**Expected behavior:**
I believe this should compile fine

**Actual behavior:**
`Component.tsx:11:13 - error TS2339: Property 'prop1' does not exist on type '{}'.`

If I switch the order of the attributes like this:

`<Component prop2="test" prop1="test" />`

I get the error 

`Component.tsx:11:13 - error TS2339: Property 'prop2' does not exist on type '{}'.`

I'm not sure if the compiler is just stopping on the first attribute and all attributes would produce the same error, but this code was running fine on 2.8.2

Thanks

**Comment by DanielRosenwasser** [comment]
Confirmed, something like this worked in 2.8 but not anymore: https://agentcooper.github.io/typescript-play/?target=5&jsx=2#code/CYUwxgNghgTiAEA7KBbEBnADlMCBSAygBrwDeAUPFfAJaIAuIMAZjggKIQhoMDC06dPBAAPRomBCA8gCMAVuHpl4AbREAudPRh0A5gF11URAE94AX3KXyyNFjbwASiBz0K1eMwCuiMPRoA9ojwYHBQjJzcIAwAFAAqJpgg6vDGJgA0qfTaNDJejOgpaZkAdGVgABY0EMBwiCkAgjAwUCYAPGkAfACURaZklB7UcPReMMGIXhAQg1TW1pBQgvC8ASiYQdFKFACQmF4yEDRg8JgwAZgAjClaOoi68AC88ABEL+R7B0cnZxcATDccvcnq93tYAG6weAFJTPGIfNqrdabBinc5XR4vGEvNH-THY+AAek65G6QA

**Comment by weswigham** [comment]
An empty `ElementAttributesProperty` in the JSX namespace will get back the old behavior. We updated it so that if `ElementAttributesProperty` wasn't present, we'd use the first argument of the constructor instead of the class instance shape.
