### PR TITLE
Re-add strict concat signature

### LINKED ISSUE #9901: Tuple types get incorrect contextual type
**TypeScript Version:** 
```
$ tsc --version
Version 2.0.0
```

**Code**

```ts
// concat-bug.ts
var a : Array<[number, number]>= [[1, 2]];

// Typescript detects these first two tuples as arrays of numbers (`number[]`) instead of `[number, number]`
a.concat([[3, 4], [5, 6], [7, 8]]);
```

**Expected behavior:**
No compile errors. (It works in the 1.8 playground)

**Actual behavior:** 
```
$ tsc concat-bug.ts
concat-bug.ts(4,10): error TS2345: Argument of type '[number[], number[], [number, number]]' is not assignable to parameter of type '[number, number] | [number, number][]'.
  Type '[number[], number[], [number, number]]' is not assignable to type '[number, number][]'.
    Types of property 'pop' are incompatible.
      Type '() => number[] | [number, number]' is not assignable to type '() => [number, number]'.
        Type 'number[] | [number, number]' is not assignable to type '[number, number]'.
          Type 'number[]' is not assignable to type '[number, number]'.
            Property '0' is missing in type 'number[]'.
```

Note that the 3rd parameter is correctly detected as a tuple, but the first two are detected as arrays of numbers.

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #9901. Broken by #6629 after we missed the bug during the discussion in #6594.

#6629 introduces a new type for concat: `(...items: (T | T[])[]): T[]`. This means that `concat` accepts either list-wrapped arguments (`T[]`) or top-level arguments (`T`):

```ts
numbers.concat(1, [2, 3], 4)
```

Here, (1) and (4) are top-level arguments (`T`) whereas (2) and (3) are wrapped-arguments. Unfortunately, when you have a tuple or list type parameter, it's ambiguous whether an argument is list-wrapped or top-level:

```ts
pairs.concat([[1, 2], [3, 4]]);
```

If `[[1,2], [3, 4]]` is a top-level argument, then its type is `number[][]` (or `[number, number][]` or [[number, number], [number, number]]). If it's a list-wrapped argument, then its type is `number[]` (or `[number, number]`). But TypeScript can't tell, so it has to guess. Unfortunately, it guesses "top-level argument" (`T`) with type `number[][]`/`[number, number][]`. In the #9901 repro, `number[][]` is not compatible with the type argument `T=[number, number]`.

Adding a stricter overload first guides the inference process to prefer the list-wrapped-only case (`T[]` only) before falling back to the mixed top-level/list-wrapped overload.

### CODE REVIEW

**Comment by weswigham** [comment]
:+1:
