### ISSUE TITLE
instanceof does not respect inherited `Symbol.hasInstance`

### ISSUE THREAD

**Issue by rotu** [microsoft/TypeScript#56536]
### 🔎 Search Terms

hasinstance, instanceof, 2359, TS2359

### 🕗 Version & Regression Information

- I was unable to test this on prior versions because this is recent functionality introduced in #55052

### ⏯ Playground Link

https://www.typescriptlang.org/play?declaration=false&target=9&module=7&ts=5.4.0-dev.20231124#code/C4TwDgpgBAEghgZwJIDsHDigxhA8gMygF4oBvAKCigG0BlEAWwCMB7AGwDoALRVdTHAF0AFAA8AXAFcUAaxQsA7igCU4qK3YRM5AL7lyAegNQWM8vmlZgASxYooDEHwzY8+MVNnylAGihZxeGQ0FxwCZQoqACcIYEko+1EoaxCBCBZCLF19I3Uo0wgUc0sbOwcnVNcCVGAIKIQIK1sUD2k5RRQ-AKDnNIIoADITJgArRuAIyigYuISoJJT+Vwz-bMNjJnyZQuLsUvtHXqr8AHFCuussAB4AYSgIUVqUABMEWF5KsPwAPlavDq64huk2isXiiWSn3SmV0QA

### 💻 Code

```ts
type HasInstanceOf = {
  [Symbol.hasInstance](x:unknown): boolean
}

// ok
function myInstanceOf(x:unknown, c:HasInstanceOf){
  return x instanceof c
}

// broken
function myInstanceOfIntersection(x:unknown, c:HasInstanceOf & object){
  return x instanceof c
}

// broken
function myInstanceOfGeneric<C extends HasInstanceOf>(x:unknown, c:C){
  return x instanceof c
}
```

### 🙁 Actual behavior

The second and third examples give error TS2359
> The right-hand side of an 'instanceof' expression must be either of type 'any', a class, function, or other type assignable to the 'Function' interface type, or an object type with a 'Symbol.hasInstance' method.

In all cases, the right-hand side *is* an object type with a `Symbol.hasInstance` method.

### 🙂 Expected behavior

I expect all three examples to typecheck.

**Comment by fatcerberus** [comment]
> does not respect **inherited `Symbol.hasInstance`**

For the record, it actually works *correctly* with an inherited `hasInstance`:
[Playground link](https://www.typescriptlang.org/play?declaration=false&target=9&module=7&ts=5.4.0-dev.20231124#code/JYOwLgpgTgZghgYwgAgBJwM4EkQbHEJAeRmQG8AoZZAbQGUBPAWwCMB7AGwDoALTHPASQBdABQAPAFwBXEAGsQbAO4gAlJOTtOEAhQC+FCqEixEKHD2jBIAE3TZc+QhBLII4yCBsY0-R0JdSMgMKAHpQ5DY5ChhZBDBgNhBkJgYBJ2IYCRl5RRUAGmQESXt0gJJVSmooCDBpKGTxZFBBZzZSBH1DcMjo2MIEpJS0-2cSCytbbNkFZRBC4omoawg7P1bMyqpkGrqG5CaWjIh2oq6wiJYoKIgQGLjB5NSysZgcEwwIeMSQady5hYldbHVwAMkiLAAVl8wFtqrV6o1mqMkKdOiEelcbnd+t8hs8UYEAOK3KwIAA8AGE3B5bt5fA4NoEAHx-WYFIqSSlwnYI-aHQlo-RAA)

So the issue is specifically with intersections and generics.

**Comment by rotu** [comment]
@fatcerberus well observed!

Also broken with unions:

```ts repro
const Top = {[Symbol.hasInstance]:(x:unknown)=>(true as const)}
const Bot = {[Symbol.hasInstance]:(x:unknown)=>(false as const)}

// broken
function myInstanceOf(x:unknown, c : typeof Top | typeof Bot)
{
  return x instanceof c
}
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/MYewdgzgLgBAKiADjAvDA3gbQMoE8C2ARiADYB0AFgIYQCSkUVYwApgLoBcAFAB4cCuYANZgQAdzABKFAD4uUAE78WMGjFANJAXwBQG6DABCIWGix4ipSjXrQmrTrwHDRE6XIBmVEhBVr9UNo6OgD0ITCECiBCLGA6HoLAUACW4DD4uLaMzCwA8h5OgiLiYAA06jAcMFC4iCwgHvBIMAA+1bX1jcaBOug6MDAKLFD8CmAwPDDJDPad6jpaQA)
