### PR TITLE
Include export specifiers in the list of syntactic defaults

### LINKED ISSUE #24528: export { default } from broken in 2.9
**TypeScript Version:**  2.9.1 (also tried 3.0.0-dev.20180531)

**Search Terms:** export default, export default from

**Code**

A project that was working on 2.8 started failing on 2.9 with this error:

```
.../dts/Schema.d.ts:6:46 - error TS2507: Type 'typeof import(".../node_modules/shapeshifter/...' is not a constructor function type.

export default class Schema<T = any> extends BaseSchema {
```

The shapeshifter declaration looks like the following.

```
export { default } from './Schema';
export { MetadataField, PrimaryKey, Relation } from './types';
```

The above causes the error, while the following does not cause the error.

```
import Schema from './Schema';
export { MetadataField, PrimaryKey, Relation } from './types';
export default Schema;
```

**Expected behavior:**

It doesn't error and supports `export { default } from`.

**Actual behavior:**

It errors.

**Related Issues:** N/A

### PR DESCRIPTION
**Pull request by weswigham**
It was omitted in the original list of possible syntactic default declarations (things that indicate a declaration file definitely refers to a module). I can't imagine why it'd only break in 2.9 though, and not 2.8 - perhaps `resolveExportByName` was mistakenly resolving the alias before, or the symbol was otherwise mismanaged and masked the issue? I kinda wanna bisect just to see what triggered the change.

Fixes #24528

### CODE REVIEW

**Comment by weswigham** [comment]
Followup: It's because https://github.com/Microsoft/TypeScript/pull/22995 wasn't in 2.8. 😄

**Comment by mhegazy** [comment]
Please port to release-2.9 as well.
