### PR TITLE
fix lookup regression again

### LINKED ISSUE #26731: Incorrect error for parameter initializer referencing preceding parameter
**TypeScript Version:**  3.1.0-dev.20180829

**Search Terms:**

**Code**

```ts
// @target: ES2015
function test(foo: string, bar = foo) {}
```

**Expected behavior:**
No error

**Actual behavior:**
Error `Cannot find name 'foo'.` in the initializer of `bar`

**Playground Link:** 

**Related Issues:**
#26719
caused by #26317 //cc @Kingwl

### PR DESCRIPTION
**Pull request by Kingwl**
Fixes #26731

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@Kingwl thank you for the follow-up! Can you please add a testcase with the repro from the linked issue?

**Comment by ajafff** [comment]
@RyanCavanaugh the baseline change is actually the same as my repro in the linked issue

**Comment by RyanCavanaugh** [comment]
@ajafff true. I'd still prefer an explicit example - we are much more likely to notice an error file going from 0 to 1 or vice versa than a type baseline changing.

**Comment by Kingwl** [comment]
sure, wait a few moment

**Comment by sandersn** [comment]
Thanks for the second fix @Kingwl.

**Comment by Kingwl** [comment]
@sandersn 
Actually, I hope there is no fix. 🤷🏻‍♂️
