### ISSUE TITLE
Property 'caretPositionFromPoint' does not exist on type 'Document'

### ISSUE THREAD

**Issue by Egor-Koldasov** [microsoft/TypeScript#49931]
# Bug Report

### 🔎 Search Terms

caretPositionFromPoint
Property 'caretPositionFromPoint' does not exist on type 'Document'

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4.2

### ⏯ Playground Link

Doesn't work in 4.4.4: [Playground link](https://www.typescriptlang.org/play?ts=4.4.4#code/JYMwBAFAJg9gxgVwLYFMB2AXAdHAhgJxQwAUYBnYDYGNAMXxiVOEwEoxZFVMcCjSKVGvUbNMEAAwAaMBNYBuIA)
Works in 4.3.5: [Playground link](https://www.typescriptlang.org/play?ts=4.3.5#code/JYMwBAFAJg9gxgVwLYFMB2AXAdHAhgJxQwAUYBnYDYGNAMXxiVOEwEoxZFVMcCjSKVGvUbNMEAAwAaMBNYBuIA)

### 💻 Code

```ts
if (document.caretPositionFromPoint) document.caretPositionFromPoint(0, 0);
```

### 🙁 Actual behavior

'Document' should have an optional property "caretPositionFromPoint" since it exists in Firefox browser. [Link](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint).

### 🙂 Expected behavior

Property "caretPositionFromPoint" has been removed from 'Document', I was not able to find an explanation of this decision.

**Comment by MartinJohns** [comment]
It was removed here: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029

Probably because it's an experimental API with close to no browser support: https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint

**Comment by mike-lischke** [comment]
Still the wrong decision IMO. The alternative `document.caretRangeFromPoint` is deprecated and without `document.caretPositionFromPoint` there's no alternative to use. The variant `document.caretPositionFromPoint` works in Firefox and web devs need to test for it either to use this or the alternative. How are we supposed to do that, if there's no entry for the method we need to test?

**Comment by mgiraldo** [comment]
i'm in this exact situation. i need to support either method for the different browsers that support them... kind of:

```js
let range;

if (document.caretRangeFromPoint) {
  range = document.caretRangeFromPoint(pos.x + rt.left, pos.y + rt.top)
} else {
  range = document.caretPositionFromPoint(pos.x + rt.left, pos.y + rt.top)
}
```

is there a shim i can add to have `Document` include `caretPositionFromPoint`?

**Comment by vogon** [comment]
https://github.com/microsoft/TypeScript/issues/49931#issuecomment-1457128558 it's been a year since you left this comment, so hopefully you got some help elsewhere by now, but for anyone else who wants a quick shim for this, here's what I'm using:

```ts
declare global {
    type CaretPosition = {
        offsetNode: Node;
        offset: number;
    }

    interface Document {
        caretPositionFromPoint?(x: number, y: number): CaretPosition;
    }
}
```

it doesn't support `getClientRect()` on `CaretPosition`, but that wasn't necessary for our use case and hopefully it should be straightforward enough to figure out its declaration if it is for yours.
