### ISSUE TITLE
object destructuring assignment with rename throws error

### ISSUE THREAD

**Issue by effervescentia** [Microsoft/TypeScript#10668]
**TypeScript Version:**  `2.0.2` (and `2.1.0-dev.20160830`)

**Code**

``` ts
// A *self-contained* demonstration of the problem follows...

let _value: SomeType;
let _other: OtherType;

({ value: _value, other: _other } = someFunction());

```

**Expected behavior:**
`_value` should be set to the value `value` returned in the result of `someFunction()`
same with `_other`

(this works in `2.0.0` and `2.0.0-dev.20160628`)

**Actual behavior:** 
Throws errors:
`error: cannot find name 'value'`
`error: cannot find name 'other'`

**Comment by mhegazy** [comment]
looks like there is something else going on here..


```shell
c:\test\93>tsc --v
Version 2.1.0-dev.20160901

c:\test\93>type C:\test\93\src\index.ts
// A *self-contained* demonstration of the problem follows...

declare function someFunction(): { value: number, other: number };

let _value: number;
let _other: number;

({ value: _value, other: _other } = someFunction());
c:\test\93>tsc C:\test\93\src\index.ts

c:\test\93>echo %ERRORLEVEL%
0
```

**Comment by effervescentia** [comment]
Exact location of the failing code
https://github.com/groupby/searchandiser-ui/blob/master/test/unit/tags/_suite.ts#L18

The error generated when running with `2.0.2`:
<img width="856" alt="screen shot 2016-09-01 at 21 06 11" src="https://cloud.githubusercontent.com/assets/3784470/18189352/1d6b7da0-7088-11e6-8832-3e1202ea2076.png">

I'll try to put together a failing case that doesn't rely on my codebase 😜

**Comment by thorn0** [comment]
I've reproduces this:

```ts
d:\dev\zzzqwd>tsc -v
Version 2.0.7

d:\dev\zzzqwd>type index.ts

function qux(bar: string) {
  const obj = { value: 1 };
  let foo: number;
  ({ value: foo } = obj);
  let log = () => bar;
}

d:\dev\zzzqwd>tsc index.ts
index.ts(5,6): error TS2304: Cannot find name 'value'.
```

**Comment by effervescentia** [comment]
Yes! Thank you, I knew I wasn't crazy

On Nov 5, 2016 20:20, "Georgii Dolzhykov" <notifications@github.com> wrote:

I've reproduces this:

d:\dev\zzzqwd>tsc -vVersion 2.0.7
d:\dev\zzzqwd>type index.ts
function qux(bar: string) {
  const obj = { value: 1 };
  let foo: number;
  ({ value: foo } = obj);
  let log = () => bar;
}
d:\dev\zzzqwd>tsc index.tsindex.ts(5,6): error TS2304: Cannot find name 'value'.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/TypeScript/issues/10668#issuecomment-258651426>,
or mute the thread

**Comment by kpreisser** [comment]
Hi @mhegazy,
now that a repro is available, should this issue be marked as bug? I can still reproduce the error with the current `master` branch.
Thanks!

**Comment by sandersn** [comment]
Fix is up at #13708
