### ISSUE TITLE
Creating new instance based on interface definition dynamically does not work anymore for v2.2.0

### ISSUE THREAD

**Issue by mrucelum** [Microsoft/TypeScript#13898]
**TypeScript Version:**  2.2.0

**Code**

```ts
import { Registry } from '../registry';
import { Customization } from './customization';

export function CustomizationAnnotation() {

  return function <C extends Customization>(target: { new (...args: any[]): C; }): any {

    if (!isCustomization(target)) {
      throw new Error('CustomizationAnnotation can be only used for classes that implement Customization interface!');
    }

    Registry.registerCustomizer(new target());

    return target;
  };
}

function isCustomization(target: any | Customization): target is Customization {
  return (<Customization>target.prototype).getScope !== undefined;
}

```

**Expected behavior:**
It should compile successfully as it did for e.g. version 2.1.5

**Actual behavior:**
I get the following compilation error:
`Error:  [...]customization-annotation.ts (17, 33): Cannot use 'new' with an expression whose type lacks a call or construct signature.`

Maybe I got this wrong, but I thought that by defining `target` as `{ new (...args: any[]): C; }` I am saying `target` is a type that has a constructor? And furthermore, just the same code works fine with older TS versions (like 2.1.5).

The really interesting thing is that it _does_ work when I remove the check for the interface (`isCustomization()`). For me it seems that this check suddenly overwrites the type of "target"...?

**Comment by mhegazy** [comment]
How is `Error` defined? do you have a custom lib added?

This code compiler with no error locally (other than the missing modules). please provide a self contained reproduction of the issue.

**Comment by mrucelum** [comment]
I updated my report to contain more information. I hope it is now reproducible.

**Comment by mrucelum** [comment]
I tried again today with typescript@latest (v2.2.2) and I can still reproduce the error.

@mhegazy As you closed the ticket, is this intended behavior then? And if so, could you please explain why? Or point me to some documentation? Because for me this is a quite strange error and behavior...

**Comment by mhegazy** [comment]
Target is narrowed to a `Customization` as a result of the call to the function `isCustomization`.  `Customization` does not have a construct signature. I am guessing `isCustomization` should be defined as:

```ts
function isCustomization(target: any | Customization): target is { new (...args: any[]): Customization; } {
  return (<Customization>target.prototype).getScope !== undefined;
}
```

**Comment by mrucelum** [comment]
Thanks a lot - that did the trick! :)
