### ISSUE TITLE
Creation of d.ts mishandles case of `export const a = 34`

### ISSUE THREAD

**Issue by 3n-mb** [Microsoft/TypeScript#12734]
**TypeScript Version:**  2.0.3
**Code**
When making definitions, code from `.ts` file with line
```ts
export const a = 34;
```

**Expected behavior:**
Generated `d.ts` should be
```ts
export declare const a: number;
```
similarly to cases of `let` and `var`

**Actual behavior:**
But, it turns into
```ts
export declare const a = 34;
```
which, necessarily produces for consumers an error:
```
error TS1039: Initializers are not allowed in ambient contexts.
```

**Comment by mhegazy** [comment]
This is a new feature in TS 2.1.  The declaration file is a valid TS 2.1 file. If you want your declaration files to be consumable by TS 2.0 as well, add a type annotation, e.g.:

```ts
export const a: number= 34;
```

will be emitted as:
```ts
export declare const a : number;
```

**Comment by 3n-mb** [comment]
Thank you.
`: number` addition works for me.

**Comment by sccolbert** [comment]
This is silly, and a backwards incompatible change. I know you guys don't follow semver, but this breaks existing node builds for little benefit. Any chance of a patch release to support both?

**Comment by sccolbert** [comment]
To be clear, it appears that we have TS 2.0 `d.ts` files which are failing to compile with TS 2.1 due to this issue.

**Comment by sccolbert** [comment]
My previous comments (for those getting email) are invalid. Apologies.

**Comment by blink1073** [comment]
This was my mistake.  I had produced the `d.ts` files using a local TS 2.1, and tried to consume them using a global TS 2.0, not realizing the versions differed.
