### ISSUE TITLE
Changed behaviour in TS2.1 for Promise<void>

### ISSUE THREAD

**Issue by MichaelOates** [Microsoft/TypeScript#12871]
In typescript 2.0 any promise could be used a promise of type void, this does not seem to be the case in typescript 2.1. 

I couldn't find this listed as a breaking change or any existing tickets so raised this one.

**TypeScript Version:**  2.1.4

**Code**

```ts
function testVoidPromises(promiseA: Promise<void>, promiseB: Promise<void>): Promise<void> {
	return Promise.all([promiseA, promiseB]);
}
```

**Expected behavior:**
This compiles without errors in typescript 2.0

**Actual behavior:**
This fails to compile in typescript 2.1.4 with the following error:
test.ts(2,9): error TS2322: Type 'Promise<[void, void]>' is not assignable to type 'Promise<void>'.
  Type '[void, void]' is not assignable to type 'void'.

**Comment by DanielRosenwasser** [comment]
This has to do with the fact that `Promise` has overloads that use tuple types.

**Comment by astashko** [comment]
It's not only about Promise.all. Promise<void> means any promise (meaning both wit hand without values) in most cases. But simple code like this now fails:
```javascript
function foo(left: number, right: number): Promise<void> {
	if (left > right) return Promise.resolve();
	else return Promise.resolve('boo')
}
```

**Comment by advorkovyy** [comment]
```javascript
let x: Promise<void> = Promise.resolve(1) 
```
gives TS2322:Type 'Promise<number>' is not assignable to type 'Promise<void>'.  Type 'number' is not assignable to type 'void'.

So, this is obviously a bug in typescript compiler

**Comment by cwoodland** [comment]
Any headway with this issue??
Thanks

**Comment by kolya182** [comment]
+

**Comment by chharvey** [comment]
Will solving this issue also solve the problem of `() => Promise<number>` not being assignable to `() => Promise<void>`? Since [`() => number` is assignable to `() => void`](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-functions-returning-non-void-assignable-to-function-returning-void), I would expect the same reasoning to hold for async functions as well.

[Playground](http://www.typescriptlang.org/play/index.html#src=%2F%2F%20expected%20error%3A%20type%20'number'%20is%20not%20assignable%20to%20type%20'void'%0D%0Alet%20v%3A%20void%20%3D%202%0D%0A%0D%0A%0D%0A%2F%2F%20expected%20error%3A%20type%20'Promise%3Cnumber%3E'%20is%20not%20assignable%20to%20type%20'Promise%3Cvoid%3E'%0D%0Alet%20pv%3A%20Promise%3Cvoid%3E%20%3D%20Promise.resolve(2)%0D%0A%0D%0A%0D%0A%2F%2F%20expected%20non-error%3A%20type%20'()%3D%3Enumber'%20is%20assignable%20to%20type%20'()%3D%3Evoid'%0D%0A%2F%2F%20read%20FAQ%3A%20https%3A%2F%2Fgithub.com%2FMicrosoft%2FTypeScript%2Fwiki%2FFAQ%23why-are-functions-returning-non-void-assignable-to-function-returning-void%0D%0Atype%20FuncVoid%20%3D%20()%20%3D%3E%20void%0D%0Alet%20fv%3A%20FuncVoid%20%3D%20()%20%3D%3E%202%0D%0A%0D%0A%0D%0A%2F%2F%20UNEXPECTED%20error%3A%20type%20'()%3D%3EPromise%3Cnumber%3E'%20is%20not%20assignable%20to%20type%20'()%3D%3EPromise%3Cvoid%3E'%3F%3F%0D%0Atype%20AsyncFuncVoid%20%3D%20()%20%3D%3E%20Promise%3Cvoid%3E%0D%0Alet%20afv%3A%20AsyncFuncVoid%20%3D%20async%20()%20%3D%3E%20Promise.resolve(2)%0D%0A%0D%0A%0D%0Alet%20obj%3A%20%7B%0D%0A%20%20%20%20fv%3A%20FuncVoid%3B%0D%0A%20%20%20%20afv%3A%20AsyncFuncVoid%3B%0D%0A%7D%20%3D%20%7B%0D%0A%20%20%20%20fv%3A%20()%20%3D%3E%202%2C%0D%0A%20%20%20%20afv%3A%20()%20%3D%3E%20Promise.resolve(2)%2C%20%2F%2F%20UNEXPECTED%20error%0D%0A%7D%0D%0A%0D%0A%0D%0Ainterface%20Foo%20%7B%0D%0A%20%20%20%20fv()%3A%20void%3B%0D%0A%20%20%20%20afv()%3A%20Promise%3Cvoid%3E%3B%0D%0A%7D%0D%0Aclass%20Bar%20implements%20Foo%20%7B%0D%0A%20%20%20%20fv()%3A%20number%20%7B%0D%0A%20%20%20%20%20%20%20%20return%202%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20async%20afv()%3A%20Promise%3Cnumber%3E%20%7B%20%2F%2F%20UNEXPECTED%20error%0D%0A%20%20%20%20%20%20%20%20return%20Promise.resolve(2)%0D%0A%20%20%20%20%7D%0D%0A%7D)

**Comment by keradus** [comment]
any updaate?

**Comment by jorenl** [comment]
So, almost four years later I still run into this issue continuously:
https://www.typescriptlang.org/play/?ssl=18&ssc=26&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgEoQM4AdkG8BQyRyCA9gCYQBcyIArgLYBG0A3IcUxQJ40ZhRQAc3YBffPhh0QCMMFIhkYOAGsIAMRAAKGCBpaAlMgC8APmQA3UsHJGCxZFAhg6UEGIlSZchUtUQABShSBmAMDW1dfSMzZCCQsIgAHisbUzsOIicXNw98MhB+ZF0TZEMadGwTcy1cMkoaACYABmaAGmQucl5kACIAeQBpXtEDdgKirGDQ8M1S8rjpxKTKrHNY+JmIADonDFIAGwsIWpIKamQW9s6eGgHh5FH2fGU1TR0QMZf-TcT3qYSs0+rCAA

Afaik, `() => T` assigns to `() => void` just fine, but `() => Promise<T>` does not assign to `() => Promise<T>`.
What's the correct pattern/workaround here?

**Comment by DanielRosenwasser** [comment]
Seems like "`Promise<void>` should work like `void`" is an apt description (as #46461 put it)

**Comment by tncbbthositg** [comment]
I'm running into this issue now.  I agree with @rbuckton that it feels a little bit strange to take a function that returns a value and assign it a return type of void.  But, it does make sense to specify that you're accepting a function as an argument and you want to completely disregard the return type.

To that end, it makes sense to me to have a value `() => T` that you can assign to `() => MehNothingReally` and `void` seems like as reasonable a keyword as any here.  While strictly speaking, `() => void` is not the same as `() => T` it does indicate that "I have no intent to use the return type of this function."

If it's reasonable for someone to do that, then it must also be reasonable for someone to say, "I'm going to wait for this function to finish running . . . but I don't care what the return type of the function is."

In that case, one might want to say, `() => Promise<T>` is assignable to `() => Promise<MehNothingReally>` . . . and for now, `void` is the keyword to indicate that.

In my particular use case, I have a library that loads data asynchronously.  The return value is something like, `{ data, refetch }`.  I'd like to pass that refetch to component.  The refetch component does not care at all about the return value of the promise . . . only that the promise has been resolved.

In order to accommodate this, I have to say:

```typescript
const { data, refetch } = useMyData();
const doRefetch = () => { refetch(); }
```

Technically, because I'm in react, it's even more complicated than that.  I don't really care if I can assign `Promise<FancyDataFetchResult>` to `Promise<void>`.  But, I do need some kind of type that indicates, `Promise<WhateverYouWant_IWillNeverUseThisValue>`.

**Comment by troywweber7** [comment]
A workaround (which, if undesirable, might at least spark more discussion):

```ts
function doSomething():Promise<number>{
   return Promise.resolve(1);
}

function doSomethingLarger():Promise<void>{
   return doSomething().then();
}
```

This will pass the compiler error. But then I have to wonder: what are the drawbacks to calling `.then()` on this function just so that we can bypass this error? Seems silly.
