### ISSUE TITLE
4.8.2 -> 4.8.3 regression: type narrowing fails with a discriminant type of never

### ISSUE THREAD

**Issue by shigma** [microsoft/TypeScript#50716]
# Bug Report

### 🔎 Search Terms

regression, narrow, union, control flow

### 🕗 Version & Regression Information

- This changed between versions 4.8.2 and 4.8.3

### ⏯ Playground Link

Note: playground does not have 4.8.3 support

[Playground link with relevant code](https://www.typescriptlang.org/play?#code/PQKhAIAsBdoBwM4C5jACYEsEGMD2AnNAOjwFt0BTANwoBtc4L8F1dsXoGN3gBzAQ2gUA7vwCeAYjjj6-NAgC0AoaLELpY2WgUJo+AK7Zo+-BXAhgAKAoAPOAWjgMAOyH4AZv2xmA4oJHiAAoyuHIAynqGxqYAPADy4LZCzvLgfiricXB4aBQANOAAKok2yakA1hRiuO5p-qoAojSuCAUAIgB84ADeluDgoBAMOWbuBODQkGYaWuZW-QxI4HF9A2CJzY5ogvxzq2hLbauDE1MbFK7gzvyko+OTWOAzoWh7-dAA-EuFx+sIFABHfQXbxXfSkABGTAK+n+rzG+HApgQ4JcvHA-wQCAwuGcCHA-BSUAo-Hw0ChgnxFlWCC+YMhTEsAF9LNY7A4JmJGHUMmJgpoXuAALw9VYAbQSLh5ATEWRGAF0lgkkhdUukZXLcLkiG0AJJhQIAQUKAGEABKrfofUX9W3gMXFKWVaq1dWNTYIRXS1T8rQRAxGEwUGJuzLZLUUHX6o2ms0FQoFUNiJoXaAIB3yjqW8BMsXOmre8Qplry7NLJO+l7+qJB+IFZzUaHLEplfH5131IKkm7460V7ukdNxeXgJYNmj4LO5pOa3KlyzQLnTWheCiQXC0XKIkXjxls+xkpyuJieUH9-A9m32mfh7VmhoAGQfw6WcBX3nXm8Z-TFN5GRF1NoGgAOUKXUADEAE0vTfVdPy3cU-wjIgACUGjCABVABZBoYPfNcNwQn8kO1NCAEUMPQwoAH0fAw3UHzaaicKwgAhBoULCPC4MI79r07WVb0jAA1OJdRNBpqLCQpjUkjDAjaWTuI-Xj8EQgTZ0jQI0LCECJOo+TFMKXDX3w+DGRZSwThgeBkFQTAcAIYgyEoGh6EYZhWB4Tg4G4FhhgjRRCW0XRBFhBQRgQCRlBlJQBIUALcipKxbAPRwLnBQtBJGK8TkNZxzkuUR8Qc6RoGwKZiDecA9QNY1zWFcAAAY8l+CBwIwUxXg8nFMGwfhaFoMRwAhYbJjMbBaAwVMJlwcBKgoOBTgm3EGyMHECoGjAaCIar70NFDCnY41GoARla-oTgiUk0wJK4RAxCgsQ28A0BMNFlqPDBoAwAaoGChBIH4SpdupfpAJAsCoMagAmC61ggDC4G2IRPsm6bXAAcnxOBkRBSNqu09C9LkhTZMagBmeGTgwuFZvAAArXAXGAWgSRocBxlIXAOahaBhAoC5wCoZnQQqwkG1oBBQfmcBRPEyTpNkgyyeMxqABZqfWFCnvBMxdlx6gcVhR7ntxU5BHAYrXqwPBnDWoQqrB8AdOwhpGoANi1iBINwfQMXXfRNwJWAKFIOBHE4JEKDth2CSJZE9acUhbkwfwhpl1Y0JNOJgOAhoTWKEUAHZvZdwFgV0I8EVIQQXv4CE-ccGp3CmhtwF4fQMGD24GWYI87pXfBeDMTvu6d2XyMo6TaPoxjmIaNiOLCRqAA4y8KM5MWxc2gfxKEhZcKgtpRigqt9-3Ab94PTFjmPHGCpxclcDB3DEYBE9uAlsDwQg0Qz6qupgLCUNA+QCUl0JhF1LnRqABOMuYQZoYBTmfX6QghoEncG4cAd91rOF4AUO20B+AuHxONcAAADKYN0KTQGoi4Nwx9aAUPprCAmzt7xPgSCKU6LU2rgEQZcKUyJ7B4jMFHW+FBtofV2NQsktD6ZeHKM4XAwg2ZoBHhbRw31-r70FgVSR20z6Z36PtQ6x0aKGhNAAaTOudZkrJrKwEQCgdAtsnIkFwOQXIbkGBMBYGgNgHAuA8BiqoCQZBa4pCCikBQjYWhxV5HEj0exUocgYSeVcWViy3V6HaE4twsT8E0dbbAph-CvGdv0HCYQwiGh8JJE0aFZJLG6ASJYp0czZgKU9BAxSzDW1QY7aq1TIH1NJkZBorT2ngBhl0-J6xCl9JKfwEqdAKDDKqeAGpdSGnUSAg+Boxlpn8CWBTLpll3D6GcOtc2qz-hkiwr0-pAAKeJ0ATkdJzAASh6JZNJh5VliBueAK5Nyfp3O2BHRBZtnAvJcHAfQHysqVjkL8vJThajwucIi6ARBHBCkJeATGOzxnUSaQ0WSmN0XZnuUwaATyikj2xbiogaBvmrBZCyIAA)

### 💻 Code

<img width="885" alt="image" src="https://user-images.githubusercontent.com/33423008/189542339-cf0d3bf1-25fe-4060-9614-84cd590cc68d.png">

<img width="980" alt="image" src="https://user-images.githubusercontent.com/33423008/189542425-f93f63bf-57e8-4f02-8c34-47a46d8a1bec.png">

### 🙁 Actual behavior

4.8.3

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/33423008/189542363-369b94f6-147f-4c6d-9874-474f1883d90d.png">

### 🙂 Expected behavior

4.8.2 

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/33423008/189542393-95ff26f3-fea7-4d86-b419-c61383957e55.png">

**Comment by jcalz** [comment]
> Note: playground does not have 4.8.3 support

[It does](https://www.typescriptlang.org/play?ts=4.8.3#code/PQKhAIAsBdoBwM4C5jACYEsEGMD2AnNAOjwFt0BTANwoBtc4L8F1dsXoGN3gBzAQ2gUA7vwCeAYjjj6-NAgC0AoaLELpY2WgUJo+AK7Zo+-BXAhgAKAoAPOAWjgMAOyH4AZv2xmA4oJHiAAoyuHIAynqGxqYAPADy4LZCzvLgfiricXB4aBQANOAAKok2yakA1hRiuO5p-qoAojSuCAUAIgB84ADeluDgoBAMOWbuBODQkGYaWuZW-QxI4HF9A2CJzY5ogvxzq2hLbauDE1MbFK7gzvyko+OTWOAzoWh7-dAA-EuFx+sIFABHfQXbxXfSkABGTAK+n+rzG+HApgQ4JcvHA-wQCAwuGcCHA-BSUAo-Hw0ChgnxFlWCC+YMhTEsAF9LNY7A4JmJGHUMmJgpoXuAALw9VYAbQSLh5ATEWRGAF0lgkkhdUukZXLcLkiG0AJJhQIAQUKAGEABKrfofUX9W3gMXFKWVaq1dWNTYIRXS1T8rQRAxGEwUGJuzLZLUUHX6o2ms0FQoFUNiJoXaAIB3yjqW8BMsXOmre8Qplry7NLJO+l7+qJB+IFZzUaHLEplfH5131IKkm7460V7ukdNxeXgJYNmj4LO5pOa3KlyzQLnTWheCiQXC0XKIkXjxls+xkpyuJieUH9-A9m32mfh7VmhoAGQfw6WcBX3nXm8Z-TFN5GRF1NoGgAOUKXUADEAE0vTfVdPy3cU-wjIgACUGjCABVABZBoYPfNcNwQn8kO1NCAEUMPQwoAH0fAw3UHzaaicKwgAhBoULCPC4MI79r07WVb0jAA1OJdRNBpqLCQpjUkjDAjaWTuI-Xj8EQgTZ0jQI0LCECJOo+TFMKXDX3w+DGRZSwThgeBkFQTAcAIYgyEoGh6EYZhWB4Tg4G4FhhgjRRCW0XRBFhBQRgQCRlBlJQBIUALcipKxbAPRwLnBQtBJGK8TkNZxzkuUR8Qc6RoGwKZiDecA9QNY1zWFcAAAY8l+CBwIwUxXg8nFMGwfhaFoMRwAhYbJjMbBaAwVMJlwcBKgoOBTgm3EGyMHECoGjAaCIar70NFDCnY41GoARla-oTgiUk0wJK4RAxCgsQ28A0BMNFlqPDBoAwAaoGChBIH4SpdupfpAJAsCoMagAmC61ggDC4G2IRPsm6bXAAcnxOBkRBSNqu09C9LkhTZMagBmeGTgwuFZvAAArXAXGAWgSRocBxlIXAOahaBhAoC5wCoZnQQqwkG1oBBQfmcBRPEyTpNkgyyeMxqABZqfWFCnvBMxdlx6gcVhR7ntxU5BHAYrXqwPBnDWoQqrB8AdOwhpGoANi1iBINwfQMXXfRNwJWAKFIOBHE4JEKDth2CSJZE9acUhbkwfwhpl1Y0JNOJgOAhoTWKEUAHZvZdwFgV0I8EVIQQXv4CE-ccGp3CmhtwF4fQMGD24GWYI87pXfBeDMTvu6d2XyMo6TaPoxjmIaNiOLCRqAA4y8KM5MWxc2gfxKEhZcKgtpRigqt9-3Ab94PTFjmPHGCpxclcDB3DEYBE9uAlsDwQg0Qz6qupgLCUNA+QCUl0JhF1LnRqABOMuYQZoYBTmfX6QghoEncG4cAd91rOF4AUO20B+AuHxONcAAADKYN0KTQGoi4Nwx9aAUPprCAmzt7xPgSCKU6LU2rgEQZcKUyJ7B4jMFHW+FBtofV2NQsktD6ZeHKM4XAwg2ZoBHhbRw31-r70FgVSR20z6Z36PtQ6x0aKGhNAAaTOudZkrJrKwEQCgdAtsnIkFwOQXIbkGBMBYGgNgHAuA8BiqoCQZBa4pCCikBQjYWhxV5HEj0exUocgYSeVcWViy3V6HaE4twsT8E0dbbAph-CvGdv0HCYQwiGh8JJE0aFZJLG6ASJYp0czZgKU9BAxSzDW1QY7aq1TIH1NJkZBorT2ngBhl0-J6xCl9JKfwEqdAKDDKqeAGpdSGnUSAg+Boxlpn8CWBTLpll3D6GcOtc2qz-hkiwr0-pAAKeJ0ATkdJzAASh6JZNJh5VliBueAK5Nyfp3O2BHRBZtnAvJcHAfQHysqVjkL8vJThajwucIi6ARBHBCkJeATGOzxnUSaQ0WSmN0XZnuUwaATyikj2xbiogaBvmrBZCyIAA) although you sometimes need to manually modify the url because the version you want isn't in the dropdown

Also, it's kind of hard to go back and forth looking at images of someone's IDE with boxes around things, and then at a playground link, and trying to match those up.  Could you please put the code here as plaintext and use code comments to call attention to anything you want people to notice?

**Comment by shigma** [comment]
> It does although you sometimes need to manually modify the url because the version you want isn't in the dropdown

@jcalz Thanks a lot for your quick response and useful tip.

It looks that the playground above does not report an error. Maybe I need to provide more specific code but the typings from source code is a bit too long. I'll provide some key typings first, and if it doesn't help I'll try to give a small-scale reproduction later.

```ts
/** https://discord.com/developers/docs/topics/gateway#payloads-gateway-payload-structure */
export interface GatewayPayloadStructure<O extends GatewayOpcode, T extends keyof GatewayEvents, D> {
  /** opcode for the payload */
  op: O
  /** event data */
  d?: D
  /** the event name for this payload */
  t?: T
  /** sequence number, used for resuming sessions and heartbeats */
  s?: number
}

// this gives out
// GatewayPayloadStructure<GatewayOpcode.DISPATCH, "READY", ReadyEvent> | ... 55 more
export type GatewayPayload = {
  [O in GatewayOpcode]: O extends GatewayOpcode.DISPATCH
    ? {
      [T in keyof GatewayEvents]: GatewayPayloadStructure<GatewayOpcode.DISPATCH, T, GatewayEvents[T]>
    }[keyof GatewayEvents]
    : GatewayPayloadStructure<O, never, O extends keyof GatewayParams ? GatewayParams[O] : never>
}[GatewayOpcode]

// expect a `Message` here
export async function adaptMessage(bot: DiscordBot, meta: Message, session: Partial<Session> = {}) {}

export async function adaptSession(bot: DiscordBot, input: GatewayPayload) {
  const session = bot.session()
  if (input.t === 'MESSAGE_CREATE') {
    session.type = 'message'
    // `GatewayEvents['MESSAGE_CREATE']` is assignable to `Message`
    // In 4.8.2 `input` is narrowed but in 4.8.3 it isn't
    await adaptMessage(bot, input.d, session)
  }
}
```

And there is a [failing CI](https://github.com/satorijs/satori/runs/8293903157?check_suite_focus=true) with above error.

**Comment by shigma** [comment]
I'm now reproducing the error with `strictNullChecks` set to `false`: [link](https://www.typescriptlang.org/play?strictNullChecks=false&noUnusedLocals=true&noUnusedParameters=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&ts=4.8.3#code/PQKhAIAsBdoBwM4C5jACYEsEGMD2AnNAOjwFt0BTANwoBtc4L8F1dsXoGN3gBzAQ2gUA7vwCeAYjjj6-NAgC0AoaLELpY2WgUJo+AK7Zo+-BXAhgAKAoAPOAWjgMAOyH4AZv2xmA4oJHiAAoyuHIAynqGxqYAPADy4LZCzvLgfiricXB4aBQANOAAKok2yakA1hRiuO5p-qoAojSuCAUAIgB84ADeluDgoBAMOWbuBODQkGYaWuZW-QxI4HF9A2CJzY5ogvxzq2hLbauDE1MbFK7gzvyko+OTWOAzoWh7-dAA-EuFx+sIFABHfQXbxXfSkABGTAK+n+rzG+HApgQ4JcvHA-wQCAwuGcCHA-BSUAo-Hw0ChgnxFlWCC+YMhTEsAF9LNY7A4JmJGHUMmJgpoXuAALw9VYAbQSLh5ATEWRGAF0lgkkhdUukZXLcLkiG0AJJhQIAQUKAGEABKrfofUX9W3gMXFKWVaq1dWNTYIRXS1T8rQRAxGEwUGJuzLZLUUHX6o2ms0FQoFUNiJoXaAIB3yjqW8BMsXOmre8Qplry7NLJO+l7+qJB+IFZzUaHLEplfH5131IKkm7460V7ukdNxeXgJYNmj4LO5pOa3Kltn2MlOVxMTyg-v4Hs2+0z8Pas0NAAyh+HS264AhSwAjDnmayTjB4MhUJgcARiGRKDR6IxmKweJwcDcCwwwRoohLaLogiwgoIwIBIygykonZqKBuRUlYtiLo4FzgoWsp7mYvT9CchrOOclyiPir7SNA2BTMQbzgHqBrGuawrgAADHkvwQAAYhgpivL+OKYNg-C0LQYgXtJkxmNgtAYKmEy4OAlQUHApzybiDZGDi5ESRgNBEExB6GgASoUABCDTGhxV48SR6wRKSaYElcIgYhQWL6eAaAmGiWnLhg0AYBJUAQQgkD8JUJnUv0uptA0AByhS6nxACaHEAEyOWsEAAKpwNsQhBQpSmuAA5PicDIiCkZMYE5kNGEKUmg0AD6BWBG0xoNBxADMeUnAVcIqeAABWuAuMAtAkjQ4DjKQuALVC0DCBQFzgFQ02gvRhINrQCBxfM4AAGpxLq7UdWEhR9V1PV9RxAAsw3rOZ3ngmYuy1dQOKwl5Pm4qcgjgFRflYHgzi6UIjHxeAzVhAVACy-UigAbG9EAZbg+gYpAuO0K8ghCKQcCOJwSIUFDMMEkSyJfU4pC3Jg-hSSdqzNSacTJclDQmsUIoAOxYwjgLAroy4IqQgi+fwEK444NTuIpDbgLw+gYET4C3AyzDLu5tCkrwZga1rcOnc1ACKBUtYUHU+AVuqHm0HWo8jNnmWEHEAByi4UZyYtiwPRfiUJbS4VCGSVFCMTjeNRYTrymDT1OOBBTi5K4GDuGIwAM7cBLYHghBouzTG6slZ2GoeiU3S1YS6jzHEAJyi2EykYMzsdhUIUkEu4bjgKnenOLwBRQ9A-AuPicngAABlMrkUtAHUuG4Ue0PP42wg18MHseCQile3G8eAHeXFKyL2HiZiUynFBGYFuxL2SK-jV45TOLgwhzWgJsg0cCFCKYdNrkQfkZWOHN+hmUsjZY0HVDQmgANL2QcneSwD5YCIBQOgSG74SC4HILkb8DAmAsDQGwDgXAeCIVUBIMgMsUjgRSAoRsLRkK8jYR6PYWEOTr1XF4XwKFixuWIraE4twsT8AAeDbAph-CvHhv0VGYQwiGh8J1E0zU+pngJNeW8dpJHeQQDIsw4Me6wyYiohuGjOrdV6oUBoej+BLGyoYiR6wpGmNkfwaidAKBWOUeAVR6jNEdSSoeBoTiXFLAGreFklh3D6GcHpYGfj-hkmRiYsxAAKdh0BYngBvEyAAlD0RJfClx+LEKk8AyTUmhXSdscmHcgbOFyS4OA+hCn4UrHIcp4ic7gE6c4bp0AiCOCFNM8AlVQl2I6to2yTjKqDOzBkpg0BsnSJNqM8ZRA0ClNWCyFkQA)

**Comment by andrewbranch** [comment]
Full repro for @typescript-bot:

```ts repro
// @strictNullChecks: false

/** https://discord.com/developers/docs/topics/gateway#payloads-gateway-payload-structure */
export interface GatewayPayloadStructure<O extends GatewayOpcode, T extends keyof GatewayEvents, D> {
  /** opcode for the payload */
  op: O
  /** event data */
  d: D
  /** the event name for this payload */
  t?: T
  /** sequence number, used for resuming sessions and heartbeats */
  s?: number
}

export type GatewayPayload = {
  [O in GatewayOpcode]: O extends GatewayOpcode.DISPATCH
    ? {
      [T in keyof GatewayEvents]: GatewayPayloadStructure<GatewayOpcode.DISPATCH, T, GatewayEvents[T]>
    }[keyof GatewayEvents]
    : GatewayPayloadStructure<O, never, O extends keyof GatewayParams ? GatewayParams[O] : never>
}[GatewayOpcode]

export interface GatewayParams {
  [GatewayOpcode.HELLO]: { b: 1 }
}

/** https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-opcodes */
export enum GatewayOpcode {
  /** An event was dispatched. */
  DISPATCH = 0,
  /** Fired periodically by the client to keep the connection alive. */
  HEARTBEAT = 1,
  /** Starts a new session during the initial handshake. */
  IDENTIFY = 2,
  /** Update the client's presence. */
  PRESENCE_UPDATE = 3,
  /** Used to join/leave or move between voice channels. */
  VOICE_STATE_UPDATE = 4,
  /** Resume a previous session that was disconnected. */
  RESUME = 6,
  /** You should attempt to reconnect and resume immediately. */
  RECONNECT = 7,
  /** Request information about offline guild members in a large guild. */
  REQUEST_GUILD_MEMBERS = 8,
  /** The session has been invalidated. You should reconnect and identify/resume accordingly. */
  INVALID_SESSION = 9,
  /** Sent immediately after connecting, contains the `heartbeat_interval` to use. */
  HELLO = 10,
  /** Sent in response to receiving a heartbeat to acknowledge that it has been received. */
  HEARTBEAT_ACK = 11,
}

/** https://discord.com/developers/docs/topics/gateway#commands-and-events-gateway-events */
export interface GatewayEvents {
    /** message was created */
    MESSAGE_CREATE: { a: 1 }
    /** message was edited */
    MESSAGE_UPDATE: { a: 2 }
    /** message was deleted */
    MESSAGE_DELETE: { a: 3 }
}

function assertMessage(event: { a: 1 }) {}

export async function adaptSession(input: GatewayPayload) {
  if (input.t === 'MESSAGE_CREATE') {
    assertMessage(input.d)
  }
}
```

**Comment by ahejlsberg** [comment]
Simpler repro:

```ts
type Foo = { kind?: 'a', a: number } | { kind?: 'b' } | { kind?: never };

function gg(foo: Foo) {
    if (foo.kind === 'a') {
        foo.a;  // Error with 4.8.3 when strictNullChecks is off
    }
}
```

Appears to be caused by #50592 (where we now bi-directionally check comparability in discriminant narrowing).

**Comment by ahejlsberg** [comment]
I guess the bot got there a few seconds faster than me. 😄

**Comment by ahejlsberg** [comment]
Anyways, I'll come up with a fix.

**Comment by ahejlsberg** [comment]
Another way to write the repro is:

```ts
type Foo = { kind: 'a' | undefined, a: number } | { kind: 'b' | undefined } | { kind: undefined };

function gg(foo: Foo) {
    if (foo.kind === 'a') {
        foo.a;
    }
}
```

Since `undefined` is assignable and comparable to any type in non-strictNullChecks mode (strange yes, but that's how it is), it sort of becomes obvious what the issue is: In non-strictNullChecks mode, a type with a discriminant of `undefined` is always included. However, it just so happened that the uni-directional discriminant check sometimes excluded `undefined`, but now it consistently includes it.

So, I'm tempted to say this is working as intended.

**Comment by shigma** [comment]
I don't think it is about `undefined`, I removed the `?` and still see this error:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/33423008/189792962-59d09033-7858-4ffd-9cf1-e964ab76d55a.png">

```
Property 'a' does not exist on type '{ kind: "a"; a: number; } | { kind: never; }'.
  Property 'a' does not exist on type '{ kind: never; }'.
```

[link](https://www.typescriptlang.org/play?strictNullChecks=false&ts=4.8.3#code/C4TwDgpgBAYg9nKBeKBvKBrAlgOwCYBcUA5AIbEA0UpROArgLYBGEATlAL5QA+amuhEk2KcefbPloQAbm04BuAFCKAZnRwBjYFjg4oAc30AKFQiLw4ASjSKodqFhVQTCAHQS8yJCjLFrqW3sg0zhXUnk7AHpIqABRVlY4dgB3LGAACygAFlcADlcAZihk9Ig9AGdgViwtADk6ABsGgGFSjQxyh064FRVAuw5FQaA)

**Comment by ahejlsberg** [comment]
@shigma Hmm, yes, this example fails with 4.8.3, but didn't with 4.8.2, regardless of strictNullChecks settings:

```ts
type Foo = { kind: 'a', a: number } | { kind: 'b' } | { kind: never };

function gg(foo: Foo) {
    if (foo.kind === 'a') {
        foo.a;
    }
}
```

The issue appears to be that a discriminant type of `never` was matched by nothing before, but now is matched by anything due to the bi-directional comparability change in #50592. We definitely need to fix that.

**Comment by fatcerberus** [comment]
@ahejlsberg Out of curiosity, why is `never` considered a discriminant in the first place?  It’s not a unit type; in fact being the bottom type it’s the exact opposite (initial object vs. terminal object)

**Comment by ahejlsberg** [comment]
> Out of curiosity, why is never considered a discriminant in the first place?

It isn't. To be considered a discriminant property of a union type, at least one of the constituent property must have a literal type, and at least two constituents must have different types for the property. But a property with a `never` type doesn't disqualify the union.

**Comment by segevfiner** [comment]
@ahejlsberg It's still erroring on v4.8.4: https://www.typescriptlang.org/play?ts=4.8.4#code/C4TwDgpgBAYg9nKBeKBvKBrAlgOwCYBcUA5AIbEA0UpROArgLYBGEATlAL5QA+amuhEk2KcefbPloQAbm04BuAFCKAZnRwBjYFjg4oAc30AKFQiLw4ASjSKodqFhVQTCAHQS8yJCjLFrqW3sg0zhXUnk7AHpIqABRVlY4dgB3LGAACygAFlcADlcAZkC7DkVSoA

**Comment by ahejlsberg** [comment]
@segevfiner Yeah, you're right, the fix was tagged for 4.8.4 but somehow didn't make it into the release. It's definitely fixed in the main branch and any 4.9 release.
