### PR TITLE
Partial matches in union type signatures

### LINKED ISSUE #4122: Functions with optional arguments in union types not working
I noticed the following gives an error when using typescript@next:
```typescript
var a: boolean | number;
a.toString(); // number#toString has an optional argument

var b: { foo(arg?: string): string } | { foo(): string };
b.foo();

var c: { foo(...args): string } | { foo(): string };
c.foo();

var d: ((arg?: string) => string) | (() => string);
d();
```
This used to work with 1.5.3, but with 1.6.0-dev.20150802 this gives the following errors:
```
test.ts(2,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
test.ts(5,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
test.ts(8,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
test.ts(11,1): error TS2349: Cannot invoke an expression whose type lacks a call signature.
```
Is this a bug?

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we allow partial signature matches when computing the signature set of a union type. Specifically, a signature in a particular constituent type is included in the signature set if it has a match in every other constituent type, but the matching signatures are allowed to have extra optional parameters and different return types.

Fixes #4122.

### CODE REVIEW

File: tests/cases/conformance/types/union/unionTypeCallSignatures2.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+interface C {
+    (x: string, ...y: string[]): number;
+    (x: number, s?: string): number;
+    <T>(x: T[]): T[];
+}
+
+var f: A | B | C;
+var n = f(42);             // number
+var s = f("abc");          // boolean | string | number
+var a = f([true, false]);  // boolean[]
```
Comment (danquirk) [inline tests/cases/conformance/types/union/unionTypeCallSignatures2.ts]: could you augment this to include a permutation or two to make sure the behavior is the same when the unions/overloads are in different orders, ie:
```var f2: C | B | A;```

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -3131,52 +3131,66 @@ namespace ts {
...
-                    else {
-                        signature = cloneSignature(source);
-                        // Clear resolved return type we possibly got from cloneSignature
-                        signature.resolvedReturnType = undefined;
-                        signature.unionSignatures = unionSignatures;
+            for (let i = 0; i < signatureLists.length; i++) {
+                for (let signature of signatureLists[i]) {
+                    // Only process signatures with parameter lists that aren't already in the result list
+                    if (!result || !findMatchingSignature(result, signature, /*partialMatch*/ false, /*ignoreReturnTypes*/ true)) {
+                        let unionSignatures = findMatchingSignatures(signatureLists, signature, i);
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Seems like the signatures could be in a funky order now in the resulting overload set. Do you think the order should still be based on the first consituent?

**Comment by JsonFreeman** [comment]
This will work in some cases, but I think the arity rules could be relaxed even more. Ideally you would want something like this to work:
```ts
function f1(s: string) { }
function f2(s?: string) { }
function f3(...s: string[]) { }
function f4(s: string, s2?: string) { }
function f5(s?: string, n?: number) { }
function f6(s?: string, ...n: number[]) { }
function f7(s: string, ...sRest: string[]) { }

var fUnion: typeof f1 | typeof f2 | typeof f3 | typeof f4 | typeof f5 | typeof f6 | typeof f7;

fUnion(""); // All constituents can be called by passing a single string.
```

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -6924,20 +6946,13 @@ namespace ts {
...
-                }
-
                 let signature = getNonGenericSignature(current);
                 if (signature) {
                     if (!signatureList) {
                         // This signature will contribute to contextual union signature
                         signatureList = [signature];
                     }
-                    else if (!compareSignatures(signatureList[0], signature, /*compareReturnTypes*/ false, compareTypes)) {
+                    else if (!compareSignatures(signatureList[0], signature, /*partialMatch*/ false, /*ignoreReturnTypes*/ true, compareTypes)) {
```
Comment (JsonFreeman) [inline src/compiler/checker.ts]: I'd consider making partialMatch true here since you want to be as lax as possible for contextual signatures.

File: src/compiler/checker.ts (hunk 2 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: The "canonical" ordering is order of constituent types followed by order of signature declarations. For an intersection type, that is the exact list you get. For union types, we reduce that list to contain only signatures that have matches, *in the order of the source of the match*. In other words, the signatures appear in the positions they were declared and we never move a signature to a position of one of its partial matches. I think this is a reasonable way to do it. Anything having to do with reordering of partially matched signatures is going to be rather speculative anyway.

File: src/compiler/checker.ts (hunk 3 above)
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Possibly, but it is a bit different here in that were trying to find the most informative signature, not the least common denominator. For example:

```typescript
var f: ((x: string) => void) | (() => void) = x => { ... };
```

Here you'd really like the contextual signature to be `(x: string) => void` so `x` can be contextually typed. But then it get complicated in situations like this:

```typescript
var f: ((x: string) => void) | ((x: number) => void) | () => void) = x => { ... };
```

Here we'd have to go with `() => void` and no contextual type for `x`.

Anyway, not clear that there is a simple solution so I'm leaving the existing rule in place.

**Comment by ahejlsberg** [comment]
> This will work in some cases, but I think the arity rules could be relaxed even more.

Agreed, we should cover all those cases. Pretty easy to do.

File: src/compiler/checker.ts (hunk 2 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: Yes, and I think the most important thing is that the order is deterministic, which it is. I think you're right, this order is not bad.

Comment (JsonFreeman) [inline src/compiler/checker.ts]: And as you say, the parallel with intersection types is nice.

File: src/compiler/checker.ts (hunk 3 above)
Comment (JsonFreeman) [inline src/compiler/checker.ts]: It seems like in both of those examples, you'd get no contextual signature, whether or not you accept partial matches. But something like the following would give you a contextual signature *only* if you accept partial matches:
```ts
type RequiredCallable = (s: string) => string;
type OptionalCallable = (s?: string) => string;
var func: RequiredCallable | OptionalCallable = x => x.charAt(0); // x is string only if partialMatches is true
```
It's a pretty silly example, but my point is that partialMatches will only make it more likely that a contextual signature will emerge at all.

**Comment by JsonFreeman** [comment]
Looks good

**Comment by ahejlsberg** [comment]
@mhegazy Want to take a look? I'd like to get this merged.
