### ISSUE TITLE
Declaration emit drops expando properties when the synthesized namespace also contains `export { … }`

### ISSUE THREAD

**Issue by lassan** [microsoft/TypeScript#63699]
### 🔎 Search Terms

expando, declaration emit, namespace, `export {`, function property, 7.0 regression

### 🕗 Version & Regression Information

- This changed between versions **6.0.3** and **7.0.2**.
- Still reproduces on **7.1.0-dev.20260731.1**.

### ⏯ Playground Link

Not linked — the bug is in `.d.ts` output, so it needs the compiler rather than the playground's type view.

### 💻 Code

```ts
// repro.ts
const updates = { go: 1 }

export function workflow(input: { x: string }) {
  return input.x
}

workflow.id = (input: { x: string }) => `id_${input.x}`
workflow.updates = updates
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "declaration": true,
    "emitDeclarationOnly": true,
    "outDir": "dist",
    "strict": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "target": "es2022"
  },
  "files": ["repro.ts"]
}
```

### 🙁 Actual behavior

7.0.2 and 7.1.0-dev emit:

```ts
declare const updates: {
    go: number;
};
export declare function workflow(input: {
    x: string;
}): string;
export declare namespace workflow {
    var id: (input: {
        x: string;
    }) => string;
    export { updates };
}
export {};
```

Because `updates` was assigned from a local identifier it is emitted as `export { updates }`, while `id` — assigned an inline expression — is emitted as a bare `var`. Introducing an explicit `export { … }` puts the namespace body into explicit-export mode, so the un-prefixed `var id` is no longer an export of `workflow`.

The emitted declaration is therefore not equivalent to the source. A consumer of the `.d.ts`:

```ts
import { workflow } from "./dist/repro.js"

workflow.updates      // ok
workflow.id({ x: "1" })
//        ~~ error TS2339: Property 'id' does not exist on type 'typeof workflow'.
```

The property is silently missing — `tsc` emits the file without complaint, and the failure only appears in whatever consumes it.

### 🙂 Expected behavior

Every expando property assigned to the function should be visible on the emitted type, regardless of whether it was assigned from an identifier or an inline expression. 6.0.3 emits both uniformly and the consumer compiles:

```ts
export declare function workflow(input: {
    x: string;
}): string;
export declare namespace workflow {
    var id: (input: {
        x: string;
    }) => string;
    var updates: {
        go: number;
    };
}
```

Either form seems fine as long as it is consistent — the bug is the mix of `var` and `export { … }` in one namespace body.

### Additional context

This pattern is common in the wild for tagging metadata onto a function (Temporal workflow definitions, React compound components, etc.), and the mix of identifier and inline assignments arises naturally. In our codebase 35 declarations emitted this shape after upgrading to 7.0; nothing failed at emit time, and only the two whose properties were consumed through the `.d.ts` surfaced an error. The workaround is to hoist every inline expression to a local `const` so all members emit as `export { … }`.

**Comment by lassan** [comment]
Withdrawing this — filed prematurely on my side before we'd decided to report it upstream. Closing to keep it out of your triage queue. Apologies for the noise.
