### ISSUE TITLE
5.5.0 inheriting outDir: ${configDir} does not automatically exclude it from compilation

### ISSUE THREAD

**Issue by Knagis** [microsoft/TypeScript#58327]
### 🔎 Search Terms

configDir

### 🕗 Version & Regression Information

This is likely bug with feature introduced in 5.5.0

### ⏯ Playground Link

https://github.com/Knagis/importHelpers-5.5.0/tree/exclude-lib

### 💻 Code

tsconfig.base.json
```json
{
    "compilerOptions": {
        "outDir": "${configDir}/lib",
    },
}
```

packages/foo/tsconfig.src.json
```json
{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": {
        "composite": true,
    },
    "include": [
        "**/*.ts"
    ],
    "exclude": [
        "**/*.spec.*",
    ],
}
```

packages/foo/tsconfig.test.json
```json
{
    "extends": "../../tsconfig.base.json",
    "compilerOptions": {
        "composite": true,
    },
    "references": [
        {
            "path": "tsconfig.src.json"
        },
    ],
    "include": [
        "**/*.spec.ts"
    ],
}
```

### 🙁 Actual behavior

When using `outDir: "${configDir}/lib"` in the base config, compiling this project results in

```
error TS5055: Cannot write file 'C:/Code/tslibissue/packages/foo/lib/src/index.d.ts' because it would overwrite input file.
```

### 🙂 Expected behavior

Project compiles without errors

### Additional information about the issue

If i specify `outDir: "lib"` or even `outDir: "${configDir}/lib"` in both src.json and test.json, the project compiles without errors as the lib folder seems to be automatically excluded from the compilation.

**Comment by Knagis** [comment]
seems that this has always been the case and specifying `outDir: "lib"` doesn't affect this. now i need to figure out why i have this regression in our monorepo when upgrading from 5.4.5 to 5.5.0..

**Comment by Knagis** [comment]
🤔 project that compiles without issue on 5.4.5, fail with the issue described here with 5.5.0. Adding explicit `"exclude": ["lib"]` to the project solves the issue, but that was never needed before...

**Comment by Knagis** [comment]
Updated/simplified reproduction repo, now it reproduces the stated error as is and uncommenting `outDir` in the derived tsconfig.json prevents it.

**Comment by Knagis** [comment]
`tsc --showConfig` with inherited outDir:

```json
{
    "compilerOptions": {
        "outDir": "./lib",
        "composite": true,
        "declaration": true,
        "incremental": true
    },
    "files": [
        "./lib/src/index.d.ts",
        "./lib/src/index.spec.d.ts",
        "./src/index.spec.ts",
        "./src/index.ts"
    ],
    "include": [
        "**/*.ts"
    ]
}
```

the same with outDir defined in the derived config:
```
{
    "compilerOptions": {
        "outDir": "./lib",
        "composite": true,
        "declaration": true,
        "incremental": true
    },
    "files": [
        "./src/index.spec.ts",
        "./src/index.ts"
    ],
    "include": [
        "**/*.ts"
    ],
    "exclude": [
        "lib"
    ]
}
```

**Comment by Knagis** [comment]
ok, so the issue isn't really configDir - but that the outDir from base config isn't ever applied as exclude rule. if i specify `outDir: "packages/foo/lib"` in the root, the same issue appears. Just that before `${configDir}` it never made sense to not have `outDir` specified in the derived config file.
