### ISSUE TITLE
Putting a decorator on a class makes its inherited static method invisible

### ISSUE THREAD

**Issue by pdeva** [Microsoft/TypeScript#16438]
**TypeScript Version:**  2.2.2/2.3.4

**Code**

This works:

```ts
class Animal {
	static say () {
		console.log("animal");
	}
}
class Dog extends Animal {
}

Dog.say() //prints 'animal'
```
This breaks:
If we add a decorator to `Dog`,  calling `Dog.say()` will throw an exception saying it cant find the function

```ts
class Animal {
	static say () {
		console.log("animal");
	}
}
@log
class Dog extends Animal {
}

Dog.say() //throws Error -  Uncaught TypeError: Dog.say is not a function
```

**Expected behavior:**

After adding decorator, one of 2 things must happen:

1.  `Dog.say()` should work as expected, or
2. Typescript compiler should mark the call as a compile time error.

**Actual behavior:**

- No error by typescript compiler
- Call throws an error at runtime

**Breaking change from previous version**

The code with decorator will work fine in TypeScript 2.1.x with ES5 target.
The code breaks when:
 

- TypeScript 2.1.x with ES6 generation is target
- Typescript 2.2.x/2.3.x with either ES5 or ES6 target is used.

Either way, this is a breaking change from previous typescript version.
Either the new compiler should mark it as error or support it.
The code should not  break at runtime as it does now

**Comment by DanielRosenwasser** [comment]
Looks like it works if `log` is just

```ts
function log(x) {
  return x;
}
```

We need a more complete repro.

**Comment by mhegazy** [comment]
Automatically closing this issue for housekeeping purposes. The issue labels indicate that it is unactionable at the moment or has already been addressed.
