### PR TITLE
consistently check for >, >=, <, <= for unconstrained types with strictNullChecks

### LINKED ISSUE #50603: No error on unconstrained type parameter in `>` comparison
# Bug Report

### 🔎 Search Terms

object is possibly undefined 4.8

### 🕗 Version & Regression Information

- This changed between versions 4.7.4 and 4.8.2

### ⏯ Playground Link

TS playground on 4.8.0-beta [link](https://www.typescriptlang.org/play?ts=4.8.0-beta#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwLaYoA8AKgHwAUmMAXHAJIzBQCGARgDbClkCUdJOAB84KJBw5wA3gCg48uF3hRgAZ3G04gkWIlwAvKPEcA3HIUJocCmhyr4ANzgQEcar2nmFCzK4or1Dnh9EKM9IREAjTgyOAcPWW8khSiggzizZPkAXy84XO8VGCQoXFSYM1ygA).

(The playground doesn't seem to have 4.8.x releases, but I tested on 4.8.0-beta and nightly (4.9.0-dev.XXXXXXX).)

### 💻 Code

```ts
export function min<T>(it: Iterable<T>): T | null {
    let result: T | null = null;
    for (const v of it) {
        if (result === null || result > v) {
            result = v;
        }
    }
    return result;
}
```
```
error TS2532: Object is possibly 'undefined'.

        if (result === null || result < v) {
                               ~~~~~~
```

On that line, hovering over the first `result` shows `T | null`. Hovering over the second `result` shows `T & ({} | undefined)`.

### 🙁 Actual behavior

I get a type error.

### 🙂 Expected behavior

No error.

### PR DESCRIPTION
**Pull request by iisaduan**
fixes #50603, which bisected to #49119

Previously: unconstrained type parameters were inconsistently checked in comparisons, as shown below (5.5.3 [playground](https://www.typescriptlang.org/play/?ts=5.5.3#code/GYVwdgxgLglg9mABMOcA8AVAfACgIYBciGANIgEZEYCUiA3gFCLOIBOAplCK0nluQG4GAXwZjQkWAmSoATJkTsAHlHZgAJgGdE4ANZg4AdzC5CxMpWK1GLNp269+Q0ePDR4SFHADMC5ao1tOmFEAB9EMBAAGyiwnQ12YBgwdnVTKgsqayYWDi4eRD5BESA)): 
```typescript
function f<T>(a: T, b: T) {
   return a > b; \\ okay
}

function g<T extends {} | undefined | null>(a: T, b: T) {
   return a > b; \\ error!! 
      \\ 'a' is possibly 'null' or 'undefined'.ts(18049)
      \\ 'b' is possibly 'null' or 'undefined'.ts(18049)
}
```
That would allow us to write `f(undefined, undefined)` 

Now:

```typescript
    function f1<T>(a: T, b: T): boolean {
        return a > b;
               ~
!!! error TS18046: 'a' is of type 'unknown'.
                   ~
!!! error TS18046: 'b' is of type 'unknown'.
    }
    
    function f2<T extends {} | undefined | null>(a: T, b: T): boolean {
        return a > b;
               ~
!!! error TS18049: 'a' is possibly 'null' or 'undefined'.
                   ~
!!! error TS18049: 'b' is possibly 'null' or 'undefined'.
    }    
```
This PR does not affect the checking of unconstrained types in other locations.

### CODE REVIEW

**Comment by iisaduan** [comment]
@typescript-bot test it 
@typescript-bot pack this

File: tests/baselines/reference/unconstrainedTypeComparison.errors.txt [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+unconstrainedTypeComparison.ts(34,16): error TS18049: 'b' is possibly 'null' or 'undefined'.
+unconstrainedTypeComparison.ts(45,12): error TS18047: 'a' is possibly 'null'.
+unconstrainedTypeComparison.ts(45,16): error TS18048: 'b' is possibly 'undefined'.
+
+
+==== unconstrainedTypeComparison.ts (20 errors) ====
+    function f1<T>(a: T, b: T): boolean {
+        return a > b;
+               ~
+!!! error TS18046: 'a' is of type 'unknown'.
```
Comment (andrewbranch) [inline tests/baselines/reference/unconstrainedTypeComparison.errors.txt:27]: This error message isn't right, though I'm not sure what. `possilby 'null' or 'undefined'` might be alright, since those are the values we're concerned about entering a comparison? And then it's consistent with a constraint of `{} | null | undefined`.

Comment (iisaduan) [reply tests/baselines/reference/unconstrainedTypeComparison.errors.txt:27]: `possibly 'null' or 'undefined'` is the one that comes up with the other PR

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -27493,6 +27493,11 @@ export function createTypeChecker(host: TypeCheckerHost): TypeChecker {
         return type === unknownUnionType ? unknownType : type;
     }
 
+    // use to determine if a parameter may be undefined or null (or is unknown/unconstrained)
+    function getUnknownIfMaybeUnknown(type: Type) {
+        return (strictNullChecks && type.flags & TypeFlags.Instantiable) ? getBaseConstraintOfType(type) || unknownType : type;
```
Comment (gabritto) [inline src/compiler/checker.ts:27498]: I'm assuming from #59059 that making this change to `getTypeFacts` breaks a lot of existing code, is that right?

Also, does making this change to `checkNonNullType` instead also break a lot of code?

Comment (iisaduan) [reply src/compiler/checker.ts:27498]: Yes, I tried that and putting this change direclty into `checkNonNullType` gets a very similar result to #59059 in terms of breaking object index checking

Comment (iisaduan) [reply src/compiler/checker.ts:27498]: A lot of the cases that break relate to this type of index access https://github.com/microsoft/TypeScript/pull/59059#issuecomment-2230097569

**Review by gabritto — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Checking this

@typescript-bot perf test this

File: src/compiler/checker.ts (hunk 2 above)
Comment (DanielRosenwasser) [reply src/compiler/checker.ts:27498]: I don't know if this it's noticeably different in semantics, but istead of doing this, you might want to try to modify `getBaseTypeOfLiteralTypeForComparison` and rename it `getBaseTypeForComparison`. Then pass the result of that into `checkNonNullType`.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:27498]: I would also consider renaming this to `getBaseConstraintOrUnknown`, use `??` instead of `||`, and just get rid of the `strictNullChecks` check.

Comment (DanielRosenwasser) [reply src/compiler/checker.ts:27498]: Also - any clue if this works on unions of unconstrained type parameters? Can you add a test?

```ts
function f<T, U>(x: T | U, y: T | U) {
  return x < y;
}
```

**Review by DanielRosenwasser — CHANGES_REQUESTED** [review]

**Comment by iisaduan** [comment]
@DanielRosenwasser Thanks for the suggestions! Good catch--it does work for unions but not intersections, so I added those cases as well.

**Review by weswigham — APPROVED** [review]

**Comment by gabritto** [comment]
@typescript-bot test it

**Comment by ahejlsberg** [comment]
I have just put up #59437 which I believe is the right fix for #50603 plus the inconsistencies related to unconstrained type parameters vs. type parameters constrained to `{} | null | undefined`. There are an awful lot of interacting parts here. In particular, it only becomes feasible to check that unconstrained generic types are possibly nullable in `--strictNullChecks` mode by first fixing the fact that `obj` shouldn't be null-checked in `obj[key]` when `obj` and `key` both have generic types.
