### PR TITLE
Simplify indexed access types applied to mapped types

### LINKED ISSUE #28839: Strange keyof behavior with combination of Partial and Record.
**TypeScript Version:**  3.2.1

**Search Terms:**
keyof, Record, Partial, ...

But actually, I don't know how to exactly express this problem in the search box...

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

interface ITest {

    a: string;
}

type PartialRecord<K extends keyof any, T> = {

    [k in K]?: T;
};

class SlotTest<ES> {

    private _slots1: Partial<Record<keyof ES, ITest>> = {};

    private _slots2: Record<keyof ES, ITest> = {} as any;

    private _slots3: PartialRecord<keyof ES, ITest> = {};

    public doTest1<K extends keyof ES>(name: K): void {

        /**
         * It works well in v2.9.x, but fails in v3.2.1.
         * [ts] Type '{ a: string; }' is not assignable to type 'Record<keyof ES, ITest>[K]'. [2322]
         */
        this._slots1[name] = {"a": "ggg"};
    }

    public doTest2<K extends keyof ES>(name: K): void {

        /**
         * This works fine.
         */
        this._slots2[name] = {"a": "ggg"};
    }

    public doTest3<K extends keyof ES>(name: K): void {

        /**
         * This works fine.
         */
        this._slots3[name] = {"a": "ggg"};
    }
}
```

**Expected behavior:**

When I used v2.9.2, the code works well.

**Actual behavior:**

But, when I upgrade to v3.2.1, it fails with compilation error message like this:

```
Type '{ "a": string; }' is not assignable to type 'Record<keyof ES, ITest>[K]'.
```

**Playground Link:** 

**Related Issues:** 

https://github.com/Microsoft/TypeScript/issues/18538 maybe

### PR DESCRIPTION
**Pull request by ahejlsberg**
Previously we didn't simplify indexed access types applied to mapped types beyond one level because it could cause infinite recursion when mapped types circularly reference themselves. With this PR we now simplify to any number of levels, meaning that constructs such as the following are no longer errors:

```ts
function test<T, K extends keyof T>() {
    let x: Partial<Record<keyof T, string>>[K] = "hello";  // Was error, now ok
}
```

Fixes #28839.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -67,6 +67,7 @@ namespace ts {
         let enumCount = 0;
         let instantiationDepth = 0;
         let constraintDepth = 0;
+        let simplificationDepth = 0;
```
Comment (weswigham) [inline src/compiler/checker.ts]: What test necessitates tracking this?

Comment (weswigham) [reply src/compiler/checker.ts]: Like, why aren't we simplifying to an arbitrary number of levels deep? `getSimplifiedType` already has a reentrancy guard in place because conditional types caused it to be reentrant.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: tests/cases/compiler/infiniteConstraints.ts

Comment (weswigham) [reply src/compiler/checker.ts]: Looking into it, deleting the `if (objectType.flags & TypeFlags.TypeParameter) {` case within `getSimplifiedIndexedAccessType` fixes the bad generativeness of `infiniteConstraints.ts` (since it's only by diving into a constraint that you could possibly be manufacturing new types during this process). I don't think it should be necessary for anything (why is something that "simplifies" looking at constraints?) and is the only reason that generative-ness can occur. From what I can tell, it's a vestige of when we were missing some assignability rules for indexed accesses, and removing it + adding the `return mapType(instantiateType(getTemplateTypeFromMappedType(objectType), templateMapper), getSimplifiedType);` line in `substituteIndexedMappedType` results in one new error in `keyofAndIndexedAccess.ts` which, looking at it is _correct_.

Comment (weswigham) [reply src/compiler/checker.ts]: And I do so love deleting code.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I think you're right. It does mean that the repro from #13285 will break, but I think that is correct given how it is currently written. It may in fact not be possible to write that example without any type annotations or assertions.

Comment (weswigham) [reply src/compiler/checker.ts]: Aye - the input map type `{[oldId: string]: string}` is too general.

Comment (ahejlsberg) [reply src/compiler/checker.ts]: I've updated the PR, including the closest we can get in the repro from #13285. Unfortunately we need an explicit type annotation because we can't narrow generic types that have `undefined` in their constraint. But that's a known issue.

File: tests/baselines/reference/keyofAndIndexedAccessErrors.js [hunk 2]
```diff
@@ -142,6 +142,16 @@ function test1<T extends Record<string, any>, K extends keyof T>(t: T, k: K) {
...
 }
+
+// Repro from #28839
+
+function f30<T, K extends keyof T>() {
+    let x: Partial<Record<keyof T, string>>[K] = "hello";
+}
+
+function f31<T, K extends keyof T>() {
+    let x: Partial<Partial<Partial<Partial<Partial<Partial<Partial<Record<keyof T, string>>>>>>>>[K] = "hello";
```
Comment (weswigham) [inline tests/baselines/reference/keyofAndIndexedAccessErrors.js]: Aside: Part of me wonders if we should have come rule in place to compact mapped types like this, even when generic.
