### ISSUE TITLE
Intersected Record<…> array types do not work with array methods

### ISSUE THREAD

**Issue by vladdeSV** [microsoft/TypeScript#50964]
# Bug Report

### 🔎 Search Terms

intersect array intersected type map

### 🕗 Version & Regression Information

Every version of TypeScript 4 (Tested nightly and v4.0.5)
Neither of code examples work in v3.9.7 but is related to another issue, see https://github.com/microsoft/TypeScript/issues/50964#issuecomment-1259550942

### ⏯ Playground Link

- [ts@4.8.2](https://www.typescriptlang.org/play?ts=4.8.2#code/MYewdgzgLgBCEC4YCUCmoBOATAPAcgDMQQ8AaGaDASzAHMA+AbQF0YAyFdEbfAIwEMMZClGp0mrALwwWAKFlEMMABShIsEHAJwIAShgBvWTBNwAdAIyyAvvPhmAtvwAOyzZPrnL+gPQ+YAKLIyADyyEgAChggzqgYUACeMHiWeDBYIKgQMGAgsKgAHlTQcGAwibHJaJi4AEREILXklDQMeGbKAEwAzN0AnLryskA) this one bothers me

### 💻 Code

```ts
// ts@4.8.2
const os: Record<'foo', string>[] & Record<'bar', string>[] = []

for (const o of os) {
    o.bar
}

os.map(o => o.bar) // ERROR: Property 'bar' does not exist on type 'Record<"foo", string>'.(2339)
```

### 🙁 Actual behavior

`os.map(o => o.bar) // ERROR: Property 'bar' does not exist on type 'Record<"foo", string>'.(2339)`

Other methods `filter`, `some`, `find` do not work either.

### 🙂 Expected behavior

No error, just as in the normal for-loop.

**Comment by jcalz** [comment]
Looks like a duplicate of #41874

**Comment by vladdeSV** [comment]
I don't think it's a duplicate.

That issue is only for ts@3.9, and the type is regarded as a union. I'll clarify my issue and remove references to any ts@3.9 code.

My issue is that the type is correct in an ordinary for-loop, but not for array methods.

**Comment by RyanCavanaugh** [comment]
I agree this is a duplicate; the problem described is explained in #41874.

**Comment by vladdeSV** [comment]
Ah, my bad. It's definitely a dupe.

Should this issue be closed?
