### PR TITLE
Rerun LKG to remove 'awaited' type

### PR DESCRIPTION
**Pull request by rbuckton**
This regenerates the LKG in master now that we've reverted 'awaited'.

### CODE REVIEW

**Comment by muuki88** [comment]
This commit removes the `WindowConsole` object. Was this intented? It breaks `window.console` access with `Property 'console' does not exist on type 'Window'`

**Comment by muuki88** [comment]
It seem that this was introduced in https://github.com/microsoft/TSJS-lib-generator/pull/831

**Comment by gaspard** [comment]
This commit breaks the generateKey overloads in SubtleCrypto...

I have no idea how to fix this...

```ts
interface SubtleCrypto {
    // AlgorithmIdentifier is too generic and masks other overloads. This definition should come last.
    // Previous definition had only 'string' which was more specific and prevented other definitions from
    // being hidden.
    generateKey(algorithm: AlgorithmIdentifier, extractable: boolean, keyUsages: KeyUsage[]): Promise<CryptoKeyPair | CryptoKey>;
    generateKey(algorithm: RsaHashedKeyGenParams | EcKeyGenParams | DhKeyGenParams, extractable: boolean, keyUsages: KeyUsage[]): Promise<CryptoKeyPair>;
    generateKey(algorithm: AesKeyGenParams | HmacKeyGenParams | Pbkdf2Params, extractable: boolean, keyUsages: KeyUsage[]): Promise<CryptoKey>;
}
```

This breaks compilation for this perfectly correct code:

```ts
export const encAlgo: AesKeyGenParams = {
  name: 'AES-CBC',
  length: 128,
}

crypto.subtle
      .generateKey(encAlgo, true, ['decrypt', 'encrypt']) // ==> THIS USES THE GENERIC OVERLOAD
      // Symetric crypto: should see a CryptoKey
      .then(cryptoKey => { // SEES cryptoKey as CryptoKey | CryptoKeyPair
        crypto.subtle
          .exportKey('raw', cryptoKey) // FAILS NOW
          .then(keyBuffer => {
             // ...
          }, reject)
      }, reject)
```
