### ISSUE TITLE
Cannot import type declaration after 4.7.0-dev.20220323

### ISSUE THREAD

**Issue by ameinhardt** [microsoft/TypeScript#49349]
# Bug Report

After updating typescript to 4.7.2 (i.e. see exact nightly builds below), I get an error about not being able to import node type declaration (TS6137), although the imported project is available directly in node_modules. Can this be resolved by typescript (configuration) without third party package modifications?

### 🔎 Search Terms

TS6137, @types/node, request-compose

### 🕗 Version & Regression Information
- This changed between versions 4.7.0-dev.20220323 and 4.7.0-dev.20220325. The former compiles without error, the latter produces below error.

### ⏯ Playground Link
Run `npm run dev` on
https://stackblitz.com/edit/node-ugydk7?file=package.json

### 💻 Code
empty tsconfig.json, package.json containing only typescript, @types/node, request-compose.
index.ts:
```javascript
import rec from 'request-compose';
```

top of affected compose.d.ts:
```javascript
/// <reference types="node" />
import '@types/node'
import * as http from 'http'
import * as https from 'https'
import * as stream from 'stream'
```

### 🙁 Actual behavior

```bash
$ tsc -b .
node_modules/request-compose/compose.d.ts(2,8): error TS6137: Cannot import type declaration files. Consider importing 'node' instead of '@types/node'.
```

### 🙂 Expected behavior

`tsc -b .` compiles without errors, possibly with an additional tsconfig setting

**Comment by RyanCavanaugh** [comment]
`import '@types/node'` is not a supported form of importing a types package -- if that ever worked, it was because of a bug. The `/// <reference types="node" />` is the correct way to do this; I don't know why they added the incorrect `import` on the following line.
