### PR TITLE
Obey the excludeArgument parameter when checking JSX signature validity

### LINKED ISSUE #27986: Type inference in JSX broke in nightly build
**TypeScript Version:**  3.2.0-dev.20181019

**Search Terms:** react jsx type inference

**Code**
```ts
import * as React from "react";

interface ErrorResult {
    readonly error: true
}

interface AsyncLoaderProps<TResult extends {}> {
    readonly asyncLoad: () => Promise<TResult>;
    readonly children: (result: Exclude<TResult, ErrorResult>) => React.ReactChild;
}

class AsyncLoader<TResult extends {}> extends React.Component<AsyncLoaderProps<TResult>> {
    render() { return null; }
}

async function load(): Promise<{ success: true } | ErrorResult> {
    return { success: true };
}

class SomeComponent extends React.Component<{}> {

    render() {
        return (
            <AsyncLoader asyncLoad={load}>{result =>
                <div>{result.success}</div>
            }
            </AsyncLoader>
        );
    }
}
```

TSC call: `npx tsc -t es2017 -m commonjs --jsx react --strict src/TypeScriptIssue.tsx`

(Without `--strict` there is no compile error.)

**Expected behavior:**
No compile error.

**Actual behavior:**
```
src/TypeScriptIssue.tsx:24:26 - error TS2322: Type '() => Promise<ErrorResult | { success: true; }>' is not assignable to type '() => Promise<{ success: true; }>'.
  Type 'Promise<ErrorResult | { success: true; }>' is not assignable to type 'Promise<{ success: true; }>'.
    Type 'ErrorResult | { success: true; }' is not assignable to type '{ success: true; }'.
      Type 'ErrorResult' is not assignable to type '{ success: true; }'.
        Property 'success' is missing in type 'ErrorResult'.

24             <AsyncLoader asyncLoad={load}>{result =>
                            ~~~~~~~~~

  src/TypeScriptIssue.tsx:8:14
    8     readonly asyncLoad: () => Promise<TResult>;
                   ~~~~~~~~~
    The expected type comes from property 'asyncLoad' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<AsyncLoader<{ success: true; }>> & Readonly<{ children?: ReactNode; }> & Readonly<AsyncLoaderProps<{ success: true; }>>'
```

This is a regression in 3.2.0. Code compiles in 3.1.3.

### PR DESCRIPTION
**Pull request by weswigham**
It controls if we skip fixing parameter types or not; so without it we were fixing parameter types during the first step but not locking in the inference result, causing the discrepancy noted.

Fixes #27986

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -7082,7 +7082,9 @@ namespace ts {
         function getDefaultConstraintOfConditionalType(type: ConditionalType) {
             if (!type.resolvedDefaultConstraint) {
                 const rootTrueType = type.root.trueType;
-                const rootTrueConstraint = rootTrueType.flags & TypeFlags.Substitution ? (<SubstitutionType>rootTrueType).substitute : rootTrueType;
+                const rootTrueConstraint = rootTrueType.flags & TypeFlags.Substitution
+                    ? ((<SubstitutionType>rootTrueType).substitute).flags & TypeFlags.AnyOrUnknown ? (<SubstitutionType>rootTrueType).typeVariable : getIntersectionType([(<SubstitutionType>rootTrueType).substitute, (<SubstitutionType>rootTrueType).typeVariable])
```
Comment (sandersn) [inline src/compiler/checker.ts]: what is this for?

Comment (sandersn) [reply src/compiler/checker.ts]: also, PLEASE make this line a little shorter. I can't read this diff even in VSCode's diff view.
(I also don't like double-nested ternarys of the form ??:: but they are palatable with shorter lines)

Comment (sandersn) [reply src/compiler/checker.ts]: ok, I remember you telling me about this. Is the new SubtleSkip test intended to test this? I don't see any conditional types with a constraint of any | unknown.

Comment (weswigham) [reply src/compiler/checker.ts]: Fixing conditional types once the change is in. Without it, a conditional type `T extends any ? T : never` (as in the react `.d.ts`) has a contextual type of `any` instead of `T`.
