### ISSUE TITLE
Type narrowing in one case statement does not propagate to the next case

### ISSUE THREAD

**Issue by johan13** [microsoft/TypeScript#56361]
### 🔎 Search Terms

* Type narrowing
* Switch statement

### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about switch statements and type narrowing.

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.3.0-beta#code/GYVwdgxgLglg9mABMOcAUBDATgcwFyIDOUWMYOiAPouACYCmwZ9tAlIgN4BQivRA7jCgQAFojQkQ9dtz5zEEDIXqJsFALyaaYBkzAs8Pecagiscfon2WAolnNY0rANxcjxxctW4AdMWxQhADqQiJoAEQAHuGsBAD0cYj09nBYiAAqAMoAjAAcAAwALLkEAORqpYgwhIgADnCEhDAARgA2AJ6IpXSMzLSlPu7GfFj0UCBYSOEAguGuQ3K6GCCtUIbD8qPjk4jhAEJzQwC+XCdAA

### 💻 Code

```ts
function foo(arg: string | undefined) {
    switch (true) {
        case arg === undefined:
            throw new Error();

        case arg.startsWith("x"): // error TS18048: 'arg' is possibly 'undefined'.
            return "A";

        default:
            return "B";
    }
}
```

### 🙁 Actual behavior

`error TS18048: 'arg' is possibly 'undefined'.` in the second case.

### 🙂 Expected behavior

I expect the type to be narrowed to string in the second case statement.

### Additional information about the issue

See also #56352. Ping @Andarist.

**Comment by MartinJohns** [comment]
I feel dirty seeing this code.

**Comment by RyanCavanaugh** [comment]
Forgive me if this comes off weird, but do you actually write code like that?

**Comment by johan13** [comment]
> Forgive me if this comes off weird, but do you actually write code like that?

No. I was just trying to reduce this to a minimal example that still reproduces the same behaviour. The original code was a bit more sane. :-)

**Comment by johan13** [comment]
That being said, you guys started this whole thing by suggesting the `switch (true)` pattern in the 5.3 release notes. 😉

**Comment by jakebailey** [comment]
"suggesting" is a strong term 😄 

At best, MDN has examples of it and some projects use it in lieu of pattern matching.

In any case, these issues are at least exposing that our CFA doesn't actually flow between case expressions, which was true before.

**Comment by yoursunny** [comment]
I'm having a similar issue with this code [playground](https://www.typescriptlang.org/play?ts=5.2.2#code/MYewdgzgLgBATgUwIIwLwwPQD0kAoA6AJgNQCUAJBgNwBQoksiAQmplgSaU5bTQGYBXMMCgBLcDD64ANqLAIAXDGhw5Ac1JKwAgLYAjBHBgBvGjHMxpCWDqUAlBGoCiADwAOrhMCRw4AQwBPGAAfGG1paRCYIUIEPjkEQloLZQB3UShgAAsYXCg4AQRSEzMUi2A-CAQYAEIa3B1WRCQAOgQXLxkE0k0Ssv74awE4MBgdGoBtAEYAXRarMDUoLOSBgF9S-oqq2vrG9GY2juAu+R6lUwGyxChh0fHpuYWllc2yjZSPixu7mABaKa0DZAA):

```ts
const reA = /^A(\d+)$/;
const reB = /^(\d+)B$/;

function f(line: string): number {
    let m: RegExpExecArray | null | undefined;
    switch (true) {
        case !!(m = reA.exec(line)): {
            return m![1].length;
        }
        case !!(m = reB.exec(line)): {
            return m![1].length;
        }
    }
    return -1;
}
```

This code works in TypeScript 5.2.
After upgrading to TypeScript 5.3, the compiler gives error "Property 'length' does not exist on type 'never'." because it somehow thinks the `m` in second case is `never`.
If I declare a separate variable `m2` of same type and assign to that in the second case, the code works.

> Forgive me if this comes off weird, but do you actually write code like that?

I actually wrote code like this, [real code](https://github.com/yoursunny/NDNts/blob/e3b6d08109ac106721fd874d5b088325d9723c60/packages/trust-schema/src/schema/versec/token.ts#L161).
`switch (true)` is a common pattern in Go programming language, and I brought it to TypeScript.

**Comment by jakebailey** [comment]
I don't think that's directly related, but a new bug with the new implementation and probably deserves its own issue.

**Comment by Vlad-Shcherbina** [comment]
I think there is a much less exotic situation where this issue manifests: accidental duplicate case constants.
```ts
function f(x: "a" | "b"){
    switch (x) {
        case "a": break;
        case "a": break;  // no error ☹️
        case "b": break;
    }
}
```
If narrowing after switch cases worked correctly, the type of `x` would narrowed to `"b"` after the first branch, and the second branch would be a type error.

For comparison, the equivalent else-if chain behaves as expected:
```ts
if (x === "a") {
    ...
} else if (x === "a") {  // error 🙂
    ...
} else if (x === "b") {
    ...
}
```

**Comment by Xample** [comment]
Here is [another example](https://www.typescriptlang.org/play/?ts=5.6.0-beta#code/FAMwrgdgxgLglgewgAjgZwBIFMA2OEAUAbgIY5hYBcyaMATnBAOYCU1ARggjliSgN7BkwkcLpYYYOilLksyALxLkAImx4EKgNzAAvsFCRYiFOgxxiZCtVoNmbZJ268BQ0SPGTpyWRUXK1OG09A3BoeCRUNABVCAATLBBGLDjLOWo+AE8HX3l0ZEgEpIgU5EF3DwkpFBhMgAcsBBAfK3klBVVbRiZg-VCjCNM0AHFxCW60igB+G3puhycePjK3CrQAdzgYKAALZAJ6ChYVitORKBI0PJj4xOTU3IdPauQQMiudM7OLq6j1fEmWCeVW8hywny+FR+13MgOBXhqdAoEMhoiKJDAOBg1Ge3jeOA+BjO+j6AHpSchNjAdggwDAaFTdshof1wiYoqMsONmABJECAmY0Ob2DhcJauM5wZoEdCxIr3OHHcqo0S4lD4wnE1buKX7My4AGPJXalVq5BglHufSS6VmCxGk4qyoI81I8EmkTW05mjXuvRAA):

```typescript

function isHello(value: string): boolean {
        return value === "Hello";
}

function isHi(value: string): boolean {
        return value === "Hi";
}

function isUndefined(value: any): value is undefined {
        return typeof value === "string";
}


function isGreeting(value?: string): boolean {
        switch (true) {
                case isUndefined(value): return false;
                case isHello(value): return true;
                case isHi(value): return true;
                default: return false;
        }
}

// without switch case

function isGreetingIf(value?: string): boolean {
        if (isUndefined(value)) {
                return false;
        }
        if (isHello(value)) {
                return true;
        }
        if (isHi(value)) {
                return true;
        }
        return false;

}
```

Note: In the real world the conditions are errors checking and the returned value, an enum of the corresponding error.

**Comment by JosXa** [comment]
> Forgive me if this comes off weird, but do you actually write code like that?

I do think there are situations where a `switch(true)` expression can make the code a lot more readable. Random real world code example where I just stumbled over this TS bug:

Before:
```ts
    if (!fileKind) {
      return [false, `We cannot deal with file type '${mimeType}'.`];
    }

    if (this.allowedFileKinds === 'all') {
      return VALID;
    }

    if (!this.allowedFileKinds.includes(fileKind)) {
      return [false, `We cannot deal with file type '${mimeType}'.`];
    }
```

After:
```ts
    switch (true) {
      case !fileKind:
        return [false, `We cannot deal with file type '${mimeType}'.`];
      case this.allowedFileKinds === 'all':
        return VALID;
      case !this.allowedFileKinds.includes(fileKind):
        //                                 ^? Not inferred to be truthy!
        return [false, `We cannot deal with file type '${mimeType}'.`];
      default:
        return VALID;
    }
```

**Comment by Benjamin-Dobell** [comment]
I believe I've ran into a much simpler reproduction for this that doesn't contain any, ah, unusually convoluted case conditions.

[Playground](https://www.typescriptlang.org/play/?#code/KYOwrgtgBAygLgJwJYgOYFFzQN4CgpQCCUAvFAOQCG5ANPlAEKkUBGtuAvrrnAJ4AOwWIhSokAMyTAAJpkgA1SgBswQsgAMAJNnjI0ciB3UBubuLAgAxnCQB7EFEsALYJYDWAOWAA3YAgA8ACpQwAAecKDSAM5QID5+AHwAFHAAXFCBAJRQeFy45lY29lDilEhKUUneyqrpuqISUrJYiirA2XgEUQDuSHDOUFU17Tn0BJaUUUL1+lgAdISpY6MEq472UXCOLu7pVOTM1W2mawQsCMCUbierXGsTU8J6GPMM6Z2nlhtbzq5ue2xDsMbmtzpdrss7qtpMBSmAlGlluMdp54gghm1MsYoAB6HFQI6qKBRJy2eHSKAsIQgSgIBC2boyKBwWyxNFQFwXehcPJ8QRQVpIaSUCLocKRKJBELikDRRiTYA0eVTBLMQKmfIWax2BzdWwINyEekWaQY2pPBqSGQGVqqDr0L4gTbEyjiYA24ZAtpQSYC5RCkXumXRfwzF6QJV84C2cQE4YJbF4qAAYUmcCVLDAPxRzKcIqgZIQjjTUCQMSOQrm9HoPT6AySUVd7paw3t9wVFtmkAW7yR6yd2b+e2ozEbbo9xz7YKuIKgUPGHbDBjmbxWn2+2yHrAOZDHzYUwKnFxnkOWMLhCKWp037i8vnRe4ndpuPNwQA)

```ts
enum StringEnum {
  A = 'a',
  B = 'b',
}

type StringifiedEnumValue = `${StringEnum}`;

function checkNever<T extends never>(t: T) {
}

function unexpectedlyFails(value: StringifiedEnumValue) {
  switch (value) {
    case StringEnum.A:
    {
      const check: 'a' = value;
      break;
    }
    case StringEnum.B: {
      const check: 'b' = value;
      break;
    }
    default:
      checkNever(value); // value should be narrowed to never here
  }
}
```

`value` should have been narrowed to `never`. I use this pattern extensively with enums.

It's seemingly the implicit conversion between strings and enum string values that trips up the type checker here. I can work around this as follows:

```ts
type ValidateExtends<T extends Base, Base> = T;

function workAround(value: StringifiedEnumValue) {
  const safeEnumValue = value as ValidateExtends<StringEnum, typeof value>; // Cast, but check that our cast is valid.
  
  switch (safeEnumValue) {
    case StringEnum.A: {
      const check: 'a' = safeEnumValue;
      break;
    }
    case StringEnum.B: {
      const check: 'b' = safeEnumValue;
      break;
    }
    default:
      checkNever(safeEnumValue);
  }
}
```
