### ISSUE TITLE
Referenced project not building with circular dependencies

### ISSUE THREAD

**Issue by mokcrimea** [Microsoft/TypeScript#26902]
**TypeScript Version:**  3.1.0-dev.20180905

**Search Terms:**
project references, composite build
**Code**
Simple example of the project - https://github.com/mokcrimea/ts-bug

**Expected behavior:**
No errors.
**Actual behavior:**
Compile error:
```
lib/build/src/index.d.ts:1:33 - error TS2307: Cannot find module './someOtherInterface'.

1 import { IOtherInterface } from "./someOtherInterface";
```
**Related Issues:**

**Comment by sheetalkamat** [comment]
Built from master and no errors, seems to be fixed through rework on tsbuild
`
c:\temp\ts-bug>node c:\TypeScript\built\local\tsc.js -b -v
[11:55:38] Projects in this build:
    * lib/tsconfig.json
    * tsconfig.json

[11:55:38] Project 'lib/tsconfig.json' is out of date because output file 'lib/build/src/index.js' does not exist

[11:55:38] Building project 'c:/temp/ts-bug/lib/tsconfig.json'...

[11:55:40] Project 'tsconfig.json' is out of date because output file 'build/src/index.js' does not exist

[11:55:40] Building project 'c:/temp/ts-bug/tsconfig.json'...
`

**Comment by mokcrimea** [comment]
It's works in `3.2.0-dev.20180927`. 
Thank you.
