### PR TITLE
Use 'void' for the contextual type of an unused expression

### PR DESCRIPTION
**Pull request by rbuckton**
This Draft PR primarily is intended to investigate the consequence of contextually typing unused expressions to `void`.

### CODE REVIEW

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
From what I can see, using `void` as the contextual type of any unused expression seems to be a major breaking change.

**Comment by rbuckton** [comment]
The most recent commit demonstrates only contextually typing unused `await` to `void`.

**Comment by rbuckton** [comment]
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this

**Comment by rbuckton** [comment]
@typescript-bot user test this

**Comment by rbuckton** [comment]
From the user tests:
### chrome-devtools-frontend:
```
node_modules/chrome-devtools-frontend/front_end/bindings/TempFile.js(77,9): error TS2322: Type '(value?: void | PromiseLike<void>) => void' is not assignable to type '(this: FileReader, ev: ProgressEvent<FileReader>) => any'.
  Types of parameters 'value' and 'ev' are incompatible.
    Type 'ProgressEvent<FileReader>' is not assignable to type 'void | PromiseLike<void>'.
      Property 'then' is missing in type 'ProgressEvent<FileReader>' but required in type 'PromiseLike<void>'.
```

Due to the fact the contextual type is `void` instead of `unknown`, this no longer becomes assignable to the `onloadend` handler of a `FileReader`. Addressing this would require either a cast of the promise or changing the code to `reader.onloadend = () => resolve();`

```
node_modules/chrome-devtools-frontend/front_end/ui/UIUtils.js(1995,65): error TS2345: Argument of type '(value?: void | PromiseLike<void>) => void' is not assignable to parameter of type '(arg0: Event) => any'.
  Types of parameters 'value' and 'arg0' are incompatible.
    Type 'Event' is not assignable to type 'void | PromiseLike<void>'.
      Property 'then' is missing in type 'Event' but required in type 'PromiseLike<void>'.
```

In this case, the `resolve` callback is no longer assignable to the click handler. Addressing this would require casting the promise.

### puppeteer

```
src/node/BrowserFetcher.ts(335,64): error TS2345: Argument of type '(value?: void | PromiseLike<void>) => void' is not assignable to parameter of type '(error: Error) => void'.
  Types of parameters 'value' and 'error' are incompatible.
    Type 'Error' is not assignable to type 'void | PromiseLike<void>'.
      Property 'then' is missing in type 'Error' but required in type 'PromiseLike<void>'.
```

This is another case of `resolve` no longer being assignable to an existing callback.

**Comment by rbuckton** [comment]
At present this does not seem to be a tenable solution. From the user tests, there are several errors where contextually typing to `void` resulted in breaks in both JS and TS code, as `void` is too precise. As this was a change intended to _reduce_ breaks caused by #39817, at this time it does not seem to be a viable solution.
