### ISSUE TITLE
Abstract property access error occurs in non-abstract class constructors

### ISSUE THREAD

**Issue by sirtrollraptor** [Microsoft/TypeScript#19197]
**TypeScript Version:**  starting from 2.6.0-dev.20171010, 2.6.0-dev.20171015

**Code**

```ts
abstract class Animal {
  public abstract name: string;
}

class Cat extends Animal {
  public name = "Cat";
}

class Foo {
  constructor(animal: Animal) {
    animal.name;
  }
}

new Foo(new Cat());
```

**Expected behavior:**
No compilation error should occur.

**Actual behavior:**
`index.ts(11,12): error TS2715: Abstract property 'name' in class 'Animal' cannot be accessed in the constructor.`
This regression was introduced in #19005, as accessing an abstract property in *any* constructor causes this error, rather than the indented goal of disallowing abstract property accesses only in the constructors of abstract classes that are/extend the abstract class that the abstract property belongs to.

**Comment by RyanCavanaugh** [comment]
@sandersn can you take a look ASAP? Thanks!

**Comment by sandersn** [comment]
The error is just missing a check that the usage is inside the constructor of the declaring class, not just any constructor. I'll add the check.

**Comment by mhegazy** [comment]
The original change is 2.7 bound, so this fix needs to go into master.
