### PR TITLE
Remove undefined from optional spread properties

### LINKED ISSUE #16509: Object spread with Partial breaks in TS 2.4
Test program works in TS2.3 and fails in TS2.4:

```ts
interface Fields {
  foo: number;
  bar: string;
}

declare let y: Fields;
declare let z: Partial<Fields>;

let x: Fields = {...y, ...z};
```

```sh
sigint:~/t$ tsc --version
Version 2.3.4
sigint:~/t$ tsc
sigint:~/t$ ./node_modules/.bin/tsc --version
Version 2.4.0
sigint:~/t$ ./node_modules/.bin/tsc 
f.ts(9,5): error TS2322: Type '{ foo: number | undefined; bar: string | undefined; }' is not assignable to type 'Fields'.
  Types of property 'foo' are incompatible.
    Type 'number | undefined' is not assignable to type 'number'.
      Type 'undefined' is not assignable to type 'number'.
```

### PR DESCRIPTION
**Pull request by sandersn**
Fixes #16509 by making the change from #15938 less strict. This is
technically a hole, but it's not as big a hole as before #15938.

### CODE REVIEW

**Comment by mhegazy** [comment]
and we need this in release-2.4 as well.

**Comment by sandersn** [comment]
It's now in release 2.4.
