### ISSUE TITLE
 type assertions affect the type narrowing of the subsequent code

### ISSUE THREAD

**Issue by a145789** [microsoft/TypeScript#58050]
### 🔎 Search Terms

Type Assertion type Narrowing 

### 🕗 Version & Regression Information

- This changed between versions 5.3.3 and 5.4.3

### ⏯ Playground Link

https://www.typescriptlang.org/play?ts=5.4.3#code/JYWwDg9gTgLgBAbzjAnmApnAwhcEB26+MANMmpgAoA2ArgObD5wC+cAZlLnAOQButdDwBQwgPRjyGbHAC82XJELEA2j3wBDEEIC6w9AA9IsKZhx5lMAOrAYACwCS+AM4wN1agB4AKgD45cN5wAGRwNAxM+kbQ8KjSNvZOru7U4YzM8kgA+mBQ6OzABgD8AFxwrlBM9Kyihsbw7LT4AMYwwARwAO62ji5uHp5YcIYwRAAmzgoWRKSBwwaj+BNwCb3JHmlMvgAUwnBwzYoEM2VDAD7YKjoke8gaUPToMKWBwgCUZRVViLeHfQdHSyrJL9agBbZuB5POBFIoA6bEN5wDSTcxKGbAvopHy+X4EVzw9HESbyACCUCgGhQADpgM5yZSUNtDgiYEi4SyifAyipOcdiHo8f8kJptKwAnzLM4VAAGHRwW7Adhwbai9BIhC3fZ5GC0KDMNW3FiibVPPXMABEFuExuEQA

### 💻 Code

```ts
import { type Component, type Plugin } from 'vue'

// type C = Component['name']
export type ComponentWithInstall<T> = T & Plugin
export type WithInstallPlugin = { _prefix?: string }

export function withInstall<C extends Component, T extends WithInstallPlugin>(
  component: C | C[],
  target?: T
): string {
  const componentWithInstall = (target ?? component) as ComponentWithInstall<T>
  const components = Array.isArray(component) ? component : [component]

  const { name } = components[0] 
  if (name) {
    return name
  }

  return ""
}

```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/37403253/b2c931e2-8b62-4697-ad9f-0a07ef6641ca)
the name property is underlined in red, indicating an error.
> Property 'name' does not exist on type 'Component'.(2339)

The `type C = Component['name']` is valid, as the `name` property exists within the `Component` type. When I remove `const componentWithInstall = (target ?? component) as ComponentWithInstall<T>`, everything returns to normal. Alternatively, if I uncomment `type C = Component['name']`, even though it's not used anywhere, the error disappears. Type assertions should not affect the type narrowing of subsequent code, but an error occurs. This code worked fine in version 5.3.3, but started to error in version 5.4.3.

### 🙂 Expected behavior

Ts don't report the error.

**Comment by MartinJohns** [comment]
> This is a crash

This is no crash. Crash means the compiler crashes, not you receiving an error.

> This changed between versions 5.3.3 and 5.3.4

You probably mean 5.4.3? There is no version 5.3.4.

**Comment by a145789** [comment]
> > This is a crash
> 
> This is no crash. Crash means the compiler crashes, not you receiving an error.
> 
> > This changed between versions 5.3.3 and 5.3.4
> 
> You probably mean 5.4.3? There is no version 5.3.4.

Excuse my carelessness; I have made revisions.

**Comment by ahejlsberg** [comment]
That's very strange. I'll take a look.

**Comment by jcalz** [comment]
crossref [Will type assertions affect the type narrowing of the subsequent code?](https://stackoverflow.com/questions/78265645/will-type-assertions-affect-the-type-narrowing-of-the-subsequent-code)

**Comment by ahejlsberg** [comment]
The issue here appears to be inconsistent caching of union and intersection property lookups, specifically the caching logic in `getUnionOrIntersectionProperty` and its handling of the (misspelled) `skipObjectFunctionPropertyAugment` parameter. It doesn't have anything to do with narrowing.

**Comment by ahejlsberg** [comment]
I see what's happening. For various reasons we have two caches for resolved property lookups on unions and intersections, one that includes property augmentations from `Object` and `Function`, and one that doesn't. Logic was added in #54753 to propagate entries from the non-augmented cache to the augmented cache (see [here](https://github.com/microsoft/TypeScript/pull/54753/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R14632)), but that's incorrect when properties are marked with `CheckFlags.Partial`. I'll put up a PR with a fix.
