### PR TITLE
Fix partial type relations

### LINKED ISSUE #16985: Regression: 2.4.1 Generic type mismatch
This is a simplified piece of code which demonstrates the problem. It compiles fine in 2.3.4 & 2.4.0, but produces a not assignable error in 2.4.1 and nightly.

**TypeScript Version:**  2.4.1 / nightly (2.5.0-dev.20170629)

**Code**

```ts
interface MyInterface {
  something: number;
}

class MyClass<T extends MyInterface> {
  doIt(data : Partial<T>) {}
}

class MySubClass extends MyClass<MyInterface> {}

function fn(arg: typeof MyClass) {};

fn(MySubClass);
```

**Expected behavior:**

No compile error.

**Actual behavior:**

```
test.ts(13,4): error TS2345: Argument of type 'typeof MySubClass' is not assignable to parameter of type 'typeof MyClass'.
  Type 'MySubClass' is not assignable to type 'MyClass<T>'.
    Types of property 'doIt' are incompatible.
      Type '(data: Partial<MyInterface>) => void' is not assignable to type '(data: Partial<T>) => void'.
        Types of parameters 'data' and 'data' are incompatible.
          Type 'Partial<T>' is not assignable to type 'Partial<MyInterface>'.
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR the following is no longer an error:

```ts
interface Foo { a: string, b: string }

function f<T extends Foo>(a: Partial<Foo>, b: Partial<T>) {
    a = b;  // No error here
}
```

Fixes #16985.

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -5765,12 +5765,13 @@ namespace ts {
             return type.modifiersType;
         }
 
+        function isPartialMappedType(type: Type) {
+            return getObjectFlags(type) & ObjectFlags.Mapped && !!(<MappedType>type).declaration.questionToken;
+        }
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: This seems like an awfully specific check - does it work on homomorphic mapped types in which all properties of the type being mapped are already optional? For example:

```ts
type Shapify<T> = {
    [K in keyof T]: any;
}

interface MyInterface {
  something?: number;
}

class MyClass<T extends MyInterface> {
  doIt(data: Shapify<T>) {}
}

class MySubClass extends MyClass<MyInterface> {}

function fn(arg: typeof MyClass) {};

fn(MySubClass);
```

The same question applies to if you used `Readonly<T>` or others.

Comment (ahejlsberg) [inline src/compiler/checker.ts]: I'm not sure what you're getting at. The only way we can be certain that *all* properties of the type that results from a mapping operation are optional is if the mapped type includes a `?` in the template specification. That's what we're checking here.

Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: As we discussed offline, that example doesn't apply because a constraint being all-optional (e.g. `MyInterface`) doesn't guarantee that `T` itself will be all-optional.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -9254,8 +9255,12 @@ namespace ts {
...
                         // Report structural errors only if we haven't reported any errors yet
                         const reportStructuralErrors = reportErrors && errorInfo === saveErrorInfo && !sourceIsPrimitive;
-                        if (isGenericMappedType(source) || isGenericMappedType(target)) {
-                            result = mappedTypeRelatedTo(source, target, reportStructuralErrors);
+                        // An empty object type is related to any mapped type that includes a '?' modifier.
+                        if (isPartialMappedType(target) && !isGenericMappedType(source) && isEmptyObjectType(source)) {
+                            result = Ternary.True;
+                        }
+                        else if (isGenericMappedType(target)) {
+                            result = isGenericMappedType(source) ? mappedTypeRelatedTo(<MappedType>source, <MappedType>target, reportStructuralErrors) : Ternary.False;
```
Comment (DanielRosenwasser) [inline src/compiler/checker.ts]: If you made `isGenericMappedType` a type predicate, you could avoid the type assertions.

Comment (ahejlsberg) [inline src/compiler/checker.ts]: No, because something for which `isGenericMappedType` returns false could still be a `MappedType`. We would need to introduce a new unique type representing generic mapped types, but it isn't worth the hassle.

**Comment by ahejlsberg** [comment]
@DanielRosenwasser If you're otherwise done with the review, please close it out and I will get this PR merged.

**Comment by ahejlsberg** [comment]
@DanielRosenwasser Ping!
