### ISSUE TITLE
[3.7.0-beta] Child class cannot override base member function with arrow function

### ISSUE THREAD

**Issue by MLoughry** [microsoft/TypeScript#33855]
**TypeScript Version:**  3.7.0-dev.20190927 (works on 3.7.0-dev.20190926)

**Search Terms:**
TS2424, member function

**Code**

```ts
class BaseClass {
    foo() {
        return null;
    }
}

class ChildClass extends BaseClass {
    foo = () => null;
}
```

**Expected behavior:**
In 3.6.3 and <=3.7.0-dev.20190926, this code would compile without error

**Actual behavior:**
```
error TS2424: Class 'BaseClass' defines instance member function 'foo', but extended class 'ChildClass' defines it as instance member property.

8   foo = () => null;
    ~~~
```

Since our code has to compile down to ES5 (to support IE11), we need to perform some sort of method binding on methods that reference `this`. With this change, it means we would need to make *all* possibly-overridable member functions arrow functions

**Playground Link:** http://www.typescriptlang.org/play/index.html?ts=3.7-Beta#code/MYGwhgzhAEBCkFMDC4rQN4Cho+gMwHsCAKASg21yoCcEAXAV2oDtpmGQQBuSnAX0wDMoSDCQALAJYgAJilHQEADzoJmMmPAjJUMLFUIFoAXmhkTAPjYdugoA

**Related Issues:**

**Comment by sandersn** [comment]
I looked at the change from TS 3.0 again and found that it was supposed to remove only this error but actually removed it as well as the opposite:

```ts
class B {
  foo = () => null
}
class C extends B {
  foo() {
    return null
  }
}
```

I restored both errors in #33509 while adding new errors -- I noticed dead code and confused an intern's first check-in with a broken change.

I'll take this error (property-overrides-method) back out, but leave in the error for method-overrides-property.

**Comment by MLoughry** [comment]
Thanks for the quick fix, @sandersn

**Comment by ulrichb** [comment]
Hmm, this was released in TS@next ~ 3 days ago, but since typescript@3.7.0-dev.20191018 the same error appeared again :/
