### PR TITLE
Fix circular alias error

### LINKED ISSUE #3018: error TS2303: Circular definition of import alias 'default'.
Hi, I'm switching to ES6 modules. The type definition below worked fine in 1.5.0-alpha, but gives an error in 1.5.0-beta

```
declare var io: SocketIOClientStatic;

declare module 'socket.io-client' {
    export default io;
}
```

It seems that error TS2303: Circular definition of import alias 'default' is always given when the export default is a variable. At least the error message is misleading. The earlier form 'export = io' is not allowed in ES6 output mode.

### PR DESCRIPTION
**Pull request by ahejlsberg**
Fixes #3018.

### CODE REVIEW

**Comment by mhegazy** [comment]
:+1:
