### PR TITLE
Enum unification and improvements

### LINKED ISSUE #27976: Enums does not support literal typing with computed values
**TypeScript Version:**  3.2.0-dev.201xxxxx

**Search Terms:**

- enum flag
- enum computed literal typing

**Code**

```ts
enum AnimalFlags {
    None           = 0,
    HasClaws       = 1 << 0,
    CanFly         = 1 << 1,
    EatsFish       = 1 << 2,
    Endangered     = 1 << 3,

    EndangeredFlyingClawedFishEating = HasClaws | CanFly | EatsFish | Endangered,
}

enum RegularEnum {
    None,
    HasPowers,
}


const a = AnimalFlags.EatsFish;
const b: AnimalFlags.EndangeredFlyingClawedFishEating = AnimalFlags.EndangeredFlyingClawedFishEating;
const c = RegularEnum.HasPowers;
```

**Expected behavior:**

`a` Should have type of `AnimalFlags.EatsFish`
`b` Should not throw. Should allow the assignment of `AnimalFlags.EndangeredFlyingClawedFishEating` as type.

I would expect a computed Enum to behave as a regular enum, in this case, `c` has type `RegularEnum.HasPowers`

**Actual behavior:**

`a` is typed as `AnimalFlags`.
`const b: AnimalFlags.EndangeredFlyingClawedFishEating` is throwing `Enum type 'AnimalFlags' has members with initializers that are not literals.`
`b` should be allowed to be typed as `AnimalFlags.EndangeredFlyingClawedFishEating`. 

**Playground Link:** 

[Link](http://www.typescriptlang.org/play/#src=enum%20AnimalFlags%20%7B%0D%0A%20%20%20%20None%20%20%20%20%20%20%20%20%20%20%20%3D%200%2C%0D%0A%20%20%20%20HasClaws%20%20%20%20%20%20%20%3D%201%20%3C%3C%200%2C%0D%0A%20%20%20%20CanFly%20%20%20%20%20%20%20%20%20%3D%201%20%3C%3C%201%2C%0D%0A%20%20%20%20EatsFish%20%20%20%20%20%20%20%3D%201%20%3C%3C%202%2C%0D%0A%20%20%20%20Endangered%20%20%20%20%20%3D%201%20%3C%3C%203%2C%0D%0A%0D%0A%20%20%20%20EndangeredFlyingClawedFishEating%20%3D%20HasClaws%20%7C%20CanFly%20%7C%20EatsFish%20%7C%20Endangered%2C%0D%0A%7D%0D%0A%0D%0Aenum%20RegularEnum%20%7B%0D%0A%20%20%20%20None%2C%0D%0A%20%20%20%20HasPowers%2C%0D%0A%7D%0D%0A%0D%0A%0D%0Aconst%20a%20%3D%20AnimalFlags.EatsFish%3B%0D%0Aconst%20b%3A%20AnimalFlags.EndangeredFlyingClawedFishEating%20%3D%20AnimalFlags.EndangeredFlyingClawedFishEating%3B%0D%0Aconst%20c%20%3D%20RegularEnum.HasPowers%3B)

**Related Issues:** 

I think is the same that one reported last year #18393. It was closed as a Design Limitation, but since there has been some big changes in Typescript maybe this would be worth to be reviewed again.

### LINKED ISSUE #35875: TS 2535 when using const enum values derived from other const enum values
**TypeScript Version:** 3.7.2

**Search Terms:** 2535 const enum

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
const enum Foo { Value = 0x01 }
const enum Bar { Value = 0x02 }
const enum Baz { Value = Foo.Value | Bar.Value }
type Test = Baz.Value

const foo: Foo.Value = Foo.Value
const bar: Bar.Value = Bar.Value
const baz: Baz.Value = Baz.Value
```

**Expected behavior:** It to type-check without errors

**Actual behavior:** "Enum type 'Baz' has members with initializers that are not literals. (2535)" on both the type alias and the `baz` type, referencing `Baz.Value` in the type position.

**Playground Link:**  https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=8&pc=33#code/MYewdgzgLgBApmArgWxgMRCGBvGA1AQwBtE4YBeGABgA8qBGGAXwChRJYEUYAhAgJxz5ipCtToAmZm3DR4SVHwBeQwiTKUMIAHRrRAH14DdIsqygBPAA5kAKnDmVlJ9SxkcYAM0wAudJhdRTQC9OHc5ACMBPz5+QI0jONDw2CilGIIleLFnUKA

**Related Issues:**

### LINKED ISSUE #40793: Enable constants as computed values for string enums
# Search Terms

'TS18033', 'typescript define enum with constant string value', 'string enum computed constant'

## Suggestion

Please consider enabling to use constant variables as values for string enums. The following code snippet fails compilation with TS18033 ('Only numeric enums can have computed members, but this expression has type 'string'. If you do not need exhaustiveness checks, consider using an object literal instead.')

```ts
const VALUE: string = 'ENUM_VALUE';

enum MyEnum {
  KEY = VALUE, // <-- Fails with TS18033
}

console.log(MyEnum.KEY);
```

, whereas the following passes:

```ts
enum Values {
  VALUE = 'ENUM_VALUE',
}

enum MyEnum {
  KEY = Values.VALUE,
}

console.info(MyEnum.KEY);
```

## Use Cases

Use string interpolation (templated strings) when defining the value of a string enum to be able to reuse pre-defined constants as part of the value. (E.g. namespace prefixes, extension postfixes)

## Examples

```ts
const NAMESPACE: string = 'com.mycompany.myservice';

enum Errors {
  INVALID_INPUT_ERROR = `${NAMESPACE}.errors#InvalidInput`,
}
```

## Checklist

My suggestion meets these guidelines:

* [ X ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ X ] This wouldn't change the runtime behavior of existing JavaScript code
* [ X ] This could be implemented without emitting different JS based on the types of the expressions
* [ X ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [ X ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

### LINKED ISSUE #43902: String enums from string constants
# Suggestion

If possible, it would be nice to be able to define enum with string values, coping over string values from other enums (if their values can be calculated statically during compilation). Example:

```TypeScript
export enum ColdColors {
 BLUE = '#0000FF',
 // ...
}

export enum WarmColors {
 YELLOW = '#FFFF00',
 // ...
}

export enum Colors {
  BLUE = ColdColors.BLUE,
  YELLOW = WarmColors.YELLOW,
  // ...
}

// And/OR also

export const robinsEggBlue = '#00C0DE';


export const enum ColdColors2 {
 BLUE = '#0000FF',
 ROBINS_EGG_BLUE = robinsEggBlue,
 // ...
}

export const enum WarmColors2 {
 YELLOW = '#FFFF00',
 // ...
}

export const enum Colors2 {
  BLUE = ColdColors2.BLUE,
  YELLOW = WarmColors2.YELLOW,
  // ...
}
```

## 🔍 Search Terms

List of keywords you searched for before creating this issue. Write them down here so that others can find this suggestion more easily and help provide feedback.

## ✅ Viability Checklist

I **DON'T know** if my suggestion meets these guidelines:

* [ ] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [ ] This wouldn't change the runtime behavior of existing JavaScript code
* [ ] This could be implemented without emitting different JS based on the types of the expressions
* [ ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [ ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## 📃 Motivating Example

As shown above, in the code example, this will help to avoid duplicating constant string literals everywhere (if you want to define them in multiple places, including inside an enum).

## 💻 Use Cases

As stated in the motivation, to group string literals that are defined as constants inside enums

### PR DESCRIPTION
**Pull request by ahejlsberg**
Since #9407 TypeScript has had two kinds of enum types: _Numeric enum types_ and _literal enum types_ (also known as _union enum types_). Numeric enum types have permitted enum members to have computed values, but not literal types; whereas literal enum types have required members to be declared using simple numeric or string literals only. The distinction between these two kinds of enums is subtle and has been the source of a fair amount of confusion over time.

With this PR we unify the two kinds into a single hybrid that incorporates the best of both worlds. Specifically, enums are always represented as unions of their member types, member values may be computed by constant or non-constant expressions, and members with constant values are given literal types. The PR only affects type checking of enums. There are no changes to the emitted code (except for better inlining of constant expressions in some cases).

An enum declaration now declares a type representing the entire enum and types representing each member (similar to literal enum types). For example,

```ts
enum E {
    A = 10 * 10,  // Numeric literal enum member
    B = "foo",    // String literal enum member
    C = bar(42)   // Opaque computed enum member
}
```

declares a type `E` and types `E.A`, `E.B`, and `E.C`, where `E` is the union `E.A | E.B | E.C`.

An enum member has a literal enum type when it is initialized by a constant expression or when it has no initializer and is given an auto-incremented numeric value. In the example above, `E.A` and `E.B` denote enum literal types with values `100` and `"foo"` respectively.

An enum member has a unique and opaque enum member type when it is initialized by a non-constant expression. Non-constant initializer expressions must be assignable to type `number` and are not permitted in `const` enum declarations. In the example above, `E.C` denotes a unique enum member type representing the value computed by the non-constant initializer expression. This unique type is assignable to type `number`, but otherwise incompatible with other types.

An expression is considered a _constant expression_ if it is

* a number or string literal,
* a unary `+`, `-`, or `~` applied to a numeric constant expression,
* a binary `+`, `-`, `*`, `/`, `%`, `**`, `<<`, `>>`, `>>>`, `|`, `&`, `^` applied to two numeric constant expressions,
* a binary `+` applied to two constant expressions whereof at least one is a string,
* a template expression where each substitution expression is a constant expression,
* a parenthesized constant expression,
* a dotted name (e.g. `x.y.z`) that references a `const` variable with a constant expression initializer and no type annotation,
* a dotted name that references an enum member with an enum literal type, or
* a dotted name indexed by a string literal (e.g. `x.y["z"]`) that references an enum member with an enum literal type.

Note that constant expressions are not permitted to make forward references--any value referenced by a constant expression must have been previously declared.

Some examples:

```ts
const BaseValue = 10;
const Prefix = "/data";
const enum Values {
    First = BaseValue,  // 10
    Second,             // 11
    Third               // 12
}
const enum Routes {
    Parts = `${prefix}/parts`,       // "/data/parts"
    Invoices = `${prefix}/invoices`  // "/data/invoices"
}
```

NOTE: This PR is technically a breaking change because checking of the new unified enum types is stricter than the old numeric enum types.

Fixes #27976.
Fixes #35875.
Fixes #40793.
Fixes #43902.

### CODE REVIEW

**Comment by RyanCavanaugh** [comment]
@typescript-bot pack this

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

**Comment by ahejlsberg** [comment]
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster
@typescript-bot test top100

**Comment by ahejlsberg** [comment]
This change has surprising few effects: Performance, user code test suite, and DT test suite are unaffected. One new error in top100 test suite, correctly identifying an issue in `vscode`. Small change in extended test suite, emit now uses inlined constants due to better constant expression folding.

There were four new errors in the compiler itself. See fixes [here](https://github.com/microsoft/TypeScript/pull/50528/commits/3f66f6c499f9170e5d114e977a1512c0fbd12024) and [here](https://github.com/microsoft/TypeScript/pull/50528/commits/f0c2023717aecb53b851cf17a3610d8ae4f13c76). I think these new errors are perfectly fine, even if one of them is a manifestation of #9998.

File: tests/baselines/reference/enumWithExport.types [hunk 1]
```diff
@@ -10,6 +10,6 @@ enum x {
 >x : x
 
   z = y
->z : x.z
```
Comment (sandersn) [inline tests/baselines/reference/enumWithExport.types:13]: interesting change here: `y` is not resolved so `z` gets the type of the parent enum instead of an enum member type. I think that's fine, but I wouldn't have predicted it from reading the code.

File: tests/baselines/reference/parserComputedPropertyName16.types [hunk 2]
```diff
@@ -3,7 +3,7 @@ enum E {
 >E : E
 
   [e] = 1
->[e] : E.__computed
```
Comment (sandersn) [inline tests/baselines/reference/parserComputedPropertyName16.types:6]: similar change here

**Review by sandersn — CHANGES_REQUESTED** [review]

**Comment by Jack-Works** [comment]
what happened to the back referencing `Enum[Enum.Value] === "some value"`? and is it possible to allow symbols?

**Comment by jakebailey** [comment]
@typescript-bot pack this

File: src/compiler/types.ts [hunk 3]
```diff
@@ -3922,8 +3922,8 @@ namespace ts {
     // is distinguished from a regular type by a flags value of zero. Incomplete type
     // objects are internal to the getFlowTypeOfReference function and never escape it.
     export interface IncompleteType {
-        flags: TypeFlags;  // No flags set
-        type: Type;        // The type marked incomplete
+        flags: TypeFlags | 0;  // No flags set
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/types.ts:3925]: Exactly. We actually don't want to have a `TypeFlags.None` because we expect at least one flag to be set.

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -18601,12 +18543,12 @@ namespace ts {
             if (s & TypeFlags.BigIntLike && t & TypeFlags.BigInt) return true;
             if (s & TypeFlags.BooleanLike && t & TypeFlags.Boolean) return true;
             if (s & TypeFlags.ESSymbolLike && t & TypeFlags.ESSymbol) return true;
-            if (s & TypeFlags.Enum && t & TypeFlags.Enum && isEnumTypeRelatedTo(source.symbol, target.symbol, errorReporter)) return true;
+            if (s & TypeFlags.Enum && t & TypeFlags.Enum && source.symbol.escapedName === target.symbol.escapedName &&
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts:18546]: It used to be that `TypeFlags.Enum` types would always have a `SymbolFlags.Enum` symbol. But we now use `TypeFlags.Enum` types with `SymbolFlags.EnumMember` symbols to represent unique enum member types of computed enum members. In `isEnumTypeRelatedTo`, we check that the names of the parent symbols (the containing enum declarations) match, but here we also need that we have matching member names.

BTW, it is still possible for a `TypeFlags.Enum` type to have a `SymbolFlags.Enum` symbol, but that only happes for a completely empty enum declaration.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -18551,19 +18492,20 @@ namespace ts {
...
+            if (sourceSymbol.escapedName !== targetSymbol.escapedName || !(sourceSymbol.flags & SymbolFlags.RegularEnum) || !(targetSymbol.flags & SymbolFlags.RegularEnum)) {
+                return false;
+            }
             const id = getSymbolId(sourceSymbol) + "," + getSymbolId(targetSymbol);
             const entry = enumRelation.get(id);
             if (entry !== undefined && !(!(entry & RelationComparisonResult.Reported) && entry & RelationComparisonResult.Failed && errorReporter)) {
                 return !!(entry & RelationComparisonResult.Succeeded);
             }
-            if (sourceSymbol.escapedName !== targetSymbol.escapedName || !(sourceSymbol.flags & SymbolFlags.RegularEnum) || !(targetSymbol.flags & SymbolFlags.RegularEnum)) {
-                enumRelation.set(id, RelationComparisonResult.Failed | RelationComparisonResult.Reported);
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply src/compiler/checker.ts:18564]: It's cheaper to do the check than to compute a key to fetch a cached result. So, no point in caching.

File: tests/baselines/reference/constEnumPropertyAccess1.errors.txt [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+    var a = G.A;
+    var a1 = G["A"];
+    var g = o[G.A];
+    
+    class C {
+        [G.A]() { }
+        get [G.B]() {
+            return true;
+            ~~~~~~~~~~~~
+!!! error TS2322: Type 'boolean' is not assignable to type 'number'.
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply tests/baselines/reference/constEnumPropertyAccess1.errors.txt:31]: Yup.

File: tests/baselines/reference/parserComputedPropertyName16.types (hunk 2 above)
Comment (ahejlsberg) [reply tests/baselines/reference/parserComputedPropertyName16.types:6]: This one was kinda bad previously. We should've never revealed the `__computed` internal name.

File: tests/baselines/reference/constEnum2.errors.txt [hunk 7]
```diff
@@ -1,10 +1,9 @@
...
 tests/cases/conformance/constEnums/constEnum2.ts(11,9): error TS2474: const enum member initializers can only contain literal values and other computed enum values.
 tests/cases/conformance/constEnums/constEnum2.ts(12,5): error TS1357: An enum member name must be followed by a ',', '=', or '}'.
-tests/cases/conformance/constEnums/constEnum2.ts(12,9): error TS2474: const enum member initializers can only contain literal values and other computed enum values.
 
 
-==== tests/cases/conformance/constEnums/constEnum2.ts (4 errors) ====
+==== tests/cases/conformance/constEnums/constEnum2.ts (3 errors) ====
     // An enum declaration that specifies a const modifier is a constant enum declaration.
     // In a constant enum declaration, all members must have constant values and
     // it is an error for a member declaration to specify an expression that isn't classified as a constant enum expression.
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply tests/baselines/reference/constEnum2.errors.txt:9]: Actually, comments are fine. What's changed here is that `g = CONST` is now an allowed declaration because we've added the ability to compile-time evaluate references to `const` declarations.

That said, the test is missing a comma after one of the declarations, which is rather pointless. I will fix that.

File: tests/baselines/reference/enumWithExport.types (hunk 1 above)
Comment (ahejlsberg) [reply tests/baselines/reference/enumWithExport.types:13]: Actually, it's given the unique enum member type `x.z` associated with a computed member. But we display the type as just `x` because there is only one member (i.e. type `x`, the union of all enum members, and type `x.z` are the same).

File: src/compiler/checker.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (sandersn) [reply src/compiler/checker.ts:18546]: >  but it is common to use empty enum types to declare unique subtypes of number

(!) TIL

**Review by sandersn — APPROVED** [review]

**Review by RyanCavanaugh — APPROVED** [review]

**Comment by WORMSS** [comment]
Would this have a problem?
```ts
const boat = 2;
const goat = 1;
enum NonTier6ItemGraphCodes {
  Moose = boat,
  Goose = goat,
  Loose, // This would ALSO be 2 and stamp over Moose 
}
```
Currently this throws an `Enum member must have initializer` error in TS 4.8.4.

**Comment by andreymaslovru** [comment]
Hi, this is still causing a problem in the latest version of TS.
**"typescript": "^4.9.3"**

`const path = '/admin/refresh'

const enum AuthEndpoints {
  login = '/admin/login',
  refresh = `${path}`  _//error: Computed values are not permitted in an enum with string valued members.ts(2553)_
}

export default AuthEndpoints

`

**Comment by jakebailey** [comment]
This PR is in TypeScript 5.0, not 4.9 (which was closed to new features after the beta). If you want to use it now, you can try the nightlies, but you won't see this in 4.9.

**Comment by WORMSS** [comment]
So, it seems TS5 still has the enum stomping problem 

https://www.typescriptlang.org/play?ts=5.0.0-dev.20221121#code/MYewdgzgLgBARiAhrAvDATAbgFCkrAcyVRgEYcBTMAVwFsYA5cAFQEsKAnANgEkoLaAcQ6IADgAsAwiAAmFCDADe2GDACyIEBAow0CZABoVMQZu26YRQ8YAyZikYC+QA

**Comment by ahejlsberg** [comment]
@WORMSS I'm not sure there's a problem here. TS is perfectly happy for multiple enum members to have the same value. There's no concept of "stomping" on a member--except of course the reverse mapping can only reflect one, which ends up being the last one.

The "Enum member must have initializer" error is gone in 5.0 because the checker now underdstands that `Moose` and `Goose` are constant values (and not computed values).

**Comment by WORMSS** [comment]
Would be nice if it would count to 3.

**Comment by nicojs** [comment]
This is probably off-topic because it probably works by design, but I still have to ask:

Why are string literals not allowed to be assigned to enums while number literals are?

Take this example:

```ts
enum MessageKind {
  Start = 'start',
  Stop = 'stop',
  Wait = 100
}

const wait: MessageKind = 100;
const stop: MessageKind = 'stop'; // 💥 🤷‍♀️
```

https://www.typescriptlang.org/play?ts=5.0.0-dev.20221121#code/KYOwrgtgBAssDO8CGBzYBpAliAJlA3gFBRQDKALkgE7lQC8UA5PJTYwDTFnkD2ADvSYt+HLgHUkmWgwCMABjmEAvoUIBjHiBZQA7pPIAuWAmRosuQfLkBudZu3C+RuIlQZseBs159G1qAD0AVCAvBuApTtAA

**Comment by ahejlsberg** [comment]
> Why are string literals not allowed to be assigned to enums while number literals are?

Numeric enum types have a few extra rules to enable their use as bit flags. In particular, type `number` is assignable to any numeric enum type such that the `&` and `|` operators can be used to compose values. It also used to be that `any` numeric literal type was assignable to _any_ numeric enum type, but now we only allow assignment of a numeric literal type to an numeric enum type with the same underlying value (see #51561).

There is no equivalent scenario for enum string literals, so no need for looser rules.

**Comment by hackwaly** [comment]
Symbols still not works
```
enum MyType {
    foo = Symbol("foo"), // Type 'symbol' is not assignable to type 'number' as required for computed enum member values.ts(18033)
}
```

**Comment by Harpush** [comment]
@ahejlsberg Just a question but after this change `extends` still doesn't work as expected... worth a new issue?
```ts
enum One {
  A = 1,
  B = 2
}

type aa<T> = T extends number ? true : false;
type bb<T> = number extends T ? true : false;
type tt1 = aa<One>; // true - expected
type tt2 = bb<One>; // true - not expected
```
Worth noting it works for string enums

**Comment by RyanCavanaugh** [comment]
@Harpush Your expectation isn't correct. Numeric enums are assignable both to and from `number`

**Comment by Harpush** [comment]
> @Harpush Your expectation isn't correct. Numeric enums are assignable both to and from `number`

So is it by design to behave differently from string enums? I guess there are reasons for it (maybe enum as flags?) so thanks for the clarification. I thought this PR was meant to distinguish between enums meant to be a "named union" - string or number - to computed number enums meant mostly for flags. Out of curiosity - why is there a difference between number and string enums in that matter while both represent so called "named union"?

**Comment by RyanCavanaugh** [comment]
Numeric enums are assignable from `number` because bit flags remains a scenario for those. There's no corresponding behavior for string enums, so there's no need for an assignability "hole" there.

**Comment by Harpush** [comment]
> 

I understand... A shame there is no way to distinguish those. In order to support the flags case all number based enums now have this "hole". Wish there was like in c# that you can mark an enum as flags enum which would solve those problems.

**Comment by Sweater-Baron** [comment]
Is this included in a published version of Typescript yet? Based on the comments in this PR thread, it sounds like it should be in Typescript 5.

I'm on Typescript 5.0.2, but getting the error "const enum member initializers can only contain literal values and other computed enum values.", which I believe shouldn't happen if I'm on a version of typescript that includes this code?

I'm copying the example from the PR:
```
const prefix = '/data';

const enum Routes {
  Parts = `${prefix}/parts`, // "/data/parts"
  Invoices = `${prefix}/invoices`, // "/data/invoices"
}
```

**Comment by janbiasi** [comment]
> Is this included in a published version of Typescript yet? Based on the comments in this PR thread, it sounds like it should be in Typescript 5.

@Sweater-Baron Yes it is, your example is working perfectly fine running version 5.0.2 (see [playground](https://www.typescriptlang.org/play?ts=5.0.2#code/MYewdgzgLgBADgJwKYDMCWAPGBeGByAegBMBDKEvAbgFgAoO0SWJMAVwFsYAlEVqJCDADedGDAAKJBFEG4ABgBIhiVJgC+BOFJlyANDAIEYAImJkSm7RGOiYASTAA3EGmACcMRcuToMGtE4ubhB6BkampOQEAc6uAja0anQM4BAgADZIAHTpIADmABQ8fAJZktIQ+sX8EFkOscEAlJRAA)). If you use VSCode make sure that you use your local TypeScript version and not VSCode's version.

**Comment by JordanDC2** [comment]
Is there any plan to implement enum extension like in this [ playground?: ](url)

Screen Shot 2023-03-21 at 9 01 53 AM

**Comment by isaackhoo** [comment]
> > Is this included in a published version of Typescript yet? Based on the comments in this PR thread, it sounds like it should be in Typescript 5.
> 
> @Sweater-Baron Yes it is, your example is working perfectly fine running version 5.0.2 (see [playground](https://www.typescriptlang.org/play?ts=5.0.2#code/MYewdgzgLgBADgJwKYDMCWAPGBeGByAegBMBDKEvAbgFgAoO0SWJMAVwFsYAlEVqJCDADedGDAAKJBFEG4ABgBIhiVJgC+BOFJlyANDAIEYAImJkSm7RGOiYASTAA3EGmACcMRcuToMGtE4ubhB6BkampOQEAc6uAja0anQM4BAgADZIAHTpIADmABQ8fAJZktIQ+sX8EFkOscEAlJRAA)). If you use VSCode make sure that you use your local TypeScript version and not VSCode's version.

I have set my vscode to use 5.0.2, but im still getting the error
image

**Comment by WORMSS** [comment]
@JordanDC2 Not 100% exactly what you asked for..
But I find they work better than enums

https://www.typescriptlang.org/play?#code/MYewdgzgLgBADgJwKYDMCWAPGBeGByAegBMBDKEvAbgFgAoUSWAJRAFcokIcYBvOmATAAKJBFAgAuGAAMAJD0SpMAXwJxR46QBp+ggJJgAbiDTBOUuQuToMqtEZNmI2uspgkuDaDVp0vzNg4IAFEMDjAiJCJuPlpBGAA6JJZ2Th04wQB5BEiESRl5RRtVEBykPJdaNw8Yfx86KABPOCQYFKDQ8MiiADUSABtWTm4mlpAUNsDOTqQIqIBtAGskRvGYUaQ19umw2e6AXXraFFYwYCg0cBgAcxAoEAAKBCmpbZDdud6BoYgASl5lHQ6Ld7g83jNPgkDMZTJxfj4QY83lCHLC-pQgA

**Comment by JordanDC2** [comment]
@WORMSS yeah thats kind of what im having to work with currently, i just wish it was a capability of Enums since we can have computed values now but not computed keys

**Comment by Seriosus** [comment]
> @JordanDC2 Not 100% exactly what you asked for.. But I find they work better than enums
> 
> https://www.typescriptlang.org/play?#code/MYewdgzgLgBADgJwKYDMCWAPGBeGByAegBMBDKEvAbgFgAoUSWAJRAFcokIcYBvOmATAAKJBFAgAuGAAMAJD0SpMAXwJxR46QBp+ggJJgAbiDTBOUuQuToMqtEZNmI2uspgkuDaDVp0vzNg4IAFEMDjAiJCJuPlpBGAA6JJZ2Th04wQB5BEiESRl5RRtVEBykPJdaNw8Yfx86KABPOCQYFKDQ8MiiADUSABtWTm4mlpAUNsDOTqQIqIBtAGskRvGYUaQ19umw2e6AXXraFFYwYCg0cBgAcxAoEAAKBCmpbZDdud6BoYgASl5lHQ6Ld7g83jNPgkDMZTJxfj4QY83lCHLC-pQgA

Man, you saved me, thank you.
This is indeed better than using enums or at least when not using literals.

**Comment by tka85** [comment]
Sounds weird, but I'm on Typescript 5.0.2. I'm forcing VSC to use the local installed Typescript version (which it recognizes is 5.0.2 instead of VSC's 4.9.5) and the enum values still get udnerlined with red squiggly line.

```
export enum TABLES {
    foo = `${config.db.schema}.foos`,
    bar = `${config.db.schema}.foos`
}

```
Any ideas what I'm missing here? I see the [playground](https://www.typescriptlang.org/play?ts=5.0.2&ssl=1&ssc=1&pln=2&pc=1#code/MYewdgzgLgBADgJwKYDMCWAPGBeGByAegBMBDKEvAbgFgAoO0SWJMAVwFsYAlEVqJCDADedGDAAKJBFEG4ABgBIhiVJgC+BOFJlyANDAIEYAImJkSm7RGOiYASTAA3EGmACcMRcuToMGtE4ubhB6BkampOQEAc6uAja0anQM4BAgADZIAHTpIADmABQ8fAJZktIQ+sX8EFkOscEAlJRAA) link posted above by @janbiasi and it should be working for 5.0.2. But it's not.

I confirm that the project has 5.0.2 installed with `npm ls typescript`; only 5.0.2 and no other version exists in the workspace.

**Comment by Regiden** [comment]
We just tried to update our code base and we noticed a ton of errors. Turns out this change basically means you cannot treat an enum as basically "just" a number anymore? No way to optionally tell TypeScript to allow "optional" values that are basically null? 

This is somewhat weird, because you now can't have a fall back state and HAVE to define a "NONE" type. 

```
enum TEST {
    ONE = 1,
    TWO
}

const foo: TEST = 0;
```

This now is an error. Was there any reason not to allow for a fallback here?

**Comment by gabriel-calin-lazar** [comment]
how come 
we have strict enum usages when value is number, when using number literal or enum entry
but
we have strict enum usages when value is string, only when using enum entry - not when using string literal ?

would be really useful to not have this not so obvious difference

you can check some examples [here](https://www.typescriptlang.org/play?ts=5.1.0-beta#code/KYOwrgtgBAggzgOUgI2AJzgUXNA3gWACgooB5BTKAXigEYAaIkgFQHVTqoAmIgXyKIBjAPYg4AFyijg8JBFRoA+gC5YiFOiw5OtANxDREqSBnr56RSrVyFWyJ1kaM2SADpymfYQNjJ4gO7CjuZKqsG2LtA0XF4ivlABQWYKlmHJmpEO6c44rmykXkQA9EVQwAAeAA7AguLAACZlaGjCaFAm5eI+RuIAFmjApjYWacM59jQAzLpQJVDMAJ7VUADkkytQAJZw7cKSAIZwcJsA5iD7yAA2wAnCCUs3K+EZOCsChKD28ADK4mibIBOdjwTDIFE4K1oK0YxHm7AhXGhfHeczAHWqtQaTRabQ6XUIcSM0h+fwBJysJP+gOBEKhMzmi2WKwARLRmRttrsDkdTucrjdxHdxA9VpSycC3gTDJJiXBflTyRS5aTqZkaGLVbkPIVCKj0TU6o10Dj2hV8YS-IENeS0vLxWrVoj6aVGY9mVx2VsdiA9lBDsczhdrrd7kzrRLupaknbAak1DGgQ7w5E8uwdXMKhjDdjWqbOpGEv1BtalQmaTQ1itnfMRSzJp7OT7uQG+cHBaHHsnXu9PtB4ABZTblBqZAiwjw6GEseEVxEw-jeKXxWWD4f1JWrkfaGh6AsrocNOMDg-1JNwTenrUUdOlNGZg1Y425vEFxLHtcbk8OlZO2alGtMu6Dber6-q8kGApCrW75bpAkoWgkVrnieR7IWuZ4Xim+Q3mUVQPkazTPmar5FqYF6fuh25QNMf4AY86xelyfo8oG-IhsKYZobBECSsUpT3piBEmi+S49KRMHrhR3EQus1auqszL1hyIHNuBbHthxnZcZecHvEAA)

**Comment by ahejlsberg** [comment]
@gabriel-calin-lazar See my comment [here](https://github.com/microsoft/TypeScript/pull/50528#issuecomment-1341136338).

**Comment by vtarelkin** [comment]
@tka85 any ideas about it? Also have TS above 5 and it complains

**Comment by tka85** [comment]
> @tka85 any ideas about it? Also have TS above 5 and it complains

Nope. No response.

**Comment by tka85** [comment]
@vtarelkin Nope. No response.

**Comment by jakebailey** [comment]
An old PR is really not the best place to ask for help or report bugs. I would really suggest filing an issue if you want it to be seen by the right people.

**Comment by vtarelkin** [comment]
@jakebailey people are searching over the whole net and hope to find a clue here) maybe you could help us please?)) I have a TS above 5th version and it still complains 
image

**Comment by jakebailey** [comment]
Please, please, please, file an issue and fill out the template.

**Comment by nick4fake** [comment]
@jakebailey this issues comes the first google search result. I have typescript 5.1.3 and just noticed the same problem, still trying to find any relevant tickets in this repo

**Comment by RyanCavanaugh** [comment]
Please file a new issue outlining the problem you're having
