### ISSUE TITLE
Namespace defined in .d.ts is no longer accessible from node .js file

### ISSUE THREAD

**Issue by JoelEinbinder** [Microsoft/TypeScript#22969]
**TypeScript Version:**  2.8.1

**Search Terms:** refers to a UMD global, but the current file is a module. Consider adding an import instead.

**Code**

externs.d.ts
```ts
export as namespace Puppeteer;
export interface TargetInfo {
  type: string;
  targetId: string;
  title: string;
  url: string;
  attached: boolean;
}
```

target.js
```js
const fs = require('fs');
class Target {
  /**
   * @param {!Puppeteer.TargetInfo} targetInfo
   */
  constructor(targetInfo) {}
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "noEmit": true,
    "allowJs": true,
    "checkJs": true,
    "target": "es2017"
  },
  "include": [
    "."
  ]
}
```

Setup
```bash
npm init
npm install --save-dev typescript
npm install --save-dev @types/node
npx tsc -p .
```

**Expected behavior:**
Everything runs successfully

**Actual behavior:**
`Target.js(4,15): error TS2686: 'Puppeteer' refers to a UMD global, but the current file is a module. Consider adding an import instead.`

When attempting to upgrade Puppeteer to use Typescript 2.8, we ran into this issue with our externs file. This previously worked on 2.7.2. See https://github.com/GoogleChrome/puppeteer/issues/2279

The externs file method we were using did feel pretty hacky. The error message is right in that we are using something defined as a UMD global in a node module. But I don't have a better solution.

**Comment by sandersn** [comment]
Note that Typescript 2.9 will provide a better workaround in the form on import type:

```js
/** @type {import("puppeteer").Keyboard} */
var keyboard;
```

**Comment by mhegazy** [comment]
I do not think we want to show ppl these errors in jsdoc context.
it does not affect the generated code, and thus does not matter how they reach the symbol. this should only be an error for values in expression context.

**Comment by sandersn** [comment]
I should have a fix soon. It's easy to get rid of the error entirely, but I think I'll take @mhegazy's advice and only get rid of the error for type references.

**Comment by sandersn** [comment]
Fix is up at #23129
