### ISSUE TITLE
Alias type for indexing a generic object with with transform breaking change in 4.2+ (2nd issue)

### ISSUE THREAD

**Issue by iPherian** [microsoft/TypeScript#44095]
# Bug Report

### 🔎 Search Terms

index generic with alias, alias generic

### 🕗 Version & Regression Information

- This changed between versions 4.1.5 and 4.2.2
  - Still broken in 4.2.4 and nightly

### ⏯ Playground Link

[Playground link](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAaghgGwPIDMA8AVAfFAvFDAbQGsIQB7FAgXQG4BYAKCYGNyA7AZ2CgCM5O0fAG8mUKGwTkATgC4oAIgDm0iBHYKANEwC+UARI7cGzRigCu7FsACWHKEojAAYtPIBbAApuwnAHLkwADKABZwqgAmaACyMhDe5L5QEAAewOoRnFDCOlgAFGJQ7nEJvvKxqqWc2oziYD7ypBRUVQHBYZFooJCUfAIQmlAV8T6cWEwAlPIA9ABUs2KzUAkR5iwQWRDSbtJQNuxQ3Rss0jZgPAAsAHQATFcpfOY8nGvrEJl7B9cAjFcArItFlAAIJZfgsYgqciWCKDF4sN4ffZ8QIhPZUCjmKCqMAIODrQ4haCqYDmaQHI76TiCaS2DiyQG1JbwZDoVqBULhd5dcAQXr8QSDYZVLDjJlAgDuNmAIQZ4qZy1GbU5nSO-P6QpKoywhCgTV67PaXKiaqoAoGQy1iTGUGojKgSwA6iEbCw0TYsjLoB6XtAZXAeABJfTuQ7SED7JSHcgOJz6Hi8CAsODmQT6CaE6As1BoK55sUOqAANy2nDsB3hiPefAgKDigzg7AiNeTqe9zzU7k9Mfc0AQNlImZAUE4IWhCAiQN7jczI7gvcJkcGidbaa9I6THGbqXqGzL9g9UAAVqmeP3B+5G+ZEAgQEDVJxyAgi5HYIgc3mrjgpTLZ-jSYgyQpLu1LllAda7BgVyLNMb6smghoqtypp9IKlqVNqOCiLUUDTLBAg0nSBwsOYABeezAAA5FkJ7cOBMgSESEKvkcnDQThbBcDw7Ach01YiHoBiIXxJq8uqaHCtqJjiCSZIHDxRqRIQ9SJHQuhMEwlLCcaaAADIABJBEB6RNlkOSDAASoZxkZGZuR4FASDuNKaBWUEgz6lQBlBDgABkhROS53keWQvRuVgJhMHhQHzri0CpnAjisEYZ7qA5jguG4XhKrxxp5MIUAIOo8jfAADFShhcVAOiDAoRUaBMJhAA)

### 💻 Code

```ts
type ValOf<T> = T[keyof T];

const base = {
  color: "green",
} as const;

function getFromPropsNotShared<MoreProps extends {}>(
  moreProps: MoreProps,
  prop: keyof PropsNotShared<typeof base, MoreProps>
): /**
 * Produces error in typescript 4.2.x but succeeds in 4.1.5
 *
 * As background, succeeds in both if you replace the return type assertion:
 *
 * ValOf<PropsNotShared<typeof base, MoreProps>>
 *
 * with:
 *
 * PropsNotShared<typeof base, MoreProps>[ keyof PropsNotShared<typeof base, MoreProps> ]
 *
 * Which is the issue that I am trying to get at because a) the ValOf<...>
 * version succeeded before, and because it seems to me like they should
 * mean the same thing, because the second expression is just like manually
 * resolving ValOf<...> with the actual expression for T.
 */ ValOf<PropsNotShared<typeof base, MoreProps>> {
  // assertion cuz it's just for checking types.
  const notShared = {} as PropsNotShared<typeof base, MoreProps>;
  return notShared[prop];
}

type PropsNotShared<LHS extends {}, RHS extends {}> = Omit<RHS, keyof LHS> &
  Omit<LHS, keyof RHS>;

// example usage
const len = getFromPropsNotShared({ len: 10 as const }, "len");
```

### 🙁 Actual behavior

Says the line `return notShared[prop];` in `getFromPropsNotShared()` is not assignable to the annotated return type. Works if you replace it with a similar annotation manually resolving ValOf. But it worked in 4.1 and it seems to me like the two different return type expressions should mean the same (see comment).

### 🙂 Expected behavior

Would expect the line `return notShared[prop];` to succeed with the ValOf<...> return type on `getFromPropsNotShared()`.

**Comment by RyanCavanaugh** [comment]
So basically you have a higher-order operation that we happen to know doesn't introduce new values, but TS doesn't really have any way to verify that, so rejects that as a lookup since there's no way to establish the symmetry of those two types. I'm not sure why this ever worked.

Even staring at the code I can't tell what it's trying to accomplish. If you have some examples of what valid/invalid calls to getFromPropsNotShared and what the return types are supposed to be, I can probably give you a definition that works without error.

**Comment by iPherian** [comment]
> So basically you have a higher-order operation that we happen to know doesn't introduce new values, but TS doesn't really have any way to verify that, so rejects that as a lookup since there's no way to establish the symmetry of those two types.

@RyanCavanaugh Hmm `ValOf`? Yes, that makes sense. Thanks!

>  I'm not sure why this ever worked.
>
> Even staring at the code I can't tell what the sample is trying to accomplish. If you have some examples of what valid/invalid calls to getFromPropsNotShared and what the return types are supposed to be, I can probably give you a definition that works without error.

That would be very helpful!

Here's a longer example which may make more sense:

### Description

Basically the `Errors` class manages an object full of error name keys and whose values are metadata for those errors (error codes, etc). And one is able to add to the common errors or override them in the constructor, and then `getError()` in a type-safe way.

The similarity is between in the OP `type PropsNotShared` and in the below `type CustomObjectAssign`. The expressions are similar enough that they both produce errors when running them through the higher order operation `ValOf`, specifically when returning from `getFromPropsNotShared()` in the OP and `Errors.getError()` below. But I hope the following makes more sense.

### ⏯ Playground Link

[playground](https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBAaghgGwPIDMA8AVAfFAvFDAbQGsIQB7FAgXQG4BYAKCdEigFEAnT8zgJQgBjXgBM8UAcM4i0AZ2CcAlgDsA5gBoO3XlgbNGK4BE4o4g6Fx6coAbyZQowkRABcUZQFcAtgCNjegF8mJgB6ACow+zCoAEFlECgIAA8FOETtTlkoFShgAAsLDKzhZXlOD0FgXigAd0UEBCg-KDgRZzEq3ILZCE04ZREolvj8lVVaxXyu6Fk4L2gwHkhOUHc56DqGqHIAN2MlZ1q8uGAAciyCzggAOiiQphL5Jrgey14s-DtGBzqRVQhgLIAHLkYAAdUUfwBIHYynIHlUeTcXwcDicrigAEZsep7FAArjGAEWsVyKVgHpQhEhgBZfpwf5ZNJXKRiSiOci+FQQMT7arKdZZAC0OHRTIG23yxig82ArROcFu3zC90YyTAvGAjgQLyyb0yaHYKU4cH1WWSRgGeoyklEOBRUEWih2J2gAH0+fwhKI3ABhDzyTlIHwAKyEwBislkilUyjQrAg7J8LwgZs0RtSZt0wW+HPJ5UqvAAFBaTWa3Bmy0UAJS2PEOUaya4em3e6TiQQBqpeYNhyqR6OxovJ15FTSl001vQOIL6BxgDw+BCKQRQf7AfVF+vpKxA9ZuUgUKhmw3GydWWRYQgAIhbVlt0mv1Dx1bc8GQ6BPlfP7yvt89D4iE+9rbuEkS5qi0QAOLOhATK5OA0CetcUBFooWRSjKcA5Is5BLhAXjVkqqIOCq25XMAHicMoXToc2AFtiIhCenu8x0His6zqEIQtG0UCyJySFnju7zbNYuz7JC0AjtAZJwQ8ZJPJ6HzuBANRaBeRYOr867AqCEJQqAsLwoiyLbuibjYgALCSebyISM4Obk5DkHS8QACIuSIrSyGZEEcs4lmYgATLZjzAE5BJMAE1aUowIQ8ckcxgAg0ABgy8mMOFEyGbIljiMp1zrpu146QCengpC64wnCCJ5NesVQAl-F5PCCBiLIFTmDyCnklAIheT5+X4IVxUZEW15VK5-QgJ55DeSIsgNXo2X-HAmTDSJmRFQCJXKBAPI0rwEBQRA61LY1zWyK1HjtVtTRCHAAbQI290CvM2RZHCWo5BAkyXNMHJeF4ZJiYDE5bbIOZgUMGAFFAFFUTRCaffxihePU63OYDPgePUP00Yj1EIWw7K9uG1y6jGygOdEyTmGAWr5Cc2TOMowArogjpLMYHNwdkyPw3wAASADK2x7NwUmAwAMmLAvyGdbIoEMuEiBUYyqZLKFgi8WGHH4ghPT02RnMUCDkD01idK16nk5UlNRtTLSVB4iAICAQw1LwxBNncTAoB4yiVIooOdoGPahuGA7U5g63rokKQQFatgElAovwpw5iJ5ai2p1gW65nKnDrm4GDxwCTkCVR5huBnNcQEwr5QP6Ef2xGTuxnHJeV+nmfmCBuZEzR7eO4OyhaVA1zT8XCdp9XWcQLWetB8QcI1DReut927cx1327lz3EXbvXi94tmRI5ij29BlH-ad3Gcvixayd5zYaci8-Scp+-OD4EgGNgBoE-poQ87In44AAGR4gdA4QgABpAWUAwFUCftQNwiCX4pxQRIeWAB+XBosEHUCgG4J+xDpz4j0EAA)

### 💻 Code

```ts
type ValOf<T> = T[keyof T];

type ErrorRecord = Record<string, Error>;

interface Error {
  code: number;
}

/**
 * Any extra errors in the Errors constructor will be added to these, and
 * anything with the same property name will override what's here.
 */
const baseErrors = {
  widgetsNotWidgetyEnough: {
    code: 111,
  },
} as const;

/**
 * Manages a record of combined error names -> codes and other metadata.
 */
export class Errors<ExtraErrors extends ErrorRecord> {
  private _errorRecord: CustomObjectAssign<typeof baseErrors, ExtraErrors>;

  constructor(extraErrors: ExtraErrors) {
    this._errorRecord = customObjectAssign(baseErrors, extraErrors);
  }

  public getError(
    errorName: keyof Errors<ExtraErrors>["_errorRecord"]
  ): ValOf<Errors<ExtraErrors>["_errorRecord"]> {
    /**
     * Gives a type error. (is the main problem).
     */
    return this._errorRecord[errorName];
  }
}

// add some extra errors or override base ones
const errors = new Errors({
  widgetsNotWidgetyEnough: {
    code: 114 as const,
  },
  tooManyDoodads: {
    code: 112 as const,
  },
});

// example usages
const widgetsErr = errors.getError("widgetsNotWidgetyEnough"); // should succeed
const doodadsErr = errors.getError("tooManyDoodads");
const gearsErr = errors.getError("needMoreGears"); // should error because this error name is not in either the common or the extra errors

/**
 * The return type is similar to the built in return type of Object.assign,
 * except that identical properties in the RHS override the LHS instead of
 * producing never. Was made because it's closer to how Object.assign actually
 * works.
 */
function customObjectAssign<Target extends {}, Source extends {}>(
  target: Target,
  source: Source
): CustomObjectAssign<Target, Source> {
  return Object.assign({ ...target }, source) as unknown as CustomObjectAssign<
    Target,
    Source
  >;
}

type CustomObjectAssign<LHS extends {}, RHS extends {}> = Omit<RHS, keyof LHS> &
  {
    [K in keyof LHS]: K extends keyof RHS ? RHS[K] : LHS[K];
  };

```

**Comment by iPherian** [comment]
@RyanCavanaugh made the issue in OP more specific and fleshed out the types a bit more. Felt like it was different enough to open a new one: #44108

**Comment by whzx5byb** [comment]
A minimal repo:
```typescript
type PropsNotShared<LHS extends {}, RHS extends {}> = 
  & Omit<RHS, keyof LHS>
  & Omit<LHS, keyof RHS>
;

function test<T>() {
  type T1 = PropsNotShared<{x: 1}, T>;
  type T2 = PropsNotShared<{x: 1}, T>;
  type N1 = T1[keyof T1];
  type N2 = T2[keyof T2];
  var x: N1 = {} as any;
  var y: N2 = {} as any;
  x = y; // <- error here.
}
```

https://www.typescriptlang.org/play?ts=4.2.3#code/C4TwDgpgBACgTgezAZwHIOAZQBYEM4QAmAPADIASmUEAHsBAHaHJQDeAvgDRQBKl1dRszbsAfFAC8UALAAoKFABkUAPIBbAJbBifTNwDWEEAgBmUCplFyFy9VrKUDR070pXZAbjlyTAVwYAxsAaCAxQ9MjaACqiABQAlGzW4eDQUQCMkrCIKOhYeAQkrDQAXFDpXFAxXvIpkFUATFnwSGgYOPhExMVlFdzVyaD1qJlSGQDahsZmGQC6NQpD0KhNYw2TzjMN88kAbvhQpVAjWRxQuCy4DCALUPtwUCBlK6fs55fXtzRZN1AA9H8oMQALTUOCIB7YCAEAB0cnYQA

**Comment by iPherian** [comment]
> A minimal repo:
> 
> ```ts
> type PropsNotShared<LHS extends {}, RHS extends {}> = 
>   & Omit<RHS, keyof LHS>
>   & Omit<LHS, keyof RHS>
> ;
> 
> function test<T>() {
>   type T1 = PropsNotShared<{x: 1}, T>;
>   type T2 = PropsNotShared<{x: 1}, T>;
>   type N1 = T1[keyof T1];
>   type N2 = T2[keyof T2];
>   var x: N1 = {} as any;
>   var y: N2 = {} as any;
>   x = y; // <- error here.
> }
> ```

Nice!

**Comment by iPherian** [comment]
> Edit:
> According to my investigation, this is essentially cause by the use of Conditional Type.
> 
> ```ts
> function test<T>() {
>   type T3 = T & (T extends any ? {} : {});
>   type T4 = T & (T extends any ? {} : {});
>   type N3 = T3[keyof T3];
>   type N4 = T4[keyof T4];
>   var x3: N3 = {} as any;
>   var x4: N4 = {} as any;
> 
>   x3 = x4; // <- error here.
> }
> ```

hmm, you think so?
Because you can keep the conditional and it succeeds:

[playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygHgCoD4AUAlIgN4CwAUIsgJ4AOKi2AzIgLyL7aIoAeqYACZpEAQzA1EAflIBfRAC45hANyVqUeo2wAWdp258BwsROlzFytVVoNEAOVYcWAbQDWKGnGBNmAXWsNLQc9Zx13T28mHQD1RAA3UQAnRF5mJUd9EnlREXEaQITk1J0M0Itc0wLKOLT9Xh0VRAB6ZsRMAFpEMDgeJKS4FPyAW0GUADpKWSA)

```ts
function test<T>() {
  type T3 = (T extends any ? {} : {});
  type T4 = (T extends any ? {} : {});
  type N3 = T3[keyof T3];
  type N4 = T4[keyof T4];
  var x3: N3 = {} as any;
  var x4: N4 = {} as any;

  x3 = x4; // <- no error anymore.
}
```

...but have just an intersection and it fails again:

[playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABFApgZygHgCqJQD1TABM1EBvAXwBpEBVPQlEsqgPgAoBKCgWAChEyAJ4AHFImwBmRAF5JiAGT0A3AKFQxE7ABY5C5XTWCR4xADkZ86QG0A1imFxgkqQF1jGrRb3Wd9x2dJHQ91RAA3AEMAJ0R8KQAuCysKSkRIskiwYU8ImLidJPNfVPTM7OMw+P18HRVEAHoGxEwAWjxo6LhYgAsUaJQBSiA)

```ts
function test<T extends {}, U extends {}>() {
  type T3 = T & U;
  type T4 = T & U;
  type N3 = T3[keyof T3];
  type N4 = T4[keyof T4];
  var x3: N3 = {} as any;
  var x4: N4 = {} as any;

  x3 = x4; // <- error here
}
```

And there's an intersection in the OP too, perhaps it's caused by intersections.

**Comment by whzx5byb** [comment]
> And there's an intersection in the OP too, perhaps it's caused by intersections.

It seems that this is caused by https://github.com/microsoft/TypeScript/pull/30769.

We know `keyof (A & B)` is `(keyof A) | (keyof B)`, and `T[M | N]` is `T[M] | T[N]`, so `T3[keyof T3]` is resolved to `T3[keyof T] | T3[keyof U]` as expected, when it is in a "read position".

However, when `T3[keyof T3]` appears in the "write position", it uses an intersection instead of a union, so `T3[keyof T3]` is resolved to `T3[keyof T] & T3[keyof U]`, which leads to the error.

**Comment by iPherian** [comment]
@whzx5byb Thanks for tracking that down! It's very informative.

Given that, and the more I think about this, I confess that I may have made a mistake. So that PR is saying that when T[K] is on the target side of a type relationship it's the intersection of the types of the values of T. But you know, that makes sense. After all, if all you know about K is that it is any of the keys of T, and any of these T[K] have incompatible types, then it shouldn't be possible to assign to them, right? So in that case an intersection makes never which can't be assigned to.

like in here:

```ts
type PropsNotShared<LHS extends {}, RHS extends {}> = 
  & Omit<RHS, keyof LHS>
  & Omit<LHS, keyof RHS>
;

function test<T>() {
  type T1 = PropsNotShared<{x: 1}, T>;
  type T2 = PropsNotShared<{x: 1}, T>;
  type N1 = T1[keyof T1];
  type N2 = T2[keyof T2];
  var x: N1 = {} as any;
  var y: N2 = {} as any;
  x = y; // <- error here.
}
```

All typescript knows about x and y is that they are *some* value of T1 (or T2 doesn't matter). But all of those values are not neccessarily assignable to each other, hence the error.

In fact, i'm kind've swinging the opposite direction now, and think that it should fail more than it does.

Consider this example which should fail but doesn't.

[playground](https://www.typescriptlang.org/play?ts=4.2.3#code/GYVwdgxgLglg9mABFApgZygHgCoD4AUAlIgN4CwAUIogG4CGATogB4Bci2A2gNYoCecYBwC6iALykAvojpoZYPgG5K1ekz7suvAUOyiJJabPlKVLcYiWIA9NcSYAtIjQALOCAA2AE0QoGDOCYXPxQAGkQAIxQIOhA0FEQwOCgZDw9aOg8QdERBDhkGBLBo9DRGGA8+GTQ0GABzMDoIjwSoOF86CBdcqGCGSkkgA)

```ts
function test<T>() {
  var x: T[keyof T] = {} as any;
  var y: T[keyof T] = {} as any;
  x = y; // <- should error here, because not all values of T are necessarily assignable to each other
}
```

The nice thing about PropsNotShared was that it was a longish expression which could be deconstructed by typescript, and so if you were assigning an index of it to another index of it, the target type i.e. intersection of all possible values actually looked to be a different expression than the source type i.e. the union of all possible values. But above, no information is known about `T[keyof T]` other than that T is a type and it's being indexed by one of it's keys, so perhaps the intersection of all possible values doesn't look any different than their union, and the assignment happens.

**Comment by iPherian** [comment]
@whzx5byb Thanks for tracking that down! It's very informative.

Given that, and the more I think about this, I confess that I may have made a mistake. So that PR is saying that when T[K] is on the target side of a type relationship it's the intersection of the types of the values of T. But you know, that makes sense. After all, if all you know about K is that it is any of the keys of T, and any of these T[K] have incompatible types, then it shouldn't be possible to assign to them, right? So in that case an intersection makes never which can't be assigned to.

like in here:

```ts
type PropsNotShared<LHS extends {}, RHS extends {}> = 
  & Omit<RHS, keyof LHS>
  & Omit<LHS, keyof RHS>
;

function test<T>() {
  type T1 = PropsNotShared<{x: 1}, T>;
  type T2 = PropsNotShared<{x: 1}, T>;
  type N1 = T1[keyof T1];
  type N2 = T2[keyof T2];
  var x: N1 = {} as any;
  var y: N2 = {} as any;
  x = y; // <- error here.
}
```

All typescript knows about x and y is that they are *some* value of T1 (or T2 doesn't matter). But all of those values are not neccessarily assignable to each other, hence the error.

In fact, i'm kind've swinging the opposite direction now, and think that it should fail more than it does.

Consider this example which should fail but doesn't.

[playground](https://www.typescriptlang.org/play?ts=4.2.3#code/GYVwdgxgLglg9mABFApgZygHgCoD4AUAlIgN4CwAUIogG4CGATogB4Bci2A2gNYoCecYBwC6iALykAvojpoZYPgG5K1ekz7suvAUOyiJJabPlKVLcYiWIA9NcSYAtIjQALOCAA2AE0QoGDOCYXPxQAGkQAIxQIOhA0FEQwOCgZDw9aOg8QdERBDhkGBLBo9DRGGA8+GTQ0GABzMDoIjwSoOF86CBdcqGCGSkkgA)

```ts
function test<T>() {
  var x: T[keyof T] = {} as any;
  var y: T[keyof T] = {} as any;
  x = y; // <- should error here, because not all values of T are necessarily assignable to each other
}
```

The nice thing about PropsNotShared was that it was a longish expression which could be deconstructed by typescript, and so if you were assigning an index of it to another index of it, the target type i.e. intersection of all possible values actually looked to be a different expression than the source type i.e. the union of all possible values. But above, no information is known about `T[keyof T]` other than that T is a type and it's being indexed by one of it's keys, so perhaps the intersection of all possible values doesn't look any different than their union, and the assignment happens.

**Comment by iPherian** [comment]
I'd be willing to close this if @whzx5byb doesn't have any more issues.
