### ISSUE TITLE
Possible 2.1 regression: Type 'void[]' is not assignable to type 'void'.

### ISSUE THREAD

**Issue by fictitious** [Microsoft/TypeScript#12353]
**TypeScript Version:**  2.1.1  (npm i typescript@2.1)

**Code**

```ts

function f(): Promise<void>[] {

    let p: Promise<void>[] = [];

    p.push(Promise.all(f()));

    return p;
}


```

**Expected behavior:** I believe this should compile without errors, as it does in 2.0

**Actual behavior:**

tsc --lib es6 p.ts
p.ts(6,12): error TS2345: Argument of type 'Promise<void[]>' is not assignable to parameter of type 'Promise<void>'.
  Type 'void[]' is not assignable to type 'void'.

**Comment by wallverb** [comment]
Isn't it more like 2.1 improvement ?

```ts
# TS 2.0
let b: Promise<void>
let b2: Promise<void[]>
b = b2 // <- OK
```

```ts
# TS latest
let b: Promise<void>
let b2: Promise<void[]>
b = b2 // <- Proper error: void[] not assignable to void
```

**Comment by fictitious** [comment]
No it's not. Anything is assignable to void because most of the time, it OK to discard the value.

**Comment by wallverb** [comment]
Ok, I will let others answer it then.

I was just making an observation that this works in TS2.0 but throws error `string[] is not assignable to string` in latest
```ts
let a: Promise<string>
let b: Promise<string[]> = Promise.resolve(['test'])
a=b
```
and that you can't assign `void[] to void` even in TS2.0:
```ts
let c: void = undefined;
let d: void[] = [undefined];
c = d // Error: void[] is not assignable to []
```

**Comment by fictitious** [comment]
Ok, I see that `void` was deliberately made incompatible with any other type in typescript. And stricter check in 2.1 for promises is an improvement for any type, except `void`.

So the question essentially becomes: is there any way to express that any promise is assignable to `Promise<void>`? After all, this code is valid:

```
let pv: Promise<void>;
let pn: Promise<number>;

pv.then(function() {
    // ok
});

pn.then(function() {
    // also ok - not using the number here
});

```

shouldn't this be valid too?

     pv = pn; // error. why ?

**Comment by fictitious** [comment]
Answer: `Promise<void>` was the wrong choice, `Promise<{}>` works for me.

Sorry for the noise.
