### PR TITLE
More prolific literal types

### LINKED ISSUE #16457: Refine unions in contextual typing
Source issue #16450 and others (TODO: find them)

This code should work, but doesn't:
```ts
interface X {
    type: 'x';
    value: string;
}

interface Y {
    type: 'y';
    value: 'none' | 'done';
}

function foo(bar: X | Y) { }

foo({
    type: 'y',
    value: 'done',
});
```

Similar example:
```ts
interface X {
    type1: 'x';
    value: string;
}

interface Y {
    type2: 'y';
    value: 'none' | 'done';
}

function foo(bar: X | Y) { }

foo({
    type2: 'y',
    value: 'done',
});
```

We can, in principle, make this work by discarding `X` from the union.

In the first example, this can be done (somehow) by using the discriminating union from the object literal.

In the second example, this can be done by noting that we have a fresh object literal type (meaning there are known to be no additional properties) and a missing `type1` property.

### LINKED ISSUE #19632: String literal generic not always inferred when part of union in nested object
**TypeScript Version:**  Version 2.7.0-dev.20171031

**Code**

```ts
declare function direct<A extends string>(a: A | A[]): Record<A, string>
declare function nested<A extends string>(a: { fields: A }): Record<A, string>
declare function nestedUnion<A extends string>(a: { fields: A | A[] }): Record<A, string>

const directUnionSingle = direct("z")
const directUnionArray = direct(["z", "y"])
const nestedSingle = nested({fields: "z"})
const nestedUnionSingle = nestedUnion({fields: "z"})
const nestedUnionArray = nestedUnion({fields: ["z", "y"]})

declare function hasZField(arg: { z: string }): void

hasZField(directUnionSingle) // ok
hasZField(directUnionArray) // ok
hasZField(nestedSingle) // ok
hasZField(nestedUnionSingle) // error TS2345: Argument of type 'Record<string, string>' is not assignable to parameter of type '{ z: string; }'
hasZField(nestedUnionArray) // ok

```

**Expected behavior:**
All 5 calls to `hasZField` compile without errors

**Actual behavior:**
One call does not compile because it infers `A` to be `string` instead of `"z"` 

Not a big deal just a quirk I came across and assume is a bug.

### LINKED ISSUE #19837: Fails to get contextual type for string literal in array
**TypeScript Version:**  2.7.0-dev.20171108

**Code**

```ts
const x: 'a' | 'a'[] = ['a'];
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(1,7): error TS2322: Type 'string[]' is not assignable to type '"a" | "a"[]'.
  Type 'string[]' is not assignable to type '"a"[]'.
    Type 'string' is not assignable to type '"a"'.
```

Was broken by #19733 -- verified by testing with its merge commit and with the previous commit. @weswigham 
Detected by running DefinitelyTyped tests.

### PR DESCRIPTION
**Pull request by weswigham**
This is an iteration on #19322.

Building on what @ahejlsberg suggested in reviewing #19322, this fixes #16457 by, rather than doing any special-casing of contextual types, causing us to infer literals so long as they are domain-appropriate for a given position. This means that if a number type is contextually typed by a number type, then we retain a literal, and the same each for string and boolean literals.

This necessitated fixing the `comparable` relationship to be deeply bidirectional (instead of just bidirectional at the top level); as casts between potentially compatible object types would fail thanks to the extra literal types without the deep bidirectionality (this was visible within our own codebase).

Most of the baseline diffs are just new literal types materializing before they are assigned and disappear, however as mentioned in [this comment](https://github.com/Microsoft/TypeScript/pull/19322#issuecomment-340127904), there are some ramifications where what was previously OK is now an error due to the stricter inference. I think could revert to the old behavior (or similar to it) for type parameters; however this could be an improvement (and is certainly more consistent). Perf-wise, I actually don't see any difference; these types were always there before, we just widened them, whereas now we widen them a step later under _most_ circumstances.

By request, fixes #19632. Also fixes #19837.

### CODE REVIEW

**Comment by mhegazy** [comment]
Apart form the test build change, do you see any breaks in the RWC baselines?

**Comment by weswigham** [comment]
@mhegazy Two fewer errors (one each in two projects) due to the more permissive comparable relationship (desirable - the casts should likely have been allowed), and a bunch of altered error messages which now contain literals, but no new breaks.

**Comment by weswigham** [comment]
@ahejlsberg I've incorporated the changes you suggested in person.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18434,24 +18440,28 @@ namespace ts {
...
+
+        function shouldUseLiteralType(declaration: VariableLikeDeclaration) {
             return getCombinedNodeFlags(declaration) & NodeFlags.Const ||
                 getCombinedModifierFlags(declaration) & ModifierFlags.Readonly && !isParameterPropertyDeclaration(declaration) ||
-                isTypeAssertion(declaration.initializer) ? type : getWidenedLiteralType(type);
+                (declaration.initializer && isTypeAssertion(declaration.initializer));
         }
 
-        function isLiteralContextualType(contextualType: Type) {
+        function isLiteralContextualType(contextualType: Type, candidateLiteral: Type): boolean {
```
Comment (sandersn) [inline src/compiler/checker.ts]: Consider flipping the parameters and changing the name to canBeContextuallyTypedAsLiteral (or something similar; probably the parameter names would need to change too.)

File: tests/baselines/reference/arrayLiteralExpressionContextualTyping.errors.txt [hunk 2]
```diff
@@ -1,8 +1,8 @@
-tests/cases/conformance/expressions/contextualTyping/arrayLiteralExpressionContextualTyping.ts(8,5): error TS2322: Type '[number, number, number, string]' is not assignable to type '[number, number, number]'.
-  Types of property 'pop' are incompatible.
-    Type '() => string | number' is not assignable to type '() => number'.
-      Type 'string | number' is not assignable to type 'number'.
-        Type 'string' is not assignable to type 'number'.
+tests/cases/conformance/expressions/contextualTyping/arrayLiteralExpressionContextualTyping.ts(8,5): error TS2322: Type '[1, 2, 3, string]' is not assignable to type '[number, number, number]'.
```
Comment (sandersn) [inline tests/baselines/reference/arrayLiteralExpressionContextualTyping.errors.txt]: hm, it would be nicer if this change didn't happen.

Comment (weswigham) [reply tests/baselines/reference/arrayLiteralExpressionContextualTyping.errors.txt]: Why? `1`, `2`, and `3` are verbatim what was written and are all contextually typed by `number`. It's pretty reasonable, IMO.

Comment (sandersn) [reply tests/baselines/reference/arrayLiteralExpressionContextualTyping.errors.txt]: People expect to see types in a type error, and don't think of `1` as a type. It's not the end of the world; it remains pretty clear because this only happens with contextual typing when the value is sitting right there in plain sight.

File: src/compiler/checker.ts (hunk 1 above)
Comment (weswigham) [reply src/compiler/checker.ts]: @rbuckton 's dynamic names PR already includes both of those things, actually.

**Comment by ahejlsberg** [comment]
I think there is some more fundamental thinking we need to do around the comparable relationship before this is ready to go.

The comparable relationship should hold if some value exists that belongs to both types. For object types I think this means we should consider them comparable unless we can prove they're disjoint. I'm not sure that's what we currently do, even with this PR. For example, when a member is present in one object type but not the other, we should consider it a match (because we can't prove that it isn't).

Also, the relationship should be commutative (bidirectional), which it isn't, even with the changes in this PR (e.g. `isTypeComparableTo` is unidirectional for primitives at the top level).

**Comment by weswigham** [comment]
@ahejlsberg 
> For object types I think this means we should consider them comparable unless we can prove they're disjoint

Any given type variables `T` and `U` cannot be proven to be disjoint, so they would be comparable under such a scheme. However, we have a lot of people that assume that we save you from going `if (T === U)` right now.

Maybe its better to think of this in terms of troubleshooting this specific issue with the comparable relationship:
```ts
declare enum Strings { 
  A = "a",
  B = "b"
}

declare let a: { y: 1 | 2, z: "b" | "c" };
declare let b: { y: number, z: Strings.A | Strings.B };

a = b as typeof a;
b = a as typeof b;
```
Those casts fail - even though `{ y: 1, z: "b" }` is assignable to both types - even though each individual member type is comparable:
```ts
declare let az: "b" | "c";
declare let bz: Strings.A | Strings.B;

az = bz as typeof az; // succeeds on Strings.A | Strings.B -> "b | "c", fails on "b" | "c" -> Strings.A | Strings.B  overall success
bz = az as typeof bz;

declare let ay: 1 | 2;
declare let by: number;

ay = by as typeof ay; // fails number -> 1 | 2, succeeds on 1 | 2 -> number, overall success
by = ay as typeof by;
```
(all of those casts work).

`comparableRelation` is implemented identically to `assignableRelation` except:
* No excess property checks on fresh types
* Mapped types' modifiers are always comparable
* Generics are erased when comparing singleton signatures, instead of compared strictly
* When `source` is a union, only `some` element of that union needs to be comparable, rather than `each` element.
* Optional properties in both types can have incompatable types (in strict mode, this is also handled by the `each` => `some` union flip, since all optional properties have `undefined` in their domain)

Ergo, `{ y: 1 | 2, z: "b" | "c" }` would be comparable to `{ y: number, z: Strings.A | Strings.B }` if both directions were checked both at the top level _and_ at each member, instead of just at the top.

Right now what we really have is a `partiallyComparable` relationship that we've branded as `comparable`, but then check both directions of at many use sites (except narrowing where we only use one direction in a few places, and is potentially an oversight since in others within narrowing we use both directions) - in `checkAssertionWorker`, `checkBinaryLikeExpression`, and `checkSwitchStatement` (all of its non-narrowing uses) we always look at both directions. Our internal usages arguably _expect_ a deeply comparable behavior - nobody would expect the example cast at the top of this comment to fail.

**Comment by weswigham** [comment]
Superseded by #19966
