### ISSUE TITLE
Cannot extend tsconfig.json from another monorepo package.

### ISSUE THREAD

**Issue by josefie** [microsoft/TypeScript#56847]
### 🔎 Search Terms

TS6053: File not found.
extend tsconfig.json
monorepo
turbo
package.json main tsconfig.json

### 🕗 Version & Regression Information

- This changed between versions 5.2.2 and 5.3.2

### 💻 Code

package.json of the base package:
```json
{
  "name": "@betterplace/ts-config-base",
  "main": "tsconfig.json",
  "dependencies": {
    "typescript": "5.3.2"
  }
}
```

package.json of the importing package:
```json
{
  "name": "@betterplace/app",
  "devDependencies": {
    "@betterplace/ts-config-base": "workspace:*"
  }
}
```

tsconfig.json of the importing package:
```json
{
  "extends": "@betterplace/ts-config-base"
}
```

### 🙁 Actual behavior

I'm trying to [extend](https://www.typescriptlang.org/tsconfig#extends) a tsconfig.json with a base config that is imported from another package in a monorepo. This worked until after updating typescript from 5.2.2 to 5.3.2. Now the tsconfig.json is not found anymore.

This is the error message:
```
⨯ Unable to compile TypeScript:
error TS6053: File '@betterplace/ts-config-base' not found.
```

This is the basic setup:

**@betterplace/ts-config-base**
- package.json - includes typescript as dependency and defines tsconfig.json as its main entrypoint
- tsconfig.json - base config

**@betterplace/app**
- package.json - includes `@betterplace/ts-config-base` package as a dependency
- tsconfig.json - extends the tsconfig from `@betterplace/ts-config-base`

### 🙂 Expected behavior

`@betterplace/app`'s tsconfig.json should extend the tsconfig.json from `@betterplace/ts-config-base`.

### Additional information about the issue

If I directly extend the tsconfig using the relative path to the file, it works:

```
"extends": "../ts-config-base/tsconfig.json"
```

**Comment by andrewbranch** [comment]
tsconfig lookups read from the `"tsconfig"` package.json field, not `"main"`

```diff
{
  "name": "@betterplace/ts-config-base",
- "main": "tsconfig.json",
+ "tsconfig": "tsconfig.json", 
  "dependencies": {
    "typescript": "5.3.2"
  }
}
```

**Comment by josefie** [comment]
> tsconfig lookups read from the `"tsconfig"` package.json field, not `"main"`

@andrewbranch Thank you for the hint! Unfortunately that doesn't fix it. The problem is in the other package, the one that _uses_ the tsconfig. I am just adding it as `"main"` here, because it is the main (and only) file that is exported from this simple config package.

**Comment by andrewbranch** [comment]
I understand. `main` cannot be used for this purpose. The other package that uses the tsconfig will not look at `main` as part of its lookup.

**Comment by josefie** [comment]
It did work in previous versions, though. Did anything change in that regards and is there any way for me to make this work again?

**Comment by andrewbranch** [comment]
I’m not able to reproduce this working in 5.1 or 5.2. I didn’t try anything earlier. If it was working with `main` in a recent version, it may have been an accident, but we would probably want to preserve the behavior for backward compatibility. But as far as I can see in the code or in my attempts to repro, it has never worked with `main`, and there would be no reason to change it now if that’s the case. Can you provide a working reproduction?

**Comment by josefie** [comment]
FYI this was an [issue in ts-node](https://github.com/TypeStrong/ts-node/issues/2076). Upgrading ts-node from v10.9.1 to [v10.9.2](https://github.com/TypeStrong/ts-node/releases/tag/v10.9.2) solved it. Thanks for your help!
