### ISSUE TITLE
TypedArray.prototype.map() should have a 1-argument overload

### ISSUE THREAD

**Issue by michalburger1** [Microsoft/TypeScript#16521]
**TypeScript Version:**  2.4.0

**Code**

```ts
function foo(array: Uint8Array) {
  return array.map(x => x + 1);
}
```

**Expected behavior:**
Should pass all type checks.

**Actual behavior:**
```
error TS2554: Expected 2 arguments, but got 1.
```

**Comment by michalburger1** [comment]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/map.

As far as I can tell this was broken in https://github.com/Microsoft/TypeScript/commit/a76b4b1f28ec4c6af5aaaca092116691af89962e. Cc @mhegazy.

**Comment by mhegazy** [comment]
Fix should be in `typescript@next` tomorrow, and in `typescript@2.4.1`. sorry for the trouble.

**Comment by michalburger1** [comment]
Thanks for the quick fix!
