### PR TITLE
Remove location of other declaration from "Subsequent x declarations must have same type" errors

### LINKED ISSUE #20178: Bad subsequent declaration error
The current declaration mismatch error looks like:

```sh
error TS2403: Subsequent variable declarations must have the same type.  Variable 'items' has type 'DataTransferItemList' at built/local/lib.d.ts 6521:13, but here has type 'DataTransferItem[]'.
```
The error was introduced by https://github.com/Microsoft/TypeScript/pull/19356. I do not think this is the correct solution here. the error as it stands is hard to read, and does not lend itself to navigation..

moreover, it makes our baselines very noisy. 

I think the correct solution here is to do revert the changes in https://github.com/Microsoft/TypeScript/pull/19356 and look into 
 https://github.com/Microsoft/TypeScript/issues/10489 instead.

### PR DESCRIPTION
**Pull request by andy-ms**
Fixes #20178

### CODE REVIEW

**Comment by mhegazy** [comment]
RWC tests will need an update after this is merged.
