### PR TITLE
Adds 'Awaited' type alias and updates to Promise.all/race/allSettled/any

### LINKED ISSUE #22469: Suggestion: Allow array of > 10 values in argument of Promise.all() and Promise.race()
Currently, Promise.all() and Promise.race() both have signatures like this:
```typescript
all<T1>(values: [T1 | PromiseLike<T1>]): Promise<[T1]>;
// ...
all<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(values: [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>, T4 | PromiseLike <T4>, T5 | PromiseLike<T5>, T6 | PromiseLike<T6>, T7 | PromiseLike<T7>, T8 | PromiseLike<T8>, T9 | PromiseLike<T9>, T10 | PromiseLike<T10>]): Promise<[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]>;
```
While this is suitable in most cases, occasionally there is a need (or preference) to wait on the retrieval of several (10+) dependencies and then access them all within a single block.

Workarounds for Promise.all() certainly exist (i.e. splitting into multiple Promise.all() calls) - but code can become unnecessarily complex. Workarounds for Promise.race() are not as easy.

Since actual implementations of Promise.all() and Promise.race() are boundless, it would be helpful if  lib.es2015.promise.d.ts reflected a wider range of plausible use cases.

**Proposed solution:**
Add overloads to lib.es2015.promise.d.ts - using the pattern it already uses today - to support ~20 items instead of ~10.

### LINKED ISSUE #27711: Promise<Promise<T>> cannot exist in JS
**TypeScript Version:**  Version 3.2.0-dev.20181011

**Search Terms:**
is:open label:Bug promise 
label:Bug wrapped promise
label:Bug wrapped nested 

**Code**

```ts
const p1 = new Promise<Promise<Number>>((resolveOuter) => {
    const innerPromise = new Promise<Number>((resolveInner) => {
        console.log('Resolving inner promise')
        resolveInner(1)
    })

    console.log('Resolving outer promise')
    resolveOuter(innerPromise)
})

p1.then((p2: Promise<Number>) => {
    p2.then((num) => 
        console.log('the number is: ', num)
    )
})
```

**Expected behavior:**
Compilation should fail, because `p1` is actually a `Promise<number>` due to promise unwrapping.
**Actual behavior:**
Compilation should fail, requiring code which looks like:

```

const p1 = new Promise<Number>((resolveOuter) => {
    const innerPromise = new Promise<Number>((resolveInner) => {
        console.log('Resolving inner promise')
        resolveInner(1)
    })

    console.log('Resolving outer promise')
    resolveOuter(innerPromise)
})

p1.then((p2: Number) => {
    console.log('the number is: ', p2)
})
```

**Playground Link:**  
[Runtime error](http://www.typescriptlang.org/play/#src=const%20p1%20%3D%20new%20Promise%3CPromise%3CNumber%3E%3E((resolveOuter)%20%3D%3E%20%7B%0D%0A%20%20%20%20const%20innerPromise%20%3D%20new%20Promise%3CNumber%3E((resolveInner)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Resolving%20inner%20promise')%0D%0A%20%20%20%20%20%20%20%20resolveInner(1)%0D%0A%20%20%20%20%7D)%0D%0A%0D%0A%20%20%20%20console.log('Resolving%20outer%20promise')%0D%0A%20%20%20%20resolveOuter(innerPromise)%0D%0A%7D)%0D%0A%0D%0Ap1.then((p2%3A%20Promise%3CNumber%3E)%20%3D%3E%20%7B%0D%0A%20%20%20%20p2.then((num)%20%3D%3E%20%0D%0A%20%20%20%20%20%20%20%20console.log('the%20number%20is%3A%20'%2C%20num)%0D%0A%20%20%20%20)%0D%0A%7D)%0D%0A)
[No runtime error](http://www.typescriptlang.org/play/#src=const%20p1%20%3D%20new%20Promise%3CNumber%3E((resolveOuter)%20%3D%3E%20%7B%0D%0A%20%20%20%20const%20innerPromise%20%3D%20new%20Promise%3CNumber%3E((resolveInner)%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Resolving%20inner%20promise')%0D%0A%20%20%20%20%20%20%20%20resolveInner(1)%0D%0A%20%20%20%20%7D)%0D%0A%0D%0A%20%20%20%20console.log('Resolving%20outer%20promise')%0D%0A%20%20%20%20resolveOuter(innerPromise)%0D%0A%7D)%0D%0A%0D%0Ap1.then((num%3A%20Number)%20%3D%3E%20%7B%0D%0A%20%20%20%20console.log('the%20number%20is%3A%20'%2C%20num)%0D%0A%7D)%0D%0A)

**Related Issues:** 
Didn't find related issue

### LINKED ISSUE #28427: when has optional elements in tuple types, Promise.all has error
**TypeScript Version:**  3.1.3

**Search Terms:**
Promise.all, optional elements in tuple types

**Code**
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

const arr: [Promise<number>, Promise<string>?] = [
  Promise.resolve(1)
];

arr[1] = Promise.resolve('1');

Promise.all(arr);    // Error

// or

const arr2: Array<Promise<number> | Promise<string>> = [Promise.resolve(1)];
arr2.push(Promise.resolve('1'));

Promise.all(arr2);   // Error
```

**Expected behavior:**

`Promise.all(arr)` should be correct 

**Actual behavior:**

### LINKED ISSUE #30390: 3.4 regression for type argument inference
Found trying to compile VS Code at https://github.com/Microsoft/vscode/blob/1ce2b64abb08ed7998a5a6697ba0248a51934605/src/vs/workbench/services/textfile/common/textFileService.ts#L294-L338

Isolated repro:

```ts
function blah(): Promise<{ success: boolean }> {
    return Promise.resolve(100).then(() => {
        if (Math.random()) {
            return {
                success: true
            }
        }
        return Promise.resolve({ success: false })
    })
}
```

### LINKED ISSUE #31722: [3.5.1] Iterable is missing in lib.es2015.promise.d.ts
**TypeScript Version:**  
* 3.5.1
* 3.6.0-dev.20190601

**Search Terms:** async, await, polyfill, csproj, TypeScriptLib 

**Code**

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "none",
    "lib": ["dom", "es5", "es2015.promise"],
    "strict": true,
  }
}
```

a.ts
```
// empty
```

**Expected behavior:**
```
> npx typescript@3.4.5
// ok
```

**Actual behavior:**
```
> npx typescript@3.5.1
../path/typescript/lib/lib.es2015.promise.d.ts:129:21 - error TS2304: Cannot find name 'Iterable'.

129     race<T>(values: Iterable<T>): Promise<T extends PromiseLike<infer U> ? U : T>;
                        ~~~~~~~~


Found 1 error.
```

**Playground Link:** None

**Related Issues:** Not found.

**Workaround:**
Add "es2015.iterable" to lib

### LINKED ISSUE #33559: new readonly modifiers on Promise.all break lyricist in DT
Broken by #33057 

1. clone dt
2. cd ~/dt/types/lyricist
3. tsl
4. error on `const songsByArtist: SongByArtist[] = results[5];

```ts
Promise
    .all([
        lyricist.album(1, { fetchTracklist: true, textFormat: LyricistTextFormat.PLAIN }),
        lyricist.artist(1, { textFormat: LyricistTextFormat.PLAIN }),
        lyricist.artistByName('any_artist', { textFormat: LyricistTextFormat.PLAIN }),
        lyricist.search('any_song'),
        lyricist.song(1, { fetchLyrics: true, textFormat: LyricistTextFormat.PLAIN }),
        lyricist.songsByArtist(1, { page: 1, perPage: 10, sort: 'asc' }),
    ])
    .then((results) => {
        const album: Album = results[0];
        const artist: Artist = results[1];
        const artistByName: Artist = results[2];
        const searchResult: SearchResult[] = results[3];
        const song: Song = results[4];
        const songsByArtist: SongByArtist[] = results[5];

        console.log('album', album.name);
        console.log('artist', artist.name);
        console.log('artistByName', artistByName.name);
        console.log('searchResult length', searchResult.length);
        console.log('song', song.title);
        console.log('songsByArtist length', songsByArtist.length);
    });
```

**Expected behavior:**
No error, and `results[5]: SongByArtist[]`

**Actual behavior:**
Error, and `results[5]: SearchResult[]`

The two types are VERY similar, although I'm not sure that's relevant. My guess is that it's a very subtle inference problem.

### LINKED ISSUE #33562: tsc 3.6.3: `Promise.all` breaks with some union type
**TypeScript Version:**  3.6.3

**Search Terms:** promise all

**Code**

```ts
type MaybePromise<T> = T | Promise<T> | PromiseLike<T>

function MaybePromise<T>(value: T): MaybePromise<T> {
    return Promise.resolve(value)
}

async function main() {
    let aaa: number
    let bbb: string
    [
        aaa,
        bbb,
    ] = await Promise.all([
        MaybePromise(1),
        MaybePromise('2'),
        MaybePromise(true),
    ])
}
```

tsconfig:

```json
{
  "compilerOptions": {
    "strict": true,
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "es6"
    ]
  }

```

**Expected behavior:**

Code should compile without errors.

**Actual behavior:**

Error:

```
test.ts:11:9 - error TS2322: Type 'number | Promise<1>' is not assignable to type 'number'.
  Type 'Promise<1>' is not assignable to type 'number'.
test.ts:12:9 - error TS2322: Type 'string | Promise<"2">' is not assignable to type 'string'.
  Type 'Promise<"2">' is not assignable to type 'string'.
```

Code compiles well with 3.5.3, but not 3.6.3 nor 3.7.0-dev.20190922.

**Playground Link:** 

Weirdly enough, on the playground the return value of `Promise.all` is not a tuple but a list.

https://www.typescriptlang.org/play/#code/C4TwDgpgBAsghiARhACgJwPYFsCWBnCAHgBUA+KAXimKgB8p1t8iy6HNcCAZHAaxdIAoQQDMArgDsAxsBwYJsBMkacBACgBucADZiIALmoBKQ-CSoOzEuQDegqA6hoIwMWgUrmAOmd4M2jQhNHT0jQQBfYTg8EGkocWlZeSgsOBwJNSMoO0cobRcoOCLDCTEsZDR7R3zgKER6wzxgNHSAcyqHAG0O3MKigBoe3PrEQdyAXUpCgHc02s8CLx1tNW7exzNlSwI1AEYjMfXFcwWggHIAJjODoY2lCyYd5tDDh3GwyKA

**Related Issues:** 

- ~~Maybe related? https://github.com/microsoft/TypeScript/issues/33559~~

### LINKED ISSUE #33752: 3.7-beta regression: Promise.all wrongly adds `undefined` type
**TypeScript Version:**  3.7.0-beta

**Search Terms:**

promise all

**Code**

```ts
interface A {
  a: string
}
interface B {
  b: string
}
async function main(): Promise<A> {
  const [a, b] = await Promise.all([
    Promise.resolve({a: "a"} as A),
    Promise.resolve({b: "b"} as B | undefined), // <- the `| undefined` here is the problem
  ]);
  return a; // <- a has type `A | undefined`, but should be `A`
}
```

**Expected behavior:**

This is a regression from 3.6.3, where the return tuple of `Promise.all` is correctly inferred.

**Actual behavior:**

A `| undefined` bound of a different tuple member also adds a `| undefined` bound on a different unrelated return value of `Promise.all`.

**Playground Link:** 

https://www.typescriptlang.org/play/?ts=3.7-Beta#code/JYOwLgpgTgZghgYwgAgILIN4ChnLgLmQGcwpQBzLAXy1ElkRQCFMdkAjQkskSmuIgE8QCZDACuIsMAD2IZAFs4oABQBKQgAUoMhcCIQAPKgB8rXAjklkAbTgAaDgF1kAXjwB3ZWGTbd+iAA6OAAbEJUbNlw-PQNAqAgiGRCANwgVDAJkACI4bKo8IjQ1eyjfHVighKTU9IxOHPZ8wuQWAB9kSQATCBhQCC6S5AB6YeRDAFpkMAALFAADDu7e-q755DmE5H1pueQABx12EIgFNic1AG42BLBxKHk4S5GxybwNgWnBfYX0JZAen0QAN5o52OIfEQZjJxCEuhxfvNqEA

**Related Issues:** 

Maybe https://github.com/microsoft/TypeScript/pull/33707 ?

### LINKED ISSUE #34924: A second argument in Promise.all([...]) that returns a Record breaks the return signature
**TypeScript Version:** 

3.7.2

**Search Terms:**

Promise.all, Record

**Code**

```typescript
interface MoviesResponse {
    movies: [];
}

type CharactersResponse = Record<number, any>;

const getMovies = async (): Promise<MoviesResponse> => ({
    movies: [],
})

const getCharacters = async (): Promise<CharactersResponse> => ({
});

(async () => {
    const [{ movies }, characters] = await Promise.all([getMovies(), getCharacters()]);
    console.log(movies, characters);
})();
```

**Expected behavior:**

The first variable in the deconstructed array should be correctly typed as `MoviesResponse`, rather than `CharactersResponse`. This worked in 3.6.4.

**Actual behavior:**

Both variables in the deconstructed array are inferred to be `CharactersResponse`. So when I try to deconstruct the first argument doing `{ movies }`, it's an invalid destructuring.

Interestingly, if we update `CharactersResponse` to not be a map type, the problem goes away, e.g:

```
interface CharactersResponse {
    characters: any[];
}
const getCharacters = async (): Promise<CharactersResponse> => ({
    characters: [],
});
```

**Playground Link:**

http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=17&pc=6#code/JYOwLgpgTgZghgYwgAgLIHsBuwIGcBKeADuiLigN4BQytyAtljrgFzIDaAugNxUC+VKmACeRFAGEAFnCiJIUAsVLlkAXmSEE6KABMAPCACu9AEbQANMjghhAPl5UtZMMgDmEMBmx41V3MJAEZAAKAEo2AAUodHpgcj0vZkJcEjIIWzUM4Oo6BiY8Ni5zflDBJ1wXdzApGTloXF84f0CQ8OQomLiIPRrZBHlFFOV0zJDqPlCHYKaAoLDRnLpyl3YKPO8GvksEaT6BzkaAdzhgFw7Y8gA6OAAbG+D2KsS8MMsq3rqFMM5JmiXldA3CCXG7oVzBRgbba7T64X4TMLcIA

**Related Issues:**

None found.

### LINKED ISSUE #34937: 3.7.2 Promise.all does infers base type of interfaces rather than actual interface
**TypeScript 3.7.2**
[Playground link](https://www.typescriptlang.org/play/index.html#code/JYOwLgpgTgZghgYwgAgIoFcD2kBiwA2kUyA3gFDKXID6wAJgFzIDOYUoA5gNxkC+ZZUEXhI0WXASIBBOgDc4IJHWQQAHpBB1mY7BDyFopClRBwAthCat2IbnwEx0isMEwhkHCGAy79RZgAUAJRMAApQmGbAzBAAPD4SBlAA2gC6AHxGVMhQXuhQ7iAQAO7I4ZHRcQl6ktBp6QHG2ZQBucyY+LIQADQ5EABWEAhgQcgAvJnkzdN97Z0QAclNM80kNPRMAOQAKhCsm8j8K9mpQTwrvGf2ZI7Oru6e3uI1Scwy8ooQdMFhEVEx8Wefmg7wUSnqWSouTA+UKJTKf0qgN8tSgoM+dHqjRWrT2HS6vVyg2GowmkOOs3xCyWFNW60YyB2ezAm16pgsW12+0OyxWp3OM0uPH4ZDgzAAnopguNJssEG5WMhkjBUcxenA5GCvqlxsg4MU4MAwAiKjEAHRwfD4Ra8qiParAqCBILdW2Ue1A1XopTBZb8vhAA)

Compiler Options:
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "useDefineForClassFields": false,
    "alwaysStrict": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "downlevelIteration": false,
    "noEmitHelpers": false,
    "noLib": false,
    "noStrictGenericChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "preserveConstEnums": false,
    "removeComments": false,
    "skipLibCheck": false,
    "checkJs": false,
    "allowJs": false,
    "experimentalDecorators": false,
    "emitDecoratorMetadata": false,
    "target": "ES2017",
    "module": "ESNext"
  }
}
```

**Input:**
```typescript
interface QuoteFilter {
    _id: string;
}

interface QuoteFilterAdvanced extends QuoteFilter {
    name: string;
}

function getQuoteFilters(): Promise<QuoteFilter[]> {
    return new Promise<QuoteFilter[]>(
        (resolve, reject) => {
            resolve([
               { _id: 'Test' }
            ]);
        });
}

function getQuoteFiltersAdvanced(): Promise<QuoteFilterAdvanced[]> {
    return new Promise<QuoteFilterAdvanced[]>(
        (resolve, reject) => {
            resolve([
               { _id: 'Test', name: 'Test' }
            ]);
        });
}

async() => {
    const [filters, advanced] = await Promise.all([
        getQuoteFilters(),
        getQuoteFiltersAdvanced()
    ]);
}
```

**Output:**
```javascript
"use strict";
function getQuoteFilters() {
    return new Promise((resolve, reject) => {
        resolve([
            { _id: 'Test' }
        ]);
    });
}
function getQuoteFiltersAdvanced() {
    return new Promise((resolve, reject) => {
        resolve([
            { _id: 'Test', name: 'Test' }
        ]);
    });
}
async () => {
    const [filters, advanced] = await Promise.all([
        getQuoteFilters(),
        getQuoteFiltersAdvanced()
    ]);
};

```

**Expected behavior:**
I am expecting the advanced variable to be an array of QuoteFilterAdvanced rather than QuoteFilter.

This was correctly inferred in Typescript 3.6.3

### LINKED ISSUE #35136: Unexpected compile / type error when using Promise.all
**TypeScript Version:**  3.7.2

**Search Terms:**
- Promise.all typing

**Code**

`index.ts`
```ts
type RandomType = {};

const getRandomValue = async (): Promise<RandomType> => {
    return {};
};

const getResults = async (): Promise<{ data: string[] }> => {
    return { data: ['a', 'b', 'c'] };
};

const run = async () => {
    const [random, { data }] = await Promise.all([getRandomValue(), getResults()]);
    console.log(random, data);
};

run();
```

`tsconfig.json`
```json
{
    "compilerOptions": {
        "target": "esnext",
        "lib": ["esnext", "dom"]
    },
    "exclude": ["node_modules"],
    "include": ["./**/*.ts"]
}

```

**Expected behavior:**
Compiles successfully.

**Actual behavior:**
Compile error: "Property 'data' does not exist on type 'RandomType'."

Seems to still compile the js file even though it shows a compile error.

Does not run with `ts-node` though.

**Playground Link:**
http://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=13&pc=31#

**Related Issues:**

### LINKED ISSUE #35258: Insufficient type narrowing of return type with Promise.all
**TypeScript Version:**  3.7.2

**Search Terms:**
generics readonly Promise.all

**Code**

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "strictNullChecks": true,
    "esModuleInterop": true,
  }
}
```

```ts
declare function x1(): Promise<number>;
declare function x2(): Promise<number | null>;

(async () => {
	const [a, b] = await Promise.all([x1(), x2()]);
	if (a < 1) { }
})();
```

**Expected behavior:**
type of `a` should be `number`

**Actual behavior:**
type of `a` is `number | null`

**Playground Link:** 
https://www.typescriptlang.org/play/index.html?noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&esModuleInterop=false&ssl=1&ssc=1&pln=8&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwA8BGACgEoAueABRhwFssBnEAHlWXoCMQYA+ANwAoUJFgIU6bHkIAmclVoNmbDt17wAPvA4QIgoUJJQmAT3Txy8ALx94AbyEBIMHiYZ4AbSgAaeFwBdG3goAHcoLA8lRhYAOig9Ek9icj8CeTIAsmEnLERLKHhWeCIyB3gAXyEKsnJhIA

**Related Issues:**

### PR DESCRIPTION
**Pull request by rbuckton**
This adds an `Awaited<T>` type alias that supports the following capabilities:

- Recursive unwrap
- Resolves promise-like "thenables" without relying on `PromiseLike` (to avoid issues with augmentation/assignability)
- Non promise "thenables" resolve to `never`
- Supports `null` and `undefined` in non-strictNullChecks mode
- Relies on recursion limiters to provide errors for unresolvable promises.

This also adds overloads to `Promise.all`, `Promise.race`, `Promise.allSettled`, and `Promise.any` to leverage `Awaited<T>`.

Supersedes #33707, thanks @jablko for your prior work on this.

Fixes #27711
Fixes #22469
Fixes #28427
Fixes #30390
Fixes #31722
Fixes #33559
Fixes #33562
Fixes #33752
Fixes #34924
Fixes #34937
Fixes #35136
Fixes #35258

### CODE REVIEW

**Comment by rbuckton** [comment]
The OOM in Prettier doesn't seem to be related to this change, as I'm seeing it in other unrelated PRs as well.

**Comment by rbuckton** [comment]
Notes from design meeting:

- [x] Need to see what this breaks.
  - Nothing seems broken in the RWC and User tests as is.
- [ ] Need to see if we can remove overloads.
  - I'm concerned that removing overloads for `all` will be a breaking change for anyone who has previously used
    explicit type arguments to overcome inference issues that this will ostensibly solve. The question is whether 
    this is an acceptable breaking change.
- [ ] Maybe see if this can be leveraged by `await`?
  - I am exploring this in a separate PR that I will post shortly. This is likely to be a very breaking change in higher-order, since `await PT` where `PT` is a `Promise<T>` and `T` is a type variable will now produce an `Awaited<T>` instead of `T`. While this is arguably more correct (which was the case in the `awaited T` PR), it is also likely to be a breaking change.

**Comment by rbuckton** [comment]
I investigated whether having `await` return `Awaited<T>` would be a major breaking change in #45701 and it doesn't seem like that's the case, so I will merge the changes into this PR.

**Comment by rbuckton** [comment]
@typescript-bot perf test
@typescript-bot run dt
@typescript-bot test this
@typescript-bot user test this inline

**Comment by rbuckton** [comment]
Dropping overloads for `.all` is definitely a breaking change, per https://github.com/microsoft/TypeScript/pull/45350#issuecomment-912843170.

Puppeteer uses `Promise.all` with explicit type arguments: 
- https://github.com/puppeteer/puppeteer/blob/10e847404e83781cea6e624431798e2792fa440e/src/common/Coverage.ts#L256
- https://github.com/puppeteer/puppeteer/blob/10e847404e83781cea6e624431798e2792fa440e/src/common/Page.ts#L1757

@DanielRosenwasser: @ahejlsberg was in favor of dropping the redundant overloads. Is this something we feel comfortable with shipping in 4.5 as a breaking change or should we leave [these overloads](https://github.com/microsoft/TypeScript/pull/45350/files#diff-8c957ded346ac45f5abec03832bab4bfb8eeb382b4e7ad087b27a28b4301735bL21) in for now?

If necessary, we could add a `/** @deprecated */` to the now mostly unnecessary overloads and give users a release before removing them. Something like this:
```ts
/**
 * @deprecated This overload has been removed in favor of `all<T extends readonly unknown[] | []>(values: T): Promise<...>`. 
 * If explicit type arguments are still necessary, please use `all<[T1, T2, T3, ...]>(...)` instead.
 */
all<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(values: readonly [T1 | PromiseLike<T1>, T2 | PromiseLike<T2>, T3 | PromiseLike<T3>, T4 | PromiseLike<T4>, T5 | PromiseLike<T5>, T6 | PromiseLike<T6>, T7 | PromiseLike<T7>, T8 | PromiseLike<T8>, T9 | PromiseLike<T9>, T10 | PromiseLike<T10>]): Promise<[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]>;
```

**Comment by rbuckton** [comment]
@typescript-bot pack this

**Comment by rbuckton** [comment]
If anyone in the community heavily uses `await` with generics and/or `Promise.all`, please give the above build a try and let me know your experience.

**Comment by andrewbranch** [comment]
Verdict from design meeting:

- Let's try removing the `Promise.all` overload ladder and listen for feedback in nightlies
- `await T` should only produce `Awaited<T>` when the constraint of `T` is `any`, `unknown`, `{}`, or `object`. Anything else is either primitive, or conveys enough information that we should just assume that it’s not going to be instantiated with something Promise-like. (Not sure it was mentioned in the meeting, but I also assume there is handling for when the constraint of `T` is already Promise-like.)

**Comment by rbuckton** [comment]
I've updated the PR based on the feedback from the design meeting. I still need a reviewer before I can merge, though.

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -32527,8 +32560,10 @@ namespace ts {
                 let wouldWorkWithAwait = false;
                 const errNode = errorNode || operatorToken;
                 if (isRelated) {
-                    const awaitedLeftType = getAwaitedType(leftType);
-                    const awaitedRightType = getAwaitedType(rightType);
+                    let awaitedLeftType = getAwaitedType(leftType);
+                    let awaitedRightType = getAwaitedType(rightType);
+                    awaitedLeftType &&= unwrapAwaitedType(awaitedLeftType);
+                    awaitedRightType &&= unwrapAwaitedType(awaitedRightType);
```
Comment (andrewbranch) [inline src/compiler/checker.ts:32566]: I don't think I understand why we'd unwrap here, and I doubt this has test coverage since it would only have an effect in higher order, and the test cases I recall are very simple `3 + promiseOfNumber` kind of operations. Actually, off the top of my head, I’m not sure you could come up with a test case where this matters, since it’s for binary operators where `wouldWorkWithAwait` would only come out true if the awaited types were primitives?

**Comment by andrewbranch** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts (hunk 1 above)
Comment (rbuckton) [reply src/compiler/checker.ts:32566]: I had to add this or we were getting `Did you forget to use 'await'?` related errors for every invalid expression like `1 + {}`. That may have been remediated by restrictions I added around when we add `Awaited<T>` to the result of `getAwaitedType`, but in general I think its a good idea to leave this in since this logic previously expected `getAwaitedType` to return `T` (and not `Awaited<T>`).

Comment (rbuckton) [reply src/compiler/checker.ts:32566]: The problem is with the behavior of assignability with respect to recursive conditional types. Take these two examples:

**Example 1**
```ts
// @strict: true

var v: void;
var b: boolean;
function f<T>(x: T, y: Awaited<T>) {
    x < v; // error
    y < v; // ok

    x < b; // error
    y < b; // error
}
```
[Playground Link](https://www.staging-typescript.org/play?ts=4.5.0-pr-45350-27&ssl=1&ssc=17&pln=1&pc=13#code/PTAEAEGcBcCcEsDG0Bco4FcCmAoHA3AQ1lHzXwHt4ATAbgONACM0mKKAbLQgO3oDMMPZPAo9Q-ADwAVAHwAKAB5ppAGlABPNAEEA7oXjQs1GbICUoAN45Qt0ItCTS9O5sfO8rh06Yu7G918cAF8gA)

**Example 2**:
```ts
// @strict: false

var v: void;
var b: boolean;
function f<T>(x: T, y: Awaited<T>) {
    x < v; // error
    y < v; // ok

    x < b; // error
    y < b; // ok
}
```
[Playground Link](https://www.staging-typescript.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&ts=4.5.0-pr-45350-27#code/PTAEAEGcBcCcEsDG0BcoBmBDANpApgFAEBumsoxaxA9vACYDcJZoARmq9ddnpgHZN0AVz7J41PhgA8AFQB8ACgAeaGQBpQATzQBBAO6Z40PHVlyAlKADeBUHdBLQUik3tanLom8fPWr+5oefgQAvkA)

In Example 1 (strict mode), `x < v` is an error, but `y < v` is *not* an error, which results in `wouldWorkWithAwait` being `true`. It also behaves that way if `v` is `any[]`, for some reason.

In Example 2 (non-strict mode), `x < v` and `x < b` are errors, but `y < v` and `y < b` are *not* errors, which results in  `wouldWorkWithAwait` being `true` for *every* failed comparison operation.

As a result, I think this needs to stay, but I'll do a little more digging.

Comment (rbuckton) [reply src/compiler/checker.ts:32566]: When we're checking whether `Awaited<T>` is comparable to `void`, we get to a point where we're checking whether the default constraint of `Awaited<T>` is comparable to `void`. The default constraint of `Awaited<T>` is `T | (T extends object ? T extends { then(onfulfilled: infer F): any; } ? F extends (value: infer V) => any ? Awaited<V> : never : T : T)`, so we end up in a union comparison.

In the union comparison we use `someTypeRelatedToType` because we're using the comparable relation. During this, we check if `T` is related to `void`, and in the process call `getNormalizedType(T, /*forWriting*/ false)` which returns the `null` type, which is comparable to `void`. This means `Awaited<T>` is comparable to `void`, so `wouldWorkWithAwait` ends up `true`.

Comment (rbuckton) [reply src/compiler/checker.ts:32566]: Also, you don't trigger the suggestion diagnostic because `getAwaitedType` for `Awaited<T>` produces `Awaited<T>`, so the type doesn't change (and thus won't trigger the related error diagnostic).

**Review by andrewbranch — APPROVED** [review]

File: src/lib/es5.d.ts [hunk 2]
```diff
@@ -1440,6 +1440,19 @@ interface Promise<T> {
...
+ */
+type Awaited<T> =
+    T extends null | undefined ? T : // special case for `null | undefined` when not in `--strictNullChecks` mode
+        T extends object ? // `await` only unwraps object types with a callable then. Non-object types are not unwrapped.
+            T extends { then(onfulfilled: infer F): any } ? // thenable, extracts the first argument to `then()`
+                F extends ((value: infer V) => any) ? // if the argument to `then` is callable, extracts the argument
+                    Awaited<V> : // recursively unwrap the value
+                    never : // the argument to `then` was not callable.
+            T : // argument was not an object
+        T; // non-thenable
```
Comment (ExE-Boss) [inline src/lib/es5.d.ts:1454]: I believe that these comments are swapped.

Comment (rbuckton) [reply src/lib/es5.d.ts:1454]: Apparently so. I will push up a small fix.

Comment (rbuckton) [reply src/lib/es5.d.ts:1454]: Fixed by #45918

**Comment by frigus02** [comment]
> If anyone in the community heavily uses `await` with generics and/or `Promise.all`, please give the above build a try and let me know your experience.

I did a quick search for `Promise.all` usages in the Google code base internally and only found a handful (~10) of usages with more than 1 generic parameter. We should be fine here.

To check usages of `await` with generics we will have to actually upgrade TypeScript and see where the builds break, I think. We'll probably report that together with other findings.

**Comment by wbt** [comment]
It would be helpful to add some documentation about this on the [Utility types page](https://www.typescriptlang.org/docs/handbook/utility-types.html), not just in the 4.5 release notes that aren't part of the docs search.
