### ISSUE TITLE
Trying to import a project with allowSyntheticDefaultImports into one without causes errors

### ISSUE THREAD

**Issue by zsgalusz** [Microsoft/TypeScript#26316]
When trying to import dependencies that were compiled with allowSyntheticDefaultImports into a project without the setting, TS generates errors inside the imported project. This means it's impossible to use libs generated with different import settings, and makes synthetic imports contagious. Also things get extra difficult when trying to use 2 dependencies with mismatching setting - one of them will always error. Noticed this issue when upgrading to TS3.0 - it was working in TS2.8.

**TypeScript Version:**  typescript@3.1.0-dev.20180808

**Search Terms:** allowSyntheticDefaultImports, Module has no default export

**Code**

```ts
// in project foo with allowSyntheticDefaultImports: true
import React from "react";

export class Foo extends React.Component {
  render() {
    return <div>Foo</div>;
  }
}

// in project bar without allowSyntheticDefaultImports
import * as React from "react";
import { Foo } from "foo";

export class Bar extends React.Component {
  render() {
    return <Foo />;
  }
}
```

**Expected behavior:**
Both projects should build without errors. The consumer project should not need to know about the settings used to compile the dependency, and should not be expected to use allowSyntheticDefaultImports.

**Actual behavior:**
Second project generates error in first project: `../foo/dist/index.d.ts:1:8 - error TS1192: Module '"/Users/nyu/Code/tstest/bar/node_modules/@types/react/index"' has no default export.`

**Playground Link:** because needing multiple projects, cant very well replicate in playground. Instead clone this: https://github.com/zsgalusz/tssynthetictest

**Related Issues:** nothing promising looking

**Comment by RyanCavanaugh** [comment]
> This means it's impossible to use libs generated with different import settings, and makes synthetic imports contagious.

This is *true* though. If you're using a piece of code that depends on a loader providing synthetic defaults, then you can't run it in an environment where synthetic defaults aren't present.

`allowSyntheticDefaultImports` isn't really an either/or proposition; if it's off and you turn it on, nothing bad will happen.

**Comment by zsgalusz** [comment]
> allowSyntheticDefaultImports isn't really an either/or proposition; if it's off and you turn it on, nothing bad will happen.

That's not entirely true. For example, in our projects we have a lot of old namespace imports like `import * as classnames from 'classnames'`. Turning on `allowSyntheticDefaultImports` unsurprisingly causes all these to error at runtime with eg. `TypeError: classnames is not a function`.
