### ISSUE TITLE
instanceof type guard missing deduction

### ISSUE THREAD

**Issue by abramobagnara** [Microsoft/TypeScript#20138]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
class C { }

function f<T extends C>(v: T | string): void {
  if (v instanceof C) {
    const x: T = v;
    console.log(x);
  }
}

```

**Expected behavior:**

No compile errors:

**Actual behavior:**

p.ts(5,11): error TS2322: Type 'string | T' is not assignable to type 'T'.
  Type 'string' is not assignable to type 'T'.

**Comment by ahejlsberg** [comment]
This was an error in previous releases too because `C` is an empty object type. However, with #19671 we can (and should) get this right.

**Comment by abramobagnara** [comment]
From last part of comment above it seems you imply that master branch after #19671 merge get this right, but this is not the case. Am I missing something?

I can confirm that if C is not an empty object type Typescript 2.6.1 compile the source without errors.

**Comment by ahejlsberg** [comment]
@abramobagnara I meant that with the approach we introduced in #19671 we *can*, but currently don't , get it right even when C is an empty class type (as in your example). You are correct that it used to work when C is not an empty class. Both issues are fixed by #20142 that I just put up.
