### ISSUE TITLE
5.1 regression from 5.0: JavaScript heap out of memory (Type instantiation is excessively deep and possibly infinit)

### ISSUE THREAD

**Issue by melroy89** [microsoft/TypeScript#54542]
# Bug Report

`5.0.4` used to work fine after upgrading to the current latest version `5.1.3`. Very slow builds and eventually crashes. My root-cause seems to be a circular issue of some sort with tsc.

Seems like tsc can't handle interface definition files anymore, in this case from `lodash`?

```
node_modules/@types/lodash/common/common.d.ts:194:15 - error TS2589: Type instantiation is excessively deep and possibly infinite.

194     interface Object<T> extends LoDashImplicitWrapper<T> {
                  ~~~~~~

node_modules/@types/lodash/common/common.d.ts:206:15 - error TS2430: Interface 'ObjectChain<T>' incorrectly extends interface 'LoDashExplicitWrapper<T>'.
  The types returned by 'entries().pop()' are incompatible between these types.
    Type 'CollectionChain<string | T[keyof T]>' is missing the following properties from type 'ObjectChain<[string, any]>': assign, assignIn, assignInWith, assignWith, and 11 more.

206     interface ObjectChain<T> extends LoDashExplicitWrapper<T> {
                  ~~~~~~~~~~~
```

My workaround was adding `"skipLibCheck": true` to the tsconfig.json did mitigate the issue for now.

```
node_modules/@types/lodash/common/common.d.ts:194:15 - error TS2589: Type instantiation is excessively deep and possibly infinite.

194     interface Object<T> extends LoDashImplicitWrapper<T> {
                  ~~~~~~

node_modules/@types/lodash/common/common.d.ts:206:15 - error TS2430: Interface 'ObjectChain<T>' incorrectly extends interface 'LoDashExplicitWrapper<T>'.
  The types returned by 'entries().pop()' are incompatible between these types.
    Type 'CollectionChain<string | T[keyof T]>' is missing the following properties from type 'ObjectChain<[string, any]>': assign, assignIn, assignInWith, assignWith, and 11 more.

206     interface ObjectChain<T> extends LoDashExplicitWrapper<T> {
                  ~~~~~~~~~~~
```
Workaround for me was to add: `"skipLibCheck": true` to the tsconfig.json did mitigate the issue for now.

### 🔎 Search Terms

- Crash
- OOME
- 5.1
- Heap

### 🕗 Version & Regression Information

I also tried the latest `next` tag, with the same issues.

- This is a crash
- This changed between versions 5.0.x and 5.1.x

### ⏯ Playground Link

The "Type is excessively deep" is being triggered in a project that includes this the `@types/lodash`, so in your package.json be sure you have the dependency:

```json
"dependencies": {
     "lodash": "^4.17.21"
},
"devDependencies": {
    "@types/lodash": "^4.14.195"   
}
```

Be sure that you did NOT set `skipLibCheck` to `true`. So keep it to false, otherwise the `d.ts` files will be ignored. 

Execute via: `NODE_OPTIONS=--max-old-space-size=8192 tsc --pretty --diagnostics --extendedDiagnostics --incremental false`

### 💻 Code

See below, it doesn't involve my code.

### 🙁 Actual behavior

JavaScript heap out of memory, because of circular/ too deep dependency?

```bash
node_modules/@types/lodash/common/common.d.ts:194:15 - error TS2589: Type instantiation is excessively deep and possibly infinite.

194     interface Object<T> extends LoDashImplicitWrapper<T> {
                  ~~~~~~

node_modules/@types/lodash/common/common.d.ts:206:15 - error TS2430: Interface 'ObjectChain<T>' incorrectly extends interface 'LoDashExplicitWrapper<T>'.
  The types returned by 'entries().pop()' are incompatible between these types.
    Type 'CollectionChain<string | T[keyof T]>' is missing the following properties from type 'ObjectChain<[string, any]>': assign, assignIn, assignInWith, assignWith, and 11 more.

206     interface ObjectChain<T> extends LoDashExplicitWrapper<T> {
                  ~~~~~~~~~~~
Found 2 errors in 1 file.

Errors  Files
     2  node_modules/@types/lodash/common/common.d.ts:194
Files:                          253
Lines of Library:              9875
Lines of Definitions:         73521
Lines of TypeScript:           3999
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Identifiers:                 117524
Symbols:                    4856905
Types:                      1093043
Instantiations:            11883895
Memory used:               2379915K
Assignability cache size:    230447
Identity cache size:            772
Subtype cache size:             398
Strict subtype cache size:       10
I/O Read time:                0.15s
Parse time:                   1.17s
ResolveModule time:           0.21s
ResolveTypeReference time:    0.03s
ResolveLibrary time:          0.02s
Program time:                 1.70s
Bind time:                    0.47s
Check time:                 239.51s
transformTime time:           0.05s
Source Map time:              0.02s
commentTime time:             0.04s
I/O Write time:               0.02s
printTime time:               0.37s
Emit time:                    0.37s
Total time:                 242.05s
```

### 🙂 Expected behavior

No crashes or errors during `tsc`!

**Comment by ahejlsberg** [comment]
I can repo this with a simple single-file project that just imports `@types/lodash` when `strict` mode is disabled:

```ts
// compile without --strict
import "lodash";
```

No problems when compiling with `--strict` enabled. The runaway type check happens when computing variance information for type `Object<T>`. A quick workaround is to change one of the declarations of `Object<T>` to `Object<in out T>`.

**Comment by ahejlsberg** [comment]
@RyanCavanaugh @DanielRosenwasser FYI.

**Comment by ahejlsberg** [comment]
Hoping someone has time to bisect this so we can identify the source of the issue.

**Comment by jakebailey** [comment]
Wild guess, but this may be the cause of the OOM in https://github.com/typescript-eslint/typescript-eslint/pull/7088 based on the timing.

**Comment by JoshuaKGoldberg** [comment]
Confirmed @jakebailey, great spot - thanks! I bisected in https://github.com/typescript-eslint/typescript-eslint/pull/7091 on the individual TypeScript `main` commits and 958487bedac2f9990387ca0f65f977a7f7c18297 is the first that causes the OOM.

**Comment by cami-dev** [comment]
Any update on this? Got the same issue when upgrading to typescript 5.1.3 from 4.9.4 and we have @types/lodash : 4.14.195 as devdependencies

**Comment by throrin19** [comment]
Same problem with lodash here. Any news about this resolution ? 

This is my error : 

```
 ../../node_modules/@types/lodash/common/common.d.ts(194,15): error TS2589: Type instantiation is excessively deep and possibly infinite.
       ../../node_modules/@types/lodash/common/common.d.ts(206,15): error TS2430: Interface 'ObjectChain<T>' incorrectly extends interface 'LoDashExplicitWrapper<T>'.
         The types returned by 'entries().pop()' are incompatible between these types.
           Type 'CollectionChain<string | T[keyof T]>' is missing the following properties from type 'ObjectChain<[string, any]>': assign, assignIn, assignInWith, assignWith, and 11 more.
```

**Comment by melroy89** [comment]
My workaround for now is to disable interfaces (.d.ts files), using the following code snippet in my local `tsconfig.json` file:

```json
  "skipLibCheck": true,
```

**Comment by slavede** [comment]
https://github.com/microsoft/TypeScript/issues/54542#issuecomment-1594889906

**Important to mention** that it is a just temporary workaround as it would skip all libraries check.

**Comment by slavede** [comment]
> My workaround for now is to disable interfaces (.d.ts files), using the following code snippet in my local `tsconfig.json` file:
> 
> ```json
>   "skipLibCheck": true,
> ```
> 
> More info: https://www.typescriptlang.org/tsconfig#skipLibCheck


**Important to mention** that it is a just temporary workaround as it would skip all libraries check.

**Comment by melroy89** [comment]
> **Important to mention** that it is a just temporary workaround as it would skip all libraries check.

Yes workarounds are hopefully temporary in general. I don't like this approach either, but at least I can build again.

**Comment by StanislavKharchenko** [comment]
Any chance to fix this?
3 weeks after issue was reported.

**Comment by chris-heney** [comment]
Yeah, my serverless framework deploys are broken until this is fixed too.

**Comment by DanielRosenwasser** [comment]
Can people following the thread verify that https://github.com/microsoft/TypeScript/pull/54781 fixes the issue? You can do so by using a specific build of TypeScript:

```json
{
    "devDependencies": {
        "typescript": "https://typescript.visualstudio.com/cf7ac146-d525-443c-b23c-0d58337efebc/_apis/build/builds/155637/artifacts?artifactName=tgz&fileId=04DE374095785839F62F13D7F462400B471B8FC647A291E41CD31D23BFD6186002&fileName=/typescript-5.2.0-insiders.20230626.tgz"
    }
}
```

(see https://github.com/microsoft/TypeScript/pull/54781#issuecomment-1607903315)

**Comment by Mr0grog** [comment]
@DanielRosenwasser That build works great and solves the issue for the project where I ran into problems! 🚀

**Comment by dcsaszar** [comment]
@DanielRosenwasser Verified. Works for us, too!

**Comment by JoshuaKGoldberg** [comment]
@DanielRosenwasser confirmed https://github.com/typescript-eslint/typescript-eslint/pull/7088/ appears to be fixed, thanks!

**Comment by melroy89** [comment]
Sorry for my late response, but I can in fact confirms TypeScript v5.2.2 solved all my issues.
