### ISSUE TITLE
Symbol.interator for array of numbers?

### ISSUE THREAD

**Issue by sant123** [Microsoft/TypeScript#11102]
**TypeScript Version:**  Playground.

Hi, in the playground version I found this:

![image](https://cloud.githubusercontent.com/assets/7959437/18794363/cd0a018e-8184-11e6-9241-fb9f6475432f.png)

**Code**

```ts
function myFunc() {
    let items = [1, 2, 3, 4, 5];

    for (let item of items) {
        console.log(item);
    }
}
```

**Expected behavior:**
No error.

**Actual behavior:** 
An error.

In normal JS this is not an error:

![image](https://cloud.githubusercontent.com/assets/7959437/18794408/058ebe1e-8185-11e6-98d5-96748082b8ee.png)

**Comment by kitsonk** [comment]
That seems to be a really odd configuration of Playground that is causing it with the release of TypeScript 2.0.  It seems like the Playground is sort of stuck between ES5 and ES6.  The emit is ES5, but the syntax checking is ES6 but without the proper libraries loaded.

Running locally, both targeting ES5 and ES6 that works without issue.

**Comment by sccolbert** [comment]
Another example:

![capture](https://cloud.githubusercontent.com/assets/137289/18797661/8f8465ec-8194-11e6-8d4f-116fd1e5bbcc.PNG)

**Comment by sant123** [comment]
That's right @kitsonk, but only occurs in the playground. Also async and generator statements are "compiled" with no problems, but the result code is not compatible with ES5 and below. I've tested it with VS Code too but I do not get problems.

**Comment by sccolbert** [comment]
I get this error when running the code above targeting ES5 output. i.e. not limited to playground for me:
`error TS2346: Supplied parameters do not match any signature of call target.`

**Comment by kitsonk** [comment]
@sccolbert did that ever work?  I think what you are proposing is covered by #5296 which is still just a proposal.

**Comment by sccolbert** [comment]
@kitsonk I could have sworn it used to be translated to a `foo.apply(void 0, values)` call...

**Comment by sccolbert** [comment]
For example, this compiles fine on TS 1.8:

```
var values: number[] = [1, 2, 3, 4, 5];
var data: number[] = [];

data.push(...values);
```

But as you mentioned, the original code I posted does not. Which is doubly strange :)

**Comment by jasongrout** [comment]
> For example, this compiles fine on TS 1.8:

And that code seems fine on playground too: http://www.typescriptlang.org/play/#src=var%20values%3A%20number%5B%5D%20%3D%20%5B1%2C%202%2C%203%2C%204%2C%205%5D%3B%0D%0Avar%20data%3A%20number%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0Adata.push(...values)%3B

**Comment by mhegazy** [comment]
this is an issue with the playground. we recently updated to the latest version of [monco-editor](https://github.com/Microsoft/monaco-editor) and that seems to set the target to ES6 all the time. i will see if i can get a fix for this soon. sorry for the confusion.

Iterators are only supported when your targeting ES6. so `for .. of` only works in ES6. and you should get an error indicating this otherwise.

**Comment by sccolbert** [comment]
Sounds like my example is a red herring. Still not clear though why spread works in one context, but not the other.

**Comment by mhegazy** [comment]
Should be fixed now. sorry about the confusion.
