### ISSUE TITLE
IDBRequest interface error while upgrading from 1.4 to 1.5

### ISSUE THREAD

**Issue by DickvdBrink** [Microsoft/TypeScript#3721]
Hi guys, 
I was converting some more TS code to 1.5 but I noticed a problem while upgrading from 1.4 to 1.5.

My issue is that the code below used to compile in 1.4 but doesn't in 1.5 because the onerror event changed.

    addReq.onerror = (event) => {
        deferred.reject("Error" + event.message);
    };

addReq is of type `IDBRequest` and the error with 1.5 is:
>TS2339	Property 'message' does not exist on type 'Event'

This happens because on 1.4 onerror was defined like this: `onerror: (ev: ErrorEvent) => any` [link](https://github.com/Microsoft/TypeScript/blob/v1.4/src/lib/dom.generated.d.ts#L10011)
and in 1.5 it is defined like this: `onerror: (ev: Event) => any` [link](https://github.com/Microsoft/TypeScript/blob/v1.5.0-beta/src/lib/dom.generated.d.ts)

Was this intentional?

**Comment by mhegazy** [comment]
@zhengbli can you take a look

**Comment by zhengbli** [comment]
The reason was that in the spec, the type of ``error`` event fired by ``IDBRequest`` is ``Event`` instead of ``ErrorEvent``. And according to the [W3C](https://w3c.github.io/IndexedDB/#dfn-fire-an-error-event):
> The event must use the Event interface and have its type set to "error"

Therefore the change might be safer. A workaround might be:
```typescript
addReq.onerror = (event) => {
    console.log("Error" + (<ErrorEvent>event).message);
};
```

**Comment by DickvdBrink** [comment]
Ah oke, Just mentioned this because the upgrade broke my code but if it is by design it is fine with me. Easy fix so no worry :)

Guess this one can be closed :)
