### ISSUE TITLE
TSC compiler fails to resolve node typings if started with -p

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/TypeScript#10536]
**TypeScript Version:**  2.0.0

**Steps""
- create new directory
- npm init (fill in the values)
- npm install --save typescript@2.0.0
- npm install --save @types/node
- add the following setting to the workspace settings `"typescript.tsdk": "./node_modules/typescript/lib"`
- create a tsconfig.json with the following settings:
```json
{
	"compilerOptions": {
		"module": "commonjs",
		"moduleResolution": "node"
	},
	"exclude": [
		"node_modules"
	]
}
```
- create TS file main.ts with the following content
```ts
import * as cp from 'child_process';
```

Observe: everything is ok in VS Code. No errors and code assist works
- open shell on the workspace
- execute .\node_modules\.bin\tsc -p .
Observe: compile errors are printed
```
main.ts(1,21): error TS2307: Cannot find module 'child_process'.
```
- execute .\node_modules\.bin\tsc
Observe everything is ok

Might hit more people when migrating to 2.0.0. Almost all our scripts call tsc with -p .

**Comment by yortus** [comment]
I just ran into the opposite problem a few hours ago. `tsc -p` compiled without errors, but there were red squiggles in VSCode on all the node `import`s. When I added a `typeRoots` setting to `tsconfig.json`, they were both happy. Something is definitely out of sync between the two.

**Comment by mhegazy** [comment]
should be fixed in `typescript@next` and next TS 2.0 release.
