### ISSUE TITLE
Exported variable 'x' has or is using name 'y' from external module 'z' but cannot be named

### ISSUE THREAD

**Issue by evert** [microsoft/TypeScript#43008]
# Bug Report

### 🔎 Search Terms

* exported
* external
* 4.2
* symbol

### 🕗 Version & Regression Information

  This error started popping up in 4.2.2. We rolled back all our typescript versions to 4.1.5. I suspect it _might_ be a regression, but I don't understand the error well enough to be certain.

- This changed between versions 4.1.5 and 4.2.2

### ⏯ Playground Link

So, this really sucks but I've been trying to create a minimal version of this issue, but because this crosses multiple packages all my efforts so far were fruitless. I control all the relevant packages though

### 💻 Code

This is a simplified version of the code that _doesn't_ trigger this bug unfortunately. 

The following is a basic middleware framework:

```typescript
const middlewareCall = Symbol('middleware-call');
export { middlewareCall };

/**
 * A function that can act as a middleware.
 */
type MiddlewareFunction = (
  ctx: number,
  next: () => Promise<void>
) => Promise<void> | void;

/**
 * An object that exposes a symbol can also function as a middleware
  */
type MiddlewareObject = {
  [middlewareCall]: MiddlewareFunction
};


type Middleware = MiddlewareFunction | MiddlewareObject;

export class App {

  use(mw: Middleware[]) {

    console.log(mw);

  }

}
```

An application might use this as such:

```typescript
import routes from './c';
import { App } from './a';

const app = new App();

app.use(routes);
```

The routes file is where the error occurs:

```typescript
import Controller from './d';

export default [
  new Controller()
];
```

Lastly, the controller:

```typescript
import { middlewareCall } from './a';

export default class Controller {
  
  [middlewareCall](ctx: number, next: () => Promise<void>) {

  }
}
```

I know this is a lot. I would hate to get this bug report. The issue with the above is indeed that it _doesn't_ reproduce the issue. To see it for yourself, run `tsc` on the following git repo (after upgrading to 4.2.2):

https://github.com/curveball/a12n-server

### 🙁 Actual behavior

```
src/routes.ts:37:7 - error TS4023: Exported variable 'routes' has or is using name 'middlewareCall' from external module "/home/evert/src/curveball/a12n-server/node_modules/@curveball/core/dist/application" but cannot be named.

37 const routes = [
         ~~~~~~
```

Found 1 error.

### 🙂 Expected behavior

No errors

**Comment by evert** [comment]
This is fixed in Typecript 4.2.3
