### ISSUE TITLE
ts4.6.1-rc regression: Property ... does not exist on type 'Partial<MyStorage>[K]'

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript#47890]
# Bug Report

### 🔎 Search Terms

partial, generics

### 🕗 Version & Regression Information
Tested with nuget package 4.6.0 and 4.6.1-rc and "nightly" on playground with is labeled v4.6.0-dev.20220116 

- This changed between versions 4.5.4 and 4.6.0

### ⏯ Playground Link

```ts repro
function __getStoredValue<K extends keyof Grid.Storage>(
    key: K
): Grid.Storage[K]['anonymousUser'] | undefined {
    let user = 'admin';

    let storageForKey = {
        anonymousUser: [1],
        users: {
            admin: [2]
        }
    } as Partial<Grid.Storage>[K];

    if (!storageForKey) {
        return undefined;
    }

    if (!user) {
        return storageForKey.anonymousUser;  // <--
    } else {
        if (storageForKey.users) {  // <--
            return storageForKey.users[user]; // <--
        }
        return undefined;
    }
}
namespace Grid {
    export interface Storage {
        columnWidths: StorageItem<number[]>;
    }
    export interface StorageItem<V> {
        /** value for anon */
        anonymousUser: V;
        /** value for each user */
        users: Record<string, V>;
    }
}
const result = __getStoredValue('columnWidths');
console.log(result);
```

[Workbench Repro](https://www.typescriptlang.org/dev/bug-workbench/?#code/GYVwdgxgLglg9mABAfWQcwKZQMpTgJwwBMA1AQwBsQMAeAaUQwA8oMwiBnRAawwE84wRAHF8MIgDpcBMpgB8ACgBQiVT34AuRHSUBKLaPFS8+WRgDadALrmA5GTAI+AWzggOAVQ4Z8tq4gAfRHAiDGAYMGJEAG8VNQosYO98RABeRHsiZwjbAG4lONUEqEQOEzMAMQI6fjSYwrVVBydXdy8fLXMARisAGgbG9x8OLVjG8bUyLIjOgCYrAbUAXwalxDIuAAUyfFhKGkNJaVN5Syt8hpghBQBCMplMKvwavl16idVCKBB8JBCwiLEfKNFaXa43Ib4N5jD5fH5Ie4nDBPF4SZpgFxuTzJYHLRgUbzvD5XRAKRGVar8CSQjjQxYTOG-UrlR6UvjU5IccyQ870xArD6IRl-dgAyJEXGqFYrMBkZwYDgABzIEAwIjERCJqmYioIJQirHwwBVauOZi14wgcCozjAAHVxFAABYjRBmzAASVYzhoYBAzgARj5zFY5JL+Q0dXrEAafMbVW6WRgvRgfSQ5BbGgB6ABUOcQADdKNREMACOtHEgc1m+ejMW1kloSOHs3nC8W1WWUhgVU6kj5ENW+TStAAlDBW-BEGhlMRgNC9RDp8PSpRWsBlIUKkAUErpVCYHAmYjkKgYBS2K02+2Ol22XT5dcca0YCQUOBoBSEDg7qAPoA)

### 🙁 Actual behavior
TS4.5.4 is happy to compile my code, but ts4.6.x complains on access `anonymousUser` or `users`:

Property 'anonymousUser' does not exist on type 'Partial<Storage>[K]'.
Property 'users' does not exist on type 'Partial<Storage>[K]'.
Property 'users' does not exist on type 'Partial<Storage>[K]'.

### 🙂 Expected behavior
Should still compile as the property exists on the type.

**Comment by RyanCavanaugh** [comment]
Cleaned up:
```ts
interface MyObj {
    someKey: {
      name: string;
    }

    someOtherKey: {
      name: number;
    }
}

const ref: MyObj = {
  someKey: { name: "" },
  someOtherKey: { name: 42 }
}

function func<K extends keyof MyObj>(k: K): MyObj[K]['name'] | undefined {
    const myObj: Partial<MyObj>[K] = ref[k];
    
    if (myObj) {
      return myObj.name;
    }

    const myObj2: Partial<MyObj>[keyof MyObj] = ref[k];
    if (myObj2) {
      return myObj2.name;
    }
    return undefined;
}
```

This appears to be caused by https://github.com/microsoft/TypeScript/pull/47109, specifically that we no longer immediately resolve `Partial<MyObj>[K]` to a non-generic type.

I believe this can be worked around with some minor modification (shown the repro as `myObj2`) which wouldn't cause any loss of correctness in working code, but we should document it in the blog regardless.

**Comment by RyanCavanaugh** [comment]
@ahejlsberg ping to confirm this is an intended break

**Comment by HolgerJeromin** [comment]
This duplicates the type information from `__storage` object into the function variable.
```ts
const __storage: Partial<Grid.Storage> = {...}
// inside function
const storageForKey:Partial<Grid.Storage>[keyof Grid.Storage]  = __storage[key];
// does not work:
const storageForKey:Partial<Grid.Storage>[K]  = __storage[key];
```

But fine enough for me. Thanks for your work.

<details><summary>Complete example</summary>

```ts
namespace Grid {
    export interface Storage {
        columnWidths: StorageItem<number[]>;
    }
    export interface StorageItem<V> {
        /** value for anon */
        anonymousUser: V;
        /** value for each user */
        users: Record<string, V>;
    }
}
const __storage: Partial<Grid.Storage> = {
    columnWidths: {
        anonymousUser: [1],
        users: {
            admin: [2]
        }
    }
};

function __getStoredValue<K extends keyof Grid.Storage>(
    key: K
): Grid.Storage[K]['anonymousUser'] | undefined {
    let user = 'admin';

    const storageForKey = __storage[key];
    //const storageForKey:Partial<Grid.Storage>[K]  = __storage[key]; // does not work
    //const storageForKey:Partial<Grid.Storage>[keyof Grid.Storage]  = __storage[key]; // works

    if (!storageForKey) {
        return undefined;
    }

    if (!user) {
        return storageForKey.anonymousUser;  // <--
    } else {
        if (storageForKey.users) {  // <--
            return storageForKey.users[user]; // <--
        }
        return undefined;
    }
}


const result = __getStoredValue('columnWidths');
console.log(result);
```
</details>

**Comment by ahejlsberg** [comment]
This is not an intended break. [This change](https://github.com/microsoft/TypeScript/pull/47109/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R24943) in #47109 was part of an early evolution of the PR, but should have been removed. It's an easy fix, I'll put up a PR.

**Comment by HolgerJeromin** [comment]
Successfully tested with TS `4.7.0-dev.20220220`. Thanks for your quick fix.
