### PR TITLE
Fix destructuring and narrowing interaction

### LINKED ISSUE #45762: 4.4 regression: `in` operator does not narrow types in generic constraints when destructuring
# Bug Report

### 🔎 Search Terms

in operator, narrowing, generics, constraints, destructuring

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4.2

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.2#code/C4TwDgpgBAGlC8UDeUCGAuKBnYAnAlgHYDmUAvlAD7JQBGmOBJ5AUCwGYCuhAxsPgHtCULrwCMAHgAqUCAA9gEQgBMssAHwAKAG6oANpwiYpASmQsoUfOyiaA5KjtXhugxDNILlqDyE40CFCuhgB0qF6WvoRYAnoQIXoCxPaOADRoJl4UEHpY0J7ePn7AdIHB8bQRRdGx8YnJdrR26bSZlmQsHRzcfILCojwATNKyCkqqGjr6hsYeXta2Dk5EQdPu5oVR-iio5GVrVVu1CUkpzRlZsrn5h8U0tHuI5bc1cScNTS1trB1AA)

### 💻 Code

```ts
type X = { a: string } | { b: string }

// Works in 4.3.5 and 4.4.2
function func1<T extends X>(value: T) {
  if ('a' in value) {
    const a = value.a
    console.log('a', a)
  } else {
    const b = value.b
    console.log('b', b)
  }
}

// Works in 4.3.5, not in 4.4.2
function func2<T extends X>(value: T) {
  if ('a' in value) {
    const { a } = value // Property 'a' does not exist on type 'X'.(2339)
    console.log('a', a)
  } else {
    const { b } = value // Property 'b' does not exist on type 'X'.(2339)
    console.log('b', b)
  }
}

```

### 🙁 Actual behavior

Types are not narrowed when using destructuring assignment and the compiler throws error 2339.

### 🙂 Expected behavior

Types are narrowed when using destructuring assignment.

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #45762

## Background

In 4.3, we improved control-flow narrowing of generic types (#43183). When we are about to go into control-flow narrowing, we call a function `getNarrowableTypeForReference`, that returns the type we are going to use in narrowing.
As of 4.3, when we call `getNarrowableTypeForReference` on something of type `T extends C`, we often get type `C` (the constraint) instead of the generic type `T`, which allows us to do narrowing when we couldn't. As an example:

```ts
type C = { kind: "a", a: string } | { kind: "b", b: string }

function func<T extends C>(value: T) {
    if (value.kind === "a") {
        value.a; // In 4.3: value.a: string
    } else {
        value.b; // In 4.3: value.b: string
    }
}
```

Inside the `if` branch above, to get the type of `value.a`, we first need the type of `value`. So we call `getNarrowableTypeForReference(value)`, and get type `C` (instead of the generic `T`, which we can't narrow). Then we can further narrow `C` into `{ kind: "a", a: string }` due to the `if` condition. Finally, we get the type of property `a` of type `{ kind: "a", a: string }`, which is type `string`, and that is the type of `value.a`.

In 4.3, the same thing happened for binding elements in binding patterns:

```ts
type C = { kind: "a", a: string } | { kind: "b", b: string }

function func<T extends C>(value: T) {
    if (value.kind === "a") {
        const { a } = value; // In 4.3: a: string
    } else {
        const { b } = value; // In 4.3: b: string
    }
}
```

However, that meant other things broke, like #43941:

```ts
type Params = {
    foo: string;
} & ({ tag: 'a'; type: number } | { tag: 'b'; type: string });

const getType = <P extends Params>(params: P) => {
    const {
        foo,
        ...rest // <4.3: rest: Omit<P, "foo"> -- 4.3: rest: { tag: 'a'; type: number } | { tag: 'b'; type: string }
    } = params;

    return rest;
};

declare const params: Params;

switch (params.tag) {
    case 'a': {
        const result = getType(params).type; // <4.3: result: number -- 4.3: result: string | number
        break;
    }
    case 'b': {
        const result = getType(params).type; // <4.3: result: string -- 4.3: result: string | number
        break;
    }
}
```

In the example above, to determine the type of `...rest`, we once again call `getNarrowableTypeForReference(params)`, determine that type, and then compute whatever properties are left after we remove `foo`.
Before 4.3, `getNarrowableTypeForReference(params)` returned type `P`, so `rest` would have generic type `Omit<P, "foo">. In 4.3, `getNarrowableTypeForReference(params)` returned type `Params`, so `rest` would have non-generic type `{ tag: 'a'; type: number } | { tag: 'b'; type: string }`.

That distinction between `rest` having a generic versus non-generic type means we can or can't narrow other uses of `rest`.
The problem in the example above surfaces in the `switch` statement, when we try to call the function `getType`, that returns `rest`.
If we keep `rest` generic, we can "flow" the narrowing of the switch statement into the return type of `getType`.
If `rest` is instead the non-generic type, we can't do that narrowing, because there's no longer a connection between `getType`'s type parameter `P` and the type of `rest`.

## Change in 4.4

To fix the issue #43941 above, we reverted the `getNarrowableTypeForReference(ref)` behavior, making it return the type parameter instead of the type parameter's constraint *when the reference `ref` was contextually typed by binding patterns*.
So the result was like this:

```ts
type C = { kind: "a", a: string } | { kind: "b", b: string }

function func<T extends C>(value: T) {
    if (value.kind === "a") {
        value.a; // In 4.4: value.a: string
        const { a } = value; // In 4.4: error, "Property 'a' does not exist on type 'C'".
    } else {
        value.b; // In 4.4: value.b: string
        const { b } = value; // In 4.4: error, "Property 'a' does not exist on type 'C'".
    }
}
```

## Issue

It seems we are at odds on whether we should have `getNarrowableTypeForReference` return the generic type or the constraint when we have binding patterns/destructuring, because the most useful behavior can go either way depending on the code in question.

In some cases, we really expect the binding pattern access to behave like the regular property access:
```ts
if (value.kind === "a") {
        value.a; // string
        const { a } = value; // error, but should be string???
}
```

On the other hand, in this case:
```ts
const getType = <P extends Params>(params: P) => {
    const {
        foo,
        ...rest
    } = params;

    return rest;
};
```
when `rest` has the generic type `Omit<P, "foo">`, it becomes possibly more useful for callers of that function, because we can narrow the return type based on the argument type.

## Proposed fix

A compromise for this issue with binding patterns is to have `getNarrowableTypeForReference` return the generic type if we are retrieving the type in order to use it for a *rest* binding element, and to have `getNarrowableTypeForReference` return the constraint type for non-rest binding elements. Like this:

```ts
type C = { kind: "a", a: string } | { kind: "b", b: string }

function func<T extends C>(value: T) {
    if (value.kind === "a") {
        const { a } = value; // getNarrowableTypeForReference(value) = C, a: string
        const { ...rest } = value; // getNarrowableTypeForReference(value) = T, rest: T (or Omit<T, something>)
    }
}
```

### Implementation

To implement this special casing for binding elements, we need a way to know *inside `getNarrowableTypeForReference` if we are returning a type to be used for determining the type of an object rest binding element.
This PR changes `getNarrowableTypeForReference` (and some other checker functions) to take in a `checkMode` parameter.
We also have a new `CheckMode` flag, `CheckMode.ObjectRestBindingElement`, that indicates precisely this.

## Questions
- Do we want to move forward with this fix? It's a bit weird and seems like we're stacking a special case on top of a special case, but there might not be a better way to solve this, because an argument can be made for using a generic type's constraint, and an argument can also be made for keeping the generic type in the situations above.

- Is there a better way to implement this, without passing around `CheckMode`? 
- Do we want this special, generic-preserving behavior for rest binding elements in array binding patterns too?

### CODE REVIEW

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -8680,11 +8688,15 @@ namespace ts {
         }
 
         // Return the inferred type for a variable, parameter, or property declaration
-        function getTypeForVariableLikeDeclaration(declaration: ParameterDeclaration | PropertyDeclaration | PropertySignature | VariableDeclaration | BindingElement | JSDocPropertyLikeTag, includeOptionality: boolean): Type | undefined {
+        function getTypeForVariableLikeDeclaration(
+            declaration: ParameterDeclaration | PropertyDeclaration | PropertySignature | VariableDeclaration | BindingElement | JSDocPropertyLikeTag,
+            includeOptionality: boolean, // >> TODO: change this to use a flag in check mode; figure out how this interacts with caching
```
Comment (gabritto) [inline src/compiler/checker.ts:8693]: If we decide to move forward with this PR, I'm going to replace the use of `includeOptionality` parameter by a new check mode flag.

File: tests/baselines/reference/narrowingDestructuring.js [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+    }
+}
+
+type Z = { kind: "f", f: { a: number, b: string, c: number } }
+    | { kind: "g", g: { a: string, b: number, c: string }};
+
+function func2<T extends Z>(value: T) {
+    if (value.kind === "f") {
+        const { f: f1 } = value;
+        const { f: { a, ...spread } } = value;
```
Comment (gabritto) [inline tests/baselines/reference/narrowingDestructuring.js:20]: I'm not sure if this case is any more weird than this whole thing already is, but... `...spread` here is not going to have a generic type, since we first get the non-generic type of `value`, then find out the non-generic type of property `f` on that type, and that's the type we use to compute the type of `spread`.

File: tests/cases/compiler/narrowingDestructuring.ts [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+    }
+}
+
+type Z = { kind: "f", f: { a: number, b: string, c: number } }
+    | { kind: "g", g: { a: string, b: number, c: string }};
+
+function func2<T extends Z>(value: T) {
+    if (value.kind === "f") {
+        const { f: f1 } = value;
+        const { f: { a, ...spread } } = value;
```
Comment (gabritto) [inline tests/cases/compiler/narrowingDestructuring.ts:19]: I'm not sure if this case is any more weird than this whole thing already is, but... ...spread here is not going to have a generic type, since we first get the non-generic type of value, then find out the non-generic type of property f on that type, and that's the type we use to compute the type of spread.

File: tests/cases/compiler/narrowingDestructuring.ts [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+    } else {
+        const { g: { c, ...spread } } = value;
+        value.g;
+    }
+}
+
+function func3<T extends { kind: "a", a: string } | { kind: "b", b: number }>(t: T) {
+    if (t.kind === "a") {
+        const { kind, ...r1 } = t;
+        const r2 = (({ kind, ...rest }) => rest)(t);
```
Comment (gabritto) [inline tests/cases/compiler/narrowingDestructuring.ts:30]: That's an inconsistency that was already present. We have:
`r1 : Omit<T, "kind">`, but `r2 : { a: string; }`.

File: src/compiler/checker.ts [hunk 5]
```diff
@@ -8579,7 +8586,8 @@ namespace ts {
 
         /** Return the inferred type for a binding element */
         function getTypeForBindingElement(declaration: BindingElement): Type | undefined {
-            const parentType = getTypeForBindingElementParent(declaration.parent.parent);
+            const checkMode = declaration.dotDotDotToken && declaration.parent.kind !== SyntaxKind.ArrayBindingPattern ? CheckMode.ObjectRestBindingElement : CheckMode.Normal;
```
Comment (gabritto) [inline src/compiler/checker.ts:8589]: I assumed here we only want this special rest behavior for rest elements in *object* binding patterns, but maybe we also want it for array rest elements too.

**Comment by gabritto** [comment]
@typescript-bot perf test this

**Comment by orta** [comment]
@typescript-bot perf test this

**Comment by gabritto** [comment]
@typescript-bot pack this

File: src/compiler/checker.ts [hunk 6]
```diff
@@ -175,12 +175,16 @@ namespace ts {
...
+        Normal = 0,                        // Normal type checking
+        Contextual = 1 << 0,               // Explicitly assigned contextual type, therefore not cacheable
+        Inferential = 1 << 1,              // Inferential typing
+        SkipContextSensitive = 1 << 2,     // Skip context sensitive function expressions
+        SkipGenericFunctions = 1 << 3,     // Skip single signature generic functions
+        IsForSignatureHelp = 1 << 4,       // Call resolution for purposes of signature help
+        RestBindingElement = 1 << 5,       // Checking a type that is going to be used to determine the type of a rest binding element
+                                           //   e.g. in `const { a, ...rest } = foo`, when checking the type of `foo` to determine the type of `rest`,
+                                           //   we need to preserve generic types instead of substituting them for constraints
+        IncludeOptionality = 1 << 6,       // >> TODO: description, replace bool param with flag
```
Comment (gabritto) [inline src/compiler/checker.ts:187]: I'll add this flag instead of the `includeOptionality` parameter in another commit, once we settle on the other changes of this PR

**Comment by RyanCavanaugh** [comment]
@ahejlsberg any concerns? 4.6 RC is fast approaching and we'd like to have this in

File: src/compiler/checker.ts [hunk 7]
```diff
@@ -33711,10 +33727,16 @@ namespace ts {
                 isJSDocTypeAssertion(node);
         }
 
-        function checkDeclarationInitializer(declaration: HasExpressionInitializer, contextualType?: Type | undefined) {
+        function checkDeclarationInitializer(
+            declaration: HasExpressionInitializer,
+            checkMode: CheckMode | undefined,
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:33732]: Just make this `checkMode: CheckMode` and pass `CheckMode.Normal` instead of `undefined`.

File: src/compiler/checker.ts [hunk 8]
```diff
@@ -8456,9 +8460,12 @@ namespace ts {
...
         // Return the type of a binding element parent. We check SymbolLinks first to see if a type has been
         // assigned by contextual typing.
-        function getTypeForBindingElementParent(node: BindingElementGrandparent) {
+        function getTypeForBindingElementParent(node: BindingElementGrandparent, checkMode: CheckMode | undefined) {
+            if (checkMode && checkMode !== CheckMode.Normal) {
+                return getTypeForVariableLikeDeclaration(node, /*includeOptionality*/ false, checkMode);
+            }
             const symbol = getSymbolOfNode(node);
-            return symbol && getSymbolLinks(symbol).type || getTypeForVariableLikeDeclaration(node, /*includeOptionality*/ false);
+            return symbol && getSymbolLinks(symbol).type || getTypeForVariableLikeDeclaration(node, /*includeOptionality*/ false, checkMode);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:8468]: Yeah, we should definitely fold the `includeOptionality` into `CheckMode`.

File: src/compiler/checker.ts [hunk 9]
```diff
@@ -8690,11 +8698,15 @@ namespace ts {
         }
 
         // Return the inferred type for a variable, parameter, or property declaration
-        function getTypeForVariableLikeDeclaration(declaration: ParameterDeclaration | PropertyDeclaration | PropertySignature | VariableDeclaration | BindingElement | JSDocPropertyLikeTag, includeOptionality: boolean): Type | undefined {
+        function getTypeForVariableLikeDeclaration(
+            declaration: ParameterDeclaration | PropertyDeclaration | PropertySignature | VariableDeclaration | BindingElement | JSDocPropertyLikeTag,
+            includeOptionality: boolean, // >> TODO: change this to use a flag in check mode; figure out how this interacts with caching
+            checkMode: CheckMode | undefined,
```
Comment (ahejlsberg) [inline src/compiler/checker.ts:8704]: Again, just `checkMode: CheckMode` and use `CheckMode.Normal` as appropriate.

**Review by ahejlsberg — CHANGES_REQUESTED** [review]
Looks good in general, but would like to see a few changes first.

File: src/compiler/checker.ts (hunk 6 above)
Comment (gabritto) [reply src/compiler/checker.ts:187]: Since replacing the `includeOptionality` by a `CheckMode` flag affects our caching behavior in `checkExpressionCached` (or we'll have to add an exception for that flag only), I'm gonna merge this without that part for the 4.6 RC, and I can add this change in another PR if we really want this.
