### PR TITLE
Preserve literal types in contextual unions

### LINKED ISSUE #16457: Refine unions in contextual typing
Source issue #16450 and others (TODO: find them)

This code should work, but doesn't:
```ts
interface X {
    type: 'x';
    value: string;
}

interface Y {
    type: 'y';
    value: 'none' | 'done';
}

function foo(bar: X | Y) { }

foo({
    type: 'y',
    value: 'done',
});
```

Similar example:
```ts
interface X {
    type1: 'x';
    value: string;
}

interface Y {
    type2: 'y';
    value: 'none' | 'done';
}

function foo(bar: X | Y) { }

foo({
    type2: 'y',
    value: 'done',
});
```

We can, in principle, make this work by discarding `X` from the union.

In the first example, this can be done (somehow) by using the discriminating union from the object literal.

In the second example, this can be done by noting that we have a fresh object literal type (meaning there are known to be no additional properties) and a missing `type1` property.

### LINKED ISSUE #19837: Fails to get contextual type for string literal in array
**TypeScript Version:**  2.7.0-dev.20171108

**Code**

```ts
const x: 'a' | 'a'[] = ['a'];
```

**Expected behavior:**

No error.

**Actual behavior:**

```
src/a.ts(1,7): error TS2322: Type 'string[]' is not assignable to type '"a" | "a"[]'.
  Type 'string[]' is not assignable to type '"a"[]'.
    Type 'string' is not assignable to type '"a"'.
```

Was broken by #19733 -- verified by testing with its merge commit and with the previous commit. @weswigham 
Detected by running DefinitelyTyped tests.

### PR DESCRIPTION
**Pull request by weswigham**
Fixes #16457, replaces #19587, in which this code started getting reviewed.

Adds a test for #20279.
Also fixes #19837.
Also fixes #16457.

### CODE REVIEW

**Comment by weswigham** [comment]
@ahejlsberg I've updated this for post-dynamic-names merge; would you like to take a look over it again so we can merge and fix #19837 and #16457?

File: src/compiler/checker.ts [hunk 1]
```diff
@@ -18856,24 +18857,30 @@ namespace ts {
 
         function checkDeclarationInitializer(declaration: VariableLikeDeclaration) {
             const type = getTypeOfExpression(declaration.initializer, /*cache*/ true);
+            return shouldUseLiteralType(declaration) ? type : getWidenedLiteralType(type);
+        }
+
+        function shouldUseLiteralType(declaration: VariableLikeDeclaration) {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: `shouldKeepLiteralType` may be a better name since it only matters if you already have a literal type.

File: src/compiler/checker.ts [hunk 2]
```diff
@@ -4306,9 +4306,10 @@ namespace ts {
             if (strictNullChecks && declaration.initializer && !(getFalsyFlags(checkExpressionCached(declaration.initializer)) & TypeFlags.Undefined)) {
                 type = getTypeWithFacts(type, TypeFacts.NEUndefined);
             }
-            return declaration.initializer ?
+            type = declaration.initializer ?
                 getUnionType([type, checkExpressionCached(declaration.initializer)], /*subtypeReduction*/ true) :
                 type;
+            return shouldUseLiteralType(declaration) ? type : getWidenedLiteralType(type);
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: What are the cases that are affected by this change?

File: src/compiler/checker.ts [hunk 3]
```diff
@@ -18856,24 +18857,30 @@ namespace ts {
...
+        function shouldUseLiteralType(declaration: VariableLikeDeclaration) {
             return getCombinedNodeFlags(declaration) & NodeFlags.Const ||
-                (getCombinedModifierFlags(declaration) & ModifierFlags.Readonly && !isParameterPropertyDeclaration(declaration)) ||
-                isTypeAssertion(declaration.initializer) ? type : getWidenedLiteralType(type);
+                getCombinedModifierFlags(declaration) & ModifierFlags.Readonly && !isParameterPropertyDeclaration(declaration) ||
+                (declaration.initializer && isTypeAssertion(declaration.initializer));
         }
 
-        function isLiteralLikeContextualType(contextualType: Type) {
+        function isLiteralLikeContextualType(candidateLiteral: Type, contextualType: Type): boolean {
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: `isLiteralOfContextualType`

File: src/compiler/checker.ts [hunk 4]
```diff
@@ -18856,24 +18857,30 @@ namespace ts {
...
-                    contextualType = constraint;
-                }
-                return maybeTypeOfKind(contextualType, (TypeFlags.Literal | TypeFlags.Index | TypeFlags.UniqueESSymbol));
+                    return isLiteralLikeContextualType(candidateLiteral, constraint);
+                }
+                // No need to `maybeTypeOfKind` on the contextual type, as it can't be a union, _however_, `candidateLiteral` might still be one!
+                return !!(((contextualType.flags & TypeFlags.StringLike) && maybeTypeOfKind(candidateLiteral, TypeFlags.StringLike)) ||
+                    ((contextualType.flags & TypeFlags.NumberLike) && maybeTypeOfKind(candidateLiteral, TypeFlags.NumberLike)) ||
+                    ((contextualType.flags & TypeFlags.BooleanLike) && maybeTypeOfKind(candidateLiteral, TypeFlags.BooleanLike)) ||
+                    ((contextualType.flags & TypeFlags.ESSymbolLike) && maybeTypeOfKind(candidateLiteral, TypeFlags.ESSymbolLike))
```
Comment (ahejlsberg) [inline src/compiler/checker.ts]: Why all the extra parentheses?

Comment (weswigham) [reply src/compiler/checker.ts]: Old habit; I tend to add parens around any inner binary expression since internalizing operator precedence beyond simple PEMDAS isn't something I, personally, bother to think about. They're gone now~

File: src/compiler/checker.ts (hunk 2 above)
Comment (weswigham) [reply src/compiler/checker.ts]: You can see the changes at https://github.com/weswigham/TypeScript/pull/1/files

**Comment by weswigham** [comment]
@ahejlsberg Ran DT tests - Fixes 7 instances of #19837, and changes the error text of 4 tests to include or not include literals as appropriate for the new rules, same as RWC (introducing no new errors).

**Comment by mhegazy** [comment]
@weswigham we had an offline discussion today as a result of https://github.com/Microsoft/TypeScript/issues/20279. the main cause of the memory load is generating unions of literal types and doing sub-type reduction on them. the inclusion of this change exasperates the issue further. 

@ahejlsberg has a change to limit the inference of literal types to only when the contextual type has a literal type from the same family, and that seems to alleviate the issue for these large json-like arrays/objects with a contextual type. but obviously this is going the opposite direction of this PR. 

I now believe your original proposal for including the literal type in the contextual type is a better approach, and we should go with that instead. @ahejlsberg seems to have changed his mind on that issue as well after looking into https://github.com/Microsoft/TypeScript/issues/20279.

**Comment by weswigham** [comment]
> I now believe your original proposal for including the literal type in the contextual type is a better approach, and we should go with that instead. @ahejlsberg seems to have changed his mind on that issue as well after looking into #20279.

Done.

> @ahejlsberg has a change to limit the inference of literal types to only when the contextual type has a literal type from the same family, and that seems to alleviate the issue for these large json-like arrays/objects with a contextual type. but obviously this is going the opposite direction of this PR.

I couldn't find a PR for that, so I built it into this one, since it was a smallish change in the same place as I've been working in here. I'll add a test for #20279 hopefully shortly.

**Comment by weswigham** [comment]
I've added a test for #20279 and confirmed that with the proposed tweaks, this fixes it.

**Comment by weswigham** [comment]
@ahejlsberg This has now been merged with master and is _just_ the change for preserving literal types in unions generated via contextual typing.

**Comment by weswigham** [comment]
@ahejlsberg `getUnionType` now uses a tristate for determing the level of subtype reduction to apply, per your request. Available are `None`, `Literal`, and `Subtype`.
