### ISSUE TITLE
Binding element 'any' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by wallverb** [Microsoft/TypeScript#9657]
**TypeScript Version:**  Version 2.1.0-dev.20160712

**Code**

```ts
function test({a:any}) {
	
}
```

**Expected behavior:**
Should compile with `--noImplicitAny` (compiles fine with 1.8.0)

**Actual behavior:** 
error TS7031: Binding element 'any' implicitly has an 'any' type.

**Comment by mhegazy** [comment]
this is not a type annotation, this is a rename for the destructured propeortes. Please see http://www.typescriptlang.org/docs/handbook/variable-declarations.html#property-renaming

what you want is:

```ts
function test({a} : { a: any}) {

}
```

**Comment by wallverb** [comment]
Shouldn't it be bug for 1.8 then ?

**Comment by mhegazy** [comment]
> Shouldn't it be bug for 1.8 then ?

I am sure there was one logged, could not find it. it should be fixed in latest `typescript@next` as well as `typescript@2.0.0`

**Comment by StoneCypher** [comment]
I feel like a stronger error message should be emitted here.  I don't think many people will easily find this.
