### ISSUE TITLE
`This condition will always return 'false'` (2367) error no longer appears on template literal types with keyword types

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript#45201]
# Bug Report

### 🔎 Search Terms

This condition will always return 'false'

### 🕗 Version & Regression Information

- This changed between versions 4.2.3 and 4.3.5

### ⏯ Playground Link

- [not working in 4.4.0-dev.20210727](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210727#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAAa5IAkA3igK4C2ARiDAL5EBQp8AvD-AOT1YfeAHoR8FEnhMYSGNIBuIFPAwALJNQDma1QE8ADiDTxYCAJYpktA1Azn6EEGzbJ0WQTEIk8lGgyZWbn5PYTEZOUIAFUMEPgAiT3jhcxNJLCg0NHMtFChHBAwpDFj+H3IqOkYWIj4gA)
- [working in 4.2.3](https://www.typescriptlang.org/play?ts=4.2.3#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAAa5IAkA3igK4C2ARiDAL5EBQp8AvD-AOT1YfeAHoRTGEhiEAKgE8ADgj4AiQTBXCAlmngokWKGjRaA5iij0ICDEngZFyknko0GTVnzZtk6LOsJncio6RhYibn51YTEJKVlHfjVYTXgdPQN4IxNzS2t7OwclfiDXUI8iPiA)

### 💻 Code

```ts
declare const foo: `foo${number}`
foo === 'bar' // no error even though types are incompatible

const bar: `foo${number}` = 'bar' //error: Type '"bar"' is not assignable to type '`foo${number}`'
```

### 🙁 Actual behavior

no error when comparing the incompatible types

### 🙂 Expected behavior

the same error that occurs when you do the same thing in typescript <=4.2.3
```
This condition will always return 'false' since the types '`foo${number}`' and '"bar"' have no overlap.(2367)
```

**Comment by DetachHead** [comment]
looks like this is fixed in 4.5
