### ISSUE TITLE
JSDoc does not parse type *= correctly

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript#19985]
**TypeScript Version:**  2.7.0-dev.201xxxxx

**Code**

```ts
  /**
   * @override
   * @param {symbol} eventType
   * @param {*=} eventData
   */
  dispatchEventToListeners(eventType, eventData) {
    if (!this._listeners || !this._listeners.has(eventType))
      return;

    var event = /** @type {!Common.Event} */ ({data: eventData});
    var listeners = this._listeners.get(eventType).slice(0);
    for (var i = 0; i < listeners.length; ++i)
      listeners[i].listener.call(listeners[i].thisObject, event);
  }
```

**Expected behavior:**
No errors, type for `eventData` is `any | undefined`.

**Actual behavior:**
```
front_end/common/Object.js(103,14): error TS1110: Type expected.
```
(A parse error on `*=` - a valid jsdoc type (an  arity-optional anything))

**Comment by sandersn** [comment]
This works in 3.6 and higher, at least.
