### ISSUE TITLE
Union types are not being narrowed down correctly in 4.3

### ISSUE THREAD

**Issue by KnorpelSenf** [microsoft/TypeScript#44401]
# Bug Report

Potentially related to #44382.

### 🔎 Search Terms

- union types
- narrowing
- 4.3

### 🕗 Version & Regression Information

- This changed between versions 4.2 and 4.3

### ⏯ Playground Link

[Playground link with relevant code](https://www.typescriptlang.org/play?ts=4.4.0-dev.20210601#code/JYOwLgpgTgZghgYwgAgBrIN4FgBQzlwD8AXJgQApQD2ADqQM5hSgDmyAvgNy74BGJZXpVoMmrDtxztcYAJ40UAQSpQAQsgC8ZOKSq8AVhARhOyXqQCuIACYQYoCNY7IAPtss27D66fPI9hsYSuLi2CAA2cFAoCFQgjMgAjqToAGTIymqSuMAwyAAUiQB0cMgAhBpaVrb2II4AlJg8SSUlwjSS7MgQ4fQo2HjIAPRDLbzIwPQTILFQ0cbhstMw0NFOcFM0VJDgwHDhi8jVXnXWxM3FvEVC1B240jhAA)

### 💻 Code

```ts
interface X {
  a?: { aProp: string };
  b?: { bProp: string };
}
type AorB = { a: object; b: undefined } | { a: undefined; b: object };

declare const q: X & AorB;

if (q.a !== undefined) {
  q.a.aProp;
} else {
  // q.b is incorrectly inferred as potentially undefined:
  q.b.bProp;
}
```

### 🙁 Actual behavior

`q.b` is inferred as potentially undefined in the `else` block. Given that `q` conforms with `AorB`, and `q.a` is known to be undefined in the else block, this is incorrect.

### 🙂 Expected behavior

`q.b` should be inferred as present. In particular, it should be `{ bProp: string }`.

**Comment by KnorpelSenf** [comment]
@RyanCavanaugh is it planned to fix this at some point in the near future? I see you added it to the backlog, but that list contains 2.6K issues and some of them are years old.

If it turns out that this bug will be ignored, then I'd prefer to start looking for workarounds now, and beginning to rewrite a number of TypeScript projects that rely on the old behaviour.

**Comment by RyanCavanaugh** [comment]
@KnorpelSenf barring other people encountering this or other prioritization data appearing, I don't expect it'd be fixed soon unless someone from outside the team wrote a PR (not unlikely but obviously I cannot predict when that might happen)

**Comment by KnorpelSenf** [comment]
Thanks for the quick response, then I'll start looking into workarounds

**Comment by caojoshua** [comment]
Potential fix in #44771 

Regression in [this commit](https://github.com/microsoft/TypeScript/commit/a21f61f746ded34b67a1d6e25ba59ed634dddd0b)

> Potentially related to #44382.

I've found that the regression is not related to this issue.

**Comment by KnorpelSenf** [comment]
As a workaround it is possible to add a superfluous check for `undefined`. (Alternatively, a type cast could be performed.) This is obviously not a satisfying solution.

Naturally, I would much rather have see #44771 merged.

**Comment by denis-sokolov** [comment]
I’ve got another way to reproduce this. Has been fixed by the same fix in #44771, I’m leaving this in case it helps anyone with a similar case find this issue.

Union of an intersection type is not narrowed down after type guards: [Playground](https://www.typescriptlang.org/play?jsx=4&ts=4.3.5#code/C4TwDgpgBAKlC8UDeUAeAuKBnYAnAlgHYDmUAvlAGTJQiY4EnkDcAUKwMYD2hOUxXLgBNMcAD5QARIR4RJCKTMJy2AelX9BQqPixRCAQ1y4uAdwjbgXRbPlEowABbRuhIfmD4eBgDat8AGZQABQCwgjwiNK2AJSawgB0VgCqYJC4AMIGWBDBMWycPHwARgbaUUpyUNmwUBLRypJqGqXauvpcwPpGJuZthA7OUK7unt4+ADRQgDgEKWkQmdnQQlwQejJdEKi6XTwO4NAwgLgE-kHBrREVsVCtSVyp6Vk5eQXq+5BcQWHlke8QnzcypcQuIbI0YuxXHwZABJQjABY5DhjAZXRrVPQoDDYPBEYjMWj0XFMCj1SpNVhvWHwxEQZFeAbtQzGMwWBzWBpVexOFw8UYM3ynELUhG4JEo4GcyRxEW0+k8O4PBZPXL5VhAA)
```ts
type T = { x: string } & { y: string };

const good: T | "none" = "none";
// good is narrowed to "none" in the conditional
if (good === "none") good.toUpperCase();

const bad = "none" as T | "none";
// bad is not narrowed in the conditional, “toUpperCase does not exist on type T”
if (bad === "none") bad.toUpperCase();

// typeof good === typeof bad === (T | "none")

const noIntersection = "none" as { x: string; y: string } | "none";
// noIntersection is narrowed to "none" in the conditional
if (noIntersection === "none") noIntersection.toUpperCase();
```

Worked correctly in 4.2. Works incorrectly on 4.3. Works incorrectly on 4.4.0-dev.20210712. Works correctly on 4.4.0-dev.20210714.
